[STEP1] Jaegeun, Rookie
tasty-code/ios-juice-maker pull request #1
Opened 2022-08-24 01:28 UTC by wormsJJG

@Tacocat-tastycode 
@잼킹

# 수행한 내용
 - 역화을 세분화하여 타입을 생성
 - 주스를 만드는 함수 구현
 - 과일의 재고를 관리하는 함수 구현
# 고민한 내용
이번 프로젝트는 실제로 앱이 구동되는 만큼 좀더 많은 생각을 했습니다.

``` swift
class FruitStore {
    let strawberry = 10
}

```
이렇게 구현하게 되면 fruitStore에서 재고가 빠지고 더해지는 과정까지 맡게 됩니다.
그래서 아래의 코드처럼 과일 따로 재고 따로 타입을 나누었습니다.

``` swift
class Storage {
    private(set) var amount: Int = 10
    
    func minusAmount(_ amount: Int) {
        self.amount -= amount
    }
    
    func addAmount(_ amount: Int) {
        self.amount = amount
    }
}

enum Fruit {
    static let strawberry = Storage()
    static let banana = Storage()
    static let kiwi = Storage()
    static let pineapple = Storage()
    static let mango = Storage()
}
```

2022-08-24 06:36 UTC, jaemuYeo requested changes
안녕하세요 루키 재근!! 스텝1 진행하느라 고생했어요~
이번 코드에서는 타입설계에 대한 부분을 중점으로 보았어요.
아쉬웠던 점들은 타입프로퍼티를 통해 열거형들을 구성했다는 점인데요!🥲
열거형은 정말 다양하게 활용할 수 있는 타입이니 조금 더 학습해보고
각각의 타입에 더 와닿을 수 있는 특성과 행위들을 나열해주었으면 좋겠어요 💪

static프로퍼티 또는 메서드는 메모리 저장방식부터 호출 방식, 사용해야하는 이유들이
있어요! 루키와 재근이 알고있는 static의 특징들도 궁금합니다!

2022-08-24 06:36 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> -        // Do any additional setup after loading the view.
불필요한 주석을 잘 제거해주었군요! 👍
사실 import 위에 있는 주석도 일관성있게 맞춰주면 좋답니다 ㅎㅎ
재근 루키가 생성한 뉴 파일과 기존에 있던 파일을 비교해보고 최신화해보세요~~

2022-08-24 06:36 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
>  // 과일 저장소 타입
불필요한 주석이라고 생각합니다!

2022-08-24 06:36 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> -class FruitStore {
이 클래스의 이름은 왜 변경되었나요??
파일명과 (.swift) 내부에 선언한 객체의 네이밍은 비슷하게 하는것이 좋습니다☺️

2022-08-24 06:36 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func minusAmount(_ amount: Int) {
minus와 add의 네이밍이 조금 와닿지가 않아요! 증가 감소같은 네이밍은 어떤가요?
그리고 매개변수를 통해 amount를 받도록 명시해주었는데 메서드명에 amount가 한 번 더 명시된것 같아요
전치사를 사용하여 조금 더 네이밍을 문장처럼 만들어보면 좋을것 같습니다🙏
실제로 사용될 곳에서의 이음새를 생각해보면 더 쉽게 네이밍을 할 수 있을거예요!

2022-08-24 06:36 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        self.amount = amount
이 친구는 증가되지않고 할당만 하는건가요?

2022-08-24 06:36 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +enum Fruit {
이 친구를 어떻게 사용될지가 궁금하군요 🤔
왜 각각의 과일들이 Strorage의 인스턴스가 되고
static으로 선언되었는지 궁금합니다!

2022-08-24 06:36 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +typealias recipe = (Storage: Storage, amount: Int)
타입별칭을 사용하셨군요!! 정말 좋은 언어의 기능이지만
때로는 가독성에 피해를 끼칠수있기에 명확할때만 사용하길 권장합니다 ㅎㅎ
또한 말그대로 `타입` 별칭인데 네이밍은 변수같군요!!🤔

2022-08-24 06:36 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +class Juice {
쥬스 메이커가 해야할 일을 쥬스라는 객체가 가지고 있다는 생각이 듭니다 🤔
현재처럼 Juice 클래스와 JuiceType 열거형을 따로두지않고
Juice라는 열거형을 통해 쥬스타입에 필요한것들을 나열해보면 어떨까요?
Hint. 연산프로퍼티와 switch-case를 활용해보세요!

### 추가적인 질문입니다!
1. 연산프로퍼티와 메서드는 어떤 차이가 있나요?
2. 연산 프로퍼티의 네이밍도 동사로 시작해야할까요?
3. Bool타입의 네이밍은 어떻게 작성할까요?

2022-08-24 06:36 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +enum JuiceType {
이런 경우 Juice로만 네이밍해주어도 충분합니다 😀

2022-08-24 06:36 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +    static let strawberry = Juice(recipes.strawberry, "딿기주스")
딿기주스 오타요! ㅎㅎ

2022-08-24 06:36 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/JuiceRecipe.swift
> +enum recipes {
타입의 네이밍은 어떻게 해야할까요? 조사해보고 저도 알려주세요 😀
그리고 이 레시피는 쥬스타입에 포함되어있는게 좋지 않을까요??

2022-08-25 00:35 UTC, wormsJJG commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> -        // Do any additional setup after loading the view.
넵 제거 해보겠습니다.!

2022-08-25 00:35 UTC, wormsJJG commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
>  // 과일 저장소 타입
넵

2022-08-25 00:37 UTC, wormsJJG commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> -class FruitStore {
과일 타입과, 스토리지 타입을 따로 만들어 FruitStore는 제거했습니다.
파일과 선언한 객체의 네이밍은 비슷하게 하는것이 좋은것같습니다

2022-08-25 00:37 UTC, wormsJJG commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func minusAmount(_ amount: Int) {
넵

2022-08-25 00:37 UTC, wormsJJG commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        self.amount = amount
넵 활당을 하는 역활입니다. 역활을 본다면 add는 맞지 않는 표현같네요.!

2022-08-25 00:38 UTC, wormsJJG commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +typealias recipe = (Storage: Storage, amount: Int)
별칭은 다시한번 생각해보겠습니다.!

2022-08-25 00:39 UTC, wormsJJG commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +enum JuiceType {
넵

2022-08-25 00:39 UTC, wormsJJG commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +    static let strawberry = Juice(recipes.strawberry, "딿기주스")
넵 수정하였습니다

2022-08-25 00:41 UTC, wormsJJG commented on JuiceMaker/JuiceMaker/Model/JuiceRecipe.swift
> +enum recipes {
타입의 네이밍은 대문자의 명사로 시작하고, pascal casing을 사용한다고 하네요!

2022-08-25 00:47 UTC, wormsJJG commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +class Juice {
1. 연산프로퍼티는 접근자만 구현해서 읽기 전용 상태 구현이 쉽습니다. 그리고 연산 프로퍼티는 쓰기 전용 상태로는 구현이 불가능합니다.
2. 동사로 시작하거나 is로 시작하는게 맞을 것같습니다.
3. Bool타입의 네이밍을 공부해보니 각언어의 컨벤션에 마다 다르지만 swift에서는 is를 써주는 것이 컨벤션이라고 합니다.

2022-08-30 06:21 UTC, jaemuYeo requested changes
수정한 코드 확인했습니다!!
한 가지 말씀드리고 싶은건 커밋 메시지에 PR반영, 리뷰반영 등으로 기록해두었는데
수정이 이루어지는 과정또한 여러분들의 컨벤션에 맞게 해주었으면 좋겠어요!!
커밋도 코드 작성과 마찬가지로 하나하나 신중하게 해야합니다 🙂
재요청을 받고서 어디가 수정된건가 많이 헤메었어요 ㅠ_ㅠ
커밋로그가 하나로 퉁쳐서 되었거나 재요청시 처음 PR보낼때처럼 코멘트를 남겨주지 않으면
제가 할 수 있는건 전의 코드와 현재코드를 둘다 보면서 비교하는 행위를 할 수 밖에 없습니다,,

---

현재 코드가 의도와 조금은 멀어졌다 생각하는데
그 이유를 생각해보니 초반에 가이드해놨던 JuiceMaker, FruitStore 타입을 활용하지않고
새로운 타입을 만들게되면서 인 것 같아요!
FruitStore 타입은 아예 사라져버렸군요 ㅎㅎ
한 번 다시 가이드라인을 잡아줄테니 해볼수 있을까요??

---
JuiceMaker는 내부에 Juice를 가진다
Juice는 쥬스종류를 나열하고 이름과 레시피를 가진다
JuiceMaker는 쥬스를 재조할 수 있다

FruitStore 타입은 내부에 Fruit를 가진다
Fruit는 과일종류를 나열한다
FruitStore는 과일의 초기값을 10으로 설정해주고 과일 재고를 증가 또는 감소할 수 있다

---

또한 의문점은 static을 활용한 특성들을 정의한 것인대요~
static을 활용할때는 어떤 경우인지 알아보고 지양해주었으면 해요!🤔

2022-08-30 06:21 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> -class FruitStore {
FruitStore타입과 JuiceMaker타입은 활용해보라고 선언해둔 것이었습니다 😀

2022-08-30 06:21 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func minusAmount(_ amount: Int) {
네이밍은 그대로 진행되는 걸까요?

2022-08-30 06:21 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +typealias recipe = (Storage: Storage, amount: Int)
말그대로 `타입`별칭이니 UpperCamelCase로 지어보세요~

2022-08-30 06:21 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +    enum Recipes {
이전 코멘트에 대한 답변으로 명사로 지어야한단 답변을 달아주었는데
복수형을 그대로 사용하셨네요 😀

2022-08-30 06:21 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +        static let strawberry = Juice(Recipes.strawberry, "딿기주스")
여기 오타가 그대로 있군요 ㅎㅎ

2022-08-30 07:12 UTC, chaeyoon1101 commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +    enum Recipes {
수정을 했었는데 브랜치가 꼬여서 수정이 안된 것 같습니다 다시 수정해보겠습니다

2022-08-30 07:12 UTC, chaeyoon1101 commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +        static let strawberry = Juice(Recipes.strawberry, "딿기주스")
다시 수정하겠습니다

2022-09-01 02:59 UTC, jaemuYeo reviewed
재근 루키 스텝1 진행하느라 고생많았습니다 👏
머지진행할게요!!

2022-09-01 02:59 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    init() {
모델을 구현할때는 내부적으로 값을 주지않고 외부에서 값을 주는 것이 좋다고 생각해요 :)
init에도 매개변수 활용할 수 있는데 외부에서 값을 받을 수 있도록 해볼수 있을까요?

2022-09-01 02:59 UTC, merged