쥬스 자판기 [STEP 2] 이안,유니
tasty-code/ios-juice-maker pull request #100
Opened 2023-12-14 08:33 UTC by ianK0909

@ryan-son

안녕하세요 이안,유니 입니다
쥬스만들기 STEP2 작업완료 후 PR 올립니다.

<h3>PR Point</h3>

extension UIViewController 에 얼럿을 정의하고 , 상황별 적절한 메시지를 보여주게 구현했습니다.

<h3>궁금한 점</h3>

- 라벨은 하나하나 구현과 연결을 해주었는데요. 라벨도 버튼처럼 컬렉션을 사용해서 구현하면 코드를 줄일수있을 꺼같은데 하는방법을 모르겠습니다. 라벨처럼 하나하나 구현 및 연결을 해주는게 좋은방법인가요?? 버튼처럼 컬렉션을 사용해 한번에 연결을 해주는게 좋은방법인가요??
- 화면전화 방식이 모달,네비게이션 방식이 있는데 어떤 상황에서 모달이나, 네비게이션 화면전화방식을 선택해야될까요? 
- 현재 싱글톤 방식을 사용하고있습니다. 싱글톤 방식에서 재고 갱신 방법은  ```viewWillAppear()```  을 사용하면 재고 갱신이 가능한데요. 화면전화방식을 Modality로 바꾸면 ```viewWillAppear()``` 을 사용할수없게되면서 새로운 방식을 생각해야되는데 어느 방식이 좋을까요?

2023-12-14 18:02 UTC, ryan-son requested changes
유니, 이안, Step 2 수행하시느라 고생 많으셨습니다.
Step 1과 같이 본문에 남겨주신 질문만 짚고 자세한 사항은 코드에 코멘트 달아둘게요~

>라벨은 하나하나 구현과 연결을 해주었는데요. 라벨도 버튼처럼 컬렉션을 사용해서 구현하면 코드를 줄일수있을 꺼같은데 하는방법을 모르겠습니다. 라벨처럼 하나하나 구현 및 연결을 해주는게 좋은방법인가요?? 버튼처럼 컬렉션을 사용해 한번에 연결을 해주는게 좋은방법인가요??

- 구현의 양이 적은 것이 꼭 좋다고 할 수는 없는 것과 마찬가지로 Interface Builder에서 IBOutlet을 하나씩 연결해주는 방식과 IBOutlet collection을 만드는 방법 모두 장단이 있어 어떤 방법이 더 좋다고 하기는 어렵습니다. 구현하는 여러분의 취향이 포함되는 것이니 아래의 장단을 살펴보고 결정해보시면 좋겠습니다.
1. 하나씩 인터페이스를 마련하면 구현의 양은 많을 수 있으나 배열에 index로 접근하는 구현이 없으므로 코드가 명시적이고 런타임 에러가 일어날 가능성이 적습니다.
2. 묶음 형식의 IBOutlet collection을 사용하면 구현의 양은 적을 수 있으나 배열의 index에 각각 어떠한 요소가 포함되었는지를 참조할 수 있는 인스턴스 또는 메서드를 정의하여야하며 유효하지 않은 index로 배열에 접근하는 것을 방지하기 위해 방어 로직을 마련하여야 합니다.

>화면전화 방식이 모달,네비게이션 방식이 있는데 어떤 상황에서 모달이나, 네비게이션 화면전화방식을 선택해야될까요?

- 제가 답변드리기 전에 아래 문서를 읽어보고, iOS에서 기본적으로 제공하는 앱들에서는 어떠한 기능에 어떠한 화면 전환 방식을 이용하였는지, 그리고 왜 그랬을지 생각해보신 후에 이야기 나눠보면 더 좋을 것 같습니다.
- [Modality - Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/modality)

> 현재 싱글톤 방식을 사용하고있습니다. 싱글톤 방식에서 재고 갱신 방법은 viewWillAppear() 을 사용하면 재고 갱신이 가능한데요. 화면전화방식을 Modality로 바꾸면 viewWillAppear() 을 사용할수없게되면서 새로운 방식을 생각해야되는데 어느 방식이 좋을까요?

- 싱글톤 패턴을 이용했기 때문에 viewWillAppear 호출에 의존하는 로직 구성이 가능한건가요?
- 모달 형식으로 화면 전환을 했을 때 덮인 화면이 viewWillAppear 호출될 수 있는지를 먼저 알아보시면 좋을 것 같네요. 어떤 방식으로 화면 전환시킬지는 그 이후에 결정해보시면 좋겠습니다. 아래 문서와 문서에 등장하는 키워드로 알아보시면 됩니다.
- [UIModalPresentationStyle - Apple Developer](https://developer.apple.com/documentation/uikit/uimodalpresentationstyle)

2023-12-19 07:11 UTC, ianK0909 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    }
문자열보간법으로 변경하면 String으로 변경되는과정이 필요없이 바로 String 적용할수있어서 더 편한거같습니다.

2023-12-19 07:12 UTC, ianK0909 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    }
싱글톤을 사용하지않는 방법으로 리팩토링 하였습니다.

2023-12-19 07:13 UTC, ianK0909 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        }
Tag에 Index를 부여하는 방식으로 변경하였고, 네임스페이스를 사용하여 Tag를 읽기 쉽게 변경하였습니다.

2023-12-19 07:20 UTC, Jin0Yun commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    }
1.예상치못한 에러에 대해서도 알랏창 띄워서 사용자가 에러임을 확인할 수 있게 수정하였습니다.
```swift
func order(juice: Juice) {
            do {
                try juiceMaker.make(juice: juice)
                print("\(juice.name) 나왔습니다.")
                showAlert(title: "완성", message: "\(juice.name) 나왔습니다! 맛있게 드세요")
                setInitialFruitLabel()
            } catch let error as JuiceMakerError {
                juiceMakeErrorCase(error)
            } catch {
                print("알 수 없는 에러")
                showAlert(title: "에러", message: "예상치 못한 에러가 발생했습니다.")
            }
        }
```
2. 에러에 대한 처리를 메서드로 분리해 에러케이스별로 알럿을 보여줄 수 있게 수정하였습니다.
```swift
        private func juiceMakeErrorCase(_ error: JuiceMakerError) {
            switch error {
            case .outOfStock(_):
                print("\(error.message)")
                showAlertWithConfirmation(title: "재고부족", message: "\(error.message)") { _ in
                    self.performSegue(withIdentifier: "InventoryView", sender: self)
                }
            case .negativeAmount(_):
                print("\(error.message)")
                showAlert(title: "에러", message: "\(error.message)")
            }
        }
```

2023-12-19 07:22 UTC, ianK0909 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
>      }
두번째 과일까지 확인한 후 과일을 소모할수있게 변경하였습니다.

2023-12-20 17:49 UTC, ryan-son approved these changes
이안, 유니! Step 2 수행하시느라 고생 많으셨습니다. 추가 코멘트를 남겨두었으니 참고해보시고 필요하시다면 다음 스텝의 PR 전에 반영해보시면 좋겠습니다. 그럼 다음 스텝에서 뵙겠습니다!

2023-12-20 17:49 UTC, ryan-son commented on JuiceMaker/JuiceMaker/Controller/OrderJuiceViewController.swift
> +            setInitialFruitLabel()
setInitialFruitLabel 메서드를 이곳에서 재사용할 계획이시라면 initial이라는 의미를 제거하고 현재 재고 수량으로 갱신한다는 의미로 이름을 지어줄 수 있을 것 같습니다!

2023-12-20 17:49 UTC, ryan-son commented on JuiceMaker/JuiceMaker/Controller/OrderJuiceViewController.swift
> +            juiceMakeErrorCase(error)
메서드 네이밍 규칙에 따라 에러를 처리한다는 의미로 handleJuiceMakerError(_:)로 이름 지어줄 수 있을 것 같습니다.

2023-12-20 17:49 UTC, ryan-son commented on JuiceMaker/JuiceMaker/Controller/OrderJuiceViewController.swift
> +            showAlert(title: "에러", message: "\(error.message)")
열거형 인스턴스에서 나온 연관값도 에러 메시지에 포함시켜준다면 에러를 맞딱뜨렸을 때 이해와 디버깅이 더 용이해질 것 같습니다.

2023-12-20 17:49 UTC, ryan-son commented on JuiceMaker/JuiceMaker/Extension/Alert.swift
> +    func showAlertWithConfirmation(title: String, message: String, action: ((UIAlertAction) -> Void)? = nil) {
이 메서드의 action 파라미터는 '예'를 선택했을 때 액션이므로 매겨변수 이름을 confirmationAction으로 지어줄 수 있을 것 같습니다.

2023-12-20 17:49 UTC, ryan-son commented on JuiceMaker/JuiceMaker/Extension/Alert.swift
> +        alertController.addAction(UIAlertAction(title: "아니오", style: .destructive, handler: nil))
destructive는 일반적으로 삭제와 같이 데이터 복구가 불가능하거나 어려운 상태에 사용하는 경우가 많습니다. 이러한 세부적인 사항들이 궁금해지실 때는 Human Interface Guidelines를 살펴보시면 좋습니다.
- [Buttons/Roles - Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/buttons#Role)

2023-12-20 17:49 UTC, ryan-son commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
'최초 모든 과일의 수량이 10개이다'라는 요구사항이 변경되었을 때 유연하게 대응할 수 있도록 fruitInventory 인스턴스를 이니셜라이저를 통해 전달받되 초기값을 설정해서 번거로움을 줄여보는 건 어떨까요?

2023-12-20 17:49 UTC, ryan-son commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
>          }
에러를 확인하고 작업을 수행하기보다 JuiceMaker는 소비하는 행동에만 집중하고, 에러를 확인하는 건 FruitStore에서 수행해보는 건 어떨까요?

2023-12-20 17:49 UTC, ryan-son commented on JuiceMaker/JuiceMaker/Model/TagNameSpace.swift
> +}
이 내용은 사용되는 JuiceMakerViewController 내부에 선언하되 해당 ViewController 외부에서의 소요가 없으므로 접근 제한을 걸어주는 건 어떨까요?

2023-12-20 17:49 UTC, merged