쥬스자판기 [Step3] Sidi, Easy
tasty-code/ios-juice-maker pull request #105
Opened 2023-12-19 07:41 UTC by jus1234

리뷰어: @cherrishRed
버드: Sidi, Easy

레드 안녕하세요!
쥬스자판기 프로젝트 STEP 3 PR 드려요!

### STEP 3를 진행하며 고민한 내용

**모달과 화면 사이의 생명주기**

처음 화면 전환 방식을 모달로 변경했을 때 모달이 닫히면 기존 화면의 `viewWillApear`가 실행되는 줄 알았습니다. 하지만 모달의 경우 닫혔을 때 기존 화면에서 `viewWillApear` 가 실행되지 않는 문제를 발견했습니다. 이 문제를 아래와 같은 클로져 전달 방식으로 해결했습니다.

```swift
class JuiceOrderingViewController {
  // 기존화면 viewController
  func presentFruitStockViewController() {
    guard let secondVC = storyboard?.instantiateViewController(withIdentifier: FruitStockViewController.className) as? FruitStockViewController else { return }
    secondVC.onDismissal = self.configureFruitStoreUI
    self.present(secondVC, animated: false)
  }
}

class FruitStockViewController {
  // 모달 화면 viewController
  var onDismissal: (() -> Void)?
  
  func dismissFruitStockViewController() {
    onDismissal?()
    self.dismiss(animated: false)
  }
} 
```

문제를 해결했지만 이후 모달이라도 `.fullScreen`스타일인 경우 `dismiss` 시 기존 화면에서 `viewWillApear`가 호출된다는 것을 알게되고 다시 수정 하였습니다.

```swift
class JuiceOrderingViewController {
  override func viewWillAppear(_ animated: Bool) {
    super.viewWillAppear(animated)
    configureFruitStoreUI()
  }

  func presentFruitStockViewController() {
    guard let secondVC = storyboard?.instantiateViewController(withIdentifier: FruitStockViewController.className) as? FruitStockViewController else { return }
    secondVC.modalPresentationStyle = .fullScreen
    self.present(secondVC, animated: false)
  }
}
```

**stepper 커스터마이징**

`stepper`가 눌렸을 때 +, - 중 어느것이 눌렸는지 판단하는 방법을 고민하던 중 `stepper`의 `value`가 변화한다는 것을 활용해 보면 좋겠다는 생각을 했습니다. 그래서 변화를 감지하는 속성 감시자를 활용해보면 어떨까 싶어 `UIStepper`를 상속을 한 새로운 `class`를 만드는 방법으로 시도를 해보았습니다. 시도 코드는 아래와 같습니다.

```swift
class FruitStockStepper: UIStepper {
    var tappedSign: Sign = .none
    
    override var value: Double {
      didSet {
          tappedSign = value > oldValue ? .plus : .minus
      }
  }
}
```

하지만 스테퍼가 눌려 `value`가 변화 하더라도 속성 감시자는 실행되지 않았습니다. 원인을 알아본 결과 사용자가 UI에서 스테퍼를 조작하여 값이 변경되면 내부적으로는 `UIStepper`의 내장 동작이 발생하며, 이는 `KVO(Key-Value Observing)`를 사용한다는 것을 알게 되었습니다. 이후 `addTarget`으로 `valueChanged` 시 함수를 실행하는 방식으로 변경하였습니다.

```swift
class FruitStockStepper: UIStepper {
    
    var tappedSign: Sign = .none
    var oldValue: Double = 0.0
    
    override var value: Double {
        didSet {
            tappedSign = value > oldValue ? .plus : .minus
        }
    }
    
    override init(frame: CGRect) {
        super.init(frame: frame)
        setAddTarget()
    }
    
    required init?(coder: NSCoder) {
        super.init(coder: coder)
        setAddTarget()
    }
    
    private func setAddTarget() {
        addTarget(self, action: #selector(valueChanged), for: .valueChanged)
    }
    
    @objc private func valueChanged() {
        tappedSign = value > oldValue ? .plus : .minus
        oldValue = value
    }
}
```

### 클래스 다이어그램
![클래스다이어그램](https://github.com/tasty-code/ios-juice-maker/assets/47639904/82a7b7c0-f8c8-4693-b3d0-70f71ca67740)

2023-12-19 18:27 UTC, cherrishRed requested changes
Sidi, Easy 두분 모두 수고 많으셨습니다!

구현하신 내용 모두 잘 확인했습니다.
전반적으로 너무 잘 작성하셨습니다 👏🏻👏🏻👏🏻

크게 수정하셨으면 하는 부분이 한가지 있습니다. 

지금 두가지 뷰에서 데이터의 싱크가 너무 잘맞고 있습니다. 
재고 수정 화면에서 재고를 바꾸면, 닫기 버튼을 누르기 전에 사실상 재고가 수정되고 있죠. 이부분을 닫기 버튼을 누를 때, 재고를 한번에 수정하는 것으로 바꿔 보는 것을 추천 드립니다. 

저장을 하는 케이스 저장을 하지 않는 케이스가 있는 거죠. 

저장, 닫기 이렇게 버튼을 추가하셔도 좋고, 아니면 모달 스타일로 (full screen 이 아닌 손으로 내릴 수 있는) 스타일로 만드셔도 되고, 아니면, 그냥 지금 있는 ui 에서 내부만 그렇게 수정하셔도 됩니다. 

**🍑 모달과 화면 사이의 생명주기**
생명주기에 대해서 공부하시고 고민하신 흔적이 아주 인상깊었습니다!

결국 viewWillAppear 에 넣는 방법을 사용하셨네요.
좋습니다. 실제로는 closure로 사용하기도 하고, 생명 주기에 넣기도 합니다. 

그런데, 지금 처음 뷰를 로드 할 때, 
viewDidLoad 도 호출이 되고, viewWillAppear 도 호출이 되기 때문에, 똑같은 메서드가 두번 실행이 되게 되네요. 이걸 피할 방법은 없을까요?

**🍑 stepper 커스터마이징** 
stepper에 대해서 아주 깊게 공부를 하셨군요. KVO 까지 정말 이번 step 에 많은 도움이 되셨을 것 같습니다. 

그런데, 지금 구현된 가능들은, 충분히 이미 UIStepper 가 가지고 있는 기능 같습니다. 값들은 stepper 내부가 아닌, viewController 나 viewModel 에서 제어 할 수 있도록 수정을 해보면 좋을 것 같습니다. 

**🍑 다이어그램**
다이어그램은 너무 잘 그리셨습니다!

2023-12-21 06:23 UTC, jus1234 commented on JuiceMaker/JuiceMaker/Controller/FruitStockStepper.swift
> +    }
UIView 를 상속받아서 생성자를 사용하려고 하면 requried init?(coder: NSCoder) 를 작성해야 합니다. xib 나 스토리보드에서 생성이 될때에는 init(coder: NSCoder)를 통해서 객체가 생성됩니다!

2023-12-21 07:04 UTC, yoruck2 commented
닫기 버튼을 누를 때, 재고를 한번에 수정하는 것으로 만들어봤습니다!
화면과 모델간의 싱크가 한번만 맞으면 되기 때문에 FruitStore를 싱글톤에서 의존성 주입을 통한 인스턴스 공유 방식으로 바꾸었고 재고 관리 뷰에는 재고 업데이트 클로져를 전달해 클로져로 업데이트 하는 방식으로 변경했습니다!

2023-12-21 10:56 UTC, cherrishRed requested changes

2023-12-21 10:56 UTC, cherrishRed commented on JuiceMaker/JuiceMaker/Controller/FruitStockViewController.swift
> +class FruitStockViewController: UIViewController {
이 VC를 다른 곳에 상속할 일이 있을까요? 
없다면, final 을 붙여 주세요!

2023-12-21 10:56 UTC, cherrishRed commented on JuiceMaker/JuiceMaker/Controller/FruitStockViewController.swift
> +        fruitStockSaveButton.isEnabled = stepperDict.map { Int($0.key.value) } == originStockValue ? false : true
이 경우에 모든 값을 구하고 비교하는 것보다, 
다른 값이 하나라도 나온다면 true 를 early return 하는 방법은 어떤가요? 
꼭 한줄에 짜야 할 필요는 없습니다.

2023-12-21 10:56 UTC, cherrishRed commented on JuiceMaker/JuiceMaker/Controller/FruitStockViewController.swift
> +    }
메서드 들이 외부에서 실행되지 않는다면, private 이 필요해 보이네요. 
다른 메서드들도요.

2023-12-21 10:56 UTC, cherrishRed commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderingViewController.swift
> +        secondVC.updateFruitStore = fruitStore.updateFruitStore
closure 를 쓰셨군요! 좋은 시도 입니다!
그런데, fruitStore 내부에 있는 값을 넘기다 보니 가독성이 조금 떨어지는 것 같습니다. 
`secondVC.updateFruitStore = fruitStore.updateFruitStore`
특히 이 줄은 변수를 할당하는 것 처럼 보이네요. 
클로저를 사용하신다면, 구현부가 vc 에 있는 것이 좋을 것 같아요. 
구현부에서, fruitStore.updateFruitStore 를 호출하더라도요.

이 부분을 delegate pattern 을 사용해서 수정해 보시면 좋을 것 같아요!
일반적으로 두 뷰 사이의 관계에서 많이 사용하는 패턴이예요!
싱글톤도 사용해 보셨고, 클로저도 사용해 보셨으니, delegate 까지 사용하시면, 각각의 장단점을 느끼실 수 있을 거예요!

2023-12-21 10:56 UTC, cherrishRed commented on JuiceMaker/JuiceMaker/Controller/FruitStockViewController.swift
> +        self.dismiss(animated: false)
animated 를 true 로 두면, 자연스러운 animation 이 되고 좋을 것 같네요.

2023-12-21 10:56 UTC, cherrishRed commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderingViewController.swift
> +
secondVC 보다 조금더 의미있는 네이밍 이거나, 
지역변수이고, 이 메서드 안에는 vc 는 하나밖에 없으니, 그냥 vc 이거나 
하는 네이밍으로 수정해 보세요!

2023-12-21 12:25 UTC, jus1234 commented on JuiceMaker/JuiceMaker/Controller/FruitStockViewController.swift
> +class FruitStockViewController: UIViewController {
다른 곳에서 상속할 일이 없는 class라 final을 붙이겠습니다!

2023-12-21 12:26 UTC, jus1234 commented on JuiceMaker/JuiceMaker/Controller/FruitStockViewController.swift
> +    }
네 외부에서 호출되지 않는 메서드들은 private을 붙이겠습니다!

2023-12-21 12:28 UTC, jus1234 commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderingViewController.swift
> +
지역변수로 메서드에서 유일한 vc라 vc로 사용하면 좋을거 같습니다!

2023-12-21 12:31 UTC, jus1234 commented on JuiceMaker/JuiceMaker/Controller/FruitStockViewController.swift
> +        self.dismiss(animated: false)
애니메이션도 추가해 보겠습니다!
레드! 애니메이션 관련해서 든 궁금증인데 앱에서 애니메이션을 추가하거나 추가하지 않을 때의 조건같은 것도 있을까요?!

2023-12-21 12:32 UTC, jus1234 commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderingViewController.swift
> +        secondVC.updateFruitStore = fruitStore.updateFruitStore
delegate pattern도 사용해 보겠습니다!

2023-12-21 12:34 UTC, jus1234 commented on JuiceMaker/JuiceMaker/Controller/FruitStockViewController.swift
> +        fruitStockSaveButton.isEnabled = stepperDict.map { Int($0.key.value) } == originStockValue ? false : true
아 그러네요! 전부 순회할 필요 없이 일치하지 않는 요소가 생기면 early return을 하도록 하면 더 좋을거 같습니다!

2023-12-26 04:16 UTC, jus1234 commented
@cherrishRed 레드! 리뷰 주신 내용으로 리팩토링 진행했습니다! 확인 부탁드려요~~
- delegate pattern 적용
- 네이밍 수정
- final 키워드 추가
- early return 적용
- 접근제어자 추가

2023-12-26 08:54 UTC, cherrishRed approved these changes
연휴도 끼어 있었는데, 두분 모두 수고하셨습니다!

delegate 패턴을 잘 적용해셔서 코드가 깔끔해진 것 같습니다!
네이밍 수정하신 부분도, 점점 네이밍 실력이 좋아지시는 것 같습니다.
첫 ui 프로젝트 수고 많으셨습니다!

2023-12-26 08:54 UTC, merged