쥬스자판기 [Step 3] 댄, 라마
tasty-code/ios-juice-maker pull request #106
Opened 2023-12-19 07:57 UTC by eensungkim

Step 3
멤버 : @eensungkim, @llamang
리뷰어 : @minsson

쥬스 자판기 프로젝트의 마지막 Step입니다! 
정리하여 PR 드립니다. 감사합니다!

# 리뷰 추가 반영사항

- 변수 네이밍 수정 반영
- .description 대신 String(describing:) 활용

# Step 3 구현내용
## 재고 수정 화면
제목 추가 및 닫기 버튼 구현
현재 재고 내용 Label 에 반영
스테퍼를 활용한 재고 수정 기능
오토레이아웃 적용

## JuiceViewController.swift
showStockViewModal() : 기존 내비게이션 컨트롤러를 활용한 이동에서 모달을 활용한 이동으로 변경 구현

extension JuiceViewController : 재고 수정 모달을 빠져나오더라도 수정된 재고가 기존의 쥬스 화면에 반영될 수 있도록 위임 패턴을 활용하여 구현

## StockViewController.swift
closeButtonTapped() : 모달 종료 버튼이 클릭되는 경우 위임받은 메서드 실행 및 화면 종료

setInitialStepperValue() : 현재 재고를 스테퍼의 초기 밸류와 연동

protocol StockViewControllerDelegate : 위임 패턴 활용을 위한 프로토콜 구현

## 그 외
재고 수정 메서드인 reloadFruitsCount() 를 viewDidLoad() 가 아닌 viewIsAppearing() 에서 호출하도록 변경

# 질문
- 댄 : 추후 추가하도록 하겠습니다.
- 라마 : 추후 추가하도록 하겠습니다.

2023-12-21 14:29 UTC, minsson requested changes
안녕하세요, 댄, 라마! 어느새 이번 프로젝트의 마지막 STEP이군요!
이번 스텝도 코드도 깔끔하고, 기능도 잘 구현해주셔서 잘 이해할 수 있었어요.
코드에 대한 상세한 피드백은 평소처럼 코드 코멘트로 남겨두었으니 참고해주세요.

아래는 질문에 대한 답변이에요. 두 분 다 좋은 질문을 해주셔서 감사해요. 저도 함께 생각해볼 수 있어서 좋았어요. ☺️

## 질문에 대한 답변
>- 댄 : 화면 전환 방식을 내비게이션에서 모달로 변경하면서, JuiceViewController 의 생명주기 메서드들이 동작하지 않는 상황이 있었습니다. 이를 해결하기 위해 위임 패턴을 활용해서 JuiceViewController 의 메서드를 모달의 뷰로 전달해줘야 했었는데요.
모달을 적용해보고 공부한다는 입장에서 적용해보았지만, 내비게이션 방식이 좀 더 어울린다고도 판단이 들었습니다. 기획의 차이가 아닐까 싶은데요. 내비게이션과 모달 사이에서 선택할 때 민쏜님은 어떤 기준으로 구분하시는지 궁금합니다.

저의 경우에는 데이터를 계층적으로 보여줘야 하는 상황이라면 내비게이션을 사용하고, 일시적으로 어떤 정보를 전달하거나 행위를 하게 하는 경우에는 모달을 사용해요. 사실 이런 기준보다는 그동안 아이폰을 사용해오면서 꾸준히 누적되온 경험을 따르면 더 직관적일 거라고 생각해요. 그동안 우리가 자연스럽게 겪어서 익숙해진 UX가 있으니까요.

제가 설명드리는 것보다는, 잘 설명되어 있는 자료를 드리면 더 많은 도움이 될 것 같아요.

[H.I.G - Modality](https://developer.apple.com/design/human-interface-guidelines/modality)에 Modality를 어느 경우에 사용하는지 잘 설명되어 있어요. Modality 뿐만 아니라 다른 것들도 전반적으로 가볍게 읽어보시길 권하고 싶어요.

또, [WWDC 2022 - Explore navigation design for iOS](https://developer.apple.com/videos/play/wwdc2022/10001)도 추천해요. WWDC는 이 영상 외에도 관심있는 주제를 찾아보며 틈틈이 봐두면 앞으로 정말정말정말 많은 도움이 될 거예요.





    
> - 라마 : Stepper를 활용해 기존 `FruitStore`의 `updateStock` 메서드를 사용하려면, `Int(sender.value) - (fruitStore.storage[.pineapple] ?? 0)` 같은 추가적인 연산이 필요했습니다.
 왜냐하면 기존의 재고에 수량을 더하거나(`amount > 0`) 빼는(`amount < 0`) 방식이기 때문입니다. 이번 프로젝트에서 `FruitStore`의 `updateStock` 메서드는 Stepper를 통해서만 사용됩니다. 
따라서 `Int(sender.value) - (fruitStore.storage[.pineapple] ?? 0)` 같은 추가적인 연산을 제거하고자, 다음과 같이 기존 재고와 상관없이 수량을 업데이트하는 메서드로 구현을 변경했습니다. 
해당 변경으로 인해 Stepper를 통한 `FruitStore`의 재고를 업데이트하는 구현은 간단해졌지만, 기존 재고와 상관없이 수량을 setter 방식으로 업데이트하는 것이 어색하게 느껴집니다.

저 개인적으로는, 적어도 지금 프로젝트에서는 지금 두 분이 구현해 놓으신 방식이 더 좋고, 직관적인 방법이라고 생각해요. 가독성도 기존 방식 대비 더 좋아지고요.

어떤 점에서 라마가 어색하게 느끼시는 건지에 대해 생각해봤어요. `기존 재고와 상관없이 수량을 setter 방식으로 업데이트하는 것`이라고 말씀해주신 부분에서 힌트를 얻을 수 있었어요.
`재고를 변경한다 -> 기존 재고에서 / 소비하거나 / 공급한만큼 / 변경된다`라고 생각한다면 충분히 어색하게 생각할 수 있을 것 같아요. 무엇보다도 현실의 우리에게는 이런 게 더 익숙한 사고방식이고요. 

그렇지만 우리가 코드를 작성하는 공간은 현실 세계가 아니라 컴퓨터 세계이고, 그렇기 때문에 현실과는 다르게 생각해볼 수 있을 것 같아요. 현실에서는 기존에 창고에 있던 과일을 어딘가로 순간이동시켜서 없애버리고 새로운 과일을 공급할 수 없지만, 컴퓨터 세계에서는 할당을 통해 기존의 값에 새로운 값을 덮어씌울 수 있으니까요.

2023-12-22 00:31 UTC, eensungkim commented on JuiceMaker/JuiceMaker/Controller/JuiceViewController.swift
>      }
- [이 문서](https://developer.apple.com/documentation/uikit/view_controllers/displaying_and_managing_views_with_a_view_controller#3370691)를 통해 생명주기 관련 메서드들을 확인할 수 있었구요. [콘텐츠를 업데이트할 때 활용하라는 내용](https://developer.apple.com/documentation/uikit/view_controllers/displaying_and_managing_views_with_a_view_controller#3370691:~:text=Update%20the%20content%20of%20your%20views%20in%20the%20viewIsAppearing(_%3A)%20method%20of%20your%20view%20controller.)을 보고서 적용하게 되었습니다.
- 재고 수정 화면을 적용하고 테스트해보니 기존 쥬스주문 화면의 재고가 업데이트되지 않는다는 점을 발견했습니다. 문서를 찾아보니 viewDidLoad는 생명주기 안에서 처음 Load 될 때에 한 번만 호출된다는 것을 알 수 있었습니다. 로드된 이후에도 업데이트를 반영해줄 수 있도록 viewIsAppearing 에서 메서드를 호출하도록 수정했습니다.
- viewWillAppear 는 전환이 시작되는 첫 과정에서 호출되는 메서드이고, viewIsAppearing 은 view 가 이미 계층구조에 올라가고 프레임이나 경계, 여백 등을 정의한 상태 이후에 호출되는 메서드입니다.

2023-12-22 01:02 UTC, eensungkim commented on JuiceMaker/JuiceMaker/Controller/JuiceViewController.swift
> +        showStockViewModal()
제안해주신 네이밍이 더 좋을 것 같아요! 반영하겠습니다.

2023-12-22 01:05 UTC, eensungkim commented on JuiceMaker/JuiceMaker/Controller/JuiceViewController.swift
> +        showStockViewModal()
https://github.com/tasty-code/ios-juice-maker/pull/106/commits/f3047ca51c52bec08dc7ef04c0166f725ca353f6

2023-12-22 01:26 UTC, eensungkim commented on JuiceMaker/JuiceMaker/Controller/JuiceViewController.swift
> +        mangoCountLabel.text = String(describing: fruitStore.storage[.mango] ?? 0)
질문 주신 김에 문서를 조금 더 확인해보니, describing 을 활용하는 경우 전달되는 인자가 어떤 프로토콜을 따르는지에 따라 출력이 다양하게 바뀔 수 있을 것 같아요.
저희가 원하는 건 Int 를 변환해주는 것이지, 여기에 부가적인 가능성이 생기면 안된다고 판단하여 제안해주신 부분으로 변경하는 것이 맞다고 생각됩니다!
description 이라는 걸 알게되고 이를 썼다가 변경하는 과정에서 한 번 더 생각하는 과정을 놓친 것 같습니다. 😅

2023-12-22 01:26 UTC, eensungkim commented on JuiceMaker/JuiceMaker/Controller/StockViewController.swift
> +        mangoCountLabel.text = String(describing: fruitStore.storage[.mango] ?? 0)
위에 답변을 남겨두었고 변경했습니다!

2023-12-22 01:29 UTC, eensungkim commented on JuiceMaker/JuiceMaker/Controller/JuiceViewController.swift
> +        mangoCountLabel.text = String(describing: fruitStore.storage[.mango] ?? 0)
https://github.com/tasty-code/ios-juice-maker/pull/106/commits/965b472f9808be6f81cb2fad8afb908f32c4dc6f

2023-12-22 01:29 UTC, llamang commented on JuiceMaker/JuiceMaker/Controller/JuiceViewController.swift
> +//  JuiceMaker - JuiceViewController.swift
과일 쥬스 주문 화면을 담당하는 `Controller`라는 의미에서 다음과 같이 변경했습니다. 
`JuiceViewController` → `FruitJuiceOrderViewController` 
e732bd2b1ad494a54aae57a8bf850640e3c53e5f

2023-12-22 01:29 UTC, eensungkim commented on JuiceMaker/JuiceMaker/Controller/StockViewController.swift
> +        mangoCountLabel.text = String(describing: fruitStore.storage[.mango] ?? 0)
https://github.com/tasty-code/ios-juice-maker/pull/106/commits/965b472f9808be6f81cb2fad8afb908f32c4dc6f

2023-12-22 01:31 UTC, eensungkim commented on JuiceMaker/JuiceMaker.xcodeproj/project.pbxproj
>  		};
폴더는 기존에 제공받은 형태를 유지했기 때문에 특별히 저희만의 기준이 있지는 않았습니다.
기존에 제공받은 형태를 확인했을 때 MVC 패턴을 따라 폴더로 구분이 되어있었고, 따라서 저희가 필요에 따라 새롭게 생성하게 된 StockViewController.swft 파일의 경우 Controller 폴더 안에 넣는 것이 바람직하다고 판단했습니다.

2023-12-22 02:07 UTC, llamang commented on JuiceMaker/JuiceMaker/Controller/StockViewController.swift
> +}
extension을 이용해 메서드를 묶었습니다. 
246efe49b8c84c755e0ac8acec0077dfba4a470c

혹시 더 적절한 것이 있다면 알려주세요!

2023-12-22 02:36 UTC, eensungkim commented on JuiceMaker/JuiceMaker/Controller/JuiceViewController.swift
> +
- 우선 스토리보드에 그렇게 되어 있었던 점 때문이기도 하구요. 최종 구현 예시에서도 내비게이션 방식의 title bar 영역이 회색으로 처리된 것을 확인했었습니다. 사실 이 때문에 화면 전환 시에 모달과 내비게이션 중 무엇이 의도한 바인지에 대한 고민이 이어지기도 했었습니다.
title bar 영역을 별도로 구현한다면 통일성을 살리기 위해 불필요한 노력이 들어가야 한다고 판단했고, 그래서 기존에 되어 있는 것을 최대한 살리는 방향으로 구현하게 되었습니다.
- 바로 StockViewController 를 찾아서 캐스팅해주면 된다고 생각합니다. 단 그렇게 하면 타이틀바 영역에 대한 디자인을 별도로 해당 화면에 구현해 주어야 할 것 같습니다.
- guard let 을 활용하게 되면 해당 조건을 충족하지 못할 때 early exit 이 됩니다. 또한 if let 의 경우 조건문 내부의 스코프에서만 해당 변수명을 활용할 수 있지만, guard let 을 활용할 경우 guard let 이후에서 일반 변수를 선언해준 것처럼 변수명을 활용할 수 있습니다.
사실 구현할 당시에 guard let 으로 할 수도 있다는 점에 대해 이야기가 나왔는데, 다른 것들에 대한 고민으로 이어지면서 놓쳤던 부분입니다. 바인딩이 되지 않고서 모달 화면으로 넘어간다면 의도와 다른 동작이 발생할 수 있기 때문에, guard let 으로 변경하는 것이 맞다고 생각합니다.
- 수정 반영했습니다!

2023-12-22 02:49 UTC, llamang commented on JuiceMaker/JuiceMaker/Controller/StockViewController.swift
> +    weak var delegate: StockViewControllerDelegate?
약한(weak) 참조는 참조하는 인스턴스를 강력하게 유지하지 않는 참조이므로 ARC가 참조된 인스턴스를 삭제하는 것을 막지 않습니다. 이 동작은 참조가 강력한 참조 순환의 일부가 되는 것을 방지합니다.

> [Weak References](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/automaticreferencecounting/#Weak-References)
> 

클래스의 인스턴스가 강력한 참조가 없는 지점에 도달하지 않는 코드를 작성하는 것이 가능합니다. 이는 두 클래스 인스턴스가 서로에 대한 강력한 참조를 보유하여 각 인스턴스가 다른 인스턴스를 활성 상태로 유지하는 경우 발생할 수 있습니다. 이를 강한 참조 순환(strong reference cycle)이라고 합니다.

> [Strong Reference Cycles Between Class Instances](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/automaticreferencecounting/#Strong-Reference-Cycles-Between-Class-Instances)
> 

약한(weak) 또는 소유되지 않은(unowned) 참조를 사용하면 참조 순환의 한 인스턴스가 이를 강력하게 유지하지 않고도 다른 인스턴스를 참조할 수 있습니다. 그러면 인스턴스는 강력한 참조 순환을 생성하지 않고도 서로를 참조할 수 있습니다.

> [Resolving Strong Reference Cycles Between Class Instances](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/automaticreferencecounting/#Resolving-Strong-Reference-Cycles-Between-Class-Instances)
>

2023-12-22 04:09 UTC, llamang commented on JuiceMaker/JuiceMaker/Controller/StockViewController.swift
> +}
> AnyObject를 붙여주셨네요! AnyObject는 무엇이고, 어떤 목적으로 사용하신 건가요?

프로토콜의 상속 목록에 `AnyObject` 프로토콜을 추가하여, 프로토콜 채택을 구조나 열거형이 아닌 클래스 유형으로 제한할 수 있습니다.

📖 [Class-Only Protocols](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/protocols/#Class-Only-Protocols)

프로토콜을 클래스 전용으로 표시하면, 해당 프로토콜 타입의 대리자(delegate)가 약한 참조를 사용해야 함을 선언할 수 있습니다.

2023-12-22 06:44 UTC, llamang commented on JuiceMaker/JuiceMaker/Controller/StockViewController.swift
> +}
> Delegate 패턴이란 무엇이고, 어떤 이유로 사용하나요?
> 

Delegate 패턴

- 위임은 클래스나 구조가 자신의 책임 중 일부를 다른 유형의 인스턴스에 전달(또는 위임)할 수 있도록 하는 디자인 패턴입니다. 

- 이 디자인 패턴은 위임된 기능을 제공하는 준수 유형(대리자라고도 함)이 보장되도록 위임된 책임을 캡슐화하는 프로토콜을 정의하여 구현됩니다. 

- 위임은 특정 작업에 응답하거나 해당 소스의 기본 유형을 알 필요 없이 외부 소스에서 데이터를 검색하는 데 사용할 수 있습니다.

- 📖 [Delegation](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/protocols/#Delegation)

Delegate 패턴을 사용한 이유

- `Stock` View 모달 화면이 종료되면,`FruitJuiceOrder` View의 재고 수량을 reload 하기 위해 사용했습니다.

- 해당 delegate을 사용하지 않은 상태에서 `Stock` View에서 재고를 업데이트하고 종료하면, `FruitJuiceOrder` View로 돌아왔을 때 업데이트된 과일 재고 수량이 해당 View에 반영되지 않았습니다. 그래서 `Stock` View 화면이 `viewWillDisappear` 메서드를 호출할 때, `FruitJuiceOrder` View의 재고 수량을 reload 하도록 구현했습니다. 

- 참고로, `viewDidDisappear` 메서드에서 `FruitJuiceOrder` View의 재고 수량을 reload 하면 업데이트된 과일 재고 수량이 눈에 띄도록 늦게 반영됩니다. 이런 이류로 `viewWillDisappear` 메서드를 선택했습니다.

> 같은 작업을 수행하기 위한 다른 방법은 무엇이 있을까요?
> 

NotificationCenter 

- 등록된 관찰자에게 정보를 broadcast 할 수 있는 알림 발송 메커니즘입니다. 즉, 알림은 발신자가 알 수 없는 여러 수신자에게 메시지를 broadcast 하는 데 사용됩니다. 

- 컨트롤러는 게시되는 알림과 관련된 사용자 정의 정보(userInfo)가 포함된 컨텍스트(dictionary) 개체를 전달할 수 있습니다.

- 코드 줄이 많지 않아 구현이 쉽습니다.

- 📖 [NotificationCenter](https://developer.apple.com/documentation/foundation/notificationcenter)

- 📖 [Notification](https://developer.apple.com/documentation/foundation/notification)

Observation

- Key-value observing은 다른 개체의 속성 변경 사항을 개체에 알리는 데 사용하는 Cocoa 프로그래밍 패턴입니다. 모델과 뷰 등 논리적으로 분리된 앱 부분 간의 변경 사항을 전달하는 데 유용합니다. NSObject에서 상속된 클래스에서만 키-값 관찰을 사용할 수 있습니다.

- 두 개체 간에 정보를 쉽게 동기화할 수 있는 방법을 제공할 수 있습니다. 

- 관찰하려는 속성(properties)은 문자열을 사용하여 정의해야 합니다. 따라서 컴파일 타임에 경고나 검사가 발생하지 않는 단점이 있습니다. 

- 또한 속성을 리팩토링하면 관찰(observation) 코드가 더 이상 작동하지 않을 수 있습니다.

- 객체가 여러 값을 관찰하는 경우 복잡한 `if` 문이 필요합니다.

- 할당이 해제되면 관찰자를 제거할 필요가 있습니다.

- 📖 [Key-value observing](https://developer.apple.com/library/archive/documentation/General/Conceptual/DevPedia-CocoaCore/KVO.html)

- 📖 [Using Key-Value Observing in Swift](https://developer.apple.com/documentation/swift/using-key-value-observing-in-swift)

📖 [Delegates VS Notifications VS Observations in iOS](https://medium.com/@azeemireland/delegates-vs-notifications-vs-observations-in-ios-fa312e66c0ff)

> 여러 방법 중에서 Delegate 패턴을 선택하신 이유는 무엇인가요?
> 

구현 시에는 NotificationCenter와 Delegate 패턴 중에서 선택했고, 다른 방법은 알고 있지 않아서 고려하지 않았습니다. 

NotificationCenter을 사용하지 않은 이유

- 저희 구현에서는 여러 관찰자가 해당 알림을 일괄적으로 받아야 할 필요가 없습니다.
- 또한 관찰자가 알림을 올바르게 처리하는지 컴파일 타임에 확인할 수 없는 단점도 있습니다.
- 이전에 등록한 객체가 할당 해제된 경우 알림 센터에 등록을 취소해야 합니다.

Delegate을 선택한 이유

- 청취할 모든 이벤트는 delegate 프로토콜에 명확하게 정의되어 있습니다.
- 특정 이벤트 처리를 위해서 발신자(위임 개체)와 수신자(대리인) 간의 일대일 관계를 형성합니다.
    
    통신 프로세스를 유지 또는 모니터링하는 데 다른 객체가 필요하지 않습니다.
    
- 추적이 가능하고 애플리케이션 내 제어 흐름을 쉽게 식별할 수 있습니다.

2023-12-27 01:16 UTC, minsson commented
댄, 라마, STEP 3 고생 많으셨습니다! :)

2023-12-27 01:16 UTC, merged