쥬스 자판기 [STEP 3] Jane, Harry
tasty-code/ios-juice-maker pull request #108
Opened 2023-12-19 12:13 UTC by jane1choi

@junbangg
안녕하세요~ 알라딘! Jane, Harry입니다!
STEP 3 마지막 PR 올립니다!!!!!
조언, 제안 모두 환영이니 자유롭게 의견주시면 감사하겠습니다😊😊

## 🔍 What is this PR?
STEP 3의 기능을 구현했습니다.
- 상단바 '재고 추가' 및 '닫기' 버튼 구현
- 화면전환 방식 수정(`Navi 방식` -> `Modality`)
- 데이터 저장 방식 및 전달 방식 수정 (싱글톤 패턴 -> 화면 전환 시 데이터 전달)

## 📝 PR Point
### 상단바 UI 구현 및 오토레이아웃 적용 (아이폰 SE 기기대응)
새롭게 추가된 UI 구현 사항을 구현하며 스토리보드를 이용해 오토레이아웃을 적용해주었고, `Stack View`를 사용해 아이폰 SE 기기의 화면까지 대응할 수 있도록 했습니다.
  
### 화면전환 방식 수정 - Modality
STEP 2 PR에서 고민되는 부분으로 언급했었는데, HIG 문서를 기반으로 고민했을 때 해당 로직에서는 Modality가 더 적합하다고 판단했고,
STEP 3에서 구현 요구 사항으로 추가된 버튼의 타이틀인 '닫기' 라는 단어의 의미도 Modality와 더 어울린다고 생각해서 화면전환 방식을 네비 방식에서 모달 방식으로 수정했습니다.

### 데이터 저장 방식 및 전달 방식 수정
기존 싱글톤 패턴을 이용한 데이터 저장 및 업데이트 로직을 첫번째 화면인 `OrderViewController`에서의 초기값 설정 후 데이터 변경사항을 화면전환 시에 다음 화면, 이전 화면으로 넘겨주는 방식으로 수정했습니다. 

**로직 변경 이유**
해당 프로젝트에서는 2개의 화면만 존재하기 때문에 전역에서 접근할 수 있는 싱글톤 인스턴스를 두는 것보다 화면전환 시 데이터 전달 방식으로 데이터를 다음 화면으로 넘겨주고, 다시 넘겨받는 방식으로 화면에 보이는 UI를 업데이트 해주는 방식이 더 적합하다고 판단했습니다.

데이터를 가져오고 변경해주는 방식을 `FruitStore`의 프로퍼티에 직접 접근하는 방식이 아닌, 프로퍼티는 접근 제어를 통해 클래스 내부로 숨기고 클래스의 메서드에 접근해 가져오고 변경해주는 형태로 구성했습니다. 싱글톤 패턴을 사용했을 때는 앱 전역에서 프로퍼티에 쉽게 접근해 변경할 수 있었기 때문에 데이터의 사용 및 변경이 용이하다는 이점이 있었지만 해당 방식으로 코드를 수정해 데이터를 가지고 있는 프로퍼티를 은닉화해줄 수 있었습니다. 

두가지 방식에 장단점이 있다고 생각하는데, 여기에 대한 리뷰어님의 의견도 궁금합니다!!! 자유롭게 코멘트로 의견 남겨주시면 감사하겠습니다😊😊

## 📸 Screenshot
|    구현 내용    |   구동 영상   |
| :-------------: | :----------: |
| 쥬스 제조 및 재고관리 로직 |  ![Simulator Screen Recording - iPhone 14 Pro - 2023-12-19 at 21 07 32](https://github.com/tasty-code/ios-juice-maker/assets/63277563/2090ad0f-5dc1-4682-befe-350c592e4ac0) |
| SE 기기 대응 | <img width="700" alt="스크린샷 2023-12-19 오후 9 09 20" src="https://github.com/tasty-code/ios-juice-maker/assets/63277563/355a1be0-bd3f-4b4d-9dfc-533c22e99a17"> |

2023-12-20 22:37 UTC, junbangg requested changes
수고하셨습니다!!! 
지난 스텝에서 이야기 나눴던 부분에 대해서 리팩토링도 하신 점 아주 칭찬합니다!!
앞으로도 계속 그런 리팩토링 정신을 갖고계시길..👍🙏

질문 내용에 대해서 간단히 저의 의견을 드리자면..! 
일단 SIngleton 에 대해서...

**저는 진짜 특별한 근거/이유가 없다면,,, 싱글톤은 멀리 하려고 하는 편입니다:)**

물론 검색하면 나오는 다양한 이유들이 있지만, 제가 개인적으로 느낀 단점은 다음과 같아요(특히 오래된 레거시 싱글톤들을 보면서)

1. Global 하게 접근이 가능해서, 시간이 지나면 지날 수록 의존 관계가 엉망진창이 된다.
    - 여기저기서 자유롭게 접근하고 수정하다보면, 언젠가부터 관리가 힘들어지더라고요
2. 1번의 연장선이긴한데,, 싱글톤에 의해서 다른 타입들과 결합도가 생기면서, 마음대로 수정하기가 점점 힘들어지고 사이드 이펙트가 생길 가능성이 높아져요!
    - 여기저기서 사용하면 할 수록 수정할 때 Side effect가 생길 수 있는거죠
3. 처음에는 순수한 마음으로 자그만한 Singleton을 만들지만, 사용하기가 너무 편해서, 여기저기 다양한 목적으로 사용하게 되면서, 아주 자연스럽게 SRP 가 위배되는 모습이 보기 쉬운것 같아요

이야기 하다보니까 그냥 Singleton 의 단점을 이야기했네요 ....ㅎㅎ그런데 이런 패턴이 생겨난 이유도 분명히 있겠죠?? 디자인 패턴이라는게 개발자들이 흔하게 부딪히는 문제를 해결하기 위해 생겨난 방법론들이니까?

지금 OrderViewController랑 InventoryViewController 끼리 FruitStore 로 캐치볼 할 수 있게 리팩토링을 하셨는데, 만약에 앱이 복잡해지고 규모가 커지면서, FruitStore에 저장되는 데이터가 다양한 곳에서 접근/수정 되어야할 필요가 있으면 어떻게 해야될까요🤔

2023-12-20 22:37 UTC, junbangg commented on JuiceMaker/JuiceMaker/Controller/OrderViewController.swift
> +        self.fruitStore = FruitStore.init(fruitContainer: [
그냥 `FruitStore()` 이런 식으로 사용 앟나고 `.init` 을 한 이유가 있을까요??( 단순 궁금증)

2023-12-20 22:37 UTC, junbangg commented on JuiceMaker/JuiceMaker/Controller/OrderViewController.swift
> +        nextViewController.setUpFruitContainerData(fruitStore.fetchFruitContainer())
`fruitStore.fetchFruitContainer()` 를 상수에 저장 해놨다가 `nextViewController.setupFruitContainerData()` 에 집어 넣는거 어떨까요??
조금이라도 더 가독성이 향상 될것 같다는 개인적인 생각입니다~

2023-12-20 22:37 UTC, junbangg commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func updateFruitContainer(_ data: [Fruit: Int]) {
요런 느낌은 어떠신가요?
```suggestion
    func updateFruitContainer(with data: [Fruit: Int]) {
```

2023-12-20 22:37 UTC, junbangg commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
fetch 도 나쁘지는 않은데요~! 
fetch 라고 하면, API 에서 가져올것 같은 느낌이 있어요!

다른 네이밍은 없을까요???🤔

2023-12-20 22:37 UTC, junbangg commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +            fruitStore.updateFruitQuantity(of: fruit, by: storedFruit)
직접 객체의 프로퍼티에 접근하지 않고, 메서드를 제공하는 객체지향적인 방식 너무 좋습니다!👍

2023-12-20 22:37 UTC, junbangg commented on JuiceMaker/JuiceMaker/View/InventoryViewController.swift
> +    private let fruitStore: FruitStore = FruitStore(fruitContainer: [:])
내부에서 직접 생성되도록 변경된 이유가 뭘까요???

2023-12-20 22:37 UTC, junbangg commented on JuiceMaker/JuiceMaker/View/InventoryViewController.swift
> +        fruitStore.updateFruitQuantity(of: fruit, by: fruitQuantity)
지금은 크게 신경 안쓰셔도 되지만, 
`fruitStore.updateFruitQuantity(of: fruit, by: fruitQuantity)` 요런식으로 데이터만 변경하면
`fruitElementsByStepper[stepper]?.label.text = String(fruitQuantity)` 가 호출 되지 않아도 알아서 UI가 적용될 수 있는 방법도 나중에 생각해보시면 좋을것 같네요🙂

2023-12-20 22:37 UTC, junbangg commented on JuiceMaker/JuiceMaker/View/InventoryViewController.swift
> +        presentingViewController.setUpFruitContainer(data: fruitStore.fetchFruitContainer())
모달 present 했을때 처럼, fruitStore 를 다시 전달하는 방식인거죠?!

2023-12-20 22:37 UTC, junbangg commented on JuiceMaker/JuiceMaker/Controller/OrderViewController.swift
> +            label.text = String(fruitStore.fetchFruitQuantity(of: fruit))
상수로 적당히 나눠서 할당해주면 어떨까요?? 조금이나마 더 가독성을 향상 시키기 위해!

2023-12-20 22:37 UTC, junbangg commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +            var storedFruit = fruitStore.fetchFruitQuantity(of: fruit)
네이밍이 조금 더 명확할 수 있을것 같아요!

2023-12-21 04:59 UTC, hemil0102 commented on JuiceMaker/JuiceMaker/View/InventoryViewController.swift
> +        presentingViewController.setUpFruitContainer(data: fruitStore.fetchFruitContainer())
네 맞습니다. 😄

1. present로 뷰 컨트롤러를 모달로 표시했을 경우, 해당 표시된 화면을 프로퍼티로 갖게됩니다. 
> 즉, 저희는 InventoryViewController를 모달로 띄웠으므로, `presentingViewController는 InventoryViewController가 됩니다.`

2. 만약 뷰 컨트롤러가 모달로 표시되지 않았지만 그 부모 중 하나가 모달로 표시되었다면, 이 속성은 부모를 표시한 뷰 컨트롤러를 포함합니다. 

> 여기서 저희는 OrderViewController에서 InventoryViewController를 모달로 띄우므로 `부모는 OrderViewController가 됩니다.` 작성한 코드는 `모달로 표시된 뷰 컨트롤러의 부모가 OrderViewController일 때에만` 타입캐스팅으로  OrderViewController에 대한 `작업을 수행하고`, 그렇지 않은 경우에는 아무 작업도 하지 않고 함수를 종료합니다. 모달로 표시된 경우에만 특정 작업을 수행하도록 하고, 그렇지 않은 경우에는 무시하도록 하는 것입니다.
 
3. 현재 뷰 컨트롤러나 그 부모 중 어느 것도 모달로 표시되지 않았다면, 이 속성의 값은 nil입니다.

When you present a view controller modally (either explicitly or implicitly) using the present(_:animated:completion:) method, the view controller that was presented has this property set to the view controller that presented it. If the view controller was not presented modally, but one of its ancestors was, this property contains the view controller that presented the ancestor. If neither the current view controller or any of its ancestors were presented modally, the value in this property is nil.

애플 공식 문서: https://developer.apple.com/documentation/uikit/uiviewcontroller/1621430-presentingviewcontroller/

2023-12-21 05:23 UTC, jane1choi commented on JuiceMaker/JuiceMaker/View/InventoryViewController.swift
> +        presentingViewController.setUpFruitContainer(data: fruitStore.fetchFruitContainer())
네 맞습니다!! dismiss 시에도 이전 화면에 변경된 데이터를 전달해주는 부분입니다!!

2023-12-21 06:00 UTC, hemil0102 commented on JuiceMaker/JuiceMaker/Controller/OrderViewController.swift
> +        self.fruitStore = FruitStore.init(fruitContainer: [
(정말 단순하게도) 제가 .을 찍는 버릇이 있어서 Xcode에서 띄워주는 완성 리스트로 구현을 하다보니 .init()을 사용했네요. 가독성은 없는 편이 나을 것 같아서 삭제해줬습니다. 😅

적용 커밋: 53764de9b20f6c29f237c58c2ca6f216c6c4216d

2023-12-21 06:02 UTC, hemil0102 commented on JuiceMaker/JuiceMaker/Controller/OrderViewController.swift
> +        nextViewController.setUpFruitContainerData(fruitStore.fetchFruitContainer())
리뷰 감사합니다. 아래 코드로 수정사항 반영했습니다. 

```swift
let fruitInventory = fruitStore.checkFruitContainer()
nextViewController.setUpFruitContainer(data: fruitInventory)
```

2023-12-21 06:03 UTC, hemil0102 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func updateFruitContainer(_ data: [Fruit: Int]) {
느낌 좋아서 바로 반영했습니다. 518fda8633fe702bad941b5041f2292463f16038

2023-12-21 06:05 UTC, hemil0102 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
해당 부분은 fetch를 check로 수정하였는데, 더 좋은 네이밍이 있다면 추천 받습니다! 
뭔가 과일 상자에서 과일을 가져오는 느낌으로 작명하고 싶은데, take나 get은 사용을 잘 안한다고 해서 check로 하였는데...
어떤게 좋을지 잘 모르겠지만 Jane과 많은(?) 고심 끝에 check로 반영했습니다. 감사합니다.

518fda8633fe702bad941b5041f2292463f16038

2023-12-21 06:08 UTC, hemil0102 commented on JuiceMaker/JuiceMaker/Controller/OrderViewController.swift
> +            label.text = String(fruitStore.fetchFruitQuantity(of: fruit))
수정사항 반영하였습니다. 😀 518fda8633fe702bad941b5041f2292463f16038

```swift
private func configureUI() {
        for (fruit, label) in labelsByFruit {
            let fruitQuantity = fruitStore.checkFruitQuantity(of: fruit)
            label.text = String(fruitQuantity)
        }
    }
```

2023-12-21 06:11 UTC, hemil0102 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +            var storedFruit = fruitStore.fetchFruitQuantity(of: fruit)
심혈(?)을 기울여 조금 더 직관적으로 재고 수량, 요구 수량이라는 맥락이 드러나도록 네이밍을 수정하였습니다. 😎 

```swift
var remainingQuantity = fruitStore.checkFruitQuantity(of: fruit)
if remainingQuantity < requiredQuantity {
        fruitStore.updateFruitContainer(with: originalFruitContainer)
        throw JuiceMakerError.invalidRequest
}
```

2023-12-21 07:14 UTC, hemil0102 commented on JuiceMaker/JuiceMaker/View/InventoryViewController.swift
> +        fruitStore.updateFruitQuantity(of: fruit, by: fruitQuantity)
와 그렇게 할 수도 있군요! 제인과 이야기 해보니 didset 또는 반응형 프로그래밍(RxSwift, Combine) 이야기가 나오더라구요. 값을 옵저빙 하는 관점인 것 같아요. 이 부분은 아직 RxSwift, Combine를 접해보지 않았어서, 향후 프로젝트 진행하면서 추가 개념을 알게 될 때 적용해보겠습니다. 감사합니다~

2023-12-21 07:25 UTC, jane1choi commented on JuiceMaker/JuiceMaker/View/InventoryViewController.swift
> +    private let fruitStore: FruitStore = FruitStore(fruitContainer: [:])
사실 `fruitContainer`를 빈값으로 초기화 한 이후에 화면전환 과정에서 값을 업데이트 해주는 방식으로 코드를 구성했었어서 어차피 화면전환 시 대체 될 데이터이니 내부 생성으로 초기화해도 되지 않을까,, 하는 생각에서 이렇게 코드를 구성해두었었는데, 코멘트 확인 후 생각해보니 `fruitContainer` 프로퍼티가 아닌 `fruitStore` 객체를 초기화해주는 것이니 외부 주입으로 하는 것이 객체 간 결합도를 줄여줄 수 있어 훨씬 좋은 방법이라는 생각에 외부 주입 방식으로 수정했습니다!! 확인 감사해요!!!
 
두 가지 방식으로 `fruitStore` 외부 주입을 구현해보았는데요, 한 가지 고민되는 점이 있어서 추가로 질문 남깁니다!!
1. `init()` 생성자 안에서 인스턴스 생성으로 초기화 후 화면 전환 코드에서 `setUpFruitContainer(data: )` 호출로 원하는 데이터 넘겨주기
2. `instantiateViewController(identifier:creator:)` 메서드 활용해서 화면 전환 시 인스턴스 주입

위의 두가지 방식으로 외부 주입을 구현했습니다!
첫번째 방식의 경우 `present`, `dismiss` 모두 `setUpFruitContainer(data: )` 라는 커스텀 메서드 호출로 변경된 데이터를 세팅해준다는 점에서 화면전환 시 데이터 전달 코드에 통일성이 있다는 점에서 장점이 있다고 생각하고, 두번째 방식의 경우 화면 전환 시에 필요한 데이터를 바로 주입해주어서 present되는 뷰컨에서는 `setUpFruitContainer(data: )` 메서드 자체가 필요없어지기 때문에 코드 간결성 면에서 장점이 있다고 생각하는데, 두 가지 방식에 대한 리뷰어님의 의견도 궁금해서 질문 남겨봅니다!!! 
어떤 방식이 더 좋아보인다!  혹은 두가지 방식에 대한 장단점에 대한 개인적인 견해 모두 환영이니 의견 남겨주시면 감사하겠습니다😊😊

[0d896bb](https://github.com/tasty-code/ios-juice-maker/pull/108/commits/0d896bb683730bf5b3baf178212b89fe736a0d38) ~ [af7c99b](https://github.com/tasty-code/ios-juice-maker/pull/108/commits/af7c99b634457558d5d4394e57d8d6024b28193b) 커밋 확인해주시면 감사하겠습니다!!!

2023-12-21 07:30 UTC, hemil0102 commented
> 수고하셨습니다!!! 지난 스텝에서 이야기 나눴던 부분에 대해서 리팩토링도 하신 점 아주 칭찬합니다!! 앞으로도 계속 그런 리팩토링 정신을 갖고계시길..👍🙏
> 
> 질문 내용에 대해서 간단히 저의 의견을 드리자면..! 일단 SIngleton 에 대해서...
> 
> **저는 진짜 특별한 근거/이유가 없다면,,, 싱글톤은 멀리 하려고 하는 편입니다:)**
> 
> 물론 검색하면 나오는 다양한 이유들이 있지만, 제가 개인적으로 느낀 단점은 다음과 같아요(특히 오래된 레거시 싱글톤들을 보면서)
> 
> 1. Global 하게 접근이 가능해서, 시간이 지나면 지날 수록 의존 관계가 엉망진창이 된다.
>    
>    * 여기저기서 자유롭게 접근하고 수정하다보면, 언젠가부터 관리가 힘들어지더라고요
> 2. 1번의 연장선이긴한데,, 싱글톤에 의해서 다른 타입들과 결합도가 생기면서, 마음대로 수정하기가 점점 힘들어지고 사이드 이펙트가 생길 가능성이 높아져요!
>    
>    * 여기저기서 사용하면 할 수록 수정할 때 Side effect가 생길 수 있는거죠
> 3. 처음에는 순수한 마음으로 자그만한 Singleton을 만들지만, 사용하기가 너무 편해서, 여기저기 다양한 목적으로 사용하게 되면서, 아주 자연스럽게 SRP 가 위배되는 모습이 보기 쉬운것 같아요
> 
> 이야기 하다보니까 그냥 Singleton 의 단점을 이야기했네요 ....ㅎㅎ그런데 이런 패턴이 생겨난 이유도 분명히 있겠죠?? 디자인 패턴이라는게 개발자들이 흔하게 부딪히는 문제를 해결하기 위해 생겨난 방법론들이니까?
> 
> 지금 OrderViewController랑 InventoryViewController 끼리 FruitStore 로 캐치볼 할 수 있게 리팩토링을 하셨는데, 만약에 앱이 복잡해지고 규모가 커지면서, FruitStore에 저장되는 데이터가 다양한 곳에서 접근/수정 되어야할 필요가 있으면 어떻게 해야될까요🤔

싱글톤은 클래스를 활용하여 객체를 `저장소처럼` 활용합니다. 이 경우 말씀해주신 것 처럼 싱글톤에 수많은 의존 관계가 형성되어, 한 곳의 수정 사항이 다른 곳에도 영향을 미치는 문제가 발생할 것 같아요. 아직 큰 규모의 프로젝트를 하지 않아서 답변을 충분하지 않을 수 있지만, 검색을 해서 찾아보았을 때는 데이터 쿼리, 데이터 베이스라는 용어들이 눈에 띄었습니다. 

CoreData, SQL, UserDefault, Realm 등 같은 저장소를 활용해서 대규모 프로젝트의 데이터를 관리할 수 있다고 하는데요. 이 부분은 직접 해보게 된다면 차이를 조금 명확히 알게 될 것 같아요.

2023-12-21 07:35 UTC, jane1choi commented
> 지금 OrderViewController랑 InventoryViewController 끼리 FruitStore 로 캐치볼 할 수 있게 리팩토링을 하셨는데, 만약에 앱이 복잡해지고 규모가 커지면서, FruitStore에 저장되는 데이터가 다양한 곳에서 접근/수정 되어야할 필요가 있으면 어떻게 해야될까요🤔

STEP 3도 상세한 리뷰 감사합니다!! 남겨주신 요 질문에 대해 제 개인적인 생각을 코멘트로 남겨보자면,,
사실 규모가 커지고 데이터의 수정이 많아진다면 로컬에 데이터를 저장할 수 있는 방법 중 하나인 `CoreData`를 사용할 수 있을 것 같고, 다양한 유저가 데이터에 접근해서 수정하고 업데이트 받아야되는 상황이라면 서버에서 데이터를 관리할 수 있도록 하고 API 요청을 통해 데이터를 주고 받아야 될 것 같습니다!!

2023-12-21 22:10 UTC, junbangg commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +            var storedFruit = fruitStore.fetchFruitQuantity(of: fruit)
크 좋습니다👍👍👍

2023-12-21 22:15 UTC, junbangg commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
요것도 정답(?) 은 없고 어쩌면 네이밍 컨벤션 나름일 수도 있는 영역이긴한데요
다른 언어들과 다르게 get 이라는 prefix 를 잘 사용하지 않아서 네이밍이 항상 헷갈리고 고민스럽더라고요 저도..🤔

메서드에는 동사를 붙이는 프랙티스가 익숙하다면 다음 네이밍은 조굼 어색할 수도 있을것 같은데 다음과 같은 네이밍에 대해서는 어떻게 생각하시나요? 스위프트 스럽다고 나름 생각하고 저는 이런식으로 쓴답니다ㅎㅎ(정답은 물론 아니지만)

`fruitStore.quantity(of fruit: Fruit) -> Int`

2023-12-21 22:28 UTC, junbangg commented on JuiceMaker/JuiceMaker/View/InventoryViewController.swift
> +    private let fruitStore: FruitStore = FruitStore(fruitContainer: [:])
물론 set 메서드도 좋은 방법이고 충분히 괜찮은 의존성 주입 방법이긴한데 저는 뷰컨을 만드는 경우에는 더 가능하면 생성자를 제공 해주는게 좋다고 생각해요!
set 메서드를 제공할때랑 init 메서드를 제공할때 프로퍼티의 형태가 달라지는것을 보실 수 있었을것 거예요!
눈치 채셨겠지만 하나는 프로퍼티가 옵셔널이 되는걸 보실 수 있을거예요ㅎㅎ

물론 나쁜 방법은 아니고 두 방법 모두 뷰컨 다룰때 많이 사용되지만~ 저는 전자를 선호하는 편이랍니다~

2023-12-21 22:28 UTC, junbangg commented on JuiceMaker/JuiceMaker/View/InventoryViewController.swift
> +        presentingViewController.setUpFruitContainer(data: fruitStore.fetchFruitContainer())
👍👍👍

2023-12-21 22:29 UTC, junbangg approved these changes
👍👍👍👍

2023-12-22 00:58 UTC, jane1choi commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
오 진짜 스위프트 api 가이드라인스러워요,,, 저도 네이밍이 항상 어려운 것 같은데,, 예시 감사합니다!!!

2023-12-22 01:00 UTC, jane1choi commented on JuiceMaker/JuiceMaker/View/InventoryViewController.swift
> +    private let fruitStore: FruitStore = FruitStore(fruitContainer: [:])
의견 감사합니다!!!

2023-12-24 14:55 UTC, merged