쥬스자판기[Step3] Asher, LJ
tasty-code/ios-juice-maker pull request #109
Opened 2023-12-20 05:28 UTC by ijs1103

@Mino777

리뷰어 : Mino777
버드 : 🕵🏻 애셔(Asher)@tawans , 🔥엘제이(LJ)@ijs1103

안녕하세요~ 마이노! 드디어 마지막 PR을 올립니다. 
그동안 많은 가르침 감사드리며 STEP3도 잘부탁드려요.

## 🤔고민하며 구현하려고 노력했던 점

### 화면 이동 방식의 변경
화면 이동 방식을 코드상에서 바로 확인이 가능하고 직관적이라는 장점이 있어
세그웨이 방식에서 프로그래밍 방식으로 리팩토링 하였습니다.

### Stepper 활용
스텝퍼(Stepper)는 사용자가 값을 증가 또는 감소시킬 수 있는 인터페이스 요소입니다. 스위프트에서는 UIStepper 클래스가 이러한 동작을 구현하는 데 사용됩니다. UIStepper는 일반적으로 버튼 두 개(증가 및 감소 버튼)와 현재 값을 나타내는 레이블이 함께 제공됩니다.
스텝퍼의 주요 속성 및 메서드는 다음과 같습니다:

**value**: 현재 값. 이 값은 스텝퍼에서 증가 또는 감소할 때마다 변경됩니다.
**minimumValue**: 스텝퍼에서 허용되는 최소 값.
**maximumValue**: 스텝퍼에서 허용되는 최대 값.
**stepValue**: 각 단계에서 값이 증가 또는 감소하는 크기.
**wraps**: 최소 및 최대 값에 도달하면 값을 감지하여 감소 또는 증가를 계속할지 여부를 나타냅니다.
**autorepeat**: 버튼을 길게 누르면 지속적으로 값을 변경할지 여부를 나타냅니다.

### 오토 레이아웃 적용
iOS 및 macOS 개발에서 사용되는 레이아웃 관리 시스템으로, 사용자 인터페이스 요소의 위치 및 크기를 동적으로 제어하기 위한 도구입니다. 오토레이아웃은 다양한 화면 크기 및 방향에서 일관된 사용자 경험을 제공하고, 다양한 디바이스에서 애플리케이션의 모습을 최적화하는 데 도움을 줍니다.

### 화면 사이의 데이터 공유
델리게이트 패턴을 사용하여 메인뷰컨과 재고수정뷰컨 양방향으로 데이터를 전달할 수 있도록 하였습니다.
델리게이트 패턴은 객체 간의 상호 작용을 위해 사용되는 디자인 패턴 중 하나이며, 프로토콜(Protocol)을 통해 구현됩니다. 델리게이트 패턴은 확장성이 좋고, 커스텀한 동작을 정의하기에 용이하므로 iOS 애플리케이션에서 자주 사용되는 것으로 공부 하였습니다.

### 쥬스주문 버튼이나 UIStpper에서 sender의 tag로 구분하여 분기 처리
sender 받는 부분을 currentTitle에서 tag로 변경하여 분기처리하였습니다.

## 🤔 클래스와 구조체를 언제 사용할것인가?
[Choosing Between Structures and Classes](https://developer.apple.com/documentation/swift/choosing-between-structures-and-classes)에 따르면 기본적으로 구조체를 사용하고 꼭 필요한 경우에만 클래스를 사용하라 권고하고 있습니다. 
그 이유 중에 하나로, 클래스는 런타임에 실행될 함수를 결정짓는 Table Dispatch를 하게 되어 컴파일 타임에 Direct Dispatch를 하는 구조체보다 필연적으로 성능이 떨어지는 문제가 있습니다.
성능뿐만 아니라 클래스를 사용할 경우 하나의 힙영역을 거의 모든 스레드에서 접근할 수  있기에 교착상황이나 경쟁상황 같은 문제가 발생하기도 합니다.
구조체는 `stack` 영역에 할당되고 각각의 스레드는 독립된 `stack` 영역을 가지고 있기 때문에 구조체는 이러한 문제에서 비교적 자유롭고 `thread-safe` 합니다.

#### 과일가게 -> class 
과일가게는 과일들을 프로퍼티로 가지고 있고 과일들의 수량 변경이 자주 일어나게 되어, 값을 매번 복사하여 할당하는 것보다 참조하는것이 유리하기 때문에 `class`를 사용하는것이 좋습니다.
또한 쥬스메이커에 의존성을 주입할때 과일가게가 클래스 타입이면 강한 참조를 통해 개발자의 의도대로 객체의 수명을 관리할 수 있게 됩니다.

#### 쥬스메이커 -> struct 
공식문서에서 정의한 클래스를 사용하는 상황을 다음과 같이 세가지가 있습니다. 
> 1) 인스턴스의 동일성을 보장하고 식별자를 가져야 하는 경우 
> 2) objective-c와의 상호운용성 (object-c로 만든 클래스나 api를 사용하는 경우) 
> 3) 상속 기능을 활용해야 할 때

쥬스메이커는 위 상황에 해당되지 않고 단순히 과일가게를 프로퍼티로 소유하고, 쥬스를 만드는 메서드를 가지고 있기 때문에 `struct`로 구현하는게 좋습니다.

## ✅ 프로젝트 수행 중 핵심 경험

- [x] Swift API Design Guide에 따른 이름짓기
- [x] 소스코드에 불필요한 코드 및 코멘트 남기지 않기
- [x] 메서드의 기능단위 분리
- [x] 요구사항에 따른 타입의 정의
- [x] 타입의 캡슐화/은닉화
- [x] 상황에 알맞은 상수/변수의 올바른 선택
- [x] 내비게이션 바 및 바 버튼 아이템의 활용
- [x] 얼럿 컨트롤러 활용
- [x] Stepper 활용
- [x] Modality의 활용
- [x] 화면 사이의 데이터 공유
- [x] 오토레이아웃 시작하기

2023-12-21 06:53 UTC, Mino777 requested changes
안녕하세요!! Asher, LJ!

STEP 3 진행하시느라 정말 수고 많으셨습니다!!🥳

UML작성 너무 좋습니다! 현업에서도 순서도 및 UML을 종종 그립니다ㅎㅎ
정말 복잡한 로직이 필요한 피쳐가 기획되면 기획자와 같이 회의실 잡고 같이 그릴때도 있었어요ㅎㅎ
정교하게 그릴 필요까지는 없으니, 가볍게 주요 컴포넌트들을 바로바로 도식화 할 수 있는 수준까지만 되더라도 아주 도움이 많이 됩니다👍

---------------------------------------------------------------------------------------

## 코멘트

### 칭찬 드리고 싶은 점
- UML 및 순서도를 작성하신 점👏
- Stepper를 활용해보신 점👏
- 오토레이아웃을 적용해보신 점👏
- 화면 이동 방식을 변경해보신 점👏
- Class와 Structure에 대한 고민을 해보신점👏

---------------------------------------------------------------------------------------

### 고민했던점
> 오토 레이아웃 적용
좋습니다! 오토레이아웃에 대한 개념은 꼭 제대로 잡고 가셔야합니다. 현업에 나가셨을 때 UI는 빠르게 그리고 뒷단의 로직을 고민하고 좋은 코드를 작성하는 작업에 최대한 많은 시간을 쏟으셔야 하기 때문에 UI를 그리는 작업에서 시간을 많이 뺏기면 안됩니다👍 다양한 UI를 직접 그려보시면서 샘플을 많이 만들어 두시면 도움이 될 때가 많으니 꼭 직접 그려보시는걸 추천드립니다ㅎㅎ (그래서 최대한 코드만으로 UI를 짜두는게 나중에 좋습니다!)

> 화면 사이의 데이터 공유
양방향으로 데이터를 전달하는 구조는 바람직하진 않습니다. 양방향의 데이터 흐름의 경우 복잡성도 증가되고, 결합도도 높아지고, 테스트도 어려워집니다. 데이터 전달 흐름은 가능한 단방향으로 이루어지도록 설계하는것이 좋습니다. 이 부분은 지금은 이해하기 어려우실 수 있으니 나중에 학습 하시다보면 단방향이라는 키워드가 나오실거에요! 그때 가서 딥하게 고민해보시고 학습해보시면 좋을 것 같습니다👍

> 쥬스주문 버튼이나 UIStpper에서 sender의 tag로 구분하여 분기 처리
해당 부분의 코멘트는 아래 코드 코멘트에 남겨두었습니다!

> 클래스와 구조체를 언제 사용할 것인가?
메모리 레벨까지 학습하시는 점 너무너무 좋습니다👍 해당 고민은 정말 할 수 있는 한 딥하게 하시면 좋습니다. 저도 올해 처음으로 면접관으로 참석 했을 때 면접자분들을 보면 다는 아니겠지만 유독 해당 질문에 답변을 완벽하게 잘하시는 분들이 다른 질문들도 답변이 좋더라구요! 면접 단골 질문이니 나중에 캠프 끝나시고 면접 시즌 되시면 툭 치면 다다닥 나오게 준비해두시면 좋습니다ㅎㅎ

2023-12-21 06:53 UTC, Mino777 commented on JuiceMaker/JuiceMaker/Controller/ModifyInventoryViewController.swift
> +    @IBOutlet weak var mangoStepper: UIStepper!
stepper를 사용해보셨네요! 좋습니다👍

2023-12-21 06:53 UTC, Mino777 commented on JuiceMaker/JuiceMaker/Controller/ModifyInventoryViewController.swift
> +    }
계속 프로젝트를 진행하시면서 이런 과일들에 대한 분기가 계속해서 이루어지고 있네요!

슬슬 귀찮지 않나요?ㅎㅎ
어떻게 하면 이런 분기문들을 간소화시킬 수 있을까요?

힌트로는 enum의 CaseIterable 이라는 프로토콜이 있습니다.
caseIterable 프로토콜에 대한 학습 및 리팩토링도 한번 해보시죠!💪

2023-12-21 06:53 UTC, Mino777 commented on JuiceMaker/JuiceMaker/Controller/ModifyInventoryViewController.swift
> +    }
이 부분도 CaseIterable을 통한 간소화 해보시죠!

2023-12-21 06:53 UTC, Mino777 commented on JuiceMaker/JuiceMaker/Controller/ModifyInventoryViewController.swift
> +    }
이 부분도 CaseIterable을 통한 간소화 해보시죠!

2023-12-21 07:18 UTC, ijs1103 commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +                )
그냥 실수였네요 허허;; 다른 AlertBuilder도 줄바꿈 적용하겠습니다

2023-12-21 11:23 UTC, tawans commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
>      }
```swift    
@IBAction func fruitJuiceOrderButtonTapped(_ sender: UIButton) {
        
        switch sender {
        case strawberryJuiceOrderButton:
            showResultAlert(juiceMaker.makeJuice(juiceMenu: .strawberry))
        case bananaQuantityLabel:
            showResultAlert(juiceMaker.makeJuice(juiceMenu: .banana))
        case pineappleJuiceOrderButton:
            showResultAlert(juiceMaker.makeJuice(juiceMenu: .pineapple))
        case kiwiJuiceOrderButton:
            showResultAlert(juiceMaker.makeJuice(juiceMenu: .kiwi))
        case mangoJuiceOrderButton:
            showResultAlert(juiceMaker.makeJuice(juiceMenu: .mango))
        case strawberryBananaJuiceOrderButton:
            showResultAlert(juiceMaker.makeJuice(juiceMenu: .straberryBanana))
        case mangoKiwiJuiceOrderButton:
            showResultAlert(juiceMaker.makeJuice(juiceMenu: .mangoKiwi))
        default:
            showResultAlert(.failure(JuiceError.unknown))
        }
    }
```

버튼 자체 분기로 변경하였습니다!

2023-12-21 11:27 UTC, tawans commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
>  }
그렇네요;;; 필요없는 juiceMadeDelegate부분 삭제 하였습니다.

2023-12-21 11:31 UTC, tawans commented on JuiceMaker/JuiceMaker/Controller/ModifyInventoryViewController.swift
> +    }
그렇군여~!! 감사합니다 해당 순서로 변경했습니다.!

2023-12-22 04:18 UTC, tawans commented on JuiceMaker/JuiceMaker/Controller/ModifyInventoryViewController.swift
> +    }
```swift
    private func setStepperValue(for fruit: FruitName, to value: Int, atIndex index: Int) {
        fruitSteppers[index].value = Double(value)
    }
```
caseIterable 프로토콜적용해서 리팩토링 했습니다!

2023-12-22 04:19 UTC, tawans commented on JuiceMaker/JuiceMaker/Controller/ModifyInventoryViewController.swift
> +    }
```swift
    private func updateFruitLabel(fruitName: FruitName, quantity: Int?, atIndex index: Int) {
        guard let fruitQuantity = quantity else {
            return
        }
        fruitquantityLabels[index].text = String(fruitQuantity)
    }
```
caseIterable 프로토콜적용해서 리팩토링 했습니다!

2023-12-22 04:19 UTC, tawans commented on JuiceMaker/JuiceMaker/Controller/ModifyInventoryViewController.swift
> +    }
```swift
    @IBAction func fruitStepperValueChanged(_ sender: UIStepper) {
        guard let index = fruitSteppers.firstIndex(of: sender) else {
            return
        }
        let fruit = FruitName.allCases[index]
        updateFruitQuantity(fruit, with: Int(sender.value), atIndex: index)
    }
```
caseIterable 프로토콜적용해서 리팩토링 했습니다!

2023-12-22 04:21 UTC, tawans commented on JuiceMaker/JuiceMaker/Controller/ModifyInventoryViewController.swift
>  }
디스코드 DM으로 메시지 드렸습니다.

2023-12-22 07:12 UTC, Mino777 approved these changes
Step 3 진행하시느라 정말 정말 고생많으셨어요💪💪

방학 동안에는 꼭 푹 쉬시고 만약에 학습하더라도, 새로운 걸 공부하기 보단 지금까지 해왔던걸 정리하는 시간을 가지셨으면 좋겠어요!

그리고 고민하는 시간을 너무 많이 사용하지 마세요! 제가 추천드리는 고민 시간은 딱 1시간이면 충분합니다!
1시간을 고민했는데 모르겠다 생각이 드시면 주저없이 DM 보내주세요!!💪💪

행복한 크리스마스 되세요🎉🎉

2023-12-22 07:12 UTC, Mino777 commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +    }
해당 코드에서

```swift
private func moveModifyInventoryView() {
        guard let modifyInventoryVC = self.storyboard?.instantiateViewController(withIdentifier: "ModifyInventoryViewController") as? ModifyInventoryViewController else { return }

        modifyInventoryVC.fruitStore = juiceMaker.fruitStore

        self.navigationController?.pushViewController(modifyInventoryVC, animated: true)
    }
```

요런식으로만 fruitStore를 프로퍼티를 통한 의존성 주입으로 주입해주면 fruitStore는 class 타입 즉 Reference 타입이기에 결국엔 두 화면 모두 같은 재고 데이터를 참조할 수 있겠죠?!

그럼 두 화면간의 데이터 전달이라기 보단, 단방향으로 fruitStore를 통한 데이터 흐름이 이루어질 수 있을 것 같아요!

천천히 고민해보시고 막히시는 부분 있으면 바로바로 DM 주세요💪

2023-12-22 07:12 UTC, Mino777 commented on JuiceMaker/JuiceMaker/Controller/ModifyInventoryViewController.swift
> +    private var fruitQuantity = [FruitName: Int]()
요고 대신

```swift
private var fruitStore: FruitStore?
```
요렇게 정의해서 fruitStore를 주입받으면 될 것 같네요!

2023-12-22 07:12 UTC, merged