쥬스자판기 [STEP 3] 루피, 홍
tasty-code/ios-juice-maker pull request #111
Opened 2023-12-21 07:48 UTC by ujhong7

담당 리뷰어 : @GREENOVER (green)
팀원: @kimdj1102 (loffy), @ujhong7 (�hong)

---
클래스 다이어그램
![Untitled](https://github.com/tasty-code/ios-juice-maker/assets/108393988/48b7d4ab-bbae-4bbe-a1fa-4a5d6a268e74)

---
시퀀스 다이어그램 
![스크린샷 2023-12-15 오후 3 07 53](https://github.com/tasty-code/ios-juice-maker/assets/108393988/79811f33-ffda-4d74-ba3c-bba08f7ef34b)

---

### 오토 레이아웃

**iPhone 15 외에 다른 시뮬레이터에서도 UI가 정상적으로 보일 수 있도록 오토레이아웃을 적용했습니다.**

<img width="506" alt="15e1e56206a5f615" src="https://github.com/tasty-code/ios-juice-maker/assets/108393988/566eac63-04c9-488a-9830-de0e51c85bf8">

https://github.com/tasty-code/ios-juice-maker/assets/108393988/2a31a030-2ab6-4030-8dab-3de0ab5a6f3f

## 고민한 점
    

### 화면 간 데이터 전달 방식

> Notification vs Delegate

- Notification 방식은 연관성이 없는 객체들끼리 데이터를 전달할 때 적합함
- Delegate 방식은 하위 뷰에서 상위 뷰로 데이터 전달을 할 때 적합함

- **Delegate** 패턴은 **일대일 통신에 사용**되며, 델리게이트 객체와 이를 구현하는 객체 간의 **직접적인 연결이 필요**합니다. 
**Notification** 패턴은 **일대다 통신**에 사용되며, 관찰자 객체들이 **간접적으로   연결**됩니다.
- **Delegate** 패턴은 **프로토콜을 통해 명시적**으로 델리게이트 **메서드를 정의하고 구현**합니다.
 **Notification** 패턴은 Notification **이름을 통해 이벤트를 식별**하고 **NotificationCenter를 통해 등록 및 수신**합니다.
- **Delegate** 패턴은 **컴파일 타임**에 델리게이트 객체의 **메서드가 정의**되어야 하며, **실행 시점에 동적으로 메서드가 호출**됩니다. 
**Notification** 패턴은 이벤트를 **보내는 객체와 관찰자 객체 간에 결합도가 낮아서** **런타임**에 동작합니다.

> 데이터 전달 진행 순서
1. 두번째 화면에서 "저장"버튼을 누름
2. 두번째 화면의 Label의 값을 inventory에 저장함
3. 첫번째 화면의 Label의 값을 inventory의 값으로 다시 변경함

처음에는 Notification방식을 사용했었지만, 이렇게 두번째 화면에서 첫번째 화면의 인스턴스인 label에 접근해야하기 때문에 그 관계가 명확하다보니 **Delegate**방식을 사용하게 되었습니다. 물론 Notification방식도 하위에서 상위로 접근할 수 있지만, 모든 객체에게 신호를 보내기 때문에 효율성이 떨어지기 때문입니다. 

1. 우선, 프로토콜로 Delegate를 선언해주고,
```
protocol StockManagementViewControllerDelegate: AnyObject {
    func updateStockData(updatedData: [Fruit: Int])
}
```
2. 두번째 페이지에 Delegate변수를 선언해줍니다.
```
weak var delegate: StockManagementViewControllerDelegate?
```
> !! 여기서 weak으로 약한 참조 선언을 한 이유는 protocol을 통해 서로가 서로를 참조하는 순환참조를 하고 있기 때문에 두번째 페이지가 dismiss될 때 정상적으로 메모리에서 할당 해제를 해주기 위함 !!

3. 첫번쨰 페이지에 함수를 선언해주고, Delegate를 채택합니다.
```
extension JuiceMakingViewController: StockManagementViewControllerDelegate {
    func updateStockData(updatedData: [Fruit: Int]) {
        juiceMaker.fruitStore.updateInventory(updatedData)
        showNumberOnLabel(fruits: juiceMaker.fruitStore.inventory)
    }
}
```
4. 마지막으로, 첫번째 페이지에서 두번째 페이지의 delegate변수를 self로 선언해줍니다.
```
stockManagementVC.receivedFruitInventoryData = juiceMaker.fruitStore.inventory
            stockManagementVC.delegate = self
```
이렇게 Delegate로 데이터 전달을 해보니 원하는 상위 화면의 프로퍼티에 직접 접근 할 수 있어서 정말 간편했습니다.

### 구조체와 클래스 선택 기준
구조체는 불변성과 값 복사의 특성으로 인해 작은 크기의 데이터나 불변 데이터를 표현하는 데 유용합니다.
 반면에 클래스는 참조 복사로 인해 공유 상태와 변경 가능성이 필요한 경우에 적합합니다. 
`JuiceMaker`이 구조체로, `FruitStore`가 클래스로 구현된 이유에 대한 설명은 다음과 같습니다:

1. **값 복사 대 참조 복사:**
    - **JuiceMaker (Struct):** `JuiceMaker`는 값 복사를 가지는 것이 적합한 것으로 보입니다. 값 복사는 인스턴스를 전달할 때 해당 인스턴스의 사본을 원할 때 사용됩니다. 이는 각 코드 부분이 독립적인 복사본과 작업하도록 보장하며, 인스턴스가 비교적 작고 불변일 때 적합합니다.
    - **FruitStore (Class):** `FruitStore`는 참조 복사를 가지는 경우가 많습니다. 여러 부분에서 동일한 인스턴스를 참조하려면 참조 복사가 필요합니다. 여러 부분에서 인벤토리에 액세스해야 하는 경우 클래스를 사용하면 같은 인스턴스를 참조할 수 있습니다.
2. **불변성:**
    - **JuiceMaker (Struct):** 구조체는 일반적으로 불변성이 권장되는 상황에 적합합니다. `JuiceMaker` 인스턴스가 생성 후에 변경되지 않아야 하는 경우 구조체를 사용하면 모든 속성이 상수로 만들어 불변성을 강제할 수 있습니다.
    - **FruitStore (Class):** 클래스는 참조 타입으로 불변성에 대한 제약이 덜합니다. **인벤토리 상태를 시간이 지남에 따라 수정**해야 하는 경우 클래스를 사용하면 더 많은 유연성을 얻을 수 있습니다.
3. **복사:**
    - **JuiceMaker (Struct):** `JuiceMaker`가 구조체이므로 함수에 전달하거나 변수에 할당할 때 사본이 생성됩니다. 한 인스턴스의 변경이 다른 인스턴스에 영향을 미치지 않도록 보장하는 데 유용합니다.
    - **FruitStore (Class):** 클래스는 참조 타입이므로 인스턴스를 전달할 때 해당 인스턴스의 참조가 전달됩니다. 공유 상태나 객체가 큰 경우 클래스를 사용하면 효율적일 수 있습니다.

---

2023-12-21 08:41 UTC, GREENOVER requested changes
@ujhong7 @kimdj1102 
두분 마지막 스텝까지 완주하셨네요!! 너무 고생 많으셨습니다ㅎㅎ 🚀
코드의 질도 좋고 동작은 충분히 이상없구요!
그래서 이번 리뷰의 중점은 코드의 가독성과 유지보수를 생각해서 조금 더 줄여볼 수 있는 방향으로 드려봤습니다.
두분이서 한번 코멘트를 보고 어떤것이 더 괜찮을지 아니면 다른 방법은 없을지 한번쯤 고민해보면 좋을것 같아요 😃
아..! 추가로 스텝을 다 마치셨으니 지금까지 PR을 올리면서 UML 구조도라던지 트러블슈팅, 고민한 흔적들 이런것도 리드미를 통해서 잘 기록해두면 추후 큰 자산이 됩니다ㅎㅎ
***
### 칭찬 드리고 싶은 부분
- 커밋 관리를 끝까지 아주 잘 해주셨네요 💯
- 네이밍, 접근제어 등 스텝이 갈수록 신경을 잘 쓰시는 모습이 보입니다 💯
- 딜리게이트 패턴을 잘 이해하고 사용하시는것 같아요 💯
***
이 외 고민하셨던 화면 전환 방식에서의 딜리게이트 채택 이유 그리고 구조체, 클래스를 채택할때의 기준들 모두 저도 이견 없습니다!ㅎㅎ
충분히 적절한 방향으로 고민하시고 코드에도 잘 녹아져있어보입니다.
최고입니다 👍

스텝3까지 3주간 열심히 달려오셨는데 그만큼 유종의 미를 충분히 잘 거두셨을거라 생각되고 코드 퀄리티도 아주 많이 향상되었다고 느껴져요!
고생 많으셨습니다~~
꼭 수정해야될 부분은 없지만 한번 코멘트를 잠깐 고민해봐도 좋을것 같아서 우선은 Request Changes로 남겨둘께요!
지금 코드 그대로 머지되어도 되니 언제든 재리뷰 요청 혹은 머지 요청을 해주세요 😁
연말은 따뜻하게 보내시길 바래요!

2023-12-21 08:41 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/JuiceMakingViewController.swift
> +extension JuiceMakingViewController: StockManagementViewControllerDelegate {
LGTM 👍

2023-12-21 08:41 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/StockManagementViewController.swift
> +    @IBAction func doneButtonPressed(_ sender: Any) {
두 메서드 모두 마찬가지로 private해도 될것 같습니다!

2023-12-21 08:41 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/StockManagementViewController.swift
> +    @IBAction func cancleButtonPressed(_ sender: Any) {
cancel이 맞는 워딩같습니다 🙋🏻

2023-12-21 08:41 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/StockManagementViewController.swift
> +    weak var delegate: StockManagementViewControllerDelegate?
weak를 붙여주신 이유가 궁금합니다~ㅎㅎ

2023-12-21 08:41 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/StockManagementViewController.swift
> +private extension StockManagementViewController {
setupTargetActionOnStepper와 setupStepper 코드에서 어떻게 보면 중복되는것이 많은데 steppers와 labels를 별도 프로퍼티로 만들고 이를 활용하여 반복을 돌도록 하면 조금 코드를 줄일 수 있을것 같은데 어떻게 생각하시나요~?
왜냐면 setupStepper에서 추후 과일이 추가되면 case를 관리해야되는것도 있고, 만약 setupStepperxxx와 같이 내부 동일한 for문을 똑같이 돌때 동일하게 case별로 또 구성해줘야할것 같아서 이와 같은 느낌은 어떠신지 제안드려봅니다..!

```swift
private extension StockManagementViewController {
  var steppers: [Fruit: UIStepper] {
    return [.strawberry: changeAmountOfStrawberryStepper,
            .banana: changeAmountOfBananaStepper,
            .pineapple: changeAmountOfPineAppleStepper,
            .kiwi: changeAmountOfKiwiStepper,
            .mango: changeAmountOfMangoStepper]
  }
  
  var labels: [Fruit: UILabel] {
    return [.strawberry: numberOfStrawberryLabel,
            .banana: numberOfBananaLabel,
            .pineapple: numberOfPineAppleLabel,
            .kiwi: numberOfKiwiLabel,
            .mango: numberOfMangoLabel]
  }
  
  func setupTargetActionOnStepper() {
    for (fruit, stepper) in steppers {
      stepper.addTarget(self, action: #selector(changeAmount(_:)), for: .valueChanged)
    }
  }
  
  @objc func changeAmount(_ sender: UIStepper) {
    for (fruit, stepper) in steppers {
      if sender == stepper, let result = receivedFruitInventoryData[fruit] {
        labels[fruit]?.text = (Int(sender.value) + result).description
        break
      }
    }
  }
  
  func setup(number: Int, on stepper: UIStepper) {
    stepper.minimumValue = -Double(number)
    stepper.maximumValue = 100
  }
  
  func setupStepper(fruits: [Fruit: Int]) {
    for (fruit, number) in fruits {
      if let stepper = steppers[fruit] {
        setup(number: number, on: stepper)
      }
    }
  }
}
```

2023-12-21 08:41 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/StockManagementViewController.swift
> +private extension StockManagementViewController {
setupTargetActionOnStepper, changeAmount, setupStepper가 비교적 간결해지는 이점이 있습니다.
이제 나중에 과일이 추가되더라도 세 메서드 모두 케이스를 추가하지 않아도 steppers, labels 변수만 건들면되서 조금 더 유지보수가 편하지 않을까 싶어요~!

2023-12-21 08:41 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/StockManagementViewController.swift
> +private extension StockManagementViewController {
요 부분도 위 리뷰 코멘트처럼 가독성을 높이면서 중복을 줄이기 위해서 딕셔너리 변수로 관리하면 어떨까요..!?
과일이 수천개가 되었을때를 고려해서 어떤것이 유지보수에 더 편리하고 가독성이 나을지 두분에서 한번 고민해봐도 좋을것 같은 포인트입니다 🙋🏻

2023-12-22 07:35 UTC, kimdj1102 commented on JuiceMaker/JuiceMaker/Controller/StockManagementViewController.swift
> +    @IBAction func doneButtonPressed(_ sender: Any) {
네 수정했습니다! 저희가 우선 Label과 Stepper 변수들도 private으로 선언해주었는데 이 변수들도 private으로 접근제어를 해주는게 필수적인 건가요?

2023-12-22 07:38 UTC, kimdj1102 commented on JuiceMaker/JuiceMaker/Controller/StockManagementViewController.swift
> +    weak var delegate: StockManagementViewControllerDelegate?
weak으로 약한 참조 선언을 한 이유는 protocol을 통해 서로가 서로를 참조하는 순환참조를 하고 있기 때문에 두번째 페이지가 dismiss될 때 정상적으로 메모리에서 할당 해제를 해주기 위해서 였습니다.

2023-12-22 08:19 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/StockManagementViewController.swift
> +    @IBAction func doneButtonPressed(_ sender: Any) {
필수적이지는 않습니다~!

2024-01-02 01:30 UTC, Tacocat-tastycode commented
프로젝트 진행 기간 종료로 PR Close

2024-01-02 01:30 UTC, closed without merging