Feature noam&paul step3
tasty-code/ios-juice-maker pull request #113
Opened 2023-12-22 01:26 UTC by earths-voluble

## 인사말
@yim2627 @Gnoam-R @earths-voluble

안녕하세요 지성!

Juice Maker Step3 리뷰 요청 드립니다.

Step3에서는 AutoLayout을 사용해서 과일 저장소 뷰를 조절 했습니다. 그리고 싱글톤 패턴을 사용하여 서로 다른 클래스에 FruitStore 객체의 의존성을 공유하는 방식을 채택하여 UI에 값을 적용하는 코드를 구현하게 되었습니다.

## 구현 내용 설명

- `StockViewController` AutoLayout 적용
<img width="1000" alt="Screenshot 2023-12-22 at 10 25 24" src="https://github.com/tasty-code/ios-juice-maker/assets/103843007/a9521b71-e45e-4fba-9569-f36728baffc3">

    
- 네비게이션 바에 제목 및 닫기 버튼 추가
    - `StockVIewController` 에서 닫기 버튼을 클릭시 `dismiss` 를 실행, 모달을 닫고 메인 뷰로 화면이 전환 됩니다.
- Stepper & 재고 수량 Label 반영
    - Stepper의 심벌에 초기 값을 저장하고 버튼이 눌릴 때 변경되는 값을 `Label`과 `FruitStore` 에 저장합니다.
    - Stepper의 최소값을 설정하여 음수로 값이 내려가는 현상을 방지했습니다.
- Main과 Modal화면의 과일 수량 일체화
    - `StockViewController`의 닫기 버튼을 클릭 시 `StoreViewController`의 재고 수량 화면에 변경된 과일 값을 입력합니다.
    - 위 요구사항을 동작시키기 위해서 `FruitStore` 객체를 싱글턴으로 생성, 쥬스 주문 또는 `StockVIewController`의 버튼 클릭으로 변경되는 과일의 수량값을 즉시 저장하고 화면에 적용하는 로직을 구현했습니다.

### UML
![JuiceMaker](https://github.com/tasty-code/ios-juice-maker/assets/103843007/ef29a75b-7845-45d5-b68e-8e9e9f457609)
## 쥬스 메이커 동작 화면

<br>
<h1 align="center">
<br>

![292069471-a1dc30b8-655d-4510-8b23-ad9a3ddd2468](https://github.com/tasty-code/ios-juice-maker/assets/103843007/af11e312-1a86-4e72-b78b-e5a4324122fa)

<br>

</h1>
<br>

## 궁금한점

서로 다른 ViewController에서 동일한 클래스에 있는 과일 수량 값을 가져와 화면에 뿌려주는 방법에 대해 다양한 방법들이 존재하겠지만 저희는 싱글톤 패턴을 적용했습니다. 이유는 현재는 2개의 클래스에서 `FruitStore` 의  의존성을 받고 있지만 더 많은 클래스에서 사용 되는 경우 객체를 하나만 생성해도 여러 곳에서 가져와 사용할 수 있게 하는 점이 장점이라 생각했어요. 하지만 사용하게 되면서 순환 참조와 같은 문제점과 대규모 프로젝트에서 단위 테스트에 대한 어려움이 있을것이다 라는 이야기를 들어서 더 좋은 방법을 찾고자 합니다. 지성이라면 이 프로젝트에서 어떤 방법을 사용하실 건가요?

2023-12-22 03:20 UTC, yim2627 requested changes
안녕하세요 노움 폴!

이번 스텝도 수고많으셨습니다~ UML도 잘 작성해주셨네요 👍

싱글톤에 대한 제 입장은 지양은 하되 쓸거면 잘쓰자입니다. 이유는 싱글톤 객체는 프로젝트 규모가 커질 수록 싱글톤 객체를 의존하는 객체들이 많아져 SideEffact가 발생할 확률이 높고, 문어발식 의존이 생긴다면 싱글톤 객체 코드 하나만 변경되도 많은 코드들이 깨져버리는 OCP(개방폐쇄원칙)을 위배하게 되므로 좋지 않다고 생각합니다.
다만 뭐든 적당한건 괜찮다고 생각합니다. 싱글톤 패턴 또한 생겨난 이유가 있을테고 실제로 가장 많이 사용되는 패턴이기도 하니까요! (FileManager, UserDefault 등등)  의존성 역전, 추상화 등등을 작업하여 리팩토링과 테스트를 유용하게 한다면 괜찮다고 생각해요.

저의 경우엔 싱글톤도 괜찮다고 생각하지만, 의존성 주입, DI Container 등의 방식을 사용할 것 같은데, 이 방식들은 아직 적용할 단계가 아니니 관심 있으시다면 의존성 주입(Dependency Injection)정도에 대해서 간단히 공부해보시면 도움이 될 것 같네요.

또 궁금하신 점이 있으시다면 언제든 DM 주세요!

2023-12-22 03:20 UTC, yim2627 commented on JuiceMaker/JuiceMaker/Controller/StoreViewController.swift
>      }
`StockViewController`와 달리 viewWillAppear에서 initView를 호출해주신 이유가 있을까요?

2023-12-22 03:20 UTC, yim2627 commented on JuiceMaker/JuiceMaker/Controller/StoreViewController.swift
>          guard let secondVC = storyboard?.instantiateViewController(withIdentifier: "StockViewController") as? StockViewController else { return }
"StockViewController" 같은 identifier를 관리할 수 있는 방법은 뭐가 있을까요?

2023-12-22 04:21 UTC, Gnoam-R commented on JuiceMaker/JuiceMaker/Controller/StoreViewController.swift
>      }
`ViewWillAppear`과 `ViewDidLoad`의 차이를 설명드리자면 `ViewDidLoad`는 앱이 실행되어 `VIewController`가 메모리에 올라오는 그 순간에만 Init되어 다시 불러지는 일이 없지만 `ViewWillAppear`의 경우 특정 View가 화면에 나타나는 때마다 호출이 됩니다.

`StoreViewController`에서 `StockViewController`로 이동하고 다시 `StoreViewController`로 돌아올때 `StockViewController`에서 변경한 과일 재고 정보를 반영하기 위해서는 `ViewWillAppear`를 통해 다시 변경하고자 하는 화면을 초기화 시켜줘야 했습니다.

또한 화면 이동 방식이 `Modal`인 경우 아래와 같이 `modal` 속성을 변경해줘야 `ViewWillAppear`이 나타났습니다.

```swift
secondVC.modalPresentationStyle = .fullScreen
```

왜 `Navigation`이 아닌 `Modal`인 경우 속성을 변경하지 않으면 화면을 닫을때 `ViewWillAppear`가 나타나지 않았던 걸까요…?

2023-12-22 04:21 UTC, earths-voluble commented on JuiceMaker/JuiceMaker/Controller/StockViewController.swift
> +        fruitStore.fruits[selectedFruit.rawValue] = intSender
네이밍 수정 완료했습니다!

2023-12-22 07:57 UTC, earths-voluble commented on JuiceMaker/JuiceMaker/Controller/StoreViewController.swift
>          guard let secondVC = storyboard?.instantiateViewController(withIdentifier: "StockViewController") as? StockViewController else { return }
> `as?`는 무엇을 하는 코드일까요? `as`, `as!`에 대해서도 설명 부탁드립니다.

`as`는 다운캐스팅 키워드로써, 하위 클래스의 인스턴스를 사용할 수 있게 하지만 실패의 위험이 있기 때문에, 다운캐스팅이 실패할 경우 `as?`는 옵셔널 값을 반환하고, `as!`는 강제 언래핑과 마찬가지로 크래시가 일어나게 됩니다.

> "StockViewController" 같은 identifier를 관리할 수 있는 방법은 뭐가 있을까요?

identifier들을 관리하는 enum인 `VCIdentifiers`를 추가해 보았습니다.

2023-12-23 14:38 UTC, yim2627 commented on JuiceMaker/JuiceMaker/Controller/StoreViewController.swift
>      }
노출 스타일에 따라 뷰라이플사이클이 달라질 수 있습니다. 이 부분에 대해서도 추가적으로 공부해보시면 도움이 되실거에요!

2023-12-23 14:40 UTC, yim2627 approved these changes

2023-12-23 14:40 UTC, merged