쥬스 자판기 [STEP 3] Matthew, 희동
tasty-code/ios-juice-maker pull request #114
Opened 2023-12-22 02:05 UTC by kimbs5899

@July911
안녕하세요! Matthew, 희동입니다! 😊

STEP 3 PR 올립니다 !!!!

- 코드 리뷰 반영
- Refactoring 진행
- Error 처리
- 네이밍 컨벤션
- branch 컨벤션

Alert을 UIViewController의 extension으로 추가하여 구현하고 okAction을 클로저를 처리하는 과정중
순환참조에 대한 문제를 리뷰를 통해 깨닫고 수정하게 되었습니다.
아직 ARC에 대한 내용이 이해된 부분이 많진 않지만, 클로저에서 self 키워드의 강한 참조로 인한 메모리에서 해제 되지 않는 경우를 대비하여
weak self, unowned self 를 통해 약한 참조, 미소유 참조로 잡아주는 부분에 대해 알게 되었습니다!

좋은 리뷰 감사합니다~!

2023-12-22 02:48 UTC, July911 requested changes

2023-12-22 02:48 UTC, July911 commented on JuiceMaker/JuiceMaker.xcodeproj/project.pbxproj
>  		C1ED27C92B217B530013F195 /* DetailViewController.swift */ = {isa = PBXFileReference; fileEncoding = 4; lastKnownFileType = sourcecode.swift; path = DetailViewController.swift; sourceTree = "<group>
DetailViewController가 뭐죠 ?

2023-12-22 02:48 UTC, July911 commented on JuiceMaker/JuiceMaker.xcodeproj/project.pbxproj
> +				C17402B52B317ACA00196D0D /* JuiceMakerViewText.swift in Sources */,
JuiceMakerViewText 
이름이 모호한 것 같습니다.

2023-12-22 02:48 UTC, July911 commented on JuiceMaker/JuiceMaker.xcodeproj/project.pbxproj
>  				E4AE21D72B22F5D9004484C0 /* Message.swift in Sources */,
Message 가 뭘까요 ?

2023-12-22 02:48 UTC, July911 commented on JuiceMaker/JuiceMaker/Controller/DetailViewController.swift
> +            print(JuiceMakerError.notFoundFont.description)
폰트를 못불러왔을때 유저가 print문을 볼 수 있나요 ? 다른방법은 없나요 ?

2023-12-22 02:48 UTC, July911 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +                self.showDetailView()
unowned 와 weak의 차이는 뭔가요 ? 
JuiceMaker 는 싱글톤 아닌가요 ?

2023-12-22 02:48 UTC, July911 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        guard let controller = self.storyboard?.instantiateViewController(identifier: JuiceMakerViewText.detailViewControllerText.description) as? DetailViewController else {
identifier를 만드는 다른 방법은 없나요 ?

2023-12-22 02:48 UTC, July911 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
>      private func showDetailView() {
show라는 이름 좋습니다 .

2023-12-22 02:48 UTC, July911 commented on JuiceMaker/JuiceMaker/Error/JuiceMakerError.swift
> +enum JuiceMakerError: Error, CustomStringConvertible {
CustomStringConvertible 이건 어디에쓰나요 ?

2023-12-22 03:59 UTC, kimbs5899 commented on JuiceMaker/JuiceMaker.xcodeproj/project.pbxproj
>  		C1ED27C92B217B530013F195 /* DetailViewController.swift */ = {isa = PBXFileReference; fileEncoding = 4; lastKnownFileType = sourcecode.swift; path = DetailViewController.swift; sourceTree = "<group>
뷰가 2개뿐이라서 메인뷰와 상세페이지뷰로 나눠 상세페이지를 Detail 뷰로 지정하여 그 뷰에 해당하는 컨트롤러를 DetailViewController로 만들었습니다!

2023-12-22 03:59 UTC, kimbs5899 commented on JuiceMaker/JuiceMaker.xcodeproj/project.pbxproj
> +				C17402B52B317ACA00196D0D /* JuiceMakerViewText.swift in Sources */,
조금더 고민해서 수정해보겠습니다!

2023-12-22 04:00 UTC, kimbs5899 commented on JuiceMaker/JuiceMaker.xcodeproj/project.pbxproj
>  				E4AE21D72B22F5D9004484C0 /* Message.swift in Sources */,
결과에 대한 응답 메세지를 묶어 하나의 Message enum으로 만들었습니다!
네이밍이 혹시 혼동이 오신다면 고민해보겠습니다!

2023-12-22 04:02 UTC, kimbs5899 commented on JuiceMaker/JuiceMaker/Error/JuiceMakerError.swift
> +enum JuiceMakerError: Error, CustomStringConvertible {
보통 enum의 케이스별 텍스트 표현을 사용하고싶을때 사용하는걸로 알고있습니다!
텍스트적인 표현을 커스터마이즈하기 위해 사용했습니다!

2023-12-22 04:02 UTC, kimbs5899 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
>      private func showDetailView() {
감사합니다~!

2023-12-22 04:02 UTC, kimbs5899 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        guard let controller = self.storyboard?.instantiateViewController(identifier: JuiceMakerViewText.detailViewControllerText.description) as? DetailViewController else {
if let을 사용할수 있을것 같습니다!

2023-12-22 04:06 UTC, kimbs5899 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +                self.showDetailView()
unowned 미소유 참조이고, weak는 약한 참조입니다!
네! 싱글톤입니다! 싱글톤의 경우 강한참조가 발생 할 수 있습니다!

2023-12-22 04:09 UTC, kimbs5899 commented on JuiceMaker/JuiceMaker/Controller/DetailViewController.swift
> +            print(JuiceMakerError.notFoundFont.description)
print문은 유저가 볼수 없습니다. 만약 유저가 보게할려면 Alert을 통해 경고 메세지를 띄워야하는데
폰트와 같이 내부에 저장한 파일이 누락된 경우까지 사용자에게 제공해야할 메세지가 아니라고 생각합니다.
개발자가 디버깅 또는 테스트를 통해 알아야할 메시지라고 판단했습니다!

2024-01-02 01:31 UTC, Tacocat-tastycode commented
프로젝트 진행 기간 종료로 PR Close

2024-01-02 01:31 UTC, closed without merging