쥬스자판기 [STEP 3] 카일, 엘
tasty-code/ios-juice-maker pull request #117
Opened 2023-12-22 08:22 UTC by Changhyun-Kyle

@LeeZion94
안녕하세요, 시온
**`STEP3`** 보내드립니다! 확인 부탁드립니다!
이번에도 저번처럼 디코에서 만나뵐 수 있으면 너무 좋을 것 같습니다😝

---
## ✅ UML

![JM UML.001](https://hackmd.io/_uploads/HkGD85GwT.png)

## 🧐 고민했던점

- ### 앱 진입 시점에서의 `init`
    - `FruitStoreViewController`를 생성할 때는 initializer를 통해 의존성을 주입할 수 있었지만, `JuiceMakerViewController`의 경우 앱의 첫 진입화면이고 스토리보드 베이스로 진행되어 외부에서 `JuiceMakerViewController`가 생성될 때 의존성을 주입하는 부분에 제약이 있었습니다. 따라서, 제한적으로나마 `required init()`을 통해 초기값을 설정해주었습니다.
        ```swift
        // 수정 전
        // JuiceMakerViewController
        private var fruitStore: FruitStore = FruitStore(strawberryStock: 10, 
                                                        bananaStock: 10,
                                                        pineappleStock: 10,
                                                        kiwiStock: 10,
                                                        mangoStock: 10)
        private lazy var juiceMaker: JuiceMaker = JuiceMaker(fruitStore: fruitStore)

        // 수정 후
        // JuiceMakerViewController
        private var fruitStore: FruitStore
        private var juiceMaker: JuiceMaker
    
        required init?(coder: NSCoder) {
            self.fruitStore = FruitStore(strawberryStock: 10, 
                                         bananaStock: 10,
                                         pineappleStock: 10,
                                         kiwiStock: 10,
                                         mangoStock: 10)
            self.juiceMaker = JuiceMaker(fruitStore: fruitStore)
            super.init(coder: coder)
        }
        ```
- ### `JuiceMakerAlert Protocol`의 확장성 
    - `STEP2`에서 리뷰해주신 부분을 토대로 `Alert`을 사용할 때 어느 `UIViewController`에서 해당 프로토콜을 채택하면 동일한 방법으로 `Alert`을 띄울 수 있도록 리팩토링 했습니다. 하지만, 리팩토링한 코드가 모든 `UIViewController`에서 구현의 제약 없이 범용적으로 쓸 수 있다곤 생각하지만 과연 가독성과 효율성 측면에서 괜찮은 방법으로 구현한 부분인지는 시온의 생각이 궁금합니다 👀
        ```swift
        // 수정 전
        // JuiceMakerAlert
        extension JuiceMakerAlert where Self: UIViewController {
            func showJuiceMakerAlert(isCompletedMakeJuice: Bool, message: String, completion: (() -> Void)?) {
                let alert = UIAlertController(title: "알림" , message: message, preferredStyle: .alert)
                guard
                    isCompletedMakeJuice
                else {
                    alert.addAction(UIAlertAction(title: "예", style: .default, handler: { _ in
                        completion?()
                    }))
                    alert.addAction(UIAlertAction(title: "아니요", style: .cancel))
                    self.present(alert, animated: true)
                    return
                }
                alert.addAction(UIAlertAction(title: "확인", style: .cancel))
                self.present(alert, animated: true)
            }
        }
        // 수정 후
        // JuiceMakerAlert
        extension JuiceMakerAlert where Self: UIViewController {
            func showJuiceMakerAlert(buttonTitles: [String],
                                     message: String,
                                     styles: [UIAlertAction.Style] = [.default],
                                     completions: [(() -> Void)?] = [nil]) {
                guard buttonTitles.count == styles.count,
                      buttonTitles.count > completions.count
                else {
                    fatalError("InputError: showJuiceMakerAlert() - Please Check Parameters")
                }
                let alert = UIAlertController(title: "알림",
                                              message: message,
                                              preferredStyle: .alert)
                for (index, buttonTitle) in buttonTitles.enumerated() {
                    let action = UIAlertAction(title: buttonTitle, 
                                               style: styles[index],
                                               handler: { _ in
                        completions[index]?()
                    })
                    alert.addAction(action)
                }
                self.present(alert, animated: true)
            }
        }
        ```

## 🤔 조언을 얻고 싶은 부분
- ### `Delegate`패턴 VS `NotificationCenter`
   - STEP3에서 구현해야하는 부분 중 2번째 뷰인 `FruitStoreViewController`에서 과일의 재고를 수정하면 첫번째 뷰인 `JuiceMakerViewController`로 데이터를 전달해줘야 합니다. 이때, `JuiceMakerViewController`의 `FruitStore`를 `FruitStoreViewController`로 주입시켜줬기 때문에 같은 데이터를 공유 중 입니다. 따라서, 뷰를 업데이트만 해주면 라벨에 적용이 되는데 그렇다면 `viewWillAppear`에서 적용하는 것이 나은지 `Delegate`패턴을 적용하는 것이 나은지 궁금합니다. 저희는 `viewWillAppear`에서 적용한다면 첫 진입 시에도 작동하기 때문에 오히려 `Delegate`패턴이 나을 것 같다고 생각합니다. 뿐만 아니라, 델리게이트 프로토콜이 하는 역할이 `dismiss` 됐을 때 뷰를 업데이트 해주고 있는데 이 역할을 봤을 때 `Delegate`패턴으로 구현하는 것이 옳은 지 아니면 `notificationCenter`로 구현하는 것이 옳은 지 궁금합니다. 
       ```swift
        // Delegate 패턴
        // JuiceMakerViewController
       extension JuiceMakerViewController: FruitStockDelegate, JuiceMakerAlert {
           func updateFruitStock() {
                setStockLabelUI()
            }
        }
        // FruitStoreViewController
        @IBAction private func tappedCloseButton(_ sender: UIBarButtonItem) {
            delegate?.updateFruitStock()
            dismiss(animated: true)
        }
    
        // NotificationCenter
        // JuiceMakerViewController
        private func configureUI() {
            self.navigationItem.rightBarButtonItem = UIBarButtonItem(title: "재고수정",
                                                                 style: .plain,
                                                                 target: self,
                                                                 action: #selector(showFruitStoreViewController))
            NotificationCenter.default.addObserver(self, 
                                               selector: #selector(setStockLabelUI),
                                               name: NSNotification.Name("updateUINotification"),
                                               object: nil)
        }
        // FruitStoreViewController
        @IBAction private func tappedCloseButton(_ sender: UIBarButtonItem) {
            NotificationCenter.default.post(name: NSNotification.Name("updateUINotification"), 
                                        object: nil)
            dismiss(animated: true)
        }
        ```
- ### 문서주석과 매개변수 `input` 에러 시 확인 방법
    - 현재 리팩토링한 코드가 효율적인 코드인지 의문이 들어 아래와 같이 문서주석을 작성했습니다. **`"설명이 필요한 드립은 실패한 드립이다"`** 라는 말이 있듯이..이와 같이 설명이 필요한 코드라면...실패한 코드일까요...
        ```swift
        protocol JuiceMakerAlert {
        /// JuiceMaker 프로젝트에서 필요한 Alert을 띄웁니다. 의도한 Alert Action을 순서에 맞게 입력해주세요.
        /// - Parameters:
        ///   - buttonTitles: Alert이 present 되었을 때, 필요한 버튼들의 제목을 순서대로 나열해주세요.
        ///   - message: Alert이 present 되었을 때, 표시할 메세지를 입력해주세요.
        ///   - styles: Alert 버튼의 스타일을 순서대로 지정해주세요.
        ///   - completions: Alert 버튼을 눌렀을 때 진행할 Action을 순서대로 입력해주세요.
        func showJuiceMakerAlert(buttonTitles: [String],
                                 message: String,
                                 styles: [UIAlertAction.Style],
                                 completions: [(() -> Void)?])
        }
        ```
        ![image](https://hackmd.io/_uploads/BJYFF2Mv6.png)
    - 해당 코드 자체가 배열을 순회하여 `alert`에 `addAction`을 해주고 있습니다. 따라서, 배열의 순서가 굉장이 중요한데 이때 서로 매칭이 되지 않았을 때 이 `protocol`을 활용하려고 하는 개발자에게 에러를 보여주고 싶습니다. 그렇다면, 현재처럼 `guard문`에서 `fatalError`를 호출하는 것이 나을지 `print문`으로 `return`하는 것이 나을지 아니면 다른 좋은 방법이 있는 지 궁금합니다!
        ```swift
        extension JuiceMakerAlert where Self: UIViewController {
        func showJuiceMakerAlert(buttonTitles: [String],
                                 message: String,
                                 styles: [UIAlertAction.Style] = [.default],
                                 completions: [(() -> Void)?] = [nil]) {
        guard buttonTitles.count == styles.count,
              buttonTitles.count > completions.count
        else {
            fatalError("InputError: showJuiceMakerAlert() - Please Check Parameters")
            }
                {/*code*/}
            }
  [...]

2023-12-23 05:48 UTC, LeeZion94 commented
# 

## UML

- 작성해주시는 UML을 확인해봤을 때 일반화와, 직접연관을 표현해주신 것을 확인했습니다. 그렇다면 UML을 통해 왜 일반화와 직접연관을 표현해주셨나요? 의존과 집합등 다양한 표현방법이 있었음에도 그 2가지를 선택해서 작성해주신 이유가 궁금합니다.
- 또한, UML을 왜 그려야할까요? 해당 UML을 가지고 개발자들은 서로 어떤의견을 나누고 공유할 수 있을까요? 개발단계에서의 UML과 같은 산출물들이 왜 필요하다고 생각하시는지가 궁금합니다.
- UML 작성의도가 전체적으로 궁금해요!

## JuiceMakerAlert 확장성

- 해당 protocol은 확장성 있게 리팩토링해주셧다고 했지만, 위험할 수 잇는 수정이라고 생각해요 그 이유는 순서에 맞게 개발자가 신경써서 파라미터에 올바른 값을 넣어줘야하기 때문이에요.
- Step2에서 구두로 말씀드렸던 것 처럼 action 자체를 외부에서 주입해서 넣어줬다면 조금 더 개발자 각자의 판단에 의존하지 않고 안전히 해당 기능이구현되지 않았을까 싶습니다!

## Delegate Pattern vs Notification Center

- 위의 2개의 방식의 차이점은 무엇인가요?
- 카일과 엘은 개발할 때 어떤 부분들을 가장 중요하게 생각하고 고려하시면서 코드를 작성해주시나요?
- 2가지 방법모두 기능을 구현하는데 있어서 필요하다면 상황에 맞게 적용하시면 좋을 것 같아요. 정답은 없다고 생각합니다.
- 하나의 기능을 구현하는데 있어서 사용할 수 있는 것들을 나열하고 비교하는 건 좋은 습관이라고 생각됩니다. 반드시 이 기능을 구현하는데 필요한 것인지 고민해보고 다른 방법들과 비교해보다보면 카일과 엘이 코드를 작성함에 잇어서 중요하게 생각하는 것들에 대해 생각해보게되고 그 기준에 부합하는 코드를 작성한다면 이유가 있는 코드를 작성하는 계기가 될 수 있지 않을까요?

## 주석

- 주석을 작성하는 것은 상황에 따라 다르겠지만 일반적으로 지양되어야한다고 생각해요. 카일과 엘이 먼저 언급해주셨듯 주석을 사용하지 않고 그 기능을 충분히 설명할 수 있어야 좋은 코드라고 생각되기도하고, 가장 중요한건 코드는 수정되어도 주석은 잘 수정되지 않고 관리되지 않기 때문입니다. 리팩토링의 의도는 좋았지만 그로 인해 주석이 추가되어야만한다면 좋은 방향으로의 리팩토링 이었는지 한번 고민해보는 건 어떨까요?

## Dictionary

- 이 부분은 구두로 다시 논의해봐요

## Wildcard Pattern

- 이 부분또한 정답은 없다구 생각합니다. 하지만 일정한 기준을 가지고 적용하는 것이 중요하다고 생각해요. 함수의 네이밍자체에서 이미 어떤 값이 들어올 수 있을지 확실히 예상할 수 있다면 wildcard pattern을 적용해도 이해하는데 무리가 없다고 생각해요.

2023-12-23 06:02 UTC, LeeZion94 requested changes

2023-12-23 06:02 UTC, LeeZion94 commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +    weak var delegate: FruitStoreDelegate?
weak 키워드가 사용되어야하는 이유는 무엇인가요?

2023-12-23 06:02 UTC, LeeZion94 commented on JuiceMaker/JuiceMaker/Model/FruitStoreDelegate.swift
> +protocol FruitStoreDelegate: AnyObject {
AnyObject가 채택되어야하는 이유는 뭔가요?

2023-12-23 06:02 UTC, LeeZion94 commented on JuiceMaker/JuiceMaker/Model/JuiceMakerAlert.swift
> +    func showJuiceMakerAlert(buttonTitles: [String],
리팩토링으로 인해 오히려 Step2로직의 가독성이 조금 떨어졌다고 생각해요 ㅠㅠ
구두로 논의하기 전에 한번 수정해볼까요?

2023-12-26 03:33 UTC, Changhyun-Kyle commented on JuiceMaker/JuiceMaker/Model/JuiceMakerAlert.swift
> +    func showJuiceMakerAlert(buttonTitles: [String],
저번 리뷰 때 시온의 말을 잘못 이해했던 것 같습니다. UIAlertAction을 직접 주입하기 보단 외부에서 받아온 전달인자으로만 로직을 수행해야한다고 이해해서 난해한 코드가 됐습니다. 따라서, UIAlertAction을 외부에서 주입할 수 있게 리팩토링 했습니다!
```swift
// 선언부
// JuiceMakerAlert
protocol JuiceMakerAlert {
    func showJuiceMakerAlert(message: String, actions: [UIAlertAction])
}

extension JuiceMakerAlert where Self: UIViewController {
    func showJuiceMakerAlert(message: String, actions: [UIAlertAction]) {
        let alert = UIAlertController(title: "알림",
                                      message: message,
                                      preferredStyle: .alert)
        for action in actions {
            alert.addAction(action)
        }
        self.present(alert, animated: true)
    }
}

// 구현부
// JuiceMakerViewController
    private func proceedMakingJuice(juice: Juice, labels: [UILabel]) {
            {/*code*/}
            showJuiceMakerAlert(message: error.localizedDescription,
                                actions: [
                                    UIAlertAction(title: "예",
                                                  style: .default,
                                                  handler: { _ in
                                                      self.showFruitStoreViewController()
                                                  }),
                                    UIAlertAction(title: "아니오",
                                                  style: .cancel)
                                ]
            )
        }
    }
```

2023-12-26 05:19 UTC, Changhyun-Kyle commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +    init?(fruitStore: FruitStore, coder: NSCoder) {
`UIViewController`는 `NSCoding` 프로토콜을 채택함으로써 `storyboard`와 `xib` 파일을 `interface` 파일에 객체를 추가하고 아카이빙된 객체들을 실행 중에 `interface`에서 언아카이빙하여 메모리에 로드되는 과정을 거치게 됩니다. 따라서, 초기화 과정에서 필요한 매개변수가 누락된 경우와  `NSCoder`의 값이 잘못되어 언아카이빙에 실패할 경우 `failure`가 될 수 있다고 생각합니다. 임의의 `NSCoder` 값을 `FruitStoreViewController`를 생성할 때 주입 후 `LLDB`를 활용하여 디버깅했을 때, `init?()`에서 실패하는 것을 확인할 수 있었습니다. 또한, `UIViewController`를 인스턴스화할 때, 해당 스토리보드 또는 `nib` 파일에서 지정한 식별자가 잘못된 경우 `init?()`이 실패할 수 있다고 생각했으나, 디버깅 시 `init?()`이 호출되기 전 `FruitStoreViewController`를 초기화할 때 `storyboard`에서 식별자를 파악할 수 없어 앱이 중단되는 것을 확인했습니다.

- `식별자가 잘못된 경우`

![image](https://github.com/tasty-code/ios-juice-maker/assets/101093592/98751786-5554-4df7-b090-0adaa39e1f99)
- `NSCoder 및 초기화 과정에서 필요한 매개변수가 누락 경우`

![image](https://github.com/tasty-code/ios-juice-maker/assets/101093592/a74003a4-1c11-4f38-8e34-5a8fc626f60a)

2023-12-26 05:34 UTC, Changhyun-Kyle commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +    private func setStockLabelUI() {
각 `ViewController` 컨텐츠의 값을 넣어준다는 로직을 설명하기 위해 `setUpContents`로 수정하였습니다!

2023-12-26 05:35 UTC, Changhyun-Kyle commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +    private func setStepperValue() {
위 코멘트와 동일하게 `setUpContents`로 네이밍을 통일했습니다!

2023-12-26 05:43 UTC, Changhyun-Kyle commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +//        delegate?.updateFruitStock()
`NotificationCenter`와 `Delegate` 모두 구현해보면서 장단점에 대해 고민했습니다. 시온에게 리뷰를 받은 후 더 나은 판단인 방법을 활용하고자 우선 `NotificationCenter`를 구현하고 `Delegate` 관련 로직을 주석처리했습니다.

2023-12-26 05:47 UTC, Changhyun-Kyle commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +        dismiss(animated: true)
`self`에 대한 코드 컨벤션을 프로젝트 중반 부에 정하게 되어 누락된 것  같습니다. 저희는 정확히 어떤 메소드 혹은 프로퍼티가 현재 자신(`self`)인지 명확하게 하기 위해서 `self.` 키워드를 삽입하기로 결정했습니다.

2023-12-26 05:48 UTC, Changhyun-Kyle commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +//    func updateFruitStock() {
앞서 코멘트 드린 부분과 마찬가지로 시온에게 리뷰를 받은 후 더 나은 판단인 방법을 활용하고자 우선 `NotificationCenter`를 구현하고 `Delegate` 관련 로직을 주석처리했습니다.

2023-12-26 05:58 UTC, Changhyun-Kyle commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    private func proceedMakingJuice(juice: Juice, labels: [UILabel]) {
`makeJuice`라는 함수가 `juiceMaker` 객체에 이미 존재하여 비슷한 네이밍을 피하고자 해당 함수명을 채택했습니다. 네이밍하는 부분이 제일 어렵네요...ㅠ

2023-12-26 06:08 UTC, Changhyun-Kyle commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +            fatalError("init(coder:) has not been implemented")
해당 로직은 `View`를 띄워주고 의존성을 주입하는 기능을 합니다. 따라서, 이번 프로젝트에서 중요한 역할을 담당하고 있기에 휴먼에러가 발생했을 때 명확하게 해당 에러를 파악할 수 있도록 하기 위한 목적이었습니다. `print()문`으로 출력하는 방법과 고민하였으나 개발 단에서 해당 에러를 통과하게 되면 사용자에게 나타나지 않을 부분이라 생각하여 `fatalError`로 예외처리를 했습니다.

2023-12-26 06:54 UTC, Changhyun-Kyle commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +        dismiss(animated: true)
`self`에 대한 코드 컨벤션을 제대로 짚고 넘어가지 않아 발생한 문제입니다. `self` 키워드에 대한 기준이 모호하여 문법적으로 필수로 사용해야될 때만 `self`키워드를 사용하는 방법으로 결정했는데 시온만의 기준이 있으신지 궁금합니다!

2023-12-26 07:11 UTC, LeeSe0ngYe0n commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +                guard index < labels.count else { return }
우선 과일 재고의 라벨을 업데이트 해주는 로직을 `updateStockLabels()`함수로 분리했습니다.
` guard index < labels.count else { return }`는  휴먼에러를 방지하기 위해 구현한 코드였는데 이런 경우까지 고려해서 프로그래밍을 하는 것이 맞는지 궁금합니다!

2023-12-26 07:19 UTC, LeeSe0ngYe0n commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +            let sortedJuiceRecipe = juice.recipe.sorted(by: { $0.value > $1.value })
후행클로저의 과도한 축약으로 인해 가독성이 안좋은 걸까요? 저희가 이해한게 맞다면 아래와 같이 수정했습니다!
```swift
 let sortedJuiceRecipe = juice.recipe.sorted { firstIngredient, secondIngredient in
            firstIngredient.value > secondIngredient.value
        }
```

2023-12-26 11:18 UTC, Changhyun-Kyle commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +        NotificationCenter.default.post(name: NSNotification.Name("updateUINotification"),
- `Delegate`와 `NotificationCenter`를 고민하다가 결론 짓지 못한 채 우선 `NotificationCenter`로 구현했습니다. 그 이유는 당시 `Delegate`는 데이터를 전달하는 개념을 갖고 있고, `NotificationCenter`는 이벤트를 발생시킨다는 개념을 갖고 있다고 생각했습니다. 

  현재 코드를 보면 fruitStore에 대한 의존성을 상위 뷰에서 주입하고 있기 때문에 데이터를 전달한다기 보다 데이터는 이미 적용되어 있고 view만 새로 업데이트를 해줘야 했습니다. 따라서, `NotificationCenter`로 구현하는 것이 옳은 지에 대한 고민을 하게 되었습니다.

- `Notification`은 이벤트가 발생하는 곳에서 `NotificationCenter.default.post` 메서드를 사용하여 `Notification`을 발송합니다. 

  `Notification`을 받아야 객체는 `addObserver(_:selector:name:object:)` 메서드를 사용하여 옵저버로 등록합니다. 
  이후 등록된 옵저버에 의해 해당 `Notification`이 발생하면, 옵저버는 `selector`에 정의된 메서드를 호출하여 `Notification`을 처리합니다. 

  또한, `NotificationCenter`는 싱글톤 객체이기 때문에 객체가 더 이상 `Notification`을 수신하지 않을 때, `removeObserver(_:name:object:)` 메서드를 사용하여 옵저버를 해제해야 합니다.

- 시온의 리뷰를 받은 뒤 [Delegation](https://developer.apple.com/library/archive/documentation/General/Conceptual/DevPedia-CocoaCore/Delegation.html)과 [Notification](https://developer.apple.com/library/archive/documentation/General/Conceptual/DevPedia-CocoaCore/Notification.html#//apple_ref/doc/uid/TP40008195-CH35-SW1)에 대해 더 자세히 알아보다보니  `NotificationCenter`는 싱글톤 객체를 기반으로 이벤트 발생여부를 옵저버를 등록한 객체에게 전달하는 방식으로 일대다(1:N)의 객체에 이벤트를 전달할 때 유용하고, `Delegate`의 경우  `protocol`을 정의하여 이벤트를 대신 처리할 객체가 채택하여 사용하는 방식으로 일대일(1:1)의 객체에 이벤트를 전달할 때 유용하다는 것을 알게 되었습니다.

  `Notification`과 `Delegate` 코드에 대한 메모리 디버깅으로 메모리 효율에 대해 추적하고 싶었지만 관련 레퍼런스 및 여러 시도에도 알아내지 못했습니다...혹시 방법을 알고 계신지 궁금합니다...ㅠ

2023-12-26 11:18 UTC, LeeSe0ngYe0n commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +    weak var delegate: FruitStoreDelegate?
`JuiceMakerViewController`와 `FruitStoreViewController`가 `delegate`를 통해 `강한 참조`를 하고 있기 때문에 `순환 참조`를 방지하기 위해 `weak`키워드를 사용해야 합니다!

2023-12-26 11:19 UTC, LeeSe0ngYe0n commented on JuiceMaker/JuiceMaker/Model/FruitStoreDelegate.swift
> +protocol FruitStoreDelegate: AnyObject {
`Delegate 패턴` 사용 시 객체 간에 `강한 참조`를 하기 때문에 `순환 참조`가 일어날 수 있습니다. 
그렇기 때문에 `weak` 키워드를 사용해야 하는데 `weak` 키워드는 `참조 타입`에서만 쓸 수 있는 키워드입니다.
`AnyObject`를 채택하지 않으면 `FruitStoreDelegate`를 채택하는 타입이 클래스인지 구조체인지 열거형인지 알 수가 없기 때문에 `weak` 키워드를 사용할 수 없습니다.
`AnyObject`를 사용하면 클래스 전용 프로토콜의 인스턴스에 대한 구체적인 유형으로 사용할 수 있기 때문에 `AnyObject`가 채택되어야 합니다!
Ref: https://developer.apple.com/documentation/swift/anyobject

2023-12-27 00:46 UTC, Changhyun-Kyle commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        NotificationCenter.default.addObserver(self,
현재 코드에서는 확신하기 어렵다고 생각합니다. `NotificationCenter`에서 `Observer`는 `Notification`의 이름과 내용을 기반으로 작업을 수행하기 때문입니다. 하지만, `NSNotification.Name`에 대한 `enum` 타입을 관리한다면 어느 객체 간의 통신인지 조금 더 명확하게 알 수 있을 것 같습니다!

2024-01-02 01:31 UTC, closed without merging

2024-01-02 01:31 UTC, Tacocat-tastycode commented
프로젝트 진행 기간 종료로 PR Close