[STEP 2] ERA
tasty-code/ios-juice-maker pull request #13
Opened 2022-09-01 01:38 UTC by kr-yeon

@jaemuYeo 리뷰 부탁드립니다!
### **수행한 내용**
- [x] 재고 관리 (+/-)를 뷰에 적용 완료
- [x] 쥬스 주문 적용 완료
- [x] 쥬스 주문시 재고가 부족하거나 완료시 Alert띄우기 완료
- [x] 재고 관리 뷰와 쥬스 주문 뷰의 JuiceMaker동기화 완료
- [x] 재료의 값이 변할때마다 실행하는 함수 적용 완료

### **고민되었던 내용**
observe에 대해 제일 많이 고민했습니다. 주스의 값을 사용할때마다 update시켜주면 되는 일이지만, 새로 배운 observe라는 개념을 적용시켜 보고싶었습니다. 하지만 KVO의 ObjectC에 관한 에러때문에 쉽사리 적용시키지 못하였고 그러던중 찾아본것이 didSet이었습니다.
didSet으로 set될때의 값을 함수로 넘겨주어 처리를 하였습니다.

### **조언을 얻고 싶은 부분**
네이밍에 관해 조언을 다시 한번 얻고 싶습니다. 
`JuiceMaker.makeJuice`함수의 반환값을 활용하여 Alert을 띄우는 함수를 작성했습니다.
이 함수의 네이밍을 어떻게 할지 조언을 얻고 싶습니다. 현재 코드에서는 `makeJuice함수를` 만들었는데, 위 부분의 함수 이름과 겹쳐 이게 맞을까 라는 생각이 듭니다.

IBOutlet에 관하여 조언을 얻고 싶습니다. 각 라벨과 터치를 다 불러오다 보니 코드의 양이 필요 이상으로 늘어났다고 생각합니다.
혹시 이 부분에 관하여 줄이거나, 좋은 방법이 있을까요?

2022-09-01 07:49 UTC, jaemuYeo requested changes
에라 스텝2도 고생많았습니다 👏
모르고 스텝3까지 구현했다했는데 전부구현이 아니라 일부 재고변경에 대한 것만 구현해주었군요!
나머지는 이번 스텝이 머지되고 난 후 진행해주면 좋을 것같아요! 
스텝1에서 남겨놓았던 코멘트들도 너무너무 잘 반형해주었네요 ㅎㅎ☺️🙏
역할별로 커밋을 나누어 해주어서 보기에도 너무 좋았어요 👍
아쉬웠던것은 네이밍과 같은 간단한 것에도 feat라는 컨벤션을 사용했다는 것이 아쉬웠어요!
상황에 맞는 커밋 컨벤션을 익혀서 더 다양하게 활용해보면 좋을 것 같습니다 ㅎㅎ
그리고 MV에 관해 모든 파일(타입)에서 은닉화 캡슐화를 시도해보세요 😀(매우 중요)

## 고민했던 부분
KVO를 사용하려고 했던 시도와 프로퍼티 감시자의 활용을 잘 해주어서 멋져요 👍
그 외에도 화면간에 데이터를 전달할 수 있는 방법은 어떤 것들이 있을까요?
viewDidLoad 만으로도 충분히 결과를 가져올 수 있을 것같아요!

## 에라가 궁금한 부분에 대하여
1. makeJuice 네이밍
저는 함수의 네이밍이 같다는 것에는 크게 신경쓰지 않는 편입니다!
실질적으로 해당 함수가 하는 기능이 네이밍과 일치하다면 말이죠 😀
지금과 같은 경우도 호출 방법이 달라서 충분히 전달이 잘 됩니다~

2. 코드를 줄일 수 있는 방법
이것도 정말 다양한 방법이 있는데요! 사실 지금 구현한 방식도 너무 잘했어요 💯
몇 가지 방법을 공유할게요! 시도하고 싶은 방법이 있다면 구현해보세요 !!
- 일일이 아웃렛과 액션을 주어서 개별 구현 (현재 방식)
- 하나의 액션에 여러 버튼을 연결하기
- Outlet 변수를 배열 타입으로 만들기
- 커스텀 클래스를 만들어서 UILabel또는 UIButton에 메서드 구현하기
```swift
// 커스텀 클래스 예시
class JuiceOrderButton: UIButton {
    // 내부구현
}
```

4. 업데이트 문제
저는 수정된 부분만 업데이트 해주면 좋을 것 같다 생각합니다.
매번 모든 label을 업데이트하는 것은 불필요한 행동이라 생각해요 😀

---

코멘트에 대해 확인해주시고 수정할 부분이 있다면 수정해서 재요청해주세요!! 💪

2022-09-01 07:49 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker.xcodeproj/project.pbxproj
>  				C73DAF3A255D0CDD00020D38 /* ViewController.swift */,
불필요한 파일은 제거하주면 좋아요 😀

2022-09-01 07:49 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker.xcodeproj/project.pbxproj
> +		FB1FD77E28BF052600357543 /* Constant */ = {
Error타입이 Constant 라는 그룹안에 포함되어있는게 어색하네요🤔

2022-09-01 07:49 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Controller/FruitManagementController.swift
> +class FruitManagementController: UIViewController {
기존의 ViewController라는 밋밋한 네이밍을 프로젝트 화면에 맞게 잘 네이밍 해주었네요! 👍

2022-09-01 07:49 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Controller/FruitManagementController.swift
> +        strawberryLabel.text = String((try? juiceMaker.getQuantity(of: .strawberry)) ?? 0)
형변환 실패시 0을 주는 것이 큰 상관은 없으니 큰 의미가 없다는 생각이 들어요
convert를 해주는 함수를 통해 String타입을 반환하고 사용한다면 해결할 수 있을 것같은데 시도해 볼 수 있을까요!!?

다른 메서드들도 비슷한 방식을 시도해보면 좋을 것 같아요~

2022-09-01 07:49 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Controller/MakeJuiceController.swift
> +class MakeJuiceController: UIViewController {
MakeJuiceController 보다는 JuiceMakerViewController는 어떤가요??
ViewController는 네이밍이 바뀌더라도 붙여주면 좋습니다 ⭐️

2022-09-01 07:49 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Controller/MakeJuiceController.swift
> +    @IBAction func hitStrawberryBananaJuiceButton(_ sender: Any) {
이 곳을 포함에 아래의 버튼 메서드들의 네이밍을 hit로 했군요
보통 버튼을 누르는 행위를 통해 내부의 기능들이 실행되기 때문에
tap 또는 didTap으로 시작한답니다 😀

2022-09-01 07:49 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Controller/MakeJuiceController.swift
> +        makeJuice(of: .mangoKiwi)
자기자신의 내부의 프로퍼티 또는 메서드를 사용하는 경우 self를 붙여주는 습관을 들이면 좋아요 😉

2022-09-01 07:49 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Controller/MakeJuiceController.swift
> +            showAlert(message: juiceStatus.message, confirmText: "예", confirmHandler: { _ in self.pushFruitManagement() }, cancelText: "아니오")
이 곳에 있는 문자열들 "예", "확인", "" 와 같은 것들을 
생성해두신 그룹(Constant)에서 모아서 관리하면 좋을 것 같아요! 
Hint. static let

2022-09-01 07:49 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Controller/MakeJuiceController.swift
> +        navigationController?.pushViewController(fruitManagementVC, animated: true)
화면 전환방식을 push로 선택한 이유가 있나요??

2022-09-01 07:49 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
>              return [ .strawberry: 16 ]
대괄호 안쪽에 공백이 없어도 됩니다! `[.딸기: 16]`

2022-09-01 07:49 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +enum MakeJuiceStatus {
상태를 타입으로 만들어서 관리하는 방법 너무 좋습니다!
다만 네이밍이 동사여서 JuiceStatus 정도만으로도 표현될 것같아요!

2022-09-01 08:13 UTC, kr-yeon commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
>              return [ .strawberry: 16 ]
앗, 이거는 습관입니다. 유지해도 괜찮을까요?

2022-09-01 08:32 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
>              return [ .strawberry: 16 ]
다수가 사용하는 컨벤션에 개인의 습관이 들어간다면 단점이 될 수도있어요🔥
다른 언어에서 파생된 습관이라면 더욱 반대입니다 ㅎㅎ
이번 프로젝트에서는 크게 신경쓰지 않을게요!

2022-09-01 09:29 UTC, kr-yeon commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
>              return [ .strawberry: 16 ]
Swift에는 코드 스타일을 맞춰주는 수단이 따로 있을까요? 궁금해졌네요 ㅎㅎ

2022-09-02 03:17 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
>              return [ .strawberry: 16 ]
swifLint라는 라이브러리가 있는데 추후에 사용해볼 기회가 있으니
현재는 제약사항대로 외부 라이브러리를 사용하지 않고 진행해주세요!

2022-09-02 04:53 UTC, kr-yeon commented on JuiceMaker/JuiceMaker/Controller/MakeJuiceController.swift
> +        navigationController?.pushViewController(fruitManagementVC, animated: true)
현제 재공된 뷰에서 뒤로가는 버튼이 없었습니다. present로 이동시 뒤로가는 버튼을 만들어 dismiss를 해야하기때문에, push로 선택했습니다.

2022-09-02 05:20 UTC, kr-yeon commented on JuiceMaker/JuiceMaker/Controller/FruitManagementController.swift
> +        strawberryLabel.text = String((try? juiceMaker.getQuantity(of: .strawberry)) ?? 0)
음.. 잘 모르겠습니다.

2022-09-02 06:30 UTC, kr-yeon commented on JuiceMaker/JuiceMaker/Controller/FruitManagementController.swift
> +        strawberryLabel.text = String((try? juiceMaker.getQuantity(of: .strawberry)) ?? 0)
```swift
func getQuantity(of fruit: Fruit) -> String {
    do {
      return String(try juiceMaker.getQuantity(of: fruit))
    } catch {
      return "0"
    }
}
``` 일까요..

2022-09-14 08:48 UTC, closed without merging