쥬스 메이커 [STEP 1] Mason, Miro
tasty-code/ios-juice-maker pull request #18
Opened 2023-01-03 05:59 UTC by qwerty3345

안녕하세요 제이슨!🙋‍♂️ @ehgud0670 
쥬스메이커 프로젝트를 진행하게 된 Mason, Miro 입니다 :)
어느덧 2023년 새해가 밝았네요ㅎㅎ 
프로젝트를 해 나가며 리뷰어 분들의 코드리뷰를 통해 정말 큰 도움이 되고 있습니다🤗
이번 프로젝트를 통해 "이유 있는 코드"를 작성하는 습관을 들일 수 있도록 열심히 고민하고 공부하겠습니다! :+1: (많은 도움 부탁드려요..💕)
감사합니다🙇‍♂️

# ✅ 요구사항 & 체크리스트

- [x]  `FruitStore` 타입 정의 - 과일의 재고를 관리
    - [x]  딸기, 바나나, 파인애플, 키위, 망고 종류의 과일을 관리 (초기 재고 10개)
    - [x]  각 과일의 수량 n개를 변경하는 기능 구현
- [x]  `JuiceMaker` 타입 정의 - 과일쥬스를 제조
    - [x]  각 쥬스별 제조 레시피 정의 (ex 딸기쥬스 - 딸기 16개 소모…)
    - [x]  `FruitStore`의 과일을 사용하여 과일쥬스를 제조하는 기능 구현
    - [x]  쥬스 제작 전 과일의 재고를 확인하는 로직 구현

# 📝 모델 구조

`struct JuiceMaker` -  쥬스를 제조하는 쥬스메이커

- `let fruitStore: FruitStore` - 쥬스 제조 시 과일의 재고를 관리
- `func makeJuice(of fruitJuice: FruitJuice)` - 재고 확인 후, 과일 쥬스 제조
- `fun hasEnoughStock(for fruitJuice: FruitJuice)` - 쥬스 레시피를 통한 재고 확인

`class FruitStore` - 과일의 재고를 관리

- `var stock: [Fruit: Int]` - 각 과일 타입별 재고 수량을 갖고있는 딕셔너리
- `func changeStock(of fruit: Fruit, by number: Int)` - 과일 재고의 수량을 변경

`enum Fruit` - 과일의 종류를 담고 있는 enum

`enum FruitJuice` - 과일 쥬스의 종류를 담고 있는 enum

- `var recipe: [Fruit: Int]` - 각 과일 쥬스별 레시피 정보 (소모 과일 갯수)

# **⁉️ 고민과 해결**

### 😲 1. 클래스, 구조체 중 어떤 걸 선택해야 할까? (FruitStore, JuiceMaker)

- `FruitStore`
    - 내부에 과일 재고에 해당하는 딕셔너리 데이터를 갖고 있고, 해당 데이터를 수정하는 역할을 수행합니다
    - 데이터를 갖고 있고, 계속해서 해당 데이터를 수정해야 하며 해당 데이터의 identity 를 유지해야 한다면`class` 로 구현하는 것이 적절하다 생각되었습니다.
    - +) 차후 여러 뷰컨트롤러에서 전역적인 접근이 가능하고 과일 재고 데이터를 공유해야 하는 상황이 생긴다면 싱글턴 패턴으로 구현하는 것이 바람직 해 보였습니다.
- `JuiceMaker`
    - 쥬스를 만드는 역할을 하고, 실질적인 속성(과일 재고)에 대한 변경은 `FruitStore` 에게 위임하므로 구조체로 구현하는 것이 적절하다 판단했습니다.

### 🤔 2. `enum Fruit` 와 `enum FruitJuice` 의 case 명이 겹치는 문제

- 과일 종류에 해당하는 Fruit 의 case 와 과일 쥬스 종류에 해당하는 FruitJuice case 중 
딸기 - 딸기(쥬스), 바나나 - 바나나(쥬스) 처럼 동일한 case 명을 공유합니다.
- 두 가지의 enum 을 동시에 사용할 때, enum의 타입을 축약해 case 만 작성할 시 식별이 불가한 문제가 생겼고 이에 대한 해결책을 생각 해 보았습니다.
    1. FruitJuice의 case 이름을 .strawberryJuice 로 쥬스라는 걸 명시해준다
    2. 동시에 사용하는 경우, 한 쪽의 enum을 Fruit.strawberry 로 풀어쓴다
- 1번의 경우에는, FruitJuice.strawberryJuice 처럼 타입명에 명시된 “Juice” 가 케이스에도 중복되는 느낌이 들어서 2번으로 구현하였습니다.

❓🧐 이에 대한 제이슨의 의견은 어떤지 여쭤보고 싶습니다..! 
##### ⬆️질문1

```swift
enum Fruit: CaseIterable {
    case strawberry
    case banana ...

enum FruitJuice {
    case strawberry
    case banana
    case strawberryBanana ...
    var recipe: [Fruit: Int] {
        switch self {
        case .strawberry: 
            return [Fruit.strawberry: 16]  // 🤔 둘 다 case 명이 strawberry 이다...
        case .banana:
            return [Fruit.banana: 2]
  ...
```

### 😲 3. `.allSatisfy` 내부에서 옵셔널 바인딩 처리

- 재고 수량이 충분한지 확인하는 hasEnoughStock 함수를 사용할 때,
전체 조건을 확인하는 `.allSatisfy` 의 내부에서 어떻게 옵셔널 바인딩을 처리 할 것인가?
- `.allSatisfy` 클로저 내부에서 작성하는 return 은 함수의 return 이 아니라, 
파라미터로 받는 조건을 체크하는 클로저의 return 이므로, 각기 return 으로 처리 가능
    - `func allSatisfy(_ predicate: (Self.Element) throws -> Bool) rethrows -> Bool`

```swift
private func hasEnoughStock(for fruitJuice: FruitJuice) -> Bool {
    return fruitJuice.recipe.allSatisfy { fruit, numberOfUse in
        guard let fruitStock = fruitStore.stock[fruit] else {
            return false
        }
        return fruitStock >= numberOfUse
    }
}
```

- 더욱 간단하게, 이번 경우에는 수량을 체크하는 것이므로 해당 dictionary가 nil 일 경우에는 재고 수량을 0으로 nil coalescing 기본값을 줘도 된다고 판단하여 그렇게 처리했습니다.

```swift
private func hasEnoughStock(for fruitJuice: FruitJuice) -> Bool {
    return fruitJuice.recipe.allSatisfy { fruit, numberOfUse in
        (fruitStore.stock[fruit] ?? 0) >= numberOfUse
    }
}
```

### 🤔 4. `changeStock(of:by:)` 함수의 파라미터에 대한 고민

- 아래 코드와 같이 `makeJuice(of:)` 함수에서 `changeStock(of:by:)` 함수 호출을 통하여 과일의 재고를 변경시킵니다. 
- 이 과정에서 `changeStock(of:by:)` 함수는 `makeJuice(of:)` 함수 안에서 `-numberOfUse`를 파라미터 값으로 받게 되는데, 파라미터에 “-”를 붙이는 게 어색하다고 느껴져 고민을 하게 되었습니다. 
해당 부분을 보완하기 위하여 아래와 같은 방안을 생각해보았습니다. 
    - 재고 수정 함수`changeStock(of:by:)`를 두개의 함수로 나누기(재고 추가, 재고 사용)
    - `changeStock(of:by:)` 함수에 재고 추가(+), 재고 사용(-) 여부를 판단하는 파라미터를 추가하기

❓🧐 이러한 고민에대해 Jason의 의견이 궁금합니다! 더 좋은 방식이 있을 지 혹은 해당 고민보다는 다른 코드에 더 힘을 쓰는(?)게 좋을 지 궁금합니다! 
##### ⬆️질문2
```swift
// struct **JuiceMaker**
func makeJuice(of fruitJuice: FruitJuice) {
    guard hasEnoughStock(for: fruitJuice) else {
        return print("쥬스를 만들기 위한 재고가 부족합니다.")
    }
    
    fruitJuice.recipe.forEach { fruit, numberOfUse in
                                    // 🤔 해당 부분에 "-" 사용
        fruitStore.changeStock(of: fruit, by: -numberOfUse)    
    }
}

// class **FruitStore**
func changeStock(of fruit: Fruit, by number: Int) {
    guard let fruitStock = stock[fruit] else {
        return print("해당하는 과일이 존재하지 않습니다.")
    }
    guard fruitStock + number >= 0 else {
        return print("재고가 부족합니다.")
    }

    stock[fruit] = fruitStock + number
}
```

### 😲 5. `CaseIterable` 프로토콜 채택을 통한 `Fruit.allCases` 사용

- `FruitStore` 객체 생성 시 initializer를 통하여 `FruitStore` 프로퍼티 stock의 기본 재고값을 `[Fruit:Int]`로 각 과일별로 10개만큼 채워 넣기 위하여 `allCases` 메소드를 사용하려고 하였습니다.
- 이와 관련하여 공부를 하던 중, 열거형 타입을 배열처럼 사용하기위해서는 `CaseIterable` 프로토콜을 채택해야 됨을 알게되었고, 해당 프로토콜 채택을 통하여 손쉽게 initialize를 시킬 수 있었습니다.

```swift
final class FruitStore {
    private(set) var stock: [Fruit: Int] = [:]
    
    init() {
        Fruit.**allCases**.forEach { fruit in
            stock[fruit] = 10
        }
    }
}
```

## 🤔 질문사항 정리 (링크)

1. [질문1](####⬆️질문1)
2. [질문2](####⬆️질문2)

감사합니다!

2023-01-03 06:34 UTC, ehgud0670 reviewed
안녕하세요 Mason, Miro! 
리뷰어 제이슨입니다 :)
고생하셨고 일단 코멘트 드리기에 앞서 질문에 대한 답변부터 드리도록 하겠습니다. 

> enum Fruit 와 enum FruitJuice 의 case 명이 겹치는 문제

겹치면 말씀하신것처럼 헷갈리죠 ㅎㅎ 1번 2번 모두 좋지만 저도 2번이 더 좋은 것 같아요. 
1번은 아무래도 enum 명과 case 가 juice 로 겹치니까요. 
2번처럼 Fruit.strawberry 라고 명시적으로 적어서 헷갈림을 방지하는 것이 좋겠네요. 

> changeStock(of:by:) 함수의 파라미터에 대한 고민

저는 지금 그대로도 괜찮다고 판단되는데 가독성 면에서 어색하다고 느껴지시면 말씀하신대로 메소드를 증가, 감소로 나누셔도 좋을 것 같아요 :)

2023-01-03 07:07 UTC, ehgud0670 requested changes
각 print 문을 적으신 곳은 에러를 활용해도 되는 메소드들이네요~
결국에 makeJuice 메소드를 사용하는 상위 메소드가 에러를 catch 할 수 있도록 
쥬스 메이커의 makeJuice 및 여타 메소드들을 에러를 던지도록 만들어보시는 건 어떠신가요? 
테스트까지 하면 완벽하고요 👍

ps. 전반적으로 코드가 깔끔하네요 👍

2023-01-03 07:31 UTC, qwerty3345 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +            return print("해당하는 과일이 존재하지 않습니다.")
return문 의 파라미터로 Void 함수인 print 함수를 넘겨서 실행하는 구조로, 
둘 다 동일하게 작동하는 것으로 알고 있습니다.

다른 코드에서 비슷하게 사용한 방식을 보고 한 줄로 깔끔하게 처리할 수 있는 것 같아서 사용했던 것 같습니다 :)
그런데, 말씀하신 대로 명시적이지 않게 되는 문제가 있는 듯 합니다. (저도 처음 봤을 때 어? 저게 호출이 돼? 라고 생각했었던 것을 보니 더욱 그런 것 같습니다)
만약에 현업에서 일반적으로 사용하지 않는 방식이라면 수정하도록 하겠습니다!

2023-01-03 07:34 UTC, ehgud0670 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +            return print("해당하는 과일이 존재하지 않습니다.")
네 ㅎㅎ 동작엔 문제가 없는데 보기 헷갈려서 말씀드렸어요 ㅎㅎ 
일반적으로 그렇게 사용하지 않아서 수정하시면 좋을것 같아요! 👍

2023-01-04 04:29 UTC, longlivedrgn commented
안녕하세요 제이슨!🙋‍♂️ @ehgud0670
먼저 PR 코멘트 너무 감사합니다 :) 말씀해주신대로 각 에러를 타입으로 분류하고 에러를 던질 수 있게 코드를 변경해보았습니다.
테스트의 경우 구체적으로 프로젝트가 진행이 될 [STEP 2]에서 해볼 계획입니다!

# **⁉️ 구현 방식**

## 😇 1. 에러 케이스 정의

- `LocalizedError`를 채택받은 enum 타입의 `StockError`를 정의하였습니다.

```swift
enum StockError: LocalizedError {
    case noCorrespondingFruit
    case notEnoughToMakeJuice
    case notEnoughToChange
    
    var errorDescription: String? {
        switch self {
        case .noCorrespondingFruit:
            return "일치하는 과일이 없습니다."
        case .notEnoughToMakeJuice:
            return "쥬스를 만들기에 재고가 부족합니다."
        case .notEnoughToChange:
            return "수량을 변경하기에 재고가 충분하지 않습니다."
        }
    }
}
```

## 😇 2. 에러를 던질 수 있는 함수로 변경

- 재고 변경 시 Dictionary Key에 해당 과일이 존재하지 않을 경우 `noCorresspondingFruit` 에러를 던지고, 
재고를 0미만으로 변경 할 경우, `notEnoughToChange` 에러를 던지는 코드를 작성하였습니다.

```swift
// class FruitStore
func changeStock(of fruit: Fruit, by number: Int) throws {
    guard let fruitStock = stock[fruit] else {
        throw StockError.noCorrespondingFruit
    }
    guard fruitStock + number >= 0 else {
        throw StockError.notEnoughToChange
    }
}
```

- 쥬스 생성 시 재고가 부족할 경우 `notEnoughToMakeJuice` 에러를 던지도록 코드를 작성하였습니다.

```swift
// struct JuiceMaker
func makeJuice(of fruitJuice: FruitJuice) throws {
    guard hasEnoughStock(for: fruitJuice) else {
        throw StockError.notEnoughToMakeJuice
    }
    
    try fruitJuice.recipe.forEach { fruit, numberOfUse in
        try fruitStore.changeStock(of: fruit, by: -numberOfUse)
    }
}
```

- 위 코드에서 `makeJuice(of:)` 가 `changeStock(of:by:)` 을 호출합니다. 
이 때 changeStock이 error 를 던질 경우 호출부인 makeJuice 안에서 직접 에러를 처리하는 것이 아니라,
makeJuice 를 호출하는 호출부에서 에러 케이스들을 핸들링 하도록 구현하였습니다.
    - 에러를 던질 수 있는 함수를 고차함수 (forEach) 에서 호출하니, 
    try 고차함수 { try 함수 } 형식으로 중첩해서 try 를 해줘야 했습니다.
    - 🤔❓ **고차함수 내부의 try 함수를 바로 do-catch 로 핸들링 해주면 가능하지만, 위와 같이 다시 던지는 형태로 구현하려면 이렇게 해야 했는데, 혹시 다른 방법이 있을지 궁금합니다..!**
    - 🤔❓ **반복문에서의 에러 핸들링을 위와 같이 고차함수로 수행해도 되는지 (일반적인지) 도 궁금합니다 :)**

2023-01-04 05:23 UTC, ehgud0670 approved these changes
> 🤔❓ 고차함수 내부의 try 함수를 바로 do-catch 로 핸들링 해주면 가능하지만, 위와 같이 다시 던지는 형태로 구현하려면 이렇게 해야 했는데, 혹시 다른 방법이 있을지 궁금합니다..!

다시 던져 결국에 makeJuice 메소드를 사용할 최상위 메소드에서 do - catch 하는것이 자연스러워 보이네요. 잘 하셨어요 👏

> 🤔❓ 반복문에서의 에러 핸들링을 위와 같이 고차함수로 수행해도 되는지 (일반적인지) 도 궁금합니다 :)

일반적인지는 모르는데 rethrows 해야해서 좀 헷갈려보이긴 하네요. 사용하는데는 상관없는 것 같아요.
다만 다른 이유에서 저는 해당 코드를 고차함수가 아닌 반복문을 사용하는걸 추천드립니다. 
왜냐하면 고차함수는 순수함수(pure function)를 인자로 받아야 하는데 현재 클로져 코드가 순수하지 않기 때문입니다. 내용이 순수하지 않으면 for 문을 쓰는게 정석이기 때문입니다. 한번 고민해보시고 다음 스텝때 바꾸시는 것도 좋을 것 같아요 :) 

수고하셨습니다! 💯💪

2023-01-04 05:23 UTC, merged