쥬스메이커 [STEP 1] Avery, Jenna
tasty-code/ios-juice-maker pull request #19
Opened 2023-01-04 01:29 UTC by ueunli

안녕하세요 콘🌟  @protocorn93
이번에 쥬스메이커 프로젝트를 같이 진행하게 된 Avery와 Jenna입니다!
미숙한 부분이 많은 코드지만 읽어보시고 피드백 주시면 열심히 공부해서 반영해보겠습니다🔥
새해 복 많이 받으세요!!!
　 
　 
# 🧃 구현사항
### Fruits
- 재료가 되는 과일의 종류에 대한 열거형
- CaseIterable프로토콜 채택으로 타입변수 allCases를 생성
- [x] 사용할 과일 5종을 정의

### Juice
- 과일로 만드는 쥬스의 종류에 대한 열거형
- 재료조합명을 String원시값으로 가짐
- case별로 필요한 재료의 수량을 딕셔너리로 저장(`recipe`)
- [x] 과일로 제조할 쥬스 7종을 정의
- [x] 각 쥬스 제조에 필요한 정해진 개수의 과일 목록을 제시

### FruitStore
- 과일의 재고를 관리하는 클래스
- 생성 시, 딕셔너리 `stocks`에 `Fruits`의 `allCases`요소들을 key로, 기본값(10)을 value로 갖는 재고 쌍을 저장
- 싱글턴 패턴 적용: 통일된 단 하나의 창고객체가 필요하므로 과일저장소를 싱글턴 클래스로 구현
- [x] 과일별 재고를 저장
   - [x] 초기값: 각 10개
- [x] 과일별 재고를 확인
- [x] 과일별 재고를 변경

### JuiceMaker
- 주문이 들어온 쥬스를 만들 수 있는지 확인하고 제조하는 구조체
- FruitStore의 유일한 인스턴스(`fruitStore`)를 소유
- 현재 단계에서는 외부에서 호출될 일이 없는 속성과 메서드를 `private`으로 선언
- [x] 주문이 들어온 쥬스의 제조가 가능한지 판별
- [x] 주문이 들어온 쥬스의 레시피에 따라 과일별 재고를 소모

　 
　 
　 
# 🧃 고민했던 부분
## ✔  M-V-C사이의 로직 분배
패턴에서 로직에 관한 코드는 Model, Controller 중 어디로 가야 하는지 고민했습니다. 
`FruitStore`의 `countStock(of:)`와 같이 단순히 내부에 저장된 값을 확인해 주는 코드는 모델에 있기에 적합하지만, 
`JuiceMaker`의 `startBlending()`은 `FruitStore`의 `decrease()`를 불러오는데,  이는 유저의 쥬스 제조 버튼을  누름을 뷰컨트롤러에서 받아오면 모델의 값을 변경하는 부분으로 모델보다 컨트롤러(ViewController)에서 관리하는 편이 좋지 않을까 라고 생각했습니다. 
MVC 패턴의 포인트는 View와 Model의 분리라고 알고 있는데, 컨트롤러에는 어느정도의 역할이 할당되면 좋을지 궁금합니다.

　
## ✔  주문 가능 여부
1. `특정 재료의 재고가 충분한가`
2. `메뉴가 주문 가능한가`(= 모든 재료의 재고가 충분한가)

처음엔 위와 같은 Bool타입 변수 2개를 따로 만들 생각이었습니다. 
이후 재고 및 메뉴상태 관리 기능에 필요할 것 같아서였으나, 고민 끝에 다음과 같은 이유로 `2번`만 구현했습니다. (`checkOrderable(of:)`)
> 현재 단계로서는 '입력받은 메뉴의 레시피가 결국 제조 가능한가' 여부를 구하는 것까지가 요구사항인 점, 
> 따라서 '어떤 재료가 부족한가'는 중요하지 않다는 점, 
> 어떤 재료가 부족하든(~~`1번`~~), 하나라도 부족한 게 발견된 순간 `2번`을 false로 반환하고 조기종료하고자 for-in문 사용(~~forEach함수~~)

　
## ✔  재고확인 시점
`startBlending(of:)`함수 내부에서 `checkOrderable(of:)`함수를 호출하기　→　호출하지 않기
위의 MVC 로직분배에 관해 의논하는 과정에서 위와 같이 재고확인 시점을 변경했습니다. 
ViewController에서 재고확인→재고소진(음료제조) 순서대로 각자 호출하는 편이 적절하다고 판단했기 때문입니다. 
1. 주문을 받는다(VC구현 아직)
2. 제조 가능한 메뉴인지 확인한다
3. 제조한다

위 과정 중 3에서 2를 호출해서 동작여부를 결정하는 것이 자연어 기준으로는 순서가 맞아 보이지만, 로직적으로는 올바르지 않다는 것을 깨달았습니다. 
VC를 아직 구현하지 않은 상태지만, VC에서 '2를 먼저 검증 후 3을 아예 실행하지 않거나 실행하도록' 하는 편이 적절한 코드이고,
3 시점에 '제조하거나 하지 않는다'로 에러·얼럿을 띄우는 분기처리를 할 예정인데 내부호출로 구현하면 이 부분이 깔끔하지 못할 거라 생각했습니다.
(+ 두 함수의 매개변수 타입은 기존의 내부호출을 염두에 두고 설정한 것으로, 이후 수정될 수 있습니다)

　
## ✔  구현을 보류한 것들
- [ ] **재고 감소 메서드만 구현**
   재고 변경 방법이 다양할 듯하여 재고변경을 감소&증가 2가지로 분리하였으며, 
   현재로선 과일재고를 사용하기만 하므로 재고 증가 메서드는 구현하지 않았습니다. 
   이후 스텝 요구조건에 따라 차근차근 구현해보겠습니다! 
- [ ] **에러처리**
   재고나 주문에 관한 에러 구현도 이후 스텝 진행하며 더 고민해보겠습니다..!
- [ ] **옵저버**
   과일 재고의 변동을 수시로 확인하고 업데이트 하기 위해 옵저빙 방법을 같이 공부해보기로 했습니다.
   현업에서 많이 쓰거나 저의 프로젝트 성격을 고려할 때 추천하실 만한 옵저빙 방법이 있다면 조언 부탁드립니다!
- [ ] **기타**
   이외에도 레시피들의 재료 수가 일정하다면 재고확인이나 재고소진 코드의 효율성을 위해 forEach를 어떤 매칭패턴으로 대체할 수 있을까, 메뉴의 주문 가능 여부를 메뉴별 변수나 연관값으로 만들까 등등 많은 고민을 했지만 여러모로 다음 스텝을 진행해봐야 알겠다는 결론을 내렸습니다. 

　
　

2023-01-04 23:11 UTC, protocorn93 requested changes
두분 모두 고생하셨어요! 깔끔하게 코드를 작성해주셔서 리뷰하기 너무 수월했고, 요구사항뿐만 아니라 필요하다고 생각되는 메서드들도 적절히 잘 추가해주셨네요👍

간단한 코멘트 몇개 남겨놓았어요! 

---

###  M-V-C사이의 로직 분배

> 패턴에서 로직에 관한 코드는 Model, Controller 중 어디로 가야 하는지 고민했습니다.
FruitStore의 countStock(of:)와 같이 단순히 내부에 저장된 값을 확인해 주는 코드는 모델에 있기에 적합하지만,
JuiceMaker의 startBlending()은 FruitStore의 decrease()를 불러오는데, 이는 유저의 쥬스 제조 버튼을 누름을 뷰컨트롤러에서 받아오면 모델의 값을 변경하는 부분으로 모델보다 컨트롤러(ViewController)에서 관리하는 편이 좋지 않을까 라고 생각했습니다.
MVC 패턴의 포인트는 View와 Model의 분리라고 알고 있는데, 컨트롤러에는 어느정도의 역할이 할당되면 좋을지 궁금합니다.

저는 컨트롤러가 온전히 비즈니스 로직을 가져가야 한다고 생각해요. 모델로부터 값을 가져와 가공/연산하여 뷰에 전달하는 역할인거죠. 

데이터를 어떻게 표현해야할지는 뷰의 역할이라고 보여져요. 컨트롤러가 5를 반환하면 이를 "남은재고 : 5개"로 표현하는건 뷰의 역할이라고 생각해요.

하지만 iOS에서 MVC로 작성하다보면 ViewController의 존재가 애매해지는데요(이름도 뷰+컨트롤러죠) 보통 그래서 많은 회사, 팀에선 UIView, UIViewController 모두를 뷰로 보고 작업하곤해요. 뷰 컨트롤러에 비즈니스 로직을 담당하는 객체를 주입해서 사용하곤 하죠! 뷰/뷰컨트롤러는 사용자 이벤트 (터치, 드래그, 라이프사이클 이벤트) 등을 해당 비즈니스 로직에 전달만 해주는 것이구요.

그리고 종종 구조에 따라 컨트롤러와 뷰 사이에 프레젠터라는 객체를 두기도해요. 위와 같은 상황에서 컨트롤러가 5를 반환하면 프레젠터는 5를 받아 "남은재고 : 5개"를 반환하고 뷰는 이를 받아 화면에 보여주고 말이죠. 

뷰를 최대한 아무것도 모르고 주는대로 화면에 출력해주는 바보 객체로 만들려는 노력 중 하나죠! 


### 옵저버
과일 재고의 변동을 수시로 확인하고 업데이트 하기 위해 옵저빙 방법을 같이 공부해보기로 했습니다.
현업에서 많이 쓰거나 저희 프로젝트 성격을 고려할 때 추천하실 만한 옵저빙 방법이 있다면 조언 부탁드립니다!

찾아보면 아시겠지만 다양한 방법이 있는데요! 델리게이트 패턴도 이 시점에 한번 고민해볼만한 방법같아요.

2023-01-04 23:11 UTC, protocorn93 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    private func checkOrderable(of ingredients: [Fruits: Int]) -> Bool {
인자로 `[Fruits: Int]`라는 딕셔너리 자료구조를 직접 받는것보단 `Juice`를 받는게 가독성 면에서 좀 더 좋을 것 같아요.

2023-01-04 23:11 UTC, protocorn93 commented on JuiceMaker/JuiceMaker/Model/Fruits.swift
> +}
개인적으론 복수형이 아니라 단수형이 맞지 않나라는 생각도 드네요!

2023-01-05 07:28 UTC, ueunli commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    static var shared = FruitStore(initialStock: 10)
참조타입 인스턴스이므로 let선언으로 바꿨습니다!

2023-01-05 07:28 UTC, ueunli commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
>  class FruitStore {
> Jenna

궁금했지만 끝까지 조사하지 못하고 넘어갔던 부분인데, 콕 집어주신 덕분에 오개념을 바로잡을 수 있었어요! 
~~(얼마 전 어떤 예시코드를 잘못 해석해서 싱글턴 클래스에 final키워드를 붙일 필요가 없다고 알고 있었습니다...)~~
싱글턴 클래스가 될 필요성과는 별개로, 하위클래스 상속이 필요하지 않다는 점에서 final키워드도 적용했습니다.

2023-01-05 07:29 UTC, ueunli commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    var stocks = [Fruits: Int]()
놓친 부분입니다ㅠㅠ private으로 수정했습니다. 
private(set)도 고려했지만 현재로서는 범위 내 메서드들로 기능 수행에 문제가 없어 배제했습니다. 
각 요소들의 접근수준에 대해 고민하는 습관을 들여보겠습니다!!

2023-01-05 07:29 UTC, ueunli commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func countStock(of fruit: Fruits) -> Int {
네이밍 추천 감사합니다! `countStock` → `count`로 맞췄습니다 🙆‍♀️

2023-01-05 07:30 UTC, ueunli commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    private func checkOrderable(of ingredients: [Fruits: Int]) -> Bool {
안그래도 호출시점을 변경하며 매개변수까진 잘 다듬지 못한 것 같아 아쉬웠는데 말씀하신 방법이 좋은 것 같아 반영했습니다!
가독성을 위해 for-in문의 '`ingredient in ingredients`'를 유지하고 싶어서 
1. 매개변수명 변경, (`ingredients` → `menu`)
2. 내부에서 ingredients 상수를 따로 선언하는 과정을 추가했습니다. 
(`let ingredients = menu.recipe`)

사실 주관적인 부분이라, 차라리 1, 2를 하지 않고 '`ingredient in ingredients.recipe`'로만 수정하는 게 나은지 고민이 됩니다. 조언 부탁드려요 !!

2023-01-05 13:29 UTC, protocorn93 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    private func checkOrderable(of ingredients: [Fruits: Int]) -> Bool {
저는 1번이 좀 더 무난한 것 같네요!

2023-01-06 00:38 UTC, merged