[Step 1] JoJo, Is
tasty-code/ios-juice-maker pull request #23
Opened 2023-01-04 15:15 UTC by CODEMASTERJO

안녕하세요 @zdodev 
이번 프로젝트를 함께 진행하게된 JoJo, Is 입니다.
새해 복 많이 받으세요 🙏

2023년 첫 리뷰어로 소대를 만나게 되어서 반갑습니다!
저희의 코드가 아직 많이 부족하지만 리뷰해주시는 부분 열심히 보강해서 Step이 진행될때마다 성장하고 싶어요🔥\
어떤 피드백이든 무조건 좋습니다! 편하게 리뷰해주세요!!

ㅤ

## ‼️ 요구 사항 및 구현 사항

### 🙋‍♂️ 각 객체 별 책임

| Name | Type | 책임 |
| -- | -- | -- |
| Fruit | enum | FruitStore가 저장하는 Element이자 Juice의 재료인 과일 목록 |
| Storing| protocol | Element를 저장할 수 있는 Storing 청사진
| FruitStore | final class | Fruit 창고 객체-클래스 |
| Juice | enum | Fruit가 재료인 주스 목록 |
| JuiceMaker | struct | Juice를 만드는 객체-구조체 |
| JMError | enum | JuiceMaker 관련 Error 목록 |

> **FruitStore는 다음의 조건을 충족해야합니다**ㅤ

### 🍎 Fruit

> **FruitStore가 관리하는 과일의 종류 : 딸기, 바나나, 파인애플, 키위, 망고**

```swift
enum Fruit: CaseIterable {
    case strawberry
    // ...
}
```

- 관리하는 과일 종류가 정해져있기에 enum으로 Fruit을 정의했어요
- FruitStore에서 각 과일의 초기 재고를 편하게 설정하기 위해 CaseIterable 프로토콜을 채택했어요

> **각 과일의 초기 재고 : 10개** \
> **각 과일의 수량 n개를 변경하는 기능이 있습니다**

### 📦 Storing

```swift
typealias Storeable = Hashable & CaseIterable

protocol Storing {
    associatedtype Element: Storeable
    
    var items: [Element: Int] { get }
    
    mutating func add(item: Element, count: Int)
    mutating func subtract(pairOfItems: [Element: Int])
    func hasEnough(pairOfItems: [Element: Int]) -> Bool
}

extension Storing {
    func hasEnough(pairOfItems: [Element: Int]) -> Bool {
        //..
    }
}
```

- protocol을 공부해보고 싶어서 Storing이라는 프로토콜을 프로젝트에 도입했어요
- 실제로 구현해야 하는 구체적인 타입인 과일 저장소를 추상화 시켜 하나의 저장소 프로토콜을 만들었어요
- 저장소는 Storeable(저장할 수 있는?)한 Element라면 무엇이든 저장할 수 있도록, Generics을 도입해 표현했어요
- 특정 아이템의 재고가 충분한지 확인하는 hasEnough method는 Storing을 conform한 구체 타입의 저장 프로퍼티를 수정하지 않기 때문에 extension의 default implementation으로 구현할 수 있다고 생각했어요
- FruitStore의 Fruit이 CaseIterable이기 때문에 Storeable은 Hashable & CaseIterable한 타입으로 설정했어요

### 🏬 FruitStore

```swift
final class FruitStore: Storing {
    private(set) var items: [Fruit : Int] = [:]
    
    init(defaultStock count: Int) {
        for fruit in Fruit.allCases {
            add(item: fruit, count: count)
        }
    }
    // ...
}
```

- FruitStore는 Storing 프로토콜을 conform하고 Element는 Fruit이예요
- FruitStore을 초기화할 때 각 Fruit을 돌면서 defaultStock만큼 재고를 채워요
- `각 과일의 수량 n개를 변경하는 기능`이라는 요구 사항을 n개로 설정하는 것이 아니라 n개를 더하거나 뺀다고 생각했기에, add, subtract 메서드를 구현했어요

> **JuiceMaker.swift 파일에 다음의 조건을 충족하는 JuiceMaker 타입을 정의합니다**
>
> - FruitStore의 과일을 사용해 과일쥬스를 제조합니다<br>
>   - 딸기쥬스 : 딸기 16개 소모
>   - 바나나쥬스 : 바나나 2개 소모
>   - 키위쥬스 : 키위 3개 소모
>   - 파인애플 쥬스 : 파인애플 2개 소모
>   - 딸바쥬스 : 딸기 10개 + 바나나 1개 소모
>   - 망고 쥬스 : 망고 3개 소모
>   - 망고키위 쥬스 : 망고 2개 + 키위 1개 소모

### 🥤 Juice

```swift
enum Juice {
    case strawberryJuice
    // ...

    var ingredients: [Fruit: Int] {
        // ...
    }
}
```

- Juice의 종류 역시 enum으로 정해줬어요
- Juice의 ingredicents 속성을 통해 쥬스 별 재료와 필요한 개수를 담은 Dictionary를 알 수 있어요

> **과일의 재고가 부족하면 과일쥬스를 제조할 수 없습니다** \
> **JuiceMaker는 FruitStore를 소유하고 있습니다**

### 👩‍🌾 JuiceMaker

```swift
struct JuiceMaker<T:Storing> where T.Element == Fruit {
    private(set) var fruitStore: T
    
    mutating func make(juice: Juice) throws -> Juice {
        let ingredients: [Fruit: Int] = juice.ingredients
        guard fruitStore.hasEnough(pairOfItems: ingredients) else {
            throw JMError.outOfStock
        }
        self.fruitStore.subtract(pairOfItems: ingredients)
        
        return juice
    }
}
```

- JuiceMaker의 make함수는 다음과 같아요
  - Juice 타입 매개 변수인 juice를 받아요
    - juice는 viewController에서 눌린 버튼에 따라 만들어서 던질 예정이예요
  - Fruit만 저장할 수 있는 Storing 프로토콜을 conform하는 fruitStore를 소유하고 있어요
  - 싱글톤이 아니라 그 대안 중 하나인 의존성 주입을 사용 및 공부해보고 싶어서 Protocol과 Generic을 이용했어요
  - juice의 재료를 확인한 후 창고에서 재료들이 충분한지 확인해요
    - 충분하지 않으면 재고 없다는 오류를,
    - 충분하다면 창고에서 재료를 줄인 후 쥬스를 반환해요

## 고민한 부분

### 1️⃣ FruitStore

- 과일 재고 관리
  - 과일과 과일수량의 값을 매칭하여 관리하기 위해 Dictionary를 사용하였습니다.
  - `Key: 과일` `Value: 수량`
- 과일수량 초기값 설정
  - 과일별로 초기값을 지정하기 위해 `CaseIterable`프로토콜의 `allCases`를 활용하여 설정하였습니다.
- add 함수 관련  

    ```swift
    final class FruitStore: Storing {

        func add_before(item: Fruit, count: Int) {
              guard let stock = items[item] else {
                  // some Error
              }
              items[item] = stock + count
        }

        func add_after(item: Fruit, count: Int) {
              items[item, default: 0] += count
        }
    }
    ```

  - 초기에는 Dictionary의 subscript의 반환값이 `optional`로 반환되어 `guard let` 바인딩을 통해 해결했습니다.
  - 하지만, guard let 바인딩으로 처리하면 else 구문을 처리하여야 하는데 앞선 input값을 hasEnough함수를 통해 정제하므로 실행될 일이 없다고 판단하였습니다.
  - 이에 더불어 기존에 없는 key라고 하더라도 그것이 Storing의 Element이기만 하다면, (FruitStore의 경우 Fruit) 새롭게 추가하면 된다고 생각했어요.
  - 따라서 subsript의 `default`를 활용해 기존 구현을 수정했습니다.

- subtract 함수 관련

    ```swift
    final class FruitStore: Storing {
      
        func subtract_before(item: Fruit, count: Int) {
              guard let stock = items[item] else {
                  // some Error
              }
              items[item] = stock - count
        }

        func subtract_after(item: Fruit, count: Int) {
              items[item]? -= count
        }
    }
    ```
  - add와 동일하게 초기에는 Dictionary의 subscript의 반환값이 `optional`로 반환되어 초기에는 `guard let` 바인딩을 통해 해결했습니다.
  - 그러나 FruitStore에 의존하는 JuiceMaker는 Juice를 만들 때 만들기 전에(subtract 함수를 호출하기 전에) `hasEnough` 함수를 통해 미리 재고를 확인합니다.
  - 그러므로 nil이 나올 가능성이 없다고 판단, FruitStore의 subtract는 위와 같이 구현을 변경했습니다.
    - nil이면 아무런 동작을 하지 않고, nil이 아니면 뺀 값으로 업데이트합니다.
  - 그런데 Storing 프로토콜만 떼어 놓고 생각한다면, hasEnough method가 먼저 불린다는 보장이 없어서 갖고 있지 않은 Element 혹은 재고보다 많은 수를 빼달라는 요청이 들어올 수 있습니다.
  - ❓ 이를 고려한다면 subtract method가 이러한 상황에 대비해야 해야 하는게 아닐까 싶기도 한데, 소대의 의견은 어떤가요?
  
### 2️⃣ Storing

- Storing을 프로토콜로 정의한 이유는 2가지 입니다.
   1. Storing 프로토콜을 인터페이스로 활용하여 `JuiceMaker`의 `FruitStore`에 대한 의존성을 해결한다.
   2. 향후 `Store`의 확장성을 높인다. -> 확장성을 위해 `Generic`을 활용했습니다.

- Naming
  - Store 프로토콜 명칭을 고민하던 중 [이 글](https://santoshbotre01.medium.com/naming-a-protocol-in-swift-b0d933b44ddc)을 참고하여
  - > Performed by = name+ing\
    > Performed on = name+able \
    > Performed for = name+delegate\
    > Unable to identify = name + protocol
  - 저장소의 프로토콜 명칭은 `Storing`을 사용하였고, 저장소에 저장되는 요소는 Hashable & CaseIterable을 채택한 `Storeable`을 제너릭 타입명칭으로 활용하였습니다
  - ❓ 적절한 네이밍이었을까요?
  - ❓ 소대의 좋은 네이밍 비결은 무엇인가요?

### 🤔 의존성 주입

- 해당 과제의 모델링을 논의하면서 `Singleton`, `상위객체(JuiceMaker)-하위객체(FruitStore)`, `의존관계역전원칙을 적용한 의존성 주입` 등 다양한 방법을 시도했어요
- 함께 스터디를 진행한 결과 의존성 주입을 활용하면 확장성을 추가로 가져갈 수 있다고 판단하여 이와 같이 구성했습니다
- 친숙하지 않은 Protocol과 Generic을 함께 사용해서 그런지 실제 코드에 적용할 때 어려웠는데요
  1. 처음에는 단순히 외부에서 fruitStore 객체를 만들어 주입해주면 의존성 주입이라고 생각했어요
  2. 그런데 함께 공부하다보니 JuiceMaker의 프로퍼티인 fruitStore가 FruitStore 타입이 아니라 Storing 타입이어야 성공적으로 DIP를 적용한 것이라고 생각했습니다
  3. 그래서 Storing을 JuiceMaker에 넣은 결과.. 수 많은 컴파일 에러와 인사하게 되었고
  4. 구글신과 애플 문서, 스택 오버플로우를 돌고 돌아 지금의 코드가 완성되었어요
- Fruit를 저장하는 Storing 타입만 fruitStore가 될 수 있도록 타입 제약을 걸었다고 이해했습니다.
- 그런데 현재의 코드가 유연성을 해치지는 않는지, 즉 이러한 타입 제약이 프로토콜을 채택한 의미를 퇴색시키는 것이 아닐지 생각했어요.
- ❓ 이에 대한 소대의 의견은 어떤지, 그리고 이를 개선할 방법이 있을지 궁금해요!

2023-01-05 15:17 UTC, zdodev requested changes
안녕하세요. @CODEMASTERJO , @vanism2091 !
리뷰어 소대입니다!

리뷰하면서 코드에 고민을 하신 흔적이 많이 보였습니다.👍👍
전체적인 네이밍도 잘 지어주신 것 같습니다!
README 정리를 깔끔하게 해주셔서 작성 의도를 파악하는데 도움이 많이 되었습니다!

몇 가지 궁금증을 남겨보았습니다!
확인 부탁드립니다~

2023-01-05 15:17 UTC, zdodev commented on JuiceMaker/JuiceMaker/Model/Fruit.swift
> +}
`Fruit` 를 열거형으로 표현해보셨네요. 좋습니다👍

2023-01-05 15:17 UTC, zdodev commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
이렇게 하면 과일의 수를 일일이 대입하지 않아도 한 번에 과일 초기 재고를 저장할 수 있겠네요!👍
그런데! 과일 초기 재고가 과일마다 다른 수량으로 채워져야 합니다. 라는 기획이 추가되면 어떨까요?😲 당장 구현하지 않더라도 고민해보면 좋겠습니다!

2023-01-05 15:17 UTC, zdodev commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
말씀해주신 것 처럼 다음과 같은 코드는 재고가 마이너스가 될 수 있는 위험성이 있습니다.
재고가 0 미만이 될 수 없도록 안전장치가 필요해보입니다.
안전장치를 구현해볼 수 있을까요? 다양한 방법이 있어보입니다!

2023-01-05 15:17 UTC, zdodev commented on JuiceMaker/JuiceMaker/Model/JMError.swift
> +enum JMError: Error {
축약어보다는 다른 개발자가 봐도 이해하기 쉽도록 전체 길이의 이름을 사용하는 것은 어떨까요?

2023-01-05 15:17 UTC, zdodev commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +enum Juice {
`Juice` 를 열거형으로 표현해보셨네요. 좋습니다👍

2023-01-05 15:17 UTC, zdodev commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +struct JuiceMaker<T:Storing> where T.Element == Fruit {
1. Swift 공식 문서처럼 제네릭 타입 제약조건에 공백을 삽입하는 것은 어떨까요?
2. `JuiceMaker` 를 구조체로 정의한 이유가 궁금합니다!
3. `JuiceMaker` 가 과일 재고 체크에 대한 책임을 가지고 있어야 할까요? 의견이 궁금합니다!
4. `JuiceMaker` 가 `Fruit` 를 알고 있어야 할까요? 의견이 궁금합니다!

2023-01-05 15:17 UTC, zdodev commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        self.fruitStore.subtract(pairOfItems: ingredients)
`self` 를 사용하여 참조할 때랑 사용하지 않고 참조할 때의 기준이 궁금합니다!

2023-01-05 15:17 UTC, zdodev commented on JuiceMaker/JuiceMaker/Model/Storing.swift
> +typealias Storeable = Hashable & CaseIterable
`Storing` 은 `CaseIterable` 를 준수하지 않는 타입을 저장 요소로 사용할 수 없는 것인가에 대한 의문이 들었습니다!
오히려 `Fruit` 타입을 위한 `Storeable` 을 정의한 것은 아닐까 라는 생각도 들었습니다!
제약조건을 조금 더 유연하게 정의해보는 것은 어떨까요? 
위 생각에 대한 의견이 궁금합니다! 지금도 좋은 추상화 시도라고 생각합니다!👍
프로토콜을 사용하여 저장 요소와 저장소 필요 기능을 정의한 것도 좋았습니다.👍

2023-01-05 15:17 UTC, zdodev commented on JuiceMaker/JuiceMaker/Model/Storing.swift
> +protocol Storing {
적절한 네이밍이라고 생각합니다!
네이밍은 저도 많이 어려운데요. 길이에 상관없이 가독성을 우선시하고 타입, 메서드, 프로퍼티의 역할과 책임을 잘 표현할 수 있는 이름으로 지어보려고 노력하고 있습니다!

2023-01-05 15:17 UTC, zdodev commented on JuiceMaker/JuiceMaker/Model/Storing.swift
> +
개행을 삽입한 이유가 있을까요?

2023-01-05 15:17 UTC, zdodev commented on JuiceMaker/JuiceMaker/Model/Storing.swift
> +}
프로토콜 기본구현 문법을 사용해보셨네요.👍

2023-01-05 15:17 UTC, zdodev commented on JuiceMaker/JuiceMakerTests/JuiceMakerTests.swift
> +//        FSsut.setAllStocks(to: 10)
불필요한 코드는 제거하는 것이 어떨까요? 아래의 테스트 코드도 확인 부탁드립니다!

2023-01-05 15:17 UTC, zdodev commented on JuiceMaker/JuiceMakerTests/JuiceMakerTests.swift
> +    }
사용하지 않는 코드는 제거하는 것이 어떨까요?

2023-01-06 05:35 UTC, vanism2091 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
pairOfItems:([Fruit: Int])를 매개변수로 받는 새로운 init을 구현해봤어요😆

2023-01-06 05:45 UTC, vanism2091 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
Storing에서 subtract를 구현하는 두 가지 다른 관점이 있었어요.
자세히 말하자면 Error를 취급하지 않음(value가 nil인 경우)과 재고 없음(부족한 경우) 2가지로 나누느냐, 재고 없음만 하느냐의 문제예요.

Storeable에서  CaseIterable 조건을 제거하면서, 새로운 Store 구현체의 items이 모든 element case를 Key값으로 갖지 않을 수 있기 때문에 생긴 관점 차이였어요.

우리는 취급하지 않음이라는 에러를 새로 만들지 않고 재고 없음 에러로 통일하기로 결정했어요. 그래서 nil이거나 재료가 부족한 경우 모두 guard문을 이용해 동일한 에러를 뱉게 구현했습니다 :)

만약 value가 nil일 때, 부족할 때를 서로 다른 Error로 취급하고 싶다면 guard문을 두 번 사용하거나 switch-case-let 문을 이용해 구현할 수 있을 것 같아요.

2023-01-06 05:48 UTC, vanism2091 commented on JuiceMaker/JuiceMaker/Model/JMError.swift
> +enum JMError: Error {
소대의 의견에 동의해요! 수정해서 반영했습니다 :)

2023-01-06 05:59 UTC, vanism2091 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +struct JuiceMaker<T:Storing> where T.Element == Fruit {
1. [공식 문서](https://docs.swift.org/swift-book/LanguageGuide/Generics.html#ID187)를 확인해서 반영했어요. 좋은 의견 감사합니다!

2. class를 쓰지 않은 이유
    1. `JuiceMaker`는 다른 subclass로 상속받을 일이 없다고 생각했어요.
    2. FruitStore와 달리 `JuiceMaker`는 어떤 객체를 위한 간접적인 저장소 역할을 하지 않아요
    3. JuiceMaker의 identity가 중요하지 않다고 생각했어요.
    - JuiceMaker를 다른 변수에 할당하거나 함수의 인자로 넘길 때, 새로운 JuiceMaker가 생기는게 맞다고 생각했어요(마치 새로운 자판기가 생기는 느낌..!)  
    4. 따라서 공식 문서의 제안에 따라 구조체를 선택했어요

소대의 의견은 어떤가요?

2023-01-06 06:05 UTC, vanism2091 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +struct JuiceMaker<T:Storing> where T.Element == Fruit {
3. JuiceMaker가 과일 재고 체크에 대한 책임을 갖고 있어야 하나요?

이 리뷰를 보고 `책임`에 대한 저와 조조의 의견이 달라서 이는 더 공부해봐야 한다고 결론냈어요.

우선 제 생각은 다음과 같아요.
스텝 1을 구현할 때, 일반적으로 메이커가 재료가 있는지 창고를 직접 확인하는 식으로 모델링했어요. 카페 알바가 음료를 만들기 전에 재고가 있는지 체크하는 것 처럼요. 
그런데 그렇게 모델링하지 않아도 충분히 괜찮을 것 같았어요. 사실 이런 책임을 부여했기에 이전의 subtract 구현 문제가 생긴 것 같기도 했거든요. Storing 구현체 안에서 재고확인 및 subtract를 함께 하는 방법이 있을 것 같아요.

조조의 의견은 아래와 같았습니다.
책임을 가지면 안됩니다. 책임을 가지면 의존성을 지니게 되므로, 과일 재고 체크는 fruitStore에서만 책임을 가집니다.

그런데 우리가 의견이 달랐던 부분은,
PR을 보낸 코드에서 JuiceMaker가 책임을 갖는지 여부였어요.
저는 make 함수 내에서 `fruitStore.hasEnough`를 호출하며 재고를 확인하기 때문에 재고 체크에 대한 책임을 갖고 **있다**고 보았어요.
그러나 조조는 재고 확인의 구현이 JuiceMaker가 아니라 FruitStore에 있으므로 현재 `JuiceMaker`에는 재고 확인의 책임이 **없다**고 보았어요.
이에 대해서는 서로 `책임`과 `객체 지향`에 대한 공부를 더 진행한 후 의견을 다시 나눠보기로 했습니다 :)

2023-01-06 06:11 UTC, vanism2091 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +struct JuiceMaker<T:Storing> where T.Element == Fruit {
4. `Fruit`을 알고 있어야 하는가

모델링 시 (Fruit)JuiceMaker 이므로 Fruit인 창고만 받아야하는게 아닐까 싶었어요. Car 창고를 갖고 쥬스를 만들 수는 없으니까요. 그렇지만 쥬스는 과일 쥬스만 있는게 아니고 채소 쥬스가 있을 수 있으니.. 더 좋은 추상화를 하고 싶으면 아래와 같아야 할 것 같아요.
1. 쥬스의 재료인 Fruit 역시 추상화된 프로토콜에 의존해야 하고, 
2. JuiceMaker의 Juice도 쥬스가 될 수 있음과 같은 프로토콜에 의존하며 
3. 현재의 Juice는 해당 프로토콜을 구체화한 FruitJuice로 구현해야 할 것 같은..

길게 말한 걸 한 줄로 줄이자면, 더 좋은 추상화를 위해선 알아선 안될것같아요.

소대의 의견은 어떤가요?

2023-01-06 06:17 UTC, vanism2091 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        self.fruitStore.subtract(pairOfItems: ingredients)
self는 타입의 인스턴스에 대한 명시예요.
swift에서는 매개변수 등 지역변수가 인스턴스의 프로퍼티 명과 동일할 때에 self를 명시해야 하고 그렇지 않으면 생략해도 된다고 알고 있어요. 

그런데 인스턴스의 프로퍼티 앞에 `self`를 붙여주는게 더 명확한 코드인 것 같아서 앞으로는 프로퍼티 앞에 self를 붙이는 것으로 통일하려고 해요!

어떤 기준이든 코드를 일관적으로 작성하는 게 가독성에 중요한 요소 같아요. 소대의 리뷰를 통해 이 부분을 다시 한 번 생각할 수 있었습니다.
코드 꼼꼼하게 확인해주셔서 감사해요!😊

2023-01-06 06:19 UTC, vanism2091 commented on JuiceMaker/JuiceMaker/Model/Storing.swift
> +typealias Storeable = Hashable & CaseIterable
소대의 말대로 CaseIterable은 allCases를 사용하기 위해, 즉 프로그래머의 편의를 위해 정의한 제약조건이 맞아요.
실제로 Storeable의 필수 조건은 Element가 Dictionary의 Key이기에 Hashable이기만 하면 됩니다
이를 제거하는 것이 유연하며 더 좋은 추상화라고 생각해
이를 반영했습니다!

2023-01-06 06:19 UTC, vanism2091 commented on JuiceMaker/JuiceMaker/Model/Storing.swift
> +
딱히 없어요 :) 삭제했습니다!

2023-01-06 06:19 UTC, vanism2091 commented on JuiceMaker/JuiceMakerTests/JuiceMakerTests.swift
> +    }
확인 후 제거했습니다!👍

2023-01-08 15:11 UTC, zdodev approved these changes
안녕하세요. @CODEMASTERJO , @vanism2091 !

리뷰에 대한 코멘트(의견이나 생각)을 잘 정리해주셨습니다👍
궁금증에 대해서 좋은 이유와 많은 고민을 가지고 의견을 전달해주신 점이 좋았습니다!👍
좋은 추상화에 대한 고민도👍👍

Step 1 진행하시느라 고생하셨습니다!
여기서 마무리하도록 하겠습니다!🎉

2023-01-08 15:11 UTC, zdodev commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
좋습니다!👍

2023-01-08 15:11 UTC, zdodev commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +struct JuiceMaker<T:Storing> where T.Element == Fruit {
1. class를 쓰지 않은 이유
공식 문서의 내용을 참고해서 정해보셨네요! 좋습니다!👍
어떤 기준으로 구조체로 정의했는지 궁금했습니다😄 

2. `Fruit`를 알고 있어야 하는가
말씀해주신 방법도 좋은 방법이라고 생각합니다!
현실 세계에서 주스를 만드는 사람이 재료를 알아야 하지만, 객체 지향 세계에서는 주스 메이커가 재료를 알아야 할 필요가 없을 수도 있지 않을까(현재 구조에서는) 싶었습니다!

2023-01-08 15:11 UTC, merged