[STEP 1] june, iyeah
tasty-code/ios-juice-maker pull request #24
Opened 2023-01-05 02:42 UTC by iYeahh

코리 안녕하세요! @corykim0829

이번 쥬스 메이커 프로젝트를 함께하게 된 june과 iyeah 입니다 :)
저희가 열심히 STEP 1 구현을 해보았는데, 코드에 대한 의견을 주시면 큰 도움이 될 것 같습니다!
새해 복 많이 받으시고 잘 부탁드려요 🙋🏻‍♂️

# 세부사항
- [x] FruitStore 충족 조건
    - [x] 관리하는 과일의 종류 : 딸기, 바나나, 파인애플, 키위, 망고
    - [x] 각 과일의 초기 재고 : 10개
    - [x] 각 과일의 수량 n개를 변경하는 기능

- [x] JuiceMaker의 충족 조건
    - [x] FruitStore의 과일을 사용해 과일쥬스 제조
    - [x] 과일의 재고가 부족하면 과일쥬스 제조 불가
    - [x] JuiceMaker는 FruitStore를 소유하고 있음
- [x] (선택사항) 필요한 경우 오류처리(throw, try-catch)를 구현

# 설명

## 과일 저장소 (`final class FruitStore`)
-> final class, struct를 고민하다 final class로 적어놓긴 했지만 어떤 타입이 좋을지 고민이 되는 부분입니다. 아래 `고민된 부분` 항목에 적어두었습니다.

- `defaultStock: UInt` : 초기 재고(10)
initializer에 직접 10을 대입해도 동작은 같지만, 매직넘버를 사용하지 않기 위해 초기값을 static let 프로퍼티로 지정했습니다.

- `stockByFruit` : 과일 이름과 재고를 딕셔너리로 묶어 재고를 저장
배열과 딕셔너리를 고민하다 과일의 개수 검색의 시간복잡도를 고려하여 O(1)에 수정할 수 있는 딕셔너리를 사용했습니다.

- `enum Fruit: CaseIterable` : 과일의 종류
stockByFruit에서 사용할 키 값으로 과일들의 종류를 저장할 enum Fruit을 만들었고, 초기 재고를 반복문을 통해 설정해주기 위해 CaseIterable 프로토콜을 채택하였습니다.

- `func subtractStock(fruitType: Fruit, quantity: UInt) throws` : 과일이 소진될 때 재고를 감소시키는 함수
guard문을 통해 에러상황에 대한 처리를 했습니다.
- `func addStock(fruitType: Fruit, quantity: UInt) throws` : 과일이 채워졌을 때 재고를 증가시키는 함수
guard문을 통해 에러상황에 대한 처리를 했습니다.

## 주스 메이커 (`struct JuiceMaker`)
- `enum Juice` : 주스의 종류
    - `var recipe` : 주스를 만드는데 필요한 과일 및 개수 (딕셔너리)

- `func isEnoughStock(fruit: FruitStore.Fruit, requiredQuantity: UInt) throws -> Bool` : 과일의 재고가 충분한지 확인하는 함수
guard문을 통해 에러상황에 대한 처리를 했습니다.

- `func makeJuice(_ juice: Juice) throws` : 재고가 충분한지 확인한 후, 주스를 제조하는 함수
들여쓰기 2번을 초과하지 않는다는 요구사항을 만족시키기 위해 where절을 사용했습니다

## 에러
`enum JuiceMakeError` : .outOfStock, .notExistFruit
`.outOfStock` : 과일 저장소에 해당 과일의 재고가 부족할 때 발생하는 에러
`.notExitFruit` : 과일 저장소에 과일이 존재하지 않을 때 발생하는 에러

# 고민된 부분

1. FruitStore를 `final class` VS `struct`?

```swift
- 재고를 관리하는 속성의 특성상 추후 여러 개의 JuiceMaker가 생긴다면 
  재고 관리를 함께 할 수도 있을 것 같아 Singleton 구현도 고려하였습니다.

- final class와 struct를 계속 고민하다가 결국 결론을 내리지 못했는데요,
  어떤 걸로 구현해도 문제가 되진 않을 것 같아서요.
  혹시 이 중에 문제가 되는 선택지가 있는지, 혹은 더 나은 선택지가 있다면 그 이유가 궁금합니다!
```
```swift
2. '갯수'를 나타내는 변수명 짓기

- JuiceMaker에서 requiredQuantity, FruitStore에서 과일을 사용하거나 추가할 때 
  quantity를 사용했는데 더 좋은 변수명 있을까요 ~?
```

2023-01-05 12:46 UTC, corykim0829 requested changes
두분 모두 고생하셨습니다👏👏👏
전반적으로 깔끔하게 구현 잘 하셨고, 테스트 코드까지 작성하신 부분이 아주 훌륭합니다 👍

`Fruit`과 `Juice`를 모두 nested enum으로 구현하셨는데, 확장/변화가 많은 타입은 enum 보다는 다른 하나의 클래스나 구조체로 표현하는 것이 좋습니다. 참고하세요 👀 (꼭 바꾸라는 의미는 아닙니다!)

> 고민된 부분

1.FruitStore를 final class VS struct?
➡️ 결론지으신 것 처럼 현재 스텝 단계에서는 두가지 모두 사용해도 괜찮습니다 :)
일단 유지하고, 다음 스텝에서 변경해야할 것 같다면 그 때 바꿔도 될 것 같아요.
나중에 싱글톤은 사용할 때에는 장단점을 잘 고려해보시고 사용하는게 좋습니다.

2.'갯수'를 나타내는 변수명 짓기
➡️ quantity는 양을 의미해서 개수를 나타내기에는 애매한 것 같네요. 다른 변수명으로 개선해보면 좋을 것 같습니다!

2023-01-05 12:46 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Model/Error.swift
> +extension JuiceMakerError: LocalizedError {
Error description까지 처리한 부분이 좋네요 😊

2023-01-05 12:46 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    private(set) var stockByFruit = [Fruit: UInt]()
Dictionary 변수명 좋네요 👍

2023-01-05 12:46 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func subtractStock(fruitType: Fruit, quantity: UInt) throws {
파라미터명에서 fruitType보다 fruit으로 더 깔끔하게 표현하면 좋겠네요

2023-01-05 12:46 UTC, corykim0829 commented on JuiceMaker/JuiceMakerTests/JuiceMakerTests.swift
> +        XCTAssertNoThrow(try fruitStore.subtractStock(fruitType: .banana, quantity: quantity))
예외 처리와 이를 테스트한 부분이 좋네요 😊

2023-01-05 12:46 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func isEnoughStock(fruit: FruitStore.Fruit, requiredQuantity: UInt) throws -> Bool {
함수나 프로퍼티에서 Bool 값을 반환하면 is- 가 대표적이지만, has, can 과 같은 조동사를 쓰기도 합니다.
여기서는 hasEnoughStock을 쓰면 더 자연스러울 것 같아요 😊

2023-01-05 12:46 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func makeJuice(_ juice: Juice) throws {
파라미터명을 외부에서 보이지 않게 하는 것 보다는, make(juice: Juice)와 같이 사용하는게 스위프트 가이드에 더 맞는 네이밍입니다! 참고하세요 :)

2023-01-05 12:46 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        }
```
for (fruit, requiredQuantity) in juice.recipe where try !isEnoughStock(fruit: fruit, requiredQuantity: requiredQuantity)
```
여기 44번째 라인이 너무 길어서 가독성이 떨어지네요. 개선하면 좋겠습니다!

2023-01-06 01:24 UTC, iYeahh commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func makeJuice(_ juice: Juice) throws {
의견 반영하여 함수명과 파라미터명 변경했습니다!

2023-01-06 01:24 UTC, iYeahh commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func isEnoughStock(fruit: FruitStore.Fruit, requiredQuantity: UInt) throws -> Bool {
의견 반영하여 함수명 변경했어요 :)

2023-01-06 01:29 UTC, iYeahh commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func subtractStock(fruitType: Fruit, quantity: UInt) throws {
파라미터명과 타입의 이름 중복으로 가독성이 떨어질 듯하여 
원래 `fruit`으로 정했다가 `fruitType`로 변경했었던 거라 다시`fruit`으로 수정하긴 했는데
혹시 `fruit: Fruit` 이렇게 이름이 중복돼도 가독성이 괜찮은 건지 궁금합니다 🤔

2023-01-06 01:34 UTC, zhunhe commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        guard let fruitStock: UInt = self.stockByFruit[fruitType] else {
- `fruitStock: UInt =`에서 `fruitStock =`으로 수정했습니다 !
- `self.` 같은 경우에는 사용, 생략하는 기준이 있을까요?
    -> 이전에 사용하던 객체지향 언어가 C++에서 `this->변수명`을 컨벤션으로 사용해왔었는데, Swift가 간결함보다는 표현을 중시하는 느낌을 받았었거든요. 길더라도 알기 쉽게 표현해주기 위해 `self` 키워드를 붙여왔는데 어떠한 기준으로 생략하는지 코리의 의견을 들어보고 싶습니다 ! 👀

2023-01-06 01:40 UTC, iYeahh commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        }
들여쓰기 2번 이하라는 조건을 맞추기 위해 **if**문이 아닌 **where**절을 추가하다 보니
코드가 길어져 가독성이 떨어진 것 같습니다...!
`func make(juice)` 에서 에러를 던지는 부분을 `func hasEnoughStock` 의 리턴부분에 구현하였습니다.

원래 Bool 타입을 리턴하는 함수 `func hasEnoughStock` 를
조건을 확인하여 에러를 던지는 동작만 기능하도록 변경하였는데 혹시 문제는 없는지 여쭤보고 싶습니다 ❕

2023-01-06 01:49 UTC, zhunhe commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    static let defaultStock: UInt = 10
- static으로 선언하면 인스턴스를 생성하기 전에도 사용할 수 있는 것으로 알고 있습니다 ! 이니셜라이저에서 인스턴스 생성할 때 재고를 초기화해주기 위한 값으로 사용하기 위해 static을 사용했습니다 !

2023-01-06 08:49 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    static let defaultStock: UInt = 10
그렇군요, 초기화 시에만 사용된다면, 생성할 때만 상수로 넣어주는게 더 깔끔해보이네요! 😊

2023-01-06 08:56 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func subtractStock(fruitType: Fruit, quantity: UInt) throws {
변수명, 파라미터명에 실제 타입 값이 들어갈게 아니라면 type을 언급하는건 오해를 일으킬 수 있다고 생각해요.
`fruit: Fruit` 부분은 가독성 괜찮다고 생각합니다.
`make(juice: Juice)`와 동일하게 보면 좋을 것 같아요

2023-01-06 09:12 UTC, corykim0829 approved these changes
수고하셨습니다! 👍

남겨드린 피드백은 다음 스텝 진행하면서 같이 수정하면 좋을 것 같아요 😊

2023-01-06 09:12 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func hasEnoughStock(fruit: FruitStore.Fruit, requiredCount: UInt) throws {
메소드가 hasEnoughStock면 Bool 타입을 반환해야할 것 같은데, 그러지 않아서 어색하네요!
그리고 requiredCount도 그냥 count라고 해도 충분히 의미 전달이 될 것 같네요

2023-01-06 09:12 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +            try fruitStore.subtractStock(fruit: fruit, count: count)
같은 juice.recipe를 for문을 두번 사용하는 걸 개선할 수 있어 보이네요!
재고 검사 부분을 juiceMaker의 하위객체인 fruitstore에서 처리하게 하는건 어떨까요?

2023-01-06 09:12 UTC, merged

2023-01-10 01:47 UTC, iYeahh commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func hasEnoughStock(fruit: FruitStore.Fruit, requiredCount: UInt) throws {
hasEnoughStock 메소드는 STEP 2에서 Bool 타입을 리턴하는 함수로 구현하였고,
requiredCount -> count로 변경하였습니다!

2023-01-10 01:49 UTC, iYeahh commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +            try fruitStore.subtractStock(fruit: fruit, count: count)
for문을 두 번 사용하는 것을 개선하였고, 재고 검사 부분은 fruitStore에서 처리하도록 수정하였습니다!