[Step2]
tasty-code/ios-juice-maker pull request #27
Opened 2023-01-09 06:50 UTC by devxsby

> 안녕하세요 콘 🥕 @protocorn93 주말 잘 보내셨나요?! 🙋🏻‍♀️
> 이번 step2는 저번에 말씀해주신 접근제어 및 구조적 측면에 유의하며 구현해 보았어요~!
> 항상 좋은 리뷰 달아주셔서 감사해요 !! 오늘도 좋은 하루 보내세요 😁

# 🧃 구현사항
### 폴더링
프로젝트 규모가 작아서 간단하게만 폴더링을 해봤어요.
모델에 Fruits, Juice만 두고 싶은데 나머지 두 곳을 어디에 둘 지 몰라서 일단 같이 두었어요. 좋은 의견있으면 코멘트 부탁으려요!!
<img width="300" alt="스크린샷 2023-01-09 15 44 13" src="https://user-images.githubusercontent.com/80062632/211253720-6b1fd6ad-87fd-43e0-bcb5-39599e765ab5.png">

### 화면이동
다음 2가지 상황에서 NavigationController `Push`방식으로 뷰를 전환해요.
- 재고수정 버튼 클릭
- 재고를 수정하시겠습니까? 얼럿에서 '예' 선택

### Alert
2가지 얼럿(.alert)을 구현했어요.
- `alert(succeed:)`: 버튼 1개('확인')
- `alert(failed:)`: 버튼 2개('예', '아니오')

### 주문기능
뷰가 2개이므로 각각 `OrderVC`, `StoreVC`로 네이밍을 맞춰 파일을 분리했어요.
OrderVC에는 다음과 같은 기능을 넣었어요.
- 주문처리: `orderButtonDidTap(_:)`
- 재고동기화: `syncFruitStocks()`
　 
　 
# 🧃 고민했던 부분
## ✔ 화면이동 방식

`presnt-dismiss` vs `push-pop` 방식 중 후자의 방식으로 구현했어요.!!

그 이유는, 기본적으로 스택으로 쌓이는 네비게이션 컨트롤러가 임베드 된 StoreViewController와 연결하여 navigationBarItem 의 backButtonItem과 추후에 생길 완료버튼을 넣을 rightButtonItem을 사용하기 위해서에요.

또한 화면 전환을 케이스가 2번인 경우를 감안하여 재사용을 위해 StoreViewController안에 private function으로 `pushToStoreViewController`라는 별개의 메서드를 생성하였어요.

콘은 어떤 방식이 적합해 보이시는지, 실제로 뷰의 화면 전환을 할 때 어떤 특성을 고려하여 구현하시는 지 여쭙고 싶어요~!!

![이미지](https://cdn.discordapp.com/attachments/1059289195396472942/1061878713605697636/2023-01-09_14.26.45.png)

　
## ✔  에러처리 여부

에러정의 및 처리 여부를 고민하다가, 아래 이유로 하지 않기로 했어요
1. 던지게 되는 에러가 '필요한 과일재고가 충분치 않은 경우' 1개뿐이에요. <br>현재 로직상 '다루는 과일 목록에 없는 과일인 경우'는 절대 발생하지 않으므로 에러구현을 위한 에러가 될 수 있다고 생각했어요
2. 위 내용에 해당하는 에러 또는 얼럿이 처리되는 시점은 모두 `orderButtonDidTap(_:)` 내의 '주문가능여부확인~음료제조' 사이가 돼요. <br> 둘 중 하나만으로 요구사항 충족 및 흐름 제어에 충분하므로 얼럿만 구현했어요! 😁

2023-01-09 11:50 UTC, protocorn93 requested changes
두 분 모두 고생하셨어요! 

---

## 폴더구조

`FruitStore`나 `JuiceMaker`는 현재 비즈니스 로직을 수행하기 때문에 서비스 도메인에 속한다고 생각하고 별도 Service 폴더를 만들어 거기에 위치시킬 것 같아요.

그리고 storyboard 파일과 ViewController 파일은 굳이 폴더를 나눌 필요는 없어보여요. 

---

## 구현사항

> 주문기능
>
> 뷰가 2개이므로 각각 OrderVC, StoreVC로 네이밍을 맞춰 파일을 분리했어요.
OrderVC에는 다음과 같은 기능을 넣었어요.
>
>주문처리: orderButtonDidTap(_:)
재고동기화: syncFruitStocks() ← viewWillAppear에서 호출하였어요.

`viewWillAppear`에서 sync를 하는 것은 바람직해보이지 않아요. `OrderVC`에서 `StoreVC`가 아니라 다른 화면으로 이동이 가능해지면 그때도 돌아오면 sync 메서드가 호출될텐데요. 이를 방지하기 위해 `bool` 타입 변수를 사용하는 것도 이상할 것 같아요.

현재 화면과 다음 화면간의 의존성을 최대한 끊어내는 것이 좋아요. 지금은 현재 화면에서 A 화면으로만 가지만 B, C, D 화면으로도 갈 수 있어요. A, B, C, D 화면은 반드시 현재 화면에서만 진입할 수 있는게 아닐 수 있어요. 다른 화면에서도 A, B, C, D를 진입할 수도 있어요. 

그렇기 때문에 뷰컨트롤러 라이프 사이클에 의존해 비즈니스 로직을 처리하는 것은 조금 위험할 수 있어요. 코드가 쉽게 지저분해지기도 쉽죠. 

그래서 저는 현재 이 상황에선 델리게이트 패턴을 학습해보시고, 여기에 적용해보시는 것도 권장해드려요. 

---

## 고민했던 부분 

> presnt-dismiss vs push-pop 방식 중 후자의 방식으로 구현했어요.!!
>
> 그 이유는, 기본적으로 스택으로 쌓이는 네비게이션 컨트롤러가 임베드 된 StoreVC와 연결하여 navigationBarItem 의 backButtonItem과 추후에 생길 완료버튼을 넣을 rightButtonItem을 사용하기 위해서에요.
>
>또한 화면 전환을 케이스가 2번인 경우를 감안하여 재사용을 위해 StoreVC안에 private function으로 pushToStoreVC라는 별개의 메서드를 생성하였어요.
>
>콘은 어떤 방식이 적합해 보이시는지, 실제로 뷰의 화면 전환을 할 때 어떤 특성을 고려하여 구현하시는 지 여쭙고 싶어요~!!

내비게이션 스택을 이용한 화면 전환이냐, 모달 방식(present 등)을 통한 화면 전환이냐는 화면의 맥락에 따라 다를 것 같아요. 모달 방식에도 다양한 화면 전환 방법이 있는데, 언제 사용하는게 좋을지에 대해선 [HIG 문서](https://developer.apple.com/design/human-interface-guidelines/patterns/modality/)를 참고해주시면 좋을 것 같아요. 

내비게이션 스택을 통한 흐름은 보통 끊김없이 이어지는 흐름의 사용자 경험을 제공하고자 할 때 사용하곤해요. 다양한 케이스가 있을텐데, 회원가입 정보 입력도 있을 수 있고, 커뮤니티에서 게시글 탐색도 그러한 맥락이겠죠.

2023-01-09 11:50 UTC, protocorn93 commented on JuiceMaker/JuiceMaker/Source/Model/FruitStore.swift
> +    private(set) var stocks = [Fruits: Int]()
코드를 보면 읽기도 개방할 필요가 없어보이는데 `private(set)`으로 선언한 이유가 궁금하네요!

2023-01-09 11:50 UTC, protocorn93 commented on JuiceMaker/JuiceMaker/Source/Model/Juice.swift
> +    case mangoKiwi = "망키쥬스"
이 프로젝트와는 무관할 수 있지만, 저는 보통 enum의 `rawValue`에는 description 성격의 값을 매핑하진 않는 것 같아요. 보통 description 같은 변수는 get-only 프로퍼티로 별도로 선언하곤해요.

rawValue는 서버 응답값을 매핑하는데 사용하곤해요. 에러를 예로 들면 `rawValue`에는 서버 에러코드가 들어갈 수 있어요. `rawValue`를 통해 enum 값을 생성할 수 있는 값으로 매핑하곤해요.

```swift
enum MyAppError: String { 
  case authError = "auth_error"
}
```

2023-01-09 11:50 UTC, protocorn93 commented on JuiceMaker/JuiceMaker/Source/Model/JuiceMaker.swift
> +            guard eachStock >= ingredient.value else { return false }
## Optional

정답은 없지만 팀이나 주변 개발자분들의 코드스타일을 보면 보통 `guard` 문은 `guard`문 아래에 어떤 로직을 더 수행할 때 사용하곤 하는 것 같아요. 저라면 

```swift 
if eachStock >= ingredient.value { 
  return false 
}
```

이렇게 작성했을 것 같아요.

2023-01-09 11:50 UTC, protocorn93 commented on JuiceMaker/JuiceMaker/Source/Screen/Order/VC/OrderVC.swift
> +final class OrderVC: UIViewController {
## Style

VC보단 `ViewController`로 풀어서 작성해주시는게 좋을 것 같아요. 왠만해선 풀어서 사용하시는 습관을 가져가는게 좋을 것 같아요!

2023-01-09 11:50 UTC, protocorn93 commented on JuiceMaker/JuiceMaker/Source/Screen/Order/VC/OrderVC.swift
> +    override func viewWillAppear(_ animated: Bool) {
`super.viewWillAppear(animated)` 호출해주셔야 해요.

2023-01-09 11:50 UTC, protocorn93 commented on JuiceMaker/JuiceMaker/Source/Screen/Order/VC/OrderVC.swift
> +    @IBOutlet var juiceOrderButtons: [UIButton]!
`IBOutlet`도 `private`으로 선언 가능해요!

2023-01-09 11:50 UTC, protocorn93 commented on JuiceMaker/JuiceMaker/Source/Screen/Order/VC/OrderVC.swift
> +    @IBAction func orderButtonDidTap(_ sender: UIButton) {
`IBAction`도 `private` 선언 가능해요!

2023-01-09 11:50 UTC, protocorn93 commented on JuiceMaker/JuiceMaker/Source/Screen/Order/VC/OrderVC.swift
> +        let juice = Juice.allCases[sender.tag]
http://minsone.github.io/programming/check-index-of-array-in-swift

이런 방식으로 `extension`을 통해 안전하게 딕셔너리를 다루는 방법을 사용하시는 것도 좋아요. 일반적인 모든 회사에서 이런 `extension`은 존재할거에요.

2023-01-09 11:50 UTC, protocorn93 commented on JuiceMaker/JuiceMaker/Source/Screen/Order/VC/OrderVC.swift
> +        }
`Fruits.allCases.enumerated()`, `Juice.allCases.enumerated()`를 사용하면 조금 더 유지보수와 가독성에 도움이 될 것 같아요.

2023-01-09 11:50 UTC, protocorn93 commented on JuiceMaker/JuiceMaker/Source/Screen/Order/VC/OrderVC.swift
> +    private func alert(succeed menu: Juice) {
`presentAlert`와 같이 행위를 함께 묘사해주면 좋을 것 같아요. Swift style guide로 구글링해보시면 다양한 회사에서 심지어 구글에서도 제공하는 가이드문서가 있어요. 이런 곳들을 참고해서 메서드명이나 변수명등을 작성하는데 도움을 받을 수 있어요.

2023-01-10 01:23 UTC, ueunli commented on JuiceMaker/JuiceMaker/Source/Model/FruitStore.swift
> +    private(set) var stocks = [Fruits: Int]()
말씀하신 대로 `private`이 맞습니다!!
고칠 부분이었는데 제가 stocks 관련 시행착오 중 깜빡한 것 같아요ㅠㅠ 수정했습니다✨

2023-01-10 02:36 UTC, ueunli commented on JuiceMaker/JuiceMaker/Source/Model/Juice.swift
> +    case mangoKiwi = "망키쥬스"
예시 감사합니다! 말씀해주신 부분 및 기존 rawValue의 용도(꼭 필요하지 않음)을 고려하여 원시값 없는 열거형으로 수정했어요🙆‍♀️
> [수정한 커밋](https://github.com/tasty-code/ios-juice-maker/pull/27/commits/a725414593f0b7b64976dd2c67ad4bbf224fe59f)

2023-01-10 02:40 UTC, ueunli commented on JuiceMaker/JuiceMaker/Source/Model/JuiceMaker.swift
> +            guard eachStock >= ingredient.value else { return false }
짚어주신 대로 검증 후 처리할 동작이 딱히 없어 if문으로 수정하였습니다 !!
> [수정한 커밋](https://github.com/tasty-code/ios-juice-maker/pull/27/commits/c60dff12c5b6a237f015dec0a062da257df1c0d5)

2023-01-10 02:42 UTC, ueunli commented on JuiceMaker/JuiceMaker/Source/Screen/Order/VC/OrderVC.swift
> +final class OrderVC: UIViewController {
뷰컨트롤러들의 네이밍을 `...ViewController`로 수정했습니다 ✨
> [수정한 커밋](https://github.com/tasty-code/ios-juice-maker/pull/27/commits/b9d8b8bbf9fd3240aa5ae334ccff26f728285c4f)

2023-01-10 02:43 UTC, ueunli commented on JuiceMaker/JuiceMaker/Source/Screen/Order/VC/OrderVC.swift
> +    override func viewWillAppear(_ animated: Bool) {
수정했습니다! 
> [수정한 커밋](https://github.com/tasty-code/ios-juice-maker/pull/27/commits/cefd239062b5bbeb3db38447aaa73544ca45d997)

2023-01-10 02:43 UTC, ueunli commented on JuiceMaker/JuiceMaker/Source/Screen/Order/VC/OrderVC.swift
> +    @IBOutlet var juiceOrderButtons: [UIButton]!
수정했습니다! 
> [수정한 커밋](https://github.com/tasty-code/ios-juice-maker/pull/27/commits/2bb366794963af1785a7c0350cc55881e54548ce)

2023-01-10 02:43 UTC, ueunli commented on JuiceMaker/JuiceMaker/Source/Screen/Order/VC/OrderVC.swift
> +    @IBAction func orderButtonDidTap(_ sender: UIButton) {
수정했습니다! 
> [수정한 커밋](https://github.com/tasty-code/ios-juice-maker/pull/27/commits/2bb366794963af1785a7c0350cc55881e54548ce) (위와 동일)

2023-01-10 04:38 UTC, ueunli commented on JuiceMaker/JuiceMaker/Source/Screen/Order/VC/OrderVC.swift
> +    private func alert(succeed menu: Juice) {
`presentAlert`로 수정했습니다!
위 배열 서브스크립트 확장 및 옵셔널처리 과정에서 매개변수들도 약간 달라졌어요.
- `alert(succeed:)` → `presentSucceedAlert(menu:)`: 버튼으로부터 쥬스이름 String을 받아 주문성공 메시지를 띄웁니다
- `alert(failed:)` → `presentFailedAlert()`: 매개변수 없이 주문실패 및 재고수정에 관한 일정한 안내를 띄웁니다
> [수정한 커밋 1](https://github.com/tasty-code/ios-juice-maker/pull/27/commits/778a5ceabd42f74ca6be8915926b5d6212b728df)
[수정한 커밋 2](https://github.com/tasty-code/ios-juice-maker/pull/27/commits/bd7ebb6185318880ac6ac3f845f40f957d299350)

2023-01-10 04:38 UTC, ueunli commented on JuiceMaker/JuiceMaker/Source/Screen/Order/VC/OrderVC.swift
> +        let juice = Juice.allCases[sender.tag]
`Global/Extension/Array+.swift`파일을 만들어 구현해봤습니다
index out of range를 안전하게 피하는 법이 무엇일까 궁금했는데 알려주셔서 감사해요!
- 파라미터명을 고민하다가 보여주신 예제의 `safe`가 보편적인 네이밍인 것 같아 `safe`로 했어요
- 이로써 배열의 해당 서브스크립트 반환값이 옵셔널이 되었으므로 기존 사용처들에 옵셔널 처리(암시적추출, 바인딩 등)도 함께 넣어주었어요
- 프로토콜이나 제네릭을 활용하면 조금 더 구체적으로 다양하게 정의할 수 있을 것 같은데 처음 안 방식이라 시도하기 조심스러웠어요.
조금 더 공부해보고 다음 스텝이나 프로젝트에서 적용해보고 싶어요🌱
> [수정한 커밋](https://github.com/tasty-code/ios-juice-maker/pull/27/commits/054cedd31d8df23b76a32711db3cb1c9003647d3)

2023-01-10 11:33 UTC, merged