쥬스메이커 [STEP 2] Sunny, Joo
tasty-code/ios-juice-maker pull request #30
Opened 2023-01-10 03:38 UTC by SunnnySong

안녕하세요! 라자냐☺️(@wonhee009) Joo와 Sunny입니다😁

감기는 다 나으셨나요?!! 저는 이번에 A형 독감에 걸렸어서 이번 Step2 초반 구현을 Joo 혼자 진행했었습니다ㅜㅜ 덕분에 모든 바이러스에 면역이 생긴 느낌이지만 회복하는데 힘들었기 때문에 라자냐가 단순 감기였기를 바라요! 

이번 저희 프로젝트에 대해 간단히 말씀드리자면, Delegate를 둘 다 처음 사용해봤기 때문에 이 부분이 제일 헷갈리고 어려웠어요. 충분한 토의도 해보고 검색도 해보면서 코드를 구현했지만 아직까지 Delegate에 대해 100% 이해하지 못했어요😭  라자냐가 알고 있는, 알려주고 싶은 delegate 관련 지식이 있다면 중점적으로 적어주시면 감사하겠습니다~~~~👍

# 구현 부분

☑️ **‘재고 수정’** 버튼 터치하면 **‘재고 추가’** 화면으로 이동

☑️ 쥬스 주문

☑️ 쥬스의 재고가 있는 경우 : 쥬스 제조 후 **"(주문받은 쥬스) 나왔습니다! 맛있게 드세요!"** 얼럿 표시

☑️ 쥬스의 재고가 없는 경우 : **"재료가 모자라요. 재고를 수정할까요?"** 얼럿 표시

☑️ 예 선택시 -> **‘재고 추가’** 화면으로 이동

☑️ 아니오 선택시 -> 얼럿 닫기

☑️ 쥬스 제조 후, 화면에 재고가 변경된 사항을 반영

# Custom Delegate 사용

이번 Step2에서는 총 2가지의 Custom Delegate를 사용했습니다. 

## 1. textUpdateDelegate

```swift
protocol textUpdateDelegate: AnyObject {
    func updateLabel(fruit: Fruits)
}
```

textUpdateDelegate는 쥬스 제조 이후 바뀐 과일의 재고를 label에 업데이트 하기 위해 만들었습니다. 

- 수정 전 코드

```swift
// ViewController.swift
@IBAction func orderJuice(_ sender: UIButton) {
    guard let juice = Menu(rawValue: sender.tag) else {
        return
    }
    juiceMaker.order(juice: juice)
		updateLabelText(labels: fruitLabels)
}

private func updateLabelText(labels: [UILabel]) {
    let fruitStore = FruitStore.shared
    for label in labels {
        guard let fruit = Fruits(rawValue: label.tag) else {
            return
        }
        label.text = fruitStore.stock(fruit: fruit)
    }
}
```

변경 전 코드에서는 쥬스 제조 버튼을 누르면 juiceMaker의 order 함수가 호출되고, updateLabelText 함수를 통해 모든 과일 재고 label text가 업데이트 되었어요. 

하지만 저희는 딸바 주스를 눌렀을 때, 딸기와 바나나 재고 label만 변경되는 것이 아닌 모든 과일의 label이 변경되는게 비효율적이라 생각했어요. 

- 수정 후 코드

```swift
// ViewController.swift 
@IBAction func orderJuice(_ sender: UIButton) {
    guard let juice = Menu(rawValue: sender.tag) else {
        return
    }
    juiceMaker.order(juice: juice)
}

extension ViewController: textUpdateDelegate {
    func updateLabel(fruit: Fruits) {
        fruitLabels.forEach { label in
            if label.tag == fruit.rawValue {
                let quantity = fruitStore.stock(fruit: fruit)
                label.text = String(quantity)
            }
        }
    }
}
```

```swift
// FruitStore.swift
weak var textUpdateDelegate: textUpdateDelegate?

func remove(according recipe: [Fruits: Quantity]) throws {
    try checkFruit(according: recipe)
    for (fruit, quantity) in recipe {
        guard let stock = fruits[fruit] else {
                return
        }
        let newQuantity = stock - quantity
        fruits.updateValue(newQuantity, forKey: fruit)
        textUpdateDelegate?.updateLabel(fruit: fruit)
    }
}
```

orderJuice 버튼을 통해 쥬스를 주문하게 되면 juiceMaker.order을 통해 FruitStore.remove가 실행됩니다. remove함수에서는 checkFruit을 통해 재고가 부족한지 여부를 판단해요. 이를 통과하면 쥬스 제조에 필요한 양이 재고에서 줄어들게 되고, 저희는 이때 줄어든 Fruits을 textUpdateDelegate를 통해 ViewController에 전달해주었어요. 

textUpdateDelegate를 통해 주스 제조 Fruits을 전달해준 이유는 한 쥬스당 두개의 과일이 필요한 경우가 있기 때문이에요. 이렇게 전달한 Fruits의 rawValue가 label.tag와 동일한 label만 text를 다시 업데이트 해주었어요. (Fruits.rawValue와 Fruits의 재고를 나타내는 label의 tag는 동일)

    ❓ textUpdateDelegate를 사용하지 않고, 쥬스 제작에 사용한 과일의 label만 update해주는 다른 방법이 있을까요? 
    ❓ 또 저희가 사용한 textUpdateDelegate가 적절히 사용된 예시일까요?

## 2. juiceAlertDelegate

```swift
protocol juiceAlertDelegate: AnyObject {
    func madeJuiceAlert(juice: Menu)
    func shortOfStockAlert(message: String)
}
```

juiceAlertDelegate는 Model에서 쥬스 제조가 완료된 이후 Alert을 띄어주기 위해 만들었어요.

```swift
// ViewController.swift
@IBAction func orderJuice(_ sender: UIButton) {
    guard let juice = Menu(rawValue: sender.tag) else {
        return
    }
    juiceMaker.order(juice: juice)
}

extension ViewController: juiceAlertDelegate {
    func madeJuiceAlert(juice: Menu) {
        let alert = UIAlertController(
            title: "\(juice.koreanName) 나왔습니다! 맛있게 드세요",
            message: nil,
            preferredStyle: .alert
        )
        let checkAction = UIAlertAction(title: "확인", style: .default)
        alert.addAction(checkAction)
        self.present(alert, animated: true)
    }

    func shortOfStockAlert(message: String) {
        guard let modifiedStockVC = self.storyboard?.instantiateViewController(identifier: "ModifiedStock") else { return
        }
        let alert = UIAlertController(
            title: "\(message)",
            message: "재료가 모자라요. 재고를 수정할까요?",
            preferredStyle: .alert
        )
        let cancelAction = UIAlertAction(title: "아니오", style: .default)
        let modifiedAction = UIAlertAction(title: "예", style: .destructive) { _ in
            self.present(modifiedStockVC, animated: true)
        }
        alert.addAction(cancelAction)
        alert.addAction(modifiedAction)
        alert.preferredAction = modifiedAction
        self.present(alert, animated: true)
    }
}
```

```swift
// JuiceMaker.swift
weak var juiceAlertDelegate: juiceAlertDelegate?

func order(juice: Menu) {
    do {
        try make(juice: juice)
        juiceAlertDelegate?.madeJuiceAlert(juice: juice)
    } catch {
        juiceAlertDelegate?.shortOfStockAlert(message: error.localizedDescription)
    }
}
```

저희가 제일 고민되는 부분이 바로 juiceAlertDelegate 부분이었어요. 이 구현에 대해 저희의 생각은 조금 달랐는데요. 

- Sunny 의견
    
    : 저는 MVC 패턴에서 Controller는 View를 통해 사용자 입력을 전달 받고, 그로 인한 데이터 처리는 모두 Model에서 진행해야 한다고 생각했어요. 따라서 Controller에서는 orderJuice 버튼을 통한 사용자 입력을 Model인 juiceMaker.order()에 연결하고 실질적인 쥬스 제조는 juiceMaker에서 하도록 구현했습니다. 
    
    저는 juiceAlertDelegate를 통해 Model이 Controller에 주스 제조 결과를 전달해주고, Controller에서는 그 결과를 받아 View에게 Alert을 띄우라 전달해주는 것이라 이해했어요. 이런 식의 Delegate 사용이 적절한 것인지 궁금합니다!
    
- Joo 의견
    
    : MVC 패턴을 이해하기로는 Model과 Controller는 Model의 변화를 **Notification & KVO 방식**을 통해 알리고 View와 Controller는 **요청(delegate)과 데이터에 대한 요청(data source)**으로 ****접근하는 걸로 알고 있습니다. JuiceMaker 에서 사용되는 Delegate는 Model이 View에 직접적으로 전달하는 거 같은 느낌이 들어서 이러한 방법이 맞는 건지 궁금합니다.
    

이 부분은 아직 MVC와 Delegate에 대한 확실한 이해가 부족했기 때문에 생긴 고민이라고 생각해요. 이 부분에 대해 조금 더 공부를 해야 하지만 Delegate를 이해한 라자냐의 팁을 알려주시면 정말 감사하겠습니다😁

# 고민되는 부분

### MVC 패턴에서 Error 처리

MVC 디자인 패턴을 사용할 때, Error의 핸들링(do-catch문)을 Model에서 처리를 해야되는 지 궁금해요. 

현재 코드에서는 Model에 해당하는 JuiceMaker에서 Alert에 사용되는 메시지를 전달했어요.

```swift
struct JuiceMaker {
    let fruitStore = FruitStore.shared
    weak var juiceAlertDelegate: juiceAlertDelegate?

    func order(juice: Menu) {
        do {
            try make(juice: juice)
            juiceAlertDelegate?.madeJuiceAlert(juice: juice)
        } catch {
            juiceAlertDelegate?.shortOfStockAlert(message: error.localizedDescription)
        }
    }
}
```

### UILabel, UIButton tag 사용

```swift
// Fruits.swift
enum Fruits: Int, CaseIterable {
    case strawberry = 0
    case banana
    case pineapple
    case kiwi
    case mango
}

// JuiceMaker.swift
@IBAction func orderJuice(_ sender: UIButton) {
    guard let juice = Menu(rawValue: sender.tag) else {
        return
    }
		// ...
}

// ViewController.swift
@IBOutlet var fruitLabels: [UILabel]!

private func setupLabel() {
    fruitLabels.forEach { label in
        guard let fruit = Fruits(rawValue: label.tag) else {
            return
        }
        let quantity = fruitStore.stock(fruit: fruit)
        label.text = String(quantity)
    }
}
```
여러 UILabel, UIButton을 하나의 함수 혹은 Outlet Collection에서 동작을 할 수 있도록 각각의 tag를 부여, 해당하는 enum과 같게 구현했어요. 이러한 방식이 말고도 중복되는 것을 줄이기 위한 방법이 있는지 궁금해요!

2023-01-11 02:24 UTC, wonhee009 requested changes
수고하셨습니다 :)
코멘트 남겨두었으니 확인 부탁드려요.

- JuiceMaker가 Model이라고 생각하는 이유가 있을까요? 
- 저는 tag를 잘 사용 안하긴 하는데요. 이후 유지보수하면서 tag가 유니크한 값을 갖지 않게 되는 경우도 있고, 현재 코드처럼 tag와 뭔가를 매칭하는 방식이 이후 유지보수를 거치다보면 이 값이 원하는대로 매칭되지 않는 경우도 있는거 같습니다. 코드로 UI를 작성한다면 custom Button을 정의하고 그 버튼이 프로퍼티로써 fruit의 타입을 갖게 정의할 수 있을거 같습니다.

2023-01-11 02:24 UTC, wonhee009 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +protocol juiceAlertDelegate: AnyObject {
```suggestion
protocol JuiceAlertDelegate: AnyObject {
```

2023-01-11 02:24 UTC, wonhee009 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +protocol textUpdateDelegate: AnyObject {
fruit 재고가 업데이트 되었음을 알려주는 delegate로 이해했습니다.
text는 없어도 의미전달 가능할거 같습니다.

2023-01-11 02:24 UTC, wonhee009 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +            return Int()
nil이 아니고 Int()를 반환하는 이유가 있을까요?

2023-01-11 02:24 UTC, wonhee009 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +}
주스를 만드는걸 성공/실패 했을 경우 관련 alert을 생성해주기 위한 delegate로 이해했는데요.
관련 alert을 생성하는건 ViewController의 역할일 뿐이고 delegate와는 연관이 없는거 같습니다.
delegate에서는 주스 만드는걸 성공했는지, 재고가 부족해서 실패햇는지 정도를 알려주면 될거 같고 해당 delegate의 메서드에서는 어떤 로직을 처리하든 ViewController의 역할일거 같습니다.
이후에 주스를 만드는데 성공하면 alert을 생성하고 또 다른 로직을 ViewController가 처리하는 스펙이 생긴다면 현재 상태에서는 delegate 안에 메서드를 하나 더 추가해야할거 같습니다.

2023-01-12 04:21 UTC, SunnnySong commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +
네! 수정했습니다

2023-01-12 04:22 UTC, SunnnySong commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +protocol textUpdateDelegate: AnyObject {
넵! UpdateDelegate로 수정 완료했습니다!

2023-01-12 04:23 UTC, SunnnySong commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +protocol juiceAlertDelegate: AnyObject {
수정했습니다!

2023-01-12 08:24 UTC, SunnnySong commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +            return Int()
stock()함수의 파라미터로 Fruits만 받기 때문에 Fruits case에 없는 과일이 조회될 경우를 생각하지 않았어요. 라자냐의 리뷰를 받고 만약의 경우를 생각해 return값을 Optional로 변경하고 fruits에 존재하지 않는 과일의 재고를 조회하는 경우 nil을 리턴하도록 했어요.☺️

2023-01-12 08:24 UTC, SunnnySong commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +}
기존 코드에서 JuiceAlertDelegate는 쥬스 제조 성공 여부를 ViewController에게 전달해주는 것 보다 ViewController에서 Alert을 띄우게 명령하는 느낌이 더 강했어요. 라자냐의 리뷰를 받고 쥬스 제조 결과에 따라 Alert을 띄우는 주체가 ViewController가 될 수 있도록 ViewController에서 에러를 처리했어요. 이 과정에서 JuiceAlertDelegate의 역할이 사라졌기에 삭제했어요!

2023-01-13 04:22 UTC, SunnnySong commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    let fruitStore = FruitStore.shared
FruitStore.shared를 사용하기 쉽도록 프로퍼티로 새로 정의했었어요. 하지만 메모리 낭비가 되겠구나 라는 생각이 들어 수정했습니다!

2023-01-13 04:28 UTC, SunnnySong commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        }
휴먼 에러를 최소화 하기 위해서 tag를 사용하지 않는 방법을 찾아봤어요. protocol을 사용한 custom UIButton class와 custom UILabel class 를 만들어서 과일과 쥬스를 명시해주는 것으로 변경을 했어요. custom UILabel class에는 과일 뿐만 아니라 UILabel.text 까지 지정했어요. 각 과일 Label에서 과일 종류만 지정하면 과일 수량이 자동으로 Label에 적용될 수 있도록 구현했어요.☺️

2023-01-13 13:11 UTC, wonhee009 approved these changes
수고하셨습니다~

2023-01-13 13:11 UTC, merged