쥬스메이커 [STEP 2] june, iyeah
tasty-code/ios-juice-maker pull request #31
Opened 2023-01-10 04:23 UTC by iYeahh

코리 안녕하세요! @corykim0829

STEP 2 에서는 STEP 1 머지 전 피드백 주신 부분도 모두 수정하였으니 참고 부탁드릴게요.
코리의 리뷰 덕분에 많이 배우며 즐겁게 프로젝트 진행하고 있습니다!
이번 리뷰도 잘 부탁드릴게요 🐶

# 📃 세부사항
- [x] '재고수정' 버튼을 누르면 '재고 추가' 화면으로 이동
![](https://i.imgur.com/ubOfWof.png)

- [x] 각 주문 버튼 터치 시
    - [x] 쥬스 재료의 재고가 있는 경우![](https://i.imgur.com/he85h6R.png)

    - [x] 쥬스 재료의 재고가 없는 경우
![](https://i.imgur.com/7KxWKye.png)

    - [x] 예 버튼 선택시 재고수정 화면으로 이동
![](https://i.imgur.com/ubOfWof.png)

# ✏️ 설명

| name                     | type        | 역할과 책임                           |
|:------------------------ | ----------- |:----------------------------------- |
| JuiceMaker               | struct      | 과일의 재고를 가지고 쥬스 제조             |
| Juice                    | enum        | 쥬스 종류, 종류에 따른 레시피             |
| FruitStore               | final class | 과일의 재고 관리                       |
| JuiceMakerError          | enum: Error | 재고 관련 Error                       |
| JuiceMakerViewController | final class | 주문 버튼으로 주문을 받아 주스 제조, 재고 수정 |

# 🤔 고민된 부분

## 1. IBOutlet Collection
각 과일의 재고를 나타내는 Label 5개를 하나씩 연결하여 사용하는 것보다
여러 Button을 하나의 action으로 연결하는 것처럼 다른 방법을 고민하게 되었어요!
* IBOutlet Collection를 적용하여 배열로 묶인 레이블들의 각 인덱스와 `FruitStore`의 `enum Fruit` `raw value`를 일치시켜 각 과일의 레이블에 변경된 재고를 표시하였습니다.
* 고민되는 것은 레이블의 인덱스가 어디에도 정확히 표시되지 않아 코드를 구현한 저희만 순서를 알 수 있기 때문에 추후 유지 보수가 어려울 것 같다는 우려가 되었어요.
* Label에 enum Fruit의 raw value와 같은 값으로 tag를 주는 것도 방법 중 하나로 고려해보았는데,
지금 이 코드로도 괜찮은지, tag를 주는 것이 해결책이 될 수 있을지, 또 다른 의견이 있으신지 궁금합니다!

## 2. Modally vs Show
화면 이동 방식에 대해 고민을 했는데요,
처음엔 재고를 수정할 때만 잠시 보이는 화면으로 생각하여  Modally 방식으로 구현하려다가
* 이 프로젝트의 스토리보드는 가로로 고정이 되어 있고, 가로 화면에서의 Modally 방식은 원래 화면으로 돌아가도록 터치할 수 있는 빈 공간이 제공되지 않아서 버튼을 만들어야 했기 때문에 자동으로 backButton이 제공되는 Show 방식으로 구현하게 되었습니다.

STPE 3에서 '닫기' 버튼을 구현을 해야 해서 다시 Modally 방식으로 변경을 생각하고 있는데
* 저희는 가로 화면 고정과 버튼 생성을 기준으로 방식을 나눠 사용했지만, 실제 사용할 때는 어떤 기준으로 방식을 선택하는 게 좋을지 궁금합니다!

## 3. 고차함수
FruitStore에서 과일의 재고를 [Fruit: UInt] 형태의 딕셔너리로 관리했었는데요,
처음에는 guard문을 활용하여 Optional binding에 실패했을 때 throw notExistFruit로 예외처리를 했습니다. 하지만, 실제로는 발생할 일이 없는 에러라서 조금 불필요하다고 느껴서 고차함수인 filter로 변경했어요.

### filter
* 장점: 불필요한 Error를 만들지 않아도 됨
* 단점: 시간복잡도 O(과일의 개수)

### guard문
* 장점: 시간복잡도 O(1)
* 단점: Optional 처리를 위해 불필요한 Error를 만들어 던져줘야함

과일의 개수가 많지 않은 점. 불필요한 Error를 위해 처리해주지 않고, 코드를 조금 더 깔끔하게 작성할 수 있는 점. 때문에 filter를 사용했는데요.
guard문이 더 좋을지. 아니면 더 좋은 방법이 있는지. 코리의 의견을 듣고 싶습니다 🐶

2023-01-10 15:06 UTC, corykim0829 requested changes
수고 많으셨습니다 👏👏👏👏

> 1. IBOutlet Collection

➡️ 이 부분은 코드 내 커멘트에 적어두었으니 확인해주세요! 😊

> 2. Modally vs Show

➡️ 아무래도 닫기 버튼이 있어서 UX를 고려했을 때에는 Modally가 더 자연스럽게 느껴지는 것 같아요.
하지만 크게 상관없으니 두개 다 해봐서 차이점을 알아보는 것도 좋을 것 같네요 😊
+스토리보드를 확인하니까 NavigationController가 두개가 보이던데, 스토리보드 하나로만 처리해주세요!

> 3. 고차함수
➡️ 여기도 코드 내 커멘트에 피드백 남겨드렸습니다!

두분 모두 잘하고 계십니다!! 👏👏👏 
같이 코드를 더 개선해봅시다 💪

2023-01-11 07:08 UTC, iYeahh commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    init(defaultStock: UInt = 10) {
defaultStock -> stock 파라미터명 변경했어요!

2023-01-11 07:11 UTC, iYeahh commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +            let fruitStock = juiceMaker.fruitStore.stock(byFruit: fruit)
제시해주신 의견 덕분에 JuiceMakerViewController가 juiceMaker 와 fruitStore을 가지는 방법을 고민해볼 수 있었어요 :)
해당 부분 수정하였어요!

2023-01-11 07:13 UTC, iYeahh commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        makeJuiceAlert(juiceName: juice.rawValue)
rawValue 사용이 잦았는데 가독성이 떨어진다면 앞으로 코드를 구현할 땐 주의해야겠어요..!
enum에 property를 추가해 수정하였습니다!

2023-01-11 07:13 UTC, zhunhe commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func hasEnoughStock(countByFruit: [Fruit: UInt]) -> Bool {
리뷰주신 내용 반영하여 수정했습니다 ! 확실히 `$0.key`나 `$0.value` 보다 가독성이 좋아진거 같아요 ☺️ 

```swift
// BEFORE
return stockByFruit.filter { $0.key == fruit }[0].value

// AFTER
return stockByFruit.filter { (fruit, _) in
    fruit == byFruit
}[0].value
```

`[0].value` 부분도 수정할 수 있는 방법이 있다면 좋을 것 같은데 좋은 방법이 떠오르지 않아요 🥲

2023-01-11 07:27 UTC, zhunhe commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        }
리뷰주신 내용 반영하여 수정 진행했습니다 ! ☺️
```swift
override func viewDidLoad() {
    super.viewDidLoad()
// BEFORE
    for stockLabel in stockLabels {
        stockLabel.text = String(10)
    }
// AFTER
    updateStockLabel()
}
// AFTER
func updateStockLabel() {
    for (stockLabel, stock) in zip(stockLabels, fruitStore.stockByFruit.values) {
        stockLabel.text = String(stock)
    }
}
```

2023-01-11 07:29 UTC, zhunhe commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    func makeJuiceAlert(juiceName: String) {
`alert`으로 시작하도록 메소드명 변경했습니다 !

```swift
makeJuiceAlert() -> alertJuiceReady()
outOfStockAlert() -> alertOutOfStock()
```

2023-01-11 07:31 UTC, iYeahh commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +            stockLabels[fruit.rawValue].text = String(fruitStock)
그렇군요.... 가독성 개선을 위해 enum Fruit의 rawValue 대신 sequence 속성을 추가하는 정도로 수정했습니다!

IBOutlet Label을 5개 각각 따로 생성하는 것보다 IBOutlet Collection을 사용하는 것이 코드가 더 깔끔할 거라고 생각했는데,
그럼 차라리 따로 생성하는 게 유지/보수에는 더 나았을까 궁금합니다 🤔

2023-01-11 08:03 UTC, iYeahh commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        guard let buttonName = sender.currentTitle else {
저희가 상수화 하는 방법에 대해 아래 두가지 고민을 해보았는데,
1. 각 버튼을 IBOutlet Button 속성으로 선언하고 setTitle로 버튼명을 지정하는 방법 -> 상수화는 아님
2. order Button을 7개로 각각 만드는 방법 

두가지 모두 적합한 방법은 아닌 것 같아요...!
애초에 버튼의 이름을 가지고 구현하는 방법이 옳지 않았을 지도 모른다는 생각이 들기도 하네요 🫥

2023-01-11 15:16 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +            stockLabels[fruit.rawValue].text = String(fruitStock)
당장 보기에는 깔끔할 수 도 있지만, 그렇게 되면 스토리보드에 넣은 순서대로 index가 고정되기 때문에 유지/보수에 좋지 않죠.
만약 여기서 과일들 순서가 바뀐다면 어떻게 될까를 고민해보면 좋을 것 같아요 😊

2023-01-11 15:25 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        guard let buttonName = sender.currentTitle else {
위에 고민과 비슷하다고 생각이 드네요!
만약 버튼의 이름이 바뀐다면 어떻게 될까요?

저는 2번도 나쁘지 않다고 생각해요!

2023-01-11 15:25 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        }
여러 label들을 업데이트 하니 updateStockLabels가 조금 더 매끄러울 것 같아요 😊

2023-01-11 15:41 UTC, corykim0829 requested changes
수고 많으셨습니다!!! 🙏

이제보니 메소드들 접근제한자가 대부분 따로 선언되어있지 않네요!
메소드들 접근제한자는 우선적으로 private을 고려하는게 좋은데 이 이유도 고민해보면 좋을 것 같아요!

그리고 피드백 반영했을 때 시간이 너무 오래걸릴 것 같으면 저에게 DM 주세요!!

조금만 더 개선해봅시다!! 💪

2023-01-11 15:41 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +    var juiceName: String {
이미 Juice 라는 말이 여기 enum 객체명이기 때문에 juiceName은 중복 되는 것 같아요! 그냥 name으로 하면 깔끔할 것 같아요 😊

2023-01-11 15:41 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        }[0].value
이제보니 여기서 filter를 사용하면 가독성이 너무 떨어지고, 불필요한 느낌이 드네요! 개선해봐요 😊

2023-01-12 04:57 UTC, iYeahh commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        }[0].value
가독성을 높이기 위해 filter 대신 Nil-Coalescing로 수정해 보았어요 👍🏻

2023-01-12 04:58 UTC, iYeahh commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +    var juiceName: String {
메소드들의 접근제한자 선언하였고, juiceName -> name으로 변경하였어요 😀

2023-01-12 05:29 UTC, corykim0829 approved these changes
수고 많으셨습니다!!

피드백은 다음 스텝 진행하시면서 반영해주세요! 🔥

2023-01-12 05:29 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func stock(byFruit: Fruit) -> UInt {
파라미터를 다음과 같이 바꾸면 깔끔할 것 같아요 😊

```suggestion
    func stock(byFruit fruit: Fruit) -> UInt {
```

2023-01-12 05:29 UTC, merged