쥬스메이커 [STEP 2] Jojo, is
tasty-code/ios-juice-maker pull request #32
Opened 2023-01-10 05:39 UTC by vanism2091

안녕하세요 소대! @zdodev

PR 마감시간을 지키려고 했는데 늦어버렸네요🥲\
STEP1에서 상세한 PR감사드립니다.\
공부해 볼 부분도 알 수 있었고 놓친 부분에 대해서도 다시 한 번 공부하는 계기가 되었습니다.\
STEP2부터는 스토리보드 기능이 추가되었어요! is랑 jojo 둘다 스토리보드가 익숙하지 않아서 어려웠지만 열심히 구현해봤습니다!

## ‼️ 요구 사항 및 구현 사항

### 🙋‍♂️ 각 객체 별 책임
| Name | Type | 책임 |
| -- | -- | -- |
| JuiceMakerViewController | ViewController | Juice주문 및 Fruit 재고 현황을 보여주는 화면 |
| StoreViewController| ViewController | Fruit 재고를 수정할 수 있는 화면

🍎 JuiceMakerViewController
- **과일 재고현황**\
  각 과일별 재고 Label을 IBOutlet으로 연결
  ```swift
      @IBOutlet private weak var strawberryStock: UILabel!
      // ...
  ```
  Label과 FruitStore를 연결하기 위해 fruitLabelFruitMap 딕셔너리를 만들어 2개를 매칭   
  ```swift
    fruitLabelFruitMap = [
              strawberryStock: .strawberry,
              // ...
          ]
  ```
  `updateStockValue` 함수를 통해 과일별 재고현황을 업데이트
- **재고관리 `Button`**\
  재고 관리 화면으로 넘어가기 위해 @IBAction을 통해 코드에 `button` 연결
  ```swift
  @IBAction func ModifyStockButtonTapped(_ sender: UIBarButtonItem)
  ```
  코드로 스토리보드 네비게이션 객체를 생성하여 화면 이동
  ```swift
  guard let storeNaviVC = storyboard?.instantiateViewController(withIdentifier: "storeNavi") as? UINavigationController else { return }
  ```
  Modal 방식을 통한 화면전달
   ```swift
  present(storeNaviVC, animated: true)
  ```
- **쥬스 주문 버튼**\
`orderButtonTapped` 함수 한 곳으로 모든 juice 버튼의 입력을 받아온다.
juice 버튼 title에 각 juice 명칭이 들어가 있음으로 정제하여 각 juice에 매칭
  ```swift
  @IBAction func orderButtonTapped(_ sender: UIButton) {
    let orderName = sender.currentTitle
    let juiceName = orderName?.replacingOccurrences(of: " 주문", with: "")
    guard let juice = Juice(rawValue: juiceName ?? "") else {
    showAlert(message: "팔 수 없습니다.")
    return
  }
  ```
  juice가 생성된다면 성공 alert을 띄우고 생성되지 않는다면 실패 alert 띄운다.
  ```swift
  do {
    try juiceMaker.make(juice: juice)
    showAlert(message: "\(juice.rawValue) 나왔습니다! 맛있게 드세요!")
  } catch is JuiceMakerError {
    showFailAlert()
  }
  ```
- **Alert 구현**\
`UIAlertController`를 통해 alert 틀 생성
  ```swift
  let failAlert = UIAlertController(title: nil, message: "재고가 모자라요. 재고를 수정할까요?", preferredStyle: .alert)
  ```
  `UIAlertAction`을 통해 액션 생성
  ```swift
  let confirmAction = UIAlertAction(title: "예", style: .default, handler: { _ in self.showStoreView() })
  ```
  Alert에 액션 추가하기
  ```swift
  failAlert.addAction(confirmAction)
  ```
  `shwoAlert` 함수를 통해 성공 및 오류의 메세지만 수정하도록 활용성 확장
  ```swift
  private func showAlert(message: String) {
        let alert = UIAlertController(title: nil, message: message, preferredStyle: .alert)
  ```
📦 StoreViewController
  - 전 화면으로 돌아가기
    `UIBarButtonItem`을 코드에 연결하여 `dismiss` 실행
    ```swift
    @IBAction func backButtonTapped(_ sender: UIBarButtonItem) {
         dismiss(animated: true)
     }
    ```

## 구현예시
### 1. 재고 수정 버튼 터치
![재고 수정 버튼 터치](https://user-images.githubusercontent.com/107622687/211467156-7afd2653-6708-405e-b90a-024a10925ffc.gif)

### 2. 쥬스 주문(성공) - 망키쥬스 선택
![쥬스 주문(성공)](https://user-images.githubusercontent.com/107622687/211467179-12ba9798-4bfa-43dd-a53d-d504131692b6.gif)\
망고, 키위 재고 감소

### 3. 쥬스 주문(실패) - 딸기쥬스 주문
![쥬스 주문(실패)](https://user-images.githubusercontent.com/107622687/211466925-69ea66f9-b3d6-4268-ae70-1ec0ccd6267b.gif)\
딸기재고 부족으로 실패 alert 표시

## 🔫 Trouble Shooting

### 🧭 2개의 Navigation Controller

`JuiceMakerView`에서 `StoreView`로 modal 방식으로 화면 전환을 구현하면서\
StoreView에 적용한 navigation이 보이지 않는 문제가 있었어요.

push 방식으로 화면을 전환하면 JuiceMakerView에서 쓰던 navigation bar를 사용할 수 있는데,

- modal 형식으로 화면을 전환하고 싶었고
- 새 StoreView에서 버튼 UIComponent를 만들기 보다는 네비게이션으로 뒤로가기를 구현해보고 싶었어요.

공부해보니 새로운 네비게이션을 보이게 하려면 목표 View가 아니라 해당 View의 **navigation으로 화면을 전환**해야 하더라고요. 이걸 깨달은 이후에야 `main.storyboard`에서 처음 화살표가 navigation에 있는게 보였어요!

## 고민한 부분 + Optional(해결)

### 1️⃣ JuiceMakerVC 내 많은 IOBOutlet UILabel들

**고민** 과일 재고(5개)의 IBOutlet label을 관리하는 방법 중

1. 하나의 label을 하나의 IBOutlet 변수에 binding하는 방식
   - Label과 Fruit을 연결하기 위해 Dictionary를 추가적으로 생성해야 했어요.
2. IBOutlet Collection을 이용해 array에서 한 꺼번에 관리하는 방식

중 고민했어요.

**해결** 현재 구현한 방식은 1번 방식이예요.

한꺼번에 관리하는게 좋을 것 같아서 일반적으로 2번 방식을 선호하는 편임에도 불구하고 **1번 방식으로 구현한 이유**는 다음과 같아요.

- 찾아봤을 때, IBOutlet collection을 사용한 예시는 array내 모든 outlet을 돌면서 한 꺼번에 속성을 적용하는 경우가 많았어요.
  - 그런데 우리는 특정 label만 선택해서 text를 업데이트 하고 싶었어요.
- outlet의 index를 명시적으로 설정하는 방법을 찾지 못했어요
  - collection에 들어가는 outlet의 index는 collection에 넣은 순서대로 되는 것 같았어요.
  - 이를 명시적으로 설정할 수 없으면 이를 명시하기 위한 추가적인 문서가 필요해요(그럴 일은 없겠지만, 추후 협업을 고려했을 때)
- array의 out of index 에러를 고려해야해요.

이와 같은 이유로 1번 방식으로 구현했어요.

❓ 지금의 방식보다 더 가독성이 좋고 편한 방식이 있는지 궁금해요!\
❓ 시간이 부족해 IBOutlet Collections에 대한 공부가 부족한 상태로 판단했는데, 위 처럼 판단한 게 맞는지 궁금합니다!

### 2️⃣ 화면 전환 방식, push vs modal

**고민**
두 가지 화면 전환 방식 중 무엇을 선택할지 고민했어요.

- modal
  - 재고 수정이 무관한 흐름이라고 판단했어요

- push: 
  - 쥬스를 만드는 화면에 재고가 표시되고 해당 재고를 수정하는 것이기 때문에 유관한 흐름이라고 판단하였습니다.

**해결** 현재 구현한 방식은 modal이예요.

각자 의견이 다른 와중에, 프로젝트 핵심 경험에 modality 활용이 있어서 modal로 선택했습니다 :)

### 3️⃣ 알림창, actionsheet vs alert

**고민** 알림창의 Style을 고민했어요.

**해결** 둘 다 alert 스타일로 구현했어요.

- **재고 수정** 알림창은 결정이 필요한 중요 정보라고 생각해서 alert 형태로 구현했어요
- 쥬스를 성공적으로 만든 후 알림 창은 이후 특별한 액션을 실행하기 보다는 단순한 알림이므로 alert 형태로 구현했어요

### 4️⃣ 화면 전환 구현 방식

**고민** 다양한 화면 전환 구현 방식 중 어떤 방식으로 전환할 지 고민했어요.

1. 직접 segueway
2. 간접 segueway
3. 코드로 스토리보드 네비게이션 객체를 생성하여 화면 이동
4. 코드로 스토리보드 생성 및 객체 연결

**해결** 우리가 적용한 화면 전환 방식은 3번이예요.

재고 수정 화면으로 전환되는 trigger가 2개이기에

1. 재고 수정 버튼,
2. 재고 부족시 발생하는 alert의 `예` 버튼)

storyboard에서 세그웨이를 통해 전환하기 보다는 화면을 전환하는 함수를 만들어 활용했어요

### 5️⃣ 코드 상 일어나지 않을 에러를 처리해야 하는가?
**고민**
```swift
@IBAction func orderButtonTapped(_ sender: UIButton) {
    // ...
    guard let juice = Juice(rawValue: juiceName ?? "") else {
        // 1
        showAlert(message: "팔 수 없습니다.")
        return
    }

    do {
        // ...
    } catch is JuiceMakerError {
        // ...
    } catch {
        // 2
        showAlert(message: "\(error)")
    }
}
```

1. juice가 nil이 되는 경우
2. `JuiceMakerError`가 아니라 다른 error가 발생하는 경우

1은 현재 코드상에서는 화면 내 모든 버튼이 VC에 등록되어 있기 때문에 발생하지 않아요. 옵셔널 바인딩을 위해 guard let을 사용한 뒤에 
1. return만 할지 
2. print만 할지(로그 창에 찍힘), 
3. 사용자에게 alert를 보여줘야할 지

고민했어요.
마찬가지로 2번 상황 역시, 어떤 error가 발생할 지 모르므로 위의 세 구현 중 고민했어요. 

**해결** 두 경우 모두 3번 방식으로 구현했어요.

사용자가 버튼을 눌렀을 때 응답이 없는 경우가 생길 수 있고, 이 경우 ux적으로 좋지 않을 것 같아서요.

❓ 이런 경우 소대는 어떤 방식으로 이를 해결하는 편인지,\
❓ 그리고 이러한 상황을 어떻게 해결하면 좋을지, \
❓ 아니면 이는 생각하지 않아도 되는 문제인지 궁금해요!

2023-01-11 12:53 UTC, zdodev requested changes
안녕하세요 @vanism2091 , @CODEMASTERJO !

Step 2 구현 잘 진행해주셨습니다!
PR 내용을 잘 작성해주셔서 어떤 내용을 고민하고,
어떤 생각으로 구현했는지 이해하기가 훨씬 수월했습니다!👍

먼저 질문에 대한 제 생각을 적어보았습니다.

**1. JuiceMakerVC 내 많은 IOBOutlet UILabel들**

 같은 역할(재고 수량 표시)을 하는 여러 UILabel 을 하나로 관리하고 싶은 생각은 저도 크게 공감합니다!
 개별 IBOutlet으로 관리할 것인지, Collection 으로 관리할 지에 대해서 말씀해주신 두 방법 모두 장단점이 있다고 생각합니다.
 두 방법 다 고민해보면서 서로 간의 트레이드오프를 잘 느끼신 것 같습니다! 적어주신 판단 내용도 적절한 판단 내용이라고 생각합니다!
 지금 같은 경우도 충분히 좋은 방법입니다!
 
 **2. 코드 상 일어나지 않을 에러를 처리해야 하는가?**

 먼저 juice 타입이 옵셔널이므로 `juice가 nil이 되는 경우` 가 발생하지 않는다고 생각하는 것은 위험할 것 같습니다!
 만약 버튼의 주스 이름이 바뀐다면? Juice 타입의 rawValue 값들이 바뀐다면? 예상치 못한 에러가 발생할 수 있을 것 같습니다!
 옵셔널 타입은 `값이 없을 수 있다` 라는 의미의 타입으로 항상 방어로직을 구현하는 것이 좋습니다!
 
 다음으로 에러가 발생했을 때 처리는 정말 중요하게 생각합니다!
 저는 보통 사용자에게 안전하고, UX를 헤치지 않는 방향을 선호합니다.
 발생한 에러에 따라 다르지만, 지금같은 경우 에러 사유를 사용자에게 알림창으로 알려주는 것이 좋은 방안이라고 생각합니다.👍(그렇게 생각하신 이유도 좋습니다!)

몇 가지 궁금증을 남겨보았습니다!
궁금증에 대해 코멘트를 남겨주셔도 좋습니다!

2023-01-11 12:53 UTC, zdodev commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    @IBOutlet private weak var mangoStock: UILabel!
`Stock` 으로 끝나기 때문에 UI 요소가 아닌 재고 수량에 관한 프로퍼티로 생각할 수 있을 것 같습니다.
저는 보통 UI 프로퍼티는 `...Label`, `...Button` 같은 이름을 사용하고는 합니다!
의견이 궁금합니다!

2023-01-11 12:53 UTC, zdodev commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    private var fruitLabelFruitMap: [UILabel: Fruit]!
`!` 를 사용한 이유가 궁금합니다!

2023-01-11 12:53 UTC, zdodev commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    @IBAction func ModifyStockButtonTapped(_ sender: UIBarButtonItem) {
메소드 이름에 `Tapped` 라는 행위를 먼저 작성하는 것은 어떨까요?
다른 `@IBAction` 메서드도 확인해보면 좋을 것 같습니다!

2023-01-11 12:53 UTC, zdodev commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        }
다음 로직은 별도의 메서드로 분리해도 좋을 것 같습니다!

2023-01-11 12:53 UTC, zdodev commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    private func showStoreView() {
화면 전환하는 로직을 별도의 메서드로 구현해보셨네요.👍

2023-01-11 12:53 UTC, zdodev commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        guard let storeNaviVC = storyboard?.instantiateViewController(withIdentifier: "storeNavi") as? UINavigationController else { return }
`UINavigationController` 로 타입 캐스팅한 이유가 궁금합니다!

2023-01-11 12:53 UTC, zdodev commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    private func showAlert(message: String) {
어떤 `Alert` 인지 조금 더 구체적으로 이름을 지어줘볼 수 있을까요?

2023-01-11 12:53 UTC, zdodev commented on JuiceMaker/JuiceMaker/Controller/StoreViewController.swift
> +    @IBAction func backButtonTapped(_ sender: UIBarButtonItem) {
메소드 이름에 `Tapped` 라는 행위를 먼저 작성하는 것은 어떨까요?

2023-01-12 06:29 UTC, vanism2091 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        guard let storeNaviVC = storyboard?.instantiateViewController(withIdentifier: "storeNavi") as? UINavigationController else { return }
- Step2에서는 사용하지 않았지만, Step3에서 Navigation의 자식(?)에게 데이터를 전달하기 위해 Navigation의 viewControllers 속성에 접근해야 했어요! 이를 위해 NavigationViewController로 타입 캐스팅했습니다.
- Step2의 PR을 보내기 전, Step3의 요구 사항을 확인했고, 모달 방식으로 다음 view인 Navigation의 자식 view에 어떻게 데이터를 전달할 수 있을 지 고민했어요. 이 방법을 알아내지 못하면 모달 방식을 포기하고 push 방식으로 바꾸려고 했거든요.
- 타입 캐스팅은 이러한 고민과 해결 과정에서 작성된 코드이고 Step2 PR 시 전달하는 부분은 지워지면서 해당 타입 캐스팅만 남았습니다!

2023-01-12 06:30 UTC, vanism2091 commented on JuiceMaker/JuiceMaker/Controller/StoreViewController.swift
> +    @IBAction func backButtonTapped(_ sender: UIBarButtonItem) {
다른 IBAction의 네이밍을 고려해 다음 스텝에서 반영하겠습니다!

2023-01-12 06:30 UTC, vanism2091 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    @IBAction func ModifyStockButtonTapped(_ sender: UIBarButtonItem) {
다른 IBAction의 네이밍을 고려해 다음 스텝에서 반영하겠습니다!

2023-01-12 06:31 UTC, CODEMASTERJO commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    private var fruitLabelFruitMap: [UILabel: Fruit]!
- 여러 method에서 데이터를 참조하기 위해서는 특정 method의 지역변수가 아니라 class의 프로퍼티로 정의해야 합니다.
- 하나의 class가 instance로 initialize 되기 전에 모든 property가 초기화되어야 합니다.
- IBOutlet은 view load되는 시점에 초기화할 수 있습니다.
- 따라서 클래스 내 프로퍼티 중 IBOutlet은 옵셔널 타입일 수 밖에 없습니다.
- 옵셔널 타입 변수는 ?와 !로 선언할 수 있고, !는 참조하거나 사용할 때 자동으로 언래핑되어 value를 그대로 사용할 수 있는 반면, nil인 변수를 사용할 시 crash가 발생한다.
- 그런데 뷰 라이프사이클 상…ViewLoad에서 IBOutlet가 정의되기 때문에 우리가 해당 변수를 사용하는 ViewDidLoad에서는 IBOutlet 변수들이 nil이 아님을 보장할 수 있어요 🙂
- fruitLabelFruitMap **`!`** 사용 이유
    - fruitLabelFruitMap 도 마찬가지 이유로 추후 사용시 nil이 아님을 보장할 수 있다고 생각해서 !로 선언했습니다.
    - 하지만 찬찬히 fruitLabelFruitMap의 경우 IBOutlet이 아닌 일반 변수이면서 var이기 때문에 완벽하게 보장을 할 수 없는 것 같아요.
    - 10일 후의 내가 런타임 중에 map을 nil로 초기화하는 코드를 작성할 수도 있으니까요....🙂
    - 이후 해당 dictionary를 사용하지 않는 방법으로 구현을 변경해서 !는 사라졌습니다.

2023-01-12 06:31 UTC, vanism2091 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    @IBOutlet private weak var mangoStock: UILabel!
소대의 네이밍이 더 직관적인 것 같아요! 다음 스텝에서 반영하겠습니다 :)

2023-01-12 06:32 UTC, vanism2091 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        }
다음 스텝에서 반영하겠습니다!

2023-01-12 06:32 UTC, CODEMASTERJO commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    @IBOutlet private weak var mangoStock: UILabel!
`Label`, `Button` 등을 명시해두어야 프로퍼티를 사용할때 코드를 작성한 사람도, 코드를 보는 사람도 한눈에 확인할 수 있을거 같아요!
동의합니다!

2023-01-12 06:32 UTC, vanism2091 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    private func showAlert(message: String) {
message를 받은 대로 보여주는 Alert라 네이밍이 고민이되긴 했는데, 조조와 의논해본 후 다음 스탭에서 반영하겠습니다!

2023-01-13 13:23 UTC, zdodev approved these changes
안녕하세요! @vanism2091 , @CODEMASTERJO !

코멘트 확인하였습니다. 
좋은 의견 달아주셨다고 생각합니다.👍

Step 2 진행하시느라 고생하셨습니다!🎉

2023-01-13 13:23 UTC, merged