쥬스메이커 [STEP 2] Toughie, d.o.
tasty-code/ios-juice-maker pull request #33
Opened 2023-01-10 07:09 UTC by Toughie17

안녕하세요 븨븨~! Toughie, d.o. 입니다 :)
저번 STEP1의 상세한 코멘트 다시 한 번 감사드려요. ☺️

이번 STEP2에서는 STEP1에서 구현한 모델을 뷰와 연결시키는 작업이 대부분이었어요! (뷰컨트롤러 코드 작성)
스토리보드를 통해 앱을 만든 경험이 많지 않아 구글링도 정말 많이 했어요 😂

크게 모델에서의 변경점, 뷰컨트롤러에서의 변경점으로 나눠서 설명 드리고자 합니다.

# STEP 2 구현

## 모델 변경 사항
- FruitStore.swift 내 numberOf 함수 (과일의 개수 리턴) 수정
    - 딕셔너리의 value가 Optional UInt이기에 바인딩 처리를 위해 guard let 구문 활용
    다만 else 구문 처리에서 UInt 타입을 반환해야 하기 때문에 임의의 값 9999등이 들어갔었음
    -> 에러를 던지도록 바꿔보자.
```swift
// 기존코드

func numberOf(fruit: Fruit) -> UInt {
    guard let currentStock = fruitStock[fruit] else { return 9999 }
    return currentStock
}

->
// 변경 후
// fruitStock[fruit]이 nil인 경우 InfoMessage.noFruit을 던짐
func numberOf(fruit: Fruit) throws -> UInt {
    guard let currentStock = fruitStock[fruit] else {
        throw InfoMessage.noFruit
    }
    return currentStock
}
```

이를 위해 InfoMessage enum도 코드 개선 진행

- LocalizedError 프로토콜 준수
    - 오류에 대한 발생 이유를 설명하는 오류 프로토콜
    - 해당 프로토콜을 준수하고, computed property var errorDescription: String? 을 정의하면 아래와 같이 활용 가능 (ViewController에서 활용)

```swift
import Foundation

enum InfoMessage: LocalizedError {
    case noStock
    case noFruit

    var errorDescription: String? {
        switch self {
        case .noStock:
            return "재고가 부족합니다"
        case .noFruit:
            return "등록된 과일이 없습니다"
        }
    }
}
```
## 뷰컨트롤러 변경 사항(구현)
- 쥬스 주문 버튼 변수 생성
- JuiceMaker 인스턴스 생성
- viewDidLoad 함수 내에 setup함수 실행
    - setup함수 : 현재 재고 레이블을 리프레시 해주는 함수 실행 (refreshCurrentStokLabel)

```swift
// numberOf가 throws 함수이기에 do-try-catch로 처리
func refreshCurrentStockLabel() {
        do {
            strawberryCurrentStock.text = String(try juiceMaker.fruitStore.numberOf(fruit: .strawberry))
            bananaCurrentStock.text = String(try juiceMaker.fruitStore.numberOf(fruit: .banana))
            pineappleCurrentStock.text = String(try juiceMaker.fruitStore.numberOf(fruit: .pineapple))
            kiwiCurrentStock.text = String(try juiceMaker.fruitStore.numberOf(fruit: .kiwi))
            mangoCurrentStock.text = String(try juiceMaker.fruitStore.numberOf(fruit: .mango))
        } catch {
            print(error.localizedDescription)
        }
    }
   ```
- 재고수정 버튼 탭 → 재고 추가 뷰로 화면전환 (push - pop 방식)
- STEP 3에서 present 방식으로 해 볼 예정(present - dismiss방식)
```swift
func moveToChangeStockView() {
        guard let viewController = self.storyboard?.instantiateViewController(identifier: "ChangeStockViewController") else { return }
        self.navigationController?.pushViewController(viewController, animated: true)
    }
```
- 쥬스 주문버튼 클릭시
    - 버튼의 currentTitle(Optional String)을 활용해 switch-case 처리
    - 분기처리를 위해 JuiceMaker의 make 함수를 활용한 juiceMake 함수 생성
   
```swift
func makeJuice(fruitJuice: FruitJuice) {
        do {
            try juiceMaker.make(juiceName: fruitJuice)
        } catch {
            let failAlert = UIAlertController(title: "재료 부족",
                                              message: "재료가 모자라요. 재고를 수정할까요?",
                                              preferredStyle: UIAlertController.Style.alert)
            
            failAlert.addAction(UIAlertAction(title: "예",
                                              style: UIAlertAction.Style.default,
                                              handler: { _ in
                self.moveToChangeStockView()
            }))
            
            failAlert.addAction(UIAlertAction(title: "아니오",
                                              style: UIAlertAction.Style.default,
                                              handler: {(_: UIAlertAction!) in }))
            
            self.present(failAlert, animated: true, completion: nil)
        }
        
        let successAlert = UIAlertController(title: "쥬스 완성!",
                                             message: "\(fruitJuice.rawValue) 나왔습니다! 맛있게 드세요!",
                                             preferredStyle: UIAlertController.Style.alert)
        
        self.present(successAlert, animated: true)
        
        DispatchQueue.main.asyncAfter(deadline: .now() + 1.0) {
            successAlert.dismiss(animated: true)
        }
        
        refreshCurrentStockLabel()
    }
```

- 재고가 있는 경우 : ** 쥬스 나왔습니다. Alert 표시
    - 자동으로 Alert가 사라지도록 DispatchQueue 활용
    - 데이터와 뷰의 싱크를 맞추기 위해 리프레시 함수 실행

- 재고가 없는 경우 : 재료가 모자라요. 재고를 수정할까요? 출력 후 (예/ 아니오) 선택
    **예** → 재고수정 화면으로 이동 (moveToChangeStockView 함수 실행)

```swift
func moveToChangeStockView() {
        guard let viewController = self.storyboard?.instantiateViewController(identifier: "ChangeStockViewController") else { return }
        self.navigationController?.pushViewController(viewController, animated: true)
    }
```

아니오 → Alert 사라짐 

구현 사항, 네이밍, 코드 등 부족한 부분이 있다면 가감없이 말씀해 주세요 !
오늘도 행복한 하루 보내세요 븨븨 😎🤞

2023-01-11 03:36 UTC, YebinKim requested changes
디오, 터피 안녕하세요~
Step2 진행까지 고생 많으셨습니다! 🥳

따로 질문해주신 내용은 없어서 라인별 코멘트만 달아두었으니 확인 부탁드려요~
p2 코멘트가 있어서 Request Changes 로 요청드렸습니다 ☺️

혹시 리뷰 코멘트 중 궁금한 점이 있거나 언급되지 않은 부분에서도 궁금한 게 있다면 편히 질문 주세요 😆🙌

---

그리고 커밋 로그를 봤을 때 한 분이 커밋을 주로 진행했고 코드 스타일 또한 지난번 스텝과는 다소 달라진 것으로 보이는데 혹시 페어 프로그래밍을 진행하는데 어려움이 있으실까요??

2023-01-11 03:36 UTC, YebinKim commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +            print(error.localizedDescription)
p2;

현재 6개의 과일 중 단 하나라도 존재하지 않으면 모든 문구가 업데이트 되지 않고, 사용자는 이 에러가 무슨 상황인지에 대해 알지 못 할 것으로 보여요 🤔 (에러 처리가 print 로그만 출력하기 때문에)
즉, 해당 메서드는 현재 **문구 업데이트의 책임**과 **재고 확인의 책임** 두 가지를 가지고 있는 것으로 보이는데 메서드의 책임을 나눠주면 어떨까요??

2023-01-11 07:19 UTC, Toughie17 commented on JuiceMaker/JuiceMaker/Controller/AppDelegate.swift
> +        // Called when the user discards a scene session.#imageLiteral(resourceName: "스크린샷 2023-01-10 오전 10.55.21.png")
앗 이 부분은 저희도 잘 모르겠어요.. AppDelegate 파일은 따로 건들지를 않아서요!
다만 AppDelegate와 SceneDelegate에 대해서 찾아봤어요! (아직 개념을 잘 몰라서요)

iOS 12 까지는 하나의 앱에 하나의 window 구성이었으나(이 부분이 정확히 와닿지가 않아요 window가 뭘까요..?)
iOS 13이후부터는 window의 개념이 scene으로 대체되고 하나의 앱에서 여러개의 scene을 가지고 있다고 합니다. 

[SceneDelegate]
Scene은 앱의 사용자 인터페이스 및 컨텐츠의 배경으로 사용되며, UI의 하나의 인스턴스를 나타내는 window와 ViewController가 들어있습니다. 결과적으로 하나의 앱은 여러 Scene과 SceneDelegate 객체를 동시 활성화 가능합니다. -> Split View를 통해 다중 창 앱 빌드 가능 !

[AppDelegate]
이제는 AppDelegate가 앱의 생명주기 이벤트를 관리하지 않는다고 합니다.

[요약]
iOS13이상부터는 유저가 앱 UI의 여러 인스턴스를 동시에 만들고 관리 가능하며 App Switcher를 통해 전환 가능.
AppDeleagte는 Process LifeCycle과 Session LifeCycle을 관리하며
SceneDelegate는 UI LifeCycle을 관리한다.


아직 생명주기에 대해 깊게 공부해보지 못해서 개념들이 어렵네요..

다만 븨븨가 말씀해 주신 것처럼
이미지리터럴을 활용한다면 저렇게 "스크린샷.png"이 아닌, 
어떠한 이미지인지 유추 가능하게 이름을 저장해서 사용하는것이 좋다고 생각합니다 !

2023-01-11 07:41 UTC, Toughie17 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    func setup() {
private 걸어줬습니다 👍🏻

2023-01-11 07:43 UTC, doshkor commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        DispatchQueue.main.asyncAfter(deadline: .now() + 1.0) {
쥬스제조 성공시 유저에게 답변을 받는 것이 아니고 단순히 알림을 주는 것이기 때문에 addAction 을 따로 추가하지 않고 1초 후 dismiss 하게 하였습니다. (1초를 기다리지 않으면 내용을 읽기 전에 사라지더라구요🙄)

2023-01-11 07:44 UTC, Toughie17 commented on JuiceMaker/JuiceMaker/Model/InfoMessageError.swift
> +
한 줄만 띄우는 것이 좋아 보입니다! (수정완료)

2023-01-11 07:59 UTC, Toughie17 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    func makeJuice(fruitJuice: FruitJuice) {
수정 완료! (다시 확인 부탁드려요)

2023-01-11 08:00 UTC, Toughie17 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func numberOf(fruit: Fruit) throws -> UInt {
수정 완료!

2023-01-11 08:11 UTC, Toughie17 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +            let failAlert = UIAlertController(title: "재료 부족",
공감합니다! 
따라서 주문성공시 알럿, 주문실패시 알럿코드를 함수화 시켰습니다.
또한 함수 이름도 order로 변경해 더욱 직관적이게 바꿔봤습니다.

1. 과일쥬스를 인자로 주문을 한다.
2. 쥬스메이커에서 제조를 시도한다.
3.  에러 발생 시 실패 알럿을 띄운다.
4. 제조에 성공하면 성공알럿을 띄운다.
5. 현재 재고 레이블을 리프레시 해준다.

2023-01-12 07:06 UTC, Toughie17 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +            print(error.localizedDescription)
해당 커멘트에 대해 디오와 함께 정말 많이 고민해 보았는데요..
먼저 과일가게의 수량을 get하는 함수인 quantity에서 throws를 지우고 그냥 옵셔널 UInt 타입으로 변경했습니다.
why? 메서드를 분리하는데 do- catch 구문이 너무 발목을 잡아서요..

그래서 떠오른 아이디어가 코드에 반영되었습니다.
우선 과일 가게의 현 재고를 복사해서 가지고 있는 변수를 만들었습니다.(currentFruitStock 튜플)

과일의 재고가 변경되었을 때 실행되는 refreshLabels() 함수 안에는

과일의 재고를 확인해 튜플에 담는 checkCurrentStock 함수가 실행되고
(모든 재고가 확인되어 튜플에 잘 담기면 -> 내부에서 가드문 처리)
- 유저에게 알럿도 보내도록 수정했습니다.
- 하지만 유저는 어떠한 방식으로도 이 알럿을 보는 일이 없을거라고 생각합니다.(현재 코드상으로는)
튜플의 값을 스트링으로 바꿔 레이블을 변경해주는 changeFruitLabels 함수를 실행합니다.

즉 의도는 
1. 재고를 확인하는 함수를 따로 분리하자
2. 확인된 재고를 바탕으로 레이블을 변경하는 함수를 만들자
3. 위 절차를 순차적으로 실행하는 최종 함수를 만들자
입니다.

변수를 따로 생성하는 방식이 바람직 하지 않은듯 해서 여러가지 고민해 보았으나,
현재 과일의 재고를 관리하는 부분이 딕셔너리로 되어 있어 쉽지 않았습니다.
그래서 다른 조에서는 싱글톤을 많이 활용한 것이 아닌가.. 라는 생각도 들었습니다.

객체의 역할과 책임을 분리하는 것이 객체지향 프로그래밍을 따르는 것임을 알고는 있으나
정말 쉽지가 않네요 🥲

븨븨의 코멘트 기다리겠습니다. 감사합니다!

2023-01-12 08:43 UTC, doshkor commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +            print(error.localizedDescription)
븨븨! 추가적으로 문의가 있는데요!

과일 수량관리를 FruitStock: [Fruit: Int] 딕셔너리로 구현하다보니 
과일의 수량을 구할 때 딕셔너리의 서브스크립트를 사용하게 되요!

(ex. 망고의 수량을 확인하고 싶을 때 FuirtStock[.mango] )

딕셔너리 서브스크립트의 return 값이 옵셔널이다 보니 예외처리가 필요하고,
처음 구현시 throw 로 선언하여 do-catch 로 구현하다보니 코드가 많이 꼬이더라구요!
(서브스크립트 호출시마다 예외처리가 필요하니 코드가 길어지고 중복이 많아지는 것 같아서..?)

!!질문!!
자주 사용해야 하는 데이터인데 옵셔널 값을 return 하여 매번 옵셔널바인딩을 해야함에 불편함을 느껴서요!

매번 바인딩을 하는 것이 자연스러운 코딩일까요?

아니면 옵셔널 값을 return 하지 않는 다른 타입을 선언해서 하는 것이 좋을까요??
(예를 들어, named tuple 이나 [(String, Int)] 배열안에 튜플을 넣어 사용하는 방법을 생각해 봤습니다)

코딩에 정답은 없겠지만 븨븨님이라면 어떻게 생각하실지 궁금해서 질문 드립니다.!🥲

2023-01-12 16:55 UTC, YebinKim commented on JuiceMaker/JuiceMaker/Controller/AppDelegate.swift
> +        // Called when the user discards a scene session.#imageLiteral(resourceName: "스크린샷 2023-01-10 오전 10.55.21.png")
앗 직접 추가한 파일이 아니셨군요..!! 이미지리터럴을 활용한다면, 또는 `UIImage(name:)` 으로 이미지를 생성하든 이미지는 적절한 이미지 리소스가 적절한 이름을 가지는 게 좋을 거 같아 드린 코멘트였어요.
생명주기에 관해 말씀드리려던 것은 아니었지만😅 공부하신 내용 공유해주셔서 고마워요 ☺️

2023-01-12 17:21 UTC, YebinKim commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +
p4;

개행이 3줄인 것으로 보이네요 👀
의도된 개행이 아니라면 수정이 필요해보입니다!

2023-01-12 17:21 UTC, YebinKim commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +            self.navigationController?.pushViewController(viewController, animated: true)
p4;

탭 정렬이 맞지 않는 메서드가 있네요 👀
탭 정렬이 필요한 코드는 드래그 후 `control + i` 를 통해 일괄 정렬할 수 있습니다 😄

2023-01-12 17:21 UTC, YebinKim commented on JuiceMaker/JuiceMaker/Controller/StringConstatns.swift
> +    static let changeStockViewController = "ChangeStockViewController"
참고;

타입 이름 자체를 반환할 경우 `String(describing: self)` 를 통해서도 가능하다는 점 참고로 말씀드려요 🙌

2023-01-12 17:21 UTC, YebinKim commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +            print(error.localizedDescription)
터피, 디오 해당 코멘트에 대해 깊게 고민하느라 정말 고생 많으셨어요 🙇👍
말씀하신 것 처럼 자주 사용하는 데이터가 옵셔널 값이라면 매번 바인딩을 하는 게 불편하게 느껴질 수 있을 거 같아요.
저라면 이때 바인딩을 매번 해주는 게 불편하니 딕셔너리 값을 벗겨내는 메서드 또는 타입을 만들어서 값을 가져오도록 작성해봤을 거 같아요.

예를 들어 현재 작성하신 `checkCurrentStock()` 메서드는 재고를 확인한 후 확인한 재고의 상태를 업데이트하고 있는데요.
`checkCurrentStock(of fruit: Fruit) -> Int` 와 같이 메서드를 만들고 작성하신 `guard let` 구문의 `current~~` 를 반환하도록 만들면 **딕셔너리 값을 벗겨내는 메서드** 가 될 수 있을 거 같아요 😄

2023-01-12 17:24 UTC, YebinKim approved these changes
디오, 터피 Step2 수정까지 진행하느라 고생 많으셨어요! ☺️🙌🎉
Step2의 핵심 경험은 아래와 같았는데요.
<img width="298" alt="step2" src="https://user-images.githubusercontent.com/38066039/212136059-a26ff277-ade6-4928-9954-0401c397d888.png">

이번 스텝에서는 충분히 경험하셨고 또 고민하셨다고 생각해서 이대로 머지 진행할게요~
혹시 리뷰 코멘트 또는 궁금한 점이 있다면 언제든 DM으로 얘기해주세요 😄

Step3 진행도 화이팅입니다!! 💪🔥

2023-01-12 17:24 UTC, merged