쥬스메이커 [STEP 3] june, iyeah
tasty-code/ios-juice-maker pull request #37
Opened 2023-01-12 08:00 UTC by iYeahh

코리 안녕하세요 🐶 @corykim0829

드디어 마지막 STEP인데요,
* 보기에 간단한 코드보다 유지, 보수와 정확성을 더 중시해야 한다는 점
* naming 부분

에 대해 특히 더 깊은 고민을 할 수 있는 프로젝트였습니다!
STEP 3에서도 코리의 소중한 의견 부탁드릴게요 감사합니다 ✨

# 📃 세부사항
- [x] 화면 제목 '재고 추가' 및 '닫기' 버튼 구현
![](https://i.imgur.com/gHnl75z.png)

- [x] -, + 를 통한 재고 수정
![](https://i.imgur.com/FZFMML7.png)

- [x] 재고 수정 후 초기 화면 진입시 변경된 과일의 재고 표시
![](https://i.imgur.com/aRUdsjG.png)

# ✏️ 설명

| name                      | type        | 역할과 책임                           |
|:------------------------- | ----------- |:----------------------------------- |
| JuiceMaker                | struct      | 과일의 재고를 가지고 쥬스 제조             |
| Juice                     | enum        | 쥬스 종류, 종류에 따른 레시피             |
| FruitStore                | final class | 과일의 재고 관리                       |
| JuiceMakerError           | enum: Error | 재고 관련 Error                       |
| JuiceMakerViewController  | final class | 주문 버튼으로 주문을 받아 주스 제조, 재고 수정 |
| UpdateStockViewController | final class | 과일의 재고를 수정                      |

# 🤔 고민된 부분

## 1. `IBOutlet` vs `IBOutlet Collection`
STEP2에서는 쥬스제조 화면에서 과일 재고에 대해 IBOutlet의 배열인 IBOutlet Collection을 사용했었는데요,
* 실제 과일 재고와 재고 레이블과 직접적으로 연결하기 힘든 점
* 추후 유지보수를 생각했을 떄, tag로는 충분하지 않은 점

을 이유로 JuiceMakerViewController, UpdateJuiceViewController에서 각 재고 관련 레이블들을 IBOutlet 여러개로 연결하여 구현했고 기존에 IBOutlet Collection도 IBOutlet으로 변경했습니다.
`*쥬스 주문` 버튼은 스토리보드에 적혀있는 버튼 text에 의존적이라는 단점이 있지만 일단은 IBOutlet Collection에서 변경하지 않았습니다.
스토리보드를 사용하면서 가장 힘들었던 부분이 코드가 스토리보드에 의존적이 된다는 부분이었는데요,
이를 해결하기 위해서는 어떠한 방법들이 있는지 가이드라인이라도 주실 수 있으실까요?

## 2. 재고 추가 화면에서 닫기 버튼을 눌렀을 때, 초기 화면에 변경된 재고가 반영되지 않는 문제점
재고 추가 화면에서 닫기 버튼을 누르면 `fruitStore`에 저장되어 있는 재고가 초기 화면에 반영이 되지 않는 문제점이 발생하여
아래 방법을 통해 해결을 하긴 했는데, 혹시 더 좋은 방법이 있을까요?
```swift
override func viewWillAppear(_ animated: Bool)
```
```swift
updateStockViewController.modalPresentationStyle = .fullScreen
```

2023-01-12 11:17 UTC, corykim0829 requested changes
수고하셨습니다 👍👍👍

벌써 마지막 스텝이네요!!! 조금만 더 힘내봅시다!! 🔥

1️⃣ 코드에 self가 생략이 가능하면 되도록 생략하는게 좋습니다. Swift에서는 꼭 명시해줘야하는 경우가 있거든요! 여유가 되시면 self를 꼭 명시해야하는 부분을 정리해서 커멘트로 답해주세요! 😊

2️⃣ 현재 IBAction으로 만들어진 버튼이나 Steppter의 메소드명이 명사형으로 끝나는게 아쉽습니다.
orderButtonDidTap, orderButtonHasTouched 와 같이 액션느낌이 드는 형태로 네이밍 컨벤션을 잡아서 통일하면 좋을 것 같아요!

> 1.  IBOutlet vs IBOutlet Collection

➡️ 이번에 UpdateJuiceVC에서 IBOutlet으로 다 분리하신 부분 잘 구현하셨습니다! 👍
쥬스 주문 버튼같은 경우에도 현재는 스토리보드 의존도가 높기 때문에 모두 분리하는게 저는 좋아보입니다. 

이를 해결하기 위해서는 뷰단을 코드로 만들어서 처리해야합니다.
1. 모두 코드로 작성
2. 코드 + XIB
3. 스토리보드 + 코드
를 사용해서 의존도를 낮춰서 하나의 메소드로 여러 버튼을 처리하는 방법을 시도할 수는 있어보입니다!

> 2. 재고 추가 화면에서 닫기 버튼을 눌렀을 때, 초기 화면에 변경된 재고가 반영되지 않는 문제점

➡️ 지금 viewWillAppear에서 구현한 부분도 깔끔하게 잘 구현하셨습니다!
protocol로 신호나 데이터 전달을 하는 방법도 있습니다 :)

2023-01-12 11:17 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Controller/UpdateStockViewController.swift
> +        self.presentingViewController?.dismiss(animated: true)
그냥 dismiss 호출해도 똑같이 처리되니 참고하세요!

2023-01-12 11:17 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Controller/UpdateStockViewController.swift
> +final class UpdateStockViewController: UIViewController {
개인적으로 그냥 StockViewController라고 하면 더 깔끔할 것 같아요 😊

2023-01-12 11:17 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        guard let updateStockViewController = self.storyboard?.instantiateViewController(withIdentifier: "UpdateStockViewController") as? UpdateStockViewController else { return }
identifier는 String(describing: ) 메소드를 활용해서 클래스명으로 identifier를 처리하면 더 깔끔하고 실수를 방지할 수 있어요!

그리고 guard else - return 부분은 개행을 해주세요! 
어디서 return이 되는지는 명확하게 알아야 가독성이 더 좋습니다!

2023-01-13 04:19 UTC, iYeahh commented on JuiceMaker/JuiceMaker/Controller/UpdateStockViewController.swift
> +    var fruitStore: FruitStore!
네 앞으로 주의하도록 하겠습니다 👍🏻
Implicitly Unwrapped Optional 대신 인스턴스를 생성하는 코드로 변경해 보았어요!

2023-01-13 04:21 UTC, iYeahh commented on JuiceMaker/JuiceMaker/Controller/UpdateStockViewController.swift
> +        self.presentingViewController?.dismiss(animated: true)
불필요한 부분은 삭제하고 dismiss만 호출하였어요!

2023-01-13 04:22 UTC, iYeahh commented on JuiceMaker/JuiceMaker/Controller/UpdateStockViewController.swift
> +final class UpdateStockViewController: UIViewController {
StockViewController로 깔끔하게 변경하였어요 😀

2023-01-13 04:24 UTC, iYeahh commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        guard let updateStockViewController = self.storyboard?.instantiateViewController(withIdentifier: "UpdateStockViewController") as? UpdateStockViewController else { return }
`String(describing: )` 메소드를 처음 알게 되었어요!

개행까지 모두 수정하였어요 👍🏻

2023-01-13 04:41 UTC, iYeahh commented on JuiceMaker/JuiceMaker/Controller/UpdateStockViewController.swift
> +        self.presentingViewController?.viewWillAppear(false)
`ViewController의 생명주기`를 참고하여
* closeButtonDidTap(_ sender:) 에서 불필요하다고 하신 부분은 StepperDidTap(_ sender:) 에서 동작하도록 구현, viewWillAppear(_ animate:) 삭제하였고,
* viewDidLoad(), viewWillAppear(_ animate:) 두 군데에서 실행되던 updateStockLabels() 는 viewWillAppear(_ animate:) 에서만 동작되도록 변경하였어요!

2023-01-13 04:42 UTC, iYeahh commented on JuiceMaker/JuiceMaker/Controller/UpdateStockViewController.swift
> +        self.presentingViewController?.viewWillAppear(false)
`self 키워드`를
꼭 명시해줘야하는 경우에 대해 알아봤습니다 🤔
* escaping closure
*  initialize

명시적으로 self를 사용하는 곳보다는 최소화하는 회사가 더 많다는 것도 발견하였어요!
Swift API Design Guidelines 에서는 `간결함 보다 명확성이 더 중요하다`고 나와있지만
`'self'를 붙여서 명시성을 높이는 것보다, 함수를 작게 만들어서 구분에 드는 비용을 줄이는 게 더 좋을 것 같다`는 글을 보고
코리가 말씀하신 의견을 이해했어요  앞으로도 잘 적용하도록 하겠습니다 🤓

2023-01-13 10:05 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Controller/UpdateStockViewController.swift
> +    var fruitStore: FruitStore!
StockVC를 present할 때 fruitStore를 넘겨주기 때문에 여기서 `FruitStore` 인스턴스를 생성하는게 의미가 없어보여요.
초기화 함수로 넘겨주는건 어떨까요?

2023-09-08 07:43 UTC, closed without merging