쥬스메이커 [Step1] 뉴준성, 쫑
tasty-code/ios-juice-maker pull request #43
Opened 2023-09-12 02:32 UTC by newJunsung

## 리뷰어
@jryoun1

## 파일구조
- JuiceMaker
  + Controller
  + Model
    - FruitStore
    - FruitType
    - JuiceMaker
    - JuiceMakerException
    - JuiceType
  + View

## 고민했던 점

### Fruit와 Juice의 관계에 대한 정의
`FruitType`을 정의하여, 과일의 종류를 열거형으로 표현했습니다.
`typealias`를 통해, `Fruit`에 대한 튜플을 정의했습니다. 이 튜플은 (과일의 종류, 과일의 소모 개수)를 나타냅니다.
`JuiceType`은 쥬스의 종류를 열거형으로 나타냅니다. 내부의 `ingredients` 계산프로퍼티를 이용하여,
쥬스의 레시피를 `Fruit`(과일의 종류, 과일의 소모 개수) 배열을 통해 나타냈습니다.

- **FruitType**

```swift
import Foundation

typealias Fruit = (fruitType: FruitType, count: Int)

enum FruitType {
    case strawberry
    case banana
    case pineapple
    case mango
    case kiwi
}
```

- **JuiceType**

```swift
import Foundation

enum JuiceType {
    var ingredients: [Fruit] {
        switch self {
        case .strawberryJuice:
            return [Fruit(.strawberry, 16)]
        case .bananaJuice:
            return [Fruit(.banana, 2)]
        case .kiwiJuice:
            return [Fruit(.kiwi, 3)]
        case .pineappleJuice:
            return [Fruit(.kiwi, 3)]
        case .strawberrydBananaJuice:
            return [Fruit(.strawberry, 10), Fruit(.banana, 1)]
        case .mangoJuice:
            return [Fruit(.mango, 3)]
        case .mangoKiwiJuice:
            return [Fruit(.mango, 2), Fruit(.kiwi, 1)]
        }
    }

    case strawberryJuice
    case bananaJuice
    case kiwiJuice
    case pineappleJuice
    case strawberrydBananaJuice
    case mangoJuice
    case mangoKiwiJuice
}
```

### 한 개의 과일과 여러 개의 과일 추가・삭제 방식
한 개의 과일같은 경우에는 `checkValidation`(과일의 개수가 음수로 떨어지는지 확인하는 함수)를 통해 과일 개수를 즉시 업데이트를 했습니다.
여러 개의 과일은 `JuiceType`의 `ingredients`가 `[Fruit]`를 반환하기 때문에, 이 반환 값을 파리미터로 넣었습니다.
반복문을 통해 이 배열의 내용을 확인하며, 각 과일의 재고가 충분한지 검사합니다.
매개 변수인 `operator`는 과일 개수의 추가・감소를 결정하는 연산 클로저입니다.

이런 식으로 나타낼 수 있습니다.
```swift
try fruitStore.update(fruits: juice.ingredients, as: +)
```

- **FruitStore (한 개의 과일 처리 함수)**

```swift
func update(_ fruit: Fruit, as `operator`: ((Int, Int) -> Int)) throws {
    switch fruit.fruitType {
    case .strawberry:
        strawberry = try checkValidation(fruitCount: `operator`(strawberry, fruit.count))
    case .banana:
        banana = try checkValidation(fruitCount: `operator`(banana, fruit.count))
    case .pineapple:
        pineapple = try checkValidation(fruitCount: `operator`(pineapple, fruit.count))
    case .mango:
        mango = try checkValidation(fruitCount: `operator`(mango, fruit.count))
    case .kiwi:
        kiwi = try checkValidation(fruitCount: `operator`(kiwi, fruit.count))
    }
}
```

- **FruitStore (여러 개의 과일 처리 함수)**

```swift
func update(fruits: [Fruit], as `operator`: ((Int, Int) -> Int)) throws {
    let checkedFruits = try checkValidation(fruits: fruits, as: `operator`)
    
    for fruit in checkedFruits {
        checkedUpdate(fruit)
    }
}
```

### 현재 과일 개수의 상태로 쥬스를 만들 수 없을 때
명세에 따르면, 딸바 주스를 만들기 위해선 딸기가 10개, 바나나가 1개가 필요합니다.
기존 코드에서는 딸바주스를 만들 때, 딸기의 재고가 11개, 그리고 바나나의 개수가 0개면
딸기의 개수가 1개로 줄어든 상태에서 딸바 주스를 못 만들게 됩니다. 즉, 과일만 소모하고 주스가 만들어지지 않습니다.
따라서, 여러 개의 과일을 업데이트를 하는 함수에서는 먼저 각 과일의 재고가 충분한지 확인한 후에 주스를 만들게 개선했습니다.

- **기존 코드**

```swift
func update(fruits: [Fruit], as option: ((UInt, UInt) -> UInt)) {
    for fruit in fruits {
        update(fruit, as: option)
    }
}

func update(_ fruit: Fruit, as option: ((UInt, UInt) -> UInt)) {
    switch fruit.fruitType {
    case .strawberry:
        strawberry = option(strawberry, fruit.count)
        print(strawberry)
    case .banana:
        banana = option(banana, fruit.count)
    case .pineapple:
        pineapple = option(pineapple, fruit.count)
    case .mango:
        mango = option(mango, fruit.count)
    case .kiwi:
        kiwi = option(kiwi, fruit.count)
    }
}
```

- **개선된 코드**
```swift
func update(fruits: [Fruit], as `operator`: ((Int, Int) -> Int)) throws {
    let checkedFruits = try checkValidation(fruits: fruits, as: `operator`)
    
    for fruit in checkedFruits {
        checkedUpdate(fruit)
    }
}

private func checkValidation(fruits: [Fruit], as `operator`: ((Int, Int) -> Int)) throws -> [Fruit] {
    var checkedFruits = [Fruit]()
    for (fruitType, count) in fruits {
        var checkedCount = 0
        switch fruitType {
        case .strawberry:
            checkedCount = try checkValidation(fruitCount: `operator`(strawberry, count))
        case .banana:
            checkedCount = try checkValidation(fruitCount: `operator`(banana, count))
        case .pineapple:
            checkedCount = try checkValidation(fruitCount: `operator`(pineapple, count))
        case .mango:
            checkedCount = try checkValidation(fruitCount: `operator`(mango, count))
        case .kiwi:
            checkedCount = try checkValidation(fruitCount: `operator`(kiwi, count))
        }
        checkedFruits.append(Fruit(fruitType, checkedCount))
    }
    return checkedFruits
}
```

### 유효성 검사를 어떻게하면 효율적으로 할 수 있을지
기존에는, 여러 개의 과일의 재고가 충분한지 검사(`checkValidation` 함수)한 후에,
한 개의 과일을 업데이트(`update` 함수)하는 함수를 호출했습니다.
이 과정에서 `checkValidation` 함수가 2번 호출되기 때문에, 비효율적이었습니다. 왜냐하면 이미 확인한 과일들을 1번 더 검사했기 때문입니다.
이 코드를 개선하여, 여러 개의 과일의 재고를 검사하는 함수가 `[Fruit]` (과일의 타입, 증감된 과일의 수)를 반환하도록 하였습니다.
이 반환값으로 `checkedUpdate` 함수를 추가해서 검사된 과일들은 바로 재고 변경이 가능하도록 했습니다.

- **기존 코드**

```swift
func update(fruits: [Fruit], as `operator`: ((Int, Int) -> Int)) throws {
    try checkValidation(fruits: fruits, as: `operator`)
    
    for fruit in fruits {
        try update(fruit, as: `operator`)
    }
}

func update(_ fruit: Fruit, as `operator`: ((Int, Int) -> Int)) throws {
    switch fruit.fruitType {
    case .strawberry:
        strawberry = try checkValidation(fruitCount: `operator`(strawberry, fruit.count))
    case .banana:
        banana = try checkValidation(fruitCount: `operator`(banana, fruit.count))
    case .pineapple:
        pineapple = try checkValidation(fruitCount: `operator`(pineapple, fruit.count))
    case .mango:
        mango = try checkValidation(fruitCount: `operator`(mango, fruit.count))
    case .kiwi:
        kiwi = try checkValidation(fruitCount: `operator`(kiwi, fruit.count))
    }
}
```

- **개선된 코드**

```swift
func update(fruits: [Fruit], as `operator`: ((Int, Int) -> Int)) throws {
    let checkedFruits = try checkValidation(fruits: fruits, as: `operator`)
    
    for fruit in checkedFruits {
        checkedUpdate(fruit)
    }
}

private func checkValidation(fruits: [Fruit], as `operator`: ((Int, Int) -> Int)) throws -> [Fruit] {
    var checkedFruits = [Fruit]()
    for (fruitType, count) in fruits {
        var checkedCount = 0
        switch fruitType {
        case .strawberry:
            checkedCount = try checkValidation(fruitCount: `operator`(strawberry, count))
        case .banana:
            checkedCount = try checkValidation(fruitCount: `operator`(banana, count))
        case .pineapple:
            checkedCount = try checkValidation(fruitCount: `operator`(pineapple, count))
        case .mango:
            checkedCount = try checkValidation(fruitCount: `operator`(mango, count))
        case .kiwi:
            checkedCount = try checkValidation(fruitCount: `operator`(kiwi, count))
        }
        checkedFruits.append(Fruit(fruitType, checkedCount))
    }
    return checkedFruits
}

private func checkedUpdate(_ checkedFruit: Fruit) {
    switch checkedFruit.fruitType {
    case .strawberry:
        strawberry = checkedFruit.count
    case .banana:
        banana = checkedFruit.count
    case .pineapple:
        pineapple = checkedFruit.count
    case .mango:
        mango = checkedFruit.count
    case .kiwi:
        kiwi = checkedFruit.count
    }
}
```

2023-09-13 13:33 UTC, jryoun1 requested changes
안녕하세요 쫑, 뉴준성~
step1 고생하셨습니다.

코드를 작성하신 이유들을 잘 설명해주셔서 코드를 읽을 때 편리했던 것 같네요 💯 👏 
다만 몇가지 질문사항과 개선하면 좋을 것 같은 사항들이 있어서 코멘트 남겨두었습니다. 
확인부탁드려요 🙏 

### 질문사항 
> 반면에 Swift 공식 문서에 따르면 해당 사항을 [Guiding Principle of Access Levels](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/accesscontrol/#Guiding-Principle-of-Access-Levels)라고 하여 강제하지 않고 권고 하고 있습니다. 혹시 왜 이런지 알고 계신다면 답변을 남겨주시면 감사하겠습니다.

말씀해주신 부분은 저도 잘 모르겠어서 한 번 알아보고 알게되면 공유해드릴게요 🙏

2023-09-13 13:33 UTC, jryoun1 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    private func checkedUpdate(_ checkedFruit: Fruit) {
내부에서는 store의 과일들을 업데이트 해주는 것 같은데 함수명은 과일 업데이트를 검사하다? 이런식인것 같아서 의미가 불명확한 것 같습니다. 개선해볼까요?

2023-09-13 13:33 UTC, jryoun1 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        try FruitStore.shared.update(fruits: juice.ingredients, as: +)
juice를 make하게 되면 과일의 양이 줄어야할 것 같은데 +로 되어있어도 될까요?

2023-09-14 01:16 UTC, newJunsung commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +
제거했습니다!

2023-09-14 01:18 UTC, newJunsung commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        try FruitStore.shared.update(fruits: juice.ingredients, as: +)
감사합니다!
클로저의 다양한 적용방법을 코드를 통해 토론하다가 잘못 지운것 같습니다.
수정했습니다!

2023-09-14 01:18 UTC, shlim0 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    private func checkedUpdate(_ checkedFruit: Fruit) {
저희도 내부 로직이 이미 과일 개수를 확인하고 이를 반영하는 거라 네이밍 변경을 하는게 맞다고 생각했어요. 따라서, checkUpdate()를 applyCount()로 변경했습니다. :)

2023-09-14 01:20 UTC, newJunsung commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    var kiwi: Int
private(set)을 통하여, 외부에서 값을 확인할 수 있지만 값의 변경은 불가능하게 바꿨습니다.

2023-09-14 01:21 UTC, shlim0 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    static let shared = FruitStore()
싱글톤 패턴을 사용하면 하나의 인스턴스만을 생성하여 값을 제어할 수 있다고 알고 있습니다. 쥬스 메뉴를 주문하는 view와 과일 재고를 수정하는 view에서 '과일 개수'가 동기화(binding)되어야 하는데, 싱글톤은 한 인스턴스를 사용하기에 채택했습니다.

2023-09-14 01:23 UTC, shlim0 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    private func checkValidation(fruits: [Fruit], as `operator`: ((Int, Int) -> Int)) throws -> [Fruit] {
checkValidation()을 getCalculatedCounts()와 getCalculatedCount()로 네이밍을 수정했습니다. 이 둘의 차이는 입력받는(parameter) 과일이 여러개(배열)인지, 한개인지에 따라 다릅니다.

2023-09-14 01:24 UTC, newJunsung commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
말 그대로 편리하게 생성자를 불러내기 위해 사용합니다.
designated 생성자를 사용하면 저희 생성한 값들을 하나하나 지정해야하는 불편함이 있습니다.
그러나 convenience를 사용하여 매개변수를 받아서, 그 값을 바탕으로 편리하게 designated 생성자를 불러낼 수 있습니다.

2023-09-14 01:26 UTC, newJunsung commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    private(set) var kiwi: Int
private(set)을 사용하여 외부에서는 값을 조회만 할 수 있도록 했습니다!

2023-09-14 01:27 UTC, newJunsung commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        try FruitStore.shared.update(fruits: juice.ingredients, as: -)
as에 '-'를 사용하여 쥬스를 만들면 과일의 수가 줄도록 했습니다!

2023-09-14 04:05 UTC, jryoun1 commented
넵 변경해주신 부분 확인했습니다! 고생하셨습니다
step1은 여기서 마무리하고 다음 step으로 넘어가시죠! 💪

2023-09-14 04:05 UTC, merged