쥬스 자판기 [STEP 1] Mango, SwainYun
tasty-code/ios-juice-maker pull request #45
Opened 2023-09-12 05:26 UTC by Dongjun-developer

리뷰어: @zdodev
참가자: 망고, 스웨인

안녕하세요, 소대!
쥬스 자판기 [STEP 1] PR 올립니다.

---------------------

## 프로젝트 구성

* **쥬스와 과일의 종류를 나타내는 열거형**

```swift
@frozen enum JuiceType {
    case strawberryJuice, bananaJuice, kiwiJuice, pineappleJuice, strawberryBananaMixJuice, mangoJuice, mangokiwiJuice
}

@frozen enum FruitType {
    case strawberry, banana, kiwi, pineapple, mango
}
```

* **Fruit 모델**
```swift
struct Fruit {
    let fruitType: FruitType
    let quantity: Int
    
    init(_ fruitType: FruitType, _ quantity: Int) {
        self.fruitType = fruitType
        self.quantity = quantity
    }
    
    func updateQuantity(to quantity: Int) -> Fruit {
        return Fruit(self.fruitType, quantity)
    }
}
```
    * 주스 만드는 데 필요한 과일 종류와 수량을 가져오기 위한 구조체
    1. updateQuantity(): 과일 개수를 새로고침하는 함수
    2. 개수과 종류 정보를 가지고 비교할 수 있도록 함

* **FruitStore 클래스**
```swift
final class FruitStore {
    private var fruits: [Fruit] = [
        Fruit(.strawberry, 10),
        Fruit(.banana, 10),
        Fruit(.kiwi, 10),
        Fruit(.pineapple, 10),
        Fruit(.mango, 10)
    ]
    
    func receiveOrder(juiceType: JuiceType) {
        switch juiceType {
        case .strawberryJuice:
            makeJuice(Fruit(.strawberry, 16))
        case .strawberryBananaMixJuice:
            makeJuice(Fruit(.strawberry, 10),Fruit(.banana, 1))
        case .bananaJuice:
            makeJuice(Fruit(.banana, 2))
        case .kiwiJuice:
            makeJuice(Fruit(.kiwi, 3))
        case .pineappleJuice:
            makeJuice(Fruit(.pineapple, 2))
        case .mangoJuice:
            makeJuice(Fruit(.mango, 3))
        case .mangokiwiJuice:
            makeJuice(Fruit(.mango, 2), Fruit(.kiwi, 1))
        }
    }
}
```

    * FruitStore class
    1. 과일 초기 수량 설정, 주문 시 필요한 과일 레시피로 주문 받는 함수
    
* **makeJuice() 메서드**
```swift
private func makeJuice(_ ingredient: Fruit) {
    guard validateQuantity(ingredient: ingredient) else { return }
    updateFruit(fruit: ingredient)
}

private func makeJuice(_ firstIngredient: Fruit, _ secondIngredient: Fruit) {
    guard validateQuantity(ingredient: firstIngredient), validateQuantity(ingredient: secondIngredient) else { return }
    updateFruit(fruit: firstIngredient)
    updateFruit(fruit: secondIngredient)
}
```

    * makeJuice()
    1. 과일 수량 조절 함수
    2. receiveOrder()를 통해 전달받은 레시피에 따라서 현재 재고와 요구된 재고를 비교, 유효할 경우에 재고를 수정, 반영하기 위한 전처리 단계
> 1. 원래 `makeJuice(_ firstIngredient: Fruit, _ secondIngredient: Fruit?) { }` 형태의 메서드 하나만 사용하려 했으나, 옵셔널인 두번째 재료에 대해 `guard ~ else`로 early exit하는 과정 중 무조건 탈락되게 되어 두 조건 동시에 비교할 수 없어서 위와 같은 형태로 다시 작성했습니다.
> 2. 현재 코드로는, 만약 요구되는 재료가 세 가지, 네 가지 필요한 음료가 등장한다면 `makeJuice()`를 그만큼 추가로 작성해주어야 하는 것이 걱정됩니다. 새로운 요구에도 대응할 수 있는(재사용 가능한) 메서드를 어떻게 만들 수 있을지 궁금합니다.

* **유효성 검사, 재고 변경**
```swift
private func validateQuantity(ingredient: Fruit) -> Bool {
    guard let fruit = fruits.filter({$0.fruitType == ingredient.fruitType}).first else { return false }
    return fruit.quantity - ingredient.quantity >= 0
}

private func updateFruit(fruit: Fruit) {
    guard let index = fruits.firstIndex(where: {$0.fruitType == fruit.fruitType}) else { return }
    let target = fruits[index]
    let newQuantity = target.quantity - fruit.quantity
    fruits[index] = target.updateQuantity(to: newQuantity)
}
```

    * 유효성 검사, 재고 변경
    1. validateQuantity(): 현재 재고로 음료를 만들 수 있는지 확인하는 메서드
    2. updateFruit(): 현재 재고에서 음료를 만들고 남은 재고로 새로고침하는 메서드
> 1. 아쉬운 부분: `makeJuice()` 메서드에서 필요한 경우마다 1~2번 씩 호출하고 있는데, 더 효율적이고 알아보기 쉬운 메서드로 만들고자 했지만 방법을 찾지 못했습니다.

2023-09-12 14:32 UTC, zdodev requested changes
안녕하세요. @Dongjun-developer , @Remaked-Swain !

Step 1 구현 잘 진행해주셨습니다!
전체적인 역할 분리와 네이밍에 신경을 잘 써주신 것 같습니다!
README 도 이해하기 쉽고 깔끔하게 작성해주셨습니다!

`makeJuice` 메서드에 대해 여러 고민이 되는 점이 있어보입니다.
쥬스를 만드는 방법이나, 파라미터에 대한 제약은 없으니까 조금 더 유연하게 생각해보는 것은 어떨까요?
새로운 개념이나 요소(메뉴 or 메뉴판 같은)를 생각해도 좋을 것 같습니다!

이외에도 몇 가지 궁금증을 남겨보았습니다!
궁금증에 대해 코멘트를 남겨주셔도 좋습니다!

2023-09-12 14:32 UTC, zdodev commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        Fruit(.mango, 10)
반복되는 숫자를 별도로 관리해보는 것은 어떨까요?

2023-09-12 14:32 UTC, zdodev commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        var resultArr: [Fruit] = []
이름을 생략하기 보다는 전체 이름을 지어주는 것은 어떨까요?

2023-09-12 14:32 UTC, zdodev commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        guard let inventoryFruit = self.fruits.filter({ $0.showFruitType() == fruit.showFruitType() }).first else { throw Exception.fruitNotFound }
줄의 길이가 길어 개행하여 표현하는 것도 좋아보입니다!

2023-09-12 14:32 UTC, zdodev commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        guard let index = self.fruits.firstIndex(where: { $0.showFruitType() == target.showFruitType() }) else { throw Exception.fruitNotFound }
줄의 길이가 길어 개행을 하여 표현하는 것도 좋아보입니다!

2023-09-12 14:32 UTC, zdodev commented on JuiceMaker/JuiceMaker/Model/FruitType.swift
> +@frozen enum FruitType {
`@frozen` 을 적용하신 이유가 궁금합니다. 해당 구문에 대해 더 확인해보면 좋을 것 같습니다!

2023-09-12 14:32 UTC, zdodev commented on JuiceMaker/JuiceMaker/Model/FruitType.swift
> +    case strawberry, banana, kiwi, pineapple, mango
한 줄에 모두 나열하기 보다는 `case` 를 나누는 것은 어떨까요? 지금도 좋습니다!

2023-09-12 14:32 UTC, zdodev commented on JuiceMaker/JuiceMaker/Model/FruitType.swift
> +struct Fruit {
`Fruit` 타입을 구현해보셨네요.👍

2023-09-12 14:32 UTC, zdodev commented on JuiceMaker/JuiceMaker/Model/FruitType.swift
> +    }
`fruitType` 값을 반환하는 메서드를 구현하신 이유가 궁금합니다!

2023-09-12 14:32 UTC, zdodev commented on JuiceMaker/JuiceMaker/Model/FruitType.swift
> +    }
`quantity` 값을 반환하는 메서드를 구현하신 이유가 궁금합니다!

2023-09-12 14:32 UTC, zdodev commented on JuiceMaker/JuiceMaker/Model/FruitType.swift
> +    }
`Self` 키워드를 사용해보셨네요.👍
메서드명이 불명확한 것 같습니다. `quantityDistance` 메서드명보다 보다 명확한 이름으로 지어볼 수 있을까요?

2023-09-13 00:52 UTC, Dongjun-developer commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        var resultArr: [Fruit] = []
전체 이름을 지어주는 부분이 메서드명인지 파라메터명인지 어떤 부분을 이야기 해주신건지 이해가 잘 안되요.

2023-09-13 01:11 UTC, Dongjun-developer commented on JuiceMaker/JuiceMaker/Model/FruitType.swift
> +    }
점표기법으로 타입 내부에 값을 직접 가져오기 보다는 메서드를 사용하여서 값을 가져오는게 캡슐화를 사용하여 은닉성을 높여줄 수 있다고 생각하여서 이렇게 구현하였습니다.

2023-09-13 01:12 UTC, Dongjun-developer commented on JuiceMaker/JuiceMaker/Model/FruitType.swift
> +    }
위에 내용과 같이 캡슐화를 사용해서 구현해보았습니다.

2023-09-13 01:22 UTC, Dongjun-developer commented on JuiceMaker/JuiceMaker/Model/FruitType.swift
> +    }
quantityDistanch 는 재고량에서 과일을 만들 수 있는지 개수를 계산하는 매서드였습니다.
이러한 매서드를 naming하신다면 어떠한 매서드명을 지을 수 있을지 알려줄수 있으실까요?

2023-09-13 01:35 UTC, Remaked-Swain commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        var resultArr: [Fruit] = []
`requiredFruit requiredFruit: [Fruit]` 처럼 파라미터명을 풀네임으로 작성하여야 읽기 쉽다는 조언으로 이해하면 될지, 아니면 다른 이야기인지 모르겠습니다 ㅋㅋ... 🤔

2023-09-13 01:38 UTC, Remaked-Swain commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        Fruit(.mango, 10)
'10'이라는 숫자를 반복해서 입력해주어야 하는 부분을 말씀해주셨습니다.

말씀하신 내용에 대하여 저희 두 명은 아래와 같은 방법을 생각해보았습니다.
* SwainYun이 제안한 방안
```swift
// Properties
    private var inventory: [FruitType: Int]
    
    init() {
        let initialQuantity: Int = 10
        
        var inventory: [FruitType: Int] = [:]
        
        for fruitType in FruitType.allCases {
            inventory[fruitType] = initialQuantity
        }
        
        self.inventory = inventory
    }
```
> 모든 FruitType에 대해 10이라는 값으로 초기화 될 수 있도록 합니다.
> FruitType은 CaseIterable을 채택했습니다.
> PR 보내드릴 당시 과일을 저장하던 프로퍼티는 배열이었는데, 현재 코드는 위처럼 딕셔너리로 만들 시 어떻게 할 수 있을까를 가정하여 시도하고 있습니다.

* Mango가 제안한 방안
```swift
struct Fruit {
  private let fruitType: FruitType
  private let quantity: Int
  private let initialQuantity: Int = 10
  init(_ type: FruitType) {
    self.fruitType = type
    self.quantity = initialQuantity
  }
}
```
> 생성 시 초기값을 initialQuantity로 Fruit 객체 생성 시에 전달한다면
> 생성 초기값을 변경 시에 initialQuantity 값만 변경해서 관리해 줄 수 있다고 생각했습니다.

2023-09-13 01:40 UTC, Remaked-Swain commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        guard let inventoryFruit = self.fruits.filter({ $0.showFruitType() == fruit.showFruitType() }).first else { throw Exception.fruitNotFound }
다음과 같이 개행해보았습니다.

```swift
guard let inventoryFruit = self.fruits.filter({ $0.showFruitType() == fruit.showFruitType() }).first 
else { throw Exception.fruitNotFound }
```

어떤 조건으로 동작할지, 그리고 조건에 맞지 않으면 어떤 일을 수행할지 알아보기가 쉬워졌습니다!

2023-09-13 01:40 UTC, Remaked-Swain commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        guard let index = self.fruits.firstIndex(where: { $0.showFruitType() == target.showFruitType() }) else { throw Exception.fruitNotFound }
위와 동일합니다 :)

2023-09-13 01:48 UTC, Remaked-Swain commented on JuiceMaker/JuiceMaker/Model/FruitType.swift
> +@frozen enum FruitType {
`@frozen` 키워드는 '다른 케이스와 그 케이스에 대한 처리는 추가되지 않을거야.'  라고 컴파일러에게 알려주는 키워드라고 들었습니다.
따라서 컴파일러는 default문 없이 모든 케이스에 대응하면서도, 구체적으로 구현되지 않은 다른 케이스가 있는지 검사하지 않아도 되니 성능 상의 이점이 있다고 알고 있어서 `@frozen` 키워드를 사용했습니다.

그러나 다음 단계에서 혹은 먼 미래에 다른 메뉴가 절대 추가되지 않는다거나, 그 메뉴에 들어갈 과일이 추가되지 않을 것임을 모르기 때문에 오히려 `@frozen` 키워드의 존재 이유와 반대되는 것 같다고 느꼈습니다.

2023-09-13 01:53 UTC, Remaked-Swain commented on JuiceMaker/JuiceMaker/Model/FruitType.swift
> +    case strawberry, banana, kiwi, pineapple, mango
case 개행에는 제 코딩 스타일이 반영되었습니다 :)

* **JuiceType**
```swift
private enum JuiceType: String {
        case strawberryJuice = "딸기쥬스"
        case bananaJuice = "바나나쥬스"
        case kiwiJuice = "키위쥬스"
        case pineappleJuice = "파인애플쥬스"
        case strawberryBananaMixJuice = "딸바쥬스"
        case mangoJuice = "망고쥬스"
        case mangokiwiJuice = "망키쥬스"
       
        // ...
    }
```
> 이렇게 원시값을 넣어준 케이스는 한 줄에 나열했을 때 가독성이 매우 떨어졌기 때문에 case를 나누어 주었습니다.

* **FruitType**
```swift
enum FruitType {
  case strawberry, banana, kiwi, pineapple, mango
}
```
> 이것은 각 케이스의 이름이 짧고 원시값이 없어서 한 줄로 작성하는게 더 보기 편했습니다.

2023-09-13 02:13 UTC, Remaked-Swain commented on JuiceMaker/JuiceMaker/Model/FruitType.swift
> +    }
그런데 또 한 편으로는 FruitStore 클래스 안에 FruitType, Fruit을 중첩시켜서 쓴다고 하면
그냥 점표기법으로 접근하게 하는 것도 괜찮을 것 같기도 하고...

2023-09-13 02:19 UTC, Remaked-Swain commented on JuiceMaker/JuiceMaker/Model/FruitType.swift
> +    }
`calcQuantityGap()`
`calcQuantityDistance()`
이 정도 밖에 생각이 안나네요..ㅋㅋ

2023-09-14 09:04 UTC, ehgud0670 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        var resultArr: [Fruit] = []
@Dongjun-developer 

resultArr 를 말씀하시는것 아닐까요? 변수명이 축약되어 있네요.

2023-09-14 12:45 UTC, zdodev commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        var resultArr: [Fruit] = []
네 맞습니다. 코멘트 달아주셔서 감사합니다!

2023-09-14 13:32 UTC, zdodev reviewed
안녕하세요. @Dongjun-developer , @Remaked-Swain !

리뷰에 대한 코멘트를 잘 고민해주셨네요.👍
팀원끼리 서로 각자의 의견을 전달해주신 점이 좋았습니다!👍

Step 1 진행하시느라 고생하셨습니다!
여기서 마무리하도록 하겠습니다!

머지 요청 말씀해주시면 머지하도록 하겠습니다.

2023-09-14 13:32 UTC, zdodev commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    private enum JuiceType: String {
`nested type` 을 활용해보셨네요.👍

2023-09-14 13:32 UTC, zdodev commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    // 현재 재고 확인, 요구 수량을 빼고도 0 이상이면 통과, 아니면 outOfStock 에러 전파
꼭 필요한 주석(문서화 주석 등)이 아니라면, 제거해도 좋을 것 같습니다!

2023-09-14 13:32 UTC, zdodev commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
`SwainYun` 이 제안한 방식으로 해보셨네요.
이렇게 하면 매 과일마다 작성하지 않아도 되겠네요. 좋습니다.👍

2023-09-15 00:46 UTC, Dongjun-developer commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        var resultArr: [Fruit] = []
> @Dongjun-developer
> 
> resultArr 를 말씀하시는거 아닐까요? 변수명이 축약되어 있네요.

@ehgud0670 감사합니다~

2023-09-15 08:22 UTC, Remaked-Swain commented
# 쥬스 자판기 [STEP 2] Mango, SwainYun

리뷰어: @zdodev
참가자: 망고, 스웨인

안녕하세요, 소대!
쥬스 자판기 [STEP 2] PR 올립니다.

------------------------------------

## 프로젝트 구성

### JuiceMaker, FruitStore

* **쥬스와 과일의 종류를 나타내는 열거형**
```swift
private enum JuiceType: String {
    case strawberryJuice = "딸기쥬스"
    case bananaJuice = "바나나쥬스"
    case kiwiJuice = "키위쥬스"
    case pineappleJuice = "파인애플쥬스"
    case strawberryBananaMixJuice = "딸바쥬스"
    case mangoJuice = "망고쥬스"
    case mangoKiwiMixJuice = "망키쥬스"
    
    var recipe: [Fruit] {
        switch self {
        case .strawberryJuice: return [Fruit(.strawberry, 16)]
        case .bananaJuice: return [Fruit(.banana, 2)]
        case .kiwiJuice: return [Fruit(.kiwi, 3)]
        case .pineappleJuice: return [Fruit(.pineapple, 2)]
        case .strawberryBananaMixJuice: return [Fruit(.strawberry, 10), Fruit(.banana, 1)]
        case .mangoJuice: return [Fruit(.mango, 3)]
        case .mangoKiwiMixJuice: return [Fruit(.mango, 2), Fruit(.kiwi, 1)]
        }
    }
}

private enum FruitType: String, CaseIterable {
    case strawberry = "딸기"
    case banana = "바나나"
    case kiwi = "키위"
    case pineapple = "파인애플"
    case mango = "망고"
}
```

    * JuiceType, FruitType
    1. FruitStore 클래스 내에서만 사용할 것이라고 판단, FruitStore Nested Type으로 변경
    2. Storyboard의 각 버튼과 재고 현황을 표시하기 위해 Accessability ID와 매칭할 수 있도록 각 case별 RawValue 설정
> 각 버튼과 재고 라벨을 매칭할 수단으로, Restoration ID는 UI 복구 시 사용되는 것이라고 해서 사용하지 않는 것으로 의견 나눴고 버튼의 타이틀텍스트를 이용하는 것은 코드가 지저분해 보였습니다.
> 다른 방법도 많이 있겠지만 Accessability ID를 사용하기로 결정했습니다.

* **Fruit 모델**
```swift
private struct Fruit {
    let fruitType: FruitType
    let quantity: Int

    init(_ fruitType: FruitType, _ quantity: Int) {
        self.fruitType = fruitType
        self.quantity = quantity
    }
}
```
    * 주스 만드는 데 필요한 과일 종류와 수량을 가져오기 위한 구조체
    1. 마찬가지로 FruitStore 클래스 내에 위치하는 것으로 변경
    2. 개수과 종류 정보를 가지고 비교할 수 있도록 함

* **FruitStore 클래스**
```swift
final class FruitStore {
    private var inventory: [FruitType: Int]
    
    init() {
        let initialQuantity: Int = 10
        
        var inventory: [FruitType: Int] = [:]
        
        for fruitType in FruitType.allCases {
            inventory[fruitType] = initialQuantity
        }
        
        self.inventory = inventory
    }
}
```

    * FruitStore class
    1. 과일 종류별 재고를 쉽게 다루기 위해 Dictionary가 적절한 것 같아 Dictionary로 변경
    2. 초기값 설정 시 반복되는 숫자 '10'을 다루기 위해 init 작업에 추가
    
* **receiveOrder() 메서드**
```swift
func receiveOrder(juiceName: String) throws {
    guard let juice = JuiceType(rawValue: juiceName) 
    else { throw JuiceMakerError.invalidSelection }
    let recipe = juice.recipe
    
    for ingredient in recipe {
        try validateStock(with: ingredient)
    }
    
    for ingredient in recipe {
        try updateInventoryStock(with: ingredient)
    }
}
```

    * receiveOrder()
    1. 버튼 입력으로 받아온 juiceName(Accessability ID로 등록되어있던)으로 JuiceType이 있는지 확인, 
    2. 있다면 그 쥬스의 레시피를 확인, 
    3. 레시피에서 요구한 과일 및 수량과 현재 재고를 확인, 제조 가능하다면 사용한만큼 재고 조정
> 변경 전 메서드에서, 재고 조정 시마다 관련 함수를 호출해야할 때 반복되는 코드를 여러번 작성하는 것이 마음에 들지 않았는데 반복문 사용으로 이를 해결했습니다.

* **유효성 검사, 재고 변경**
```swift
private func validateStock(with fruit: Fruit) throws {
    guard let stock = self.inventory[fruit.fruitType], stock - fruit.quantity >= 0 else { throw JuiceMakerError.outOfStock }
}

private func updateInventoryStock(with fruit: Fruit) throws {
    guard let stock = self.inventory[fruit.fruitType] else { throw JuiceMakerError.invalidSelection }
    let remainStock = stock - fruit.quantity
    self.inventory[fruit.fruitType] = remainStock
}
```

    * 유효성 검사, 재고 변경
    1. validateStock(): 현재 재고 확인, 요구 수량을 빼고도 재고가 0 이상이면 통과, 아니면 outOfStock 에러 전파
    2. updateInventoryStock(): 요구 수량만큼 빼고 변경된 값으로 재고 갱신
> 재고 부분을 Dictionary로 변경하면서 관련 메서드들도 조금씩 바꾸어 주었습니다.

---------------------------------------

### JuiceMakerViewController

* **makeJuice() 메서드**
```swift
@IBAction func makeJuice(_ sender: UIButton) {
    guard let buttonId = sender.accessibilityIdentifier 
    else { return }
    do {
        try juiceMaker.makeJuice(juiceName: buttonId)
        manageFruitStock()
        showAlertCompletionJuiceMaking(buttonId)
    } catch let error {
        showAlertOutOfStock(error)
    }
}
```

    * makeJuice()
    1. Accessability ID를 통해 어떤 버튼이 입력되었는지 식별
    2. 모델 쪽 메서드와 연결, 재고 확인 및 수정 작업 등이 이루어짐
    3. 성공 여부에 따라 적절한 얼럿 표시
> VC의 makeJuice 메서드와 Model의 makeJuice 메서드 이름이 겹치는데, 이럴 경우 어떤 문제가 발생할 수 있을까요?

* **manageFruitStock() 메서드**
```swift
private func manageFruitStock() {
    let inventory = juiceMaker.checkFruitStoreInventory()

    strawberryStockLabel.text = String(inventory["딸기"] ?? 0)
    bananaStockLabel.text = String(inventory["바나나"] ?? 0)
    kiwiStockLabel.text = String(inventory["키위"] ?? 0)
    pineappleStockLabel.text = String(inventory["파인애플"] ?? 0)
    mangoStockLabel.text = String(inventory["망고"] ?? 0)
}
```

    * manageFruitStock()
    1. 과일명과 재고 정보를 읽어옴
    2. 재고 수량을 표시하는 라벨에 현재 재고 표시
> 쥬스 주문 후 변경된 재고로 새로고쳐주기 위해 makeJuice 메서드 내에서 다시 호출합니다.
> 또 최초 뷰 렌더링 시 표시될 수 있도록 viewDidLoad() 내에서 호출합니다.


* **showAlertCompletionJuiceMaking() 메서드**
```swift
private func showAlertCompletionJuiceMaking(_ juiceName: String) {
    let alert = UIAlertController(title: "\(juiceName) 쥬스 나왔습니다! 맛있게 드세요!", message: nil, preferredStyle: .alert)
    let yes = UIAlertAction(title: "감사합니다!", style: .default)
    alert.addAction(yes)
    present(alert, animated: true, completion: nil)
}
```

    * showAlertCompletionJuiceMaking()
    1. 쥬스 만들기에 성공할 경우 얼럿 표시
    2. 얼럿을 닫을 수 있는 버튼 추가
> 주스 재고가 있을 경우나 실행되는 메서드 입니다. 주문한 주스 이름이 alert해주고 창을 닫을 수 있도록 "yes" UIAlertAction을 추가해 주었습니다.

* **showAlertOutOfStock() 메서드**
```swift
private func showAlertOutOfStock(_ error: Error) {
    let alert = UIAlertController(title: "\(error)", message: nil, preferredStyle: .alert)
    let yes = UIAlertAction(title: "예", style: .default) { _ in
        self.moveAdjustStorageView()
    }
    let no = UIAlertAction(title: "아니오", style: .destructive, handler: nil)
    alert.addAction(yes)
    alert.addAction(no)
    present(alert, animated: true, completion: nil)
}
```

    * showAlertOutOfStock()
    1. 재고 부족으로 전파된 JuiceMakerError.outOfStock 상황에 대한 처리
    2. 재고 설정 뷰로 이동하거나 얼럿을 닫을 수 있는 버튼 두개 추가
>음료를 제조하기에 재고가 부족한 경우 실행되는 메서드이며 
> * yes경우: moveAdjustStorageView를 실행합니다.
> * no경우: alert을 닫습니다.

* **pushAdjustStockViewController() 메서드**
```swift
private func pushAdjustStockViewController() {
    guard let adjustStockViewController = self.storyboard?.instantiateViewController(withIdentifier: "AdjustStockViewController") as? AdjustStockViewController
    else { return }

    self.navigationController?.pushViewController(adjustStockViewController, animated: true)
}
```

    * pushAdjustStockViewController()
    1. navigationController를 사용하여 화면 전환시 화면 이동에 연관된 처리까지 기능해준다. UI측면에서 우측상단의 버튼클릭 시 오른쪽에서 화면이 등장하여 화면전환에 이질감이 줄어든다.
    2. AdjustStockViewController를 인스턴스화 해 부르는 과정에서 타입 캐스팅을 시도, 추후 재고 수정 화면에서 데이터를 주고 받을 수 있도록 함
> * present
> 1. 뷰 위에 뷰가 한겹 올라간 것
> 2. 세로 방향으로 전개됨
> 3. ViewController - dismiss 메서드로 빠져나옴
> 그래서 얼럿이나 알람같은거에 적합함?
> 4. modalPresentationSytle로 환면 전환 스타일을 정할 수 있음
> 
> * push
> 1. stack에 뷰컨트롤러를 push해서 다른 계층의 뷰로 전환
> 2. 가로 방향으로 전개됨
> 3. NavigationController - pop 메서드로 빠져나옴
> 4. 원하는 스택으로 돌아갈 수 있음

> * push를 사용한 이유
> 1. ViewController는 그림과 같이 1번View는 2번 View와 2번 View 3번 View끼리는 서로 연결 되어 있지만 1번 3번 View 끼리는 서로의 존재를 모릅니다.(바로 연결되어 있지 않다. 어쨌든 2번 뷰를 거쳐야 함)
> 2. NavigationController는 view들을 Stack에 넣어서
> stack의 크기단위를 알기에 원하는 위치로 이동이 가능하다는 차이가 있습니다.
> NavigationController는 view들을 Stack에 넣어서
> stack의 크기단위를 알기에 원하는 위치로 이동이 가능하다는 차이가 있습니다.

2023-09-15 14:17 UTC, merged