주스 메이커 [Step 1] 밤삭, 범
tasty-code/ios-juice-maker pull request #49
Opened 2023-09-13 04:36 UTC by snowy-summer

# 주스메이커 프로젝트 [STEP 1]

@monsteel

안녕하세요. Tony
주스메이커 프로젝트를 실습하고 PR요청 드립니다.

## 구조 설명

- ### Models
    - JuiceMaker
        - 주스를 만드는데 필요한 재료들을 FruitStore에서 빼주기 위한 메소드들을 모아놓은 구조체 입니다.
        - enum Recipe
            - 각 주스에 대한 Recipe들을 케이스 별로 모아 놓은 열거형 입니다.
    - FruitStore
        - 과일 재고의 변화를 계산해주는 메소드와 각 과일에 인스턴스를 배열로 가지고 있는 class입니다.
        - struct Fruit
            - 각 과일에 대한 이름과 수량을 프로퍼티로 가지고 있는 구조체 입니다.
        
    - ErrorCase
        -  각 에러에 대한 상들을 케이스 별로 모아 놓은 열거형 입니다.

## 프로젝트 진행과정

### 1. 기능 구현
- checkStock,makeJuice
    - 여러 과일이 섞인 메뉴 때문에 고민했습니다. 
        - 파라미터를 받아올 때 첫 번째 과일, 두 번째 과일... 이런식으로 받아오는 것은 나중에 과일이 3개, 4개 섞인 주스를 추가할 경우, 받아오는 파라미터를 계속 늘려줘야는 불편함을 줄이고자, 배열을 받아와 for문으로 배열을 탐색하는 방법으로 만들었습니다.

- orderConvertToDict
    - 파라미터로 받은 주스를 enum Recipe의 rawValue인지 확인 후, 해당 주스에 필요한 과일과 과일 갯수를 가진 딕셔너리로 반환을 하는 메소드입니다.
    - 올바른 주문인지 확인하는 함수의 내용 때문에 이름을 checkOrder로 변경하려고 합니다.

- convertFruitArr, convertDecreaseCountArr
    - [Fruit: Int]타입의 딕셔너리를 파라미터로 받아와 Fruit타입의 key를 모아놓은 배열, 소모되는 재료의 수(Int타입)를 모아놓은 배열로 반환해주는 메소드입니다.

### 2. 구조 설계시 의문점
- JuiceMaker
    - 현재 Step1을 파악하기론 ViewController에 JuiceMaker 인스턴스를 하나만 생성하기 때문에, Recipe에 대한 enum을 JuiceMaker안에 종속성을 가지기 위해 안에 생성을 했습니다. JuiceMaker 밖으로 빼서 독립적으로 사용할 수 있게 하는게 나은지 궁금합니다.
    - 저희가 생각했을 때, 따로 빼서 선언을 하게 되면 다른 곳에서 enum Recipe에 대한 불피요한 접근을 하게 되는 단점이 있을 것 같지만, 만약 JuiceMaker로 enum Recipe의 케이스에 포함되지 않는 다른 주스를 만들수 있는 JuiceMaker타입의 인스턴스를 생성했을 때, 다른 주스에 대한 enum을 생성하고 분리하여 독립적으로 사용할 수 있는 장점이 있을 것 같습니다.

2023-09-13 06:34 UTC, Monsteel requested changes
밤삭, 범 안녕하세요~ 
첫 step1 수고 많으셨어요 👍 

구조에 대한 설명, 프로젝트 진행 과정을 간결하게 잘 작성해 주셔서 리뷰할 때, 두분의 생각 흐름에 따라 리뷰할 수 있어 도움이 되었습니다. 고맙습니다 👍 

코드에 대한 리뷰는 아래 코멘트 참고해주시구요,
코드에 대한 의견을 여쭈어보는 리뷰도 포함되어 있으니 코멘트 남겨주시면 감사하겠습니다 👍

이어서 남겨주신 의문점 대해 제 의견을 작성해 볼게요 👍

JuiceMaker
>현재 Step1을 파악하기론 ViewController에 JuiceMaker 인스턴스를 하나만 생성하기 때문에, Recipe에 대한 enum을 JuiceMaker안에 종속성을 가지기 위해 안에 생성을 했습니다. JuiceMaker 밖으로 빼서 독립적으로 사용할 수 있게 하는게 나은지 궁금합니다.
>
> 저희가 생각했을 때, 따로 빼서 선언을 하게 되면 다른 곳에서 enum Recipe에 대한 불피요한 접근을 하게 되는 단점이 있을 것 같지만, 만약 JuiceMaker로 enum Recipe의 케이스에 포함되지 않는 다른 주스를 만들수 있는 JuiceMaker타입의 인스턴스를 생성했을 때, 다른 주스에 대한 enum을 생성하고 분리하여 독립적으로 사용할 수 있는 장점이 있을 것 같습니다.

우선, 지금 코드 기준으로 Recipe enum에 접근 제어자로 접근을 제한하지 않았기 때문에, 현재 구조에서 Recipe에 대해 JuiceMaker.Recipe 형태로 접근이 가능합니다 ㅎㅎ

각각 어떤 장점들이 있는지 다시한번 비교해주시고, 효용의 가치가 높은 방향으로 두분이 결정해주셔도 무관할것 같습니다 👍 

코드 반영사항 + 코멘트 남겨주시면 이어서 리뷰 진행할 수 있도록 하겠습니다 👍

2023-09-13 06:34 UTC, Monsteel commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +            try makeJuice(fruits: fruitArr, decreaseCountArr: decreaseCountArr)
1. dictionary의 key와 value를 각각의 배열로 분리하여 사용하는 구조를 설계하신 배경이 있을까요?

2. dictionary 사용을 통해 확보했던 코드의 안정성이 저해되는 포인트라 생각되는데요, dictionary 의 장점과, 이처럼 각각의 배열로 분리하여 사용했을 때 발생할 수 있는 문제점을 중심으로 한번 고민해봐 주셨으면 좋겠습니다 👍

2023-09-13 07:42 UTC, bamsak commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
먼저 이 부분은 Fruit타입 배열의 변수 명을 처음 선언 시 fruits로 선언을 했었습니다. 
그 후, JuiceMaker의 코드를 구현하는 부분에서 fruits를 반복하여 작성하게 되어 혼란이 온다는 의견이 있었고 변수명을 변경하는 과정에서  차마 이니셜라이저의 파라미터명도 같이 바꾸지 못했습니다.
다음부터 이런 상황이 있을 때 더 꼼꼼히 체크하고 변경하겠습니다.

2023-09-13 07:47 UTC, snowy-summer commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        var juiceIngredient: [FruitStore.Fruit: Int] {
한가지 함수로 재고를 추가할 때와 소모할 때 사용하기 위해 쥬스를 만드는데 필요한 재료의 갯수를  음수로 사용 했었습니다.  소모를 위한 함수는 juiceMaker에 구현을 하여 분리하겠습니다.

2023-09-13 09:19 UTC, bamsak commented on JuiceMaker/JuiceMaker/Model/Errorcase.swift
> +}
우선 ErrorCase를 Error프로토콜 error발생시 errorMessage를 확인하고 디버깅을 해야한다는 생각으로 각 case별로 어떤 에러가 발생한지 알기 쉽게하기 위해 저희가 Custom한 String을 출력하도록 CustomDebugStringConvertible를 채택하였습니다. 
또한 error처리라고 생각을 하여 Debug라는 키워드에 집중이 하여 CustomDebugStringConvertible를 채택했습니다. 
이번 리뷰 답변을 위해 String Representation protocol 대해 기존 알고 있던 프로토콜 외에 여러가지가 있는 것을 알게 되었고, 그 중 하나인  CustomStringConvertible를 채택하여 현 코드에 적용시키고 테스트를 해봤는데, 현 코드로는 두 프로토콜의 차이가 크게 와닿지가 않습니다.
해당 프로토콜둘에 대해 명확한 사용성을 구분짓기 위해 탐구를 해보려 하는데 해당하는 키워드를 알려주시면 감사하겠습니다.🙇‍♂️

2023-09-13 10:22 UTC, bamsak commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +            try makeJuice(fruits: fruitArr, decreaseCountArr: decreaseCountArr)
우선 첫번째로 딸바 주스 같은 재료가 두가지 들어가는 것에 대해  key는 key끼리 value는 value끼리 묶는 방법을 먼저 떠올렸고, 각 Array 의 요소의 갯수가 같아 인덱스로 접근하면 될 것 같은 생각이 들었습니다.

지금 리뷰를 받고 생각해보니  Dictionary의 key와 value에 접근하기 위해 따로 옵셔널 바인딩으로 index로 접근해야하는 Array 타입 보다 안정성을 더 가져갈 수 있다고 생각합니다.

두가지 솔루션을 생각해 내었는데,
첫번째로 
```swift
[[Fruit(name: “딸기") : “10”], [Fruit(name: “바나나”) : 1]]
```
각 디셔너리들을 배열로 가지고 있게 생각을 해보았습니다.
하지만 이 경우엔 기존 구현해왔던 것과 같이 각 딕셔너리에 접근하기 앞서 배열의 인덱스로 접근하는 위험성이 있을거 같은 생각이 듭니다.

두번째로는
```swift
["딸바주스": [Fruit(name: “딸기") : 10, Fruit(name: “바나나") : 1]
```
딕셔너리를 키로 묶어주어 key값으로 접근할 수 있게 하는 방법을 생각해냈습니다.
저의 판단으로는 key값으로 접근하여 옵셔널 바인딩을 통해 안정성을 확보하는 두번째 방법이 안정성을 높여줄 것이라 생각이 들어 진행해보려고 합니다. 코드의 정답이 없다고 하지만 저의 방향성에 대해 의견이 어떠신지 남겨주시면 감사드리겠습니다. 🙇‍♂️

2023-09-14 00:33 UTC, bamsak commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +            try makeJuice(fruits: fruitArr, decreaseCountArr: decreaseCountArr)
제가 어렵게 생각한 것 같습니다. Enum내의 연산 프로퍼티 타입을 위 방법으로 변경하지 않고 현재 반환타입 그대로 사용하여 따로 배열로 만들지 않고 진행하는 방법이 생각이 나 해당 방법으로 진행하겠습니다!

2023-09-14 06:13 UTC, Monsteel commented on JuiceMaker/JuiceMaker/Model/Errorcase.swift
> +}
관련된 키워드를 몇개 뽑아보면 description, debugDescription, print, debugPrint 정도 생각이 나는데요,
아마 찾아보시면서 이미 접해본 단어일수도 있겠다는 생각이 드네요. 사용 예제들을 살펴보고 실습해보시면서 두 프로토콜의 차이를 비교해보는 방법도 좋을것 같습니다 👍

2023-09-14 06:20 UTC, Monsteel commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        mangoQuatityLabel.text = String(juiceMaker.fruitStore.fruitList[4].stock)
UI에 대한 코드가 추가되었네요!
이번 step1에서 의도한 수정사항인가요 ?

2023-09-14 07:24 UTC, Monsteel approved these changes
수고하셨습니다 :)

2023-09-14 07:24 UTC, merged