STEP 1 Ireu, Poodle
tasty-code/ios-juice-maker pull request #5
Opened 2022-08-26 05:44 UTC by Y00ujin

### STEP 1 구현한 내용
- FruitJuice 열거형 생성
- Fruit 열거형 생성
- changeStock 함수 생성
- makeJuiceOf 함수 생성
- canMakeJuiceOf 함수 생성

<br>

### STEP 1 고민한 내용
- canMakeJuiceOf 함수 네이밍을 고민했는데, Bool 값을 리턴하는 함수 네이밍을 조동사를 사용하여 하는 경우가 있어서 can을 사용해 네이밍했다.

2022-08-26 07:35 UTC, jaemuYeo requested changes
푸들 이루 Step1 진행하느라 고생많았어요 👏
타입을 설계하는 것이 생각보단 어렵죠?? ㅎㅎ
자꾸자꾸 생각해보고 시도해보면 빠르게 성장할 수 있을거라 믿습니다!!
Bool 타입에 대한 네이밍을 고민한 부분은 아주 베스트입니다👍👍
is, can 이외에도 몇가지가 더있으니 상황에 맞게 사용하면 좋을 거같아요~

2022-08-26 07:35 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +enum FruitJuice: String {
쥬스 종류를 담은 이 타입은 어디에 포함되어 있을 수 있을까요??
무엇을 의미하는지 모를 문자열 원시값들도 어디에 사용할 것인가에 대한 궁금증이 생기네요 🤔
네이밍을 포함해 어떠한 경우든 축약된 무엇인가는 가독성에 너무너무 좋지 않아요 ㅠ-ㅠ

쥬스타입은 종류를 포함에 어떤 것들을 가지고 있을까요??
쥬스의 이름과 레시피도 이 곳에 포함되면 좋을 것같아 생각하는데
두 분의 생각은 어떤지 궁금합니다!!
Hint. 열거형에서의 연산프로퍼티 사용방법을 알아보세요!

2022-08-26 07:35 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +enum Fruit: String {
과일 종류를 담은 이 타입은 어디에 포함되어 있을 수 있을까요?
위에 FruitJuice열거형과 마찬가지로 원시값들의 의미를 모르겠어요!!

2022-08-26 07:35 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +public class FruitStore {
FruitStore 클래스는 왜 클래스로 선언되었을까요??
그리고 public으로 한 이유도 궁금합니다!

2022-08-26 07:35 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    var strawberry: Int = 10
Fruit라는 과일 타입을 만들어 두고서 이 곳에서도 과일의 종류를 한번 더 표현하였네요!!
만들어 놓은 Fruit타입을 활용해보세요!!
코드만 봐서는 각 과일에 대한 10이라는 값이 무엇을 의미하는지도 잘 모르겠습니다 🤔
Hint. 열거형을 배열처럼 관리하는 방법이 있습니다!

2022-08-26 07:35 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func changeStock(strawberry: Int = 0, banana: Int = 0, pineapple: Int = 0, kiwi: Int = 0, mango: Int = 0) {
매개변수에 기본값을 주는것과 안주는 것의 차이점은 무엇인가요??
내부적인 구현은 Fruit 타입을 조금 더 활용해보고 수정이 필요하다면 시도해보세요!

2022-08-26 07:35 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
>  struct JuiceMaker {
JuiceMaker타입은 왜 구조체로 선언되어있을까요?? 😲

2022-08-26 07:35 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func makeJuiceOf(_ juiceType: FruitJuice) {
Of와 같은 전치사는 전달 인자를 통해 표현해주어도 좋을 것 같아요 😀

2022-08-26 07:35 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        case .strawberry:
재고의 변경은 쥬스를 재조할 때만 이루어질까요??
도소매에서 과일 재고를 더 가져오거나 상한 과일을 버리거나 과일만 판매할 경우는요??
위에서 전달한 FruitJuice 타입을 조금 더 고민해보고 레시피는 어떻게 관리할지
재고 수정(증가 또는 감소)에 대한 부분은 어떻게 관리하면 좋을지 생각해보고
쥬스를 만드는 함수를 완성해보세요 !!

2022-08-26 07:35 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func canMakeJuiceOf(juiceType: FruitJuice) -> Bool {
이 부분도 네이밍을 고려해보세요! (of)

2022-08-26 07:35 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        default:
이 곳의 default 값은 `Default will never be executed`이라는 경고를 나타내고 있어요
무엇을 뜻할까요?
또한 default는 어떠한 경우에 사용될까요?

2022-08-29 00:46 UTC, Y00ujin commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +enum FruitJuice: String {
사용자의 입력을 S, B와 같이 주스의 이름을 축약한 형태로 받아서 사용할 목적으로 원시값을 축약하여 작성했어요.
이해하기 어려우니 축약하지 않고 풀어 써야겠어요! 🙇🏻‍♂️

쥬스타입은 FruitJuice 열거형을 말씀하시는 걸까요?

2022-08-29 00:48 UTC, Y00ujin commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +enum Fruit: String {
Class 또는 Struct 에 포함시키는 것을 말씀하시는 걸까요?

Fruit 열거형은 쓰이는 곳이 없는데 실수로 남겨둔 부분이네요..! 😭
제거하도록 하겠습니다!

2022-08-29 00:51 UTC, parkseyoon commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +public class FruitStore {
클래스로 선언한 이유는 클래스의 reference type을 이용하기 위해서 입니다!

public은 접근 제어자를 공부하다가 이렇게 하면 어떨까? 하다가 추가했습니다. 전공자 친구에게 물어보니 public을 굳이 사용하지 않고 final이나 internal을 사용해도 된다고 하더라구요. 조금 더 생각하여 코드에 반영해보겠습니다.

2022-08-29 00:55 UTC, Y00ujin commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    var strawberry: Int = 10
Fruit 열거형을 사용해서 과일의 재고를 표현해보려고 했는데 궁금한 점이 생겼어요!

과일의 재고는 값을 할당할 때에 값을 복사하여 사용하지 않고 하나의 값을 공유하여 사용하게 해야하는데, Enum으로 재고를 표현하면 값 타입이라 원하는 결과가 나오지 않을 거 같아요.

제가 모르는 열거형을 사용하는 다른 방법이 있을까요?

2022-08-29 00:57 UTC, Y00ujin commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func changeStock(strawberry: Int = 0, banana: Int = 0, pineapple: Int = 0, kiwi: Int = 0, mango: Int = 0) {
함수를 호출할 때에 기본 값을 설정해준 매개변수는 인자값을 필수로 전달하지 않아도 오류가 발생하지 않아요.
재고를 변경하고싶은 과일만 함수 호출 시에 넘겨주고 싶어서 기본 값을 모두 설정해두었어요!

2022-08-29 00:58 UTC, Y00ujin commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func makeJuiceOf(_ juiceType: FruitJuice) {
오! 좋네요 ㅎㅎㅎ 👍🏻

2022-08-29 00:59 UTC, Y00ujin commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func canMakeJuiceOf(juiceType: FruitJuice) -> Bool {
네!

2022-08-29 01:41 UTC, Y00ujin commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        default:
아! juiceType에 해당하는 case가 모두 존재해서 default로 빠질 경우가 없어서 발생하는 오류군요!

코드 수정했어요 🔥

2022-08-29 01:42 UTC, Y00ujin commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
>  struct JuiceMaker {
레퍼런스 타입의 특징인 값을 복사하지 않고 공유하여 사용하는 액션을 사용하지 않기 때문에 Struct를 사용한 것 같습니다!

2022-08-29 01:47 UTC, Y00ujin commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        case .strawberry:
도소매에서 과일 재고를 더 가져오거나 상한 과일을 버리거나 과일만 판매하는 기능이 있나요?
재고 수정에 대한 부분을 어떻게 변경할 지 모르겠어요 🥲

어떤 부분이 부족한 건지 한번 더 설명해주실 수 있을까요?

2022-08-29 02:44 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        case .strawberry:
특정 타입에서 과일의 재고를 증가하는 행위와 감소하는 행위를 만들어두고
쥬스를 재조하는 과정에서 감소하는 행위를 불러다 쓰고
재고가 부족하여 재고를 더 추가해야할때 증가하는 행위를 가져다 쓰는 방식을 생각했습니다!

2022-08-29 02:53 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    var strawberry: Int = 10
FruitStore타입 내부에서 Fruit타입을 가지게 해두고 `CaseIterable`이라는 것을 조사해보고 활용해보세요!
클래스(FruitStore)에서 열거형(Fruit) 인스턴스를 만들어 케이스들에 값들을 넣어 사용하면 어떤 결과가 나올까요?

2022-08-29 02:54 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +public class FruitStore {
넵 좋아요! internal을 디폴트값이기 때문에 아무것도 작성하지 않았을때의 상태이기도 합니다!
final class는 어떤 장점이 있을까요?

2022-08-29 02:54 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +enum Fruit: String {
중첩타입을 활용해봐도 좋을 것 같아요~~

2022-08-30 05:37 UTC, parkseyoon commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +public class FruitStore {
final class는 오버라이딩 하지 않아 성능 향상에 도움을 줍니다 ^__^

2022-08-30 05:48 UTC, Y00ujin commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    var strawberry: Int = 10
FruitStore 타입 내부에 Fruit 타입을 생성했어요. 그런데 케이스들에 넣는 값은 원시값을 말씀하시는 걸까요?
```Swift
    enum Fruit: CaseIterable {
        case strawberry, banana, pineapple, kiwi, mango
    }
```

2022-08-30 05:50 UTC, Y00ujin commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        case .strawberry:
과일의 재고를 증가하는 함수와 과일의 재고를 감소하는 함수를 따로 생성하라는 말씀이실까요?? 😮

2022-08-30 06:24 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        case .strawberry:
넵 맞습니다!!

2022-08-30 06:31 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    var strawberry: Int = 10
각각의 과일들에게 초기값을 어떻게 줄수있을까요?
[참고문서](https://developer.apple.com/documentation/swift/caseiterable)를 통해 구현해볼 수 있을까요?
allcases를 활용해보면 좋을 것같아요!

2022-08-30 07:06 UTC, Y00ujin commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +enum Fruit: String {
네! FruitStore class 내부로 옮겼어요!

2022-08-30 08:39 UTC, Y00ujin commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        case .strawberry:
넵! 수정해보겠습니다!!

2022-08-31 00:50 UTC, Y00ujin commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    var strawberry: Int = 10
각각의 과일들은 case들을 말씀하시는 걸까요? 아니면 새로 선언한 각각의 과일 변수를 말씀하시는 걸까요 ?? 🥲

2022-08-31 05:24 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +enum FruitJuice: String {
네 맞습니다! Juice타입 내부에 이름과 레시피를 연산프로퍼티를 활용하여 완성해보세요 !😀
Hint. switch-case

2022-08-31 06:02 UTC, Y00ujin commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +enum FruitJuice: String {
```Swift
    enum FruitJuice: CaseIterable {
        case strawberry, banana, pineapple, kiwi, mango, strawberryBanana, mangoKiwi
        
        var juiceName: String {
            switch self {
            case .strawberry:
                return "딸기"
            case .banana:
                return "바나나"
            case .pineapple:
                return "파인애플"
            case .kiwi:
                return "키위"
            case .mango:
                return "망고"
            case .strawberryBanana:
                return "딸바"
            case .mangoKiwi:
                return "망키"
            }
        }
        
        var juiceRecipe: [Int] {
            switch self {
            case .strawberry:
                return [16]
            case .banana:
                return [2]
            case .pineapple:
                return [2]
            case .kiwi:
                return [3]
            case .mango:
                return [3]
            case .strawberryBanana:
                return [10, 1]
            case .mangoKiwi:
                return [2, 1]
            }
        }
    }
```

이렇게 구현하는게 맞을까요?

2022-08-31 07:03 UTC, Y00ujin commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    var strawberry: Int = 10
아래와 같이 과일 변수에 초깃값을 넣어주는 게 맞을까요 ?? ㅜㅜ

```Swift
    var strawberry = Int()
    var banana = Int()
    var pineapple = Int()
    var kiwi = Int()
    var mango = Int()

    enum Fruit: CaseIterable {
        case strawberry, banana, pineapple, kiwi, mango
        
        var fruitStockInitialValue: Int {
            switch self {
            case .strawberry:
                return 10
            case .banana:
                return 10
            case .pineapple:
                return 10
            case .kiwi:
                return 10
            case .mango:
                return 10
            }
        }
    }
    

    func applyFruitStockInitialValue() {
        for val in Fruit.allCases {
            print(val.fruitStockInitialValue)
            // 여기서 각각의 과일 변수에 10이라는 초깃값을 넣어줌
        }
    }
```

2022-09-02 08:08 UTC, jaemuYeo requested changes
이르 푸들 코멘트 반영하느라 고생많았습니다 👏☺️
코드가 많이 개선된거 같아요!!
아쉬운 부분들이 몇 개 있어서 간단히 코멘트 남기고
두분이 확인후 재요청보내면 머지진행하겠습니다!

2022-09-02 08:08 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    enum FruitJuice: CaseIterable {
쥬스는 과일가게가 가지고있지않고
쥬스메이커가 쥬스를 가지고 있는것은 어떨까요?
네이밍도 Juice라고만 간단히 해주어도 좋을 것같아요!
(혹시 나중에 과일쥬스 말고 다른 쥬스가 추가된다면,,?!)

이곳에서 caseIterable을 채택한건 어디에서 쓰이죠?

2022-09-02 08:08 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        var juiceName: String {
이곳의 네이밍도 쥬스라는 타입안에 있기때문에 간단디 name으로만 해주면 될 것같습니다!

2022-09-02 08:08 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +            switch self {
switch-case를 잘 활용해주었네요 💯

2022-09-02 08:08 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        var juiceRecipe: [Int] {
여기도 recipe라는 간단한 네이밍을 하면 좋을 것같아요 😀

딕셔너리를 활용해 레시피를 아래처럼 표현해보면 어떨까요??
어떤 과일에 몇개가 필요한지 읽기 편하지 않나유ㅎㅎ
```swift
var juiceRecipe: [Fruit: Int] {
    switch self {
    case .strawberry:
        return [.strawberry: 16]
    case .banana:
        return [.banana: 2]
    case .strawberryBanana:
        return [.strawberry: 10, .banana: 1]
    case .mangoKiwi:
        return [.mango: 2, .kiwi: 1]
    }
}
```

2022-09-02 08:08 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    var fruits = [Fruit : Int]()
이 변수는 외부에서도 수정이 가능할까요??

2022-09-02 08:08 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func addStock(fruit : Fruit, stock addedStock: Int) {
잘 구현해주었어요!!
매개변수는 그냥 stock으로 해주어도 될 거같아요 ㅎㅎ
띄어쓰기 실수도 있네요!
저는 보통 guard let을 많이 쓰는 편이예요
if let과 guard let의 차이점 중 guard는 early exit라는 점인데요! 어떤 이점이 있을까요??

```swift
func add(fruit: Fruit, stock: Int) {
    guard var fruits = fruits[fruit] else { return }
    fruits += stock
}

```

2022-09-02 08:08 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func decreaseStock(fruit : Fruit, stock decreasedStock: Int) {
이 메서드의 네이밍도 `decrease(fruits: Fruit, stock)` 정도로도 포현될 것같아요!

2022-09-02 08:08 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    init() {
초기값 10이라는 것을 여기서 주면 좋을까요?
외부에서 FruitStore인스턴스를 생성할때 주면 좋을까요?
만약 인스턴스 생성시 주고싶다면 이렇게 해볼 수 있을 거같아요!
```swift
init(initialStock: Int) {
    for fruit in Fruit.allCases {
         fruits[fruit] = Stock
    }
}
```
이니셜라이징할때 init메서드의 위치도 한번 고민해보세요! (실행시 문제가 되는건 아닙니다!)

2022-09-02 08:08 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func makeJuice(of juiceType: FruitStore.FruitJuice) {
위에서 전달했던 Juice타입의 recipe형식을 사용하면
잘 매칭시켜서 decrease호출만으로 내부를 한줄내지 두줄로 구현할 수 있을 거같아요 🙂

로직상 문제는 없어서 수정이 필요하다면 리팩토링 해보세요💪

2022-09-02 08:08 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func canMakeJuice(of juiceType: FruitStore.FruitJuice) -> Bool {
이 메서드도 makeJuice와 마찬가지로 `반복`적인 일들을 많이 하는군요!
충분히 줄여볼 수 있을 거같아요!
로직상 문제는 없어서 수정이 필요하다면 리팩토링 해보세요💪

2022-12-22 07:55 UTC, closed without merging