쥬스자판기 [STEP 1] Mond, Rarla
tasty-code/ios-juice-maker pull request #50
Opened 2023-09-13 06:55 UTC by rarlala

@forestjae
안녕하세요~! 숲재!
리뷰를 요청하게 된 @rarla @mond입니다 :)
잘 부탁드립니다~!

## Step1 구현 요구사항
- FruitStore.swift 파일에 과일의 재고를 관리하는 FruitStore 타입을 정의합니다.
- FruitStore는 다음의 조건을 충족해야 합니다.
    - FruitStore가 관리하는 과일의 종류 : 딸기, 바나나, 파인애플, 키위, 망고
    - 각 과일의 초기 재고 : 10개
    - 각 과일의 수량 n개를 변경하는 기능이 있습니다.
    - 이 외에 더 필요한 기능, 특성, 타입이 있으면 자유롭게 추가해도 좋습니다.
- JuiceMaker.swift 파일에 다음의 조건을 충족하는 JuiceMaker 타입을 정의합니다.
    - FruitStore의 과일을 사용해 과일쥬스를 제조합니다.
        - 딸기쥬스 : 딸기 16개 소모
        - 바나나쥬스 : 바나나 2개 소모
        - 키위쥬스 : 키위 3개 소모
        - 파인애플 쥬스 : 파인애플 2개 소모
        - 딸바쥬스 : 딸기 10개 + 바나나 1개 소모
        - 망고 쥬스 : 망고 3개 소모
        - 망고키위 쥬스 : 망고 2개 + 키위 1개 소모
    - 과일의 재고가 부족하면 과일쥬스를 제조할 수 없습니다.
    - JuiceMaker는 FruitStore를 소유하고 있습니다.
    - 이 외에 더 필요한 기능, 특성, 타입이 있으면 자유롭게 추가해도 좋습니다.
- (선택사항) 필요한 경우 오류처리(throw, try-catch)를 구현합니다.
<br><br>

## 코드를 작성하며 고민한 점
- 우선 이번 프로젝트 진행을 하며 제공된 참고 해야 할 문서의 개념을 최대한 활용해 작업하려 노력했습니다.
    - Initialization
        - 해당 앱을 더 발전시켜 추가적으로 메서드를 생성하는 부분을 고려해봤을 때, 초기값을 10개가 아닌 n개의 임의의 값으로 사용자가 변경할 수 있는 메서드를 만들 수도 있겠다는 의견이 나왔습니다. 그래서 저장소 내 과일 재고를 10개로 초기화하는 부분에서 10개라는 값을 상수로 뺀 후 지정생성자를 선언하여 10개로 초기화시켜주었습니다.
    - Access Control
        - `FruitStore` 내 `inventory`와 `initValue`는 private으로 선언해 외부에서 접근하지 못하도록 했습니다.
    - Nested Types
        - `FruitStore` 내 `Fruit` 타입을 정의했습니다.
        - `JuiceMaker` 내 `Juice` 타입을 정의했습니다.
    - Error Handling
        - `JuiceMaker` 내 `makeJuice` 메서드에서 오류를 체크 후 print 하도록 처리했습니다.
- `JuiceMaker는 FruitStore를 소유하고 있습니다.` 라는 구현 요구사항을 충족시키기 위한 방법을 고민했습니다. `JuiceMaker` 내 `FruitStore` 인스턴스를 생성해 `JuiceMaker`의 인스턴스가 생성될 때 마다 `FruitStore`의 인스턴스 또한 재생성 되는 것을 막기 위해 `FruitStore` Class를 Singleton 패턴을 사용해 구현해 단일 인스턴스만 생성되도록 했습니다.
- 함수가 하나의 작업만 하도록 분리해 작업했습니다.
- Error 타입을 정의하고, throws function을 만들어 Error를 throw 하도록 만들었습니다. throws function을 사용하는 부분에는 do-catch를 사용하여 Error에 맞는 출력을 하도록 했습니다.
<br><br>

## 해결되지 않은 점
- do-catch를 해서 오류를 잡을 때, 정의된 오류에 맞게 catch를 작성한 후에도 switch의 default 문을 적듯이 catch를 적어줘야하는건지 아니면 해당 코드에 빠진 부분이 있어 해당을 적어줘야 하는지 궁금합니다!

<br><br>

## 조언을 얻고 싶은 부분
- Error 처리를 하기 위해 Error Type을 생성할 때 Model에 파일을 만들어 사용했습니다. Error Type 선언은 Error Type을 사용할 곳에 선언 후 사용하는지 아니면 다른 관리 방식이 있을지 궁금합니다!
- `JuiceMaker는 FruitStore를 소유하고 있습니다.` 라는 구현 요구사항을 충족시키기 위한 방법으로 Singleton 패턴을 사용한 부분에 대해 의견을 여쭙고 싶습니다. 다른 더 좋은 방법이 있었을지 만약 @forest가 구현하신다면 어떤 방식으로 구현하셨을지 궁금합니다!
- `JuiceMaker`의 `makeJuice` 함수를 좀 더 간편하게 작성할 수 있을 거 같은데 저희가 작성한 것보다 다른 더 좋은 방법이 있을지 궁금합니다.

2023-09-13 15:24 UTC, forestjae commented on JuiceMaker/JuiceMaker/Model/Error.swift
> +//  Error.swift
놓치기 쉬운 부분인데, 이런 주석 부분도 신경써서 바꿔주시면 좋을 것 같습니다 :)

2023-09-14 00:44 UTC, rarlala commented on JuiceMaker/JuiceMaker/Model/Error.swift
> +//  Error.swift
리뷰 감사합니다! 파일 생성 시 자동으로 생성되는 주석이라 크게 신경쓰지 못한 부분인데요! 혹시 어떤 부분을 신경써야하는지 잘 몰라서 혹시 조금 더 자세히 알려주실 수 있으실까요?

2023-09-14 02:36 UTC, forestjae commented
랄라, 몬드 고생 많으셨습니다!

전체적으로 잘 작성해주셨어요. 코멘트 확인 부탁드려요!

> ## 해결되지 않은 점
> * do-catch를 해서 오류를 잡을 때, 정의된 오류에 맞게 catch를 작성한 후에도 switch의 default 문을 적듯이 catch를 적어줘야하는건지 아니면 해당 코드에 빠진 부분이 있어 해당을 적어줘야 하는지 궁금합니다!

지금 작성해주신대로 하셔도 되구요, catch let error 부분에서 타입 캐스팅을 사용하여 블럭 안에서 분기하는 방법도 있습니다. 정의한 모든 에러를 catch로 처리해 주실 필요는 없고 해당 코드에서 필요한 처리만 해주시면 됩니다.

> ## 조언을 얻고 싶은 부분
> * Error 처리를 하기 위해 Error Type을 생성할 때 Model에 파일을 만들어 사용했습니다. Error Type 선언은 Error Type을 사용할 곳에 선언 후 사용하는지 아니면 다른 관리 방식이 있을지 궁금합니다!

이건 정말 여러가지 방법이 있어서 이게 정답이다 라고 말씀 드릴 수는 없을 것 같아요. 일반적으로는 Model에 속한게 맞습니다. Model 내부에서 Error로 한번 더 폴더링을 해서 그 안에 모아두거나, Error 타입이 연관된 다른 모델 타입들과 같이 두는 방법이 보편적인 것 같습니다.

> * `JuiceMaker는 FruitStore를 소유하고 있습니다.` 라는 구현 요구사항을 충족시키기 위한 방법으로 Singleton 패턴을 사용한 부분에 대해 의견을 여쭙고 싶습니다. 다른 더 좋은 방법이 있었을지 만약 @forest가 구현하신다면 어떤 방식으로 구현하셨을지 궁금합니다!

싱글턴 패턴을 사용하신 이유가 있을까요? "소유하고 있다"에 대해서 랄라랑 몬드가 이해하신 뜻이 궁금합니다. 싱글턴 패턴이 어느 상황에서 사용되는지 공부를 좀 더 해보시고 고민해보세요!

> * `JuiceMaker`의 `makeJuice` 함수를 좀 더 간편하게 작성할 수 있을 거 같은데 저희가 작성한 것보다 다른 더 좋은 방법이 있을지 궁금합니다.

메서드 내부에 다른 private 메서드를 사용해서 분리해보는건 어떨까요? 그리고 현재 store.subtract 메서드를 그대로 사용해주시고 있는데, 이 부분을 개선해보시면 좋을 것 같습니다. "레시피" 라는것은 몇몇 과일들의 필요 개수로 이루어져 있기 때문에 딕셔너리로 정의 할 수 있다고 생각합니다. 단순히 쥬스를 만들기 위한 필요 과일 숫자를 일일이 넣어주는게 아니라, 특정 쥬스일때의 레시피를 정의(쥬스 enum에서) 해놓고 메서드에 쥬스만 파라미터로 넘기게 되면 메서드 내부에서 쥬스에 필요한 과일숫자를 알아내어서 store.subtract를 사용하는 방법이 있을 것 같아요.

2023-09-15 00:39 UTC, rarlala commented
> 
> > * `JuiceMaker는 FruitStore를 소유하고 있습니다.` 라는 구현 요구사항을 충족시키기 위한 방법으로 Singleton 패턴을 사용한 부분에 대해 의견을 여쭙고 싶습니다. 다른 더 좋은 방법이 있었을지 만약 @forest가 구현하신다면 어떤 방식으로 구현하셨을지 궁금합니다!
> 
> 싱글턴 패턴을 사용하신 이유가 있을까요? "소유하고 있다"에 대해서 랄라랑 몬드가 이해하신 뜻이 궁금합니다. 싱글턴 패턴이 어느 상황에서 사용되는지 공부를 좀 더 해보시고 고민해보세요!
> 

답변 감사합니다! 우선 싱글턴 패턴을 사용한 이유는 아래와 같습니다 :)

소유하고 있다는 개념을 저희는 쥬스를 만들때는 FruitStore가 반드시 필요하기 때문에, JuiceMaker 내부에 FruitStore를 가지고 있어야 한다라고 이해했습니다.

FruitStore는 Class 타입으로 정의되어 있으므로 JuiceMaker 내부에 FruitStore를 가지기 위해서는 JuiceMaker 내 특정 상수를 선언하고 FruitStore 인스턴스를 생성해 가지고 있어야한다고 생각했습니다. 

단, JuiceMaker 내 FruitStore를 단순히 인스턴스로 생성하는 방식으로 선언한다면, JuiceMaker 인스턴스를 생성하는 상황에서 반복적으로 FruitStore의 인스턴스가 생성되고 하나의 저장소에서 관리 되지 않으므로 적절하지 않다고 판단했습니다.

따라서 싱글턴 패턴으로 FruitStore를 선언하는 방식으로 위 문제를 해결하고자 했습니다. 싱글턴 패턴으로 구현한다면 FruitStore의 인스턴스는 단 하나만 생성되기 때문에 JuiceMaker의 인스턴스가 여러번 생성되더라도 FruitStore는 단 하나의 저장소에서만 관리되도록 처리할 수 있다고 생각했기 때문입니다.

조언 주신대로 싱글턴 패턴을 사용하는 경우를 조금 더 찾아보니 FileManager, UserDefaults, UIApplication, UIAccelerometer과 같이 한가지의 방식으로만 접근이 가능하도록 제한하고자 하는 경우 사용한다고 이해했습니다!

2023-09-15 01:29 UTC, forestjae requested changes

2023-09-15 02:05 UTC, rarlala commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +  private let initValue = 10
[091a462](https://github.com/tasty-code/ios-juice-maker/pull/50/commits/091a462d3f63666ed58360745d767099f409490a) 에서 수정했습니다!

2023-09-15 02:05 UTC, yeji1008 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    let currentNum = getNum(fruitName: fruitName)
보내주신 링크 참고해서 변경하였습니다.

2023-09-15 02:06 UTC, yeji1008 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +  private var inventory = [Fruit.strawberry: 0, Fruit.pineapple: 0, Fruit.banana: 0, Fruit.kiwi: 0, Fruit.mango: 0]
감사합니다!

2023-09-15 02:06 UTC, rarlala commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +  }
[091a462](https://github.com/tasty-code/ios-juice-maker/pull/50/commits/091a462d3f63666ed58360745d767099f409490a) 안그래도 코드를 수정하며 불필요해 반환값 삭제했습니다!

2023-09-15 02:51 UTC, rarlala commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +  static let shared = FruitStore()
[10d8457](https://github.com/tasty-code/ios-juice-maker/pull/50/commits/10d8457f1b3ecefaa77b3008350f39c1bb90beac) 여기에서 수정했습니다!

싱글턴 패턴을 사용하는 경우에 init 생성자도 private으로 지정해줘야한다는 부분을 잘 인지하지 못하고 사용했던 것 같습니다!
덕분에 알게되었습니다 :) 감사합니다!

2023-09-15 02:55 UTC, yeji1008 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +      }
[091a462](https://github.com/tasty-code/ios-juice-maker/pull/50/commits/091a462d3f63666ed58360745d767099f409490a) 메서드를 private로 분리하여 사용하는 것은 어떻냐고 이야기해주셔서 checkAvailableJuice와 makeJuice로 메서드를 각각 재고 확인으로 음료 제작 가능 여부와 음료를 제작하는 코드로 분리하였습니다. 또한 enum 안에 dictionary를 넣어 반복되는 로직을 없앴습니다.

2023-09-15 02:56 UTC, rarlala commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +  }
중첩 타입을 사용해보자는 생각으로 FruitStore 내에서만 Fruit이 필요할 것이라고 생각되어 nested type으로 선언했습니다!
다만 리팩토링 하는 과정에서 FruitStore 내부 메서드를 불러오는 부분에서 Fruit 타입이 외부에서 필요해지는 경우가 생겨 외부 파일로 분리했습니다!

2023-09-15 03:05 UTC, forestjae approved these changes

2023-09-15 03:10 UTC, rarlala commented on JuiceMaker/JuiceMaker/Model/Error.swift
> +//  Error.swift
디스코드에 답변해주심 :)
파일명과 주석이 다름으로 인지하셨음! 하지만 Error라는 프로토콜이 Swift에 이미 존재하기 때문에 중복되는 네이밍은 피하시는게 좋을 것 같다는 조언을 해주셔서 STEP2에 네이밍 변경 진행하기로 함!

2023-09-19 02:38 UTC, merged