쥬스 자판기 [STEP 1] Howard, Dora
tasty-code/ios-juice-maker pull request #52
Opened 2023-09-13 07:12 UTC by KSK9820

> 리뷰어: @jungseungyeo
> Haward @JEON-Sungsu, Dora @KSK9820
 

<br/>

## 결과 화면

<img width="692" alt="스크린샷 2023-09-13 오후 4 09 44" src="https://github.com/tasty-code/ios-juice-maker/assets/68066104/3e00bea1-c78e-4db4-b814-692f4b7823ba">

<br/>

## [STEP1] 요구사항 체크리스트

- [x]  FruitStore.swift 파일에 **과일의 재고를 관리하는 FruitStore 타입**을 정의합니다.
- [x]  FruitStore는 다음의 조건을 충족해야 합니다.
    - FruitStore가 관리하는 과일의 종류 : 딸기, 바나나, 파인애플, 키위, 망고
    - 각 과일의 초기 재고 : 10개
    - 각 과일의 수량 n개를 변경하는 기능이 있습니다.
    - 이 외에 더 필요한 기능, 특성, 타입이 있으면 자유롭게 추가해도 좋습니다.
    - JuiceMaker.swift 파일에 다음의 조건을 충족하는 JuiceMaker 타입을 정의합니다.
    - FruitStore의 과일을 사용해 과일쥬스를 제조합니다.
        - 딸기쥬스 : 딸기 16개 소모
        - 바나나쥬스 : 바나나 2개 소모
        - 키위쥬스 : 키위 3개 소모
        - 파인애플 쥬스 : 파인애플 2개 소모
        - 딸바쥬스 : 딸기 10개 + 바나나 1개 소모
        - 망고 쥬스 : 망고 3개 소모
        - 망고키위 쥬스 : 망고 2개 + 키위 1개 소모
    - 과일의 재고가 부족하면 과일쥬스를 제조할 수 없습니다.
    - JuiceMaker는 FruitStore를 소유하고 있습니다.
    - 이 외에 더 필요한 기능, 특성, 타입이 있으면 자유롭게 추가해도 좋습니다.
- [x]  (선택사항) 필요한 경우 오류처리(`throw`, `try-catch`)를 구현합니다.

<br/>

## 파일 구조

- Model
    - FruitStore: 과일의 재고를 관리하는 FruitStore 타입을 정의 및 수량 변경
    - FruitStock: FruitStore의 프로퍼티로 사용하기 위한 sturct 타입 정의
    - JuiceMaker: 사용자의 요청을 입력받고, 주문 유효성 검증
    - Juice : 쥬스 이름을 정리한 열거형 타입 정의
    - Error: 에러 타입을 커스텀해서 리턴

<br/>

## 코드 설명

1. FruitStore.swift
- FruitStore 클래스 객체를 Singleton으로 만들어 타입의 캡슐화를 추구하였습니다.
    

      class FruitStore {
      static let shared = FruitStore(
          strawberry: FruitStock(singleConsumption: 16, combineConsumption: 10),
          banana: FruitStock(singleConsumption: 2, combineConsumption: 1),
          pineapple: FruitStock(singleConsumption: 2),
          kiwi: FruitStock(singleConsumption: 3, combineConsumption: 1),
          mango: FruitStock(singleConsumption: 3, combineConsumption: 2)
      )

      var strawberry: FruitStock
      var banana: FruitStock
      var pineapple: FruitStock
      var kiwi: FruitStock
      var mango: FruitStock

      private init(strawberry: FruitStock, banana: FruitStock, pineapple: FruitStock, kiwi: FruitStock, mango: FruitStock) {
          self.strawberry = strawberry
          self.banana = banana
          self.pineapple = pineapple
          self.kiwi = kiwi
          self.mango = mango
      }
  ...

    

    
2. JuiceMaker.swift
- soldOutChecker는 FruitStore의 재고를 파악하여, 사용자의 주문이 처리될 수 있는지 여부를 확인하는 함수입니다.
    - `fruitStorage.strawberry`의 무수한 사용이 가독성을 해치기 때문에 `strawberry` 변수로 만들어 사용하여 가독성을 추구하였습니다.
    - 혹시 모를 입력 오류나, 주문받은 음료를 제작할 재고가 없을 경우에 대한 처리를 위해서 `throw`를 사용하였습니다.
    - private 키워드를 사용하여 캡슐화 하였습니다.
    
    ```swift
    private func soldOutChecker(_ menu: Juice) throws -> Juice {
            let strawberry = fruitStorage.strawberry
            let banana = fruitStorage.banana
            let kiwi = fruitStorage.kiwi
            let pineapple = fruitStorage.pineapple
            let mango = fruitStorage.mango
    
            switch menu {
            case .strawberryJuice:
                guard strawberry.currentStock >= strawberry.singleConsumption else {
                    throw ErrorPrinter.stockInsufficient(["딸기"])
                }
                return .strawberryJuice
    
    ```
    
- makeJuice 는 외부에서 사용할 수 있는 함수입니다. `soldOutChecker`의 에러 처리를 위해 do try-catch를 사용하였습니다.
    
    ```swift
    func makeJuice(_ order: Juice) {
            do {
                let getOrder = try soldOutChecker(order)
                fruitStorage.stockCalculator(getOrder)
            } catch {
                print(error)
            }
        }
    
    ```
    

<br/>

## 고려하려 노력한점

- 함수의 역할에 맞는 naming을 하기 위해 노력 하였습니다.
- 잘 알지 못하는 개념이나 사용법은 지양하고, 반드시 필요한 경우 학습 이후에 사용하도록 신경썼습니다. (do try-catch)
- 기능별로 함수를 따로따로 분리하도록 노력하였습니다.

<br/>

## 궁금한점

- FruitStore 의 캡슐화를 위해서 private를 만들고, 외부에는 public 함수를 제공해서 접근하는 방법 대신 singleton 패턴을 이용하였는데, 이렇게 해도 캡슐화가 되는게 맞는지 궁금합니다.
- 인스턴스를 초기화 할때, 초기화 설정값이 너무 많아, 코드가 너무 길어져서 가독성을 해치는것 같다고 느껴졌습니다. 혹시 초기화를 조금 간소화 하거나 다른 좋은 방법이 없을지 궁금합니다.
- 프로젝트 요구사항에, JuiceMaker가 fruitStore를 소유해야한다는 제한사항이 있었습니다.
    1. 소유를 상속개념이라고 이해해서 진행하려 했으나, struct는 class를 상속받을 수 없습니다.
    2. 따라서 저희는 상속 대신 JuiceMaker 에서 fruitStore 인스턴스를 싱글톤 패턴으로 생성하여 구현하였는데 이러한 방법도 소유의 개념이라고 볼 수 있을까요?
- 쥬스를 구분짓기 위해서 switch문을 사용하였고, 그 내부에서 if문을 사용하였습니다. 그렇지만 해당 방법이 if문의 중첩이기 때문에 좋지 않은 방법이라고 생각됩니다. 혹시 더 나은 개선방향이 있다면 알려주시면 감사하겠습니다.
- if문과 비교해서 switch문은 하나의 케이스만 처리하고 통과하기 때문에 switch문을 사용하여 쥬스를 구분짓고, 그에 따른 행동을 정의하였습니다. 다만, 이런 경우 과일이나 새로운 음료의 종류가 추가된다면 모든 함수에 case를 추가해주어야 하기 때문에 유지보수의 어려움이 있을 것으로 예상됩니다. 해당 경우는 보통 어떻게 처리를 더 할 수 있는지 알고싶습니다.

<br/>

## 참고 자료

- https://docs.swift.org/swift-book/documentation/the-swift-programming-language/errorhandling/
- [[[https://yagom.net/courses/swift-basic/lessons/오류처리/](https://yagom.net/courses/swift-basic/lessons/%EC%98%A4%EB%A5%98%EC%B2%98%EB%A6%AC/)](https://yagom.net/courses/swift-basic/lessons/%EC%98%A4%EB%A5%98%EC%B2%98%EB%A6%AC/)]([[https://yagom.net/courses/swift-basic/lessons/오류처리/](https://yagom.net/courses/swift-basic/lessons/%EC%98%A4%EB%A5%98%EC%B2%98%EB%A6%AC/)](https://yagom.net/courses/swift-basic/lessons/%ec%98%a4%eb%a5%98%ec%b2%98%eb%a6%ac/))

2023-09-13 14:41 UTC, jungseungyeo requested changes
FruitStore 의 캡슐화를 위해서 private를 만들고, 외부에는 public 함수를 제공해서 접근하는 방법 대신 singleton 패턴을 이용하였는데, 이렇게 해도 캡슐화가 되는게 맞는지 궁금합니다.

`싱글톤을 쓰면 안됩니다. 은닉화는 외부 객체에서 접근이 안되어서 상태값을 볼 수 없어야합니다. 싱글톤을 오히려 은닉화를 안하는 형태입니다.`

인스턴스를 초기화 할때, 초기화 설정값이 너무 많아, 코드가 너무 길어져서 가독성을 해치는것 같다고 느껴졌습니다. 혹시 초기화를 조금 간소화 하거나 다른 좋은 방법이 없을지 궁금합니다.

`init은 만들어주고 default 함수를 만들어서 외부에서 접근시 쉽게 만들수있습니다. `

프로젝트 요구사항에, JuiceMaker가 fruitStore를 소유해야한다는 제한사항이 있었습니다.
`소유라는것을 상속이 아닌 프로퍼티로 가지고 있는거를 의마합니다. 싱글톤을 제거해주세요.`

쥬스를 구분짓기 위해서 switch문을 사용하였고, 그 내부에서 if문을 사용하였습니다. 그렇지만 해당 방법이 if문의 중첩이기 때문에 좋지 않은 방법이라고 생각됩니다. 혹시 더 나은 개선방향이 있다면 알려주시면 감사하겠습니다.

`역할 분리가 되어야 할 거 같아요. switch로 구분을 하는거 좋지만 조건을 내부에서 더 검사를 하는 모습이 안좋은거라, 조건을 나누고 조건을 더 나누는 형태입니다. 조건을 나누면 거기서 끝나면 될거같아요.`

if문과 비교해서 switch문은 하나의 케이스만 처리하고 통과하기 때문에 switch문을 사용하여 쥬스를 구분짓고, 그에 따른 행동을 정의하였습니다. 다만, 이런 경우 과일이나 새로운 음료의 종류가 추가된다면 모든 함수에 case를 추가해주어야 하기 때문에 유지보수의 어려움이 있을 것으로 예상됩니다. 해당 경우는 보통 어떻게 처리를 더 할 수 있는지 알고싶습니다.

`의존성을 주입하는 형태로 해결은 되지만 이건 지금 step의 목표는 아니예요 그래도 설명을 드리자면 과일이 될수 있는 protocol을 정의하고 역할과 기능을 부여하고, 쥬스를 생성하는거고, 이렇게 하면 하면 유지보수가 가능 합니다. 이건 추상화 개념이 필요하여 step에서는 일단 진행해주세요.`

2023-09-13 14:41 UTC, jungseungyeo commented on JuiceMaker/JuiceMaker/Model/FruitStock.swift
> +    var combineConsumption: Int?
```suggestion
    private(set) var combineConsumption: Int?
```

2023-09-13 14:41 UTC, jungseungyeo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +            guard let strawberryConsumption = strawberry.combineConsumption else{
```suggestion
            guard let strawberryConsumption = strawberry.combineConsumption else {
```

2023-09-13 14:41 UTC, jungseungyeo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +            guard let bananaConsumption = banana.combineConsumption else{
```suggestion
            guard let bananaConsumption = banana.combineConsumption else {
```

2023-09-13 14:41 UTC, jungseungyeo commented on JuiceMaker/JuiceMaker/Model/FruitStock.swift
> +    var combineConsumption: Int?
변수가 왜 3개나 필요하나요?

2023-09-13 14:41 UTC, jungseungyeo commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +            var insufficient: [String] = []
이건 사용하지 않을수도있는데 생성은 무조건 되는거같아요. 개선하면 좋을거같아요.

2023-09-14 08:41 UTC, KSK9820 commented on JuiceMaker/JuiceMaker/Model/ErrorPrinter.swift
> +            if fruit.count == 2 {
case .stockInsufficient(let fruit):
case .stockInsufficients(let fruit):

와 같이 case를 분류하여 에러처리를 하였습니다.

2023-09-14 08:42 UTC, KSK9820 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    var mango: FruitStock
FruitStore.swift 내부의 FruitStock 타입 변수들을 모두 private 처리하였습니다.

2023-09-14 08:42 UTC, JEON-Sungsu commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +            var insufficient: [String] = []
해당 부분은 switch 문을 수정하면서, 기존에 switch 문에 있던 if 구문들을 함수로 다 빼면서 개선하였습니다. 

```
private func combineJuiceSoldOutChecker(_ firstFruit: FruitStock, _ secondFruit: FruitStock, _ juice: Juice) throws -> Juice {
        guard let firstConsumption = firstFruit.combineConsumption else {
            throw ErrorPrinter.invalidInput
        }
        guard let secondConsumption = secondFruit.combineConsumption else {
            throw ErrorPrinter.invalidInput
        }
        guard firstFruit.currentStock >= firstConsumption || secondFruit.currentStock >= secondConsumption else {
            throw ErrorPrinter.stockInsufficients([firstFruit.name, secondFruit.name])
        }
        guard firstFruit.currentStock >= firstConsumption else {
            throw ErrorPrinter.stockInsufficient(firstFruit.name)
        }
        guard secondFruit.currentStock >= secondConsumption else {
            throw ErrorPrinter.stockInsufficient(secondFruit.name)
        }
        return juice
    }
```

2023-09-14 08:44 UTC, JEON-Sungsu commented on JuiceMaker/JuiceMaker/Model/FruitStock.swift
> +    var combineConsumption: Int?
이 부분은 저희가 class FruitStore 의 프로퍼티(과일들)에 현재재고, 단품에 필요한 재고, 혼합음료에 필요한 재고를 같이 두어서 꺼내서 사용할때 조금더 편하지 않을까 라는 생각에, 하나로 다 묶어두었습니다. 혹시 더 좋은 방법이 있을까요?

2023-09-14 08:45 UTC, JEON-Sungsu commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +            guard let bananaConsumption = banana.combineConsumption else{
간격 수정 하였습니다.

2023-09-14 08:45 UTC, JEON-Sungsu commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +            guard let strawberryConsumption = strawberry.combineConsumption else{
간격..수정하였습니다..!!

2023-09-14 08:45 UTC, KSK9820 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        let mango = fruitStorage.mango
해당 변수들을 미리 만들지 않고 juiceSoldOutChecker(), combineJuiceSoldOutChecker()를 사용하여 함수의 재사용성을 높이는 방향으로 구현했습니다.

2023-09-14 08:46 UTC, JEON-Sungsu commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    static let shared = FruitStore(
싱글톤은 제거하고, private 키워드를 통해서 은닉화 하는 방법으로 변경하였습니다..!!

2023-09-14 08:46 UTC, KSK9820 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        let mango = fruitStorage.mango
또한 juiceSoldOutChecker(), combineJuiceSoldOutChecker()를 사용하여 함수의 재사용성을 높이는 방향으로 구현했습니다.

2023-09-14 09:47 UTC, KSK9820 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +            let getOrder = try soldOutChecker(order)
저희는 자판기를 생각해 보았을때, 재고가 없다면 애초에 주문이 불가능 하게 되어있어서 주문 자체가 안되도록 막는게 맞지 않을까 생각했습니다.  그치만 린생이 말해주신 부분을 생각해보니, soldOutChecker 함수 혼자서 너무 많은 일을 하는것 같아 분리시키려고 해보니
* 과일에 재고량을 FruitStore 의 stockCalculator 에서 재고량을 확인해서 재고가 없으면 throw 를 하고 재고가 있으면 재고값을 빼주는 역할을 하게 하려고 했는데, 느낌이 조삼모사의 느낌이라서... 이렇게 하는게 맞는지 잘 모르겠어서요. 의도하신 바가 맞는걸까요?

2023-09-14 09:49 UTC, KSK9820 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    var mango: FruitStock
이외에도 showStockList 함수로 private 변수들을 외부에서 접근할 수 있게 하였습니다.

직접적으로 값을 변경시키는 것은 옳다고 생각하지 않아서 stockCalculator 함수를 pirvate 선언하고, changeCurrentStock 함수를 대신 이용하게 하였는데 이 방법도 괜찮은지 궁금합니다.

2023-09-14 09:59 UTC, KSK9820 commented on JuiceMaker/JuiceMaker/Model/FruitStock.swift
> +    var combineConsumption: Int?
추가로 해당 프로퍼티를 의미하는 `name` 도 상수로 추가하였습니다.

2023-09-15 11:08 UTC, jungseungyeo commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +            var insufficient: [String] = []
좋습니다 고생하셨습니다.

2023-09-15 11:10 UTC, jungseungyeo commented on JuiceMaker/JuiceMaker/Model/FruitStock.swift
> +    var combineConsumption: Int?
모델의 역할을 지키지 못하는거 같아요. 
이건 Stock 하나만 존재하거나 Stock과 name만 존재하면 좋을거같아요.

2023-09-15 11:12 UTC, jungseungyeo approved these changes
수고하셨습니다. 다음 스텝 진행 부탁드립니다.

2023-09-18 04:31 UTC, JEON-Sungsu commented
@jungseungyeo 

1. FruitStock.swift → Fruit.swift
    - FruitsStore의 프로퍼티값으로 사용하던 구조체를, enum 열거형으로 변경하였습니다.
2. FruitStore.swift
    - 기존 각각의 과일별로 프로퍼티를 따로 만들고, 구조체를 값으로 할당해주었는데, key값으로 과일을 가져오기 위해서 [Fruit:Int] 딕셔너리로 변경하였습니다.
    - 기존 프로퍼티 제공 함수(showStockList), 음료 주문 성공시 재고수정함수(stockCalculator), 재고 수정에서 값을 변경해주는 함수(stockManager) 가 switch 문으로 작성되었던 부분을, 파라미터만 받아서 동작이 가능하게끔 일반함수로 변경하였습니다.
3. JuiceMaker.swift
    -  현재 재고를 확인하는 과정에서, 여기서는 재고확인만 하고 주문 실패 처리를 FruitStore로 옮겨두었습니다.
4. Juice.swift
    - enum Juice에서 recipe 변수를 따로 만들어서, 쥬스이름을 받아서 필요한 과일의 이름과 개수를 리턴받을 수 있도록 만들었습니다.

2023-09-19 03:02 UTC, jungseungyeo approved these changes

2023-09-19 03:02 UTC, merged