주스 메이커 [Step2] 범, 밤삭
tasty-code/ios-juice-maker pull request #55
Opened 2023-09-18 02:21 UTC by snowy-summer

# [STEP 2] 주스 자판기 화면 연결 & 데이터 연동
@monsteel

안녕하세요. Tony
주스메이커 프로젝트 Step2를 진행하고 PR요청 드립니다.

---
## 추가 기능
1. StoryBoard에서 segue로 view연동
    - prepare
    - 재고 관리 뷰와 데이터 연동을 위해 prepare메소드를 override하여 구현 하였습니다.

3. alert을 통한 뷰의 이동 
    - showingOutOfStockAlert
        - 과일의 재고가 부족할 시 alert을 띄워주는 메소드 입니다.
        -  Error enum을 재사용 하기 위해 JuiceMaker.startOrder의 do catch의 error를 한번 더 throw하여 IBAction으로 do catch로 선언하였습니다.
    - showingCompletedOrderAlert
        - 확인 메시지를 출력합니다.

4. stepper
    - stepper를 조작할 경우 기존의 재고에 1씩 추가 되는 것이 아니라 1,2,3,4... stepper의 값이 추가 되는 방식이였습니다. 기존의 stepper의 값을 더하는 방식을 stepper의 값을 부여하는 방식으로 1씩 변하게 변경하고 0부터 시작하는 stepper의 값을 과일들의 재고로 초기화를 했습니다.

---
## 시도했던 점 && 의문점

1. CustomUILabel, CustomUIStepper
    -  각 VC의 label및 stepper의 프로퍼티마다 초기 값을 넣어주려 할 때, juiceMaker의 인스턴스에 인덱스로 접근하여 할당하는 방식이 좋지 않은 것 같아 각 뷰의 요소들(UILable, UIStepper)을 상속 받는 CustomUILabel 및 CustomStepper 구현 시도를 했습니다.
    - 각 VC의 NestyType으로 만들고, Label과 Stepper의 초기 값으로 juiceMaker의 인스턴스의 접근하여 초기값을 주려 했는데, NestyType에서는 juiceMaker인스턴스에 접근하지 못한다는 컴파일 에러가 발생 했습니다.
    - 해당 돌파구를 못찾고 각기 다른 IBOutlet을 선언하여 초기 값을 할당했습니다.
    - UILabel과 UIStepper를 상속받는 Custom타입을 만드는 저의 접근이 잘못된 것인지 궁금하고 만약 이런 부분에 대해서 어떤식으로 해결해 나가면 좋을지 혹시 조언이나 공부할만한 키워드를 알려주시면 감사드리겠습니다.🙇‍♂️

2. Navigation Controller 2개
    - 기존에 포크해온 파일에 뷰 1개당 Navigation Controller가 1개씩 할당이 되어 있었습니다.
    - juiceMaker랑 연결이 되어있는 navigation controller가 juicemaker 다음에 오는 fruitStore의 화면도 컨트롤을 하는데fruitStore에 navigation controller를 추가로 할당해서 스택을 독립적으로 관리해야 하는 이유를 모르겠습니다.

3. Stepper의 accessbilityLabel
    - 각 Stepper의 구분을 위해 accessbilityLabel을 사용했는데, 이 방식은 VoiceOver사용자와 상호작용을 위해 사용하는 프로퍼티로 알고 있습니다.
    - 그래서 지금 접근 방식이 좋진 않다는 것을 알지만 다른 접근 방식이 있을까요?

2023-09-18 09:14 UTC, Monsteel requested changes
안녕하세요 범, 밤삭 👍 
step2도 수고 많으셨습니다~
UI에 대한 제어들이 들어가고 유저와의 상호작용을 다루는 첫 step이셨네요~ 고생하셨습니다 👍 

이번에도 코드에 대한 리뷰는 코멘트 참고해주시구요,
아래에는 이번 PR에 남겨주신 궁금증에 대한 부분들을 코멘트로 남겼습니다 👍 

아래에는 남겨주신 질문에 대한 추가적인 설명을 부탁드리는 코멘트가 있습니다 !
코드 반영사항과 추가설명 코멘트 남겨주시면 이어서 리뷰 진행할 수 있도록 하겠습니다!

고생하셨습니다!

*******

> **CustomUILabel, CustomUIStepper**
> - 각 VC의 label및 stepper의 프로퍼티마다 초기 값을 넣어주려 할 때, juiceMaker의 인스턴스에 인덱스로 접근하여 할당하는 방식이 좋지 않은 것 같아 각 뷰의 요소들(UILable, UIStepper)을 상속 받는 CustomUILabel 및 CustomStepper 구현 시도를 했습니다.
> - 각 VC의 NestyType으로 만들고, Label과 Stepper의 초기 값으로 juiceMaker의 인스턴스의 접근하여 초기값을 주려 했는데, NestyType에서는 juiceMaker인스턴스에 접근하지 못한다는 컴파일 에러가 발생 했습니다.
> - 해당 돌파구를 못찾고 각기 다른 IBOutlet을 선언하여 초기 값을 할당했습니다.
> - UILabel과 UIStepper를 상속받는 Custom타입을 만드는 저의 접근이 잘못된 것인지 궁금하고 만약 이런 부분에 대해서 어떤식으로 해결해 나가면 좋을지 혹시 조언이나 공부할만한 키워드를 알려주시면 감사드리겠습니다.🙇‍♂️

각 뷰의 요소들(UILable, UIStepper)을 상속 받는 CustomUILabel 및 CustomStepper 구현해서
juiceMaker의 인스턴스에 인덱스로 접근하여 할당하는 구조를 어떻게 개선시킬 수 있는지 이해하지 못했습니다.. 예시와 함께 설명을 부탁드려도 될까요?

제가 CustomUILabel과 CustomStepper를 어떤 방향으로 구현하고자 하셨는지 이해하면, 조금 더 자세한 리뷰를 드릴 수 있을것 같아요.


> **Navigation Controller 2개** 
> 기존에 포크해온 파일에 뷰 1개당 Navigation Controller가 1개씩 할당이 되어 있었습니다.
juiceMaker랑 연결이 되어있는 navigation controller가 juicemaker 다음에 오는 fruitStore의 화면도 컨트롤을 하는데fruitStore에 navigation controller를 추가로 할당해서 스택을 독립적으로 관리해야 하는 이유를 모르겠습니다.

말씀만으로 전해들었을 때, 기존 구조가 Navigation Stack이 중첩해서 관리되는 구조인걸까요? 👀
말씀만으로는 잘 이해가 되지 않아서.. 이 영역도 마찬가지로 UI와 함께 설명해주시면, 자세하게 말씀드릴 수 있을것 같아요.

그리고 기본적으로 제공된 코드의 구조가 효율적이지 못하거나, 불편하다고 생각되시는 부분이 있으시다면 수정하셔서 사용하는 방법도 좋은 방향이라고 생각합니다 👍 

> **Stepper의 accessbilityLabel**
> 각 Stepper의 구분을 위해 accessbilityLabel을 사용했는데, 이 방식은 VoiceOver사용자와 상호작용을 위해 사용하는 프로퍼티로 알고 있습니다.
그래서 지금 접근 방식이 좋진 않다는 것을 알지만 다른 접근 방식이 있을까요?

`accessbilityLabel`의 본래 목적과는 다르지만, 단순히 action이 발생한 view들을 구분하기 위한 값으로 활용하고 계신 부분이 우려스러운 것으로 이해했습니다.

UIView에는, [tag](https://developer.apple.com/documentation/uikit/uiview/1622493-tag) 라는 개념이 있습니다. 해당 키워드가 해당 문제를 해소하는데에 도움이 될 수 있을것 같아요 :)

2023-09-19 01:59 UTC, bamsak commented
저의 질문을 코드로 하면 
```swift
class FruitStoreViewController: UIViewController {
    var fruitStore: FruitStore?
    
    class juiceStepper: UIStepper {
        override var value: Double = Double(fruitStore?.fruitLis[0].stock)
    }
}
```
위의 방식과 비슷한 방법으로 customStepper를 만들어  stepper의 초기값을 넣으려고 했던 방식인데, fruitStore 인스턴스에 접근이 불가능하더라구요. 이 부분에 대한 질문이었습니다!

2023-09-19 01:59 UTC, snowy-summer commented
2. 내비게이션 컨트롤러 2개
<img width="641" alt="스크린샷 2023-09-19 오전 9 20 02" src="https://github.com/tasty-code/ios-juice-maker/assets/118453865/5c442edf-d822-4f1c-a70a-8cc269b9c6ef">
2번뷰에 2번 내비게이션 컨트롤러를 연결해 관리해야하는 이유가 있을까요?


3. accessbilityLabel -> tag

```swift
extension FruitStoreViewController {
    
    private enum StepperTag: Int {
        case strawberryStepperTag = 0
        case bananaStepperTag = 1
        case pineappleStepperTag = 2
        case kiwiStepperTag = 3
        case mangoStepperTag = 4
        
        var fruitName: String {
            switch self {
            case .strawberryStepperTag:
                return "딸기"
            case .bananaStepperTag:
                return "바나나"
            case .pineappleStepperTag:
                return "파인애플"
            case .kiwiStepperTag:
                return "키위"
            case .mangoStepperTag:
                return "망고"
            }
        }
        
    }
``` 
enum으로 각 과일에 해당하는 태그의 값을 rawValue로 지정했습니다.

```swift
@IBAction func fruitStockStepper(_ sender: UIStepper) {
        do {
            guard let stepperTag = StepperTag(rawValue: sender.tag) else { return }
            
            guard let fruitStore = fruitStore else { return }
            
            guard let fruit = fruitStore.fruitList.filter({$0.name == stepperTag.fruitName}).first else { return }
            
    
            try fruitStore.addFruitStock(inputFruit: fruit, count: Int(sender.value))
            
            updateUI()
            
        } catch {
            print("\(error)")
        }
    }
``` 

stepper의 tag값을 가지고와 과일의 이름을 받아오는 방식으로 변경했습니다.

2023-09-19 06:02 UTC, Monsteel commented
@bamsak 밤삭 :)
밤삭이 전해주신 해당 방식은, NestyType으로 선언되어, FruitStoreViewController안에 JuiceStepper가 선언되었는데요,
이 경우 NameSpace는 공유할지 몰라도, 두 class가 Instance를 공유하는 상황은 아니기 때문이에요.

Object와 Instance라는 개념들을 중심으로 해당 구조를 다시한번 살펴봐 주시면, 해당 문제를 해결하는데에 도움이 될 것 같아요 :)

2023-09-19 06:07 UTC, Monsteel commented
@snowy-summer 범 :)
우선 첫번째로 말씀주신 NavigationController가 두개가 사용되는 구조는 실제로 navigationController를 하나로 가지는 구조로 사용되고 있기 때문에, 제가 보기에도 불필요해 보이는데요!

범이 생각하셨을 때 불필요하다고 생각되시면 제거해도 괜찮을것 같습니다 👍

그리고 두번째로 남겨주신 부분 역시, tag로 수정하게 되면서 전체적으로 구조가 안정되어 보이네요 👍  고생하셨습니다.

2023-09-19 06:32 UTC, Monsteel commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        }
이 영역에서 Fruit를 표현하기 위해 Fruit struct의 instance를 생성해주신 이유가 있나요?
단순히 Name을 감싸고 있는 형태이고, stock도 사용되지 않아서 불필요한 값 생성같습니다.

```swift
struct Fruit: Hashable {
  var name: String
  var stock: Int = 10
}
```

2023-09-19 06:56 UTC, snowy-summer commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        }
Fruit Struct의 instance말고 String으로 변경했습니다.

2023-09-19 06:57 UTC, Monsteel approved these changes
범, 밤삭 :) 수고하셨습니다!

2023-09-19 06:58 UTC, merged