Step2
tasty-code/ios-juice-maker pull request #56
Opened 2023-09-18 02:39 UTC by newJunsung

## 리뷰어

@forestjae

🚨**주의:** 의욕이 앞선 나머지, STEP 2의 요구사항 그 이상을 진행하였습니다. 아마도 STEP 3(아직 공개되지 않음)를 어느정도 한 것으로 추정됩니다.

---

## 파일구조

- 추가된 부분은 **볼드처리** 하였습니다.
- JuiceMake
    - Controller
        - **JuiceMenuViewController**
        - **FruitInvetoryViewController**
    - Model
        - FruitStore
        - FruitType
        - JuiceMaker
        - JuiceMakerException
        - JuiceType
    - View

---

## 변경사항

### 1. 과일 재고를 각 과일의 `Int` 타입이 아닌 `Dictionary` 타입으로 통일한 이유

- 기존의 코드에서는 과일의 재고를 각각 `Int`로 선언하여 관리하였습니다. 이 과정에서 `switch`로 과일의 재고를 업데이트할 경우, 해당 과일의 재고를 직접 접근해야하는 번거로움이 있었습니다.
- 따라서, 과일들에 해당되는 변수들을 `Dictionary`로 한 번에 묶어 변수의 값 관리를 편리하게 했습니다. `Dictionary`로 바꾸면서 `FruitStored.swift` 파일 등의 함수들도 모두 리팩토링을 마쳤습니다.

- 기존 코드

```swift
// FruitStore.swift
private(set) var strawberry: Int
private(set) var banana: Int
private(set) var pineapple: Int
private(set) var mango: Int
private(set) var kiwi: Int
```

```swift
// JuiceMenuViewController.swift
switch fruitType {
case .strawberry:
	strawberryCountLabel.text = "\(FruitStore.shared.strawberry)"
case .banana:
	bananaCountLabel.text = "\(FruitStore.shared.banana)"
case .mango:
	mangoCountLabel.text = "\(FruitStore.shared.mango)"
case .pineapple:
	pineappleCountLabel.text = "\(FruitStore.shared.pineapple)"
case .kiwi:
	kiwiCountLabel.text = "\(FruitStore.shared.kiwi)"
}
```

- 수정된 코드

```swift
// FruitStore.swift
private(set) var fruitCountList: [FruitType: Int] = [:]
```

```swift
// FruitInventoryViewController.swift
guard let fruitCount = FruitStore.shared.fruitCountList[fruitType] else {
    return
}

switch fruitType {
case .strawberry:
    strawberryCountLabel.text = "\(fruitCount)"
    strawberryStepper.value = Double(fruitCount)
case .banana:
    bananaCountLabel.text = "\(fruitCount)"
    bananaStepper.value = Double(fruitCount)
case .pineapple:
    pineappleCountLabel.text = "\(fruitCount)"
    pineappleStepper.value = Double(fruitCount)
case .kiwi:
    kiwiCountLabel.text = "\(fruitCount)"
    kiwiStepper.value = Double(fruitCount)
case .mango:
    mangoCountLabel.text = "\(fruitCount)"
    mangoStepper.value = Double(fruitCount)
}
```

### 2. `Dictionary` 타입 변경으로 인한 `FruitMaker` 생성자 변경

- `Dictionary`로 타입이 변경되면서 초기화 하는 방법에 대해 고민해야 했습니다. 우선 각 과일의 재고를 10개로 초기화 해야하는데, 열거형의 `case`만큼 과일 개수를 변경하는 일이 굉장히 번거로웠습니다. 찾아보니 `CaseIterable`이라는 프로토콜을 알게 되었고, 이 프로토콜을 활용하여 열거형의 `case`를 배열화하여 반복문에 적용할 수 있도록 했습니다. 그리고 반복문의 통해 과일 개수 초기화를 진행했습니다.

- 기존 코드

```swift
init(strawberry: UInt, banana: UInt, pineapple: UInt, mango: UInt, kiwi: UInt) {
		self.strawberry = strawberry
		self.banana = banana
		self.pineapple = pineapple
		self.mango = mango
		self.kiwi = kiwi
}
    
convenience init(count: UInt) {
		self.init(strawberry: count, banana: count, pineapple: count, mango: count, kiwi: count)
}
    
convenience init() {
		self.init(count: 10)
}
```

- 수정된 코드

```swift
enum FruitType: CaseIterable {
    case strawberry
    case banana
    case pineapple
    case kiwi
    case mango
}
```

```swift
private init(count: Int) {
		for type in FruitType.allCases {
				fruitCountList[type] = count
		}
}
    
private init(strawberry: Int, banana: Int, pineapple: Int, mango: Int, kiwi: Int) {
		fruitCountList[.strawberry] = strawberry
		fruitCountList[.banana] = banana
		fruitCountList[.pineapple] = pineapple
    fruitCountList[.mango] = mango
    fruitCountList[.kiwi] = kiwi
}
    
convenience init() {
		self.init(count: 10)
}
```

### 3. `JuiceMaker`에서 `add()`와 `sub()`를 빼고 `update()`로 통일

- STEP 1에서는 과일의 재고를 `stepper`를 통해서 변수를 관리하는지 몰랐기 때문에, `add`와 `sub` 함수를 따로 만들었습니다.
- 그러나 STEP 2에서 각 과일의 수량을 `stepper`의 값를 통해 관리한다는 것을 알게된 후에는 `sub` 함수가 더 이상 필요가 없어졌습니다. 왜냐하면 과일의 재고는 {수정된 `stepper`의 값} - {현재 과일의 값}을 현재 과일의 값에 더하면 무조건 과일의 재고가 수정되기 때문입니다. 따라서 `sub` 함수를 제거함과 동시에 `add` 함수의 이름을 `update` 로 바꿨습니다.

- 기존 코드

```swift
func add(fruit: Fruit) throws {
		try FruitStore.shared.update(fruit, as: +)
}

func sub(fruit: Fruit) throws {
		try FruitStore.shared.update(fruit, as: -)
}
```

- 수정된 코드

```swift
// JuiceMaker.swift
func update(_ fruit: Fruit) throws {
	  try FruitStore.shared.update(fruit, as: +)
}
```

```swift
// FruitInventoryViewController.swift
@IBAction func stepperValueChanged(_ sender: UIStepper) {
    let newFruitCount = Int(sender.value)
    guard let fruitType = FruitType(rawValue: sender.tag),
          let fruitCount = FruitStore.shared.fruitCountList[fruitType] else {
        return
    }
    do {
        let fruit = Fruit(fruitType, newFruitCount - fruitCount)
        
        switch fruitType {
        case .strawberry:
            try juiceMaker.update(fruit)
            strawberryCountLabel.text = "\(newFruitCount)"
        case .banana:
            try juiceMaker.update(fruit)
            bananaCountLabel.text = "\(newFruitCount)"
        case .pineapple:
            try juiceMaker.update(fruit)
            pineappleCountLabel.text = "\(newFruitCount)"
        case .kiwi:
            try juiceMaker.update(fruit)
            kiwiCountLabel.text = "\(newFruitCount)"
        case .mango:
            try juiceMaker.update(fruit)
            mangoCountLabel.text = "\(newFruitCount)"
        }
    } catch {
        return
    }
}
```

## 고민했던 점

### 1. 각 버튼(또는 `Stepper`)가 어떤 쥬스(또는 과일)에 해당하는 지 알아내는 방법

쥬스 선택 창에서 버튼과 쥬스 타입을 어떻게 매칭할 지 고민하던 중, ‘각 버튼의 텍스트에 메뉴의 이름이 적혀있다는 점을 활용하면 되겠다!’라는 생각을 했습니다. 우선 `JuiceType` 에 `String`을 상속하여 각 쥬스 케이스에 이름을 지정했습니다. 버튼을 누를 때, 해당 버튼의 텍스트 라벨에 접근하여 문자열을 가공한 후에, 쥬스 이름을 `JuiceType` 으로 변환하도록 했습니다.

- 현재 코드

```swift
// JuiceType.swift
enum JuiceType: String {
    var ingredients: [Fruit] {
        switch self {
        case .strawberryJuice:
            return [Fruit(.strawberry, 16)]
        case .bananaJuice:
            return [Fruit(.banana, 2)]
        case .kiwiJuice:
            return [Fruit(.kiwi, 3)]
        case .pineappleJuice:
            return [Fruit(.pineapple, 2)]
        case .strawberrydBananaJuice:
            return [Fruit(.strawberry, 10), Fruit(.banana, 1)]
        case .mangoJuice:
            return [Fruit(.mango, 3)]
        case .mangoKiwiJuice:
            return [Fruit(.mango, 2), Fruit(.kiwi, 1)]
        }
    }

    case strawberryJuice = "딸기쥬스"
    case bananaJuice = "바나나쥬스"
    case kiwiJuice = "키위쥬스"
    case pineappleJuice = "파인애플쥬스"
    case strawberrydBananaJuice = "딸바쥬스"
    case mangoJuice = "망고쥬스"
    case mangoKiwiJuice = "망키쥬스"
}
```

```swift
// JuiceMenuViewController.swift
guard let juiceSubstring = sender.titleLabel?.text?.split(separator: " ")[0],
let juiceType = JuiceType(rawValue: String(juiceSubstring)) else {
		return
}
order(menu: juiceType)
```

과일 수량을 조절하는 뷰에서는 `stepper`를 사용하는데, `stepper`에는 문자열이 없습니다. 따라서 각 `stepper`에 `tag`를 부여하여 이 태그를 바탕으로 과일의 타입을 가져올 수 있도록 했습니다. 이것을 하기 위해서는 `FruitType`에 `Int`를 상속하여 각 과일에 정수를 부여했습니다.

```swift
// FruitType.swift
enum FruitType: Int, CaseIterable {
    case strawberry = 0
    case banana = 1
    case pineapple = 2
    case kiwi = 3
    case mango = 4
}
```

```swift
// FruitInventoryViewController.swift
let newFruitCount = Int(sender.value)
guard let fruitType = FruitType(rawValue: sender.tag),
      let fruitCount = FruitStore.shared.fruitCountList[fruitType] else {
    return
}
```

### 2. modal segue와 show segue(push segue) 중에 show segue를 택한 이유

- `navigationController` 사용시 show segue 방식을 일반적으로 사용한다고 알고 있습니다.
- 과일 재고를 증감할 때는 특정 과일의 개수가 부족하거나 추가하고자 할 때 입니다. 이러한 로직은 주스를 고르는 View와 밀접한 관계가 있다 생각했습니다. 과일의 개수를 토대로 주스를 주문할 수 있고, 없고가 결정되기 때문입니다.
- 따라서, 순간적으로 흐름을 끊는 modal segue 방식보다 show segue 방식을 택하는 것이 좋다고 생각했습니다. stack에 viewControler를 추가하는 방식을 통해 로직이 연속성을 띈다는 것을 내포하고자 했습니다.
- 반례로, modal segue 방식을 사용자가 주스를 선택하고 결제 수단이나 포인트 적립 같은 기능에 적용할 수 있을 것 같습니다. 결제 수단이나 포인트 적립 같은 기능은 주스 자판기 프로그램을 염두하지 않더라도, 다른 프로그램에서도 공통적으로 사용될 수 있는 기능이기 때문입니다.
- 물론, 이러한 것들은 저희 팀에서 판단한 것이기 때문에 modal segue 방식을 택했다고 해서 맞거나, 틀렸다고 생각하지는 않습니다.

*****cf. modal segue and show segue*****

[What is the difference between Modal and Push segue in Storyboards?](https://stackoverflow.com/questions/9392744/what-is-the-difference-between-modal-and-push-segue-in-stor [...]

2023-09-19 13:57 UTC, jryoun1 requested changes
step2 고생하셨습니다 👏 💯 

대부분 잘 작성해주셨지만 몇가지 개선되면 좋을 부분들이 있어서 코멘트 남겨두었습니다. 
확인부탁드려요 🙏 

### 질문에 관련된 답변

고민한점 4번 viewWillAppear() 
관련해서는 코멘트에서도 한 번 남겨두었는데 viewController의 life cycle에 대해서 공부해보시면 도움이 될 것 같네요!

궁금한점

1. 이 역시도 위와 마찬가지고 각 viewController에서의 lifecycle에 대해서 우선 공부해보시면 좋을 것 같네요. 그리고 말씀해주신 binding은 KVO, delegate, notification 등을 통해서 할 수 있겠네요. 다만 binding 보다 viewController의 lifecycle에 대한 이해가 지금 step에서는 더 중요해보이긴하네요 :)

2. 관련해서는 IBOutlet collection에 대해서 알아보시면 도움이 될 것 같네요 🙏

2023-09-19 13:57 UTC, jryoun1 commented on JuiceMaker/JuiceMaker/Controller/FruitInvetoryViewController.swift
> +//  FruitInvetoryViweController.swift
파일명과 여기에 오타가 있네요!

2023-09-19 13:57 UTC, jryoun1 commented on JuiceMaker/JuiceMaker/Controller/FruitInvetoryViewController.swift
> +    @IBOutlet var mangoStepper: UIStepper!
이 IBOutlet property들은 외부에서 접근될 일이 있을까요? 🤔

2023-09-19 13:57 UTC, jryoun1 commented on JuiceMaker/JuiceMaker/Controller/FruitInvetoryViewController.swift
> +        mangoStepper.tag = 4
stepper에 tag를 셋팅하는 함수로 따로 빼는것이 가독성이 더 좋을 것 같네요!

2023-09-19 13:57 UTC, jryoun1 commented on JuiceMaker/JuiceMaker/Controller/JuiceMenuViewController.swift
> +    }
viewDidLoad를 override한 이유가 있을까요?

2023-09-19 13:57 UTC, jryoun1 commented on JuiceMaker/JuiceMaker/Controller/JuiceMenuViewController.swift
> +            self.navigationController?.pushViewController(fruitInventoryViewController, animated: true)
self를 사용하는 기준이 있을까요?

2023-09-19 13:57 UTC, jryoun1 commented on JuiceMaker/JuiceMaker/Controller/JuiceMenuViewController.swift
> +    private func alertOrderSuccess(of juice: JuiceType) {
내부에서는 alert을 보여주는 함수인 것 같은데 함수명이 명확하지 않을 것 같습니다.
아래의 fail 케이스도 동일합니다.
좀 더 명확하게 개선되면 좋을 것 같네요 🙏

2023-09-19 13:57 UTC, jryoun1 commented on JuiceMaker/JuiceMaker/Controller/JuiceMenuViewController.swift
> +//  JuiceMaker - ViewController.swift
파일명과 일치시켜주세요!

2023-09-20 06:19 UTC, newJunsung commented on JuiceMaker/JuiceMaker/Controller/JuiceMenuViewController.swift
> +//  JuiceMaker - ViewController.swift
수정했습니다! 알려주셔서 감사합니다.

2023-09-20 06:20 UTC, newJunsung commented on JuiceMaker/JuiceMaker/Controller/FruitInvetoryViewController.swift
> +//  FruitInvetoryViweController.swift
수정했습니다! 알려주셔서 감사합니다.

2023-09-20 06:21 UTC, newJunsung commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func update(_ fruit: Fruit) throws {
불필요한 주석을 제거했습니다!
FruitStore에 있는 과일 저장소 타입도 마찬가지로 제거했습니다!

2023-09-20 06:25 UTC, shlim0 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    private(set) var fruitCountList: [FruitType: Int] = [:]
fruitCountList를 fruitCounts로 변경했습니다. fruits는 여러개의 함수 파라미터로 사용되고 있어서, 혼동될 수 있을 것 같아 사용하지 않았습니다.

2023-09-20 06:26 UTC, shlim0 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    convenience init() {
코드 수정 중 사라졌던 것 같네요. 다시 추가했습니다.

2023-09-20 06:30 UTC, shlim0 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +            let checkedCount = try getCalculatedCount(of: `operator`(fruitCount, count))
변경했습니다!

2023-09-20 06:31 UTC, shlim0 commented on JuiceMaker/JuiceMaker/Model/FruitType.swift
> +    case mango = 4
삭제했습니다 :)

2023-09-20 06:32 UTC, shlim0 commented on JuiceMaker/JuiceMaker/Model/JuiceMakerException.swift
>      case negativeCountError
생각해보니 `JuiceMakerException.fruitNotFound` 라고 써도 의미 전달에 문제가 없을 것 같아요. 수정했습니다.

2023-09-20 06:34 UTC, shlim0 commented on JuiceMaker/JuiceMaker/Controller/FruitInvetoryViewController.swift
> +    @IBOutlet var mangoStepper: UIStepper!
생각해보니 그런 것 같아요! private로 변경했습니다.

2023-09-20 06:37 UTC, shlim0 commented on JuiceMaker/JuiceMaker/Controller/FruitInvetoryViewController.swift
> +        mangoStepper.tag = 4
`setTagOfStepper()`로 따로 분리하였습니다. 더 깔끔해진 것 같아요!!

2023-09-20 06:48 UTC, shlim0 commented on JuiceMaker/JuiceMaker/Controller/FruitInvetoryViewController.swift
> +        mangoStepper.addTarget(self, action: #selector(stepperValueChanged(_:)), for: .valueChanged)
![image](https://github.com/tasty-code/ios-juice-maker/assets/46235301/ec76208f-38ff-484c-800f-6d947bb25039)
해당 그림을 참고하여 ViewController Life Cycle에 대해 공부해봤습니다. 설명의 편의상 ViewController를 VC라 하겠습니다. `viewDidLoad()`는 VC에 속한 어떤 view가 메모리에 올라오면 O/S에 의해 호출됩니다. 이후 `viewWillAppear()`도 호출됩니다.

사실상 `viewDidLoad()`와 `viewWillAppear()`는 view가 그려지기 전에 호출되는 것이 공통점입니다. 다만, `viewWillAppear()`의 경우에는, 그려진 view가 메모리에서 사라지지 않는 이상, view에 변화가 일어나는 경우  `viewDidLoad()`가 호출되지 않고 `viewWillAppear()` 부터 호출됩니다. 이 점이 큰 차이점이라 생각합니다.

`addTarget()`을 해당 위치에 둔 것은 코드를 리팩토링 하던 도중 판단 착오가 있었던 것 같습니다. 해당 코드를 `viewDidLoad()`에 위치했습니다. 또한, 앞선 리뷰에서 

'stepper에 tag를 셋팅하는 함수로 따로 빼는것이 가독성이 더 좋을 것 같네요!'

라고 하신 것처럼 각stepper에 `addTarget()`하는 코드를 함수로 따로 빼는 것이 더 가독성이 좋다 생각하여 `setEventActionOfStepper()`로 분리했습니다.

2023-09-20 06:53 UTC, shlim0 commented on JuiceMaker/JuiceMaker/Controller/JuiceMenuViewController.swift
> +    private func alertOrderSuccess(of juice: JuiceType) {
`alertOrderSuccess()`를 `showAlertOrderSuccess()`로,
`alertOrderFailed()`를 `showAlertOrderFailed()`로 네이밍을 변경하였습니다.

2023-09-20 07:00 UTC, newJunsung commented on JuiceMaker/JuiceMaker/Controller/JuiceMenuViewController.swift
> +    }
`viewDidLoad()`는 `UIViewController`의 함수입니다. `JuiceMenuViewController`는 `UIViewController`를 상속받았기 때문에, viewDidLoad라는 이름을 가진 함수를 만들기 위해서는, 매개변수를 추가하여 오버로딩을 하던가, 오버라이딩을 하는 수 밖에 없습니다.
`UIViewController`의 기존 코드진행과 더불어, 저희는 기존 `viewDidLoad()` 함수에 추가적인 코드를 덧붙여야했기 때문에, `override`를 사용했습니다.

2023-09-20 07:18 UTC, shlim0 commented on JuiceMaker/JuiceMaker/Controller/JuiceMenuViewController.swift
> +            self.navigationController?.pushViewController(fruitInventoryViewController, animated: true)
`self`의 경우 자기 자신의 인스턴스에 접근할 때 쓰는 참조값으로 알고 있습니다. 
`self`를 제거하고 컴파일 시, 아래와 같은 컴파일 에러 코드를 확인할 수 있었습니다.

`Implicit use of 'self' in closure; use 'self.' to make capture semantics explicit`

closure에서는 `self`를 명시해야 한다고 알게 되었습니다. 클로저는 이름 없는 함수이기 때문에, 함수를 예를 들어 설명해보겠습니다.

```swift
func test(name: String) {
     name = name
}
```

과 같은 코드가 있는 경우, 컴파일러는 매개변수에 매개변수를 대입한다고 해석하게 되어 다음과 같은 컴파일 에러가 발생합니다.

`Assigning a variable to itself`
(`inout`을 매개변수에 붙이지 않는다면 `Cannot assign to value: 'name' is a 'let' constant`라는 에러를 확인할 수 있습니다. 매개변수는 기본적으로 `let` 취급 되기 때문입니다)

결국, 자기 자신에 값을 대입하게 되는 꼴입니다. 이와 같은 문제를 방지하려면 `self`를 붙여 명확한 코드를 작성해야 합니다. 따라서, 이와 같은 경우에는 `self`를 사용해야 합니다. 또한, 이런 경우가 아니라면 `self`를 생략해도 문제 없다고 생각합니다.

2023-09-20 13:22 UTC, jryoun1 commented on JuiceMaker/JuiceMaker/Controller/FruitInvetoryViewController.swift
> +        mangoStepper.addTarget(self, action: #selector(stepperValueChanged(_:)), for: .valueChanged)
잘 설명해주셨네요 👏 
여쭤본 이유중 하나는 viewDidLoad는 해당 vc가 생성된 이후로 한 번만 호출이 되지만, 
viewWillAppear는 화면에 노출이 될 때 마다 호출이 되는 부분도 아시면 좋을 것 같아서 말씀드렸었습니다!

2023-09-20 13:23 UTC, jryoun1 commented on JuiceMaker/JuiceMaker/Controller/JuiceMenuViewController.swift
> +    }
지금 코드에서는 viewDidLoad 내부에 super를 호출하는 것 외에는 아무것도 하지 않고 있어서 여쭤봤었습니다.

2023-09-20 13:31 UTC, jryoun1 approved these changes
고생하셨습니다! 잘 수정해주셨네요~ 
나머지 부분들은 다음 step을 진행하면서 반영해주세요! 
step2는 여기서 머지하겠습니다!

2023-09-20 13:31 UTC, jryoun1 commented on JuiceMaker/JuiceMaker/Controller/JuiceMenuViewController.swift
> +
여기도 private이 필요할 것 같네요!

2023-09-20 13:31 UTC, merged