쥬스 자판기 [STEP 2] Janine, JaeHyeok
tasty-code/ios-juice-maker pull request #57
Opened 2023-09-18 04:07 UTC by SimJaeHyeok

리뷰어: @protocorn93
버드: @janine-kang, @SimJaeHyeok

콘, 안녕하세요! STEP 2 PR 드립니다.
---
### Summary
[STEP 1]에서 만들었던 쥬스 자판기 모델들을 ViewController에 연결하는 작업을 수행했습니다.

### 구현 기능 및 상세
 - '재고 수정' 버튼을 터치하면 '재고 추가' 화면으로 이동.

- 각 주문 버튼 터치 시
  쥬스 재료의 재고가 있는 경우 : 쥬스 제조 후 “*** 쥬스 나왔습니다! 맛있게 드세요!” 얼럿 표시
  쥬스 재료의 재고가 없는 경우 : “재료가 모자라요. 재고를 수정할까요?” 얼럿 표시
  ‘예' 선택시 재고수정 화면으로 이동
  ‘아니오' 선택시 얼럿 닫기
---
### 고민했던 점
네비게이션을 이동시키는 방법이 다양해서 어떻게 이동시키는게 좋을지 고민했습니다.
특히, 스토리보드로 연결된 각 화면들을 네비게이션으로 보내게 될 때 코드로 짜여진 경우와 다르게 움직이게 되어 이 부분을 찾기 위해 많은 고민을 한 것 같습니다.

특히, 아직 의문을 가지고 있는 부분에 대해서 여쭤보고 싶습니다.

1. 각각의 스택뷰 접근 vs 하나의 큰 스택뷰로부터 각각의 스택뷰 접근
`stack view`에 접근하는 방법을 고안해내는데 고민이 깊었습니다.
하나의 큰 `stack view` 내부에 또 `stack view`가 들어가 있는 경우, 내부 스택뷰에 메서드를 각각 이어주는 것이 맞는지, 또는 외부 스택뷰에 접근하여 내부의 값까지 접근하는 것이 더 효율적인지 아직도 의문입니다.

2. 공유자원 전달 방식
각각의 ViewController에서 하나의 인스턴스를 공유하는 방법이 무조건 Sington이어야만 하는지 궁금합니다.
- 이슈: 화면 이동 후 두 개의 화면에서 재고 현황을 공유해야 함
- 구현 방법1 :  dashboardViewController(두번째 화면)에 프로퍼티 선언 후, dashboardViewController 생성 시 프로퍼티에 기존 fruitStore 할당
이러한 상황에서 궁금한 것은, `weak`키워드를 사용하여 메모리 사이클을 약하게 만들고 사용한다고 가정 시 Singleton으로 구현하는 것과 비교했을 때 어느 구현 방식이 더 적합하고 효율적인가요?

2023-09-18 04:09 UTC, janine-kang commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    }
이 부분

2023-09-19 01:15 UTC, protocorn93 requested changes
두 분 고생많으셨어요. 다만 다음부턴 커밋도 더 작은 단위로 쪼개서 부탁드릴게요! 이렇게 통으로 올려주시면 저는 여러분의 의도를 파악하기 어려워요 또한 동작 영상이나 스크린샷을 첨부해주시면 더 좋을 것 같아요

- 현재 요구사항에선 각각의 UILabel이나 컴포넌트를 직접 IBOutlet으로 연결하여 처리하는 것이 더 직관전일 것 같아요.
- 두 객체간 데이터 전달 방식은 다양한 방법이 있어요. delegate, notifications 등등 Singleton이 나쁜 것은 아니에요. 다만 편리함을 위해 투명성을 희생한다는 말도 있듯이 상태 관리에 집중이 필요한 객체이긴해요. 객체간 데이터 전달 방법은 대충 구글에 `"Passing data between two objects in Swift"` 와 같이 검색해보시면 다양한 사례와 방법들을 확인하실 수 있어요. 
- `이러한 상황에서 궁금한 것은, weak키워드를 사용하여 메모리 사이클을 약하게 만들고 사용한다고 가정 시 Singleton으로 구현하는 것과 비교했을 때 어느 구현 방식이 더 적합하고 효율적인가요?` weak 키워드를 사용한다는 것이 제가 이해를 못했어요. 좀 더 자세히 설명해주시면 좋을 것 같아요. Singleton이 나쁜 것은 아니에요. 다만 관리에 주의가 필요한 객체이긴해요.

2023-09-19 01:15 UTC, protocorn93 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        }
저는 오히려 지금 단계에선 이러한 경우엔 각각의 레이블을 IBOutlet으로 연결하는 것이 더 좋을 것 같아요. 불필요하게 코드가 복잡해진 것 같아요.

2023-09-19 05:16 UTC, SimJaeHyeok commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
>  class ViewController: UIViewController {
```swift 
import UIKit

final class ViewController: UIViewController {
```
상속과 오버라이딩이 불필요 하기 때문에 콘의 말씀에 따라 수정하였습니다.

2023-09-19 05:24 UTC, SimJaeHyeok commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    @IBOutlet weak var inventoryStackView : UIStackView!
```swift
    private let juiceMakerModel = JuiceMaker()
    
    @IBOutlet private weak var strawberryStockLabel: UILabel!
    @IBOutlet private weak var bananaStockLabel: UILabel!
    @IBOutlet private weak var pineappleStockLabel: UILabel!
    @IBOutlet private weak var kiwiStockLabel: UILabel!
    @IBOutlet private weak var mangoStockLabel: UILabel!
    @IBOutlet private weak var kiwiStockLabel: UILabel!
    @IBOutlet private weak var mangoStockLabel: UILabel!
```
inventoryStackView를 삭제하고 각각의 `UILabel`을 `IBOutlet`으로 연결해서 `private`으로 설정하였습니다.

2023-09-19 05:25 UTC, SimJaeHyeok commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    @IBAction func didTapRightNavigatorItem(_ sender: UIBarButtonItem) {
```swift 
@IBAction private func didTapRightNavigatorItem(_ sender: UIBarButtonItem) {
```
수정하였습니다.

2023-09-19 05:25 UTC, SimJaeHyeok commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    @IBAction func didTapJuiceButton(_ sender: UIButton) {
```swift 
@IBAction private func didTapJuiceButton(_ sender: UIButton) {
```
수정하였습니다.

2023-09-19 05:45 UTC, janine-kang commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }()
넵 zip과 initializer 사용하면 훨씬 깔끔하네요! 감사합니다 😃
```
private var fruitList: [Fruit: Int] = Dictionary(uniqueKeysWithValues: zip(Fruit.allCases, Array(repeating: 10, count: 5)))
```

2023-09-19 05:46 UTC, janine-kang commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        }
넵! 해당부분 확인하였습니다 🙂 각각의 Label에서 바로 값을 세팅해주는 방향으로 구현 변경했습니다!

```
    @IBOutlet private weak var strawberryStockLabel: UILabel!
    @IBOutlet private weak var bananaStockLabel: UILabel!
    @IBOutlet private weak var pineappleStockLabel: UILabel!
    @IBOutlet private weak var kiwiStockLabel: UILabel!
    @IBOutlet private weak var mangoStockLabel: UILabel!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        updateStock()
    }
    
    private func updateStock() {
        let fruitsUILabels = [strawberryStockLabel: Fruit.strawberry , bananaStockLabel: Fruit.banana , kiwiStockLabel: Fruit.kiwi  ,pineappleStockLabel: Fruit.pineapple, mangoStockLabel: Fruit.mango]
        let fruitStocks = juiceMakerModel.getAllStocks()
        for (remainFruit, fruit) in fruitsUILabels {
            guard let amount = fruitStocks[fruit] else {
                return
            }
            remainFruit?.text = String(amount)
        }
    }
```

2023-09-19 05:46 UTC, SimJaeHyeok commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }()
```swift
private var fruitList: [Fruit: Int] = Dictionary(uniqueKeysWithValues: zip(Fruit.allCases, Array(repeating: 10, count: 5)))
```
말씀하신 `Dictionary` 메서드를 이용하여 초기화하였습니다. 
고차함수 zip의 Key는 `Fruit`을 Value는 `Array`를 이용하여 전달하였습니다.

2023-09-19 05:50 UTC, SimJaeHyeok commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        }
<img width="260" alt="스크린샷 2023-09-19 오후 2 48 41" src="https://github.com/tasty-code/ios-juice-maker/assets/142188004/e821de95-303f-430b-9b90-0cceb83c2797">

말씀 하신대로 불필요한 StackView 접근을 제거하고 각각의 레이블을 IBOutlet을 연결해 수정하였습니다.

2023-09-19 05:53 UTC, SimJaeHyeok commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        }
<img width="260" alt="스크린샷 2023-09-19 오후 2 48 41" src="https://github.com/tasty-code/ios-juice-maker/assets/142188004/7905f082-3c2d-4ad2-8733-e92f0ad8051e">
말씀하신대로 IBOutlet으로 각각 Label을 연결하였습니다.

2023-09-19 05:55 UTC, janine-kang commented
> 두 분 고생많으셨어요. 다만 다음부턴 커밋도 더 작은 단위로 쪼개서 부탁드릴게요! 이렇게 통으로 올려주시면 저는 여러분의 의도를 파악하기 어려워요 또한 동작 영상이나 스크린샷을 첨부해주시면 더 좋을 것 같아요
> 
> * 현재 요구사항에선 각각의 UILabel이나 컴포넌트를 직접 IBOutlet으로 연결하여 처리하는 것이 더 직관전일 것 같아요.
> * 두 객체간 데이터 전달 방식은 다양한 방법이 있어요. delegate, notifications 등등 Singleton이 나쁜 것은 아니에요. 다만 편리함을 위해 투명성을 희생한다는 말도 있듯이 상태 관리에 집중이 필요한 객체이긴해요. 객체간 데이터 전달 방법은 대충 구글에 `"Passing data between two objects in Swift"` 와 같이 검색해보시면 다양한 사례와 방법들을 확인하실 수 있어요.
> * `이러한 상황에서 궁금한 것은, weak키워드를 사용하여 메모리 사이클을 약하게 만들고 사용한다고 가정 시 Singleton으로 구현하는 것과 비교했을 때 어느 구현 방식이 더 적합하고 효율적인가요?` weak 키워드를 사용한다는 것이 제가 이해를 못했어요. 좀 더 자세히 설명해주시면 좋을 것 같아요. Singleton이 나쁜 것은 아니에요. 다만 관리에 주의가 필요한 객체이긴해요.

2번째 부분은 참조 사이클이 생기는지 아닌지에 대한 고민이었습니다! 저도 확신이 없어서 정확하게 여쭤보질 못했네요 😭 
juiceMakerModel이라는 프로퍼티를 두번째 VC인 DashboardVC의 프로퍼티에 할당하게 되었을 때, fruitStore 인스턴스를 공유하게 된다고 생각했고 그가 참조 사이클을 일으킬 수 있다고 생각하여 fruitStore를 singleton으로만 구현해야하는지 여쭤봤던 것인데요, 결론적으로 juiceMakerModel은 Struct 타입이며, 정보의 흐름이 단방향이기 때문에 참조 사이클이 일어나지 않는다고 판단하게 되었습니다. (singleton으로의 구현과 관계 없이요!)
따라서 weak 키워드를 사용할 필요가 없다는 결론을 내렸습니다. 해당 판단이 옳게 내려진걸까요?

2023-09-19 07:19 UTC, janine-kang commented on JuiceMaker/JuiceMaker/Model/Menu.swift
> +    case mangoKiwiJuice = "망키쥬스"
해당 부분 디스코드로 말씀드렸던 것처럼, 
rawValue를 통해 구현하는 것이 보다 간편하다고 생각하여 사용하게 되었습니다.
rawValue가 값을 사용자에게 나타내기 위할 때 주로 사용된다는 점과, 변경이 불가능 하기 때문에 이후 사용자의 기호성에 따른 값 변경에 제약이 생길 수 있다는 점 인지하였고, 다시 예전처럼 분리하였습니다 🙂

2023-09-19 07:28 UTC, SimJaeHyeok commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        }
<img width="256" alt="스크린샷 2023-09-19 오후 4 17 04" src="https://github.com/tasty-code/ios-juice-maker/assets/142188004/fb7f4053-967e-4f69-8bc2-cbcdb67c77b8">

각각 재료의`Label`을 `IBOutlet`으로 연결하였고, 
해당 재료를 사용하는 쥬스 `button`을 Tap했을 시 `Label`의 값이  변경되게 액션을 연결하였습니다.

2023-09-20 10:40 UTC, protocorn93 commented
> > 두 분 고생많으셨어요. 다만 다음부턴 커밋도 더 작은 단위로 쪼개서 부탁드릴게요! 이렇게 통으로 올려주시면 저는 여러분의 의도를 파악하기 어려워요 또한 동작 영상이나 스크린샷을 첨부해주시면 더 좋을 것 같아요
> 
> > 
> 
> > * 현재 요구사항에선 각각의 UILabel이나 컴포넌트를 직접 IBOutlet으로 연결하여 처리하는 것이 더 직관전일 것 같아요.
> 
> > * 두 객체간 데이터 전달 방식은 다양한 방법이 있어요. delegate, notifications 등등 Singleton이 나쁜 것은 아니에요. 다만 편리함을 위해 투명성을 희생한다는 말도 있듯이 상태 관리에 집중이 필요한 객체이긴해요. 객체간 데이터 전달 방법은 대충 구글에 `"Passing data between two objects in Swift"` 와 같이 검색해보시면 다양한 사례와 방법들을 확인하실 수 있어요.
> 
> > * `이러한 상황에서 궁금한 것은, weak키워드를 사용하여 메모리 사이클을 약하게 만들고 사용한다고 가정 시 Singleton으로 구현하는 것과 비교했을 때 어느 구현 방식이 더 적합하고 효율적인가요?` weak 키워드를 사용한다는 것이 제가 이해를 못했어요. 좀 더 자세히 설명해주시면 좋을 것 같아요. Singleton이 나쁜 것은 아니에요. 다만 관리에 주의가 필요한 객체이긴해요.
> 
> 
> 
> 2번째 부분은 참조 사이클이 생기는지 아닌지에 대한 고민이었습니다! 저도 확신이 없어서 정확하게 여쭤보질 못했네요 😭 
> 
> juiceMakerModel이라는 프로퍼티를 두번째 VC인 DashboardVC의 프로퍼티에 할당하게 되었을 때, fruitStore 인스턴스를 공유하게 된다고 생각했고 그가 참조 사이클을 일으킬 수 있다고 생각하여 fruitStore를 singleton으로만 구현해야하는지 여쭤봤던 것인데요, 결론적으로 juiceMakerModel은 Struct 타입이며, 정보의 흐름이 단방향이기 때문에 참조 사이클이 일어나지 않는다고 판단하게 되었습니다. (singleton으로의 구현과 관계 없이요!)
> 
> 따라서 weak 키워드를 사용할 필요가 없다는 결론을 내렸습니다. 해당 판단이 옳게 내려진걸까요? 

네네 순환 참조와는 관계가 없어보이네요. 설명 감사해요! 네네 일단은 현재 구조로 나머지 스탭 진행해보시죠!👍

2023-09-20 16:42 UTC, merged