쥬스자판기 [STEP 2] Mond, Rarla
tasty-code/ios-juice-maker pull request #58
Opened 2023-09-19 02:49 UTC by yeji1008

@forestjae
안녕하세요~! 숲재!
두번째 리뷰를 요청하게 된 @rarla @mond입니다 :)
잘 부탁드립니다~!

## Step2 구현 요구사항
- '재고 수정' 버튼을 터치하면 '재고 추가' 화면으로 이동합니다.
    - 이동 방식은 어떤 방식이 적절한지 고민하기
- 각 주문 버튼 터치 시
    - 쥬스 재료의 재고가 있는 경우 : 쥬스 제조 후 “*** 쥬스 나왔습니다! 맛있게 드세요!” 얼럿 표시
    - 쥬스 재료의 재고가 없는 경우 : “재료가 모자라요. 재고를 수정할까요?” 얼럿 표시
        - ‘예' 선택시 재고수정 화면으로 이동
        - ‘아니오' 선택시 얼럿 닫기
    - 과일쥬스를 제조하여 과일의 재고가 변경되면 화면의 적절한 요소에 변경사항을 반영합니다.

<br><br>

## 코드를 작성하며 고민한 점
1. 이번 스텝 수행 중 핵심 경험인 아래 항목을 잘 사용하고자 고민했습니다.
    - 내비게이션 바 및 바 버튼 아이템의 활용
    - 얼럿 컨트롤러 활용
    - Modality의 활용
    - 화면 사이의 데이터 공유
2. 구현 요구사항 중 이동 방식은 어떤 방식이 적절한지 고민해보았습니다. 우선 Navigation Controller가 2개가 구현된 상태로 주어져 해당에 대한 이유를 찾아보았습니다. [링크](https://stackoverflow.com/questions/14977164/when-i-should-use-navigation-controller)를 참고해보니 Navigation Controller의 용도는 계층적인 구조를 표현하기 위해 사용하는 용도라고 합니다. 재고 수정에서 재고 추가 화면 이동은 계층적인 구조가 아니라는 점과 네비게이션으로 연결한다면 뒤로가기 버튼이 생기는데 뒤로가기 버튼의 의미가 모호해진다는 점, 저장과 취소 버튼이 필요하다는 점에서 Modal이 적절하다고 생각해 해당 방식으로 적용했습니다.
3. Step1에서는 이미 구현되어있던 버튼 이름을 고민하지 않고 enum case를 구현했습니다. Step2를 진행하다보니 한글로 된 쥬스 이름을 Alert Message로 표시해야하는 상황이 생겼는데, 고민 결과 기존 enum case를 수정하는 방식이 아닌 Button에 있는 Text를 가져와 공백을 기준으로 split하여 Subsequence 타입을 String으로 변환하여 사용하였습니다.
4. Alert 형태가 2가지여서 어떤 식으로 구현을 해야할 지 고민하였습니다. 저희는 AlertType을 정의하여 type에 따라 다른 형태의 Alert가 출력되도록 구현하였습니다.

<br><br>

## 조언을 얻고 싶은 부분
- 코드를 작성하며 고민한점 3번에서 더 좋은 방법이 있을지 궁금합니다.

2023-09-20 14:55 UTC, forestjae requested changes

2023-09-20 14:55 UTC, forestjae commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    let juiceName = buttonName.split(separator: " ")[0]
버튼의 타이틀 label에서 쥬스 이름을 추출하셨군요. 창의적이네요 👍 👍 👍 👍

2023-09-20 14:55 UTC, forestjae commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    }
메서드 내부에 개행이 없어서 조금 답답해보이고 가독성이 떨어지는 느낌이 듭니다.

2023-09-20 14:55 UTC, forestjae commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    } else if type == .twoButton {
oneButton과 twoButton이 무엇을 의미하나요?

2023-09-20 14:55 UTC, forestjae commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +      return (AlertType.oneButton, "\(juiceName) 나왔습니다! 맛있게 드세요!")
Juice 타입을 없애고 String을 받게 변경하신 이유가 궁금해요

2023-09-20 14:55 UTC, forestjae commented on JuiceMaker/JuiceMaker/Model/Type.swift
> +}
위에도 코멘트를 남겨두었지만, 이렇게 Alert의 타입을 정의하신 이유가 궁금해요 ㅎㅎㅎ

2023-09-21 01:06 UTC, yeji1008 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    let juiceName = buttonName.split(separator: " ")[0]
감사합니다!

2023-09-21 01:11 UTC, rarlala commented
> 
> > 3. Step1에서는 이미 구현되어있던 버튼 이름을 고민하지 않고 enum case를 구현했습니다. Step2를 진행하다보니 한글로 된 쥬스 이름을 Alert Message로 표시해야하는 상황이 생겼는데, 고민 결과 기존 enum case를 수정하는 방식이 아닌 Button에 있는 Text를 가져와 공백을 기준으로 split하여 Subsequence 타입을 String으로 변환하여 사용하였습니다.
> 
> 다른 방법은 혹시 생각해 보신게 있을까요? 기존 enum case를 수정하지 않는 방향으로 결정하신 이유가 궁금합니다.
> 

**저희가 사용한 방식**
1. 쥬스 버튼을 tag를 지정해 Int를 받는 방식을 사용함
2. tag를 활용하고자 Juice enum을 Int 타입으로 지정해 switch로 분기처리
3. 이미 버튼에 표현하고자 하는 이름이 모두 적혀있어 해당을 활용!

**만약 enum을 String 타입으로 수정한다면?** [5c10cbd](https://github.com/tasty-code/ios-juice-maker/pull/58/commits/5c10cbd37dfa621228f789d05b7f47d395691773)
- Juice enum을 String 타입으로 변경 후 rawValue 쥬스 이름으로 적기
- tag가 아닌 버튼의 이름을 활용해 createJuice에 넘기기
- 해당에 맞는 타입으로 Int → String 변환 및 juiceName 없어짐
→ tag를 활용하지 않을 수 있게 되고, juiceName을 넘길 필요가 사라짐~!

tag를 먼저 활용하려다보니 Int 타입으로 enum을 활용하는 방법 쪽으로 나아갔던 것 같아요~
enum을 수정해보니 조금 더 깔끔해지는 것 같아서 해당 방식으로 수정했습니다!

2023-09-21 01:31 UTC, yeji1008 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    }
중간중간에 개행을 넣어 해결했습니다.

2023-09-21 01:36 UTC, yeji1008 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    } else if type == .twoButton {
[663b28c](https://github.com/tasty-code/ios-juice-maker/pull/58/commits/663b28c6469b892875286169ca5ca12a1c6a5544)
oneButton은 재고가 남아있을 때 확인 버튼만 있으면 되서 하나의 버튼만 있는 Alert 형태를 이야기한 것입니다. twoButton은 재고가 남아있지 않을 때 예, 아니요 버튼 2개가 필요하기 때문입니다. 수정한 코드에서는 AlertType을 삭제하고 message를 이용해서 나누도록 변경하였습니다.

2023-09-21 01:39 UTC, rarlala commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +      return (AlertType.oneButton, "\(juiceName) 나왔습니다! 맛있게 드세요!")
[5c10cbd](https://github.com/tasty-code/ios-juice-maker/pull/58/commits/5c10cbd37dfa621228f789d05b7f47d395691773)

이것도 마찬가지로 tag를 사용하는 형태로 넘기게되면 버튼의 이름을 넘겨줘야했기 때문이에요!
enum을 수정하며 이 부분도 type을 받아 처리하게 수정되었습니다 :)

2023-09-21 01:43 UTC, rarlala commented
추가로 문의드립니다~ :)
팝업 형태의 정의가 아닌 메세지의 형태로 분기를 처리하다보니

`let outOfStock = (message == "재료가 모자라요. 재고를 수정할까요?")`
해당 코드처럼 작성 후 분기를 했는데요!

사실 해당 코드를 타입으로 또 별도로 정의해서 작성할지 고민이 되었습니다.
하지만 다른 에러 타입이  `"\(type) 나왔습니다! 맛있게 드세요!"` 형태라 정의하는 것이 고민이 되어 우선은 변경하지 않았습니다!

혹시 해당 부분에 대해 코멘트 주실 수 있을까요~?

2023-09-21 12:32 UTC, forestjae commented
> > > 3. Step1에서는 이미 구현되어있던 버튼 이름을 고민하지 않고 enum case를 구현했습니다. Step2를 진행하다보니 한글로 된 쥬스 이름을 Alert Message로 표시해야하는 상황이 생겼는데, 고민 결과 기존 enum case를 수정하는 방식이 아닌 Button에 있는 Text를 가져와 공백을 기준으로 split하여 Subsequence 타입을 String으로 변환하여 사용하였습니다.
> > 
> > 
> > 다른 방법은 혹시 생각해 보신게 있을까요? 기존 enum case를 수정하지 않는 방향으로 결정하신 이유가 궁금합니다.
> 
> **저희가 사용한 방식**
> 
> 1. 쥬스 버튼을 tag를 지정해 Int를 받는 방식을 사용함
> 2. tag를 활용하고자 Juice enum을 Int 타입으로 지정해 switch로 분기처리
> 3. 이미 버튼에 표현하고자 하는 이름이 모두 적혀있어 해당을 활용!
> 
> **만약 enum을 String 타입으로 수정한다면?** [5c10cbd](https://github.com/tasty-code/ios-juice-maker/pull/58/commits/5c10cbd37dfa621228f789d05b7f47d395691773)
> 
> * Juice enum을 String 타입으로 변경 후 rawValue 쥬스 이름으로 적기
> * tag가 아닌 버튼의 이름을 활용해 createJuice에 넘기기
> * 해당에 맞는 타입으로 Int → String 변환 및 juiceName 없어짐
>   → tag를 활용하지 않을 수 있게 되고, juiceName을 넘길 필요가 사라짐~!
> 
> tag를 먼저 활용하려다보니 Int 타입으로 enum을 활용하는 방법 쪽으로 나아갔던 것 같아요~ enum을 수정해보니 조금 더 깔끔해지는 것 같아서 해당 방식으로 수정했습니다!
> 
> (해당 commit에서 tag 받아오는 부분을 주석처리했는데! 추후 삭제했습니다!)

잘 변경해주셨습니다. 그런데 tag를 사용하면서도 enum을 사용할 수 있는 방법이 있어요. enum의 rawValue를 string으로 변경하는게 아니라 enum에 juiceName:String이란 프로퍼티를 추가하는겁니다. 많이 쓰이는 방법이니 참고 바랍니다!

```swift
enum Juice {
  case strawberry
  case ...

  var juiceName: String {
    switch self {
      case .strawberry 
        return "딸기쥬스"
      case ...
}
```

2023-09-21 12:32 UTC, forestjae commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +      }))
잘 변경해주셨네요 👍

2023-09-21 12:36 UTC, forestjae commented
> 추가로 문의드립니다~ :) 팝업 형태의 정의가 아닌 메세지의 형태로 분기를 처리하다보니
> 
> `let outOfStock = (message == "재료가 모자라요. 재고를 수정할까요?")` 해당 코드처럼 작성 후 분기를 했는데요!
> 
> 사실 해당 코드를 타입으로 또 별도로 정의해서 작성할지 고민이 되었습니다. 하지만 다른 에러 타입이 `"\(type) 나왔습니다! 맛있게 드세요!"` 형태라 정의하는 것이 고민이 되어 우선은 변경하지 않았습니다!
> 
> 혹시 해당 부분에 대해 코멘트 주실 수 있을까요~?

outOfStock의 판단을 메시지의 내용으로 하고있는데 각 메서드의 역할과 구조를 조금 변경한다면, 더 좋은 방법이 있을 것 같습니다.

checkAvailablity 메서드에서 이미 재고를 판단하고 있으니, 그 정보를 활용하면 좋을 것 같아요.

2023-09-21 12:37 UTC, forestjae approved these changes

2023-09-21 12:37 UTC, merged