쥬스 자판기 [STEP 3] bello, comdori
tasty-code/ios-juice-maker pull request #60
Opened 2023-09-21 01:51 UTC by comdori-wj

리뷰어: @corykim0829

팀원: @JinUng41, @comdori-wj

---

안녕하세요! bello, comdori입니다.

쥬스자판기 [STEP 3] 구현해 보았습니다.

- [STEP 2] 수정사항 반영
- 화면 이동 방식을 변경
- `UIStepper`를 이용한 재고 수정
- 변경된 재고에 대한 UI업데이트

아래에는 저희가 구현하면서 궁금증이 생겼던 부분들 또는 고민한 내용들에 대해서 적어보았습니다.

읽어보시고 코멘트 남겨주시면 감사하겠습니다!! 🙏🙏

---

## `private`, `Final` 키워드 반드시 붙여야 할까요? 😑

- 두 키워드는 반드시 사용할 필요는 없다고 생각합니다.
    - 그러나 유지 보수성, 성능을 향상시키려면 사용하는 것이 좋다고 합니다.
- 두 키워드를 사용하면 성능 향상이 되는 이유가 뭔지 공부해보았습니다.
    - 스위프트는 기본적으로 Dynamic Dispatch를 사용하여 매번 메서드가 호출될 때마다 메서드 테이블에서 해당 메서드를 찾고, 그 메서드를 호출하는 방식을 사용하기 때문에 느리지만, private 키워드는 Static Dispatch를 사용하여 컴파일 시점에 어떤 메소드가 사용될지 명확하게 결정되어 빠르게 사용할 수 있습니다.
    - `final` 키워드를 클래스에 사용하면 상속이 불가능하고 메서드나 프로퍼티에 붙을 경우네는 하위 클래스에서 오버라이딩 할 수 없기 때문에 Static Dispatch로 작동하게 되어 성능 향상이 됩니다.
- 하지만 다음의 경우에는 성능 향상이 되지 않을수 있습니다.
    - 상속을 통해 동작을 변경해야 하는 경우
    - 다른 클래스에서 참조할 필요가 있는 경우
    - 성능을 향상시키기 위해 상속을 허용하고자 하는 경우

> **결론 : 무조건 붙여서 사용하기 보다는 성능 향상의 가능성을 고려하여 알맞게 사용 하면 된다고 생각합니다.**

## 화면 전환에 대한 고민

[STEP 2]까지는 네비게이션 방식의 `push`& `pop`을 사용하여 화면 전환을 하였습니다.

[STEP 3]에서 ‘닫기’라는 버튼을 생성하여 첫 번째 화면으로 이동하는 것을 요구하고 있습니다.

`backButton`이 생기기 때문에 `push` & `pop` 이 적합하지 않다고 판단하였습니다.

그래서 `present`를 이용하여 두 번째 화면을 모달로 띄우도록 수정하였습니다.

```swift
private func moveInventoryVC () {
    guard let inventoryVC = self.storyboard?.instantiateViewController(identifier: "Inventory") as? FruitInventoryViewController else {
        return
    }
    inventoryVC.juiceMaker = self.juiceMaker
    let navigationVC = UINavigationController(rootViewController: inventoryVC)
    present(navigationVC, animated: true)
}
```

허나 다음과 같이 구현하였을 때 두번째 화면에서 재고를 수정하고 첫번째 화면으로 이동할 때, `MainViewController`에서 `viewWillAppear`가 호출되지 않는 문제가 발생하였습니다.

그래서 문서를 찾아 보니 `modalPresentationStyle` 에 대해서 정의를 하지 않았을 때, 기본적으로 `automatic`으로 동작한다는 것을 알 수 있었습니다.

또한 `automatic`은 UIKit에서 대부분의 경우 해당 스타일을 `pageSheet`로 매핑한다는 것도 알 수 있었습니다.실제로 프로젝트에서도 `modalPresentationStyle` 을 출력을 해보았을 때 ‘rawValue: 1’ 즉,`pageSheet`로 띄워지는 것을 알 수 있었습니다.

그래서 `viewWillAppear`를 호출하기 위해 화면을 완전히 덮는 `fullScreen`으로 띄울 수 있도록 하여 문제를 해결할 수 있었습니다.

```swift
navigationVC.modalPresentationStyle = .fullScreen
```

### 참고 자료

[modalPresentationStyle | Apple Developer Documentation](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621355-modalpresentationstyle)
[UIModalPresentationStyle.automatic | Apple Developer Documentation](https://developer.apple.com/documentation/uikit/uimodalpresentationstyle/automatic)

## 스크린 샷

<img src = "https://raw.githubusercontent.com/comdori-wj/ios-juice-maker/step3/Screenshots/%EC%A5%AC%EC%8A%A4_%EC%9E%90%ED%8C%90%EA%B8%B0_%EC%8B%A4%ED%96%89%ED%99%94%EB%A9%B4.gif">

<img src="https://raw.githubusercontent.com/comdori-wj/ios-juice-maker/step3/Screenshots/1.%EC%8B%9C%EC%9E%91%ED%99%94%EB%A9%B4.png">

<img src="https://raw.githubusercontent.com/comdori-wj/ios-juice-maker/step3/Screenshots/2.%EB%94%B8%EB%B0%94%EC%A5%AC%EC%8A%A4_%EC%A3%BC%EB%AC%B8.png">

<img src="https://raw.githubusercontent.com/comdori-wj/ios-juice-maker/step3/Screenshots/3.%EB%94%B8%EA%B8%B0%EC%A5%AC%EC%8A%A4_%EC%A3%BC%EB%AC%B8_%EB%B0%8F_%EC%9E%AC%EA%B3%A0_%EB%B6%80%EC%A1%B1.png">

<img src="https://raw.githubusercontent.com/comdori-wj/ios-juice-maker/step3/Screenshots/4.%EC%9E%AC%EA%B3%A0_%ED%99%94%EB%A9%B4_%EC%9D%B4%EB%8F%99.png">

<img src = "https://raw.githubusercontent.com/comdori-wj/ios-juice-maker/step3/Screenshots/5.%EC%9E%AC%EA%B3%A0_%EC%88%98%EC%A0%95_%ED%9B%84.png">

<img src = "https://raw.githubusercontent.com/comdori-wj/ios-juice-maker/step3/Screenshots/6.%EC%9D%B4%EC%A0%84_%ED%99%94%EB%A9%B4%EC%9C%BC%EB%A1%9C_%EB%8F%8C%EC%95%84%EC%98%A4%EA%B8%B0.png">

<img src = "https://raw.githubusercontent.com/comdori-wj/ios-juice-maker/step3/Screenshots/7.%EB%94%B8%EA%B8%B0%EC%A5%AC%EC%8A%A4_%EC%A3%BC%EB%AC%B8_%EC%84%B1%EA%B3%B5.png">

2023-09-21 16:40 UTC, corykim0829 requested changes
수고 많으셨습니다!! 👍👍👍

---
### 궁금한점에 대한 답변
> private, Final 키워드 반드시 붙여야 할까요? 😑

해당 내용을 잘 공부하시고 정리하신 것 같아요! 뿌듯합니다 ☺️
동적, 정적 Dispatch를 지금은 이정도만 이해해도 충분히 private과 final은 잘 활용하실 것 같습니다! 👍

> 화면전환에 대한 고민

viewWillAppear가 호출되지 않는다는 이슈를 기반으로 잘 풀어내신 것 같아요!

시간이 여유가 되신다면, navigationController에서 pop/push로도 같은 동작을 하는 코드를 작성해보면 좋을 것 같습니다!

이 과정에서 데이터 전달에 대한 고민도 할 수 있을 것 같아요!

2023-09-21 16:40 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +    @IBAction func orderJuice(_ sender: UIButton) {
버튼 클릭에 대한 메서드명은 전반적으로 통일해주면 좋습니다. 위에서 사용한 closeButtonTapped처럼요!
그래야 확실하게 이 함수는 버튼의 액션으로 사용되는 함수임을 인지할 수 있습니다. 참고하세요!

2023-09-22 01:51 UTC, comdori-wj commented on JuiceMaker/JuiceMaker/Controller/FruitInventoryViewController.swift
> +            }
> juiceMaker 옵셔널 바인딩은 forEach 안에 없어도 될 것 같습니다!
네, `juiceMaker`가 반복문을 실행할때 마다 옵셔널 바인딩을 하지 않도록 밖으로 뺏습니다.

> 여기도 마찬가지로 tempJuiceMaker라고 하지 않고, juiceMaker라고하면 더 깔끔할 것 같습니다!
네, 변경하였습니다!

2023-09-22 01:54 UTC, comdori-wj commented on JuiceMaker/JuiceMaker/Controller/FruitInventoryViewController.swift
> +            guard let tempStepper = stepper, let id = tempStepper.accessibilityIdentifier else {
네! 깔끔한 네이밍을 만들도록 노력하겠습니다.

2023-09-22 01:56 UTC, comdori-wj commented on JuiceMaker/JuiceMaker/Controller/FruitInventoryViewController.swift
> +                guard let fruit = try Fruit(id) else {
네, 수정하였습니다.

2023-09-22 01:59 UTC, comdori-wj commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +        guard let inventoryVC = self.storyboard?.instantiateViewController(identifier: "Inventory") as? FruitInventoryViewController else {
`let invetoryViewControllerIdentifier = "Inventory"` 로 수정 하였는데 의도하신게 맞는지 모르겠습니다. 
왜 변경하면 좋을지도 궁금합니다! 🤔

2023-09-22 01:59 UTC, comdori-wj commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +    @IBAction func orderJuice(_ sender: UIButton) {
네 통일성을 위해 수정하였습니다.

2023-09-22 02:01 UTC, comdori-wj commented
모든 사항 반영하여 업데이트 하였습니다.
추가로 고민하여 더 좋은 로직을 구현할 부분이 있으면 적용해보겠습니다. 감사합니다!

2023-09-22 02:34 UTC, JinUng41 commented
말씀해 주셨던 `push`/ `pop`로 화면 전환을 구현해보았습니다.

```swift
// MainViewController 에서..
private func moveInventoryVC () {
    let invetoryViewControllerIdentifier = "Inventory"
    guard let inventoryVC = self.storyboard?.instantiateViewController(identifier: invetoryViewControllerIdentifier) as? FruitInventoryViewController else {
        return
    }
    inventoryVC.juiceMaker = self.juiceMaker
    self.navigationController?.pushViewController(inventoryVC, animated: true)
}
```

- `push` 를 이용하여 두 번째 화면으로 넘어가도록 하였습니다.
- 데이터 전달은 기존과 같이 `FruitInventoryViewController`에서 저장 속성으로 선언한 `juiceMaker` 에 할당하였습니다.
- 하지만 이렇게 구현하게 되면, 프로젝트 요구와 다르게 네비게이션 자체에서 `backButton`이 생깁니다.
- 따라서 버튼이 생기지 않도록 다음의 코드를 작성하였습니다.

```swift
// FruitInventoryViewController 에서...
override func viewDidLoad() {
    // ... 기존 내용과 동일
    self.navigationItem.hidesBackButton = true
}
```

- 위의 코드를 통해 두번째 화면에서 `backButton`을 숨기도록 하였습니다.

두 번째 화면에서 다시 돌아올 때에는 `pop` 방식을 통해 구현하였습니다.

```swift
// FruitInventoryViewController 에서...
@IBAction func closeButtonTapped(_ sender: UIBarButtonItem) {
    self.navigationController?.popViewController(animated: true)
}
```

- 데이터 전달 방식에서 변화가 없지만 UI에 반영이 되는 이유는 결국에 `MainViewController`에서 `viewWillAppear`가 호출되기 때문입니다.
- modal의 `fullScreen` 방식과 `push`/ `pop` 방식은 UI 업데이트 과정에서 동일한 방식으로 작동하게 하였습니다.

2023-09-22 06:29 UTC, comdori-wj commented
화면 이동을 `segue`(push) 방식으로 구현해보았습니다.

데이터 전달을 위해 prepare함수를 재정의 하였습니다.

```swift
// MainViewController 에서..
override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        let mainIdentifier = "move"
        if segue.identifier == mainIdentifier {
            let vc = segue.destination as? FruitInventoryViewController
            vc?.juiceMaker = self.juiceMaker
        }
    }
```

재고 부족 알림창에서 “예”를 눌렀을 때 segue가 동작하도록 구현하였습니다.

```swift
private func juiceMakeFailAlert(message: String) {
        let alert = UIAlertController(title: message, message: nil, preferredStyle: .alert)
        let yesAction = UIAlertAction(title: "예", style: .destructive) { _ in
            self.performSegue(withIdentifier: "move", sender: nil)
            
        }
```

두 번째 화면에서 닫기 버튼을 누를때는 `pop` 방식을 통해 구현하였습니다.
```swift
// FruitInventoryViewController 에서...
@IBAction func closeButtonTapped(_ sender: UIBarButtonItem) {
    self.navigationController?.popViewController(animated: true)
}
```

2023-09-22 06:41 UTC, JinUng41 commented
수정사항을 반영하던 도중, `MainViewController`에서 Alert를 띄우는 함수의 내용이 다소 중복적이다고 생각되어 하나의 함수로 합쳐 구현해 보았습니다.
함수 내부에서 조건을 통해 각기 다른 Alert를 띄울 수 있도록 하였습니다.
 ```swift
private func displayAlert(message: String) {
    let alert = UIAlertController(title: message, message: nil , preferredStyle: .alert)
    let yesAction = UIAlertAction(title: "예", style: .default) { _ in
        if message == InventoryError.noLongerConsumeError.description {
            self.moveInventoryVC()
        }
    }
    alert.addAction(yesAction)
    if message == InventoryError.noLongerConsumeError.description {
        let noAction = UIAlertAction(title: "아니오", style: .destructive)
        alert.addAction(noAction)
    }
    present(alert, animated: true)
}
```

2023-09-22 08:37 UTC, JinUng41 commented
현재 구현 방식은 MainViewController에서 `viewWillAppear`가 무조건적으로 호출되고 있습니다. 하지만 재고가 변경되지 않았을 때는 `viewWillAppear`가 불리는 것은 메모리 낭비라고 생각하게 되었습니다. 현재 프로젝트에서는 비교적 간단한 작업이지만, 후에 네트워크가 개입되는 동작의 경우 리소스가 낭비되는 현상이 발생할 것이라 생각하게 되었습니다. 그래서 현재의 방식을 해결할 수 있는 다른 방법이 있는지 궁금합니다!!

2023-09-25 14:45 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +        guard let inventoryVC = self.storyboard?.instantiateViewController(identifier: "Inventory") as? FruitInventoryViewController else {
스토리보드에 들어가는 String값은 변경될 수 있고, 여기에 들어가는 identifier도 변경될 수 있기 때문에 유지보수 때문에 따로 관리가 필요합니다!

String(describing:)을 쓰는 것도 좋은 방법이에요! 참고하세요 :)

2023-09-25 14:54 UTC, corykim0829 commented
답변이 많이 늦어져서 죄송합니다 😢

먼저 화면이동에서 여러 방법을 시도를 해본 점이 아주 좋습니다! 👍👏👏👏👏

과일가게 프로젝트 동안 정말 수고 많으셨고 두분의 열정과 성장을 느낄 수 있어서 좋은 프로젝트 과정이었습니다! 👍
추석 잘 보내세요 :)

> 수정사항을 반영하던 도중, MainViewController에서 Alert를 띄우는 함수의 내용이 다소 중복적이다고 생각되어 하나의 함수로 합쳐 구현해 보았습니다.
함수 내부에서 조건을 통해 각기 다른 Alert를 띄울 수 있도록 하였습니다.

➡️ AlertController를 띄우는 과정이 다소 복잡하게 느껴질 수 있지만, 이렇게 분기처리를 하면 유지보수에 불리하게 됩니다. 조금 불필요하게 느껴지더라도 각 alert 처리를 함수로 만들어서 처리하면 더 깔끔하고 좋을 것 같습니다:)

> 현재 구현 방식은 MainViewController에서 viewWillAppear가 무조건적으로 호출되고 있습니다. 하지만 재고가 변경되지 않았을 때는 viewWillAppear가 불리는 것은 메모리 낭비라고 생각하게 되었습니다. 현재 프로젝트에서는 비교적 간단한 작업이지만, 후에 네트워크가 개입되는 동작의 경우 리소스가 낭비되는 현상이 발생할 것이라 생각하게 되었습니다. 그래서 현재의 방식을 해결할 수 있는 다른 방법이 있는지 궁금합니다!!

➡️ 메모리 낭비라고 말하기는 어렵습니다! `현재 구현 방식은 MainViewController에서 viewWillAppear가 무조건적으로 호출되고 있습니다.` MainViewController는 UIViewController를 상속하여 viewWillAppear를 오버라이딩한다는 점을 인지하고 다시 이 이슈에 접근해보면 좋을 것 같습니다!

2023-09-26 00:52 UTC, JinUng41 commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +        guard let inventoryVC = self.storyboard?.instantiateViewController(identifier: "Inventory") as? FruitInventoryViewController else {
네! 알겠습니다.

2023-09-26 00:58 UTC, JinUng41 commented
Alert 함수에 대해서는 다시 분리하여 작성하였습니다.
`viewWillAppear`가 매번 호출되는데 이 때 `updateFruitLabels`함수를 호출합니다.
재고가 변경되지 않았을 때 해당 함수를 호출하게 되면 그 과정이 필요없지 않나 라는 생각에 질문드렸었습니다.
감사합니다!!🙏🙏

2024-01-02 01:30 UTC, Tacocat-tastycode commented
프로젝트 진행 기간 종료로 PR Close

2024-01-02 01:30 UTC, closed without merging