쥬스 자판기 [STEP 3] Janine, JaeHyeok
tasty-code/ios-juice-maker pull request #63
Opened 2023-09-22 02:57 UTC by SimJaeHyeok

리뷰어: @protocorn93
버드: @janine-kang, @SimJaeHyeok

## 콘, 안녕하세요! [STEP 3] PR 드립니다🙌🏻

## Summary ⛳️

### 구동 영상 🐳
![play1](https://github.com/tasty-code/ios-juice-maker/assets/142188004/128e10fc-20f3-4530-9163-ced72b0d47a3)

[STEP 2]에서 만들었던 쥬스 자판기의 UI를 구현하였습니다

### 구현 기능 및 상세

- 화면 제목 '재고 추가' 및 '닫기' 버튼 구현
    - 닫기를 터치하면 이전화면으로 복귀
- 화면 진입시 과일의 현재 재고 수량 표시
- , + 를 통한 재고 수정
- iPhone 12 외에 다른 시뮬레이터에서도 UI가 정상적으로 보일 수 있도록 오토레이아웃 적용

---

### 고민했던 점 👀
- [STEP 2]에서 둘이서 고민했을 때는 다른 여러 과일이 추가되었을 경우를 생각해서 `StackView`에 접근하여 `Label`을 수정하는 방법을 사용했었는데요 콘의 조언을 듣고 간단한 프로젝트에선 코드도 복잡해지고 불필요하다 생각을 해서  직접 각각의 `Label`을  연결하여 수정하는 방법을 채택했는데요 큰 프로젝트에서 `StackView`에 접근해서 사용하는 경우도 있는 지 궁금합니다.

- 앞서 여쭤봤던 Singleton 패턴을 고민 끝에 사용하지 않게 되었습니다. 이유는 화면 전환 방식을 Modality로 변경하게 되었기 때문인데요.
STEP2에서는 `Navigation Stack`을 이용한 화면 전환방식을 채택해, FruitStore를 Singleton 패턴으로 변경하여 View 간 데이터 공유에 활용하고자 했습니다. 이후 기존 View로 돌아오게 될 때 `viewWillAppear()`에서 뷰의 업데이트를 수행하고자 계획했습니다.
그러나 구현사항에 Modality의 활용이 적혀있어 화면 전환 방식을 Modality로 변경하게 되었고, 그러다보니 기존 뷰의 업데이트 과정에서 `viewWillAppear()`를 사용하지 못한다는 것을 알게 되었습니다. 때문에 `뷰의 업데이트 방식을 Delegate 패턴으로` 진행하게 되었고, Singleton을 이용한 데이터 공유가 캡슐화보다 더 적은 Benefit을 가져온다고 생각하게 되어 다시 STEP1에서 설계했던 것 처럼 캡슐화를 하게 되었습니다. 이러한 판단에 대해서 콘의 의견이 궁금합니다.

2023-09-23 13:46 UTC, protocorn93 requested changes
두 분 모두 고생하셨습니다. 

## 고민한 점
> [STEP 2]에서 둘이서 고민했을 때는 다른 여러 과일이 추가되었을 경우를 생각해서 StackView에 접근하여 Label을 수정하는 방법을 사용했었는데요 콘의 조언을 듣고 간단한 프로젝트에선 코드도 복잡해지고 불필요하다 생각을 해서 직접 각각의 Label을 연결하여 수정하는 방법을 채택했는데요 큰 프로젝트에서 StackView에 접근해서 사용하는 경우도 있는 지 궁금합니다.

일단 먼저 많은 회사들이 스토리보드를 사용하지 않고 코드로 UI를 작성하곤 합니다. 이에 대해선 프로젝트를 진행하면서 프로젝트와는 별개로도 학습해보시면 좋을 것 같아요. 

만약 제가 회사에서 해당 화면/기능을 만들게 되었다면 모두 동적으로 화면을 구성했을 것 같네요. 이를 위해 `UILabel`, `UIStepper`를 갖는 별도 커스텀 뷰를 구현했을 것 같아요. 

그리고 별도 커스텀 뷰에는 해당 뷰를 표현하기 위한 뷰모델이 각각 매핑되겠구요. 각 뷰모델은 각 Fruit 모델을 갖고 있을 것 같아요. 정확히는 Fruit을 화면에 표현하기 위한 String 타입과 갯수를 나타내는 Int 타입의 프로퍼티를 가질 것이구요. 또한 해당 뷰모델이 각자 어떤 과일을 표현하는지 식별하기 위한 값이 존재할 것 같아요. `Fruit` case가 될 것이구요. 

(뷰모델의 개념에 대해선 추가로 학습해보시면 앞으로 많이 활용하게 될 개념일 것 같아요. )

이렇게 동적으로 구성된다면 개별 UI 요소가 과일 이름을 갖지 않고 뷰모델의 식별값으로만 다뤄질 수 있겠죠! 

> 앞서 여쭤봤던 Singleton 패턴을 고민 끝에 사용하지 않게 되었습니다. 이유는 화면 전환 방식을 Modality로 변경하게 되었기 때문인데요.
STEP2에서는 Navigation Stack을 이용한 화면 전환방식을 채택해, FruitStore를 Singleton 패턴으로 변경하여 View 간 데이터 공유에 활용하고자 했습니다. 이후 기존 View로 돌아오게 될 때 viewWillAppear()에서 뷰의 업데이트를 수행하고자 계획했습니다.
그러나 구현사항에 Modality의 활용이 적혀있어 화면 전환 방식을 Modality로 변경하게 되었고, 그러다보니 기존 뷰의 업데이트 과정에서 viewWillAppear()를 사용하지 못한다는 것을 알게 되었습니다. 때문에 뷰의 업데이트 방식을 Delegate 패턴으로 진행하게 되었고, Singleton을 이용한 데이터 공유가 캡슐화보다 더 적은 Benefit을 가져온다고 생각하게 되어 다시 STEP1에서 설계했던 것 처럼 캡슐화를 하게 되었습니다. 이러한 판단에 대해서 콘의 의견이 궁금합니다.

네네! 전 사실 이 프로젝트에선 구현해주신 delegate 패턴이 더 적합하다고 판단했어요. 한 화면에서 다음 화면으로 넘어가고 그 화면에서 다시 이전 화면으로 데이터를 전달해줄 땐 보통 이렇게 delegate 패턴을 통해 액션의 결과를 전달해주곤 해요. 

싱글톤은 보통 앱 전역에서 알고 있어야 하는 정보들을 다루는데 사용되곤 하구요. 그리고 싱글톤에선 다양한 동시성 문제를 직면할 수 있기 때문에 이에 대한 보완 작업도 필요하죠. 

현재 프로젝트에선 Main 화면에서만 원본 데이터를 갖고 있고, 재고 조정 화면에 진입할 때 해당 데이터를 함께 전달하고 (여러분이 현재 해주신 것처럼요!) 액션의 결과( 재고 추가 )를 delegate로 전달받고 Main에서 갱신해주면 될 것 같아요.

2023-09-23 13:46 UTC, protocorn93 commented on JuiceMaker/JuiceMaker/Controller/DashboardViewController.swift
> +        switch sender.tag {
태그를 잘 활용해주셨네요👍

2023-09-23 13:46 UTC, protocorn93 commented on JuiceMaker/JuiceMaker/Controller/DashboardViewController.swift
> +        case 0:
`rawValue`가 `Int`인 enum 으로 모델링한다면 좀 더 읽기 좋은 분기문이 될 것 같네요.

2023-09-23 13:46 UTC, protocorn93 commented on JuiceMaker/JuiceMaker/Controller/DashboardViewController.swift
> +            fruitData[0].1.text = Int(sender.value).description
`fruitData` 배열에 `index`로 접근할 때 좀 더 안전한 방법이 있을지 찾아보시면 좋을 것 같아요. fruitData의 내부 상태를 보장할 수 없기 때문에 좀 더 안전한 방법을 찾아보시면 좋을 것 같아요.

2023-09-23 13:46 UTC, protocorn93 commented on JuiceMaker/JuiceMaker/Controller/DashboardViewController.swift
> +    var fruitDataSet: [(Fruit, UILabel, UIStepper)]?
어떤 과일이 어떤 `UILabel`, `UIStepper`와 연관되어있는지를 알기 위해 이렇게 작성해주신 것 같은데요. UILabel도 각 과일에 따라 네이밍 되었듯이, UIStepper도 그렇게 가져가는 방법이 있을 것 같구요. 

그게 아니라면 UILabel, UIStepper를 갖는 별도 커스텀 뷰를 정의하고 해당 뷰의 별도 뷰모델을 가져가는 방법도 있을 것 같아요. 이 방법은 현재 스탭보단 이후에 나머지 프로젝트를 진행하시면서 고민해보시면 좋을 것 같네요.

2023-09-23 13:46 UTC, protocorn93 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        dashboardVC.juiceMakerModel = self.juiceMakerModel
이렇게 프로퍼티에 직접 의존성을 주입해주는 방법도 있구요. 의존성을 주입해주는 다양한 방법이 있어요. 각 방법에 대해 공부를 해보시면 이후 스탭을 진행하고 학습을 하시는데 많은 도움이 되실거에요. 

의존성 주입을 해주는 이유에 대해서 학습하다보시면 자연스럽게 객체지향의 개념도 접하시게 되실거구요.

2023-09-25 01:35 UTC, janine-kang commented on JuiceMaker/JuiceMaker/Controller/DashboardViewController.swift
> +    @IBOutlet private weak var mangoStepper: UIStepper!
바깥에서 사용하지 않는 부분들을 private 처리 했습니다!

2023-09-25 01:36 UTC, janine-kang commented on JuiceMaker/JuiceMaker/Controller/DashboardViewController.swift
> +final class DashboardViewController: UIViewController {
https://github.com/tasty-code/ios-juice-maker/pull/63/commits/f6cd46200e119c56accef59296a502919ccf9883#r1335300556

넵 바깥에서 사용되지 않는 부분에 대해 접근제어 처리했습니다

2023-09-25 01:38 UTC, SimJaeHyeok commented on JuiceMaker/JuiceMaker/Controller/DashboardViewController.swift
> +        case 0:
콘이 주신 조언대로 생각해보니 이미 생성되어있는 `Enum`타입의  Fruit에 `RawValue`만 추가하여 `Tag` 와 매치하여 더 간단하게 만들 수 있었습니다  
```swift
switch Fruit(rawValue: sender.tag) {
        case .strawberry:
            juiceMaker.updateFruitStock(fruit: .strawberry, amount: sender.value)
            strawberryLabel.text = Int(sender.value).description
        case .banana:
            juiceMaker.updateFruitStock(fruit: .banana, amount: sender.value)
            bananaLabel.text = Int(sender.value).description
        case .kiwi:
            juiceMaker.updateFruitStock(fruit: .kiwi, amount: sender.value)
            kiwiLabel.text = Int(sender.value).description
        case .mango:
            juiceMaker.updateFruitStock(fruit: .mango, amount: sender.value)
            mangoLabel.text = Int(sender.value).description
        case .pineapple:
            juiceMaker.updateFruitStock(fruit: .pineapple, amount: sender.value)
            pineappleLabel.text = Int(sender.value).description
        default:
            break
        }
```

2023-09-25 01:40 UTC, janine-kang commented on JuiceMaker/JuiceMaker/Controller/DashboardViewController.swift
기존 데이터셋으로 Fruit과 Label, Stepper를 한번에 묶어둔 부분을 삭제하고 열거형인 Fruit에 Int값의 rawValue 입력을 통해 보다 간단하게 로직 처리했습니다.

기존 `[(Fruit, UILabel, UIStepper)]` -> 변경 후 `switch Fruit(rawValue:)`

2023-09-25 01:42 UTC, janine-kang commented on JuiceMaker/JuiceMaker/Controller/DashboardViewController.swift
> +    var fruitDataSet: [(Fruit, UILabel, UIStepper)]?
https://github.com/tasty-code/ios-juice-maker/pull/63/commits/f6cd46200e119c56accef59296a502919ccf9883#r1335301936

해당 부분 더 나은 방법으로의 고민해봤는데, 우선 안전하게 사용하기 위해 Fruit의 rawValue와 네이밍으로 값을 연관시켜 처리하는 방법으로 선택했습니다.
기존의 데이터 셋에서 각 case에 따른 데이터 사용으로 변경된 셈입니다!

2023-09-25 01:43 UTC, SimJaeHyeok commented on JuiceMaker/JuiceMaker/Controller/DashboardViewController.swift
> +        }
콘이 주신 조언대로 생각해보니 이미 생성되어있는 `Enum`타입의  Fruit에 `RawValue`만 추가하여 `Tag` 와 매치하여 더 간단하게 만들 수 있었습니다

2023-09-25 01:50 UTC, SimJaeHyeok commented on JuiceMaker/JuiceMaker/Controller/DashboardViewController.swift
> +        }
콘이 주신 조언대로 이미 생성되어있는 Enum타입의 Fruit에 RawValue만 추가해서 Tag와 매치하여 조건 분기를 하여 더 간단하게 코드를 작성할 수 있었습니다.

2023-09-25 01:51 UTC, SimJaeHyeok commented on JuiceMaker/JuiceMaker/Controller/DashboardViewController.swift
> +        case 0:
https://github.com/tasty-code/ios-juice-maker/pull/63#discussion_r1335306123

2023-09-25 01:52 UTC, janine-kang commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        dashboardVC.juiceMakerModel = self.juiceMakerModel
찾아보니 프로퍼티를 통한 의존성 주입은 캡슐화를 저해하는 단점이 있기도 하네요! 이번 기회에 의존성 주입에 관해서도 공부해보겠습니다. 감사합니다 콘 🙇🏻‍♀️

2023-09-25 01:58 UTC, SimJaeHyeok commented on JuiceMaker/JuiceMaker/Controller/DashboardViewController.swift
> +            fruitData[0].1.text = Int(sender.value).description
![image](https://github.com/tasty-code/ios-juice-maker/assets/142188004/fc7f35b9-d7f9-48ba-95a5-a50f113b7d31)
위에 주신 조언대로 코드를 작성하여 복잡한 `Array` 사용하지 않는 방법을 채택하였습니다.

2023-09-26 01:05 UTC, merged