쥬스 자판기 [STEP 3] 뉴준성, 쫑
tasty-code/ios-juice-maker pull request #64
Opened 2023-09-22 06:27 UTC by shlim0

## 리뷰어

@jryoun1

## 파일구조

- 추가된 부분은 **볼드처리** 하였습니다.
- JuiceMaker
    - Protocols
        - **FruitShowable**
    - Controller
        - JuiceMenuViewController
        - FruitInvetoryViewController
    - Model
        - FruitStore
        - FruitType
        - JuiceMaker
        - JuiceMakerException
        - JuiceType
    - View

## 변경사항

### 1. UILabel과 UIStepper의 컬렉션화

여러 개의 `UILabel`과 `UIStepper`를 개별적으로 관리하다 보니, UI 컴포넌트들을 초기화하거나 내부 값을 변경하는 과정에서 불필요하게 코드가 많아졌습니다.

**Jake**가 저번 ***STEP 2*** 리뷰에서 알려주신 방법으로 `IBOutlet Collection`을 활용하여 좀 더 수월하게 UI 컴포넌트들을 관리할 수 있게 됐습니다.

감사합니다! **Jake**!🙏

- **기존 코드**

```swift
@IBOutlet weak var strawberryCountLabel: UILabel!
@IBOutlet weak var bananaCountLabel: UILabel!
@IBOutlet weak var pineappleCountLabel: UILabel!
@IBOutlet weak var kiwiCountLabel: UILabel!
@IBOutlet weak var mangoCountLabel: UILabel!

@IBOutlet private var strawberryStepper: UIStepper!
@IBOutlet private var bananaStepper: UIStepper!
@IBOutlet private var pineappleStepper: UIStepper!
@IBOutlet private var kiwiStepper: UIStepper!
@IBOutlet private var mangoStepper: UIStepper!

private func setEventActionOfStepper(){
    strawberryStepper.addTarget(self, action: #selector(stepperValueChanged(_:)), for: .valueChanged)
    bananaStepper.addTarget(self, action: #selector(stepperValueChanged(_:)), for: .valueChanged)
    pineappleStepper.addTarget(self, action: #selector(stepperValueChanged(_:)), for: .valueChanged)
    kiwiStepper.addTarget(self, action: #selector(stepperValueChanged(_:)), for: .valueChanged)
    mangoStepper.addTarget(self, action: #selector(stepperValueChanged(_:)), for: .valueChanged)
}
```

- **변경된 코드**

```swift
@IBOutlet private var fruitsCountLabels: [UILabel]!
@IBOutlet private var fruitsCountSteppers: [UIStepper]!

private func setEventActionOfStepper(){
    for fruitsCountStepper in fruitsCountSteppers {
        fruitsCountStepper.addTarget(self, action: #selector(stepperValueChanged(_:)), for: .valueChanged)
    }
}
```

## 고민했던 점

### 1. 두 ViewController 간의 중복된 함수를 하나로 묶기 위한 방법

`JuiceMenuViewController`와 `FruitInventoryViewController`에서 `UILabel`의 텍스트를 변경해주는 함수가 동일했습니다. 저희는 이 문제를 해결하기 위해 `protocol`을 사용하기로 결정했고, 이 `protocol`에 `UIView`에서의 과일 재고를 표시해주는 기능과 관련된 함수들을 담기로 했습니다. 이 과정에서 `UIStepper`의 `value`를 변경해주는 것 또한 과일 재고를 표시해주는 기능과 관련된 함수라고 생각해서 `protocol`에 담기로 했습니다. 이후 각 ViewController에서 `protocol`을 채택해서 함수를 따로 만들지 않고 바로 사용할 수 있도록 했습니다.

- **중복된 코드**

```swift
// JuiceMenuViewController.swift
// And FruitInventoryViewController.swift
private func setFruitCountToLabel(_ fruit: Fruit) {
    let (fruitType, fruitCount) = fruit
    
    fruitsCountLabels[fruitType.rawValue].text = String(fruitCount)
}
```

```swift
// FruitInventoryViewController.swift
private func setFruitCountToStepperValue(_ fruit: Fruit) {
    let (fruitType, fruitCount) = fruit
    
    fruitsCountSteppers[fruitType.rawValue].value = Double(fruitCount)
}
```

- **변경된 코드**

```swift
// FruitShowable.swift
import UIKit

protocol FruitShowable {}

extension FruitShowable {
		// 기존 setFruitCountToLabel()
    func show(_ fruit: Fruit, on fruitsCountLabels: [UILabel]) {
        let (fruitType, fruitCount) = fruit

        fruitsCountLabels[fruitType.rawValue].text = "\(fruitCount)"
    }

		// 기존 setFruitCountToStepperValue()
    func show(_ fruit: Fruit, on fruitsCountSteppers: [UIStepper]) {
        let (fruitType, fruitCount) = fruit

        fruitsCountSteppers[fruitType.rawValue].value = Double(fruitCount)
    }
}
```

- **변경된 코드를 사용하는 모습**

```swift
// FruitInventoryViewController.swift
override func viewWillAppear(_ animated: Bool) {
    super.viewWillAppear(animated)
    
    for fruitType in FruitType.allCases {
        guard let fruitCount = FruitStore.shared.fruitCounts[fruitType] else {
            return
        }
        
        let fruit = Fruit(fruitType, fruitCount)
        show(fruit, on: fruitsCountLabels)
        show(fruit, on: fruitsCountSteppers)
    }
}
```

### 2. 화면 전환 방식을 show(push)에서 modal로 변경
<img width="720" alt="1" src="https://github.com/tasty-code/ios-juice-maker/assets/46235301/e5139568-e758-4525-9a77-72447803f0db">

위의 이미지는 ***STEP 3***에서 요구하는 과일 재고 추가 화면입니다. 상단의 `재고 추가`를 보면 `닫기`버튼을 통해 쥬스 주문 화면으로 넘어가게 되어있습니다. ***STEP 2***에서 저희 코드는 버튼을 통한 뒤로가기 및 제스쳐를 통한 뒤로가기를 지원했습니다. 따라서 저희는 이 뷰를 NavigationController를 통한 화면 전환이 아닌 modal 방식으로 바꿨습니다.

- 참고. ***STEP 2***에서의 재고 추가 화면
<img width="694" alt="2" src="https://github.com/tasty-code/ios-juice-maker/assets/46235301/ddf2f242-5e2c-4fd6-8579-a0a149509d19">

참고. ***STEP 2***에서의 재고 추가 화면

그런데 modal 방식로 바꾸고 나니 두 가지 문제점이 생겼습니다. *첫 번째는* 재고 추가 제목과 닫기 버튼을 어떻게 배치할 지에 대한 문제였고, *두 번째는* 재고를 변경해도 주스 메뉴 화면에 과일 재고는 변경되지 않는다는 것이었습니다.

- *첫번째 문제를 해결하기 위해,* present를 할 때 `FruitInventoryViewController` 를 `NavigationController`에 넣은 다음, 제목과 닫기 버튼을 추가했습니다.
- *두번째 문제를 해결하기 위해,* modal 방식의 화면 전환 방식을 조사한 결과, `modalPresentationStyle.automatic`이 기본값이며 이 경우 대부분 `.pageSheet` 방식으로 작동한다는 것을 알아냈습니다. 이 방식을 사용하면, 뷰가 메모리에 남아있는 상태에서 되돌아갔을 때, `viewWillAppear()`를 작동시키지 않았습니다. 이를 해결하기 위해 `modalPresentationStyle.fullScreen` 으로 설정하여 닫기 버튼을 누르면 쥬스 메뉴로 돌아갔을 때, `viewWillAppear()`가 작동되도록 했습니다.
- **기존 코드**

```swift
guard let fruitInventoryViewController = self.storyboard?.instantiateViewController(identifier: "FruitInventoryViewController") else {
    return
}

self.navigationController?.pushViewController(fruitInventoryViewController, animated: true)
```

- ****************************변경된 코드****************************

```swift
guard let fruitInventoryViewController = self.storyboard?.instantiateViewController(identifier: "FruitInventoryViewController") else {
    return
}

**let navigationController = UINavigationController(rootViewController: fruitInventoryViewController)
navigationController.modalPresentationStyle = .fullScreen

self.present(navigationController, animated: true)**
```

## 궁금한 점

### 1. 바인딩하는 것이 옳은 것일까?

이전 질문에서 바인딩을 하는 방법으로 **Jake**가 알려준 KVO, Notification, Delegate pattern 중 하나를 사용하려 했습니다. 

- *KVO의 경우*, `[FruitType: Int]`로 구성된 `fruitsCount`를 `@objc` 를 적용하려는 과정에서 Objective-C로 표현할 수 없다는 컴파일 에러가 나와서 사용할 수 없었습니다.
- *Delegate pattern의 경우*, 다른 팀이 이 패턴을 적용 했기에 저희는 다른 방법으로 해결해보고자 했습니다. 다른 방법으로 해결해서, 그 지식을 다른 팀에게 공유하면 더 좋을 것 같다는 판단이었습니다.
- *따라서,* Notification을 활용하는게 좋겠다고 생각했습니다.

Notification을 적용하기 위해 Command Line Tools를 활용하여 연습을 진행했습니다. 하지만 구현을 마치고 나니 저희 프로젝트에 굳이 적용할 필요성이 느껴지지 않게 되었습니다. 왜냐하면, 싱글턴 패턴을 통해서 과일의 재고에 바로 접근할 수 있기 때문입니다. 또, 기존에 과일의 재고를 뷰에 업데이트 하는 함수를 호출 했을 때와 비교했을 때, `Notification.post()`를 호출하는 방식은 코드 구조의 큰 차이를 가져오지 못한다고 생각했기 때문입니다.

- **연습한 코드**

```swift
// main.swift
import Foundation

let temp = Temp()

try! FruitStore.shared.update(Fruit(.strawberry, 10), as: +)
try! FruitStore.shared.update(Fruit(.banana, 4), as: +)
try! FruitStore.shared.update(Fruit(.banana, 4), as: +)
try! FruitStore.shared.update(Fruit(.mango, 5), as: +)
try! FruitStore.shared.update(Fruit(.pineapple, 240049283), as: +)
try! FruitStore.shared.update(Fruit(.kiwi, 4), as: +)

// 출력된 내용
// strawberry>>> 20
// banana>>> 14
// banana>>> 18
// mango>>> 15
// pineapple>>> 240049293
// kiwi>>> 14
```

```swift
// Temp.swift
class Temp {
    init() {
        for type in FruitType.allCases {
            NotificationCenter.default.addObserver(self, selector: #selector(hahaha(_:)), name: NSNotification.Name(type.toString()), object: nil)
        }
    }
    
    @objc func hahaha(_ notification: Notification) {
        guard let userInfo = notification.userInfo
        else {
            print("no no userInfo")
            return
        }
        print(userInfo)
        let fruitType = FruitType(rawValue: notification.name.rawValue)!
        print(fruitType)
        print("new>>> \(userInfo[fruitType]!)")
    }
}
```

```swift
// FruitStore.swift
class FruitStore {
    static let shared = FruitStore()
    
    private(set) var fruitCounts: [FruitType: Int] = [:]
    
    private init(count: Int) {
        for type in FruitType.allCases {
            fruitCounts[type] = count
        }
    }
    
    private init(strawberry: Int, banana: Int, pi [...]

2023-09-25 13:29 UTC, jryoun1 requested changes
두 분 다 step3도 고생하셨습니다!
잘 작성해주셔서 크게 수정할 부분은 없어보이긴하네요 👏 💯 

다만 몇 가지 질문사항이 있어서 코멘트에 남겨두었고, PR에 작성해주신 부분에서도 질문이 있어서 여기 코멘트에 질문 남깁니다 🙏 

> 1. 화면 전환 방식을 show(push)에서 modal로 변경

이 부분에서 push에서 modal로 변경하신 이유가 궁금하네요! 
물론 변경해보시면서 modal로 뜰 때 modalPresentationStyle에 따른 viewController의 lifecycle 함수들이 어떻게 호출되는지 공부하시게 된 부분은 엄청 좋네요 👍 👏 

> 2. 바인딩하는 것이 옳은 것일까?

기존의 step들에서 작성해주신 코드에서는 버튼을 누르거나, 뒤로가거나 할 때 버튼의 action을 받아서 처리해주는 함수나 viewController의 lifecycle 함수내부에서 Single으로 구현된 모델에 접근해 값을 업데이트 해주면서 해당 모델의 값을 통해서 실제로 UI까지 업데이트를 시켜주고 있었습니다. 
그런데 두 분께서 바인딩 관련해서 질문을 주셨었는데, 두 분이서 바인딩을 하려고 하셨던 이유가 궁금합니다. 🙋‍♂️

2023-09-25 13:29 UTC, jryoun1 commented on JuiceMaker/JuiceMaker/Controller/FruitInvetoryViewController.swift
> +    @IBOutlet private var fruitsCountSteppers: [UIStepper]!
훨씬 깔끔해졌네요 👏

2023-09-25 13:29 UTC, jryoun1 commented on JuiceMaker/JuiceMaker/Controller/FruitInvetoryViewController.swift
> +        navigationController?.navigationBar.backgroundColor = .lightGray
이 부분도 아래와 마찬가지로 함수로 빼면 가독성이 더 좋을 것 같네요!

2023-09-25 13:29 UTC, jryoun1 commented on JuiceMaker/JuiceMaker/Controller/FruitInvetoryViewController.swift
> +            show(fruit, on: fruitsCountSteppers)
for문 자체도 하나의 함수로 빠지면 더 가독성이 좋을 것 같아요. 🙏

2023-09-25 13:29 UTC, jryoun1 commented on JuiceMaker/JuiceMaker/Protocols/FruitShowable.swift
> +}
빈 프로토콜을 구현하고 extension으로 함수를 구현해주셨는데, protocol에 함수를 선언하지 않고 빈 프로토콜로 구현하신 이유가 궁금합니다 🙋‍♂️

2023-09-25 13:29 UTC, jryoun1 commented on JuiceMaker/JuiceMaker/Protocols/FruitShowable.swift
> +    func show(_ fruit: Fruit, on fruitsCountLabels: [UILabel]) {
show 라는 네이밍은 뭔가(alert, modal, 다음화면 등)를 보여줄 것 같은데, 실제로 함수 내부에서는 label에 text를 설정해주고 있는 것 같아서 네이밍이 명확하지 않은 것 같네요.

2023-09-25 13:29 UTC, jryoun1 commented on JuiceMaker/JuiceMaker/Controller/FruitInvetoryViewController.swift
> +    @IBAction func touchUpCloseButton(_ sender: UIButton) {
IBAction func들은 외부에서 접근해도 괜찮은 함수인가요? (위에도 동일합니다)

2023-09-25 13:29 UTC, jryoun1 commented on JuiceMaker/JuiceMaker/Controller/JuiceMenuViewController.swift
> +        navigationController?.navigationBar.backgroundColor = .lightGray
위에 언급한 부분과 동일합니다!

2023-09-25 13:29 UTC, jryoun1 commented on JuiceMaker/JuiceMaker/Controller/JuiceMenuViewController.swift
> +    @IBAction func modifyInvertoryPressed(_ sender: Any) {
여기도 접근제어 확인부탁드려요 🚨

2023-09-25 13:29 UTC, jryoun1 commented on JuiceMaker/JuiceMaker/Controller/JuiceMenuViewController.swift
> +            self.present(navigationController, animated: true)
동일한 코드가 반복되고 있는것 같은데 함수로 빼면 중복을 줄일 수 있을 것 같네요 🙏

2023-09-25 13:29 UTC, jryoun1 commented on JuiceMaker/JuiceMaker/Protocols/FruitShowable.swift
> +}
또한 말씀주신 중복된 함수를 묶는 방법 중에는 저 방법외에는 다른 방법은 없었을까요? 
UILabel, UIStepper를 extension해서 중복을 줄일 수도 있을 것 같은데 protocol을 사용하신 이유도 궁금합니다.

2023-09-26 00:45 UTC, shlim0 commented on JuiceMaker/JuiceMaker/Controller/JuiceMenuViewController.swift
> +            self.present(navigationController, animated: true)
생각해보니 `재고수정` 버튼을 직접 터치할 때랑, 주문시 재고가 부족하여 재고를 수정하는 alert이 발생해 재고 수정하는 view로 넘어갈 때의 코드가 완전히 중복됐네요. 수정했습니다 👍

2023-09-26 01:38 UTC, newJunsung commented on JuiceMaker/JuiceMaker/Controller/FruitInvetoryViewController.swift
> +    @IBAction func touchUpCloseButton(_ sender: UIButton) {
private을 붙여 해결했습니다!

2023-09-26 01:39 UTC, newJunsung commented on JuiceMaker/JuiceMaker/Controller/JuiceMenuViewController.swift
> +    @IBAction func modifyInvertoryPressed(_ sender: Any) {
private을 붙여 해결했습니다!

2023-09-26 01:41 UTC, newJunsung commented on JuiceMaker/JuiceMaker/Controller/JuiceMenuViewController.swift
> +        navigationController?.navigationBar.backgroundColor = .lightGray
UIViewController에 extension을 추가하여 중복되는 부분을 제거했습니다.

2023-09-26 01:42 UTC, newJunsung commented on JuiceMaker/JuiceMaker/Controller/FruitInvetoryViewController.swift
> +        navigationController?.navigationBar.backgroundColor = .lightGray
UIViewController에 extension을 추가하여 중복되는 부분을 제거했습니다.

2023-09-26 02:11 UTC, newJunsung commented
> 두 분 다 step3도 고생하셨습니다! 잘 작성해주셔서 크게 수정할 부분은 없어보이긴하네요 👏 💯
> 
> 다만 몇 가지 질문사항이 있어서 코멘트에 남겨두었고, PR에 작성해주신 부분에서도 질문이 있어서 여기 코멘트에 질문 남깁니다 🙏
> 
> > 1. 화면 전환 방식을 show(push)에서 modal로 변경
> 
> 이 부분에서 push에서 modal로 변경하신 이유가 궁금하네요! 물론 변경해보시면서 modal로 뜰 때 modalPresentationStyle에 따른 viewController의 lifecycle 함수들이 어떻게 호출되는지 공부하시게 된 부분은 엄청 좋네요 👍 👏
> 
> > 2. 바인딩하는 것이 옳은 것일까?
> 
> 기존의 step들에서 작성해주신 코드에서는 버튼을 누르거나, 뒤로가거나 할 때 버튼의 action을 받아서 처리해주는 함수나 viewController의 lifecycle 함수내부에서 Single으로 구현된 모델에 접근해 값을 업데이트 해주면서 해당 모델의 값을 통해서 실제로 UI까지 업데이트를 시켜주고 있었습니다. 그런데 두 분께서 바인딩 관련해서 질문을 주셨었는데, 두 분이서 바인딩을 하려고 하셨던 이유가 궁금합니다. 🙋‍♂️

1. STEP 3 요구사항에 과일 추가 화면에서 우측 상단에 닫기 버튼이 있는 것을 확인할 수 있습니다. 그렇기 때문에 제스쳐를 통해서 뒤로가기를 하면 안된다고 생각했습니다. 네비게이션 컨트롤러는 제스쳐를 통해 뒤로가기를 할 수 있기 때문에 모달로 변경했습니다.
2. 스텝퍼를 통해서 값이 변경되면 값을 저희가 하나하나 지정해주는 것보다, FruitStore의 과일 재고가 바뀌면 자동으로 변경되는 것을 바랬기 때문에 바인딩을 하려 했습니다.

2023-09-26 02:39 UTC, shlim0 commented on JuiceMaker/JuiceMaker/Controller/FruitInvetoryViewController.swift
> +        navigationController?.navigationBar.backgroundColor = .lightGray
`setNavigationBarBackgroundColor()`를 `extension UIViewController`으로 두어 함수로 분리했습니다.

```swift
//  UIViewController+Extension.swift
extension UIViewController {
    func setNavigationBarBackgroundColor(_ color: UIColor = .navigationBarColor) {
        navigationController?.navigationBar.backgroundColor = color
    }
}
```
```swift
//  UIColor+Extension.swift
extension UIColor {
    static let navigationBarColor = UIColor.lightGray
}
```

`setNavigationBarBackgroundColor()`는 아래의 코드에서 호출됩니다.

```swift
//  JuiceMenuViewController.swift
 override func viewDidLoad() {
        super.viewDidLoad()
        
        setNavigationBarBackgroundColor()
    }
```

```swift
//  FruitInventoryViewController.swift
override func viewDidLoad() {
        super.viewDidLoad()
        
        setNavigationBarBackgroundColor()
    }
```

2023-09-26 02:40 UTC, shlim0 commented on JuiceMaker/JuiceMaker/Protocols/FruitShowable.swift
> +    func show(_ fruit: Fruit, on fruitsCountLabels: [UILabel]) {
`show()` -> `setCount()`로 네이밍을 변경했습니다. 의미상, show라는 네이밍이 적절하다 생각하여 적용했는데, 다시 보니 그 의미를 간접적으로 내포하는 것 같아 더 직관적인 네이밍으로 변경했습니다.

2023-09-26 02:47 UTC, shlim0 commented on JuiceMaker/JuiceMaker/Controller/FruitInvetoryViewController.swift
> +            show(fruit, on: fruitsCountSteppers)
`extension FruitShowable`에서 다음과 같이 구현했습니다.

```swift
//  FruitShowable.swift
func setCount(on UIComponents: [UIView]...) {
        for fruitType in FruitType.allCases {
            guard let fruitCount = FruitStore.shared.fruitCounts[fruitType] else {
                return
            }
            
            for UIComponent in UIComponents {
                if let labelArray = UIComponent as? [UILabel] {
                    setCount(of: Fruit(fruitType, fruitCount), on: labelArray)
                } else if let labelArray = UIComponent as? [UIStepper] {
                    setCount(of: Fruit(fruitType, fruitCount), on: labelArray)
                }
            }
        }
    }
```

과제 명세 상, 들여쓰기가 두 번을 초과하긴 하나 성능 상 크게 문제 되지 않을 것이라 판단하여(O(n)) 이중 for문을 두었습니다. 
(물론, `setCount(on: fruitsCountLabels)`과 같이 파라미터로 하나의 `[UIView]`를 받으면 이중 for문을 두지 않아도 되나, 결국 호출을 두 번하는 경우와 동치라 생각하여 이중 for문으로 일반화 하였습니다)

호출은 다음과 같은 방식으로, 아래의 코드에서 호출됩니다.

`setCount(on: fruitsCountLabels)`
`setCount(on: fruitsCountLabels, fruitsCountSteppers)`

```swift
//  JuiceMenuViewController.swift
 override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        
        setCount(on: fruitsCountLabels)
    }
```
```swift
//  FruitInventoryViewController.swift
override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        
        setCount(on: fruitsCountLabels, fruitsCountSteppers)
    }
```

2023-09-26 03:52 UTC, shlim0 commented on JuiceMaker/JuiceMaker/Protocols/FruitShowable.swift
> +}
`JuiceMenuViewController`와 `FruitInvetoryViewController`에서 호출하는 기능이라 함수를 한 곳에서 두어 호출하면 되지 않을까 하는 생각에 protocol을 떠올렸습니다. 즉, show 하는 기능이 공통되어 한 protocol에 두었습니다.

따라서, 각 VC에서 protocol을 conform하면 되기 때문이라 생각했습니다. 또한, 빈 protocol인 이유는 각 VC에서 해당 함수를 구현할 필요는 없다고 생각했기 때문입니다.

제이크가 답변해주신 내용 중에 UILabel, UIStepper를 extension 하여 해결할 생각은 미처 하지 못했습니다. 또, 막상 이를 적용하여 작성해 본 결과 코드 길이가 길어지게 되었는데, 현재 기능이 많지 않으면서 관련된 기능끼리 한 protocol에 묶고 싶었기 때문에 해당 코드는 네이밍 변경을 한 것 외에는 이번 STEP에서 변경하지 않았습니다. 피드백 감사합니다.

2023-09-26 09:08 UTC, jryoun1 commented on JuiceMaker/JuiceMaker/Controller/FruitInvetoryViewController.swift
> +        navigationController?.navigationBar.backgroundColor = .lightGray
extension을 통해서 setNavigationBarBackgroundColor를 구현해주신 부분과 색상도 입력받을 수 있도록 한 부분 매우 좋네요 👏 💯

2023-09-26 14:09 UTC, jryoun1 commented on JuiceMaker/JuiceMaker/Protocols/FruitShowable.swift
> +}
빈 protocol 인 것과 각 VC에서 해당 함수를 구현하지 않아도 되는 것과는 다른 이야기인 것 같습니다.
protocol에 해당 함수를 포함시키고 extension으로 해당 함수의 기본 구현을 해줘도 동일하게 VC에서 해당 함수를 구현하지 않아도 됩니다.

2023-09-26 14:42 UTC, jryoun1 commented
수정해주신 부분 확인했습니다 👏 또한 질문에 대한 답변도 확인했습니다! 

> STEP 3 요구사항에 과일 추가 화면에서 우측 상단에 닫기 버튼이 있는 것을 확인할 수 있습니다. 그렇기 때문에 제스쳐를 통해서 뒤로가기를 하면 안된다고 생각했습니다. 네비게이션 컨트롤러는 제스쳐를 통해 뒤로가기를 할 수 있기 때문에 모달로 변경했습니다.

넵 설명해주신 이유 좋네요. 💯  
구현을 하자면 네비게이션 컨트롤러에서도 해당 제스처를 막거나 navigationBar를 custom 한다면 구현은 가능합니다. 
다만 이 화면은 modal과 push 둘 중에 어떤 것으로 제공되는 것이 더 좋을지에 대한 고민도 해보시면 좋을 것 같네요. 또한 modal과 push로 보여줘야하는 화면들의 종류는 어떤 것인지에 대해서도 한 번 알아보시면 좋을 것 같아요.  
유저의 사용 흐름이 남아야하는 것이라면 push, 그렇지 않고 잠깐 떴다가 사라져도 되는 화면들이라면 modal로 표현되는 경우가 많을텐데 기존에 사용하시는 앱들을 보시면서 파악해보시는 것도 도움이 될 것 같네요. 

> 스텝퍼를 통해서 값이 변경되면 값을 저희가 하나하나 지정해주는 것보다, FruitStore의 과일 재고가 바뀌면 자동으로 변경되는 것을 바랬기 때문에 바인딩을 하려 했습니다. 그리고 현재 modal의 presentationMode를 fullScreen으로 설정해서 닫기를 눌렀을 경우, viewWillAppear를 통해서 무사히 값이 적용됩니다. 그러나 'presentationMode를 굳이 fullScreen으로 설정하지 않아도 바인딩을 통해 값을 변경할 수 있지않을까?'라는 생각을 하게 되어 바인딩에 대한 질문을 하게 됐습니다.

넵 좋네요. 여기서 값을 하나하나 지정해준다는 부분이 view에 변경된 값들을 setting을 시켜주는 부분을 말씀하신걸로 이해하고 말씀드릴게요. 
fruitStore가 변경되었을 때 view가 업데이트 되는 방향으로 가려면 아래와 같은 flow로 동작해야할 것 같네요. 

1. 유저의 액션이 발생할 때 action을 처리하는 함수에서는 실제로 UI를 업데이트 시켜주는 코드들이 들어가는 것이 아닌, model의 값만 수정 
2. 이때 model은 delegate pattern, notification 등을 통해서 자신이 변경되었음을 model을 바라보고 있는 view에게 알려줘야함
3. 해당 model을 바라보고 있는 view에서는 model이 변경되었음을 인지하고, 이때 view를 업데이트 시켜줄 수 있는 코드 실행

다만 이 부분은 다음 프로젝트들을 진행해보면서 필요한 시점이 오면 그때 적용해봐도 좋을 것 같네요. 
이번 프로젝트에서는 초반에 구현을 해주신 방향이 바인딩을 하지 않아도 되는 구현 방향이였던 것 같아서 굳이 적용할 필요가 없었던 것 같네요. 
그래도 시도해보신 부분들은 매우 좋네요 👏 👍 

고생하셨습니다. 🙏

2023-09-26 14:42 UTC, merged