쥬스자판기 [STEP 3] Mond, Rarla
tasty-code/ios-juice-maker pull request #65
Opened 2023-09-22 06:59 UTC by rarlala

[@forestjae](https://github.com/forestjae)
안녕하세요~! 숲재!
세번째 리뷰를 요청하게 된 [@rarla](https://github.com/rarlala) [@mond](https://github.com/yeji1008)입니다 :)
이번에도 잘 부탁드립니다~!

## Step3 구현 요구사항
- 화면 제목 '재고 추가' 및 '닫기' 버튼 구현
    - 닫기를 터치하면 이전화면으로 복귀
    - 화면 진입시 과일의 현재 재고 수량 표시
    - -, + 를 통한 재고 수정
- iPhone 12 외에 다른 시뮬레이터에서도 UI가 정상적으로 보일 수 있도록 오토레이아웃 적용
<br><br>

## 코드를 작성하며 고민한 점
- 이번 스템 수행 중 핵심 경험인 아래 항목을 잘 사용하고자 고민했습니다.
    - 내비게이션 바 및 바 버튼 아이템의 활용
    - 얼럿 컨트롤러 활용
    - Stepper 활용
    - Modality의 활용
    - 화면 사이의 데이터 공유
    - 오토레이아웃 시작하기
- 화면 사이의 데이터 공유를 할 때 여러가지 방법 중에서 어떤 것을 사용하면 좋을 지 많은 고민을 해본 결과 재고 수정 페이지로 넘어갈 때는 `segue`를 사용하였고, 데이터 전달을 위해 `present`를 활용했습니다. 그리고 다시 주문 페이지로 넘어갈 때는 `delegate pattern`을 사용하였습니다.
- `ViewController`, `EditStoreViewController` 에서 반복되는 코드를 함수를 이용하여 여러번 작성하지 않도록 하였습니다.
- 성능 향상을 위한 방법으로 `final`, `private` 키워드를 사용하는 것을 배워 적용해보았습니다.

<br><br>

## 조언을 얻고 싶은 부분
- Step2에서 고민한대로 모달로 여는 방법을 선택했습니다. 그러다보니 팝업에서 연결되는 경우에는 navigationBar를 사용할 수 없게 되었습니다. 그래서 임의의 UIView와 Label과 Button으로 제목 영역을 구성했습니다. 이미 제공된 화면에서 네비게이션 컨트롤러가 각각의 화면에 연결이 되어있어 네비게이션 타이틀을 만들 수는 있는 형태였는데, 혹시 팝업에서 열때도 해당 타이틀이 보이게 하는 방법이 있는데 저희가 해당 방식을 알지 못해 구현을 못한 것인지 궁금합니다!
    - 또한 연결되는 질문으로 UIView와 Label과 Button로 제목 영역을 구성한 부분도 UIView가 아닌 `Navigation bar`와 `Navigation item`을 활용해 만드는지 궁금합니다!
- `주문화면 내 재고가 부족하면 표시되는 모달에서 버튼을 클릭하여 재고수정 화면을 여는 방식`과 `주문화면 내 재고 수정 버튼을 클릭해 재고화면을 여는 방식`을 구현하기 위해 segue 방식을 활용해 prepare를 활용하는 방식과 present로 여는 방식 두가지를 사용하였습니다. 혹시 팝업을 열 때와 segue를 사용해 화면을 열 때 하나의 함수를 사용해 해당 코드를 줄이는 방법이 있을지도 궁금합니다.
- `EditStoreViewController` 내 `stepperButtonTapped` 메서드에 중복되는 코드를 줄이고자 노력했습니다. 하지만 각각에 맞는 Label UI 및 Stepper UI에 적용해줘야하는 부분 처리를 더 줄일 방법이 없어 `getChangeNumber` 메서드 분리 정도의 구현만 적용할 수 있었습니다. 혹시 저희가 생각하지 못한 중복된 코드를 줄이는 방법이 있을지 궁금합니다!
- 성능 향상을 위한 방법으로 final, private 키워드를 사용하는 것을 배워 적용해보았습니다. 혹시 제대로 사용을 했는지 궁금합니다.
- @IBOutlet 으로 연결되는 UI들을 하나의 그룹으로 묶어 처리하는 방법이 있는지 궁금합니다!

2023-09-22 12:01 UTC, forestjae commented
마지막까지 고생많으셨습니다 👏 👏 👏 
요구사항을 모두 구현해 주셨고, 잘 동작합니다 👍 👍 👍 

질문에 대한 답변과 코드에 코멘트 남겨놓을테니, 수정해보시고 궁금한게 있으면 언제든지 DM주세요.

> ## 조언을 얻고 싶은 부분
> * Step2에서 고민한대로 모달로 여는 방법을 선택했습니다. 그러다보니 팝업에서 연결되는 경우에는 navigationBar를 사용할 수 없게 되었습니다. 그래서 임의의 UIView와 Label과 Button으로 제목 영역을 구성했습니다. 이미 제공된 화면에서 네비게이션 컨트롤러가 각각의 화면에 연결이 되어있어 네비게이션 타이틀을 만들 수는 있는 형태였는데, 혹시 팝업에서 열때도 해당 타이틀이 보이게 하는 방법이 있는데 저희가 해당 방식을 알지 못해 구현을 못한 것인지 궁금합니다!

UINavigationViewController로 감싼 VC를 present하면 됩니다. present하시기 전에 네비게이션 컨트롤러로 감싸거나, 처음부터 재고수정 화면을 UINavigationViewController로 만드는 방법이 있겠네요.

>   * 또한 연결되는 질문으로 UIView와 Label과 Button로 제목 영역을 구성한 부분도 UIView가 아닌 `Navigation bar`와 `Navigation item`을 활용해 만드는지 궁금합니다!

보통 위에서 말씀드린 방법을 많이 쓰지만, 커스텀하게 만드실 필요가 있다면 UIView를 쓰거나 Navigation관련 컴포넌트를 쓰는 것은 개발자의 선택입니다.

> * `주문화면 내 재고가 부족하면 표시되는 모달에서 버튼을 클릭하여 재고수정 화면을 여는 방식`과 `주문화면 내 재고 수정 버튼을 클릭해 재고화면을 여는 방식`을 구현하기 위해 segue 방식을 활용해 prepare를 활용하는 방식과 present로 여는 방식 두가지를 사용하였습니다. 혹시 팝업을 열 때와 segue를 사용해 화면을 열 때 하나의 함수를 사용해 해당 코드를 줄이는 방법이 있을지도 궁금합니다.

재고가 부족할때 표시되는 얼럿에서는 스토리보드에 정의된 Segue를 사용하실 수 없기 때문에 이와같이 하신걸로 보입니다. 양쪽 다 동일하게 present를 사용하거나, alert에서도 `perfromSegue`라는 메서드를 사용하시면 코드베이스로 스토리보드에 정의된 segue를 사용하실 수 있어요.

> * `EditStoreViewController` 내 `stepperButtonTapped` 메서드에 중복되는 코드를 줄이고자 노력했습니다. 하지만 각각에 맞는 Label UI 및 Stepper UI에 적용해줘야하는 부분 처리를 더 줄일 방법이 없어 `getChangeNumber` 메서드 분리 정도의 구현만 적용할 수 있었습니
다. 혹시 저희가 생각하지 못한 중복된 코드를 줄이는 방법이 있을지 궁금합니다!

Fruit라는 enum이 있으니 tag값과 enum을 활용하면 반복되는 코드를 줄일 수 있습니다. 

> * 성능 향상을 위한 방법으로 final, private 키워드를 사용하는 것을 배워 적용해보았습니다. 혹시 제대로 사용을 했는지 궁금합니다.

네 잘 사용해주셨어요! 외부에서 사용하지 않는 프로퍼티, 메서드에는 전부 private을 붙이고 다른 클래스가 상속 당하지 않는 class에는 전부 final 키워드를 붙이는 것을 미리 생활화 하시는게 좋습니다. 그리고 접근제한자에 따라서 프로퍼티와 메서드를 정렬해보세요. override -> internal -> private 순으로 프로퍼티, 메서드를 각각 정렬해놓으면 외부에서 사용하는 게 뭔지 쉽게 파악이 가능해서 코드의 가독성이 향상됩니다.

> * @IBOutlet 으로 연결되는 UI들을 하나의 그룹으로 묶어 처리하는 방법이 있는지 궁금합니다!

`IBOutletCollection` 키워드로 검색해보세요!

2023-09-22 12:09 UTC, forestjae requested changes

2023-09-22 12:09 UTC, forestjae commented on JuiceMaker/JuiceMaker/Controller/EditStoreViewController.swift
> +  var mangoValue: String?
Int가 아닌 String으로 정의하신 이유가 있을까요?

2023-09-22 12:09 UTC, forestjae commented on JuiceMaker/JuiceMaker/Controller/EditStoreViewController.swift
> +  var delegate: ViewControllerDelegate?
나중에 배우시는 내용이긴한데, 이렇게 2개의 클래스가 서로를 참조하게 되는 경우에는 var 앞에 weak을 붙여줘야합니다. ARC에 관련된 내용입니다.

2023-09-22 12:09 UTC, forestjae commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +protocol ViewControllerDelegate {
네이밍이 너무 일반적입니다. 프로토콜의 이름만 보고도 어떤 역할을 하는지 유추 가능하게 다시 이름지어보세요!

2023-09-22 12:09 UTC, forestjae commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        sendData(view: editStoreView)
재고 수정 뷰에 데이터를 전달해주시는 이유가 궁금해요. 이미 싱글턴으로 FruitStore를 정의해두셨기 때문에, 앱 전역에서 동일한 재고값 데이터를 사용할 수 있습니다.

2023-09-22 12:11 UTC, forestjae commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +  }
text에 있는 정보를 전달해주는게 어색해보입니다. FruitStore를 활용해보시는게 어떨까요?

2023-09-25 07:47 UTC, rarlala commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +protocol ViewControllerDelegate {
[81156ad](https://github.com/tasty-code/ios-juice-maker/pull/65/commits/81156ad93bfdb5b7a54c7ac8a60c083db5737f29) 에서 EditStoreView가 닫힌 이벤트를 받는 Delegate라는 점을 생각해 네이밍을 변경했습니다~!

2023-09-25 07:49 UTC, rarlala commented
> 0703d2e

추가로 답변해주신 부분을 참고해 
[0703d2e](https://github.com/tasty-code/ios-juice-maker/pull/65/commits/0703d2ee09c98e806ee1fb637a3f459bb01d97c1) 에서 접근제한자에 따라 정렬했습니다!

2023-09-25 07:50 UTC, rarlala commented
> > * 성능 향상을 위한 방법으로 final, private 키워드를 사용하는 것을 배워 적용해보았습니다. 혹시 제대로 사용을 했는지 궁금합니다.
> 
> 네 잘 사용해주셨어요! 외부에서 사용하지 않는 프로퍼티, 메서드에는 전부 private을 붙이고 다른 클래스가 상속 당하지 않는 class에는 전부 final 키워드를 붙이는 것을 미리 생활화 하시는게 좋습니다. 그리고 접근제한자에 따라서 프로퍼티와 메서드를 정렬해보세요. override -> internal -> private 순으로 프로퍼티, 메서드를 각각 정렬해놓으면 외부에서 사용하는 게 뭔지 쉽게 파악이 가능해서 코드의 가독성이 향상됩니다.
> 

[0703d2e](https://github.com/tasty-code/ios-juice-maker/pull/65/commits/0703d2ee09c98e806ee1fb637a3f459bb01d97c1) 에서 접근제한자에 따라 정렬했습니다!

2023-09-25 07:51 UTC, yeji1008 commented on JuiceMaker/JuiceMaker/Controller/EditStoreViewController.swift
> +  var delegate: ViewControllerDelegate?
[db7ff6b](https://github.com/tasty-code/ios-juice-maker/pull/65/commits/db7ff6b19bb5c58b774406d516a42ecaae692d98)
[ARC링크](https://babbab2.tistory.com/27) 를 보고 ARC 관련 내용을 공부하였습니다.
[링크](https://stackoverflow.com/questions/33471858/swift-protocol-error-weak-cannot-be-applied-to-non-class-type)를 참고하여 protocol을 AnyObject 타입으로 설정하였습니다.

2023-09-25 08:00 UTC, rarlala commented on JuiceMaker/JuiceMaker/Controller/EditStoreViewController.swift
> +  var mangoValue: String?
싱글톤 패턴을 사용하기 전에, 주문 화면에서 전달하는 데이터를 label에 있는 text를 전달해서 String으로 받아 작업했었습니다! 
[b0191e3](https://github.com/tasty-code/ios-juice-maker/pull/65/commits/b0191e33ec32d9e323b60eae07318f934153c8d6) 에서 싱글톤 패턴을 사용하는 방식으로 수정해 위 코드를 사용하지 않게 되었습니다 :)

2023-09-25 08:01 UTC, rarlala commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        sendData(view: editStoreView)
맞아요! 저희도 해당 부분을 생각했는데, 과제 요구 조건인 화면간 데이터 전달을 구현해보자는 의미로 싱글톤 패턴의 장점을 뒤로한채 작업해보았어요! 이번에 https://github.com/tasty-code/ios-juice-maker/pull/65#discussion_r1335522927 <- 에 작성한대로 싱글톤 패턴을 사용하는 방식으로 다시 수정했습니다~

2023-09-25 08:01 UTC, yeji1008 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +  }
[b0191e3](https://github.com/tasty-code/ios-juice-maker/pull/65/commits/b0191e33ec32d9e323b60eae07318f934153c8d6)
Singleton pattern을 이용하여 sendData 함수에서 text에 있는 정보를 전달해주는 코드를 삭제하였습니다.

2023-09-26 13:16 UTC, forestjae commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        sendData(view: editStoreView)
아 그러셨군요 ㅎㅎㅎ 둘다 경험해 보셨으니 최고입니다 👍

2023-09-26 13:20 UTC, merged