쥬스자판기 [STEP 3] Howard, Dora
tasty-code/ios-juice-maker pull request #66
Opened 2023-09-22 08:23 UTC by KSK9820

> 리뷰어: @jungseungyeo
> 버디: @JEON-Sungsu, @KSK9820

### [STEP 3] 요구사항 체크리스트

- [x]  내비게이션 바 및 바 버튼 아이템의 활용
    - ViewController의 네비게이션 바 버튼을 터치하면 StockViewController로 이동합니다.
    - StockViewController의 왼쪽에 있던 기본 barItem은 보이지 않게 설정하였고, 오른쪽의 `닫기` 버튼을 터치하면 StockViewController를 내비게이션 스택에서 pop합니다.
- [x]  얼럿 컨트롤러 활용
    - 얼럿 컨트롤러와 try-catch 문을 함께 활용합니다.
    - 음료 만들기에 성공했을 때, 실패했을 때 그리고 옵셔널 값이 바인딩 실패되어 유효한 값이 없을때의 케이스를 나누어 Error 처리를하였고, 해당 Error의 message 값을 얼럿에 표시하여 present 합니다.
- [x]  Stepper의 활용
    - Stepper의 초기값을 Fruit의 재고값으로 초기화하고 시작합니다.
    - Stepper는 `+`, `-`의 리턴값을 구분하지 않고 연산된 Double 값을 리턴해주기 때문에 해당 리턴값을 Model인 FruitStore에 전달합니다.
- [x]  Modality의 활용
    - 내비게이션으로 활용합니다.
- [x]  화면 사이의 데이터 공유
    - ViewController → StockViewController 이동할 때 sendStockDelegate를 사용하여 StockViewController에 값을 전달합니다.
    - 이때 전달하는 값은, ViewController에서 실체화한 JuiceMaker 구조체의 인스턴스를 프로토콜의 sendStock() 함수의 리턴값으로 전달합니다.
- [x]  오토 레이아웃 시작하기
    - 가운데 있는 pineapple Stack을 화면의 중심으로 설정합니다. (centerX, centerY)
    - pineapple Stack을 기준으로 다른 Stack들의 좌우 여백을 20으로 설정합니다.
    - 가장 오른쪽, 왼쪽의 strawberry Stack과 mango Stack은 가장자리 여백을 설정하지 않습니다.
    - 해당 화면은 가로모드일 때, iPhone SE와 iPhone 14 Max 에서도 동작합니다.
        
        ![image](https://github.com/tasty-code/ios-juice-maker/assets/68066104/7d844f78-39b7-4219-90ad-e66cc93a4290)
        
        ![image](https://github.com/tasty-code/ios-juice-maker/assets/68066104/22d62771-a406-46bc-9271-109ec50644c0)
        

### 코드 설명

1. JuiceMaker.swift
    - ViewController 에서 Label 과 Stepper에게 값을 바인딩 하기위해 함수를 만들었습니다. FruitStore의 재고는 Int 값인데, 그대로 전달해서 ViewController 단에서 형변환을 하는것 보다, JuiceMaker에서 형변환 작업을 거쳐 넘겨줄 수 있도록 만들었습니다.
        
        ```swift
        struct JuiceMaker {
        
        func getRemainingFruits(_ fruitName: Fruit) throws -> String {
                return try String(fruitStorage.getStockInfo(fruitName))
            }
            
        func getStepperValue(_ fruitName: Fruit) throws -> Double {
            return try Double(fruitStorage.getStockInfo(fruitName))
        }
        ...
        ```
        
2. FruitStore
    - VC에서 stepper 이벤트가 발생하면, stepper 의 tag 를 받아서 어떤 과일의 재고량이 변동했는지 확인하고, stepper.value 를 받아서 fruitBox 의 재고량을 업데이트 하도록 하였습니다.
        
        ```swift
        extension FruitStore {
           ....
            
            public func stockManager(_ fruit: Int, changedStock: Double) {
                switch fruit {
                case 0:
                    fruitBox[.strawberry] = Int(changedStock)
                case 1:
                    fruitBox[.banana] = Int(changedStock)
                case 2:
                    fruitBox[.pineapple] = Int(changedStock)
                case 3:
                    fruitBox[.kiwi] = Int(changedStock)
                case 4:
                    fruitBox[.mango] = Int(changedStock)
                default:
                    break
                }
            }
        }
        ```
        
3. ViewController.swift
    - Delegation pattern 을 통해서 JuiceMaker의 인스턴스를 데이터로 넘겨주었습니다.
        
        ```swift
        extension ViewController: sendStockDelegate {
            func sendStock() -> JuiceMaker {
                return juiceMaker
            }
        }
        ```
        
    - viewWillAppear 를 통해서, 재고관리 화면에서 넘어올때, bindingLabel 함수를 호출하여 변경된 값들을 다시 맵핑하도록 하였습니다.
        
        ```swift
        final class ViewController: UIViewController {
        	...
        
            override func viewDidLoad() {
                super.viewDidLoad()
                bindingLabel()
            }
            
            override func viewWillAppear(_ animated: Bool) {
                bindingLabel()
            }
        }
        ```
        

1. StockViewController.swift 
    - Stepper의 초기값을 Fruit의 재고값으로 초기화하고 시작합니다.
    - Stepper는 `+`, `-`의 리턴값을 구분하지 않고 연산된 Double 값을 리턴해주기 때문에 해당 리턴값을 Model인 FruitStore에 전달합니다.
        
        ```swift
        extension StockViewController {
            private func updateStepperValue()  {
                guard let stock = delegate?.sendStock() else {
                    return
                }
                do {
                    strawberryStepper.value = try stock.getStepperValue(.strawberry)
                    bananaStepper.value = try stock.getStepperValue(.banana)
                    pineappleStepper.value = try stock.getStepperValue(.pineapple)
                    kiwiStepper.value = try stock.getStepperValue(.kiwi)
                    mangoStepper.value = try stock.getStepperValue(.mango)
                } catch {
                    print(error)
                }
            }
            
            private func updateStockLabel() {
                guard let stock = delegate?.sendStock() else {
                    return
                }
                do {
                    strawberryLabel.text = try stock.getRemainingFruits(.strawberry)
                    bananaLabel.text = try stock.getRemainingFruits(.banana)
                    pineappleLabel.text = try  stock.getRemainingFruits(.pineapple)
                    kiwiLabel.text = try stock.getRemainingFruits(.kiwi)
                    mangoLabel.text = try stock.getRemainingFruits(.mango)
                } catch {
                    statusAlert(ErrorMessage.invalidInput.debugDescription)
                }
            }
        ...
        }
        
        extension StockViewController {
            @IBAction func pressedStepper(_ sender: UIStepper) {
                guard let stock = delegate?.sendStock() else {
                    return
                }
                stock.fruitStorage.stockManager(sender.tag, changedStock: sender.value)
                updateStepperValue()
                updateStockLabel()
            }
            ...
        }
        ```
        

### 고려하려 노력한점

- ViewController 단에서, Model이 처리해야될 로직들을 잘 구분하고, 사용하지 않도록 신경썼습니다.

### 궁금한점

- ViewController 에서 StockViewController 로 JuiceMaker의 인스턴스를 전달하고, 전달받은 인스턴스를 통해 재고량변경을 한 뒤, 다시 인스턴스의 함수를 호출해서 추가&감소된 재고량을 표시해주는것도 데이터의 이동이라고 봐도 괜찮은걸까요? JuiceMaker가 가지고 있는 FruitStore의 class의 참조 특징을 통해서 진행하였는데 옳은 방법인지 궁금합니다.
- ViewController 에서는 값을 가져오고, 보여주기만 해야된다고 하셨는데.. 가져온 값들에 대한 타입 형변환 같은것도 하면 안되는 걸까요? FruitStore에서 현재 재고량을 보여주는 함수가 여기저기서 많이 쓰이는데, 반환 타입은 Int 이나 사용해야되는 곳에서는 다양한 타입으로 사용되어져야 해서요. 위의 getRemainingFruits 함수와 getStepperValue 함수도 같은 맥락으로 어디서는 String, 어디서는 Double 타입으로 받아야 하는데 .. 어떻게 해야 될 지 잘 모르겠어서 같은 함수지만 반환타입만 다르게 두개를 만들어서 사용하게 되었습니다.
- FruitStore, JuiceMaker에서 Dictionary 타입으로 데이터를 저장하기 때문에 해당 데이터를 파라미터 값으로 확인하기 위해서는 옵셔널 바인딩으로 값을 풀어줘야 합니다. 이때 옵셔널 바인딩에 실패하면 Error를 throw하기 때문에 해당 함수들을 호출하는 단에서는 항상 do try-catch문을 사용해야합니다. 
viewController 에서도 do try-catch를 해줘도 괜찮을까요? 
혹 너무 많은 do try-catch가 사용되는건 아닌지 걱정됩니다.

2023-09-22 23:45 UTC, jungseungyeo requested changes
# 궁금한점

ViewController 에서 StockViewController 로 JuiceMaker의 인스턴스를 전달하고, 전달받은 인스턴스를 통해 재고량변경을 한 뒤, 다시 인스턴스의 함수를 호출해서 추가&감소된 재고량을 표시해주는것도 데이터의 이동이라고 봐도 괜찮은걸까요? JuiceMaker가 가지고 있는 FruitStore의 class의 참조 특징을 통해서 진행하였는데 옳은 방법인지 궁금합니다.

`참조 타입으로 모델을 자주 구성하는 방법을 사용하기는 하나 현재 형태에서는 올바른 형태는 아닌거 같아요. 더 좋은 방법으로는 stokcVC로 화면 전환시 model을 주입하고 화면 이탈 시 delegate 패턴을 사용하여 update 할 모델을 넘겨주어 모델을 업데이트 하는 방법이 좋아 보여요. stock을 참조 할 수 있는 객체를 전달 받아서 직접 업데이트를 하다보니 의존성이 생기게 됩니다. 이 부분 수정을 하면 좋을거같아요.`

```
protocol SendStockDelegate {
  func updateStock(_ with Fruit) 
}
```

위 처럼 업데이트를 알려주면 좋습니다.


ViewController 에서는 값을 가져오고, 보여주기만 해야된다고 하셨는데.. 가져온 값들에 대한 타입 형변환 같은것도 하면 안되는 걸까요? FruitStore에서 현재 재고량을 보여주는 함수가 여기저기서 많이 쓰이는데, 반환 타입은 Int 이나 사용해야되는 곳에서는 다양한 타입으로 사용되어져야 해서요. 위의 getRemainingFruits 함수와 getStepperValue 함수도 같은 맥락으로 어디서는 String, 어디서는 Double 타입으로 받아야 하는데 .. 어떻게 해야 될 지 잘 모르겠어서 같은 함수지만 반환타입만 다르게 두개를 만들어서 사용하게 되었습니다.

`넵 가능한 형 변환을 하지 않으면 좋습니다.  getRemainingFruits, getRemainingFruits 의 기능은 같은거 같아요. 근본적으로는 View에서 역할이 아니긴 하지만 현재 형태에서 View 혹은 Maker에서 진행 부탁드려요. 그래도 해결 책을 제시하자면 DTO를 통해서 형 변환을 하는 형태입니다. 
DTO는 Data Transfer object로 데이터를 전송하는 역할을 하는 객체입니다. 이 객체에서 view에서 표현 할 수 있는 값으로 변환을 해주면 좋습니다. 이 부분은 참고 하고 넘어가주세요 :) 

https://hudi.blog/data-transfer-object/
`

FruitStore, JuiceMaker에서 Dictionary 타입으로 데이터를 저장하기 때문에 해당 데이터를 파라미터 값으로 확인하기 위해서는 옵셔널 바인딩으로 값을 풀어줘야 합니다. 이때 옵셔널 바인딩에 실패하면 Error를 throw하기 때문에 해당 함수들을 호출하는 단에서는 항상 do try-catch문을 사용해야합니다.
viewController 에서도 do try-catch를 해줘도 괜찮을까요?
혹 너무 많은 do try-catch가 사용되는건 아닌지 걱정됩니다.

`어떤 아키텍처를 사용하는지 따라 사용해도 된다 안된다고 말씀드릴수 있을거같아요. MVC를 사용한다면 당연히 ViewController에서 do catch를 사용해도 되지만 MVVM에서는 안됩니다. 꼭 ViewController에서는 안된다기 보다는 내가 어떤 역할로 이 객체를 사용하는 관점에서 바라보고 판단하면 좋을거같아요. 현재 상태에서는 사용하지 않는 형태가 좋아보입니다. 근본적으로 do catch문이 자꾸 생기는 이유는 model의 형태가 딕션너리로 구성이 되어 있기 때문이죠. 이 model을 개선하지 않으면 계속 꼬리표처럼 따라 붙을수밖에 없어요 . 해줘도 되는지 않되는지 보다는 안쓰는 형태를 안드는게 최고인거같아요. `

이번에는 DTO와 의존성 주입, 을 소개드렸는데요. DTO를 아니더라도 이번 스텝에서 의존성 주입 (DI)를 통해서 Model을 전달하는 것은 꼭 수행했으면 좋겠습니다. delegate 패턴을 (DIP)이지만 형태 형태를 매우 안좋아보여서 예시 protocol을 만들었어요. 꼭 저 함수를 쓰는건 아니지만 저런 형태의 함수로 구성해보시고 사용 부탁드립니다. 감사합니다.

2023-09-22 23:45 UTC, jungseungyeo commented on JuiceMaker/JuiceMaker/Controller/StockViewController.swift
> +        stock.fruitStorage.stockManager(sender.tag, changedStock: sender.value)
tag는 가능한 쓰지마세요. model의 값을 표시하고 업데이트를 해주면 좋을거같아요.

2023-09-22 23:45 UTC, jungseungyeo commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        bindingLabel()
super.viewWillAppear(animated)를 반드시 호출해주세요.

2023-09-22 23:45 UTC, jungseungyeo commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        bindingLabel()
애플에서도 내부적으로 동작을 하고 있다고 명시되어 호출하지않으면 어떤 문제가 발생할지 알수없어요.

2023-09-22 23:45 UTC, jungseungyeo commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
>          let stockVC = self.storyboard?.instantiateViewController(withIdentifier: "StockViewController") as! StockViewController
```suggestion
        let stockVC = self.storyboard?.instantiateViewController(withIdentifier: "StockViewController") as? StockViewController
```

강제 언래핑을 사용하지 마세요

2023-09-22 23:45 UTC, jungseungyeo commented on JuiceMaker/JuiceMaker/Controller/StockViewController.swift
> +        guard let stock = delegate?.sendStock() else {
delegate를 통해서 다시 stock의 상태를 묻고 있습니다. 

이러한 작성 된 코드가 존재하고 model이 딕션너리로 되어 있다보니 try, catch문이 자꾸 들어가게 됩니다. 
근본적인 문제는 딕셔너리를 없애고 다른 형태로 모델을 구성하며, DI를 통해서 모델을 주입해주고 
delegate를 통해서 DIP(의존성을 역전)하는 형태가 되어야 합니다.

다소 여러울수있지만.. 한번 도전해보세요 :)

2023-09-22 23:45 UTC, jungseungyeo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        case 0:
0번째가 strawberry라는 것을 보장 할 수는 없겠죠? 또 기회적으로 순서가 바꾼다면 코드 수정이 되어야 할거구요. 

파라미터로 Fruit를 받아서 changedStock를 변경하면 좋을거같아요.

2023-09-22 23:45 UTC, jungseungyeo commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    private (set) var fruitStorage = FruitStore()
private를 private(set)으로 변경이 되었다는 것은 어딘가에서 JuiceMaker를 의존성과 FruitStore의 의존성이 생긴겁니다. 
즉 디미터 법칙을 위반 할 수있어요. 

https://medium.com/sjk5766/%EB%94%94%EB%AF%B8%ED%84%B0-the-law-of-demeter-%EC%9D%98-%EB%B2%95%EC%B9%99-56d780ceda34

위의 아티클을 읽어보시고 참고해주세요 :)

2023-09-22 23:45 UTC, jungseungyeo commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
>          self.navigationController?.pushViewController(stockVC, animated: true)
위의 함수에서 model을 주입해주면 좋을거같아요. model을 주입하여 stockVC로 넘겨주는 코드를 추가해주세요.

2023-09-22 23:45 UTC, jungseungyeo commented on JuiceMaker/JuiceMaker/Controller/StockViewController.swift
> +    var delegate: sendStockDelegate?
```suggestion
    weak var delegate: sendStockDelegate?
```

를 사용하여 래퍼런스 카운트를 올리지 않는 방법이 좋습니다.

2023-09-27 00:50 UTC, KSK9820 commented on JuiceMaker/JuiceMaker/Controller/StockViewController.swift
> +    @IBOutlet weak var strawberryLabel: UILabel!
수정하였습니다 :)

2023-09-27 00:50 UTC, JEON-Sungsu commented on JuiceMaker/JuiceMaker/Controller/StockViewController.swift
> +    var delegate: sendStockDelegate?
protocol에 AnyObject추가 후 weak 까지 추가 하였습니다!

2023-09-27 00:50 UTC, KSK9820 commented on JuiceMaker/JuiceMaker/Controller/StockViewController.swift
> +protocol sendStockDelegate {
수정하였습니다 :)

2023-09-27 00:50 UTC, JEON-Sungsu commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
>          self.navigationController?.pushViewController(stockVC, animated: true)
함수를 통하여 StockViewController로 모델을 주입해주었습니다.

2023-09-27 00:51 UTC, JEON-Sungsu commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    private (set) var fruitStorage = FruitStore()
set은 모두 지웠습니다!

2023-09-27 00:51 UTC, JEON-Sungsu commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        case 0:
tag를 사용하지 않음에 따라 Fruit을 받아서 재고수정을 하도록 변경하였습니다.

2023-09-27 00:51 UTC, KSK9820 commented on JuiceMaker/JuiceMaker/Controller/StockViewController.swift
> +}
ViewController -> StockViewController 이동에는 모델을 주입하였고
StockViewController -> ViewController 이동시에는 delegate 패턴으로 ViewController의 label.text를 업데이트 하도록 변경하였습니다!

2023-09-27 00:52 UTC, KSK9820 commented on JuiceMaker/JuiceMaker/Controller/StockViewController.swift
> +        stock.fruitStorage.stockManager(sender.tag, changedStock: sender.value)
tag를 사용하지 않고 UIButton과 Stepper에 각각의 IBAction을 추가하였습니다.

2023-09-27 00:53 UTC, JEON-Sungsu commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
>          let stockVC = self.storyboard?.instantiateViewController(withIdentifier: "StockViewController") as! StockViewController
강제언랩핑은 제거하였습니다!

2023-09-27 00:53 UTC, KSK9820 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        bindingLabel()
delegate로 label의 text를 업데이트하는 방향으로 수정하였기 때문에 viewWillAppear를 뺐습니다!

2023-09-27 00:54 UTC, JEON-Sungsu commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        bindingLabel()
모델을 주입하고, 변경된 모델을 delegate로 돌려받아 변경된 모델을 가지고 View를 업데이트 해주는 방식으로 바꾸면서 viewWillAppear는 제거하였습니다.!

2023-09-27 00:54 UTC, KSK9820 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        case 0:
tag값을 넘기는 대신 Fruit을 넘기도록 수정하였습니다. 👍

2023-09-27 12:58 UTC, jungseungyeo approved these changes
도라, howard 리뷰 한 내용 잘 반영이 되었네요 ㅎㅎ 고생하셨습니다.

추가로 질문이 있으면 언제든지 연락주세요 ㅎㅎ 고생하셨습니다.

2023-09-27 12:58 UTC, jungseungyeo commented on JuiceMaker/JuiceMaker/Controller/StockViewController.swift
> +        stock.updateStock(.mango, updatedStock: sender.value)
좋습니다 :)

2023-09-27 12:58 UTC, jungseungyeo commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    @IBAction func orderMangoJuice(_ sender: UIButton) {
여기서도 private을 잊지마세요 ㅎㅎ

2023-09-27 12:58 UTC, merged