Step1
tasty-code/ios-juice-maker pull request #7
Opened 2022-08-27 03:15 UTC by eunho8713

@jaemuYeo 리뷰 부탁드립니다! 
@Tacocat-tastycode 

### **STEP1 구현 내용**

- 쥬스 만드는 함수구현
- 과일 재고관리 함수구현
- 열거형으로 과일과 쥬스 선언

### **고민한 내용**

- 딕셔너리를 활용하여 코드를 작성할지, 배열이나 다른 방법을 활용해야할지 고민하면서 계속 로직을 바꾸게 되었던것 같습니다.
- 딕셔너리를 활용해서 과일의 재고를 관리하는 함수를 구현하는 방법에 대해 어떻게 value값을 이용해서 연산을 할지 많은 고민을 했습니다.

2022-08-29 02:33 UTC, jaemuYeo requested changes
씨유 우노 스텝1 진행하느라 고생많았어요!!
생각보다 타입을 설게하는 것이 많이 어렵죠?? ㅎㅎㅎ
그래도 계속 생각해보고 어떻게 적절하게 설계하면 좋을지 작성해보면
금방금방 감을 잡을거예요~~
코드에 대해서는 개별 코멘트 남겨놓았습니다!!
메서드의 세부적인 구현은 이번 스텝에서의 중요한 부분이 아니기때문에
다음 스텝에서 실질적인 UI와의 연동을 통해 더 자세히 보도록 할게요!!

2022-08-29 02:33 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
>  class FruitStore {
FruitSttore는 왜 클래스로 선언되었을까요??
또한 상속이 필요하지 않은 클래스는 앞에 final 키워드를 붙여주면 좋습니다!
final 클래스의 특징도 한번 조사해보고 알려줄 수 있을까요??

2022-08-29 02:33 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    var fruits: [Fruit: Int] = [.strawberry: 10, .banana: 10, .pineapple: 10, .kiwi: 10, .mango: 10]
이 변수는 외부에서 마음대로 값을 바꿀 수 있는건가요??
그리고 Fruit 열거형에 멋지게 CaseIterable을 채택해주었는데
10이라는 전부 같은 초기값을 조금 더 단순하게 넣을 수 있는 방법은 없을까요??🤔
저번에 전달했던 것처럼 10도 매직넘버같아요!

2022-08-29 02:33 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func getAmount(of name: Fruit) -> Int {
이 메서드는 어떤 기능을 담당하나요?

2022-08-29 02:33 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        for ingredient in fruits {
복수형의 네이밍을 가진 것을 순회할때는 fruit와 같이 비슷한 뜻의 명사형태로 가는 것이 조금 더 명확할 것같습니다 😀

2022-08-29 02:33 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func increase(of name: Fruit, to amount: Int) {
함수의 네이밍과 매개변수를 잘 작성해서 한 문장처럼 너무 잘 읽히네요!! 멋져요👍

2022-08-29 02:33 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +            var outDict: Int = ingredinet.value
outDict이라는 네이밍이 어떤 것을 뜻하는 건지 잘 모르겠어요!
조금 더 명확한 네이밍은 없을까요?
타입 명시도 따로 하지않아도 Int라는 값을 저장할 것같아요 ☺️

2022-08-29 02:33 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +class JuiceMaker {
JuiceMaker타입이 원래 구조체였는데 클래스로 바꾼 이유가 있나요??
구조체로 선언해놨던 것은 어떤 이유였을까요??

2022-08-29 02:33 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    enum Juice {
쥬스메이커 내부에 쥬스타입을 열거형을 통해 표현한 방법이 너무 좋습니다!!
열거형 내부에 연산프로퍼티를 사용해 값을 넣어주는 것과
rawValue의 차이점은 무엇이고 어떤 경우에 사용하면 좋을까요??

2022-08-29 02:33 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    var fruitStore = FruitStore()
이 변수를 상수로 하지않고 변수로 선언한 이유가 있나요?
만약 JuiceMaker타입이 구조체였다면 어떻게 선언해볼 수 있을까요?

2022-08-29 02:33 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func isMakeAble(juice: Juice) -> Bool {
이 메서드는 외부에서도 접근가능한가요?

2022-08-29 02:33 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func useIngredients(of menu: Juice) {
이 메서드는 외부에서도 접근가능한가요?

2022-08-29 03:01 UTC, eunho8713 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +            var outDict: Int = ingredinet.value
수정하겠습니다!

2022-08-29 03:07 UTC, eunho8713 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
>  class FruitStore {
FruitStore가 클래스로 선언된 이유는 JuiceMaker가 FruitStore를 상속받기 때문이라고 생각합니다.
또한 final class 를 사용하는 이유는 더 이상 해당 클래스에서 하위 클래스로의 전체 클래스 또는 일부 (메서드, 프로퍼티)가 상속 또는 상속에 따른 재정의가 될 필요가 없다고 판단한 경우 final 키워드를 각 요소 앞에 추가함으로써 상속을 방지할 수 있다고 합니다!

2022-08-29 03:08 UTC, Schro2109 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        for ingredient in fruits {
확실히 ingredient(재료) 와 fruits (과일)은 관계성이 모호하게 느껴지네요
fruit로 수정해보겠습니다!

2022-08-29 03:11 UTC, eunho8713 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func increase(of name: Fruit, to amount: Int) {
😎

2022-08-29 03:11 UTC, Schro2109 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func isMakeAble(juice: Juice) -> Bool {
굳이 외부에서 접근할 수 있도록 만들 필요는 없었던 것 같습니다.
접근제어자를 통해서 내부에서만 접근할 수 있도록 수정해보겠습니다!

2022-08-29 03:18 UTC, Schro2109 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func getAmount(of name: Fruit) -> Int {
재고에 남아있는 해당 과일의 갯수를 Int타입으로 반환하는 메서드로
나중에 쥬스를 만드는 과정에서 필요한 과일의 갯수과 재고에 남아있는 재료의 갯수를 비교할 때 사용할 예정입니다!

2022-08-29 03:20 UTC, Schro2109 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func useIngredients(of menu: Juice) {
굳이 외부에서 접근할 수 있도록 만들 필요는 없었던 것 같습니다.
접근제어자를 통해서 내부에서만 접근할 수 있도록 수정해보겠습니다!

2022-08-29 03:22 UTC, Schro2109 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    var fruitStore = FruitStore()
처음에는 fruitStore 안에 존재하는 재고값을 수정하려면 fruitStore가 var로 선언되어야 한다고 생각했는데 이해를 잘못 했던 것 같습니다.
상수로 수정하겠습니다!

2022-08-29 03:23 UTC, eunho8713 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func isMakeAble(juice: Juice) -> Bool {
굳이 외부에서 접근할 필요하는 없는것 같습니다.
접근제어자를 통해 내부에서만 접근할수 있도록 수정해보겠습니다!

2022-08-29 03:27 UTC, Schro2109 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +class JuiceMaker {
지워진 코드를 다시 작성하는 과정에서 실수로 class타입으로 바꾸었습니다.
구조체로 선언된 이유는 애플의 공식문서(https://developer.apple.com/documentation/swift/choosing-between-structures-and-classes)에서 그 이유를 찾아볼 수 있는데, 

1. 기본적으로 구조체를 사용해야 한다.
2. 데이터를 처리하는 경우에 class로 선언한다.
라고 명시되어 있습니다.

JuiceMaker의 경우 데이터를 처리하는 부분이 없으므로 기본적인 구조체 형식으로 선언하는게 맞는 것 같습니다!

2022-08-29 03:30 UTC, eunho8713 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func getAmount(of name: Fruit) -> Int {
매개변수 name으로 받아온 딕셔너리 fruits의 현재 value값을 반환하는 역할을 합니다. 이 반환값은 JuiceMaker에서 쥬스를 만드는데 필요한 과일의 개수를 저장해놓은 딕셔너리인 recipe와 비교하여 쥬스를 만들수 있는지 판단하는 함수인 isMakeAble()에서 사용됩니다.

2022-08-30 05:36 UTC, Schro2109 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    var fruits: [Fruit: Int] = [.strawberry: 10, .banana: 10, .pineapple: 10, .kiwi: 10, .mango: 10]
변수는 private를 붙여 외부 접근을 막았고, 매직넘버를 defaultAmount라는 상수에 넣어 의미를 확실히 했으며 딕셔너리를 채우는 과정을 열거형의 .allCases를 활용한 반복문을 사용하는 방식으로 수정해 보았습니다!

2022-08-30 05:48 UTC, eunho8713 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    enum Juice {
만약 열거형 내부에 원시값(rawValue)를 사용해 값을 선언해주면 나중에 바꿀수 없기에 상수로 지정될 수가 들어가는것이 좋을것 같습니다. 하지만 열거형 내부에 연산프로퍼티를 사용해 값을 넣어주게 되면 가독성이 더 좋아지고, 값을 나중에 변경해서 사용할 수 있기때문에 값이 변경되는 변수일때 사용하면 좋을것 같습니다!

2022-08-30 07:03 UTC, jaemuYeo reviewed
리뷰반영하느라 고생많았습니다 👏
몇가지 아쉬운점을 전달하고 이번 스텝은 머지진행하겠습니다!
할 수 있는 것들은 다음 스텝에 반영해보면 좋을 것 같아요~
1. 커밋 메시지에 피드백반영 또는 리뷰반영 같은 메시지를 남기는 것 보다
해당 코드에 대한 수정 부분에 대해서 팀원과의 컨벤션에 맞게 남겨주었으면 좋겠어요!
2. 현재 STEP1 브랜치를 통해 맛코의 닉네임별 브랜치로 PR을 보냈는데
이렇게되면 스텝2도 STEP1 브랜치에 합쳐서 PR을 보내야해요 ㅎㅎ
씨유가 저번 프로젝트에서 겪었던 문제였죠??
항상 스텝별로 나누어 진행 후 보낼 저장소의 main에 병합해서 main -> 맛코브랜치로 보내주세요!
3. 커밋메시지와 관련된 얘기이기도 하지만 커밋메시지에 수정된 코드의 설명보다는
반영했다같은 메시지로 남겨있고 재요청시 어떠한 코멘트도 남겨주지 않았어요!
그럼 제가 봤을때는 어떤 부분이 수정되었는지 파악하기 힘들답니다~
재요청도 처음에 PR보낼때처럼 글을 작성할 수 있으니 참고해주세요!😀
또는 커밋을 명확하게 해주는 것이 베스트입니다!

2022-08-30 07:03 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        let juice = JuiceMaker()
테스트를 위해 진행한 코드인 것같은데 PR을 보낼때는 항상 확인하고 불필요한 코드는 제거후 보내주세요!

2022-08-30 07:03 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    init() {
allCases를 활용하여 기본재고를 잘 표현해주었네요!!
이런 방법외에도
```swift
init(defaultAmount: Int) {
    for fruit in Fruit.allCases {
            fruits[fruit] = defaultAmount
        }
}
```
이렇게 초기화해서 외부에서 FruitStore인스턴스를 생성할때 초기값을 줄 수도 있답니다 😀

2022-08-30 07:03 UTC, jaemuYeo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func getAmount(of name: Fruit) -> Int {
여기부터 함수들이 전부 띄어져있지않아요! 가독성을 위해 한칸의 개행을 진행해주세요~
다른 파일도 마찬가지입니다!

2022-08-30 07:03 UTC, merged