쥬스자판기 [Step1] 미르, 미성
tasty-code/ios-juice-maker pull request #70
Opened 2023-12-05 07:39 UTC by mireu930

@FirstDO 안녕하세요 두두!
쥬스자판기 PR보내드립니다! 확인부탁드립니다!

### 고민이 되었던 점
- `JuiceMaker` 구조체 내에 존재하는 `FruitStore` 저장 프로퍼티를 현재는 외부에서 주입받은 후 그것을 그대로 가지고 있는 상태로 만들어 두었습니다.
    ```swift
    struct JuiceMaker {
        private var fruitStore: FruitStore

        init(fruitStore: FruitStore = FruitStore()) {
            self.fruitStore = fruitStore
        }
        // ...
    }
    ```
    `FruitStore` 가 `Class` 로 사전 정의된 것을 보아, `Singleton` 패턴으로 선언해 두어야 `View` 간에 `FruitStore` 의 과일 재고를 공유 및 동기화할 수 있을 것으로 예상했으나, 현재 STEP 에서는 아직 `View` 간의 상호작용까지는 발생하지 않아 현재와 같은 형태로 구현을 해 두었습니다. 추후 해당 부분을 변경하려고 합니다.

- 소모하려는 과일갯수가 기존재고의 과일갯수를 넘어가면 과일이 부족하게 나오게하는 재고의 갯수에 대한 유효성 검사를 진행하는 메서드에서 유닛테스트를 진행했는데 max값을 넘어버리는 값이 나오는 오버플로우가 나는 연산이 되었는데, 쥬스가 만들어짐에 따라 과일재고보다 기존재고의 갯수의 이상으로 연산을 수정해줬습니다.
    ```swift
    //수정전
    private func checkStock(juice: Juice) throws {
        for (fruitName, numberOfFruits) in juice.recipe {
            guard let stock = fruitStock[fruitName] else { throw JuiceMakerError.outOfStock}
            guard stock - numberOfFruits > 0 else { throw JuiceMakerError.outOfStock}
        }

    //수정후
    private func checkStock(juice: Juice) throws {
        for (fruitName, numberOfFruits) in juice.recipe {
            guard let stock = fruitStock[fruitName], stock >= numberOfFruits else { throw JuiceMakerError.outOfStock }
        }
    ```

- 과일이라는 enum 을 취급하기 위해 `Dictionary` 를 사용하였습니다. 저희는 `Dictionary` 를 채택함으로서, `Key` 가 되는 과일이름이 중복되지 않을 수 있는 이점을 얻었습니다.
    
- 저희는 쥬스를 `class`, `struct`, `enum` 중 `enum` 을 택하였습니다. 쥬스를 제작하기 위해서는 과일이 필요한데, 과일은 `enum` 타입으로 되어 있고, `FruitStore` 클래스 등에서 재고를 `Dictionary` 로 관리하고 있기 때문에 통일성을 위해 `enum` 을 채택하였습니다. 쥬스를 제작하기 위한 레시피는 `Computed Property` (계산 프로퍼티) 를 사용하여, 소모되는 과일의 이름과 개수를 `Dictionary` 로 반환하도록 하였습니다. 이를 통해 쥬스를 만드는데 다양한 과일 종류가 필요한 경우, `Dictionary` 에 담고 사용하고 싶은 곳에서 각 `element` 를 접근할 수 있도록 했습니다.
    ```swift
        var recipe: [Fruit: UInt] {
        switch self {
        case .strawberryJuice:
            [.strawberry: 16]
        // ...
    ```
    
    ```swift
    func consumeFruit(juice: Juice) { ... }

    for (fruitName, numberOfFruits) in juice.recipe { ... }
    ```

### 조언을 구하고 싶은 점
- 현재 프로젝트에서 네이밍이 적절한지 궁금합니다.

2023-12-05 23:56 UTC, FirstDo requested changes
안녕하세요, 두분 첫번째 PR 축하드립니다 :)
커밋을 잘 나눠서 하고 코드르 깔끔하게 작성해 주셔서 보기가 편했습니다!!

몇가지 코맨트 남겼으니 확인 부탁드립니다 :)

2023-12-05 23:56 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +//  Created by 미르 & 미성
:)

2023-12-05 23:56 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Model/Fruit.swift
> +enum Fruit {
이렇게 Case가 딱 정해져있는 경우 enum이 정말 좋은 방법이죠!
rawvalue를 사용하지 않고, name 프로퍼티를 만든 방식도 너무 좋습니다 ㅎㅎ

2023-12-05 23:56 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +    var recipe: [Fruit: UInt] {
UnsignedInt를 사용한 부분이 정말 디테일 하네요 ㅎㅎ

2023-12-05 23:56 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    private var fruitStore: FruitStore
클래스 타입의 fruitStore를 var로 선언할 이유 있을까요?

2023-12-05 23:56 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Model/JuiceMakerError.swift
> +enum JuiceMakerError: LocalizedError {
LocalizedError를 채택한 부분이 좋습니다

2023-12-05 23:56 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        fruitStock.updateValue(currentStock - num, forKey: fruit)
아래처럼 쓸 수도 았습니다.
정답은 없습니다만 좀더 일반적인것 같네요..!
`fruitStock[fruit] = currentStock - num`

2023-12-05 23:56 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +final class FruitStore {
FruitStore를 정말 잘 만들어 주셨습니다!

다만 FruitStore라는 과일저장소 객체가 Juice라는 객체를 알 필요는 없다고 생각해요
주스는 과일을 아는게 당연하지만, 과일이 주스를 알 필요가 있을까요??
굳이 결합도를 높힐 필요가 없을것 같아서 Juice를 없애는 방향으로 수정하는게 좋아보입니다

2023-12-05 23:56 UTC, FirstDo commented on JuiceMaker/JuiceMakerTests/JuiceMakerTests.swift
> +    func test_딸기쥬스는_재고가없다() {
요거는 할려다가 안하신건가요? 컴파일이 안돼서요

유닛테스트가 현재 프로젝트에서 필수적인 요구사항은 아니라서 꼭 안하셔도 됩니다.
안하신다면 지워주세요!

2023-12-05 23:56 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        return quantity
간단한 로직은 한줄에 쓰는게 더 가독성이 좋아보여요 (수정사항은 아닙니다!)
```swift
return fruistStock[fruit ] ?? 0
```

2023-12-06 02:09 UTC, mireu79 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        fruitStock.updateValue(currentStock - num, forKey: fruit)
말씀주신 부분이 좀더 직관적이기도 해서 수정하였습니다!

2023-12-06 02:15 UTC, mireu79 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +final class FruitStore {
`FruitStore`라는 과일저장소 객체가 `Juice`라는 객체를 알 필요는 없다고 생각하여 `FruitStore`타입에는 `Juice` 객체를 받는 건 없애 결합도를 낮추고 `Fruit`만 받을 수 있게 수정해줬습니다!

2023-12-06 02:17 UTC, crisine commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        fruitStock.updateValue(currentStock - num, forKey: fruit)
서브스크립트를 통해 접근하는 것이 더욱 직관적이라 해당 방향으로 수정하였습니다! 😄

2023-12-06 02:20 UTC, mireu79 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
checkQuanity 매서드를 활용해 수정해줬습니다!

2023-12-06 03:51 UTC, mireu79 commented on JuiceMaker/JuiceMakerTests/JuiceMakerTests.swift
> +    func test_딸기쥬스는_재고가없다() {
해당부분 런타임확인을 테스트용 유닛테스트를 작성하였는데 지속적으로 런타임확인을 위해 유닛테스트 파일은 로컬에서만 확인을 할수 있도록 `gitinore`해줬습니다.

2023-12-06 04:08 UTC, crisine commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    private var fruitStore: FruitStore
생각해보니 `fruitStore()` 의 경우 쥬스메이커 앱에서 작동하는 `과일 창고` 개념의 역할을 하는 객체이므로, 과일 창고는 단 한개만 존재하여야 하며 교체될 여지가 없다고 생각하여 우선적으로 다음과 같이 변경하도록 하였습니다.

```swift
struct JuiceMaker {
    private let fruitStore: FruitStore
    // ...
}
```

2023-12-06 04:16 UTC, crisine commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        return quantity
버드와 함께 원래 작성되어있던 코드와, 현재 조언해주신 코드를 비교하였을 때 가독성은 확연히 현재 제시해 주신 닐 코얼레싱을 활용한 방식이 최적으로 판단하였으나, 아직 닐 코얼레싱을 사용한 문법이 익숙치 않다는 의견이 일치되어 `STEP 1` 단계에서는 현행 상태를 유지하기로 하였습니다.

추후 닐 코얼레싱을 이곳저곳에 활용해보면서 해당 문법에 익숙해지면 이 부분도 같이 반영하여 회신드리겠습니다 😄

2023-12-07 00:05 UTC, FirstDo approved these changes

2023-12-07 00:05 UTC, merged