쥬스자판기 [Step1] Sidi, Easy
tasty-code/ios-juice-maker pull request #73
Opened 2023-12-06 06:05 UTC by jus1234

리뷰어: @cherrishRed
버드: Sidi, Easy

레드 안녕하세요!
쥬스자판기 프로젝트 STEP 1 PR 드려요~!

### 프로젝트 진행 중 고민사항

**FruitStore 설계시 각 과일 별 저장 변수 생성 VS 과일 별 갯수를 담은 Dictionary 생성**

- 저장 변수

```swift
struct FruitStore {
    var strawberry: Int = 10
    var banana: Int = 10
    var pineapple: Int = 10
    var kiwi: Int = 10
    var mango: Int = 10
}
```

- Dictionary

```swift
struct FruitStore {
    var store: Dictionary<Fruit, Int>
    init() {
        self.store = Dictionary()
        Fruit.allCases.map { store[$0] = 10 }
    }
}
```
저장변수를 사용할 경우 각 속성을 직관적으로 알 수 있다는 장점이 있었고 딕셔너리를 사용한 경우 코드가 간결해지고 이후 호출할 경우에도 분기문 대신 바로 접근할 수 있다는 장점이 있었습니다.

**배열 순회 시 고차함수 VS `for`**

- forEach 사용
    
    코드 한줄로 표현할 수 있다.
    

```swift
var store: Dictionary<Fruit, Int>
Fruit.allCases.map { store[$0] = 10 }
```

- for 사용
    
    직관적이다.
    
    map 등 고차함수를 사용하는 경우보다 코드가 길어진다.
    

```swift
var store: Dictionary<Fruit, Int>
for fruit in Fruit.allCases {
    store[fruit] = 10
}
```
지금의 코드는 짧아서 둘다 직관적으로 이해가 되는 코드이지만 더 복잡한 로직이 들어간 경우나 현업에서는 어떻게 처리하는것이 좋을지도 궁금합니다!

2023-12-06 15:10 UTC, cherrishRed requested changes
두분 모두 step1 진행하시느라 수고하셨습니다!🎉🎉🎉

클래스와 구조체 그리고 enum의 사용성이 좋았습니다!

> FruitStore 설계시 각 과일 별 저장 변수 생성 VS 과일 별 갯수를 담은 Dictionary 생성

이 부분을 dictionary로 처리하신 것은 정말 좋았습니다!
```swift 
var strawberry: Int = 10
```
이라는 것을 봤을 때, 딸기의 아이디가 10이라는 건가? 싶었습니다. 만약 변수로 처리하고 싶으시다면, `strawberryCount` 같은 이름으로 변수 명을 변경하는 것이 좋지 않을까 싶습니다. 

딕셔너리가 지금은 한눈에 보이지 않아 조금 불편할 수도 있지만, 데이터를 다루기에는 더 좋은 선택 인 것 같습니다👏🏻👏🏻👏🏻

> 배열 순회 시 고차함수 VS for

이건 상황에 따라, 또 개인과 팀의 기호의 따라 다릅니다. 

보통은 간결한 로직일 경우 사용하거나, chaining 을 많이 하는 경우 씁니다. 

```swift 
let sumOfEvenNumbers = numbers
    .filter { $0 % 2 == 0 } // 짝수만 걸러냄
    .map { $0 * $0 } // 각 짝수를 제곱함
    .reduce(0, +) // 모든 값을 더함
```
for 문은 안에 한줄 이상의 복잡한 로직을 적을 때, 많이 쓰는 것 같아요. 

이 부분을 취향을 많이 타는 부분인 것 같습니다.ㅎㅎ

예약어를 변수명으로 사용

우선 `stock` 과 `quantity`를 사용하신 부분으로 `count`를 사용하고 싶은신 부분을 추축해보면, 사용하셔도 될 것 같습니다.

이유는 우선 count 가 예약어 인것은 맞지만, 예약어는 절대 쓰면 안된다, 라는게 아닙니다. 그렇게 되면 쓰면 안될 단어가 정말 너무 많아 지거든요.

**😢 안 좋은 예**

예를 들어 이런 타입을 선언했습니다. 
(음 실제로 선언이 가능한지는 모르겠네요.) 
```swift 
enum Dictionary {
	case englishDictionary
	case koreanDictionary
}
```
```swift 
let currentSelectedDictionary: Dictionary = .englishDictionary
```
누가 이런 코드를 봤습니다. 
헷갈릴만 하죠? 

**😆 좋은 예**
```swift 
struct Boxes {
	var count: Int {
		return 박스의 수
	}
}
```
우리는 이미 String 타입에 count 변수가 있고, Array 타입에도 count 가 있는 것을 알고 있죠. 
```swift 
let myBoxes = Boxes()
```
누가 Boxes 구조는 모르고 이런 코드만 봤을 때도, 
박스 계수는 어떻게 구하지? 아마 count 가 있지 않을까 하고 추측하기 쉽겠죠. 

물론 네이밍에 정답은 없습니다! 
그리고 꼭 예약어나 똑같은 변수명을 쓰고 싶을 때, 가끔 
```swift
var _count: Int 
```
이런 식으로 쓰는 경우 정말 가끔 있기는 합니다. 

지금 상황에 해당되지는 않는 것 같습니다.

2023-12-06 15:10 UTC, cherrishRed commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    }
오타가 있네요ㅎㅎ

dictionary 를 for 로 활용하신 것 너무 좋습니다!

저기서 break 가 하는 역할은 무엇일까요?

2023-12-06 15:10 UTC, cherrishRed commented on JuiceMaker/JuiceMaker/Model/JuiceMenu.swift
> +    }
rawValue 사용보다, enum 안에 변수 사용 너무나 좋습니다!

2023-12-07 01:05 UTC, yoruck2 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    }
과일의 재고가 한번이라도 부족했을때 break로 반복을 멈추어서 불필요한 루프를 줄이기 위해 사용했습니다.

2023-12-07 01:09 UTC, jus1234 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    private var store: Dictionary<Fruit, Int>
딕셔너리의 과일의 재고가 변경되는 경우가 있어 var로 선언했습니다!(let으로 선언하면 컴파일 오류가 발생힙니다.)

2023-12-07 01:14 UTC, jus1234 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        guard let nowCount = store[fruit] else {
이후 로직을 조건문 스코프 밖에서 처리하기 위해 처음 작성할 때 가드로 사용했습니다. 하지만 작성하는 과정에서 불필요한 로직이 줄면서 store[fruit] = nowCount + quantity 코드만 남게 되었습니다. 로직이 줄어 if로 작성하는 것도 좋아 보입니다!

2023-12-07 01:17 UTC, yoruck2 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
>  class FruitStore {
사실 큰 고민은 없었고 원래 주어져 있던 클래스였기 때문에 자연스럽게 이어서 작성했습니다. 😅

2023-12-07 02:27 UTC, cherrishRed commented
리펙토링 하신 것 확인 했습니다!

struct 로 고치는게 좋겠다 라는 의미는 아니었고, 정말로 class 를 왜 채택하셨는지 이유가 궁금해서 물어본 것이니, 
고민을 해보시고 차후 step에 따라서 결정하셔도 될 것 같습니다😗

2023-12-07 02:28 UTC, cherrishRed approved these changes

2023-12-08 09:27 UTC, merged