쥬스 자판기 [STEP 1] Jane, Harry
tasty-code/ios-juice-maker pull request #78
Opened 2023-12-07 02:28 UTC by jane1choi

@junbangg
안녕하세요! Jane, Harry입니다! 반갑습니다😊
STEP 1 PR 올립니다 !!! 조언, 제안 모두 환영이니 리뷰 잘 부탁드립니다~! 

## 🔍 What is this PR?
STEP 1의 기능을 구현했습니다.
- 쥬스 자판기 메인 화면 기능 구현
- 메인 -> 재고 관리 뷰 화면전환 구현

## 📝 PR Point
### 데이터 저장 방식 - `Singleton`
`Singleton Patten`을 사용하여 과일 데이터를 관리할 수 있도록 구성했습니다.
싱글톤 사용이유:
앱 전역에서 같은 인스턴스에 접근할 수 있도록 하여 과일 데이터의 동기화 문제없이 관리되도록 하기 위해서 싱글톤 패턴을 선택했습니다.

### 에러처리 방식 - `try` `do-catch`
`JuiceMakerError` 열거형 타입에 에러 케이스를 지정하여 관리했습니다. (현재는 `invalidRequest` 한가지 케이스만 존재)
 재고 관리가 부족할 경우 에러를 던지고 `try`, `do-catch` 를 통해 재고 부족 상황을 안전하게 처리할 수 있도록 했습니다.

### 재고 부족 시 alert present
과일 재고가 부족할 경우 `alert`을 이용해 사용자에게 재고 부족을 알릴 수 있도록 하였습니다.
`UIViewController + Extension` 파일에 `makeAlert()`를 정의해두어 `UIViewController`를 상속받는 어느 뷰에서든 원하는 알럿 타이틀, 메시지, 확인 버튼 타이틀 등을 파라미터로 설정해 `alert`을 쉽게 만들 수 있도록 했습니다.

### 쥬스 제조 로직 
`FuitStore` 클래스 내부 프로퍼티를 `Dictionary` 타입으로 선언해두고 `Fuit` 타입의 키 값으로 원하는 과일 데이터에 접근할 수 있도록 하여 쥬스 케이스 별 과일 재고 확인 및 과일 차감 로직의 반복되는 코드를 줄일 수 있도록 했습니다.

### 버튼 클릭 이벤트 처리 방식
총 7개의 쥬스 제조 버튼을 하나의 `@IBAction func tapMakeJuiceButton()`에 연결했습니다.
각 버튼이 눌릴 때 `sender.currentTitle`을 활용하여 사용자가 선택한 버튼을 구분하고, 각각의 로직을 수행합니다.

### 재고 수량 UILabel 표시
`configUI()` 함수 내부에 `Label`과 데이터(싱글톤)을 연결하여 `viewDidLoad()`에서 초기 값을 설정해줍니다. 
`configUI()`를 `@IBAction func tapMakeJuiceButton()` 내부에서 호출하여 사용자가 버튼을 선택하면 `Label`의 값을 업데이트 할 수 있도록 구현했습니다.

## **+** 질문 
**From. Harry(@hemil0102)**
`@IBAction func tapMakeJuiceButton()` 내부에 `configUI()`를 통해서 Label을 갱신할 경우 현재는 버튼에 상관 없이, 쥬스에 상관 없이 모든 재고를 확인하여 다시 표시해주는데, 현재는 데이터가 적어서 괜찮겠지만, 데이터가 많아질 경우에는 모든 데이터를 조회해야 하므로 성능 열화가 있지 않을까 우려됩니다. 혹시 보다 적절한 방법으로 사용자가 선택한 쥬스에 관련된 재고만 업데이트 되도록 하는 방식의 로직을 구현하는 것이 나을지, 좋은 방법이 있을지 궁금합니다.

## 📸 Screenshot
|    구현 내용    |   구동 영상   |
| :-------------: | :----------: |
| 쥬스 제조 기능 |  ![Simulator Screen Recording - iPhone 14 Pro - 2023-12-07 at 11 23 06](https://github.com/tasty-code/ios-juice-maker/assets/63277563/ec32de17-cdc8-411a-9641-6dfae9e4ec2c) |
| 재고 수정 버튼 클릭 시 화면 전환 | ![Simulator Screen Recording - iPhone 14 Pro - 2023-12-07 at 11 19 48](https://github.com/tasty-code/ios-juice-maker/assets/63277563/9d80ecb8-8af8-4455-9e0e-6f5942345920) |

2023-12-07 16:15 UTC, junbangg commented
수고하셨습니다!
전반적으로 코드가 아주 정돈 되어 보이고 깔끔하네요!!
리드미도 꼼꼼히 작성하서서 코드 이해하는데 도움이 됐습니다😊

#### 질문 주신 내용

엄청 좋은 고민을 하셨군요.!서버가 붙여지는 상황까지 확장하여 고려하셨다니 멋집니다..👍👏👏👏
그것은 사실 기능 요구사항에 따라 다를것 같기도 하네요.!
만약에 화면에 진입할때라던지, 그 전이라던지 한번만 API호출을 해도 되는거면, 저장 해놓은 데이터로 화면을 그리면 되니까 괜찮겠죠?
그치만 그게 아니라 재고가 실시간으로 계속해서 변경될 수 있어서 버튼 누를때마다 매번 API요청을 통해 재고 업데이트를 해야될 수도 있겠죠!

어떤 상황이 됐던, 주어진 요구사항을 토대로 성능 이슈가 없도록 좋은 코드를 고민 해봐야되는게 우리들의 일입니다😊

나중에 비동기 코드, 메모리 등, 효율적인 코드를 위한 공부를 하시게 될텐데, 그게 다 질문 주신 상황들에 대해서 고민 하기 위한것 같네요ㅎㅎ

#### 개선하면 좋을것 같은 점

혹시 코딩하시면서 타입 명시에 대해서 고민해보신 적 있으실까요?!

2023-12-07 16:16 UTC, junbangg requested changes
수고하셨습니다!
전반적으로 코드가 아주 정돈 되어 보이고 깔끔하네요!!
리드미도 꼼꼼히 작성하서서 코드 이해하는데 도움이 됐습니다😊

#### 질문 주신 내용

엄청 좋은 고민을 하셨군요.!서버가 붙여지는 상황까지 확장하여 고려하셨다니 멋집니다..👍👏👏👏
그것은 사실 기능 요구사항에 따라 다를것 같기도 하네요.!
만약에 화면에 진입할때라던지, 그 전이라던지 한번만 API호출을 해도 되는거면, 저장 해놓은 데이터로 화면을 그리면 되니까 괜찮겠죠?
그치만 그게 아니라 재고가 실시간으로 계속해서 변경될 수 있어서 버튼 누를때마다 매번 API요청을 통해 재고 업데이트를 해야될 수도 있겠죠!

어떤 상황이 됐던, 주어진 요구사항을 토대로 성능 이슈가 없도록 좋은 코드를 고민 해봐야되는게 우리들의 일입니다😊

나중에 비동기 코드, 메모리 등, 효율적인 코드를 위한 공부를 하시게 될텐데, 그게 다 질문 주신 상황들에 대해서 고민 하기 위한것 같네요ㅎㅎ

#### 개선하면 좋을것 같은 점

혹시 코딩하시면서 타입 명시에 대해서 고민해보신 적 있으실까요?!

2023-12-07 16:16 UTC, junbangg commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    var fruitContainer: [Fruit: Int] = [
이 프로퍼티의 역할이 뭔가요?!

2023-12-07 16:16 UTC, junbangg commented on JuiceMaker/JuiceMaker/Constant/Juice.swift
> +    case mangoKiwi = "망키쥬스 주문"
이렇게 rawValue 쓰는것도 가능하지만
연산 프로퍼티를 사용하는것은 고민 해보셨을까요??

2023-12-08 01:24 UTC, jane1choi commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +final class FruitStore {
## final 키워드란?
final 키워드를 이용해 메서드, 프로퍼티, 혹은 서브스크립트가 오버라이드 되는 것을 방지할 수 있습니다.
ex) `final var`, `final func`, `final class`
final 키워드를 붙인 method, property, subscript 를 서브클래스에서 오버라이드하면, 컴파일 타임 에러가 발생합니다.
또한, 클래스 정의 시 앞에 final 키워드를 붙여주면 클래스 자체를 final로 표시할 수 있습니다. 서브클래스를 만드는 시도를 한다면 컴파일 타임 에러가 발생합니다.

**요약**
```
1. class 앞에 final 키워드를 붙여주면 다른 클래스에서 상속이 불가능해짐
2. 클래스의 속성(메서드, 프로퍼티 등)에 final을 붙여주면 override(재정의)가 불가능해짐
```

성능적 이점
상속, 재정의 방지 이외에 final 키워드를 사용하면 성능적인 이점도 있습니다.
컴파일러가 메서드의 호출 위치를 파악하는 방법: Method Dispatch 라는 매커니즘을 통해 판단

### Method Dispatch
어떤 연산(operation)을 실행해야하는지 결정하도록 돕는 메커니즘으로,
프로그램이 메모리에서 특정 메서드 호출에 대한 실행 코드를 찾을 수 있는 위치를 CPU에 알리는 프로세스입니다.

#### 종류

**Static Dispatch**

컴파일 타임에 실제 호출할 함수를 결정하는 방식

장점: 함수 호출이 간단하고 속도가 빠름
단점: 서브 클래싱(상속)이 불가능함

참고) UIKit은 class로 뷰를 그리지만,  SwiftUI는 struct로 뷰를 그리기 때문에 Static Dispatch 방식인 SwiftUI가 속도 측면에서 빠를 수 밖에 없음. (struct는 값 타입이라 애초에 상속이 불가능하기 때문)


**Dynamic Dispatch**

런타임 시점에 어떤 메소드가 실행될지 결정되는 것, 컴파일 시점에서는 어떤 함수가 실행될 지 모름

장점: 메서드나 함수 호출이 런타임 시 동적으로 결정되기 때문에, 실행 중에 객체의 실제 타입을 고려할 수 있음. 이는 실행 중에 다양한 조건에 따라 다른 동작을 할 수 있도록 해주며 코드를 유연하고 확장가능하게 해줌
단점: 클래스의 vTable에서의 주소 값을 찾아 메서드를 실행하기 때문에 오버헤드가 발생하기 때문에 속도가 Static Dispatch에 비해 느림 

### final을 이용한 앱 성능 향상

final를 붙이면 클래스의 경우 상속이 불가능하고 메서드나 프로퍼티에 붙을 경우에는 하위 클래스에서 오버라이딩 할 수 없기 때문에 Static Dispatch로 작동하게 됩니다.
명시적으로 상속이나 재정의를 방지하여 Static Dispatch로 작동할 수 있도록 만들어 앱 성능을 향상시킬 수 있는 것!

2023-12-08 01:40 UTC, jane1choi commented on JuiceMaker/JuiceMaker/Constant/Fruit.swift
> +@frozen
`@frozen` 이란?
`@frozen`은 Declaration Attributes 중 하나로, 구조체(struct) 또는 열거형(enum) Declaration에 적용하면 타입 변경을 제한할 수 있습니다.

사용 이유
해당 프로젝트의 경우, 쥬스나 과일 케이스가 고정되어 있다고 생각해서 `@frozen`을 enum 정의 시 사용해주어도 무방하다고 판단했고, 타입이 고정되기 때문에 frozen 열거형에 대한 switch문 사용 시 default case 를 필요로 하지 않는다는 이점이 있어서 사용해주었습니다! (+ 컴파일러 속도 향상에서도 이점이 있어서 케이스가 확실히 고정되어있다면 써주려고 하는 편인 것 같아요..)

`makeJuice()` 내부 로직에 대한 리팩토링 전, switch문으로 쥬스 케이스 별로 차감되어야 하는 과일의 개수를 하나씩 체크해주는 방식으로 코드를 작성했었는데, 이때 default 에 대한 처리를 안해주려고 `@frozen`을 붙여준 것도 있는데,, 코드 리팩토링을 통해 파라미터로 딕셔너리를 받아 해당 key 값에 해당하는 value 값을 이용해 과일 개수를 차감하는 방식으로 변경하면서 `@frozen`을 굳이 써주지 않아도 될 것 같다는 생각이 드네요!! 확인해주셔서 감사합니다 :)

2023-12-08 01:41 UTC, jane1choi commented on JuiceMaker/JuiceMaker/Controller/InventoryViewController.swift
> +class InventoryViewController: UIViewController {
정확하십니다,,, 
지금 코드로 화면전환 까지만 구현한 상태라 해당 파일 생성만 해준 상태입니다!
STEP 2 에서 구현해보도록 하겠습니다😊

2023-12-08 02:03 UTC, jane1choi commented on JuiceMaker/JuiceMaker/Constant/Juice.swift
> +
case문 시작이랑 구분해주려고 띄우긴 했는데 switch문 시작 줄에서 한 줄 띄우기, 붙이기.. 
뭔가 취향 차이라고 생각해서 통일하기 or 팀 컨벤션 맞추기를 잘하면 문제 없다고 생각하는데 혹시 여기에 대해 어떻게 생각하시나요..??

2023-12-08 02:13 UTC, jane1choi commented on JuiceMaker/JuiceMaker/Constant/Juice.swift
> +            return [.strawberry: 16]
해당 메서드의 경우, `Juice` 타입의 케이스를 받아 쥬스별로 차감해야하는 과일과 과일의 개수를 반환하는 메서드입니다!
모든 쥬스에 한가지의 과일만 사용한다면 수량만 반환해도 되겠지만 특정 쥬스의 경우, 두 가지 과일을 사용해야 하는 케이스가 있어서 `Fruit` 타입의 enum을 key 값, 수량을 나타내는 Int 타입의 value 값을 갖는 `Dictionary` 타입을 반환하도록 했습니다!! 
(과일을 사용해야 하는 순서가 없고, enum 타입의 Key값으로 수량을 바로 체크해줄 수 있도록 배열이 아닌 딕셔너리 자료구조를 선택했습니다.)

2023-12-08 02:24 UTC, jane1choi commented on JuiceMaker/JuiceMaker/Controller/OrderViewController.swift
> +              let juice = Juice(rawValue: selectedButton) else {
`UIButton`의 타이틀네임이 담겨서 String 타입입니다!
네이밍 때문에 `UIButton` 타입이라고 인지할 수 있어 좋지 않은 네이밍 같다는 생각이 드네요..!!
확인해주셔서 감사합니다😊😊

2023-12-08 02:27 UTC, hemil0102 commented on JuiceMaker/JuiceMaker/Constant/Fruit.swift
> +@frozen
@frozen을 열거형에 활용할 경우 향후에 새로운 case가 추가 되지 않는걸 약속합니다. 
flexibility 를 줄여주기에 컴파일 시간을 줄여줍니다. 

애플 문서에서 확인한 바로는 When the compiler isn’t in library evolution mode, all structures and enumerations are implicitly frozen, and this attribute is ignored.

위와 같이 우리는 library evolution mode를 활용하지 않기에 암시적으로 frozen을 사용하고 있습니다. 따라서 열거형 case를 switch 구문을 @frozen 없이 구현해도 default구문을 사용하지 않아도 됩니다. 활용한 이유는 제인이 설명한바와 같습니다.

2023-12-08 02:30 UTC, hemil0102 commented on JuiceMaker/JuiceMaker/Constant/Juice.swift
> +            return [.strawberry: 16]
제인과 같은 의견입니다.

2023-12-08 02:30 UTC, hemil0102 commented on JuiceMaker/JuiceMaker/Controller/OrderViewController.swift
> +    @IBOutlet weak var mangoQuantityLabel: UILabel!
감사합니다. 적용해주었어요 ^^

2023-12-08 02:33 UTC, hemil0102 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    private let fruitStore = FruitStore.shared
키워드는 많이 접해보았는데, 저는 아직 제대로 접해본 적은 없습니다 ^^;

2023-12-08 02:46 UTC, hemil0102 commented on JuiceMaker/JuiceMaker/Controller/OrderViewController.swift
> +    private func configUI() {
감사합니다. 풀어서 사용하는 방향으로 연습하겠습니다!

2023-12-08 02:46 UTC, hemil0102 commented on JuiceMaker/JuiceMaker/Controller/OrderViewController.swift
> +    @IBAction func tapMakeJuiceButton(_ sender: UIButton) {
이 친구와 그 위에 친구도 적용했습니다. 감사합니다.

2023-12-08 02:48 UTC, hemil0102 commented on JuiceMaker/JuiceMaker/Controller/OrderViewController.swift
> +              let juice = Juice(rawValue: selectedButton) else {
`sender`는 `UIButton` 타입이고, `.curruntTitle` 메서드의 타입은 `String?`입니다. 그리고 `guard let`을 통해서 `selectedButton` 에 옵셔널을 풀어낸 문자열을 할당하기에 `selectedButton`의 타입은 `String`입니다.

2023-12-08 02:50 UTC, hemil0102 commented on JuiceMaker/JuiceMaker/Extension/UIViewController + Extension.swift
> +    func makeAlert(title: String, message: String, confirmTitle: String) {
감사합니다~

2023-12-08 08:12 UTC, hemil0102 commented on JuiceMaker/JuiceMaker/Constant/Juice.swift
> +    case mangoKiwi = "망키쥬스 주문"
Juice 열거형 내부 checkFruitQuantity() 메서드를 연산 프로퍼티로 변경해주었습니다. 
말씀해주신 맥락이 이 방향이 맞나요? 혹시 아니라면 조금 더 설명 부탁드릴게요!
커밋 적용 (785d75569f30c73cb2016465a013c954dea5ecc7)

2023-12-08 08:22 UTC, jane1choi commented on JuiceMaker/JuiceMaker/Extension/UIViewController + Extension.swift
> +    }
이 코드는 해리가 잘 설명해주신 것 같은데 휴먼 에러를 방지하기 위한 코드 맞습니다,,
UIKit에서 테이블뷰, 컬렉션뷰 셀 등록, 화면전환 등의 코드 작성 시에 `String` 타입의 className에 대한 `identifier`를 써줄 일이 굉장히 많은데요! 조금이라도 오타로 인한 에러(무슨 에러지.. 디버깅 다했는데 오타였을 때.. 굉장히 킹받는 상황...)를 방지하기 위해
`static let identifier = "identifier 이름"` 이런 식으로 전역적으로 선언 해주고 계속 사용해주거나, `identifier`가 많아질 경우 `identifier` 이름만 따로 선언을 해둔 구조체를 만들어놓고 사용하곤 하는데요, 사실 이 방법도 어쨌든 `String`값을 한 번 써주어야 하기 때문에 오타가 생길 수 있겠죠!!

그냥 클래스 이름을 바로 `String` 으로 변환해줄 수 있는 방법이 없나? 하다가 찾은 `NSStringFromClass(_:)` 요친구...
<img width="877" alt="스크린샷 2023-12-08 오후 3 20 04" src="https://github.com/tasty-code/ios-juice-maker/assets/63277563/598db7ae-d2eb-46b2-b78b-37cfbaead608">
클래스 타입을 파라미터로 넘겨주면 `String` 타입으로 변환을 해주는 친구입니다!!!

위의 코드에서 `String`으로 변환해준 값이 변수에 담기도록 선언을 해주었는데, 이 코드를 `UIViewController` extension 에 작성해준다면 `UIViewController` 타입의 클래스이름을 `.className` 으로 아주 쉽게 가져올 수 있겠죠???
지금은 딱히 사용할 일이 많이 없을 것 같아 `UIViewController + Extension` 파일에만 넣어두었는데, 저는 이 친구를 `UIView`, `UITableView`(셀 등록 과정) 등등 코드를 좀 가공해서 아주 유용하게 사용하고 있습니다.. ㅎ

활용 예시도 보여드리겠습니다!!
```Swift
protocol TableViewRegisterable {
    static var isFromNib: Bool { get }
    static func register(target: UITableView)
}

extension TableViewRegisterable where Self: UITableViewCell {
    static func register(target: UITableView) {
        if self.isFromNib {
            target.register(UINib(nibName: Self.className, bundle: nil), forCellReuseIdentifier: Self.className)
        } else {
            target.register(Self.self, forCellReuseIdentifier: Self.className)
        }
    }
}

extension BaseTableViewCell: TableViewRegisterable {
    
    static var isFromNib: Bool {
        get {
            return true
        }
    }
}
```
이런 식으로 프로토콜에 함수 기본구현을 이용해 선언해두면 셀 register 코드도 간결하게 써줄 수 있답니다!!!!!!!

2023-12-11 07:56 UTC, jane1choi commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    private let fruitStore = FruitStore.shared
@junbangg 
생각해보니까 데이터 전달 방식에 대한 코멘트인 것 같네요!
굳이 싱글톤으로 데이터를 저장해야되는 이유가 있을까요..? 라는 의도로 질문 남겨주신 것 같은데,
저도 STEP2 구현하면서 화면 간 데이터 전달이 가능한 상황이라 굳이 싱글톤이 필요없을 것 같다는 생각이 들어서 의존성 주입 + 화면 간 전달 방식으로 리팩토링 해보려고 합니다! 제가 파악한 부분이 맞을지 모르겠는데,,, 아니라면 코멘트 추가로 남겨주시면 감사하겠습니다!!!

2023-12-11 14:02 UTC, junbangg commented on JuiceMaker/JuiceMaker/Constant/Fruit.swift
> +@frozen
크..너무 멋집니다🫢🥲 👍👍

2023-12-11 14:02 UTC, junbangg commented on JuiceMaker/JuiceMaker/Constant/Juice.swift
> +
아뇨! 두 분이서 정하신거라면 저도 이견 없습니다!

2023-12-11 14:04 UTC, junbangg commented on JuiceMaker/JuiceMaker/Controller/OrderViewController.swift
> +              let juice = Juice(rawValue: selectedButton) else {
물롬 네이밍도 기가막히게 정하시면 가독성이 향상 되지만, 이런 경우에는 타입도 함께 명시하면 더더욱 좋을것 같습니다! 
타입 명시에 대한 고민을 한번 해보시면 좋을것 같습니다😊😊

2023-12-11 14:06 UTC, junbangg commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +final class FruitStore {
와우.. Method Dispatch에 대해서도 공부하셨군요 너무 훌륭합니다👏👏👏👏
제가 슬쩍 봤었을때 다른 곳에서도 final 을 붙일 수 있을것 같아요! 다음 스텝에서 수정하셔도 좋습니다~

2023-12-11 14:09 UTC, junbangg commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        let dic = juiceType.checkFruitQuantity(juice: juiceType)
공유/설명을 통해서 고민을 해보시고 결론까지 도달하시는 과정 아주 좋아보이는군요ㅎㅎ같이 이야기만 해봐도 답이 나오는 매직👐

2023-12-11 14:14 UTC, junbangg commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    private let fruitStore = FruitStore.shared
맞습니다!
싱글톤이 장점도 많지만 단점도 많은것이 사실이죠!
불필요하다고 생각하는 경우라면 아예 없애는것도 방법이고, 유지는 하되, 싱글톤에 저장될 데이터 중 필요한것들만 주입 받도록 변경할 수도 있을것 같아요!

그리고 제가 처음에 이야기 드린 이유는, shared 보다도, 그냥 FruitStore 타입만 의존하고, 생성자를 통해 의존성 주입을 받도록 수정할 수도 있을것 같아서였어요!

2023-12-11 14:17 UTC, junbangg commented on JuiceMaker/JuiceMaker/Constant/Juice.swift
> +    case mangoKiwi = "망키쥬스 주문"
아하 조금은 맥락이 다른데요!
지금 되어있는 rawValue 타입을 실제로 사용할때,
문자열이 어떤 역할인지 표현하기 더 적합한 방법이 있지 않을까 해서요(연산 프로퍼티)

그게 description 이 됐던, labelString이 됐던, 
연산 프로퍼티를 활용한다면 역할이 더 분명해질 수 있는 것이죠(rawValue 보다)

혹시 이해가 되셨을까요??

2023-12-11 14:18 UTC, junbangg commented on JuiceMaker/JuiceMaker/Extension/UIViewController + Extension.swift
> +    }
설명 감사합니다! 새로운거 배워갑니다!🙋‍♂️🙇‍♂️

2023-12-12 01:00 UTC, jane1choi commented on JuiceMaker/JuiceMaker/Constant/Juice.swift
> +    case mangoKiwi = "망키쥬스 주문"
아하 이해했습니다!!!! 그냥 문자열 보다 해당 문자열이 어떤 것을 의미하는지 표현할 수 있는 프로퍼티 이름의 프로퍼티를 사용하는 것이 좋겠다는 말씀인 것 같아요!!! 의견 반영해서 수정해보겠습니다!! 조언 감사해요😊😊

2023-12-12 05:19 UTC, merged