쥬스 자판기 [STEP 1] Nero, Sajae
tasty-code/ios-juice-maker pull request #81
Opened 2023-12-07 05:45 UTC by suojae3

# Tasty Code

**리뷰어:** <br/>
@keeplo

**버드:** <br/>
@ODDNERO
@suojae3

안녕하세요 marco!
첫 PR 잘부탁드립니다🤩

---

<br/>

### 프로젝트 소개

### 파일 구조

<pre>

JuiceMaker-iOS/
│
├── View/
│   └── JuiceMachineView.swift
│
├── ViewController/
│   └── JuiceMachineViewController.swift
│
└── Model/
     ├── Reception.swift
     ├── JuiceType.swift
     ├── Juicemaker.swift
     └── FruitStore.swift

</pre>

### 다이어그램

```swift
+------------------------------------+
|           JuiceMachineView         |
+------------------------------------+
       |
       V
+------------------------------------+
|     JuiceMachineViewController     |
+------------------------------------+
       |
       V
+------------------------------------+
|             Reception              |
|------------------------------------|
| - juiceMaker: JuiceMaker           |
| - acceptJuiceOrder()               |
+------------------------------------+
       |
       V
+------------------------------------+
|             JuiceMaker             |
|------------------------------------|
| - fruitStore: FruitStore           |
| - makeJuice()                      |
+------------------------------------+
       |
       V
+------------------------------------+
|             FruitStore             |
|------------------------------------|
| - fruitsStock: [Fruits: Int]       |
| - incrementFruit()                 |
| - decrementFruit()                 |
+------------------------------------+
```

<br/>

### 고민1.  요구사항에 따라 어떤 객체가 꼭 필요할까?

- UIComponent 객체 → `@IBOutlet`, `@IBAction`
- 주문 처리 → `Reception`
- 쥬스 레시피 → `JuiceMaker`
- 과일 재고 → `FruitStore`

### 고민2. 객체간의 연결관계를 가장 느슨하게 연결할 수 있는 방법이 있을까?

- 단방향 의존성 설정
- `JuiceMachineViewController` → `Reception` → `JuiceMaker` → `FruitStore`
- `Fruitstore`와 `JuiceMachineViewController`  의 데이터 바인딩(과일재고)은 notification center를 이용해 구현(예정)

2023-12-07 12:03 UTC, keeplo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +//MARK: - FruitStore 메서드
`// MARK: -...` 형태로 공백을 줘보면!!! 좋을것 같아요!!

[Editing source files in Xcode](https://developer.apple.com/documentation/xcode/creating-organizing-and-editing-source-files/)

사용법을 숙지하고 잘사용한다면 Xcode에서 제공하는 minimap 기능으로 코드를 이해하기 쉬워질 수 있어요!

2023-12-07 12:05 UTC, keeplo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        guard let currentStock = fruitsStock[fruit] else { print("\(#function) 에러 발생!"); return }
`guard let` 바인딩을 이용해주셨네요!
특정한 기준으로 메서드의 빠른 리턴을 하는 목적을 잘 활용해주셨네요!! 👏🏻

한가지 궁금한 점이 있습니다!
else 블럭을 `;` 를 추가하면서 한줄로 작성한 의도가 혹시 있으실까요?

2023-12-07 12:05 UTC, keeplo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        guard let currentStock = fruitsStock[fruit], currentStock-count>0 else { print("\(#function) 재고 부족!"); return }
`currentStock-count>0` 이 부분을 모두 붙여서 작성하신 의도가 혹시 있으신가요? 

가독성을 위해 공백을 추가하면 어떨까요? `currentStock - count > 0`

2023-12-07 12:08 UTC, keeplo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        guard let currentStock = fruitsStock[fruit], currentStock-count>0 else { print("\(#function) 재고 부족!"); return }
`func incrementFruit(of fruit: Fruits, at count: Int)`의 guard else 블럭을 포함해서
프린트로 log 형태만 남기는게 아니라 `FruitStore` 인스턴스를 소유하는 개체에 재고부족 또는 오류를 전달하면 좋을것 같아요!

개체간에 메시지를 전달하는 방법으로 어떤 방법들이 있을까요?
위 형태라면 어떤 방법이 좀 적절할까요?

2023-12-07 12:10 UTC, keeplo commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +
어떤 경우는 한줄 줄바꿈인데 몇명 경우는 두줄 줄바꿈입니다!

동일한 코드 컨벤션을 유지하면 좋을 것 같아요!

2023-12-07 12:11 UTC, keeplo commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func makeStrawberryJuice() {
메서드를 Reception.acceptOrder() 와 달리 분리하신 이유가 있을까요?

`JuiceMaker` 개체가 `주스를 만든다`라는 동작은 하나로 표현하는 방법도 있을 것 같은데
어떤 방향이 좋다고 생각하시나요?

2023-12-07 12:16 UTC, keeplo commented on JuiceMaker/JuiceMaker/Model/Reception.swift
> +    case stockManage
`stockManage` 라는 케이스는 어떤 의도록 작성해주신 걸까요?

2023-12-07 12:18 UTC, keeplo commented on JuiceMaker/JuiceMaker/View/JuiceMachineView.swift
> +}
다음 뷰를 작성해주신 이유가 있을까요?

어떤 의도로 뷰를 작성했는지 궁금합니다!

2023-12-08 01:09 UTC, suojae3 commented on JuiceMaker/JuiceMaker/Controller/SceneDelegate.swift
> +
아핫;; 재고처리관련 기능구현에 문제가 있는지 `Scenedelegate`에서 재고확인로그를 프린트해주는 코드를 적었다가 커밋올릴 때 지웠었습니다. 빈 한 줄을 놓쳤던 것 같아요! 꼼꼼한 리뷰 감동..🥹

2023-12-08 01:20 UTC, ODDNERO commented on JuiceMaker/JuiceMaker/View/Base.lproj/Main.storyboard
> +            <point key="canvasLocation" x="805" y="92"/>
화면 옮기다가 뭔가 잘못 드래그한 게 아닐까 싶어요 하핫 😅😅

그런데 저 코드만 봤을 때 어떤 UI 컴포넌트가 변경된 건지 파악하기가 어려운데, 확인할 수 있는 방법이 있는지 궁금합니다!

2023-12-08 01:29 UTC, ODDNERO commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +//MARK: - FruitStore 메서드
오 공식 문서에 마크 주석 부분이 있었네요! 

파라미터, 에러 처리, 리턴에 대한 주석 부분도 앞으로 참고해서 적용해 보면 좋을 것 같아요 👏🏻👏🏻👏🏻
감사합니다 😊

2023-12-08 01:32 UTC, suojae3 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        guard let currentStock = fruitsStock[fruit] else { print("\(#function) 에러 발생!"); return }
`guard let ` 을 쓰면 왜인지 모르겠지만 한 줄에 담아야한다는 강박관념이 있었습니다..🥹 
한 줄로 끝낼지, 아래와 같이 줄바꿈을 하는게 나을지 궁금해요!

![image](https://github.com/tasty-code/ios-juice-maker/assets/126137760/fb8b7479-6ab9-4d3b-90fc-c3b4e7d9a23d)

2023-12-08 01:38 UTC, ODDNERO commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        guard let currentStock = fruitsStock[fruit], currentStock-count>0 else { print("\(#function) 재고 부족!"); return }
공백을 넣어서 작성하는 게 가독성에 좋을 것 같네요! 
앞으로는 사소한 부분들도 신경 써 보도록 하겠습니다 🫡🫡

2023-12-08 02:08 UTC, suojae3 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        guard let currentStock = fruitsStock[fruit], currentStock-count>0 else { print("\(#function) 재고 부족!"); return }
연결된 객체에게 에러이벤트를 전달하는 가장 먼저 떠오르는 방법은 `do-try-catch`문이었습니다.
그럼에도 불구하고 `do-try-catch`문을 사용하지 않은 이유는 아래와 같습니다.

1. 에러처리의 목적은 개발자의 디버깅을 위해 + 사용자에게 알려주기 위해 라고 생각했습니다.
2. 사용자에게 알려준다는 것은 Alert창과 같은 뷰를 띄워주는 것이었습니다.
3. Alert창을 띄우기 위해서는 UIViewcontroller에 이벤트를 전달해주어야합니다.  
4. 따라서 이벤트를 VC까지 전달하기위해 연결된 객체를 통과시켜 전달하거나 클로저 등을 통해 이벤트를 전달해야했습니다.
5. 하지만 이것보다 생각한 더 좋은 코드는 AlertHandler라는 객체를 만들어 서로의 이벤트를 주고받을 필요없이 그냥 에러 발생 사실을 최상위 뷰에 보여주기만 하면 더 간결한 코드가 될 것이라 생각했습니다!
6. 이를 통해 컴파일 타임에서 에러를 잡을 수 없다는 단점이 있지만 trade-off 를 고려했을 때 최대한 객체간의 연관성을 줄이고싶었습니다!

2023-12-09 10:40 UTC, suojae3 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func makeStrawberryJuice() {
#### `JuiceMaker` 로 할 경우
<img width="400" alt="image" src="https://github.com/tasty-code/ios-juice-maker/assets/126137760/e311a63f-3c4d-413d-b813-ff6dabdfd7cf">

#### 각 과일 타입별로 메서드를 만들 경우
<img width="400" alt="image" src="https://github.com/tasty-code/ios-juice-maker/assets/126137760/356daae7-64d5-4c1f-b0f1-7f0d4956840e">

<br/>

어떤 코드가 더 나은 코드인지 판단하는 것은 너무 어려운 것 같습니다 ㅠㅠ
그럼에도 불구하고 개별 함수를 최대한 날씬(?)하게 쓸 때 읽기가 편한 것 같아서 아래의 경우를 선택했습니다!

Marco의 생각은 어떤가요?

2023-12-11 08:55 UTC, suojae3 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +final class FruitStore {
final 키워드를 사용시 다이나믹 디스패치에서 스태틱 디스패치로 바꾸어주어 struct와 동일한 성능을 낼 수 있었습니다!
또한 FruitStore 내부에 딕셔너리값으로 과일재고가 저장되기 때문에 값타입일 경우 값이 참조가 아닌 복사가 될 위험이 있어 구조체 선언은 피했습니다

2023-12-11 08:58 UTC, suojae3 commented on JuiceMaker/JuiceMaker/View/JuiceMachineView.swift
> +}
MVC 패턴 구현을 위해 UI컴포넌트 선언은 뷰파일에서 해주고 뷰컨에서는 addTarget() 메서드를 통해 버튼액션 메서드를 구현했습니다!

2023-12-11 09:04 UTC, suojae3 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +
감사합니다 :)

2023-12-11 09:07 UTC, suojae3 commented on JuiceMaker/JuiceMaker/Model/Reception.swift
> +            }
Reception 이라는 객체를 만든이유는 일종의 파사드 패턴을 구현하고 싶었습니다! 쥬스레시피나 과일 증감함수는 파사드 객체인 reception 뒤편으로 보호하고 VC는 오직 Reception과 소통하게끔 구현했습니다. 

따라서 reception을 통해 어떤 주스를 만들지 결정할 수 있도록 스위치문을 추가했습니다.

2023-12-11 09:58 UTC, suojae3 commented on JuiceMaker/JuiceMaker/Model/Reception.swift
> +struct Reception {
(코드수정후 남기고 싶은말..ㅠ)
원래 노티피케이션 센터에 과일재고 값을 담아서 뷰컨과 데이터바인딩을 했어야 했지만 노티피케이션에 대한 학습 불충분으로 급하게 재고변경 이벤트전달만 구현해놓았습니다 ㅠㅅㅠ

2023-12-11 13:54 UTC, keeplo requested changes
생각보다 코멘트가 많네요 😹

어디까지나 미처 생각해보시지 못했다면!
가볍게라도 한번 생각해보면 좋을것 같아서, 잡히는 부분들은 모두 코멘트 남겼습니다!
너무 고민이되거나 시간을 많이 소요하게되면 과감히 멈추고, 
디엠주셔서 힌트를 얻어가시면 좋을것 같아요!

Step 진행에 너무 몰두하는 것도 문제지만, 
모든일에 순서가 있는데 저의 커리큘럼 파괴 리뷰때문에 
시간을 너무 많이 쓰지 않았으면 하는 부분도 있어요!

그리고 조금이라도 의문이 들거나 필요성에 대한 의심이 생긴다면,
바로 제게 논의점을 언급해주세요!
함께 고민해보고 깊은 내용을 함께 탐구해보면 좋을것 같아요!

리뷰의 목적은 체점이 아니라 함께 고민하고 발전하는데 있다고 생각합니다!

---

몇가지 변경 요청점도 있고 답변 또는 코드에 대한 질문이 있습니다
답변 및 처리가 완료되시면 디엠 부탁드려요!  👊👊👊

2023-12-11 13:54 UTC, keeplo commented on JuiceMaker/JuiceMaker/View/AlertHandler.swift
> +    func getAlertMessage(alertType: AlertType) -> (String,String) {
CS 에서 프로그래밍 언어론 관련한 수업에서 저의 경험을 공유해드리면
사람이 다루는 고급언어의 목표점은 사람의 말처럼 보이는 방향이라고 해요.
그래서 코드를 작성해서 보았지만 그냥 읽어도 어떤 흐름인지 이해되는 방향이 좋을거라고 생각합니다.

그런면에서 API Design Guidelines 에서도 언급하는 것처럼 인수 이름을 자연스럽게 지어주면 좀 더 호출부를 이해하기 좋을것 같아요 

~~~swift
함수이름(으로: 타입)

얼럿메시지(으로: 주스주문성공)
~~~

2023-12-11 13:54 UTC, keeplo commented on JuiceMaker/JuiceMaker/Controller/JuiceMachineViewController.swift
> +    @objc func getFruitsStock() {
Swift가 아닌 다른언어를 먼저 배우셨다면,
위와 같은 get 네이밍과 용도를 자연스럽게 많이 사용하실거라는걸
믿어 의심치 않습니다.

[Swift 개발자처럼 변수 이름 짓기 - 노수진](https://soojin.ro/blog/english-for-developers-swift) 
제가 좋아하는 개발자분의 블로그 포스팅인데요!
`#6 스위프트의 getter` 에서 보여주는 예시처럼 
애플에서 제공하는 API 네이밍에서는 반환타입의 개체(타입 또는 속성) 이름을 그대로 써주는 형태로 구현되어 있다고 해요.

추가적으로 팁 일수도 있는데 `private(set)` 같은 키워드도 존재합니다.
이런 부분도 고려해보면 좋을것 같아요!

하지만 팀마다 컨벤션이 다르다보니 꼭 필수적인 영역은 아닙니다!

2023-12-11 13:54 UTC, keeplo commented on JuiceMaker/JuiceMaker/Controller/JuiceMachineViewController.swift
> +    @objc func getFruitsStock() {
앞선 `get` 용어 자체에 대한 피드백 이외로
함수명에 대한 피드백을 좀 더 드리자면,
기존의 get 메서드라면 상태값(프로퍼티)를 간접 접근해서 값을 전달하는 성격을 띄어야 하는데

`getFruitStock` 메서드의 용도는 View - Label에 값을 전달해서
화면을 그리는 목적이 좀 더 맞지 않을까 생각합니다!

함수의 동작과 동작을 대변하는 함수명(메서드명)을 지어주면 좋을것 같아요!

2023-12-11 13:54 UTC, keeplo commented on JuiceMaker/JuiceMaker/Controller/JuiceMachineViewController.swift
> +        setupNotificationCenter()
다양한 작업을 ViewDidLoad 시점에 담아주셨군요!

ViewDidLoad는 어떤 메서드인지, 어떤 의도로 이런 동작을 이곳에 작성했는지
설명해주실 수 있을까요?

2023-12-11 13:54 UTC, keeplo commented on JuiceMaker/JuiceMaker/Controller/JuiceMachineViewController.swift
> +    reception.acceptOrder(request: .juiceOrder, juiceType: .banana)
동일한 탭으로 수정되어야할 것 같아요!

2023-12-11 13:54 UTC, keeplo commented on JuiceMaker/JuiceMaker/Controller/SceneDelegate.swift
> +
변경점이 많을 수록 커밋 단위에 변화의 목표를 알아채기 힘들 수 있어요!

Stage 올라온 변경점을 라인 단위로 꼭 확인해야 합니다!  
불필요한 변경점은 단순 줄바꿈이어도 없는게 좋아요!

2023-12-11 13:54 UTC, keeplo commented on JuiceMaker/JuiceMaker/View/Base.lproj/Main.storyboard
> +            <point key="canvasLocation" x="805" y="92"/>
말씀해주신 것처럼  저 코드만 봤을때 어떤 UI 컴포넌트가 변경된 건지 파악하기가 어렵습니다.
마찬가지로 의도된 스토리보드 변경점이라도 수정 후에 스토리보드에서 어떤 부분이 파악하기 어려울 수 있어요!

그렇기 때문에 **위와 같이 의도되지 않은 변경점은 포함되지 않는게 좋고**
스토리보드 변경점만 커밋을 따로한다거나, 변경점 상세를 꼭 커밋기록으로 남기는 것도 중요할 것 같습니다!

커밋 전에 Stage에 불필요한 부분은 없는지 확인해서 불필요한 부분들은 Discard 해주는게 좋습니다!
git 다루기에서 커맨드 단위로 관리하시기 힘들면 GUI Git 툴을 사용해보시는 것도 추천드려요

저는 fork 사용하는데 추천합니다 ㅎ

2023-12-11 13:54 UTC, keeplo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +final class FruitStore {
final 키워드로 스태틱 디스패치에 동작되도록 처리해주셨군요!
`struct와 동일한 성능을 낼 수 있었습니다!` 이 부분에서 말씀해주신 성능의 이점은 어떤건지 알려주실 수 있을까요?

2023-12-11 13:54 UTC, keeplo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        guard let currentStock = fruitsStock[fruit] else { print("\(#function) 에러 발생!"); return }
음 제가 질문드린 요점은 `;` 부분이 있었습니다

제가 기대한 코드는 왜 블럭 안이 한 줄처리가 되었는 지 였어요!

~~~swift
guard let currentStock = fruitStock[fruit],
           currentStock - quantities > -1 else {
   print("\(#function) 재고 부족!")
    return
}
~~~

처럼 조건의 구분도 줄바꿈이 가능할 것 같은데
이런 부분의 특별한 의도가 없으시다면

줄바꿈을 통해서 작성하면
git 을 통해 변경점을 파악할때 줄 별로 확인하는 이점이 있을것 같아요

위 스크린샷에서 29번줄에서 
한 커밋은 바인딩되는 값에 변수명을 네이밍 수정하고
어떤 커밋은 두번째 조건을 수정한다면 

같은 29번줄에 계속 변경점이 생깁니다

2023-12-11 13:54 UTC, keeplo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        guard let currentStock = fruitsStock[fruit], currentStock - quantities > -1 else { print("\(#function) 재고 부족!"); return }
0이나 -1 같은 수 자체는 코드를 이해하는데 어려움을 줄 수 있어요!
`매직넘버` 라고 부르기도 하는데

지금처럼 단순한 빼기 기능이 아니라면 currentStock - quantities 같은 간단한 로직이
매우 복잡할거고 해당 로직을 거친 결과가 `-1` 이면 그게 무엇을 의미하는지 
파악하기가 직관적이지 않고 어려울 수 있어요!

좀 더 직관적으로 이해하기 좋게 위 조건을 고민해보면 좋을것 같아요!

2023-12-11 13:54 UTC, keeplo commented on JuiceMaker/JuiceMaker/Model/Reception.swift
> +            return juiceMaker.fruitStore.fruitsStock[.pineapple] ?? 0
기차 충돌 Train Wreck 이라고도 표현하는데
디미터의 법칙 Law of Demeter 을 조사해보시고 고민해보면 좋을것 같아요!

Reception에서 JuiceMaker의 프로퍼티 접근을 단순 접근 이상(메서드 사용, 내부 프로퍼티 사용) 으로 하게되면 캡슐화가 깨지고 의존성도 강하게 결합될것 같아요!

2023-12-11 13:54 UTC, keeplo commented on JuiceMaker/JuiceMaker/Controller/JuiceMachineViewController.swift
> +    deinit { NotificationCenter.default.removeObserver(self) }
register 한  Observer를 ViewController 디이니셜라이저 시점에 제거해주는 군요!
아주 좋습니다!

2023-12-11 13:54 UTC, keeplo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    Notification.Name("fruitStockDidChange")
이 부분을 줄바꿈 하신 이유가 있을까요?

2023-12-11 13:54 UTC, keeplo commented on JuiceMaker/JuiceMaker/Model/Reception.swift
> +struct Reception {
데이터 바인딩을 의무적으로 할 필요는 없습니다!

고민해보시되 선택과 집중을 해주면 좋을 것같아요!

Observing 방식엔 무엇이 있는지 탐구하시길 원하면 좀더 고민해보면 좋고
이벤트 전달 방식으로 화면을 리프레쉬 해줘도 동작만 잘되면 문제 없습니다!

2023-12-12 01:31 UTC, ODDNERO commented on JuiceMaker/JuiceMaker/View/AlertHandler.swift
> +    func getAlertMessage(alertType: AlertType) -> (String,String) {
목표점은 사람의 말처럼 보이는 방향! 앞으로 그런 부분을 고민하면서 지어 보도록 하겠습니다 🫡🫡

2023-12-12 01:39 UTC, ODDNERO commented on JuiceMaker/JuiceMaker/Controller/JuiceMachineViewController.swift
> +    @objc func getFruitsStock() {
> 스위프트에서 어떤 인스턴스를 리턴하는 함수나 메서드에 `get`을 쓰지 않는다. `get` 없이 바로 타입 이름(명사)으로 시작하면 된다.
>
미처 몰랐던 부분인데 새로 알고 갑니다! 앞으로 변수명 지을 때도 참고하기 좋을 것 같아요 👍🏻 감사합니다

2023-12-12 06:28 UTC, ODDNERO commented on JuiceMaker/JuiceMaker/Controller/JuiceMachineViewController.swift
> +    @objc func getFruitsStock() {
조언 참고하여 `getFruitStock` 대신
과일 재고의 값을 받아 업데이트한다는 의미의 `updateFruitStock`으로 함수명 변경했습니다!

2023-12-12 07:24 UTC, ODDNERO commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        guard let currentStock = fruitsStock[fruit], currentStock - quantities > -1 else { print("\(#function) 재고 부족!"); return }
매직 넘버를 지양하기 위해 먼저
`private let limitedQuantity = 0` 0을 limitedQuantity로 선언하고
`currentStock - quantities >= limitedQuantity`로 0 이상일 때의 조건을 표현하였습니다! 🫡

2023-12-12 09:17 UTC, suojae3 commented on JuiceMaker/JuiceMaker/View/AlertHandler.swift
> +    static let shared = AlertHandler()
Alert 창 띄우기를 최대한 간편하게 하고싶었습니다! 싱글톤 선언을 통해 코드 작성 간편성을 살렸습니다! 
UIViewController를 확장해서 구현하는 방법도 고민해보았으나 VC객체를 만들 때마다 불필요한 코드가 추가된다는 점에서 싱글톤을 선언 사용하게 되었습니다!

2023-12-12 09:18 UTC, suojae3 commented on JuiceMaker/JuiceMaker/View/AlertHandler.swift
> +        return currentVC!
헉 사소한 부분 잡아주셔서 감사합니다 :)

2023-12-12 09:20 UTC, suojae3 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    Notification.Name("fruitStockDidChange")
notification 학습 중에 줄바꿈을 미처 못본 것 같습니다! 불필요한 줄바꿈이라 생각되어서 수정했습니다! 감사합니다 :)

2023-12-12 09:27 UTC, suojae3 commented on JuiceMaker/JuiceMaker/View/AlertHandler.swift
> +    func getCurrentVC(head: UIViewController? = UIApplication.shared.keyWindow?.rootViewController) -> UIViewController {
currentVC에 head를 넣어주는 방식으로 적어 "링크드리스트 방식으로 싱글톤으로 선언된 UIApplication부터 시작해 연결되어있는 UIViewController에 while문을 nil값이 나올 때까지 돌려준다" 를 학습하면서 좀 더 명확하게 보이게 적어주었습니다. 불필요한 코드이기에 커밋할 때 지웠어야 했는데 미처 신경을 못썼던 것 같습니다. 감사합니다 😊

2023-12-12 09:28 UTC, suojae3 commented on JuiceMaker/JuiceMaker/View/AlertHandler.swift
> +    func getAlertMessage(alertType: AlertType) -> (String,String) {
공백추가하는게 훨씬 읽기가 좋은 것 같습니다 :)
사소한 팁들 너무 감사합니다 ☺️

2023-12-12 09:31 UTC, suojae3 commented on JuiceMaker/JuiceMaker/Model/Reception.swift
> +            return juiceMaker.fruitStore.fruitsStock[.pineapple] ?? 0
디미터 법칙, 기차충돌.. 이런건 정말.. 너무 좋은 지식인 것 같습니다. 

코드 수정하면서 최대한 디미터법칙을 지켜보려 노력했지만 초기값 셋팅에 있어서 결국 reception에서 초기재고를 가져와 넣게 되었습니다....🥹

2023-12-12 13:25 UTC, keeplo commented on JuiceMaker/JuiceMaker/Controller/JuiceMachineViewController.swift
> +        setupNotificationCenter()
`뷰컨트롤러가 만들어질때`라는 표현은 인스턴스가 생성되는 시점인가요? 
viewDidLoad 의 시점이 어떤 시점인지 좀 더 명확한 이해가 필요할 것 같아요!

2023-12-13 06:38 UTC, suojae3 commented on JuiceMaker/JuiceMaker/Controller/JuiceMachineViewController.swift
> +        setupNotificationCenter()
감사합니다 말꼬! 무심코 지나쳤던 viewDIdLoad에 대해 한 번 더 찾아보게 되었습니다

ViewDidLoad의 정확한 의미는 뷰의 컨트롤러가 **메모리에 로드**되고 난 후에 호출되는 생명주기 함수입니다!

2023-12-13 08:37 UTC, suojae3 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +final class FruitStore {
기존의 클래스에서는 다이나믹 디스패치 방식으로 동작합니다. 다이나믹 디스패치란 프로그램이 메모리에서 특정 메서드 호출에 대한 실행 코드를 찾을 수 있는 위치를 CPU에 알리는 프로세스입니다. 다이나믹 디스패치는 힙메모리에 데이터를 저장하고 사용함으로써 메모리를 좀더 길게가져가고 런타임에서 동작합니다. 스태틱 디스패치는 스택메모리를 사용하여 메모리가 바로 팝되기 때문에 서브클래싱이 불가능하지만 컴파일 타임에 인라이닝 형식으로 코드가 동작하며 성능상 더 빠른 구현이 가능합니다.

final키워드는 클래스의 다이나믹 디스패치를 스태틱 디스패치로 바꾸어주어 상속을 포기하는 대신 인라이닝이라는 성능상의 이점을 얻을 수 있습니다!

2023-12-13 11:47 UTC, keeplo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +final class FruitStore {
깊은 내용까지 학습이 완벽하군요! 답변 감사합니다!

2023-12-13 12:15 UTC, keeplo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        guard let currentStock = fruitsStock[fruit], currentStock-count>0 else { print("\(#function) 재고 부족!"); return }
세제가 말씀해주신 

에러처리 -> 디버깅
사용자에게 노티 -> 얼럿 등장

이런 형태로 구현되는 경우도 분명 많고 자연스럽지만
에러처리를 다양한 방향으로 고민해보면 좋을것 같아요!

`에러 == 사용자가 알 정도에 문제발생`  이 아닐 수 도 있을 것 같아요!
오늘 다뤄보신 TDD 개념도 출발점은 Test 의 방식일 뿐입니다.
테스트는 코딩과 밀접한 영역인데 에러처리는 Test와 정말 필수적인 관계일 것 같아요!

저는 제 주관일 수 있지만 한 문장을 인셉션 하고 싶은 점은
`에러는 동작이 어떠한 이유로 완료하지 못함을 알리는 수단` 입니다!

`do-try-catch` 를 다시 돌아볼때
`시도하고 -> 에러를 캐치해서 -> 사용자에게 알림` 에서
`시도하고 -> 에러를 캐치해서 -> 이유(에러)에 따라 처리` 가 제가 생각하는 에러처리 입니다!

제 생각이 뭔가 답은 아니고 저는 약간 다른 생각을 길게는 다양한 방향을 고려하셨으면 하는 부분에서
제가 이해하고 사용하는 방식에 에러처리를 말씀드렸는데 고민해보면 좋을것 같아요!

제가 처음 드린 질문에서 방향은 메서드의 성공실패를 Bool 타입이라거나 Result 타입이라거나
옵셔널 반환 등의 다양한 방법을 이용해서 메서드의 성공과 실패를 호출부와 소통하기를 기대했습니다!

꼭 에러타입이 아니어도 괜찮을 것 같아요!

2023-12-14 04:20 UTC, suojae3 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        guard let currentStock = fruitsStock[fruit], currentStock-count>0 else { print("\(#function) 재고 부족!"); return }
enum으로 에러타입을 분류한 뒤 개발자에게 어디서 문제가 생겼는지 알려주기 위해 switch문을 통해 프린트 메서드를 호출하고 연관값을 활용하여 커스텀 메세지를 통해 에러 메세지에 자율성을 주었습니다!

2023-12-14 09:09 UTC, keeplo commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        fruitStore.decrementFruit(of: .banana, by: 2)
중요한 사항은 아닌데 추가적인 예시를 보여드리면
 
```swift
fruitStore.decrement(fruit: .banana, by: 2)`
```
이유는 타동사 + 목적어 형태가 인수명으로 이어지기 때문에
이런 형태도 좋을것 같아요

2023-12-14 09:10 UTC, merged