쥬스자판기 [Step2] 미르, 미성
tasty-code/ios-juice-maker pull request #82
Opened 2023-12-07 06:35 UTC by crisine

# 👋 안녕하세요 @FirstDo (dudu) !
@Mireu930 @crisine (misung) 인사드립니다 😄 
이번 `STEP 2` PR Review도 잘 부탁드리겠습니다!

## 🤔고민이 되었던 점

### 1.이동방식에 대한 고민
- 화면이동방식을 어떻게 활용할까에 대한 고민을 했는데, 네비게이션과 모달리티 활용중 어떤 방식이 적절한지에 대한 고민을 했었습니다. 먼저 두방식에 대한 특징을 한번 찾아봤습니다. 각각의 이동방식에 장단점이 있어 어느방식을 콕 짚어서 선택하지 못했지    만, 뷰에 이미 네비게이션 컨트롤러를 설정하고 있어 네비게이션을 통한 이동방식을 코드로 구현했습니다.

| 모달리티  | 네비게이션 |
| :--------: | :--------: |
|1️⃣모달은 일시적으로 집중을 요하는 컨텐츠 표시할떄 사용 <br> 2️⃣사용자에게 모달로 띄운 화면이 중요하고, 필요한 경우 액션이 요구됨 <br> 3️⃣화면 나가기 위한 명백한 행동이 요구됨. | 1️⃣보통 사용자들은 앱의 기능을 탐색할떄, 타고타고 들어가다가 빠져나올떄 당황하거나 어려움을 겪음 <br> 2️⃣이떄 네비게이션은 사용자가 당황하지 않게끔, 자연스럽게 지나왔던 곳을 돌아오게끔 도와주는 것 | 

```swift
guard let viewController = self.storyboard?.instantiateViewController(identifier: "viewController") as? ManageStockViewController else { return }
        self.navigationController?.pushViewController(viewController, animated: true)
```

### 2. 주문 버튼을 통한 쥬스 주문 방식에 대한 고려
- 쥬스 주문 시 어떤 방식으로 `JuiceMaker` 객체에게 주문을 시킬 것인가의 방법에 대해 고민했습니다. 저희가 택한 방법은 다음과 같습니다.
1. 쥬스 주문 버튼에서 `" "` (space) 를 기준으로 잘라서, `0번 요소` (쥬스 이름) 을 떼옵니다.
```swift
guard let juiceName = sender.titleLabel?.text?.components(separatedBy: " ")[0] else { return }
```
2. 그리고 그것을 기반으로 쥬스 레시피에 해당 쥬스가 있는지 확인하고, 쥬스 `enum` 을 받아옵니다.
```swift
guard let juice = juiceMaker.checkJuiceRecipe(juiceName: juiceName) else { return }
```
3. 최종적으로 쥬스가 존재하는 경우, `juiceMaker` 에게 쥬스를 주문합니다.
```swift
juiceMaker.orderJuice(juice: juice)
```
### 3. 복합적인 재료가 소모되는 쥬스 주문 시, 일부 재료의 재고 부족 시 처리 방안
- 쥬스를 주문하는 과정에서 딸바/망키쥬스의 경우 복합적인 재료가 소모되는데, 초기 로직에서는 다음과 같은 상황에서 문제가 발생하였습니다. 그리고 로직의 진행 순서를 변경하여 이를 해결할 수 있었습니다.

> 초기 로직 : 딸기 재고 체크 -> 딸기 재고 없음 -> 바나나 재고 체크 -> 바나나 재고 소모 -> 모든 재료 정상 소모했는지? -> **에러 반환**
```swift
func orderJuice(juice: Juice) throws {        
    // 선행적으로 재료들의 수량을 체크하지 않아, 쥬스재료의 일부 재고가 부족함에도 충분한 재고쪽은 소모가 발생
    for (fruitName, quantity) in juice.recipe {
        try fruitStore.consumeFruit(fruit: fruitName, num: quantity)
    }
}
```
> 예시 상황 : 딸기 재고가 0개, 바나나가 9개 있을 때 딸바쥬스 주문 (딸기 10개, 바나나 1개 소모) -> 
딸기 재고가 없음에도 불구하고 바나나를 1개 소모해버림 
---
> 변경 로직 : 레시피 내 모든 재료 **재고 선행 체크** -> 실패 시 **에러 반환**, 성공 시 -> 재료 소모 -> 정상 종료
```swift
private func checkJuiceIngredients(juice: Juice) throws {
    for (fruitName, quantity) in juice.recipe {
        try fruitStore.checkStock(fruit: fruitName, num: quantity)
    }
}

func orderJuice(juice: Juice) throws {
    try checkJuiceIngredients(juice: juice) // 재고 선행 체크
    // 나머지 진행
}
```
> 예시 상황 : 위와 같은 시나리오일때, 딸바쥬스 주문 시 -> 딸기 재고 부족 -> 에러 반환 -> **Alert 띄움**

## 🙏조언을 구하고 싶은 점 

- 화면데이터공유를 받는 방식에 저희는 다른 객체들과 공유가 쉬워서 싱글톤패턴으로 구현을 해서 화면 사이에 재고를 주고받을수 있도록 구현을 해줬는데, 또다른 방식으로는 델리게이션패턴이 있는 것으로 알고 있습니다. 두두라면 어떤방식이 적절하다고 생각하는지와 그 이유에 대해 조언을 얻고 싶습니다.

2023-12-07 23:18 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +    }
MainVC에서 하지말고, Alert을 관리하는 객체가 하나 있으면 MainVC를 좀 더 가볍게 만들 수 있겠네요.

또한 어차피 기본얼럿이라면

`showOutOfStockAlert`
`showSuccessAlert`

이런식으로 두개 나누기보단
title, message, action등을 받아서 일반적인 alert를 생성하는 매서드를 만드는게 좋을것 같습니다

2023-12-07 23:21 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +        self.navigationController?.pushViewController(viewController, animated: true)
`self.` 를 전부다 쓰던지, 전부다 쓰지 말던지 
아니면 어떤상황에서만 쓸껀지 컨벤션을 맞추는게 필요해 보입니다.

또한 identifier와 VC이름은 동일하게 가져가는게 좋습니다. 나중에 VC가 많아지면 힘들어져요
```swift
self.storyboard?.instantiateViewController(identifier: "viewController") as? ManageStockViewController else { return }
```

추가로 이런식으로 identifier를 문자열로 사용하면, 오타의 가능성이 크고 컴파일 타임에 검증도 불가능합니다.
더 좋은 방법이 있을것 같아요

2023-12-07 23:22 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +    private func checkFruitsStock() {
label에 과일재고를 업데이트 해주는 친구인데, 이름이 약간 안맞는것 같네요

2023-12-07 23:23 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +    private func orderJuice(juice: Juice) {
매서드를 호출할때 아래와 같이 쓸텐데, Juice를 중복해서 쓸 필요가 없어보여요!
```swift
orderJuice(juice:)-> order(juice:)
```

2023-12-07 23:24 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +    @IBOutlet weak var mangoLabel: UILabel!
이친구들은 왜 weak이 붙었는지 (없으면 무슨일이 일어나는지), 생각해보면 좋을것 같습니다.
또 !로 선언되어 있는데, 어떤경우에 crash가 발생하는지도요!
또 왜 var로 선언되어야 하는지도 한번 찾아보시면 도움이 될것 같네요 :)

2023-12-07 23:25 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +    private let juiceMaker: JuiceMaker = JuiceMaker()
타입명시도 통일성을 맞춰주는게 좋습니다.
저는 보통 헷갈리는 경우가 아니면 생략하는 편이에요

2023-12-07 23:27 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +class MainViewController: UIViewController {
상속가능성이 없는 친구에게는 final 키워드를 붙이는게 좋습니다. 이유가 뭘까요??

또한 VC 이름도 MainVC보단 좀 더 역할에 맞는 이름이 어울릴것 같아요!

2023-12-07 23:28 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +    @IBAction private func manageStockButton(_ sender: UIButton) {
버튼 액션에는 didTap ~, tap~등의 접두사 or 접미사를 붙여서 확실히 구분해주는것도 좋아요

2023-12-07 23:30 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +    }
제가 봤던 방식중에 가장 깔끔한것 같습니다 :)
고민을 많이 하신게 느껴지네요! 누구아이디어인가요?

다만 checkJuiceRecipe라는 매서드를 굳이 만들필요없이 Juice 열거형을 만들 수 있는지 없는지 여부로 판단하는것도 좋지 않을까요?
`guard let Juice(rawvalue: juiceName)`

수정사항은 아닙니다! 구현의 차이니까요

2023-12-07 23:32 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +        guard let juice = juiceMaker.checkJuiceRecipe(juiceName: juiceName) else { return }
또 제가 느낀게 있는데, 저렇게 else 하고 아무동작도 안해버리면 나중에 디버깅이 굉장히 힘들더라고요
에러처리는 alert을 띄우거나 최소한 로그라도 남겨주는게 편할것 같아요!

2023-12-07 23:33 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +        present(alert, animated: true, completion: nil)
저는 기본값이 nil인 친구는 굳이 안쓰는 편입니다 (수정사항 아님!)

```swift
present(alert, animated: true, completion: nil)
->
present(alert, animated: true)
```

2023-12-07 23:36 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    static let shared = FruitStore()
싱글톤 패턴을 사용할땐 shared를 제외하곤 인스턴스를 만들 수 없게 하는게 좋습니다
`private init() { }` 으로 막아주세요

2023-12-07 23:41 UTC, FirstDo requested changes
고생하셨어요! 코맨트 확인 부탁드려요

2023-12-08 07:28 UTC, crisine commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +    }
[해당 커밋](https://github.com/tasty-code/ios-juice-maker/pull/82/commits/5a5928d320964ce87abb8f367a43ddb45761b4d5) 에서 다음과 같은 방향으로 수정하였습니다!

# `enum` AlertType 정의
```swift
enum AlertType {
    case defaultAlert
    case outOfStockAlert
}
```
- `Alert` 구조체에 넘겨주기 위한 `AlertType` 열거형을 정의하였습니다.

# `struct` Alert 정의
```swift
import UIKit

struct Alert {
    
    static func createAlertController(alertType: AlertType, title: String?, message: String, view: UIViewController) -> UIAlertController {
        let alertController = UIAlertController(title: title, message: message, preferredStyle: .alert)
        
        switch alertType {
        case .defaultAlert:
            let okAction = UIAlertAction(title: "확인", style: .default)
            alertController.addAction(okAction)
        case .outOfStockAlert:
            let okAction = UIAlertAction(title: "예", style: .default) { _ in view.moveToManageStockView() }
            let cancelAction = UIAlertAction(title: "아니오", style: .default)
            alertController.addAction(okAction)
            alertController.addAction(cancelAction)
        }
        
        return alertController
    }
}
```

- 매개로 `AlertType` 을 받아 내부의 `switch` 문에서 어떠한 `AlertAction` 들을 `AlertController` 에 추가해줄지 분기를 나눕니다. 그리고 최종적으로 `AlertController` 를 반환하도록 하였습니다.

- `UIViewController` 에서 `moveToManageStockView()` 를 호출할 수 있게 `UIViewController` 를 확장했습니다.

```swift
extension UIViewController {
    func moveToManageStockView() {
        guard let viewController = self.storyboard?.instantiateViewController(identifier: "viewController") as? ManageStockViewController else { return }
        self.navigationController?.pushViewController(viewController, animated: true)
    }
}
```

## 문제점
- 현재 구조상 `UIViewController` 를 확장해서 특정 `View` 로 넘어가도록 하고 있어서, `View` 를 유동적으로 입력받아 추후 화면 추가에 대비한 확장성있는 구조를 채택하고자 하였으나, 다른 부분의 수정 등 (화면 타입 생성, identifier 생성) 이 필요할 것 같아 현재의 방식에 머무르게 되었습니다.

2023-12-11 04:18 UTC, mireu930 commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +        self.navigationController?.pushViewController(viewController, animated: true)
self를 쓰지않는 방식으로 통일하였지만, 
```swift
self.navigationController?.pushViewController(viewController, animated: true)
```
해당 부분에서는 현재 사용 중인 화면에 View를 Push() 해야 하는데, 현재 화면을 지칭할 수 있는 방법을 .self 외에는 다른 방법으로 지정할 수 있는 방법이 있는지 마땅치 않아 불가피하게 .self 키워드를 해당 부분에서는 유지하도록 하였습니다.

2023-12-11 04:23 UTC, mireu930 commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +    private func checkFruitsStock() {
[지난 커밋](https://github.com/tasty-code/ios-juice-maker/pull/82/commits/9a819103a583f38566f2403413b00c8a44b3acc0)에서 `updateFruitStockLabel`라고 수정을 해줬습니다.

2023-12-11 04:25 UTC, mireu930 commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +    private let juiceMaker: JuiceMaker = JuiceMaker()
타입명시보다 타입추론으로 컨벤션을 맞췄습니다.

2023-12-11 04:26 UTC, mireu930 commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +class MainViewController: UIViewController {
[해당커밋](https://github.com/tasty-code/ios-juice-maker/pull/82/commits/9a819103a583f38566f2403413b00c8a44b3acc0)에서 `JuiceOrderViewController`로 수정해줬습니다.

2023-12-11 04:28 UTC, mireu930 commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +    @IBAction private func manageStockButton(_ sender: UIButton) {
[해당커밋](https://github.com/tasty-code/ios-juice-maker/pull/82/commits/9a819103a583f38566f2403413b00c8a44b3acc0)에서 접미사에 -Tapped라고 수정해줬습니다.

2023-12-11 04:29 UTC, mireu930 commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +        guard let juice = juiceMaker.checkJuiceRecipe(juiceName: juiceName) else { return }
[해당커밋](https://github.com/tasty-code/ios-juice-maker/pull/82/commits/44d9561c4363956f85e5d053a00ca04fa6a15650)에서 에러처리를 alert창으로 띄우게 수정해줬습니다.

2023-12-11 04:33 UTC, mireu930 commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +        present(alert, animated: true, completion: nil)
[해당커밋](https://github.com/tasty-code/ios-juice-maker/pull/82/commits/5a5928d320964ce87abb8f367a43ddb45761b4d5)에서 수정해줬습니다!

2023-12-11 04:35 UTC, mireu930 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    static let shared = FruitStore()
FruitStore파일에 해당부분은 생정자에 private을 써줬는데 추가적으로 구현을 해줘야하는 의미인지, 아님 수정을 해야한다는 의미일까요?
```swift
private init(fruitStock: [Fruit : UInt] = [.banana: 10, .kiwi: 10, .mango: 10, .pineapple: 10, .strawberry: 10]) {
        self.fruitStock = fruitStock
    }
```

2023-12-11 05:56 UTC, crisine commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +    }
안녕하세요 @FirstDo (DuDu)! 버튼에는 `쥬스이름 Label` 이 존재하니 그것을 활용해보면 어떨까 싶어서 나온 제 아이디어였습니다 😄 버튼에서 쥬스 이름을 떼오는 로직에 대한 조언도 @mireu930 로부터 받았습니다!

조언해주신 부분에 대해서는 다음과 같이 확인하였습니다!

```swift
enum Juice: String {
    case strawberryJuice = "딸기쥬스"
    case melonJuice = "멜론쥬스"
}

foo()

func foo() {
    let juiceName = "딸기쥬스"
    guard let juice = Juice(rawValue: juiceName) else { return }    
    print(juice.rawValue)
}
```

이러한 형식의 구조로 변경하는 경우 `guard let` 바인딩을 사용하여 `Juice` 열거형을 생성할 수 있다는 방법을 확인하였습니다!
제안해주신 구조로 개선하는 경우 `checkJuiceOrder()` 메서드를 정의할 필요 없이 `order()` 메서드에서 한번에 일을 처리할 수 있는 것을 확인하였습니다! 👍 

현재로서는 `checkJuiceOrder()` 에서 버튼의 Label을 얻어오는 과정에서 혹여 유효하지 않은 이름이 들어오는지 확인하고 Alert를 띄워 주는 과정과, `juice` 열거형을 생성하지 못 했을 때의 Alert 를 띄워주는 역할이 추가되어 `order()` 쪽으로 합치게 되면 메서드가 그렇게 커지지는 않지만 나름의 가독성의 편의 😅 를 위해 현행 상태와 같이 분리하여 두는 것으로 결정하였습니다!

2023-12-11 07:10 UTC, mireu930 commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +    @IBOutlet weak var mangoLabel: UILabel!
`UIViewConroller`의 구성을 살펴보면 실제로 최상위 `View`가 강한 참조로 구성되어 있는 것을 확인할 수 있습니다.
일반적으로 `MainView`는 객체들의 기본 소유자이기 때문에 하위 `View`에 대해서 강한 참조가 필요하지 않으며,
weak를 사용하여 강한참조를 통해 발생하는 메모리누수 현상을 방지할수 있습니다.

2023-12-11 07:45 UTC, crisine commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +    @IBOutlet weak var mangoLabel: UILabel!
# `@IBOutlet` 이란?
> 또 !로 선언되어 있는데, 어떤경우에 crash가 발생하는지도요!
---
> An outlet is a property that is annotated with the symbol IBOutlet and whose value you can set graphically in a nib file or a storyboard.
> 
> 아웃렛은 IBOutlet 기호로 주석이 달린 프로퍼티로, nib 파일이나 스토리보드에서 시각적인 값을 설정할 수 있습니다.

- `IBOutlet`은 StoryBoard 상의 View 객체와 Interface Builder 를 연결합니다.
- `IBOutlet` 으로 연결한 View 객체가 `nil` 로 존재하지 않는 경우에는 문제가 발생하였을 가능성이 높다고 생각합니다.
- 만약 `!` 강제 언래핑이 붙어 있는 상황에서 Storyboard 상의 View 객체가 `nil` 이라면, 바로 에러가 발생하거나 앱의 crash가 발생한다고 생각됩니다.

그렇다면, `!` 강제 언래핑을 하는 것은 StoryBoard 상에 `@IBOutlet` 으로 연결된 View 객체가 반드시 존재할 테니 강제 언래핑을 해도 괜찮다는 결론을 내볼 수 있을 것 같습니다.
## 어떤 경우에 Crash 가 발생할까요?
제가 예상한 시나리오상에서는 코드쪽에서는 `@IBOutlet` 으로 연결된 View 객체가 존재하지만, 모종의 이유로 StoryBoard 상에 연결된 해당 View 객체가 존재하지 않는 경우에 에러가 발생할 수 있다고 생각했습니다.

저희 프로젝트에서 강제로 Crash를 발생시키기 위해서는 다음과 같은 절차를 따라 이러한 결과를 얻었습니다.

1. 파인애플 수량을 나타내는 `pineappleLabel` 에 연결된 메인 뷰의 `StoryBoard` 에서 해당 `label` 을 강제로 삭제
2. 그 후 코드를 실행하니, 초기 과일들의 수량을 할당해주는 해당 부분에서 다음과 같은 에러가 발생
```swift
private func updateFruitStockLabel() {
        let stock = fruitStore.fruitStock.compactMapValues { String($0) }
        
        strawberryLabel.text = stock[.strawberry]
        bananaLabel.text = stock[.banana]
        pineappleLabel.text = stock[.pineapple] // 여기서 Error!
        kiwiLabel.text = stock[.kiwi]
        mangoLabel.text = stock[.mango]
```

```
Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value
```

현재 프로젝트 수준 상에서는 실수로 저희가 연결해 준 View 객체를 삭제한 경우에 강제 언래핑하는 과정에서 해당 View가 존재하지 않아 에러가 발생하는 경우를 문제가 발생하는 예로 들 수 있었습니다.

# `var` 로 선언되어야 하는 이유
> 또 왜 var로 선언되어야 하는지도 한번 찾아보시면 도움이 될것 같네요 :)
---
1. `@IBOutlet` 어노테이션이 붙으면 반드시 `mutable` 해야 하므로
2. 런타임 시에 변경이 될 수도 있어야 하므로

`@IBOutlet` 어노테이션이 붙은 프로퍼티가 메모리에 먼저 생성이 된 후, StoryBoard 에 있는 View 정보를 기반으로 만들어진 인스턴스를 나중에 `@IBOutlet` 에 할당하려면  `let` (상수) 의 상태에서는 할당이 불가능하니 `var` 변수여야된다고 생각합니다.

2023-12-11 11:59 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    static let shared = FruitStore()
제가 잘못봤네요!
코맨트 무시해 주세요 :)

2023-12-11 12:09 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +    @IBOutlet weak var mangoLabel: UILabel!
실제로 스토리보드를 쓰다보면, 
계속 개발하고 수정하는 과정에서 storyboard의 객체가 사라져서 runtime에 crash가 발생하는 경우도 빈번합니다

### var로 선언되어야 하는 이유
let으로 선언된 객체의 모든 프로퍼티는 이니셜라이저 시점에 초기화 되어야 합니다.
그러나 MainVC는 어떤 이니셜라이저로 초기화 할까요?

```
required init?(coder: NSCoder) { }
```

스토리보드 기반으로 VC를 만들면 위의 이니셜라이저가 호출됩니다.
그리고 Storyboard파일을 기반으로 VC를 초기화 합니다.
그리고 outlet들은 그 다음에 값이 할당되게 됩니다.

이니셜라이저 시점에 초기화를 해줄 수 없으므로 var + !로 선언하는것입니다..!

### Weak으로 선언되어있는 이유

우선 VC의 최상위 뷰와는 무관합니다.
모든 class 타입은 reference counting(이하 RC)를 활용해서 객체의 생명주기를 관리하는데요.
rc = 0 이면 해당 객체를 메모리에서 해제하게 됩니다.

스토리보드를 활용하는경우, 스토리보드에 뷰를 올릴때 rc+1, 그리고 (weak으로 선언하지 않았다면) VC 클래스에 IBOutlet을 선언할때 또 rc+1이 됩니다.
그래서 rc=2가 되서 비정상적인 상태가 됩니다.\
그래서 클래스에 IBOutlet을 선언할때는 기본적으로 weak으로 선언되는것입니다

2023-12-11 12:15 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +    }
`AlertType` 이 있을 필요가 없다고 생각해요

title, message, 그에따른 buttonAction만 있다면 모든 경우의 systemAlert을 다 만들 수 있지 않을까요?
다음스텝에서 수정해 보는게 좋을것 같아요

예를들어 아래처럼 쓸 수가 있겠네요
```swift
func alert(title: String? = nil, message: String = nil, okTitle: String, okAction: @escaping () -> Void) {
  let vc = UIAlertController(title: title, message: message, preferredStyle: .alert)
  let okAction = UIAlertAction(title: okTitle, style: .default) { _ in okAction() }
  vc.addAction(okAction) 
}
```

vc 자체를 넘겨받는 방식은 일반적으로 좋다고 보기는 조금 어려울것 같아요

2023-12-11 12:17 UTC, FirstDo approved these changes

2023-12-11 14:43 UTC, merged

2023-12-12 00:54 UTC, crisine commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +    }
화면을 이동할 때 사용하는 Alert의 경우 `okAction` 뿐만 아니라 `deny` (아니오) 에 해당하는 버튼 또한 생성이 필요하여 초기에는 `AlertController` 만 만들어 반환받고 Action의 추가가 필요한 경우 반환받은 컨트롤러를 토대로 Action을 붙이는 등의 방법을 고려했었습니다.

다음 STEP 에서 현재 제안해주신 구조에 맞게 변경해보도록 하겠습니다! 😄