쥬스메이커 [STEP1] 이안,유니
tasty-code/ios-juice-maker pull request #83
Opened 2023-12-07 06:50 UTC by ianK0909

@ryan-son 

안녕하세요  이안,유니 입니다
쥬스만들기 STEP1 작업완료 후 PR 올립니다.

<h3>PR Point</h3>

enum 사용

- 쥬스,과일에 대한 네임스페이를 한곳에 모아서 관리합니다.

싱글톤 

- 앱 전역에서 같은 인스턴스에 접근할수있으며, 과일 재고 관리를 쉽게하기 위해서 사용했습니다.

class 앞에 final 을 사용한 이유  

- 상속을 하지않는 클래스이며, 컴파일러가 static하게 dispatch 할 수 있습니다

<h3>진행사항 중 궁금한점</h3>

재고관리를 싱글톤을 사용해서 관리를 하고있습니다. 싱글톤을 사용하면 의존성이 강해진다고 하는데 계속 사용해도 괜찮을까요??

addFruitInventory, usedFruitInventory 함수를 분리를 하여 구현을 했는데 매개변수 inventory를 -정수값을 주면 하나의 함수로도 두가지 기능을 할수있는데요 이렇게 나누는게 좋을까요? 하나로만 사용하는게 좋을까요?

2023-12-07 15:07 UTC, ryan-son requested changes
반갑습니다. 이안, 유니!

Step 1 요구사항을 충실히 잘 만족시킨 것으로 보입니다. 구현에 근거 없는 유연성을 부여하는 것은 실무에서 필요치 않을 수 있지만 학습하는 입장에서는 요구사항을 만족시키면서 발생할 수 있는 상황에 대해 유연하게 대응할 수 있는 방법을 공부해보는 것도 좋다고 생각합니다. 본문에서는 여러분의 질문에 대해 간략하게 답변 남기고, 코멘트에 생각해볼 부분들을 남겨두도록 하겠습니다.

><h3>진행사항 중 궁금한점</h3>

>재고관리를 싱글톤을 사용해서 관리를 하고있습니다. 싱글톤을 사용하면 의존성이 강해진다고 하는데 계속 사용해도 괜찮을까요??

타입을 인식할 수 있는 범위라면 어디든지(여기에서는 프로젝트 전역) 접근할 수 있다는 편리성이라는 분명한 장점이 있지만, 요구사항 변경에 유연하게 대응할 수 있는 형태는 아니라고 생각합니다. 관리해야할 과일저장소가 추가된다는 요구사항만 생겨도 적용된 모든 코드가 변경되어야 할거예요. 다른 방식을 고려해보시는 것을 권장합니다. 싱글톤은 해당 타입을 인식할 수 있는 범위에 단 하나의 인스턴스만을 유지하는 것이 정당할 때 사용할 수 있는 선택지이며 이 또한 가능하다면 적용하지 않는 것을 권장합니다.

> addFruitInventory, usedFruitInventory 함수를 분리를 하여 구현을 했는데 매개변수 inventory를 -정수값을 주면 하나의 함수로도 두가지 기능을 할수있는데요 이렇게 나누는게 좋을까요? 하나로만 사용하는게 좋을까요?

재고를 추가하는 것과 사용하는 것은 예외 처리 측면에서 구현이 달라져야할 부분이 분명히 존재합니다. 구현의 양을 줄이기 위해 기능을 합치기보다 용도에 따라 분리해두는 것이 기능 확장에 더 도움이 될 것이라고 판단됩니다.

고생 많으셨습니다. 본문과 코멘트 내용을 읽어보시고 궁금하신 점이 있으시면 언제든지 물어봐주세요. 너무 오랜 고민을 하시지 않도록 가능하신 시간에 회의실에서 만나서 이야기 나누면 더 좋겠네요. DM 드리겠습니다.

2023-12-08 02:44 UTC, Jin0Yun commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
1. 현재 상황에는 사용하고 있지 않아서 private를 붙여놓았습니다! 
2,3 도 수정하였습니다 😄👍🏻

2023-12-08 02:49 UTC, Jin0Yun commented on .DS_Store
.DS_Store 파일은 맥 OS X 시스템이 finder로 폴더에 접근할 때 자동으로 생기는 파일로 알고있습니다.
해당 파일이 재업로드 되는걸 방지하기 위해서 gitignore에 추가하였습니다.

2023-12-08 06:24 UTC, Jin0Yun commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
>  struct JuiceMaker {
1. JuiceMaker 안에는 주스를 만들기 위한 기능만 담당하게 하기 위해서 값 타입인 구조체로 정의하게 되었습니다.
2. FruitStore 안에서 재고를 관리하고 상태를 변경하는 메서드들을 포함하고 있게 하고 싱글톤 구현을 위해 참조 타입인 클래스로 정의하게 되었습니다.

2023-12-08 06:28 UTC, Jin0Yun commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    }
1,2. 메서드 이름 중복과   juice.recipe 수정하였습니다.

2023-12-08 06:43 UTC, Jin0Yun commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    ]
2. 다른 방법으로는 배열을 사용하는 방법이 있을거같은데 배열의 인덱스값이 어떤 과일을 나타내는지 명확하게 표현되지 않기때문에 키-값 형태로 저장되어 각 재료에 대한 정보를 더 명확하게 표현해줄 수 있는 딕셔너리를 사용하게 되었습니다.

2023-12-12 06:50 UTC, ianK0909 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
>  struct JuiceMaker {
FruitStore를 클래스로 사용하는 이유는 과일의 재고를 하나의 객체에 관리하기 위해서 참조타입인 클래스로 선언해 다른곳에서 접근하더라도 동일한 객체의 값을 변경하기 위해 클래스로 정의했습니다. 

구조체 사용을 애플가이드라인에서 권장하고, 상속이나,참조가 필요한경우가 아닌거 같아서 구조체를 사용했습니다. 필요한 경우에는 구조체를 클래스로 변경하여 사용하겠습니다.

2023-12-12 07:04 UTC, ianK0909 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
```swift
  @discardableResult func consume(fruit: Fruit, amount: Int) throws -> Int {
        try canConsume(fruit: fruit, amount: amount)
        
        guard amount >= 0 else {
            throw JuiceMakerError.negativeAmount
        }
        fruitInventory[fruit, default: 0] -= amount
        return fruitInventory[fruit, default: 0]
    }

    private func canConsume(fruit: Fruit, amount: Int) throws {
            let currentInventory = inventory(fruit: fruit)
            
            if currentInventory < amount {
                throw JuiceMakerError.outOfStock
            }
```

수정하였습니다.

2023-12-12 16:23 UTC, ryan-son approved these changes
여러분, 고생 많으셨습니다! 금요일 회의실에서 말씀드린 부분이 거의 반영되어있네요. 추가로 코멘트 달아둔 부분 중에서 필요하다고 판단되는 것이 있으시면 적용해보시면 좋을 것 같습니다. 그럼 Step 2에서 뵙겠습니다.

2023-12-12 16:23 UTC, ryan-son commented on .gitignore
> +.DS_Store
👍

2023-12-12 16:23 UTC, ryan-son commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    ]
`FruitStore`가 싱글톤으로 구성된 점과 초깃값이 인스턴스 프로퍼티에 직접 설정되어 있는 점을 추가적으로 수정해볼 수 있을 것 같습니다.

2023-12-12 16:23 UTC, ryan-son commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
훨씬 읽기 편한 형태가 되었네요!

2023-12-12 16:23 UTC, ryan-son commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +            }
들여쓰기 수준도 맞춰주시면 좋을 것 같습니다~!

2023-12-12 16:23 UTC, ryan-son commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +}
열거형으로 구성한 Fruit과 Juice보다 유연하게 처리하셨네요. 멋집니다!

2023-12-12 16:23 UTC, ryan-son commented on JuiceMaker/JuiceMaker/Model/JuiceMakeError.swift
> +}
에러도 구성해보셨군요! 👍 LocalizedError 프로토콜도 이용해보셨으니 프로토콜에서 제공하는 에러 메시지 인터페이스를 정의해서 사용할 수 있도록 만들어 보는 것도 좋을 것 같습니다.

2023-12-12 16:23 UTC, merged