쥬스 자판기 [STEP 1] Matthew, 희동
tasty-code/ios-juice-maker pull request #85
Opened 2023-12-07 10:30 UTC by kimbs5899

@July911
안녕하세요! Matthew, 희동입니다! 😊
STEP 1 PR 올립니다 !!!!

## **STEP 1의 기능을 구현했습니다.**

쥬스 메이커의 메인 화면 기능 구현
과일타입, 쥬스타입 생성
과일스토어, 쥬스메이커 기능 구현

### 데이터 저장 방식 - Singleton

싱글톤 패턴을 사용한 이유는 기본적인 과일 데이터를 관리하고 사용하기 위해 사용했습니다.
이후 코어데이터를 적용중인데 테스트 과정에서 오류가 많아져서 적용이 늦어져 다음 Step에는 꼭 적용해보도록 하겠습니다.

### 에러 처리는 구현하지 않았습니다.

코어데이터 적용을 테스트하며 try do catch를 통해 Error를 관리할때 적용할 예정입니다.

Error의 경우 열거형으로 에러 케이스를 지정해 관리할 예정입니다.
현재는 에러가 많지 않아 적용하지 않고 이후 코어데이터 적용시 구현 예정입니다.

### 과일 제조 성공여부 관련 alert 표시로 처리했습니다.

이후 Step2에서는 버튼을 추가하여 재고 수정을 원할시 바로 해당 화면으로 이동하도록 구현 예정입니다. 

쥬스 제작

FruitStore 클래스 내부에 저장한 FruitData 타입의 배열을 만들어 그 데이터를 수정하는 매서드를 구현하는 방식으로 작성했습니다. 내부 매서드의 경우 과일 재고 추가, 과일 재고 삭제, 과일 재고 보기, 과일 재고 확인, 과일 재고 사용 으로 나눠 반복되는 코드를 줄이도록 노력했습니다.

JuiceMaker 구조체의 경우 내부에서 쥬스 제작과 쥬스 재고 보기를 나눠 매서드로 구현했고,
쥬스 제작의 경우 싱글톤을 통해 FruitStore에서 과일 데이터를 받아 해당 재고를 확인하고 충분할 경우 True를 리턴하는 Bool 타입을 통해 뷰로 전달해 Alert을 띄우는 로직입니다.

### 풀리지 않은 고민, 궁금했던 점

먼저 코드를 작성하면서 일반적인 For문 반복문과 고차함수를 통한 반복처리에 대해 뭐가 더 좋은 방식인지 궁금했습니다.
For문의 경우 사용시 너무 많은 for, if를 반복하여 코드를 많이 쓰지만 개인적으로 코드 가독성은 좋았고,
고차함수의 경우 사용시 적은 코드를 사용하지만 개인적으로 제대로 코드 가독성이 떨어졌습니다.

물론 연차별로 차이가 있고 취향의 영역도 있지만 실무에서는 어떤 방식을 더 많이 사용하지 궁금했습니다!

최대한 네이밍을 지키고 함수형 프로그래밍을 위해 기능별로 분리했지만 여전히 만족스럽지 못하고 있습니다.ㅜ
혹시 부족한 점이 있다면 다 잡아주시면 반영해보도록 하겠습니다!
감사합니다~!!
![Simulator Screenshot - iPhone 15 Plus - 2023-12-07 at 19 27 40](https://github.com/tasty-code/ios-juice-maker/assets/130636633/1cfe5908-9d23-43da-8075-79dc3b025987)
![Simulator Screenshot - iPhone 15 Plus - 2023-12-07 at 19 27 42](https://github.com/tasty-code/ios-juice-maker/assets/130636633/9192ffc7-457d-4483-9866-fa9aeeb895df)
![Simulator Screenshot - iPhone 15 Plus - 2023-12-07 at 19 29 23](https://github.com/tasty-code/ios-juice-maker/assets/130636633/8616e34a-18cb-4b84-8cf9-9535e9793804)

2023-12-08 01:34 UTC, July911 requested changes

2023-12-08 01:34 UTC, July911 commented on JuiceMaker/JuiceMaker/Controller/DetailViewController.swift
> +    var fruitStore = FruitStore.shared
Q1) 외부에서 접근이 가능한가요 ? 조금 더 정확하게 말하면 필요할까요 ?

2023-12-08 01:34 UTC, July911 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    lazy var buttons: [UIButton] = {
lazy로 하면 어떤 에러가 발생하던가요 ? 왜 생기는 에러인가요 ? 
DetailViewController 에서는 왜 이런방식으로 묶어서 처리하지 않으신건가요 ?

2023-12-08 01:34 UTC, July911 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    override func viewDidLayoutSubviews() {
어떤 용도인가요 ? 어떤 시점에 불리나요 ?

2023-12-08 01:34 UTC, July911 commented on JuiceMaker/JuiceMaker/Model/JuiceData.swift
> +    var quantity: Int64
왜 Int 대신 Int64를 사용하셨나요 ? 성능상에 이유인가요 ?

2023-12-08 01:34 UTC, July911 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        return String(0)
간단하지만 전체적으로 CRUD를 잘 구현해주셨네요. 
아무래도 수량을 더하고 빼는 요소들이 많고 UI와 직접적인 연관이 있는 부분이 아니니, 추후에 테스트 코드도 있으면 좋겠네요 !

2023-12-08 01:34 UTC, July911 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +            .map { fruitList[$0].quantity >= willUseQuantity } ?? false
고차함수를 쓰셔서 여쭤봅니다. 
flatmap 과 compactmap은 무엇인가요 ?

2023-12-08 01:34 UTC, July911 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        super.viewDidLoad()
super.viewDidLoad() 는 무엇일까요 ? 애초에 왜 override 키워드가 붙은 걸까요 ? 
한번 설명 부탁드립니다.

2023-12-08 01:34 UTC, July911 commented on JuiceMaker/JuiceMaker/Views/Base.lproj/Main.storyboard
> +                                    <stackView opaque="NO" contentMode="scaleToFill" axis="vertical" spacing="10" translatesAutoresizingMaskIntoConstraints="NO" id="tcB-i6-XX4">
contentMode="scaleToFill" 
contentMode는 무엇일까요 ?

2023-12-08 01:34 UTC, July911 commented on JuiceMaker/JuiceMaker/Views/Base.lproj/Main.storyboard
> +                            <stackView opaque="NO" contentMode="scaleToFill" distribution="fillEqually" spacing="10" translatesAutoresizingMaskIntoConstraints="NO" id="zaq-m5-IIF">
distribution="fillEqually" 의 의도는 무엇인가요 ? 어떤 옵션이 있고 설정하지 않았을때 기본값은 무엇인가요 ?

2023-12-08 01:34 UTC, July911 commented on JuiceMaker/JuiceMaker/Views/Base.lproj/Main.storyboard
> +                                <rect key="frame" x="41.666666666666686" y="248" width="761" height="108"/>
alignment="top" 다른 스택뷰에는 alignment가 안들어가있던데, 넣어주신 이유는 무엇일까요 ?

2023-12-08 01:34 UTC, July911 commented on JuiceMaker/JuiceMaker/Controller/DetailViewController.swift
> +    func setupLabel() {
JuiceMakerViewController 의 show alert을 보면 private을 붙였던데, 여기서는 안넣어주신 이유가 있을까요 ?

2023-12-12 01:47 UTC, MyNB1 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    lazy var buttons: [UIButton] = {
저희가 작성했던 코드에서는 에러가 발생하진 않았지만, lazy를 사용할 때 주의해야할 점은 
lazy가 여러 스레드에서 사용될 때, lazy가 한 번만 실행되는 걸 보장하지 않습니다.
그렇기 때문에 다중 스레드 환경에서 생성되지 않은 지연 저장 프로퍼티에 많은 스레드가 비슷한 시점에 접근한다면, 여러 번 초기화될 수 있으므로 강한 메모리 누수 및 무한루프가 발생 할 수 있습니다.

DetailViewControllerd에서는 lazy를 사용하여 활용할 로직이 따로 없었습니다.

2023-12-12 01:56 UTC, MyNB1 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    override func viewDidLayoutSubviews() {
viewDidLayoutSubviews는 서브뷰의 레이아웃이 올라갈 때 호출되는 시점에 사용됩니다.
setupUIButton()을 addsubview를 하지 않고 해당 시점에 적용했습니다.
해당시점이 불필요하다는 점을 알게 되었고 viewDidLayoutSubviews를 삭제하도록 하겠습니다.

2023-12-12 01:58 UTC, MyNB1 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        return String(0)
테스트코드도 추가하도록 하겠습니다!

2023-12-12 02:02 UTC, MyNB1 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +            .map { fruitList[$0].quantity >= willUseQuantity } ?? false
flatmap은 중복된 값을 삭제하여 배열로 리턴하고, compactmap은 nil값을 제거하여 배열로 리턴합니다.
저희가 사용한 map은 기존컨테이너에 매개변수를 통해 받은 함수를 적용한 후, 새로운 컨테이너로 리턴합니다.

2023-12-12 02:04 UTC, MyNB1 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        super.viewDidLoad()
부모의 뷰를 viewdidload를 실행하기 위함이고, override의 경우 재정의가 필요한 경우에 사용했습니다.

2023-12-12 02:16 UTC, MyNB1 commented on JuiceMaker/JuiceMaker/Views/Base.lproj/Main.storyboard
> +                                    <stackView opaque="NO" contentMode="scaleToFill" axis="vertical" spacing="10" translatesAutoresizingMaskIntoConstraints="NO" id="tcB-i6-XX4">
contentmode란 콘텐츠의 경계가 변경될 때 뷰에서 콘텐츠의 배치법을 결정하는데 사용합니다.

2023-12-12 02:30 UTC, MyNB1 commented on JuiceMaker/JuiceMaker/Views/Base.lproj/Main.storyboard
> +                            <stackView opaque="NO" contentMode="scaleToFill" distribution="fillEqually" spacing="10" translatesAutoresizingMaskIntoConstraints="NO" id="zaq-m5-IIF">
distribution은 스택뷰에 있는 콘텐츠의 크기와 위치를 정의하는 레이아웃이고
default는 Fill입니다. 
fillequally는 스택뷰 내부 콘텐츠의 비율을 뷰의 크기에 맞게 조절하기 위해 사용했습니다.
옵션에는 fill, fillEqually, fillProportionally, equalSpacing, equalCentering이 있습니다.

2023-12-12 02:31 UTC, MyNB1 commented on JuiceMaker/JuiceMaker/Views/Base.lproj/Main.storyboard
> +                                <rect key="frame" x="41.666666666666686" y="248" width="761" height="108"/>
기본적으로 정렬이 필요없을 경우 사용하지 않지만 해당 스택뷰에서는 필요하다 판단하여 사용했습니다.

2023-12-12 02:33 UTC, MyNB1 commented on JuiceMaker/JuiceMaker/Controller/DetailViewController.swift
> +    func setupLabel() {
해당 부분은 놓친 부분인 것 같습니다. 수정할 계획입니다.

2023-12-12 10:40 UTC, July911 commented on JuiceMaker/JuiceMaker/Controller/DetailViewController.swift
> +    var fruitStore = FruitStore.shared
이게 의존성 주입이 맞을까요 ? 
그렇다면 의존성 주입이란 무엇인가요 ?

2023-12-12 10:40 UTC, July911 commented on JuiceMaker/JuiceMaker/Controller/DetailViewController.swift
> +    var fruitStore = FruitStore.shared
외부보다는 앱 전역이라는 표현이 더 옳바른 것 같습니다.

2023-12-12 10:41 UTC, July911 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +            .map { fruitList[$0].quantity >= willUseQuantity } ?? false
flatmap은 중복된 값을 삭제하여 배열로 리턴하고 
주요 역할이 중복제거가 맞을까요 ?

2023-12-12 10:42 UTC, July911 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        super.viewDidLoad()
" 부모의 뷰를 viewdidload " 라는 표현이 맞을까요 ?

2023-12-12 10:44 UTC, July911 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    lazy var buttons: [UIButton] = {
lazy가 무엇인가요 ?

2023-12-12 10:45 UTC, July911 commented on JuiceMaker/JuiceMaker/Views/Base.lproj/Main.storyboard
> +                            <stackView opaque="NO" contentMode="scaleToFill" distribution="fillEqually" spacing="10" translatesAutoresizingMaskIntoConstraints="NO" id="zaq-m5-IIF">
autoresizingMask 는 뭘까요 ?

2023-12-12 11:00 UTC, kimbs5899 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        super.viewDidLoad()
보통 뷰 라이플 사이클의 템플릿 형태처럼 뷰컨트롤러의 뷰가 메모리에 로드될 때, OS에 의해 호출되는 것이기 때문에
상위뷰의 viewDidLoad를 호출하여 상위뷰의 수행작업을 수행하고 원하는 로직을 재정의하기 위해 사용합니다!

2023-12-12 11:05 UTC, kimbs5899 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +            .map { fruitList[$0].quantity >= willUseQuantity } ?? false
엇 해당 내용을 잘못 알고있었네요ㅜ
2차원 배열을 1차원 배열로 바꿔주듯 평면도를 새로 생성하여 그 안에 값을 리턴해주는 방식입니다!

2023-12-12 11:16 UTC, kimbs5899 commented on JuiceMaker/JuiceMaker/Controller/DetailViewController.swift
> +    var fruitStore = FruitStore.shared
넵! 싱글톤은 전역에서 접근이 가능하다! 이부분 다시 리마인드 하도록하겠습니다!
의존성이란 서로 다른 객체 사이에 의존 관계가 있다는 것입니다! 
의존하는 객체가 수정되면, 다른 객체도 영향을 받게 되는거죠

의존성 주입의 경우  내부에서 만든 객체를 외부에서 넣는것을 말합니다!
사실 이번 싱글톤을 사용하면서 의존성과 의존성 주입, 의존 관계 역전 법칙에 대해 공부중입니다.
의존 관계 역전 법칙의 경우 상위 계층이 하위 계층에 의존하는 전통적인 의존관계를 반전시키는 역전관계로
상위 계층이 하위 계층의 구현으로부터 독립되게 할 수 있는 구조입니다! 아직 이론적인 부분을 공부중이라 코드와 연결 시키 이해할려는 노력하고있습니다!

2023-12-13 11:09 UTC, kimbs5899 commented on JuiceMaker/JuiceMaker/Views/Base.lproj/Main.storyboard
> +                            <stackView opaque="NO" contentMode="scaleToFill" distribution="fillEqually" spacing="10" translatesAutoresizingMaskIntoConstraints="NO" id="zaq-m5-IIF">
superview의 bounds가 변경될때 subview의 크기를 어떻게 크기를 재설정 할것인가에 대한 설정부분입니다!

2023-12-13 11:10 UTC, kimbs5899 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    lazy var buttons: [UIButton] = {
생성되기전 지연생성되도록 따로 설정하는 키워드입니다!

2023-12-14 01:45 UTC, merged