쥬스자판기[Step2] 카일, 엘
tasty-code/ios-juice-maker pull request #86
Opened 2023-12-12 04:57 UTC by LeeSe0ngYe0n

@LeeZion94
안녕하세요, 시온
**`STEP2`** 보내드립니다! 확인 부탁드립니다!
이번에도 저번처럼 디코에서 만나뵐 수 있으면 너무 좋을 것 같습니다😝

---

## 🧐 고민했던점
- ### `MVC` VS `Cocoa-MVC`
    - 우선, **`MVC 패턴`** 즉 **`Model-View-Controller`** 는 기능적 분리와 데이터의 흐름를 정의합니다. 전통적인 MVC 개념은 **`Composite`**, **`Strategy`**, **`Observer`** 패턴으로 구성됩니다.
    - **`Composite`** - 애플리케이션의 뷰 객체는 실제로는 조정된 방식(즉, **`View`** 계층 구조)으로 함께 작동하는 중첩된 **`View`** 의 구성입니다. 이는 사용자 입력 및 표시는 복합 구조의 모든 수준에서 이루어질 수 있습니다.
    - **`Strategy`** - **`Controller`** 객체는 하나 이상의 **`View`** 객체에 대한 **`Strategy`** 을 구현합니다. **`View`** 객체는 시각적 측면을 유지하는 데 국한되며, 인터페이스 동작의 애플리케이션별 의미에 대한 모든 결정을 **`Controller`** 에 위임합니다.
    - **`Observer`** - **`Model`** 객체는 애플리케이션의 관심 객체(일반적으로 **`View`** 객체)에 상태 변경에 대한 알림을 제공합니다.
    - 사용자가 **`Composite`** 구조의 일부 수준에서 **`View`** 를 조작하고 그 결과를 이벤트로 생성됩니다. **`Controller`** 객체는 이벤트를 수신하고 애플리케이션에 맞는 방식으로 변경합니다. 즉, **`Strategy`** 를 적용합니다. 이 **`Strategy`** 은 **`Model`** 객체에 상태를 변경하도록 요청하거나 **`Conposite`** 구조의 일부 수준에서 **`View`** 객체에 동작 또는 모양을 변경하도록 요청합니다. **`Model`** 객체는 상태가 변경되면 **`Observer`** 로 등록한 모든 객체에 이를 알리고, **`Observer`** 가 **`View`** 객체인 경우 그에 따라 모양을 업데이트할 수 있습니다.
    - **`전통적인 MVC 패턴`**
        ![image](https://hackmd.io/_uploads/S1uP8i48T.png)
        ---
    - 반면, **`Cocoa-MVC`** 패턴은 **`전통적인 MVC`** 패턴과 애플리케이션의 **`Controller`** 와 **`View`** 객체에 부여되는 역할에서 차이가 있습니다. **`Cocoa-MVC`** 패턴은 바인딩 기술을 사용하여 **`View`** 가 **`Model`** 객체를 직접 관찰하여 상태 변경에 대한 알림을 수신합니다. **`Model`** 객체는 도메인과 관련된 데이터를 캡슐화하고 해당 데이터에 대한 작업을 수행합니다. 또한, 디자인 측면에서 **`Model`** 객체와 **`View`** 객체를 서로 분리하는 것이 재사용성을 향상시키기 때문에 가장 좋습니다. 따라서, 대부분의 **`Model`** 객체의 상태 변경에 대한 알림은 **`Controller`** 객체를 통해 **`View`** 객체로 전달됩니다. 즉, **`Cocoa-MVC`** 패턴은 **`Model`** 과 **`View`** 객체를 완전히 분리하여 **`Controller`** 객체를 통해서 알림을 수신하여 훨씬 더 깔끔하게 역할이 구분된 구성을 보여줍니다.
    - **`Cocoa MVC 패턴`**
        ![image](https://hackmd.io/_uploads/SJ4dLo4U6.png)
        ---
    - **`Ref`** : [Apple Developer/Model-View-Controller](https://developer.apple.com/library/archive/documentation/General/Conceptual/CocoaEncyclopedia/Model-View-Controller/Model-View-Controller.html#//apple_ref/doc/uid/TP40010810-CH14)

## 🤔 조언을 얻고 싶은 부분
- ### `guard let self` VS `self?.`
    - 우선, **`weak self`** 를 사용하여 약한참조를 발생시켜 **`retain count`** 를 증가시키지 않고 결과적으로 **`Memory Leak`** 을 발생하지 않게 구현하고자 했습니다. 
    - 몇 가지 예제를 알아보던 중 **`guard let self`** 와 **`self.?`** 를 통한 구현방법이 있다는 것을 알게 되었습니다.
    - **`guard let self`** 를 사용하면 **`escaping`** 클로저 블록을 실행하는 도중 **`Action`** 이 메모리에서 할당해제 될 때 **`self`** 가 클로저가 강한참조를 하고 있어 클로저가 끝날때 까지 메모리에서 지워지지 않고 클로저의 실행이 끝나기만을 기다립니다. 하지만 약한참조를 하고 있다면 **`Action`** 은 클로저의 진행유무에 상관없이 메모리에서 지워질 것이고 클로저는 그 시점에서 동작하지 않게 됩니다. 따라서, **`gaurd let`** 은 **`self`** 가 **`nil`** 인지 확인하고 **`nil`** 이 아니라면, 스코프를 위한 임시 강한 참조인 **`self`** 를 생성합니다. 이미 만들어놓은 강한 참조인 **`self`** 는 클로저 스코프의 끝에 도달할 때까지 **`deallocation`** 되지 않습니다. 즉, **`guard let`** 은 클로저의 생명 주기동안 계속해서 살아있다는 것입니다.만약에 **`guard let`** 을 사용하지 않고 **`self?.`** 를 사용하면 시작할 때 강한 참조를 만들지 않고 **`nil`** 체크를 모든 메서드를 호출할 때 마다 하게 됩니다. 이 말은 어느 포인트에서 **`nil`** 이 될 수 있다는 것이고, 해당하는 메서드는 불리지않고 다음 줄로 넘어가게 됩니다. 현재 코드에선 크게 문제될 사항이 없고 **`showFruitStoreViewController()`** 함수를 부르는 것 밖에 없기에 **`guard let self`** 를 사용해도 될 것 같다고 판단했는데 시온의 입장에서는 어떤 상황에서 **`guard let self`** 를 사용하는 지 이러한 고민이 합리적인지 궁금합니다!
        ```swift
        // self?. 사용
        func showUnderStockAlert(message: String) {
            let alert = UIAlertController(title: "알림", message: message, preferredStyle: .alert)
            alert.addAction(UIAlertAction(title: "예", style: .default, handler: { [weak self] _ in
            self?.showFruitStoreViewController()
            }))
            alert.addAction(UIAlertAction(title: "아니요", style: .destructive))
            self.present(alert, animated: true)
        }
        // guard let self 사용
        func showUnderStockAlert(message: String) {
            let alert = UIAlertController(title: "알림", message: message, preferredStyle: .alert)
            alert.addAction(UIAlertAction(title: "예", style: .default, handler: { [weak self] _ in
            guard let self else { return }
            showFruitStoreViewController()
            }))
            alert.addAction(UIAlertAction(title: "아니요", style: .destructive))
            self.present(alert, animated: true)
        }
        ```
- ### **`싱글톤 도입`** 에 대한 의문
    - 현재 **`navigationItem`** 의 **`action 핸들러`** 에 데이터를 주입해주고 있습니다. 현재 코드는 **`데이터를 전달`** 하는 기능을 하고 있다고 생각하는데 프로젝트의 흐름을 보면 **`데이터를 공유`** 해야하지 않을까라는 궁금증이 듭니다. 따라서, 싱글톤 패턴 도입에 대한 고려를 했는데 현재 앱 규모에서 과연 적절한 판단인지 궁금합니다.
        ```swift
        self.navigationItem.rightBarButtonItem = UIBarButtonItem(title: "재고수정",
                                                                 style: .plain,
                                                                 target: self,
                                                                 action: #selector(showFruitStoreViewController))
        ```
    
- ### `makeAndNotifyOrder()` 함수 구현
    - 매개변수를 받는 부분이 동일하고 쥬스를 만드는 초기 로직끼리 묶었는데 좋은 방향의 캡슐화일까요?
    - 만약 그렇다면, 네이밍은 괜찮은 지 또한 궁금합니다!
        ```swift
        func makeAndNotifyOrder(juice: Juice) throws {
            try juiceMaker.checkUnderstockedFruits(juice: juice)
            juiceMaker.makeJuice(juice: juice)
            showMakeJuiceCompleteAlert(juice: juice)
        }
        ```
- ### 쥬스버튼 **`IBAcion`** 연결
    - 현재 쥬스의 각 버튼을 하나하나 **`IBAction`** 연결해 줘서 코드가 중복되고 길어진 경향이 있는데 **`IBAction`** 함수 하나의 버튼을 다 연결해서 사용할 수 있다면 그렇게 사용하는 것이 좋은 방법인지 궁금합니다!
    - 또한 중복되는 코드는 함수로 빼서 사용할 때 **`의존성`** 이 생기게 되면 함수로 빼지 않는 것이 맞는지 방법인지 궁금합니다!

2023-12-13 01:48 UTC, LeeZion94 commented
1. 약한참조 관련한 부분
- guard self else, self?. 의 차이점에 대해서 조금 저와 다르게 이해하시고 잇는 것 같다는 생각이 들었어요. 이 부분은 이전에 공지한대로 구두로 같이 논의하면 좋을 주제라고 생각이 되고 그 전까지 guard self else를 작성하는 것이 self?와 어떤 차이가 있을지를 optional Binding이라는 관점으로 비교해보셧으면 좋겠습니다.

2. 싱글톤 도입
- 싱글톤은 안티패턴으로 불리긴하지만 사용해야하는 이유와 해제만 올바르게 이뤄질 수 있다면 사용해도 좋다고 생각해요 하지만 현재 프로젝트에서는 굳이 싱글톤을 사용해야할 이유가 없다고 생각합니다. 그 이유는 데이터를 공유해야하는 곳들이 여러군데에 산개되어서 존재해야하는 것이 아니고 충분히 넘겨줄 수 있는 형태를 띄고 있기 때문입니다. 여러분의 생각은 어떠신가요?

3. makeAndNotifyOrder()
- 여러분들이 생각하고 있는 캡슐화란 무엇인가요? 저와는 다르게 이해하고 있는 것 같아서요 ㅎㅎ 한번 여러분들이 이해하고 있는 캡슐화에 대해서 먼저 설명해주세요

4. IBAction
- 이 부분은 코멘트로 남겨놨습니다. 확인부탁드릴게요

2023-12-13 01:49 UTC, LeeZion94 requested changes

2023-12-13 01:49 UTC, LeeZion94 commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +    @IBOutlet weak var strawberryStockLabel: UILabel!
IBOutlet에 weak라는 키워드가 붙어야하는 이유는 무엇인가요?

2023-12-13 01:49 UTC, LeeZion94 commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +    var strawberryStock: String = ""
FruitStoreViewController의 과일재고들은 왜 property로 주입받아야하나요?

여러가지 방식중 property로 주입해주신 방법을 선택한 이유가 궁금해요 ㅎㅎ

2023-12-13 01:49 UTC, LeeZion94 commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +    private func configureUI() {
의도하신 configureUI의 이미는 무엇인가요?
configure의 의미를 생각해본다면 contents의 값을 넣어주는 것보단 layout을 구성한다는 의미에 더 가깝다는 생각들어요
이부분에 대해서는 어떻게 생각하세요?

2023-12-13 01:49 UTC, LeeZion94 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    private let juiceMaker = JuiceMaker()
JuiceMakerViewController는 juiceMaker를 주입받는 것이 아닌 안에서 가지고 있게 되겠네요?
JuiceMakerViewController로 juiceMaker를 외부에서 주입시켜줄 수 있는 방법으로는 어떤 방법이 있을까요?

2023-12-13 01:49 UTC, LeeZion94 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +            let strawberryStock = juiceMaker.fruitStore.fruitStocks[.strawberry],
구두로 진행했던 것과는 다르게 juceMaker.fruitStore로 과일가게에 접근하고 있군요 ㅎㅎ
해당 방법으로 접근하는 이유가 무엇인가요? fruitStore는 분명히 class로 구현되어 있는데 말이죠!

2023-12-13 01:49 UTC, LeeZion94 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    private func showMakeJuiceCompleteAlert(juice: Juice) {
alert를 만드는 부분이 2군데 있고 중복되는 코드들이 존재하는 것 같아요.
이를 한군데서 처리할 수 있도록 바꿔보는 것은 어떨까요? 또 다른 ViewController에서도 이용할 수 있도록 protocol의 extension을 사용해서 alert를 띄울 수 있는 기능을 수평확장시켜보는 것도 고려해볼 수 있을 것 같아요 ㅎㅎ 
이부분에 대해서 고민해보시고 구두로 추가적으로 논의해봐요

2023-12-13 01:49 UTC, LeeZion94 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        alert.addAction(UIAlertAction(title: "닫기", style: .destructive))
destructive style을 사용해 주셨네요? HIG에 의거하여 destructive가 사용되어야하는 경우에 대해서 설명해주세요 ㅎ

그리고 해당 alert는 '확인'이 더 적절한 문구로 보입니다.

2023-12-13 01:49 UTC, LeeZion94 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        alert.addAction(UIAlertAction(title: "예", style: .default, handler: { [weak self] _ in
해당 handler closure는 weak를 사용하지 않는다면 순환참조가 발생할까요?

2023-12-13 01:49 UTC, LeeZion94 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    private func makeAndNotifyOrder(juice: Juice) throws {
make, notify를 통합적으로 표현할수 있는 표현을 하는 것이 더 좋아보여요 ㅎㅎ

2023-12-13 01:49 UTC, LeeZion94 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +            let fruitStoreViewController = storyboard?.instantiateViewController(identifier: "FruitStoreViewController") as? FruitStoreViewController
instantiateViewController를 사용하여 initializer injection을 할 수 있는 방법에 대해서 찾아보시고 설명해주세요.
NSCoder란 무엇일까요?

2023-12-13 01:49 UTC, LeeZion94 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    @IBAction private func strawberryBananaJuiceButtonTapped(_ sender: UIButton) {
1. 먼저 함수의 이름이 동사로 시작하지 않고 있어요 IBAction의 경우에는 분명히 동사로 시작할 수 있는 event를 가지고 있다고 생각해요 Tapped를 앞으로 옮겨 보는 건어떨까요? didTapped? tapped?

2. Button을 눌러서 과일을 만드는 과정의 로직들이 중복코드가 정말 많이 발생했네요? 하나의 공통 로직으로 분기한다음 그 로직을 사용해 보는 건 어떨까요?

3. 하나의 IBOutlet으로 처리하는 것도 좋은 방법인 것 같아요. IBOutletCollection에 대해서 한번 알아보면 좋을 것 같아요
4. 또한 UIButton에는 tag 라는 property가 존재해요. 이를 어떻게 활용할 수 있을까요?

2023-12-13 01:49 UTC, LeeZion94 commented on JuiceMaker/JuiceMaker.xcodeproj/project.pbxproj
>  				C73DAF36255D0CDD00020D38 /* AppDelegate.swift */,
AppDelegate, SceneDelegate와 ViewController가 Controller라는 폴더 안에 동일하게 들어있는 것은 조금 어색해보입니다.
다른 나눠보는 건 어떨까요?

2023-12-13 01:49 UTC, LeeZion94 commented on JuiceMaker/JuiceMaker.xcodeproj/project.pbxproj
>  		C73DAF40255D0CDE00020D38 /* Assets.xcassets in Resources */ = {isa = PBXBuildFile; fileRef = C73DAF3F255D0CDE00020D38 /* Assets.xcassets */; };
Assets, LaunchScreen도 카일과 엘이 생각하는 View가 맞나요?
그렇게 생각한다면 왜 View라고 생각하시나요?

2023-12-13 01:49 UTC, LeeZion94 commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +    override func viewDidLoad() {
viewDidLoad는 언제 호출되나요?

2023-12-13 01:49 UTC, LeeZion94 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        self.navigationItem.rightBarButtonItem = UIBarButtonItem(title: "재고수정",
self.navigationItem으로 접근할 수 있는 이유는 무엇인가요?
ViewController는 항상 Navigation에 속해야만하는 것은 아닐텐데...

2023-12-13 01:49 UTC, LeeZion94 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    @objc
@objc 키워드는 무엇인가요? 그리고 여기에서는 왜 붙여주셨나요?

2023-12-15 11:48 UTC, LeeSe0ngYe0n commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +    @IBOutlet weak var strawberryStockLabel: UILabel!
UIViewController는 UIView 타입인 View를 암시적으로 언래핑하여 사용하고 있습니다.
따라서 ViewController가 관리하는 UIView에 대해 강한 참조를 유지합니다. (ViewController RC + 1, UIView RC + 1 )
또한 UIView는 자신의 하위 UIView 객체에 대한 강한 참조를 유지합니다. 각 UIView 객체의 인스턴스는 클래스로써 힙영역에 저장이 되고 IBOutlet이 ViewController에 연결되면 ViewController는 아울렛 변수로 각 UIView의 객체의 참조를 저장합니다. (UIView 객체 RC + 1) 하지만 ViewController이 UIView 객체들을 강하게 참조하면 RC가 2로 올라갑니다. 그래서 UIView가 메모리에서 해제되도 뷰의 객체의 RC는 여전히 1이기 때문에 메모리 누수가 발생할 수도 있습니다. 그렇기 때문에 weak 키워드로 순환 참조를 방지할 수 있습니다.

2023-12-15 11:55 UTC, Changhyun-Kyle commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +    @IBOutlet weak var strawberryStockLabel: UILabel!
`약한 참조 시`
![image](https://github.com/tasty-code/ios-juice-maker/assets/101093592/27dfdd9a-4db8-4b85-922d-3593094ed69e)

`강한 참조 시`
![image](https://github.com/tasty-code/ios-juice-maker/assets/101093592/39039f74-7e4a-45a9-b4fe-dd8f9c8051d0)

2023-12-15 12:03 UTC, Changhyun-Kyle commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +    var strawberryStock: String = ""
`JuiceMakerViewController`의 과일 재고 수량을 그대로 `FruitStoreViewController`에서 받아와야하기 때문에 직접적으로 값을 주입해주는 것이 효율적이라고 판단했습니다.

2023-12-15 12:09 UTC, Changhyun-Kyle commented on JuiceMaker/JuiceMaker.xcodeproj/project.pbxproj
>  				C73DAF36255D0CDD00020D38 /* AppDelegate.swift */,
위와 동일하게 로직 구현에 몰두하여 아직 폴더링 작업을 진행하지 못했습니다.
`AppDelegate, SceneDelegate`는 앱과 화면의 흐름을 나타내는 작업을 하므로 `App` 폴더로 이동시켰습니다.

2023-12-15 12:09 UTC, Changhyun-Kyle commented on JuiceMaker/JuiceMaker.xcodeproj/project.pbxproj
>  		C73DAF40255D0CDE00020D38 /* Assets.xcassets in Resources */ = {isa = PBXBuildFile; fileRef = C73DAF3F255D0CDE00020D38 /* Assets.xcassets */; };
로직 구현에 몰두하여 아직 폴더링 작업을 진행하지 못했습니다.
`Assets, LaunchScreen`을 `Resource` 폴더로 이동시켰습니다.

2023-12-17 03:08 UTC, LeeZion94 commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +    var strawberryStock: String = ""
초기화 때 건네주는 방식이 아니라면 과일 재고 수량을 그대로 받아올 수 없는 건가용? 오히려
초기화 때 건네주는 것이 더 자연스러운 흐름으로 보이는 것 같아요 어떻게 생각하세요?

2023-12-17 03:09 UTC, LeeZion94 commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +    private func configureUI() {
방금 말씀해 주셧듯 contents의 값을 넣어준다는 네이밍으로 수정되는 것이 더 명확하게 메서드의 내용을 설명할 수 있지 않을까요?

configureUI UI를 구성 하는 즉 addSubview를 하거나 직접적으로 view를 계층에 추가하는 역할을 담담해야하는 이름으로 생각됩니다. 이 부분은 강제사항이 아닌 개인의 취향도 조금 반영될 수 있는 부분이라고 생각되요 ㅎㅎ

2023-12-17 09:34 UTC, LeeSe0ngYe0n commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        alert.addAction(UIAlertAction(title: "닫기", style: .destructive))
공식문서를 참조하면 `destructive`는 컨텐츠를 `삭제`하는 경우 사용하라고 쓰여져 있습니다.
Identify destructive buttons. If an alert button results in a destructive action, like deleting content, specify the destructive button style to help people recognize it.
현재 `닫기 버튼`은 컨텐츠를 삭제하는 버튼이 아니므로 기본설정으로 바꿔주겠습니다!
Ref: https://developer.apple.com/design/human-interface-guidelines/alerts

2023-12-17 09:37 UTC, Changhyun-Kyle commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +    override func viewDidLoad() {
[Apple 공식문서](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621495-viewdidload)에 따르면 뷰 컨트롤러가 뷰 계층 구조를 메모리에 로드한 후에 호출됩니다. 이 메서드는 뷰 계층 구조가 `nib 파일`에서 로드되었는지 또는 `loadView()` 메서드에서 프로그래밍 방식으로 생성되었는지에 관계없이 호출됩니다. 일반적으로 이 메서드를 재정의하여 `nib 파일`에서 로드된 뷰에 대한 추가 초기화를 수행합니다.
> **ViewController의 생명주기**
> ![image](https://github.com/tasty-code/ios-juice-maker/assets/101093592/aabe3698-b802-491f-9d26-8ae1dda0097c)

2023-12-17 09:48 UTC, LeeSe0ngYe0n commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    @objc
`Objective-C`와 유사한 방식으로 `컴파일` 되어야 함을 `컴파일러`에게 알려주어서 `Swift 코드`를 `Objective-C` 코드와 연결할 수 있게 해주는 역할입니다. 
이 코드에서 사용한 이유는 `#selector`를 구현하기 위함입니다. `selector`는 `Objective-C`에서 사용되는 메서드이기 때문에 `@objc`를 이용해 `selector`를 구현해야 합니다!

2023-12-17 12:12 UTC, Changhyun-Kyle commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        self.navigationItem.rightBarButtonItem = UIBarButtonItem(title: "재고수정",
`스토리보드`에서 `navigationController`를 생성 후 `rootViewController`로 설정해서 접근할 수 있다고 생각합니다!

<img width="780" alt="image" src="https://github.com/tasty-code/ios-juice-maker/assets/101093592/8cbae6ea-3dbe-49b0-954f-fa1a6bcc2be9">

2023-12-18 01:47 UTC, Changhyun-Kyle commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    private func showMakeJuiceCompleteAlert(juice: Juice) {
JuiceMakerAlert 프로토콜을 선언하여 구현했습니다!
```swift
protocol JuiceMakerAlert {
    func showJuiceMakerAlert(viewController: UIViewController, isCompletedMakeJucie: Bool, message: String)
}

extension JuiceMakerAlert {
    func showJuiceMakerAlert(viewController: UIViewController, isCompletedMakeJucie: Bool, message: String) {
        let alert = UIAlertController(title: "알림" , message: message, preferredStyle: .alert)
        guard
            isCompletedMakeJucie
        else {
            let juiceMakerViewController = JuiceMakerViewController()
            alert.addAction(UIAlertAction(title: "예", style: .default, handler: { _ in
                print("누름")
                juiceMakerViewController.showFruitStoreViewController()
                print("누름")
            }))
            alert.addAction(UIAlertAction(title: "아니요", style: .cancel))
            viewController.present(alert, animated: true)
            return
        }
        
        alert.addAction(UIAlertAction(title: "확인", style: .cancel))
        viewController.present(alert, animated: true)
    }
}
```

2023-12-18 01:59 UTC, Changhyun-Kyle commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    @IBAction private func strawberryBananaJuiceButtonTapped(_ sender: UIButton) {
- 함수의 이름이 동사로 시작할 수 있도록 `tappedButton()`으로 수정했습니다.
- 중복코드를 `makeJuice()` 함수로 분기처리하여 리팩토링했습니다.
- `IBOutletCollection`과 `UIButton`의 `tag property` 도입에 대해 고민해봤습니다. 결과적으로 두 부분 모두 도입하지 않기로 결정했습니다. 그 이유는 `IBOutletCollection`을 사용한다면 코드의 양이 줄어들지만 가독성 측면에서 현저히 떨어진다고 판단했고, `UIButton`의 `tag property`을 사용한다면 `switch문`을 통해 접근해야돼서 확장에 대해 폐쇄적이라고 생각하여 현재 코드를 유지하기로 했습니다. 시온의 생각은 어떤지 궁금합니다!
```swift
     private func makeJuice(juice: Juice, labels: [UILabel]) {
             do {
                 try makeAndNotifyOrder(juice: juice)
                 for (index, ingredient) in juice.recipe.enumerated() {
                     guard 
                         let remainStock = juiceMaker.fruitStore.fruitStocks[ingredient.key]
                     else {
                         return
                     }
                     guard index < labels.count else { return }
                     labels[index].text = String(remainStock)
                 }
             } catch {
                 showJuiceMakerAlert(viewController: self,
                                     isCompletedMakeJuice: false,
                                     message: error.localizedDescription)
             }
         }
    
    @IBAction private func tappedStrawberryBananaJuiceButton(_ sender: UIButton) {
        makeJuice(juice: .strawberryBananaJuice, labels: [strawberryStockLabel, bananaStockLabel])
    }
    
    {/*code*/}
```

2023-12-18 02:09 UTC, LeeZion94 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    private func showMakeJuiceCompleteAlert(juice: Juice) {
항상 띄울 때마다 ViewController를 꼭 전달해줘야하나요? ㅎㅎ
where 절에 대해서 한번 봐주시구 활용방법에 대해서 알려주세요!

2023-12-18 02:10 UTC, Changhyun-Kyle commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    private func makeAndNotifyOrder(juice: Juice) throws {
`startJuiceMakerProcess()`로 함수명을 변경하였는데 적합한지 의문이 듭니다🥺
```swift
    private func startJuiceMakerProcess(juice: Juice) throws {
        try juiceMaker.checkUnderstockedFruits(juice: juice)
        juiceMaker.makeJuice(juice: juice)
        showJuiceMakerAlert(viewController: self, 
                            isCompletedMakeJuice: true,
                            message: "\(juice.name) 나왔습니다! 맛있게 드세요!")
    }
```

2023-12-18 02:19 UTC, Changhyun-Kyle commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    private func showMakeJuiceCompleteAlert(juice: Juice) {
새롭게 알게된 부분이네요! 프로토콜 익스텐션에 `where` 절을 사용하게 되면 이 익스텐션이 특정 프로토콜을 준수하는 타입에만 적용될 수 있도록 제약을 줄 수 있어 ViewController를 직접 전달하지 않고도 사용할 수 있게 리팩토링 했습니다!
```swift
protocol JuiceMakerAlert {
    func showJuiceMakerAlert(isCompletedMakeJuice: Bool, message: String)
}

extension JuiceMakerAlert where Self: UIViewController {
    func showJuiceMakerAlert(isCompletedMakeJuice: Bool, message: String) {
        let alert = UIAlertController(title: "알림" , message: message, preferredStyle: .alert)
        guard
            isCompletedMakeJuice
        else {
            let juiceMakerViewController = JuiceMakerViewController()
            alert.addAction(UIAlertAction(title: "예", style: .default, handler: { _ in
                juiceMakerViewController.showFruitStoreViewController()
            }))
            alert.addAction(UIAlertAction(title: "아니요", style: .cancel))
            self.present(alert, animated: true)
            return
        }
        
        alert.addAction(UIAlertAction(title: "확인", style: .cancel))
        self.present(alert, animated: true)
    }
}
```

2023-12-18 06:07 UTC, Changhyun-Kyle commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    private let juiceMaker = JuiceMaker()
`SceneDelegate`에서 앱 진입시점에 주입시켜줄 수 있을 것 같습니다. 하지만 스토리보드로 구현한 프로젝트라 어떻게 주입할 수 있을 지 잘모르겠습니다...

2023-12-19 01:37 UTC, Changhyun-Kyle commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +    var strawberryStock: String = ""
시온 말씀처럼 초기화 때 건네주는 방법이 더 자연스러운 것 같습니다!
따라서, `JuiceMakerViewController`에서 `FruitStoreViewController` 생성 시 `fruitStore` 객체를 넘겨주는 방법으로 구현했습니다.

```swift
// JuiceMakerViewController
@objc
    func showFruitStoreViewController() {
        guard
            let fruitStoreViewController = storyboard?.instantiateViewController(identifier: "FruitStoreViewController", creator: { coder in
                return FruitStoreViewController(fruitStore: self.fruitStore, coder: coder)
            })
        else {
            fatalError("init(coder:) has not been implemented")
        }
        self.navigationController?.pushViewController(fruitStoreViewController, animated: true)
    }

// FruitStoreViewController
    private let fruitStore: FruitStore
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setStockLabelUI()
    }
    
    init?(fruitStore: FruitStore, coder: NSCoder) {
        self.fruitStore = fruitStore
        super.init(coder: coder)
    }
    
    required init?(coder: NSCoder) {
         fatalError("init(coder:) has not been implemented")
    }
```

2023-12-19 01:43 UTC, Changhyun-Kyle commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +            let strawberryStock = juiceMaker.fruitStore.fruitStocks[.strawberry],
기능 구현에 몰두하다보니 신경쓰지 못했습니다 죄송합니다. `fruitStore`로 접근해서 재고 데이터를 받아오게 구현했습니다!

2023-12-19 02:01 UTC, Changhyun-Kyle commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        alert.addAction(UIAlertAction(title: "예", style: .default, handler: { [weak self] _ in
해당 `handler closer`는 `non-escaping` 클로저이기 때문에 함수가 종료되기 전 클로저가 실행됩니다. 또한, `handler`를 보면 클로저가 옵셔널 타입으로 선언되어있는데 옵셔널 타입의 클로저 매개변수는 제네릭 타입이며 클로저 타입이 아니라는 부분을 확인했습니다. 따라서, 순환참조가 발생하지 않을 것 같습니다.

2023-12-19 02:46 UTC, Changhyun-Kyle commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +            let fruitStoreViewController = storyboard?.instantiateViewController(identifier: "FruitStoreViewController") as? FruitStoreViewController
[Apple 공식문서](https://developer.apple.com/documentation/uikit/uistoryboard/3213989-instantiateviewcontroller)를 참고했을 때, 두가지 방법을 확인할 수 있었습니다.
- `instantiateViewController(identifier:creator:)`: 스토리보드에서 지정된 뷰 컨트롤러를 생성하고 사용자 지정 초기화 코드를 사용하여 초기화합니다.
- `instantiateViewController(withIdentifier:)`: 지정된 식별자를 가진 뷰 컨트롤러를 생성하고 스토리보드의 데이터로 초기화합니다.

또한, [NSCoder](https://developer.apple.com/documentation/foundation/nscoder)란 인터페이스이고 이를 구현하는 서브클래스는 어떤 객체를 메모리와 다른 데이터 포맷 사이에서 아카이빙(객체와 데이터를 디스크에 저장)과 디스트리뷰션(객체와 데이터를 서로 다른 프로세스나 스레드사이에서 복사)을 통해 전환을 가능하게 해주는 추상 클래스 입니다. 
따라서, `init(coder:NSCoder)`에서 `Coder`는 객체의 타입을 데이터와 함께 저장해두었다가 디코딩이될 때 이 타입을 그대로 사용하며 스토리보드나 nib 파일을 통해 뷰를 로드하면서 초기화합니다.

2023-12-22 08:23 UTC, merged