쥬스자판기[Step2] Sidi, Easy
tasty-code/ios-juice-maker pull request #87
Opened 2023-12-12 05:44 UTC by jus1234

리뷰어: @cherrishRed
버드: Sidi, Easy

레드 안녕하세요!
쥬스자판기 프로젝트 STEP 2 PR 드려요!
STEP 1 PR을 main브랜치로 보냈었네요...ㅜㅜ

### 코드 설명

`FuitStore` : 데이터의 일관성을 보장하기 위해 싱글톤으로 관리

`FruitStoreViewController` : `ViewController`, `SecondViewController`에서 공통적으로 사용하는 재고 화면 관리

### 쥬스자판기 STEP 2 고민사항

**Protocol 사용**

비슷한 성격의 `ViewController`를 `Protocol`로 묶어서 관리하는 것이 일반적으로 사용하는 방식인지 궁금합니다!

```swift
protocol FruitStoreViewController {}
class ViewController: UIViewController, FruitStoreViewController {}
class SecondViewController: UIViewController, FruitStoreViewController {}
```

**Alert 관리**

`ViewController`에서 alert 생성 시 코드가 너무 길어지고 결합도가 높아지는 것 같아 alert을 관리하는 Enum을 별도로 생성하고 저장 변수로 `UIAlertController`를 생성하는 방법으로 관리했습니다. 만든 Enum이 다양한 파라미터를 받고 있고 `UIAlertController`를 직접 생성하는 것도 좋지 않은 방법 같다는 생각이 들었습니다. 다른 관리 방법들이 궁금합니다!

```swift
import UIKit

enum Alert {
    case juiceSucess(Juice)
    case juiceFail(() -> ())
}

extension Alert {
    var modal: UIAlertController {
        switch self {
        case .juiceSucess(let juice):
            let alertController = UIAlertController(title: "알림", message: "\(juice.name) 나왔습니다! 맛있게 드세요!", preferredStyle: .alert)
            let yes = UIAlertAction(title: "확인", style: .default, handler: nil)
            alertController.addAction(yes)
            return alertController
        case .juiceFail(let handler):
            let alertController = UIAlertController(title: "알림", message: "재료가 모자라요. 재고를 수정할까요?", preferredStyle: .alert)
            let yes = UIAlertAction(title: "예", style: .default, handler: { _ in handler() })
            let no = UIAlertAction(title: "아니오", style: .destructive, handler: nil)
            alertController.addAction(yes)
            alertController.addAction(no)
            return alertController
        }
    }
}
```

**함수의 기능별 분리**

버튼을 눌렀을 때 동작하는 @IBAction 함수에서 버튼의 누름을 인지하는 동작까지만 책임지게 할 것인지, 인지 후 동작까지 책임지게 할 것인지 고민됐습니다.

- 책임을 나눠 본 경우

```swift
@IBAction func stockChangeButtonTapped(_ sender: UIBarButtonItem) {
    goToStockCangeView()
}

func goToStockCangeView() {
    guard let secondVC = storyboard?.instantiateViewController(withIdentifier: ViewID.secondVC.id) as? SecondViewController else { return }
    self.navigationController?.pushViewController(secondVC, animated: true)
}
```

- 나누지 않은 경우

```swift
@IBAction func juiceButtonTapped(_ sender: UIButton) {
    guard let juice =  juiceMaker.makeJuice(juice: jucieMenu[sender.tag]) else {
        present(Alert.juiceFail(goToStockCangeView).modal, animated: true, completion: nil)
        return
    }
    present(Alert.juiceSucess(juice).modal, animated: true, completion: nil)
    configureFruitStoreUI()
}
```
### 스크린샷
![Simulator_Screen_Recording_-_iPhone_15_Pro_-_2023-12-12_at_14 38 20](https://github.com/tasty-code/ios-juice-maker/assets/47639904/74cd1ba5-7e10-49b9-9d72-bae3fa4571e2)

2023-12-12 10:55 UTC, cherrishRed requested changes
@jus1234  @yoruck2 
두분 모두 수고하셨습니다!🎉🎉🎉

> 비슷한 성격의 `ViewController`를 `Protocol`로 묶어서 관리하는 것이 일반적으로 사용하는 방식인지 궁금합니다!

만들어 놓으신 `FruitStoreViewController` 잘 보았습니다. 
우선, 창의적으로 protocol 을 사용해 보시려는 접근은 너무 좋았습니다. protocol 에 대해서 잘 이해하고 계신 것 같습니다. 그런데 솔직하게 말씀드리면, 일반적으로 사용하는 방식과는 조금 결이 다릅니다.

**네이밍**
[protocol naming](https://developer.apple.com/forums/thread/125207)
이 글을 읽어 보시는 것을 추천 합니다.
FruitStoreViewController 라는 네이밍을 보면, protocol 이 아니라 UIViewController 일 것 같은 추측이 드네요. 

**UI의 유연성**
만약에, 샤인머스캣을 추가하는 기능이 들어왔습니다. 
그런데, 지금 주문 할 수는 없고, comming soon 입니다. 
`FruitStoreViewController` 에 그걸 넣어야 할까요? 

UI는 언제든 바뀔 수 있습니다. 
지금 protocol 이 채택만 하면 모든게 구현되는 가이드 처럼 보이네요. 
조금 더 구현을 viewController에 해도 괜찮으니, protocol에 최소한의 기능만 남겨 보세요. 

> `ViewController`에서 alert 생성 시 코드가 너무 길어지고 결합도가 높아지는 것 같아 alert을 관리하는 Enum을 별도로 생성하고 저장 변수로 `UIAlertController`를 생성하는 방법으로 관리했습니다. 만든 Enum이 다양한 파라미터를 받고 있고 `UIAlertController`를 직접 생성하는 것도 좋지 않은 방법 같다는 생각이 들었습니다. 다른 관리 방법들이 궁금합니다!

Alert을 따로 관리 하신 부분은 너무 좋았습니다!
실제로도 AlertService를 따로 만들어서 운영 하는 경우가 많습니다. 
이 부분을 조금 더 고도화 해보시면 좋을 것 같아요!

**함수의 기능별 분리**

> 버튼을 눌렀을 때 동작하는 [@IBAction](https://github.com/IBAction) 함수에서 버튼의 누름을 인지하는 동작까지만 책임지게 할 것인지, 인지 후 동작까지 책임지게 할 것인지 고민됐습니다.

이 부분은 가독성이 좋은 쪽으로, 그리고 컨벤션 적으로만 통일 하면, 괜찮다고 생각합니다.

2023-12-12 10:55 UTC, cherrishRed commented on JuiceMaker/JuiceMaker/Controller/SecondViewController.swift
> +class SecondViewController: UIViewController, FruitStoreViewController {
`SecondViewController` 라는 네이밍은 이 뷰가 어떤 역할을 하는지 알기 어려운 이름인 것 같습니다.🤔
뷰의 역할을 생각해서 이름을 수정해 보는 것이 어떨까요? 😗

2023-12-12 10:55 UTC, cherrishRed commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +class ViewController: UIViewController, FruitStoreViewController {
`ViewController` 이곳 네이밍도 조금 더 의미있는 네이밍을 생각해 보세요!

2023-12-12 10:55 UTC, cherrishRed commented on JuiceMaker/JuiceMaker/Enums/ViewID.swift
> +}
`ViewID` 라는 타입을 만들도록 하셨군요!
id 를 저장한다는 것은 좋은 아이디어 입니다! 
그런데, 그럼 view controller 가 하나 늘어날 때 마다 
enum case 가 하나 늘어나겠네요. 그리고, storyboard 와 같은 id 를 적어줘야 하는데, 타이핑 오류가 있을 수도 있구요.
조금 다른 방법도 찾아보면 어떨까요?

2023-12-12 10:55 UTC, cherrishRed commented on JuiceMaker/JuiceMaker/Enums/Alert.swift
> +}
Alert 을 따로 빼서 사용하신 점 너무 좋습니다!
VC 에서 코드가 간편해 지겠네요 👏👏👏

그런데, 이 alert 은 조금 범용성이 떨어지는 것 같아요. 

만약 다른 프로젝트에서, 이미 구현해 놓은 alert 을 가져다 쓰고 싶을 때, 이걸 사용하기엔 쉽지 않을 것 같습니다. 
이름이 `Alert` 인 만큼 조금 더 범용성 있게 만들어 보는 것은 어떨까요? 

아니면, `JuiceAlert` 으로 특정 기능을 위한 `Alert` 으로 이름을 바꾸는 것도 괜찮구요. 

또 `UIAlertController` 를 return 하고 있는데, 이름이 왜 `modal` 인지 궁금 하네요🤔

2023-12-12 10:55 UTC, cherrishRed commented on JuiceMaker/JuiceMaker/Controller/FriutStoreViewController.swift
> +}
ui update 를 쉽게 하도록 코드를 만드셨군요!
재미있는 코드네요!

2023-12-12 10:55 UTC, cherrishRed commented on JuiceMaker/JuiceMaker/Controller/FriutStoreViewController.swift
> +}
labels 가 있는 이유는 `configureFruitStoreUI` 라는 것을 알고 있는데, 
strawberryLabel 등 다른 label 이 필요한 이유는 무엇일까요?

2023-12-13 02:20 UTC, yoruck2 commented on JuiceMaker/JuiceMaker/Controller/SecondViewController.swift
> +class SecondViewController: UIViewController, FruitStoreViewController {
의미가 포함된 이름으로 바꾸는게 좋겠네요 ! 참고 하겠습니다

2023-12-13 02:21 UTC, yoruck2 commented on JuiceMaker/JuiceMaker/Enums/ViewID.swift
> +}
하드코딩을 피하는 쪽으로 고민을 해봐야겠네요 ..🤔

2023-12-13 02:23 UTC, yoruck2 commented on JuiceMaker/JuiceMaker/Enums/Alert.swift
> +}
단순히 모달창을 띄우기 때문에 madal이라고 했습니다.. ㅎㅎ 다른 방식도 고민해 볼게요

2023-12-13 02:23 UTC, yoruck2 commented on JuiceMaker/JuiceMaker/Controller/FriutStoreViewController.swift
> +}
👍👍

2023-12-13 02:24 UTC, yoruck2 commented on JuiceMaker/JuiceMaker/Controller/FriutStoreViewController.swift
> +}
다시보니 불필요한 부분인것 같습니다 지워도 될 것 같네요..!

2023-12-15 02:27 UTC, jus1234 commented
@cherrishRed 레드! 리뷰 반영한 내용 다시 커밋 했습니다!
확인 부탁드려요~~

2023-12-15 18:18 UTC, cherrishRed approved these changes
두분 모두 수고하셨습니다!

네이밍을 많이 고민하셔서 바꾸신 흔적이 느껴졌습니다!
가독성이 훨씬 올라간 것 같네요!

`UIViewController` 의 extension을 활용하신 부분 잘 보았습니다!
범용성도 높아지고, 사용성이 많이 좋아진 것 같습니다 😆

approve 드립니다!

2023-12-18 01:57 UTC, merged