쥬스자판기[Step2] Asher, LJ
tasty-code/ios-juice-maker pull request #88
Opened 2023-12-12 07:06 UTC by ijs1103

@Mino777

리뷰어 : Mino777
버드 : 🕵🏻 애셔(Asher)@tawans , 🔥엘제이(LJ)@ijs1103

쥬스자판기 STEP.1 이후
쥬스자판기 STEP.2 에 대한 코드 구현을 하였습니다.

## 🤔고민하며 구현하려고 노력했던 점
### - Result Type의 활용
성공과 실패의 경우를 명시적으로 처리하고 Error 타입을 실패 케이스에서 사용하기 위해
Result Type을 활용하였습니다.
### - 과일의 상태값 갱신
쥬스 주문시 과일의 갯수를 바로 반영하여 보여주기위해
NotificationCenter를 활용하여 과일 수량 상태 업데이트를 하였습니다.
### - 화면 이동방식의 선택

#### Storyboard Segues:

```swift
performSegue(withIdentifier: "SegueIdentifier", sender: self)
```

장점
- 시각적 디자인: Interface Builder를 사용하여 시각적으로 화면 전환을 설계할 수 있어 직관적이고 빠르게 작업할 수 있습니다.
- 편리한 데이터 전달: 세그를 통해 데이터를 전달하기 위해 prepare(for:sender:) 메서드를 사용할 수 있어 편리합니다.

단점
- 재사용 어려움: 특히 큰 프로젝트에서는 세그의 재사용이 어려울 수 있습니다.
- 복잡한 로직: 복잡한 화면 전환 로직을 구현하기에는 한계가 있습니다.

#### 프로그래밍 방식으로 화면 전환:

```swift
if let nextViewController = storyboard?.instantiateViewController(withIdentifier: "ViewControllerID") as? ViewControllerClass {
    navigationController?.pushViewController(nextViewController, animated: true)
}
```

장점
- 재사용 가능: 화면 전환을 코드로 구현하면 재사용성이 높아집니다.
- 동적 로직: 복잡한 비즈니스 로직에 적합하며, 동적인 화면 전환을 수행할 수 있습니다.

단점
- 디자인적 한계: Interface Builder에서 시각적으로 디자인하는 것보다 코드로 화면을 전환하는 것은 디자인 측면에서 제한이 있을 수 있습니다.
- 가독성 감소: 코드로만 관리하면서 코드가 길어질수록 가독성이 감소할 수 있습니다.

#### Navigation Controller를 사용하지 않는 경우:

```swift
if let nextViewController = storyboard?.instantiateViewController(withIdentifier: "ViewControllerID") as? ViewControllerClass {
    present(nextViewController, animated: true, completion: nil)
}
```

장점
- 독립적인 화면 전환: Navigation Controller 없이도 화면을 전환할 수 있습니다.
- 유연한 구조: Navigation Controller에 의존하지 않으므로 더 유연한 앱 구조를 설계할 수 있습니다.

단점
- Navigation 기능 부재: Navigation Controller를 사용하지 않으면 스택 기반의 뒤로 가기(Back) 기능이 자동으로 지원되지 않습니다.
- UI 일관성 감소: Navigation Controller를 사용하지 않으면 iOS의 일반적인 UI 패턴에서 벗어나게 될 수 있습니다.

종합적으로 고려해야 할 사항:
프로젝트 규모 및 복잡성: 프로젝트의 규모와 복잡성에 따라 적절한 방식을 선택해야 합니다.
디자인 요구사항: 앱의 디자인 및 사용자 경험을 고려하여 시각적인 디자인이 중요하다면 Segues, 비즈니스 로직이 우선이라면 코드로의 화면 전환을 고려해야 합니다.
유지보수와 확장성: 재사용성과 유지보수성을 고려하여 각 방식의 장단점을 살펴보고 결정해야 합니다.

####  현재 STEP2 까지는 프로젝트 규모도 작고 화면 재사용성에 대해 크게 고려하지 않아도 된다고 판단하여서 Storyboard Segue 방식으로 구현했습니다.

## 🌝 진행하면서 궁금했던 점

### 싱글톤 vs 의존성 주입
fruitstore 객체를 싱글톤으로 사용하는게 좋을지 아니면 의존성 주입을 활용하는게 좋을지 고민이 되었고 관련해서 조사를 하게 되었습니다.
싱글톤 패턴은 사용하기 쉽지만 결합도를 높여, 하나의 모듈의 변경사항이 다른 모듈에 영향을 미칠 수 있다는 단점이 있어 의존성 주입을 구현하기로 하였습니다. 
의존성 주입은 STEP3가 끝나고 리팩토링을 하면서 적용하도록 하겠습니다.   

## ✍️ 진행하면서 학습한 내용

### 의존성주입

- 필요성
    
    A객체와 B객체는 서로 의존하는 관계라고 할때, B객체의 변화가 생기면 A객체도 영향을 받는다.
    
    이때,  B객체의 변화로 인하여 A객체도 함께 수정해주어야 하고 이는 재사용성을 떨어뜨리게 된다.
    
    이러한 문제를 해결하기 위해 나온것 개념이 DI(의존성 주입)이다.
    
- 의존 관계 역전의 원칙
    
    **객체에서 어떤 Class를 참조해서 사용해야하는 상황이 생긴다면, 그 Class를 직접 참조하는 것이 아니라 그 대상의 상위 요소(상위 클래스 혹은 프로토콜)로 참조하라는 원칙.**
    
    만약  A 객체가 B객체의 하위클래스 를 참조하고 있는 상황이라고 가정할 때, B객체의 상위클래스 혹은 프로토콜이 변경되면 A,B 객체 모두 변경해야해서 비교적 잦은 코드수정이 일어난다. 
    
- 얻을 수 있는 효과
    - 객체 합성
        
        기존의 코드는 최대한 변경하지 않고 객체를 원하는대로 합성할 수 있다. 즉, 새로운 요구사항이 발생하더라도 유연하게 대처를 할 수 있고 확장성을 높일 수 있다.
        
    - 객체 생애 관리
        
        의존성을 주입받은 객체는 의존성에 대한 생애관리를 할 수 없게 된다. 그렇게 되면, 생애관리를 개발자가 관리하게 되는데 오히려 좋다. 객체들의 메모리 해제시점, 객체들간의 관계를 일관적으로 관리할 수 있기 때문이다.강한 참조를 하게 되면 ARC에 의해서 메모리 해제가 되지 않기 때문에 생애관리를 컨트롤 할 수 있다. 아래와 같이 말이다.
        
        ```swift
        let authRepository: AuthenticationRepository = AuthenticationRepositoryImp()
        
        // 하나의 의존성 객체를 여러 소비자에게 주입
        let profileService: ProfileService = ProfileServiceImp(auth: authRepository)
        let feedService: FeedService = FeedServiceImp(auth: authRepository)
        ```
        
    - 가로채기
        
        의존성을 넘겨주기전에 조작을 가할 수 있고 이것을 실제로 구현한 디자인 패턴이 데코레이터 패턴이다.
        
        데코레이터 패턴을 사용하면 가로채기를 통해 단일책임원칙을 지킬 수 있다.
        
        예를 들어 앱의 API를 모니터링 해야하는 상황이 있다.
        
        이때, API 코드에 성능측정 코드를 추가적으로 작성하는것이 아니라, 모니터링을 담당하는 데코레이터를 만들어 서비스 로직과 성능측정 로직을 분리할 수 있다. 
        
        ```swift
        protocol PurchaseService {
          func purchase(_ productID: String) async throws
        }
        
        // 데코레이터 패턴으로 성능/에러 로깅 구현
        final class PurchaseServiceMonitoringDecorator: PurchaseService {
          private let decoratee: PurchaseService
          private let logger: AppAnalytics
          private let clock: any Clock
          
          func purchase(_ productID: String) async throws {
            do {
              let duration = try await clock.measure {
                try await self.decoratee.purchase(productID)
              }
              self.logger.log(AppEvent.purchase, [AppEvent.durationKey: duration])
            } catch {
              self.logger.logError(error)
              throw error
            }
          }
        }
        ```
        
    - 그외
        - mockup 객체를 생성하는데 유리하기 떄문에 Unit Test하기에 좋다
        - 객체간 의존성을 줄이고 결합도를 낮춘다
    
    참조 
    
    [💠 완벽하게 이해하는 DIP (의존 역전 원칙) (tistory.com)](https://inpa.tistory.com/entry/OOP-%F0%9F%92%A0-%EC%95%84%EC%A3%BC-%EC%89%BD%EA%B2%8C-%EC%9D%B4%ED%95%B4%ED%95%98%EB%8A%94-DIP-%EC%9D%98%EC%A1%B4-%EC%97%AD%EC%A0%84-%EC%9B%90%EC%B9%99)
    [(Swift) Dependency Injection, 의존성 주입이란? (feat. DIP) (oopy.io)](https://80000coding.oopy.io/68ee8d89-5d05-449d-87e2-5fba84d604ca)
    [의존성 주입을 하면 잃게 되는 것 · Soojin Ro](https://soojin.ro/blog/three-dimensions-of-di)

2023-12-13 07:42 UTC, Mino777 requested changes
안녕하세요!! Asher, LJ!

STEP 2 진행하시느라 정말 수고 많으셨습니다!!🥳

PR 메세지의 양과 질 너무너무 좋습니다!!
이렇게 최대한 많이 써주시면 하나라도 더 알려드리고 싶어지니 꼭 앞으로도 많이 많이 써주세요👏👏

---------------------------------------------------------------------------------------

## 코멘트

### 칭찬 드리고 싶은 점
- PR 메세지 신경쓰신 점👏
- AlertController를 사용해보신 점👏
- Result Type을 활용해보신 점👏
- NotificationCenter를 활용해보신 점👏
- 화면 이동 방식 선택에 대한 분석👏
- 의존성 주입에 대한 학습👏

---------------------------------------------------------------------------------------

### 고민했던점
> Result Type의 활용

Result Type을 활용 해보신점 너무 좋습니다! Result Type을 통해 성공 실패를 더 명확하게 처리할 수 있고 이에따라 가독성이나 유지보수성이 더욱 더 좋아질 수 있습니다.
하지만 만약에 흐름 제어가 너무 복잡해지는 경우 오히려 코드의 복잡성이 너무 커질 수 있습니다. 또 Result 타입의 경우 타입추론이 명확하지 않는 경우 의도치 않은 오류가 발생할 수 있으니 주의할 점에 대해 인지하시고, 모든 에러 처리 상황에 꼭 Result 타입을 사용해야지! 라고 생각하실 필요는 없으시다는 점 알고 계시면 좋을 것 같습니다🙌

> 과일의 상태값 갱신

개인적으로는 NotificationCenter를 통한 모델의 업데이트는 지양하는 편입니다.
NotificationCenter를 사용할 경우
- 디버깅이 어렵습니다.
- 해당 data의 flow를 추적하기가 어렵습니다.
- NotificationCenter를 위한 객체를 만들어서 이친구들을 최대한 관리한다 해도, 프로젝트의 복잡성이 높아지면 높아질수록 점점 더 관리가 어려워질꺼에요.

해당 부분에 대한 추가 코멘트는 코드 코멘트에도 달아놔서 참고 해주세요!

> 화면 이동 방식의 선택

와우 기술을 사용하기 전에 이런 분석 및 학습 너무너무 좋습니다💯💯👏👏👏
저같은 경우는 TMI이지만 회사나 개인적으로도 스토리보드를 사용하지도 않고 좋아하지도 않아서  프로그래밍 방식 전환만 사용합니다ㅎㅎ
앞으로도 기술을 선택하고 적용할 때 이런식으로 꼭 분석하고 적용하시는 습관을 들이시면 너무 좋습니다👍👍👍

------------------------------------------------------------------------------------

추가적으로 코드 코멘트들 중 디자인패턴 관련 챌린지 요청들은 모두 옵셔널입니다!
시간이 없으시다면 나중에 적용하셔도 무방하니, 전혀 부담갖지 마시고 스킵하셔도 됩니당~!

고생하셨어요!👏👏

2023-12-13 07:42 UTC, Mino777 commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +    private func openResultAlert(_ result: Result<Void, JuiceError>) {
보통 alert을 띄우는 메서드의 경우 show prefix를 많이 사용합니다.
open prefix의 경우 외부 앱, 웹사이트 리다이렉션할 때 많이 사용합니다.

요런 네이밍 관련 코멘트는 네이밍 규칙을 위배하지 않는 이상 요런식으로도 네이밍 한다~ 정도기에 꼭 수정하실 필요는 없습니다ㅎㅎ

2023-12-13 07:42 UTC, Mino777 commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +    @IBAction func StrawberryJuiceOrderButtonTapped(_ sender: UIButton) {
네이밍 좋습니다👍👍

2023-12-13 08:14 UTC, ijs1103 commented on JuiceMaker/JuiceMaker.xcodeproj/project.pbxproj
>  				C73DAF38255D0CDD00020D38 /* SceneDelegate.swift */,
넵 Application으로 그룹핑 하겠습니다

2023-12-13 08:15 UTC, ijs1103 commented on JuiceMaker/JuiceMaker.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 16.4;
실수로 건드린것 같습니다 ... ㅎㅎ 다시 복구하겠습니다

2023-12-13 08:21 UTC, tawans commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
>      let juiceMaker = JuiceMaker()
컨벤션으로 변수선언은  줄바꿈하지 않고 붙이기로 했어서요 
이때 저도 살짝 고민했었는데 일단 컨벤션 따라가야겠다 하고 붙였었습니다.
지금 보면서 생각해보니 아웃렛 변수와는 구분을 둬서 줄바꿈하는것이 가독성이나 구분감이 더 좋을 것 같은 생각이 들긴 합니다.

2023-12-13 08:22 UTC, ijs1103 commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
>      override func viewDidLoad() {
`super` 키워드는 상위클래스의 메서드를 오버라이딩하기 위해서 사용하는것으로 알고 있습니다.

2023-12-13 08:30 UTC, ijs1103 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
>      }
`Result` 타입은 열거형이며 `success`와 `failure` 두가지 `case`로 구성되어있습니다.
`failure` case의 연관값으로 에러를 넘겨주기 때문에 에러를 따로 `throw`할 필요가 없습니다.
나중에 네트워크 처리를 할때 자주 사용되는것으로 알고 있습니다.

2023-12-14 04:07 UTC, tawans commented on JuiceMaker/JuiceMaker.xcodeproj/project.pbxproj
>  				C73DAF38255D0CDD00020D38 /* SceneDelegate.swift */,
그룹핑 완료하였습니다.

2023-12-14 04:09 UTC, tawans commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
>      let juiceMaker = JuiceMaker()
아웃렛 변수와는 구분을 위해 줄바꿈 하였습니다.

2023-12-14 04:12 UTC, tawans commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +    private func openResultAlert(_ result: Result<Void, JuiceError>) {
그렇군요! show로 변경하였습니다. 앞으로 네이밍 시 참고하도록 하겠습니다.

2023-12-14 05:07 UTC, tawans commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +    }
```swift
    @IBAction func fruitJuiceOrderButtonTapped(_ sender: UIButton) {
        guard let title = sender.currentTitle else {
             return
         }
        
        switch title {
        case "딸기쥬스 주문":
            showResultAlert(juiceMaker.makeJuice(juiceMenu: .strawberry))
        case "바나나쥬스 주문":
            showResultAlert(juiceMaker.makeJuice(juiceMenu: .banana))
        case "파인애플쥬스 주문":
            showResultAlert(juiceMaker.makeJuice(juiceMenu: .pineapple))
        case "키위쥬스 주문":
            showResultAlert(juiceMaker.makeJuice(juiceMenu: .kiwi))
        case "망고쥬스 주문":
            showResultAlert(juiceMaker.makeJuice(juiceMenu: .mango))
        case "딸바쥬스 주문":
            showResultAlert(juiceMaker.makeJuice(juiceMenu: .straberryBanana))
        case "망키쥬스 주문":
            showResultAlert(juiceMaker.makeJuice(juiceMenu: .mangoKiwi))
        default:
            showResultAlert(.failure(JuiceError.unknown))
        }
    }
```

하나의 IBAction func로 통합하였습니다..!

2023-12-14 05:21 UTC, tawans commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +        }
해당 부분 알럿창 띄우는 코드 넣어놨습니다..!

2023-12-14 05:33 UTC, tawans commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +        mangoQuantity.text = String(mango)
네 해당 로직들 별도의 메서드들로 분리하였습니다..!

2023-12-14 06:07 UTC, ijs1103 commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
>      }
말씀하신대로 UIAlertController에 Builder Pattern 적용 하였습니다. 적용해보니 재사용성과 코드가 간결해지는것은 확실히 체감이 되는데 혹시 성능적인면에서 향상되는 부분이 있을까요?

2023-12-14 07:02 UTC, tawans commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
>          guard let strawberry = allFruitQuantity[.strawberry] else {
# 공부한 내용 공유

## 세 가지 패턴이 나오게 된 배경

> 하나의 객체가 다른 객체와 **소통**은 하지만 **묶이기(coupled)는 싫을 때**

세 패턴 모두 특정 이벤트가 일어나면 원하는 객체에 알려주어 해당되는 처리를 하는 방법을 가지고 있다.

어플리케이션의 특성상 객체 간 소통은 필수적이다. 하지만 한 객체는 그 자체로 존재하면서 소통하고 싶을뿐 다른 객체에 종속되어 동작하는 것은 **‘재사용성’**과 **‘독립된 기능요소’** 측면에서 볼 때 바람직하지 않다. 대표적으로 ViewController는 한 View를 관리하는 독립적인 객체로서 존재해야지 소통을 위해 다른 ViewController에 묶여 동작하는 것은 옳지 않은 방식이다.

**특정 이벤트가 일어나면 원하는 객체에 알려주어 적절한 조치를 취하도록 한다** 
즉, **객체 간의 소통**을 위해 사용되는 것.

Delegation

Delegate는 보통 Protocol을 정의하여 사용한다. Protocol이란 일종의 기능 명세서 같은 것으로 Delegate로 지정된 객체가 해야 하는 메소드들의 원형을 적어 놓는다. Delegate 역할을 하려는 객체는 이 Protocol을 따르며 원형만 있던 메소드들의 구현을 한다. 이렇게 세팅 후 이전 객체는 어떤 이벤트가 일어났을 시 delegate로 지정한 객체에 알려줄 수 있다.

장점

- 매우 엄격한 Syntax로 인해 프로토콜에 필요한 메소드들이 명확하게 명시됨.
- 컴파일 시 경고나 에러가 떠서 프로토콜의 구현되지 않은 메소드를 알려줌.
- 로직의 흐름을 따라가기 쉬움.
- 프로토콜 메소드로 알려주는 것뿐만이 아니라 정보를 받을 수 있음.
- 커뮤니케이션 과정을 유지하고 모니터링하는 제 3의 객체(ex: NotificationCenter 같은 외부 객체)가 필요없음.
- 프로토콜이 컨트롤러의 범위 안에서 정의됨.

단점

- 많은 줄의 코드가 필요.
- delegate 설정에 nil이 들어가지 않게 주의해야함. 크래시를 일으킬 수 있음.
- 많은 객체들에게 이벤트를 알려주는 것이 어렵고 비효율적임.(가능은 하지만)

## Notification

Notification Center라는 싱글턴 객체를 통해서 이벤트들의 발생 여부를 옵저버를 등록한 객체들에게 Notification을 post하는 방식으로 사용한다. Notification name이라는 key 값을 통해 보내고 받을 수 있다.

장점

- 많은 줄의 코드가 필요없이 쉽게 구현이 가능.
- 다수의 객체들에게 동시에 이벤트의 발생을 알려줄 수 있음.
- Notification과 관련된 정보를 Any? 타입의 object, [AnyHashable: Any]? 타입의 userInfo로 전달할 수 있음.

단점

- key 값으로 Notification의 이름과 userInfo를 서로 맞추기 때문에 컴파일 시 구독이 잘 되고 있는지, 올바르게 userInfo의 value를 받아오는지 체크가 불가능함.
- 추적이 쉽지 않을 수 있음.
- Notificaiton post 이후 정보를 받을 수 없음.

## Key Value Observing

KVO는 A 객체에서 B 객체의 프로퍼티가 변화됨을 감지할 수 있는 패턴이다. 위의 두 패턴이 주로 Controller와 다른 객체 사이의 관계를 다룬다면 KVO 패턴은 객체와 객체 사이의 관계를 다루는데 적합하다. (물론 다룰수야 있다.) 메소드나 다른 액션에서 나타나는 것이 아니라 프로퍼티의 상태에 반응하는 형태이다.

장점

- 두 객체 사이의 정보를 맞춰주는 것이 쉬움.
- new/old value를 쉽게 얻을 수 있음.
- key path로 옵저빙하기 때문에 nested objects도 옵저빙이 가능함.

단점

- NSObject를 상속받는 객체에서만 사용이 가능함.
- dealloc될 때 옵저버를 지워줘야 함.
- 많은 value를 감지할 때는 많은 조건문이 필요.

##결론 : 느슨한 결합, 로직의 흐름을 확인하기 편함(가독성), 재사용성, 제3의 객체를 사용하지 않는점의 장점으로
해당 프로젝트에서는 Delegate 대리자 패턴을 사용하여 리팩토링 해보았습니다.
아직 확실하게 100% 이해하진 못헤서 앞으로 각자의 패턴 장단점을 고려하여 더 공부해보겠습니다.

2023-12-14 07:51 UTC, Mino777 commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
>          guard let strawberry = allFruitQuantity[.strawberry] else {
크 정리하고 공유하시는 습관 너무 좋습니다!! 이런 정리들이 모이면 나중에 정말 어마어마한 자산이 되실꺼에요👍👍

2023-12-14 08:35 UTC, Mino777 approved these changes
요청드린 부분들을 모두 잘 적용해주셨네요...!! 진짜 대단하십니다👍👍

Step2도 정말 고생많으셨어요!!
이번에 남겨드린 피드백 부분들은 다음 스텝에 적용해주시면 될 것 같습니다ㅎㅎ

꼭 학습하신 부분들 복습하시고, 지금처럼 정리하고 공유하시는 습관 쭈욱 이어나가셨으면 좋겠습니다👏👏👏

Step3도 빠이팅입니다!!💪💪💪

2023-12-14 08:35 UTC, Mino777 commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +    weak var juiceMadeDelegate: JuiceMadeDelegate?
delegate pattern을 사용해보셨군요! 좋습니다👍👍

weak 키워드의 경우엔 어떨때 사용할까요?
weak 키워드를 쓰지 않으면 어떤 문제가 발생할까요?

2023-12-14 08:35 UTC, Mino777 commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +                AlertBuilder(vc: self).addAction("확인", style: .default).addMessage(title:"유효하지 않은 레시피", message: "주문할 수 없는 쥬스입니다.", style: .alert)
builder pattern을 사용해보셨네요!! 좋습니다👍👍

디자인 패턴의 경우 많은 개발자들이 어떤 문제에 대해 공감하고, 그 문제를 풀어내기 위해 만든것들이기 때문에
하나하나씩 공부해보시면 도움이 많이 되실겁니다🙌

그리고, 이렇게 체이닝이나 파라미터가 많은 경우 줄바꿈을 해주시면 가독성이 올라갑니다!
```swift
AlertBuilder(vc: self)
  .addAction("확인", style: .default)
  .addMessage(
    title:"알 수 없는 에러",
    message: "에러가 발생하였습니다.",
    style: .alert
  )
```

2023-12-14 08:35 UTC, Mino777 commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +    }
리팩토링 잘 진행해주셨네요! 좋습니다👍

그런데, sender의 title에 의존하는 부분은 조금 위험한 것 같습니다.
title의 경우 기획에 의해 변경될 수 있고 변경되도 컴파일단에는 에러가 나지 않기 때문에

조금 귀찮으시겠지만, UIButton 객체 자체에 의존해서 분기를 진행하는것이 조금이나마 안전해보입니다!

```swift
@IBOutlet weak var strawberryJuiceOrderButton: UIButton!

...

  @IBAction func fruitJuiceOrderButtonTapped(_ sender: UIButton) {
    switch sender {
    case strawberryJuiceOrderButton:
      showResultAlert(juiceMaker.makeJuice(juiceMenu: .strawberry))
    default:
      showResultAlert(.failure(JuiceError.unknown))
    }
  }


```

2023-12-14 08:35 UTC, Mino777 commented on JuiceMaker/JuiceMaker/Utils/AlertBuilder.swift
크.. 빌더 패턴에 순환참조 방지까지! 너무 좋아요👍

2023-12-14 08:35 UTC, Mino777 commented on JuiceMaker/JuiceMaker/Utils/AlertBuilder.swift
> +    }
약어는 최대한 지양하는게 좋습니다!

2023-12-14 08:38 UTC, Mino777 commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
>      }
Builder Pattern의 궁극적인 목적은 코드의 명확성과 유지보수성 향상이라고 생각합니다.
성능적인면에서는 글쎄요,, 제가 생각했을때는 혹시라도 있더라도 정말 미미할거라 생각이 듭니다ㅎㅎ

2023-12-14 08:46 UTC, merged

2023-12-15 00:56 UTC, ijs1103 commented on JuiceMaker/JuiceMaker/Utils/AlertBuilder.swift
> +    }
넵 viewController로 수정하겠습니다

2023-12-15 01:18 UTC, ijs1103 commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +    weak var juiceMadeDelegate: JuiceMadeDelegate?
`weak` 키워드를 사용하면 가리키는 인스턴스의 `retain count`를 올라가지 않게됨으로써, 두개의 객체가 서로 참조를 할때 메모리에서 해제되지 않는 비정상적인 상황인 `강한 참조 순환`을 방지하기 위해서 사용합니다.
또한, `delegate` 패턴에서 자주 사용됩니다.
`weak`가 가리키는 인스턴스가 메모리에서 해제되면 `nil`로 할당되기 때문에 반드시 `optional`타입이 되어야 합니다.

2023-12-15 01:20 UTC, ijs1103 commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +                AlertBuilder(vc: self).addAction("확인", style: .default).addMessage(title:"유효하지 않은 레시피", message: "주문할 수 없는 쥬스입니다.", style: .alert)
넵 줄바꿈 수정하겠습니다ㅎ