쥬스자판기 [Step 2] 댄, 라마
tasty-code/ios-juice-maker pull request #89
Opened 2023-12-12 07:55 UTC by eensungkim

Step 2
멤버 : @eensungkim, @llamang
리뷰어 : @minsson

쥬스 자판기 프로젝트의 두번째 Step입니다! 
정리하여 PR 드립니다. 감사합니다!

# 리뷰 반영사항
## FruitStore.swift
- consume : 여러 과일을 활용할 때, 내부 로직 오류를 수정했습니다. 쥬스 만들기에 필요한 여러 과일의 재고 중에 일부만 부족한 경우에, 과일의 개수를 바로 변경하지 않고 오류가 발생하도록 했습니다.
- supply : Step 3 기능 구현 시 활용할 것으로 예상합니다.

# Step 2 구현내용
## JuiceViewController.swift
쥬스 주문 화면과 연동되어 있습니다.

### proprerty
- fruitStore : 싱글턴 패턴을 활용하여 FruitStore 에 접근합니다.

### methods
- showFruitsCount : 과일의 재고를 IBOutlet 변수와 연결해 줍니다.
- orderJuice : menu를 전달인자로 받아 쥬스 만들기를 시도하고, 성공 또는 실패에 따라 alert 을 띄웁니다.
- showNavigationView : 네비게이션뷰 컨트롤러를 활용하여 재고수정 화면으로 이동합니다.
- alertJuiceServed : 쥬스 만들기에 성공한 경우 alert 메시지를 띄웁니다.
- alertInsufficientStock : 쥬스 만들기에 실패한 경우 재고 수정 화면으로 바로 이동할지 여부를 물어보는 alert 를 띄웁니다.

## SupplyViewController.swift
재고 수정 화면과 연동되어 있습니다.
- showFruitsCount : 과일의 재고를 IBOutlet 변수와 연결해 줍니다.
- Step2 기능 구현 가이드에 따라 +/- 버튼과 연동하는 부분은 미구현 상태로 두었습니다.

# 질문
- 댄 : IBOutlet, IBAction 등을 활용해 레이블 또는 버튼과 연결해줄 때, 변수(또는 함수)가 버튼(또는 레이블)과 1:1로 대응되도록 구현하는 편이 좋은 것일까요? 비슷한 동작을 하는 변수(또는 함수)를 여러 개 생성해주는 것이 약간 낯설게 느껴져서 여쭤봅니다.

```swift
@IBAction private func orderStrawberryJuice(_ sender: Any) {
    orderJuice(menu: .딸기쥬스)
}
    
@IBAction private func orderBananaJuice(_ sender: Any) {
    orderJuice(menu: .바나나쥬스)
}

@IBAction private func orderPineappleJuice(_ sender: Any) {
    orderJuice(menu: .파인애플쥬스)
}
```

2023-12-13 11:49 UTC, minsson requested changes
안녕하세요, 댄, 라마!
Step 2 수행하시느라 고생하셨어요. 👏👏👏

깔끔하게 잘 구현해주셔서 전반적으로 이해하기 쉬워서 좋았어요! 또, 접근제어자를 무척 잘 활용해주신 점도 좋았어요. 더 안전한 코드가 될 뿐만 아니라, 변수나 메서드가 어떤 용도로 사용되는지 쉽게 이해할 수 있었어요.

구체적인 피드백은 코드에 코멘트로 달아두었으니 참고 부탁드려요.

### 질문에 대한 답변
#### 질문 1
> 댄 : IBOutlet, IBAction 등을 활용해 레이블 또는 버튼과 연결해줄 때, 변수(또는 함수)가 버튼(또는 레이블)과 1:1로 대응되도록 구현하는 편이 좋은 것일까요? 비슷한 동작을 하는 변수(또는 함수)를 여러 개 생성해주는 것이 약간 낯설게 느껴져서 여쭤봅니다.

```swift
@IBAction private func orderStrawberryJuice(_ sender: Any) {
    orderJuice(menu: .딸기쥬스)
}
    
@IBAction private func orderBananaJuice(_ sender: Any) {
    orderJuice(menu: .바나나쥬스)
}

@IBAction private func orderPineappleJuice(_ sender: Any) {
    orderJuice(menu: .파인애플쥬스)
}
```

답변부터 드리자면, IBAction 메서드의 sender를 통해 sender의 정보를 파악하는 방법이 있어요. 다만 현재 구현에서는 sender를 Any로 선택하셔서 원하는 정보에 접근하려면 타입 캐스팅이 필요해요. sender를 UIButton으로 택하시면 타입캐스팅 없이도 sender의 여러 프로퍼티에 접근할 수 있어요. 그 중에서 마음에 드는 걸 찾아보시면 좋을 것 같아요. 아니면 아예 다른 방법이 있을지도 모르겠네요!

제 개인적인 의견을 드리자면, 지금의 구현 방법이 오히려 더 좋을 수도 있다고 생각해요. 코드가 길어지고, 중복되는 단점이 있지만, 더 명확하고 직관적이고, 유지보수하면서 혼동할 여지도 적다고 봐요. 의도한 중복이라면, 중복을 무조건 나쁘게 생각할 필요는 없다고 생각해요.

댄과 라마가 불편하신 점을 해소해보시고, 장단점을 비교해보시면 좋을 것 같아요!

2023-12-13 11:49 UTC, minsson commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func supply(fruitName: Fruit, amount: Int) throws {
supply fruitName 보다는 supply fruit이 더 자연스럽게 읽힐 것 같아요.
열거형 이름도 Fruit이고요.

2023-12-13 11:49 UTC, minsson commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        guard let currentStock = storage[fruitName], (currentStock + amount) >= 0 else {
개행을 하면 가독성이 더 좋아질 것 같아요.

2023-12-13 11:49 UTC, minsson commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +            guard let currentStock = storage[fruitName], amount <= currentStock else {
개행을 하면 가독성이 더 좋아질 것 같아요.

2023-12-13 11:49 UTC, minsson commented on JuiceMaker/JuiceMaker/Controller/JuiceViewController.swift
> +    @IBOutlet private weak var mangoCount: UILabel!
`bananaCountLabel`과 같이, UI 요소의 경우 타입 이름을 같이 붙여주면 가독성을 높일 수 있어요.
예를 들어 bananaCount라면 Int 타입과 혼동하는 등, 일반 변수들과 헷갈릴 수 있어요.

2023-12-13 11:49 UTC, minsson commented on JuiceMaker/JuiceMaker/Controller/JuiceViewController.swift
> +    }
이 메서드를 비롯한 다른 order{Fruit}Juice 형태의 메서드들에 대한 이야기인데, 코드만 봐서는 어떤 버튼이 눌려야 메서드가 실행되는지 알기 어려울 것 같아요. 물론 지금은 앱의 기능이 단순하니 추론해낼 수 있겠지만요. 미래의 자신을 포함해, 누군가 코드를 읽을 때 최대한 읽기 편하게 만들어주는 게 중요해요. 그런 의미에서 어떤 버튼이 눌렸을 때 이 메서드가 호출되는 건지 알기 쉽게 만들 수 있을까요? 

'아, 이 버튼이 눌리면 `orderJuice(menu: .파인애플쥬스)`가 실행되는구나!' 라고 생각할 수 있으면 좋을 것 같아요.

2023-12-13 11:49 UTC, minsson commented on JuiceMaker/JuiceMaker/Controller/JuiceViewController.swift
> +    }
`showFruitsCount`라는 네이밍을 보면 뭔가 Alert이 뜨거나, 안 보이던 UI가 새로 나타나면서 뭔가를 보여줄 것 같은 느낌이 들어요. 이 메서드의 역할을 바탕으로 더 직관적인 네이밍으로 바꿔주실 수 있나요?

2023-12-13 11:49 UTC, minsson commented on JuiceMaker/JuiceMaker/Controller/JuiceViewController.swift
> +    }
이 메서드도 다른 IBAction 메서드들과 동일한 피드백이 적용돼요.

2023-12-13 11:49 UTC, minsson commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    static let shared = FruitStore()
싱글톤 객체로 만들어주셨군요! 아래에서 init 함수까지 private하게 만들어주셔서 좋은 싱글톤 객체가 되었어요.
- 싱글톤 패턴이 무엇인가요? 
- 싱글톤 패턴에는 어떤 장단점이 있을까요?
- 이번 프로젝트에서 싱글톤 패턴을 사용한 이유가 무엇인가요?

2023-12-13 11:49 UTC, minsson commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
>      }
init 함수 내부의 코드를 메서드로 분리하면 어떨까요?

2023-12-13 11:49 UTC, minsson commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +            throw StorageError.insufficientStock
supply를 하는데 insufficientStock이라는 에러가 발생하는 게 어색하게 느껴져요.

2023-12-15 01:31 UTC, eensungkim commented on JuiceMaker/JuiceMaker/Controller/JuiceViewController.swift
> +}
### 피드백 1에 대한 답변
- NSLocalizedString은 사용자의 언어 환경에 맞춰서 변환된 문자열을 돌려줄 수 있도록 하는 기능을 가지고 있습니다.
- alert 공식문서 예시에서 NSLocalizedString을 활용하고 있어서 가져와서 활용했던 부분이었구요. 위와 같은 기능을 가지고 있는지는  이번에 짚어주셔서 알게 되었습니다! 이번 프로젝트에서는 그냥 문자열을 바로 활용하는 쪽으로 변경하려고 합니다!

2023-12-15 01:31 UTC, eensungkim commented on JuiceMaker/JuiceMaker/Controller/JuiceViewController.swift
> +    }
위치를 조정하도록 하겠습니다!

2023-12-15 01:32 UTC, eensungkim commented on JuiceMaker/JuiceMaker/Controller/JuiceViewController.swift
> +        let supplyVC = storyboard?.instantiateViewController(withIdentifier: "SupplyViewController") as! SupplyViewController
축약어를 가능한 사용하지 않는 쪽으로 진행해 보겠습니다.

2023-12-15 01:37 UTC, eensungkim commented on JuiceMaker/JuiceMaker/Controller/JuiceViewController.swift
> +    @IBOutlet private weak var mangoCount: UILabel!
안그래도 코드를 작성할때 말씀해주신 부분 관련해서 무엇이 더 나은지에 대해 고민이 있었는데요.
대중적으로 받아들여지는 컨벤션이 무엇인지 몰라서 일단은 짧은 쪽으로 선택했었습니다.
outlet, action 네이밍들을 의견주신 방향으로 수정할 예정입니다!

2023-12-15 01:38 UTC, eensungkim commented on JuiceMaker/JuiceMaker/Controller/JuiceViewController.swift
> +    }
"버튼이 탭되었을 때" 라는 표현을 네이밍에 반영하는 쪽으로 수정할 예정입니다!

2023-12-15 01:41 UTC, eensungkim commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +            throw StorageError.insufficientStock
메서드 로직이 재고를 줄이거나 늘릴 수 있는 방식으로 변경되었으니, 여기에 맞게 이름을 변경해 줄 예정입니다.

2023-12-15 02:12 UTC, eensungkim commented on JuiceMaker/JuiceMaker/Controller/JuiceViewController.swift
> +    }
- 알고는 있었습니다!
- [애플 개발자 포럼에서 찾은 내용](https://developer.apple.com/forums/thread/107239)에 보면 누가 액션을 실행했는지를 더 명확하게 확인하고 싶다면 UIButton 을 활용하라는 의견이 있더라구요. 동작 자체에는 크게 차이가 없겠지만 다른 개발자가 실수로 버튼이 아닌 다른 view 와 연결하는 것을 막을 수 있을 거라고 생각해서, UIButton 으로 변경하는 방향으로 수정했습니다.
- 공식문서를 참고하고 싶었는데 `IBAction swift documentation` 키워드로는 특별히 문서를 찾지 못해서 개발자 포럼 내용을 참고했습니다. 🙏

2023-12-15 02:44 UTC, llamang commented on JuiceMaker/JuiceMaker/Controller/JuiceViewController.swift
> +    }
**showFruitsCount**를 **reloadFruitsCount**로 변경했습니다.
7b27cf398dd0f415fffb4937a24e45d2412a4f68
73c7803bee66a47c1a738f8634e625c5049c2127

2023-12-15 02:46 UTC, llamang commented on JuiceMaker/JuiceMaker/Controller/JuiceViewController.swift
> +    }
**adjustStock**를  **adjustingStockButtonTapped**로 변경했습니다.
7b27cf398dd0f415fffb4937a24e45d2412a4f68

2023-12-15 02:47 UTC, llamang commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
>      }
init() 메서드의 내부 구현 코드를 **setUpInitialFruitsStock** 메서드로 분리했습니다.
0c79cfa95e95f3c176d1a34966adc4f7dba0b611

2023-12-15 02:47 UTC, eensungkim commented on JuiceMaker/JuiceMaker/Controller/JuiceViewController.swift
> +    }
- 모달을 활용해서 이동하는 방식이 있을 것 같습니다.
  - 내비게이션 방식 : 화면 간의 계층을 보여주고 이동이 용이
  - 모달 방식 : 프로그램의 주 흐름과 관련 없는 임시적인 내용을 보여주기에 용이
- Step 3의 요구사항이 모달 방식에 가깝다고 판단되어 Step3에서 모달을 활용하는 쪽으로 가닥을 잡을 예정입니다.

2023-12-15 02:56 UTC, llamang commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +            throw StorageError.insufficientStock
해당 메서드는 재고의 증가 또는 감소할 수 있도록 구현되었습니다. 
그래서 **supply** 대신에 **adjustStock**으로 변경했습니다.
7b27cf398dd0f415fffb4937a24e45d2412a4f68

2023-12-15 02:56 UTC, llamang commented on JuiceMaker/JuiceMaker/Controller/JuiceViewController.swift
> +    }
7b27cf398dd0f415fffb4937a24e45d2412a4f68

2023-12-15 02:57 UTC, llamang commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func supply(fruitName: Fruit, amount: Int) throws {
**fruitName**을 **fruit**으로 수정했습니다.
7b27cf398dd0f415fffb4937a24e45d2412a4f68

2023-12-15 02:58 UTC, llamang commented on JuiceMaker/JuiceMaker/Controller/JuiceViewController.swift
> +    @IBOutlet private weak var mangoCount: UILabel!
7b27cf398dd0f415fffb4937a24e45d2412a4f68

2023-12-15 02:59 UTC, llamang commented on JuiceMaker/JuiceMaker/Controller/JuiceViewController.swift
> +    }
다음과 같은 방식으로 변경했습니다.
**orderPineappleJuice** -> **pineappleJuiceButtonTapped**
7b27cf398dd0f415fffb4937a24e45d2412a4f68

2023-12-15 07:07 UTC, llamang commented on JuiceMaker/JuiceMaker/Controller/SupplyViewController.swift
> +        mangoCount.text = fruitStore.storage[.mango]?.description
`String()`와 [[description](https://developer.apple.com/documentation/swift/int/description)](https://developer.apple.com/documentation/swift/int/description)은 Swift에서 `Int`를 `String`으로 변환하는 데 사용할 수 있으며 둘 다 동일한 결과를 제공하지만, 둘 사이에는 차이점이 있습니다.

- `String()`는 더 간단하며 단순히 숫자를 문자열로 변환하려고 할 때 일반적으로 사용됩니다.
- `.description`은 `CustomStringConvertible` 프로토콜의 일부입니다. 이는 `Int`뿐만 아니라 이 프로토콜을 준수하는 모든 유형과 함께 사용할 수 있음을 의미합니다.

일반적으로 `Int`를 `String`으로 변환하는 경우 `String()`이 더 일반적인 접근 방식입니다. 

`CustomStringConvertible`을 준수하는 사용자 정의 유형으로 작업하거나, 코드를 보다 유연하게 만들고 `description`을 제공할 수 있는 모든 유형에서 작동하도록 하려면 `.description`이 더 나은 선택일 수 있습니다. 

> `.description`을 선택하신 이유는 무엇인가요?
> 

Int 타입에 `.description`을 사용하면, 해당 `Int` 타입의 값을 그대로 `String` 값으로 변환하기 때문에 사용했습니다. 여기서의 결과는 `String()`과 완전히 동일합니다.

하지만 만약 해당 타입이 `Int`가 아닌 사용자 정의 유형이고 `CustomStringConvertible`을 준수하여 원하는 `String` 값으로 변환하도록 했다면, `String()`을 사용하는 것보다 더 유연하게 사용할 수 있을 것 같습니다.

2023-12-15 07:20 UTC, llamang commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    static let shared = FruitStore()
싱글톤 패턴은 클래스에 인스턴스가 하나만 있도록 보장하고 해당 인스턴스에 대한 전역 액세스 지점을 제공합니다.

장점

- 글로벌 접근성: 싱글톤 인스턴스는 애플리케이션 내 어디에서나 액세스할 수 있으므로 리소스 공유 및 중앙 집중식 데이터 관리가 편리합니다.

단점

- 긴밀한 결합: 싱글톤을 과도하게 사용하면 클래스 간에 긴밀한 결합이 발생하여 코드베이스를 테스트하고 유지 관리하기가 어려워질 수 있습니다.
- 전역 상태: 싱글톤은 의도하지 않은 부작용을 일으키고 디버깅을 복잡하게 만들 수 있는 전역 상태를 사용합니다.

[Managing a Shared Resource Using a Singleton](https://developer.apple.com/documentation/swift/managing-a-shared-resource-using-a-singleton)
[Singleton vs Dependency Injection in iOS Swift](https://medium.com/@ranga.c222/singleton-vs-dependency-injection-in-ios-swift-47a056a822f)


> 이번 프로젝트에서 싱글톤 패턴을 사용한 이유가 무엇인가요?
> 

과일 쥬스 주문 화면과 재고 수정 화면 사이에 데이터를 공유해야 했습니다. 

싱글톤 패턴의 장점인 “글로벌 접근성”뿐만 아니라 각 ViewController에서 해당 공유 데이터에 쉽게 접근할 수 있어서 선택했습니다.

2023-12-18 00:58 UTC, minsson commented on JuiceMaker/JuiceMaker/Controller/JuiceViewController.swift
> +    }
제 개인적인 생각으로는 PineappleJuiceOrderButtonTapped처럼 '주문' 버튼이라는 점을 넣어도 좋을 것 같아요.

2023-12-18 12:48 UTC, minsson commented on JuiceMaker/JuiceMaker/Controller/SupplyViewController.swift
> +        mangoCount.text = fruitStore.storage[.mango]?.description
넵, 그리고 링크 걸어주신 [CustomStringConvertible](https://developer.apple.com/documentation/swift/customstringconvertible)을 보면 아래와 같은 설명이 나와 있네요! 

> CustomStringConvertible 프로토콜을 준수하는 형은 인스턴스를 문자열로 변환할 때 사용할 자체 표현을 제공할 수 있습니다. String(describing:) 이니셜라이저는 모든 유형의 인스턴스를 문자열로 변환하는 데 선호되는 방법입니다. 전달된 인스턴스가 CustomStringConvertible을 준수하는 경우, String(describing:) 이니셜라이저와 print(_:) 함수는 인스턴스의 사용자 정의 설명 프로퍼티를 사용합니다.

>타입의 설명 프로퍼티에 직접 액세스하거나 일반 제약 조건으로 CustomStringConvertible을 사용하는 것은 권장하지 않습니다.

2023-12-18 12:50 UTC, minsson commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    static let shared = FruitStore()
넵, 이번 프로젝트에서는 싱글톤의 장점을 잘 느껴보시고, 다음 프로젝트에서 `의존성 주입`이라는 키워드도 한번 살펴보시면 좋을 것 같아요. 다만 종종 싱글톤은 무조건 안티패턴이라는 글들이 보일 수 있는데, 말씀해주신 것처럼 장단점이 있으니 여러모로 활용해보시며 장점, 단점을 골고루 겪어보셨으면 좋겠어요.

2023-12-18 12:52 UTC, minsson commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +            throw StorageError.insufficientStock
제 개인적인 생각에는 `adjust`도 좋지만, `update`도 고려해보시면 좋을 것 같아요. 정확히 뜻을 맞춘다는 느낌보다는, 여러 개발자들이 대중적으로 사용하는 네이밍을 선택하다는 측면에서요.

2023-12-18 12:54 UTC, merged