쥬스 자판기 [STEP2] Jane, Harry
tasty-code/ios-juice-maker pull request #90
Opened 2023-12-13 10:16 UTC by hemil0102

@junbangg

안녕하세요~ 알라딘! Jane, Harry입니다! 
STEP2 PR을 드리며 바쁘신 와중에 리뷰해주셔서 감사드려요!
조언, 제안 모두 언제나 환영합니다!

## 🔍 What is this PR?

STEP 2의 기능을 구현했습니다.

- 재고 관리 화면 기능 및 오토 레이아웃 구현
- 재고 관리 화면 스태퍼 기능 구현
- 쥬스 제조 및 재고 부족 시 얼럿 구현

## 📝 PR Point

### 의존성 개선  - `Singleton`

기존 Step1에서 싱글톤 방식으로 구현한 FruitStore()을 의존성을 외부에서 주입하는 방식으로 변경 해주었습니다. 

기존

```swift
private var fruitStore = FruitStore.shared
private let juiceMaker = JuiceMaker()
```

변경 이후

```swift
private var fruitStore: FruitStore
private let juiceMaker: JuiceMaker

required init?(coder aDecoder: NSCoder) {
        self.fruitStore = FruitStore.shared
        self.juiceMaker = JuiceMaker()
        super.init(coder: aDecoder)
}
```

### 초기 화면 - **쥬스 제조 완료시 alert 표시**

`UIViewController + Extension` 내부에서 구현한 `presentAlert()` 메서드를 `UIAlertController`를 활용하여 구현 해주었습니다. 이후 `OrderViewController`내부 `tapMakeJuiceButton()`에서 `do-catch`문 내의 `juice.makeJuice()` 메서드로 쥬스를 제조합니다. 제조에 성공한다면 `presentAlert()`를 통해 완료 얼럿을 표시합니다.

### 초기 화면 - 재고 부족시 **alert 표시**

`UIViewController + Extension` 내부에서 구현한 `presentAlertCancel()` 메서드를 `UIAlertController` 통하여 구현을 해주었습니다. 재고가 부족하다면, 예 버튼을 통해 재고수정 화면으로 이동이 필요하며, 아니오 버튼을 통해서 수정을 하지 않습니다. 쥬즈 제조 얼럿과 달리 `Cancel(아니오)`에 해당하는 버튼이 추가되므로 별도의 `presentAlertCancel()` 메서드를 만들어 주었으며, confirmAction과 cancelAction을 통해서 예와 아니오의 기능을 handler를 통해 수행합니다.  

`예`를 누를 경우 메서드 내부 `confirmAction` 파라미터를 통해 `handler`의 액션을 수행해줍니다. `pushInventoryViewController()` 메서드에 네비 화면 전환 기능을 구현하였고, 클로저 형태로 파라미터에 전달하여 화면 전환을 수행합니다. 

`아니오`를 누를 경우에는 화면전환으르 하지 않으므로 함수에서 지정한 기본값 nil로 아무런 기능 수행을 하지 않습니다.

### 재고관리화면 - Label, Stepper

개별적으로 선언한 `Label`, `Stepper`의 `@IBOutlet`을 각각으로 관리한다면 가독성은 좋지만 개별 처리로 인해 중복되는 코드로 코드가 길어집니다. 이를 가독성과 중복 처리 방지를 위해서 `딕셔너리 타입`으로 `componentsByFruit`와 `fruitElementsByStepper`을 만들어주어 키에 해당하는 요소들에 접근하여 로직을 수행하도록 만들어 주었습니다. 

이후 `configureUI()` 메서드를 통해서 싱글톤으로 공유된 데이터를 Label과 연동하고, Stepper의 초기값도 지정하였습니다. 

### 재고관리화면 - Stepper 이벤트 처리

`@IBAction func tapStepper()`에 모든 Stepper를 연결하여 이벤트를 처리합니다. 사용자가 Stepper의 버튼을 터치할 경우 sender가 fruitElementsByStepper[sender] 딕셔너리 키로 사용되어 눌려진 Stepper가 어떤 과일에 해당하는지 알아냅니다. 이후 `updateFruitQuantity(sender, fruit)` 메서드를 통해서 Label ㅠ표시 및 데이터(싱글톤)에 해당하는 과일의 수량을 업데이트 합니다. 

## **+** 질문 및 고민한 부분

**From. Harry(@hemil0102)**

1. Juice 열거형 내부에 rawValue 처리를 아래 코드와 같이 연산 프로퍼티로 접근하게 만들어주었습니다. 말씀해주신게 이 방향이 맞을까요?

```swift
enum Juice: String {
    case strawberry = "딸기쥬스 주문"
    case banana = "바나나쥬스 주문"
    case kiwi = "키위쥬스 주문"
    case pineapple = "파인애플쥬스 주문"
    case strawberryBanana = "딸바쥬스 주문"
    case mango = "망고쥬스 주문"
    case mangoKiwi = "망키쥬스 주문"
    
    var description: String {
        return rawValue
    }
```

2. 버튼과 스태퍼를 하나의 함수로 구현을 해주었습니다. 개별적인 @IBAction으로 처리하는 것은 코드가 길어져서 하나로 합쳤는데, 가독성 측면에서는 버튼의 이름이 구분되어 보여지기에 가독성은 개별적인 것이 더 좋아보입니다. 비슷한 컴포넌트를 개별처리하는 것과 배열이나 함수 하나에 묶어서 관리하는 것 중에 어떤 것을 더 선호하시나요? 

**From. Jane(@jane1choi)**

1. `OrderViewController -> InventoryViewController` 화면전환 방식

사실…개인적인 의견이지만.. HIG를 기반으로 생각해봤을 때 modal 방식이 좀 더 적합하다고 생각하긴하는데,,, 프로젝트 파일에 기본으로 `navigation bar` 가 생성되어있었고, 가로 화면에서 modal로 다음화면을 present 해주니 presentationStyle 설정을 다른 방식으로 해주어도 뒷 화면을 아예 가려버리는 방식으로 화면전환이 되더라구요…그래서 일단 구현은 navigation 방식의 화면전환으로 처리해두었는데 해당 플로우에서 적합한 화면 전환 방식에 대한 리뷰어님의 의견도 궁금합니다!

참고한 HIG 파트 - Patterns > Modality

```
모달리티(modality)는 부모 뷰와의 상호 작용을 방지하고 거부하기 위한 명시적인 조치를 요구하는 별도의 전용 모드로 콘텐츠를 제시하는 설계 기법입니다.
```

기존의 플로우 혹은 상위 뷰와 연관되지 않는 독립된 작업을 하는 경우 modal 방식의 화면전환 사용한다고 문서에 제시되어있고

아이폰 기본 앱인 시계 앱의 알람 탭의 경우 + 버튼을 눌러 새로운 알람을 추가하는 작업에서 modal 방식이 사용되었습니다. (아마도 메인 화면과 독립된 작업이기 때문에)
해당 플로우와 비슷한 경우의 화면 전환이라고 생각해 의문이 생겼습니다!

1. 싱글톤 객체 의존성 주입

이전 PR에서 남겨주신 내용을 코멘트를 참고해서 init()에서 싱글톤 객체를 주입해서 객체 간의 결합도를 낮추어 보았는데요! `JuiceMaker` 구조체에서 한 방식과 같이 init 생성자의 파라미터로 객체 주입을 해주고 싶었는데, `UIViewController`를 상속받는  ViewController 에서는 init 생성자를 커스텀하니 fatal Error 가 떠서 찾아보니 스토리보드를 사용하는 경우 별도의 처리가 필요하다고 해서 이것저것 시도해보았는데 잘 안되어서,, 파라미터가 아닌 그냥 init() 함수 내에서 주입해주는 방식으로 구현해두었습니다.

사실 평소에 거의 스토리보드 없이 개발해왔어서 이 이슈를 처음 겪었는데 ,, 왜 스토리보드를 사용할 경우에만 에러가 발생하고, 해당 경우의 해결방법을 혹시 아신다면,,, 공유해주시면 감사하겠습니다,,,

- 기존에 required init? 과 함께 써준 코드

```
    init(fruitStore: FruitStore = FruitStore.shared) {
        self.fruitStore = fruitStore
        super.init(nibName: nil, bundle: nil)
    }

```

2023-12-14 18:42 UTC, junbangg requested changes
수고하셨습니다!
코드가 정말정말 직관적이고 깔끔해서 리뷰하기가 너무 편했어요👍감격..
마크 주석이랑 익스텐션 활용해서 코드 정리한것도 너무 좋아요..! 취향 저격 당했습니다
그리고 네이밍도 너무 좋아서 가독성도 아주아주 좋습니다~ 
박수👏👏👏👏👏

질문 주신거에 대한 답변 드릴게요!

>Juice 열거형 내부에 rawValue 처리를 아래 코드와 같이 연산 프로퍼티로 접근하게 만들어주었습니다. 말씀해주신게 이 방향이 맞을까요?

코멘트 남겼어요!

>버튼과 스태퍼를 하나의 함수로 구현을 해주었습니다. 각각의 컴포넌트들을 개별적인 @IBAction으로 처리하는 것은 코드가 길어져서 하나로 합쳤는데, 가독성 측면에서는 합친 것이 나빠진 것 같기도 합니다. 비슷한 컴포넌트를 개별처리하는 것과 배열이나 함수 하나에 묶어서 관리하는 것 중에 어떤 것을 더 선호하시나요?

이것도 코멘트 남겼어요!


> Modality에 대한 고민

아주아주 좋은 고민들만 골라 하면서 사시나보네요..?!
두분이서 함께 요 내용에 대해서 고민 해보셨을까요?? 아님 다른 분들 하고도??


저는 일단 동의해요! 
공식 문서에 있는 요 내용만 봐도 
모달로 써도 충분하다고 저는 생각합니다

- Provide options that let people confirm or modify their most recent action
- Help people perform a distinct, narrowly scoped task without losing track of their previous context

모달 방법으로 한번 리팩토링하면서 어떤 코드 변화들이 필요해지는지 한번 고민해보시면 큰 도움 될것 같습니다!

> 뷰컨 생성

두가지 방법이 생각나는데요 ! 
첫번쨰는 
https://developer.apple.com/documentation/uikit/uistoryboard/3213989-instantiateviewcontroller 
요걸 한번 봐보시면 좋을것 같고,,! 

또 다른 방법으로는 뷰컨에게 static 생성 메서드를 하나 만들어주는것입니다:)

두번째 방법을 한번 상상해보시는것도 좋을것 같아요
한번 고민해보시고 또 찾아주세요 저를!

대충 다음과 같은 느낌일겁니다

```
final class 만들고싶은ViewController: UIViewController {

    static func instantiate(샬라샬라) -> 만들고싶은ViewController {
        
     }
}
```

2023-12-14 18:42 UTC, junbangg commented on JuiceMaker/JuiceMaker/Controller/OrderViewController.swift
> +            })
아주 직관적이구만요~👍

2023-12-14 18:42 UTC, junbangg commented on JuiceMaker/JuiceMaker/Controller/OrderViewController.swift
> +            })
혹시 self capturing 에 대해서 공부 해보셨을까요?!

2023-12-14 18:42 UTC, junbangg commented on JuiceMaker/JuiceMaker/Extension/UIViewController + Extension.swift
> +                      completion: (() -> Void)? = nil) {
completion을 활용하셨는데 벌써 클로져에 대해서 공부를 하셨나요?!

2023-12-14 18:42 UTC, junbangg commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    }
👍

2023-12-14 18:42 UTC, junbangg commented on JuiceMaker/JuiceMaker/View/InventoryViewController.swift
> +    @IBOutlet private weak var strawberryQuantityLabel: UILabel!
갑자기 보면서 생각이 난건데요
IBOutlet 으로 하셨을까요??
strong이면 안되는걸까요??🤔 
한번 고민해보시면 좋을것 같아서 그냥 한번 던져봅니다 냅다~~

2023-12-14 18:42 UTC, junbangg commented on JuiceMaker/JuiceMaker/View/InventoryViewController.swift
> +    }
>버튼과 스태퍼를 하나의 함수로 구현을 해주었습니다. 각각의 컴포넌트들을 개별적인 @IBAction으로 처리하는 것은 코드가 길어져서 하나로 합쳤는데, 가독성 측면에서는 합친 것이 나빠진 것 같기도 합니다. 비슷한 컴포넌트를 개별처리하는 것과 배열이나 함수 하나에 묶어서 관리하는 것 중에 어떤 것을 더 선호하시나요?

아하 여기군요?🤔

2023-12-14 18:42 UTC, junbangg commented on JuiceMaker/JuiceMaker/View/InventoryViewController.swift
> +            components.stepper.value = Double(fruitStore.fruitContainer[fruit, default: 0])
지금도 이미 가독성이 너무 좋지만~ 
fruitStore.샬라샬라 값들을 상수로 빼서 이쁜 이름 하나씩 지어준 다음에 text와 value에 할당해주면 
더할나위 없을것 같습니당

2023-12-14 18:42 UTC, junbangg commented on JuiceMaker/JuiceMaker/View/InventoryViewController.swift
> +    }
여기 맞겠죠? 
저는 나쁘지 않다고 보는데요!
저도 이렇게 하는걸 원래 선호 했던거 같은데..요즘은 또 먼 미래에 코드를 볼 사람에 대한 생각을 하게 되더라고요🤔
먼 미래에 이 코드를 보는 사람은 과연 한눈에 이걸 알아볼까?? 알아보더라도 쉽게 쉽게 버그 대응 하거나 기능 추가를 할 수 있을까?요런 생각??
그래서 저의 생각은~(질문 주신 내용 처럼) 어쩌면 그냥 풀어서 개별적으로 IBAction 연결해주는것도 나쁘지 않다고 생각을 합니다~
(updateFruitQuantity 까지는 유지하되, 각 액션별로 연결을 해주는 방법이요! )
그런 심플한 방법이 어쩔때는 한눈에 보기도 쉽고, 관리 측면에서 더 좋을 수도 있거든요!

진짜 정답이 없는거 같긴한데🤔 굳이 또 근거를 하나 생각해보자면, 이 메서드가 하나의 일을 하는게 맞나? 라는 의문점을 한번 툭 던져 볼 수도 있을것 같아요! (SRP에 대한 이야기 입니다)

요런 고민 아주 좋습니다👍 정답은 없고 각자의 생각과 근거가 중요한 영역의 문제 같네요!

2023-12-14 18:42 UTC, junbangg commented on JuiceMaker/JuiceMaker/Extension/UIViewController + Extension.swift
> +    func presentAlert(title: String,
Alert 을 익스텐션으로 관리하기로 결정한 이유가 있을까요???(틀렸다는건 아님)

2023-12-15 01:19 UTC, jane1choi commented on JuiceMaker/JuiceMaker/Extension/UIViewController + Extension.swift
> +    func presentAlert(title: String,
사용자에게 어떤 메시지나, 때로는 경고 알림을 주는 기능을 하기도 하는 `alert` 같은 경우, 앱 전역에서 정말 많이 사용됩니다!!
네트워크가 상태가 안좋아서 request error가 나거나,, 특정 상황에서 유저에게 메시지를 보여줘야 하는 경우 등에 사용되기 때문에 사실 대부분의 ViewController가 alert을 띄워줄 수 있는 기능을 가져야 하는데, 모든 ViewController에 같은 코드를 메시지만 바꿔서 적어준다면,,, 굉장히 비효율적인 코드가 될 수 있기 때문에 ViewController의 기능 자체를 확장할 수 있도록 `alert`표시 메서드를 ViewContoller extension에 정의하여 중복되는 코드를 줄이는 방식을 택했습니다! 

결론: 중복되는 코드를 줄이는 방법에는 여러가지가 있겠지만, alert의 경우 `ViewControlle`r 의 추가적인 기능으로 가질 수 있도록 extension으로 관리하는 것이 적합하다고 생각했습니다!!!

2023-12-15 01:53 UTC, hemil0102 commented on JuiceMaker/JuiceMaker/Constant/Juice.swift
> +    }
안녕하세요 알라딘 좋은 내용 알려주셔셔 감사해요! 
저희 코드가 rawValue를 통해서 Juice 열거형의 case를 받아올 수 있도록 구현되어 있어서, 
알라딘이 처음에 질문을 주셨을 때 제가 아마 잘 받아들이지 못했나봐요.

```swift
@IBAction private func tapMakeJuiceButton(_ sender: UIButton) {
        guard let selectedButtonTitle = sender.currentTitle,
              let juice = Juice(rawValue: selectedButtonTitle) else {
            return
        }
```

위 코드에서 버튼이 눌렸을 때 sender.currentTitle으로 
사용자가 버튼을 눌렀을 때 만들어질 쥬스를 열거형 case로 구분하고 있어요. 
열거형을 활용하는 이유는 향후 쥬스의 확장이나 축소가 될 수 있고, 
또 임의로 누군가 다른 쥬스를 추가할 수도 있고,
없는 쥬스를 코드로 작성할 휴먼 에러가 있을 수도 있기에,
enum case를 통해 유지보수와 관리를 용이하게 하기 위함입니다. 

알라딘이 해주신 이야기를 분석해보면서
가독성 향상을 위해 아래 코드도 만들긴 했는데...
알라딘이 물어보는게 이게 아닌 것 같은데?
하면서 적용을 안했어요. 😵‍💫

```swift
static var SelectedJuice: (String) -> Juice? {
        return { title in
            switch title {
            case "딸기쥬스 주문":
                return .strawberry
            case "바나나쥬스 주문":
                return .banana
            case "키위쥬스 주문":
                return .kiwi
            case "파인애플쥬스 주문":
                return .pineapple
            case "딸바쥬스 주문":
                return .strawberryBanana
            case "망고쥬스 주문":
                return .mango
            case "망키쥬스 주문":
                return .mangoKiwi
            default:
                return nil
            }
        }
    }
```

또 가독성 향상을 위해서 
`Juice(rawValue: selectedButtonTitle)` 을 
`Juice(selectedFrom: selectedButtonTitle)` 과 같이 가독성을 향상 해주고 싶어서
열거형 내부에 Init()을 통해 코드를 만들기도 했었는데, 
이 경우에는 버튼이 눌릴 때 마다 초기화를 해주기 때문에 반영하지 않았습니다. 

혹시 저희의 취지를 보았을 때에도 위와 같이 rawValue에 대한 가독성이 좋지 않아서, 
코드를 변경하는게 좋다면 조언을 구하고 싶습니다. 
개취의 영역이지만, 알라딘이라면 어떻게 했을지가 궁금해요!

2023-12-15 02:03 UTC, jane1choi commented on JuiceMaker/JuiceMaker/Controller/OrderViewController.swift
> +    private lazy var labelsByFruit: [Fruit: UILabel] = [
해당 프로퍼티의 초기화 시점을 늦춰주기 위해서 사용했는데요!
`labelsByFruit` 프로퍼티는 해당 뷰컨에서 정의해둔 `UILabel` 타입의 `strawberryQuantityLabel`, `bananaQuantityLabel` .. 등의 프로퍼티를 사용하고 있습니다! 만약 `lazy`로 선언해두지 않을 경우, 모든 프로퍼티는 init()이 호출될 때 동시에 초기화 되는데, 사용하는 프로퍼티가 아직 초기화되지 않은 상태라면 해당 프로퍼티의 초기화에는 문제가 생기겠죠,, 
그래서 사용하는 프로퍼티가 초기화 된 이후에 해당 프로퍼티를 안전하게 초기화해주기 위해 `lazy`로 선언해주었습니다!

2023-12-15 02:05 UTC, jane1choi commented on JuiceMaker/JuiceMaker/Controller/OrderViewController.swift
> +            })
약한 참조로 바꿔주겠습니다!
확인 감사해요,,

2023-12-15 02:15 UTC, jane1choi commented on JuiceMaker/JuiceMaker/View/InventoryViewController.swift
> +    @IBOutlet private weak var strawberryQuantityLabel: UILabel!
스토리보드를 사용해 UI를 구성해서,,, label의 UI를 업데이트 해주기 위해 outlet으로 연결해주었는데요!!
IBOutlet으로 선언하지 않고 데이터를 이용해 UI를 업데이트 해줄 수 있는 방식이 있을까요???

2023-12-15 02:15 UTC, hemil0102 commented on JuiceMaker/JuiceMaker/Controller/OrderViewController.swift
> +    private lazy var labelsByFruit: [Fruit: UILabel] = [
지연 저장 프로퍼티(lazy stored property)는 처음 사용되기 전까지 초기값이 계산되지 않는 프로퍼티를 의미합니다. 
간단히 말해, 내가 만든 프로퍼티를 사용하기 전까지 메모리에 올려두지 않겠다는 의미입니다.

같은 맥락으로 프로젝트에서, 
lazy는 프로퍼티들의 메모리 생성 시점에서 초기화 충돌을 방지 하기 위해서 사용했습니다. 

labelsByFruit 딕셔너리가 초기화 되는 시점과 
@IBOutlet으로 연결된 Label과 기타 컴포넌트의 초기화 순서가 같은 필드에 있기에
메모리에서 생성되는 시점이 같습니다.

그러나 딕셔너리에 지정된 Label값은 값이 있어야 초기화 될텐데,
메모리 생성 시점이 같다면 무엇이 먼저 생성될지 알 수가 없기 때문에 에러가 발생합니다. 

따라서 lazy를 추가하여 딕셔너리가 참조되는 시점에 메모리에 올라가게 해주므로써 
@IBOutlet을 통해 Label이 먼저 생성되는 것을 보장하여 충돌을 방지합니다. 

실제로 lazy를 사용하지 않으면 아래와 같은 에러가 발생합니다. 
`Cannot use instance member 'strawberryQuantityLabel' within property initializer; property initializers run before 'self' is available`

2023-12-15 02:23 UTC, hemil0102 commented on JuiceMaker/JuiceMaker/Extension/UIViewController + Extension.swift
> +                      completion: (() -> Void)? = nil) {
해당 과정에서 아직 전문적으로 다루진 않았지만, 
저는 이전에 야곰 코드 스타터라는 곳에서 클로저는 코드의 블럭이며, 일급 객체라고 배웠습니다. 
함수의 파라미터로도 넘겨줄 수 있구요. 

너무 줄여쓰면 때론 맥락 파악이 어렵기는 하지만, 
클로저는 축약형으로 많이 활용되는데 스유에서도 기본적으로 많이 활용되는 것 같습니다.
따라서 익숙치 않아도 프로젝트에 활용하면서 연습하면 좋아보여 사용하려고 합니다.

2023-12-15 02:33 UTC, jane1choi commented on JuiceMaker/JuiceMaker/Extension/UIViewController + Extension.swift
> +                      completion: (() -> Void)? = nil) {
클로저를 한마디로 정의하자면 실행가능한 코드블럭인데 이제 이름이 없는... 친구...(==이름없는 함수)라고 할 수 있을 것 같습니다.
클로저는 일급 객체이기 때문에 함수 파라미터로 넘겨줄 수 있습니다!!

이부분의 경우, alert의 확인 버튼이 눌리거나, alert을 present 할 때 해주고 싶은 동작을 설정해주기 위해 파라미터로 클로저를 사용했는데요, 저희는 여러 뷰컨에서 alert을 상황에 맞게 범용적으로 사용해주려고 extension에서 alert 메서드를 정의해주었고, 사용해주는 쪽(alert을 present하는 뷰컨)에서 확인 버튼 액션이 발생할 경우 or 따로 설정해주고 싶은 동작(동작이 따로 필요없는 경우는 파라미터 자체를 써주지 않아도 되도록 default를 nil로 설정)을 메서드로 정의하고 이를 실행해주는 방식으로 클로저를 파라미터로 넘겨주는 방식을 택했습니다!!!

2023-12-15 02:34 UTC, jane1choi commented on JuiceMaker/JuiceMaker/Extension/UIViewController + Extension.swift
> +                      completion: (() -> Void)? = nil) {
@hemil0102 
https://janechoi.tistory.com/5
제가 정리해둔 글인데 추가적으로 공부할 때 참고해보시면 좋을 것 같아요!!!
이해가 잘 안가는 부분이 있다면 ,, 추가적으로 설명해드리겠습니다!

2023-12-15 06:42 UTC, hemil0102 commented on JuiceMaker/JuiceMaker/Controller/OrderViewController.swift
> +            })
적용 커밋(dedcfcc31ced57bf7a133e32aca613a9bafd45eb)

2023-12-15 06:43 UTC, hemil0102 commented on JuiceMaker/JuiceMaker/View/InventoryViewController.swift
> +            components.stepper.value = Double(fruitStore.fruitContainer[fruit, default: 0])
감사합니다~!
적용 커밋(be96e21a5a46c0a8ea4c182c231a274749b81b17)

2023-12-15 11:00 UTC, hemil0102 commented on JuiceMaker/JuiceMaker/Controller/OrderViewController.swift
> +            })
물어보셔서 공부하게 되었어요. 
레퍼런스 타입을 클로져 캡쳐 리스트에 복사해서 사용하면 강한 참조가 생겨나는데, 
이 경우 순환 참조가 일어날 수 있어서 weak self와 같은 형태로 약한 참조로 만들어주어 RC를 증가시키지 않게 해줍니다. 
추가로 캡처 리스트로 복사한 이후에 사용할 때 인스턴스가 사라졌을 수도 있어서 옵셔널 형태로 활용해야합니다.  
메모리 관련은 아직 잘 모르는데 덕분에 단편적이지만 더 보게 되었고 더 알아가야겠습니다. 감사합니다. 

[Strong Reference Cycles for Closures](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/automaticreferencecounting/#Strong-Reference-Cycles-for-Closures)

2023-12-15 12:44 UTC, hemil0102 commented on JuiceMaker/JuiceMaker/View/InventoryViewController.swift
> +    @IBOutlet private weak var strawberryQuantityLabel: UILabel!
기본 강한 참조(Strong)일 경우, 
UIViewController는 UIView와 뷰객체들(UIView 위에) 올라오는 요소들을 강하게 참조합니다. 
이 경우 UIViewController의 Reference Counting은 UIView에 1개, 뷰객체수만큼 형성됩니다. 

약한 참조(Weak)일 경우, 
UIViewController는 UIView를 강하게 참조하나,
뷰객체들은 약하게 참조하게 되며 RC수는 증가하지 않습니다. 

직접 UIView 위에 강한 참조와 약한 참조로 뷰객체를 각각 IBOutlet으로 생성하고, 
클래스에 deinit을 작성하여 메모리 해제 시점을 .removeFromSuperview() 를 통해 확인 할 경우, 

강한 참조는 UIViewController가 뷰객체를 갖고 있으므로 메모리 상에서는 해제가 되지 않으며, 
약한 참조는 UIViewController가 뷰객체를 소유하지 않으므로 메모리 상에서도 해제가 됩니다. 

추가로 메모리 부족 상황에서 UIViewController는 didReceiveMemoryWarning()라는 메서드를 호출한다고 합니다. 
이 경우 메서드는 부족한 메모리를 확보하기 위해 VC 내부의 View를 nil 처리합니다. 
View를 메모리에서 해제시키면서 View가 강하게 참조하는 뷰객체들도 메모리에서 해제시키기 위해서입니다. 
하지만 강한 참조 상황에서는 View가 해제되어도 UIViewController가 뷰객체를 강하게 참조하기 때문에, 
RC가 0으로 내려가지 못하고 메모리에서 해제되지 않습니다.

2023-12-18 00:25 UTC, junbangg commented on JuiceMaker/JuiceMaker/Constant/Juice.swift
> +    }
아아아아 ~ 이해했어요! 
init을 위한 rawValue 라는걸로 제가 생각을 못했었네요! 
제가 혼란을 드렸네요ㅎㅎ

2023-12-18 00:26 UTC, junbangg commented on JuiceMaker/JuiceMaker/Controller/OrderViewController.swift
> +    private lazy var labelsByFruit: [Fruit: UILabel] = [
좋습니다~👍

2023-12-18 00:28 UTC, junbangg commented on JuiceMaker/JuiceMaker/View/InventoryViewController.swift
> +    @IBOutlet private weak var strawberryQuantityLabel: UILabel!
>스토리보드를 사용해 UI를 구성해서,,, label의 UI를 업데이트 해주기 위해 outlet으로 연결해주었는데요!!
IBOutlet으로 선언하지 않고 데이터를 이용해 UI를 업데이트 해줄 수 있는 방식이 있을까요???

제가 쓴 코멘트에 일부분을 제가 누락 시켜버렸는데
`IBOutlet 으로 하셨을까요??` <- 왜 weak 으로 하셨을까요? 라는 뜻이었습니당

2023-12-18 00:29 UTC, junbangg commented on JuiceMaker/JuiceMaker/View/InventoryViewController.swift
> +    @IBOutlet private weak var strawberryQuantityLabel: UILabel!
RC 하면서 하나씩 따져보셨군요?? 너무 좋습니다👍👍

2023-12-18 00:33 UTC, junbangg approved these changes

2023-12-18 00:33 UTC, merged