쥬스자판기 [Step3] 미르, 미성
tasty-code/ios-juice-maker pull request #92
Opened 2023-12-13 12:17 UTC by mireu930

@FirstDo 
안녕하세요 두두! ` STEP3 `PR보내드립니다!
확인부탁드립니다!🙇

## 🤔고민이 되었던 점

### Stepper로 재고수정
- Stepper를 코드에 연결하여 @IBOulet을 추가하고 @IBAction 메서드를 추가하여 각각의 과일의 재고가 수정될수 있게 switch문을 이용하여 각각의 과일의 case에 접근할수 있도록 구현해줬습니다.
    ```swift
    @IBAction func stepperTapped(_ sender: UIStepper) {
        switch sender {
        case strawberryStepper:
            strawberryStockLabel.text = String(Int(sender.value))
        case bananaStepper:
            bananaStockLabel.text = String(Int(sender.value))
        case pineappleStepper:
            pineappleStockLabel.text = String(Int(sender.value))
        case kiwiStepper:
            kiwiStockLabel.text = String(Int(sender.value))
        case mangoStepper:
            mangoStockLabel.text = String(Int(sender.value))
        default:
            break
        }
    ```
### 재고수정화면 뷰 수정
- 재고수정화면이 명세서에서의 뷰가 기존에 했던 뷰와 달라서 수정을 진행해줬습니다. 수정한 재고수정뷰에 네비게이션바 레이어를 추가하여 그안에 Bar BUtton Item을 추가하여 명세서와 같은 화면을 구상해줬습니다. 다만, 여기서 기존의 화면전환방식인 네비게이션이 아닌 모달로 수정해줬습니다. 네비게이션으로 하게되면 메인화면에서 depth가 이어지기 떄문에 재고수정화면에서 왼쪽상단에 메인으로 넘어갈 수 있는 뒤로가기(?)버튼이 있어 모달방식으로 구현하여 뒤로가기 버튼에도 IBAction을 입혀 화면전환방식을 수정해줬습니다. 
```swift
@IBAction func closeTapped(_ sender: UIButton) {
        self.presentingViewController?.dismiss(animated: true)
        updateFruitStock()
    }

```

### 메인 화면 ↔ 재고수정 화면간 전환 시 값 전달을 위한 방법
저희는 값 전달을 위한 방법으로 `Singleton` 패턴을 사용하였습니다.
```swift
struct JuiceMaker {
    private(set) var fruitStore = FruitStore.shared
    
    // ...
}
```
- 싱글톤 패턴으로 `fruitStore` 가 유지됨으로써, 메모리상에 `fruitStore` 는 한 개만 존재할 수 있도록 하였습니다.
- 아울러 재고관리 화면에서 재고를 수정하는 경우 메인 화면(쥬스 주문 화면)에도 영향을 줄 수 있게 되었습니다.

#### ManageStockViewController
```swift
private func updateFruitStock() {
    fruitStore.fruitStock[.strawberry] = UInt(strawberryStockLabel.text ?? "")
    fruitStore.fruitStock[.banana] = UInt(bananaStockLabel.text ?? "")
    fruitStore.fruitStock[.pineapple] = UInt(pineappleStockLabel.text ?? "")
    fruitStore.fruitStock[.mango] = UInt(mangoStockLabel.text ?? "")
    fruitStore.fruitStock[.kiwi] = UInt(kiwiStockLabel.text ?? "")
}
```
- 재고관리 화면에서는 해당 메서드를 통해 수정한 재고가 화면이 닫히기 전에 `closeTapped()` 메서드 내에 `updateFruitStock()` 메서드를 호출하도록 하여, 싱글톤 `fruitStore` 내의 값을 수정하도록 하였습니다.
- 추후 개선 방안으로는 `@IBAction` 컬렉션을 사용하여 반복문을 통해 코드를 줄여볼 수도 있을 것 같습니다.

### 화면이 전환될 때 값을 갱신하는 절차
쥬스를 주문하는 화면의 경우 다음과 같은 함수를 통해 각 과일별 재고 Label을 수정할 수 있도록 해 주었습니다.
```swift
private func updateFruitStockLabel() {
    let stock = fruitStore.fruitStock.compactMapValues { String($0) }

    strawberryLabel.text = stock[.strawberry]
    // 타 Label도 같은 방법으로 수정...
}
```
이제 여기서 해결해야 할 문제는 다음과 같았습니다.
1. 화면이 처음 로드되었을 때, 초기 재고를 보여줄 수 있어야 한다.
2. 재고 수정 후 쥬스 주문 화면으로 돌아왔을 때, 재고 화면에서 수정한 값을 즉시 Label들에 갱신해 줄 수 있어야 한다.

저희는 각각의 문제를 `ViewController` 의 `viewDidLoad`, `viewWillAppear` 를 오버라이딩 하여 해결하였습니다.

#### JuiceOrderViewController
```swift
override func viewDidLoad() {
    super.viewDidLoad()
    updateFruitStockLabel()
}

override func viewWillAppear(_ animated: Bool) {
    super.viewWillAppear(animated)
    updateFruitStockLabel()
}
```
- `viewDidLoad` 를 통해 화면이 로드되는 즉시 과일 재고별 Label을 초기화하도록 설정
- `viewWillAppear` 를 통해 다른 `View` 에서 해당 메인 `View` 로 넘어오게 되면, 다시금 과일별 재고 Label을 갱신하도록 하였습니다. 

### Alert 처리 방안
이전 Step에서는 Alert를 처리할 때 `viewController` 를 받아서 화면 전환할 `View` 를 메서드 내에서 정하고 있었기 때문에 결합도가 굉장히 높은 문제가 있었습니다. 또한, 일반적인 `Alert` 객체를 생성하기에는 내부에 `Action` 등을 생성하는 로직이 외부의 `AlertType` 에 의존하여 생성이 되고 있었으므로 이것을 다음과 같은 방향으로 변경하였습니다.
```swift
class Alert {
    static func createAlert(title: String? = nil, message: String? = nil, okTitle: String, okAction: @escaping () -> Void) -> UIAlertController {
        let vc = UIAlertController(title: title, message: message, preferredStyle: .alert)
        let okAction = UIAlertAction(title: okTitle, style: .default) { _ in okAction() }
        vc.addAction(okAction)
        return vc
    }
}
```
- `createAlert()` 메서드를 통하여 일반적인 `Alert` 객체를 생성할 수 있도록 하였습니다.
- 일반적인 `Alert` 객체의 경우 최소한 '확인' 버튼 1개는 존재하므로, `okTitle` 을 받도록 했습니다.
- 화면 이동을 위한 코드는 탈출 클로저를 통해 메서드를 호출한 곳에서 클로저 내에 동작을 정의할 수 있도록 했습니다.

#### Alert 클래스의 사용 방법
```swift
private func order(juice: Juice) {
    do {
        // ...
    } catch {
        // ...
        let alert = Alert.createAlert(message: JuiceMakerError.outOfStock.description, okTitle: "예") {
            self.moveToManageStockView() // 더 이상 VC를 넘겨주지 않아도 됨.
        }
        // ...
    }
}
```
- 조언해주신 개선 방향으로 메서드를 바꾸어 `Alert` 객체를 통해 원하는 경고창을 만들고, 이후에 할 동작은 `Alert` 클래스가 모르더라도 사용하는 쪽에서 원하는 동작을 클로저를 통해 할 수 있게 되었습니다.

## 🙏조언을 구하고 싶은 점 

### 데이터 전달 방식에 대한 고려점
저희가 이번 `STEP 3` 의 요구 사항을 구현하면서 화면 이동 시에 데이터를 전달하는 방법으로 `Singleton` 패턴을 사용하였습니다.

싱글톤 패턴의 구현은 간단하지만 해당 프로젝트에서 원하는 화면 공유 방식의 정답은 싱글톤 패턴이 아닌 다른 패턴이었나 싶어 PR 리뷰를 요청드리기 전에 델리게이션 패턴 등으로 변경을 할까 고려하였으나, 아직 해당 패턴에 대한 내용을 충분히 숙지하고있지 않아서 현재 가능한 수준에서 구현을 하게 되었습니다.

iOS 현업에서는 어떠한 경우 보편적으로 싱글톤(예. 네트워킹 객체에)이 사용되고, 어떤 경우 델리게이션(예. 텍스트필드의 내용을 버튼에게 위임하는 등)을 사용하는지 조언을 얻고 싶습니다.

2023-12-13 23:55 UTC, FirstDo requested changes
안녕하세요! 마지막 스텝 고생하셨습니다 :)

## 질문에 대한 답변입니다

### 데이터 전달 방식에 대한 고려점

우선 Singleton 패턴과 delegate 패턴은 다릅니다

Singleton 패턴은 여러곳에서 동일한 객체를 사용하기 위한 방법입니다.
반대로 delegate 패턴은 이벤트 callback을 위한 패턴입니다.

만약 이프로젝트에 delegate 패턴을 사용했다면
재고를 수정한뒤, 두번째 화면에서 뷰를 업데이트 시키기 위해 viewwillappear를 명시적으로 사용했는데, 델리게이트 패턴을 사용하면 그럴 필요가 없겠죠?

다만 구현에 정답은 있는 편이 아니며, 지금 하신 방법도 맞는 방법이라고 말씀드리고 싶네요,

동일한 객체를 여러군데에서 사용해야할때는 싱글톤 패턴을 씁니다.
사실 싱글톤 패턴보다는 DI(의존성 주입) 을 통해 동일한 객체를 쓰는 편이지만, 
프로젝트를 진행하면서 차차 배우셔도 될것 같아요 :)

ex) DB등

싱글톤 패턴이 왜 anti 패턴이라고 불리는지도 한번 알아보시면 좋을것 같네요
쓰지말라는 말이아니라, 단점을 알고 사용하면 더 좋을것 같아요

어떤일을 위임할때는 델리게이트 패턴을 씁니다
커스텀 delegate 패턴을 만들때는 보통 이벤트 콜백을 위해서겠죠

ex) UITableview, UICollectionView, UITextField 등등

UITableView의 delegate를 VC로 설정하면,
cell을 눌렀을때, cell을 선택했을때 등등 무슨일을 할 지를 VC가 처리해 줄 수 있습니다.
이번프로젝트에서는 과일 재고를 바꿨을때, 첫번째 화면의 UI가 자동으로 업데이트 되도록 할 수 있었겟네요.

고생하셨습니다 :)

2023-12-13 23:55 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
> +    }
```swift
`updateFruitStockLabel`을 viewDidLoad, viewWillAppear에서 해준다면,
처음 뷰가 나타날때 두번호출되지 않을까요??

View Life Cycle이 어떤식으로 동작하는지 한번 더 확인할 필요가 있을것 같네요!
그리고 override 키워드를 쓰는 이유는 무엇인지, 안쓰면 어떻게 될까요?
```

2023-12-13 23:55 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Controller/ManageStockViewController.swift
> +        self.presentingViewController?.dismiss(animated: true)
애플에서는 닫으려는 TargetVC가 dismiss를 호출하는것을 추천하고 있습니다 
(이렇게 해도 동작은 잘 합니다)

`self.dismiss(animated: true)`

2023-12-13 23:55 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Model/Alert.swift
> +class Alert {
좋네요!
더 확장하면 two button alert까지도 만들 수 있을것 같아요.
alert인지 actionsheet인지도요!

기회가 되면 하고 아니면 다른 프로젝트에서 시도해보시는게 좋겠습니다 :)

+

class로 쓸 이유가 없다면, struct or enum의 값타입이 좋겠습니다

2023-12-13 23:55 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Model/NameSpace.swift
> +}
좋은 방법입니다.
이 형태에서 개선을 한다면, 객체를 생성할수 없게 enum으로 만드는게 좋겠습니다

좀 더 개선을 한다면
VC가 100개가 되면, 100개의 namespace를 다 관리해야하는데 실수할 여지가 너무 많겠죠?

이런 방법이 있습니다.

스토리 보드의 Identifier는 클래스 이름과 동일하게 설정한후
ex) "JuiceMakerVC"

```swift
extension UIViewController {
  static var identifier: String {
    return String(describing: self)
  }
}

let vc = storyboard.instantiateViewController(identifier: JuiceMakerVC.self) as? JuiceMakerVC
```

역시 여유가 되면 적용해보고 아니면 다른 프로젝트에서 해보는게 좋겠습니다 :)

2023-12-13 23:55 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Controller/ManageStockViewController.swift
> +    @IBAction func stepperTapped(_ sender: UIStepper) {
IBAction 매서드도 private을 붙일 수 있습니다!
+ Stepper를 누르는 시점에 재고가 바뀌는건 어떨까요?

사실 구현하신 방법도 문제는 없지만,  addFruit, subtractFruit 함수가 놀고있네요

2023-12-13 23:55 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Controller/ManageStockViewController.swift
> +    }
이런식으로 객체 내부의 프로퍼티에 직접접근하는것보다는
우리가 만들어놨던 addFruit, subtractFruit 매서드를 이용하여, Stepper를 누르는 시점에 바꿔주는게 좋을것 같아요

2023-12-13 23:55 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Controller/ManageStockViewController.swift
> +    private func checkFruitsStock() {
요친구도 UI를 업데이트 하는 친구인데, 이름이 약간 안맞는것 같아요


보통
`setup(UI)`, `configure(UI)` 등등을 씁니다.
이름은 자유에요..!

2023-12-13 23:55 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Controller/ManageStockViewController.swift
> +    @IBOutlet weak var mangoStepper: UIStepper!
IBOutlet도 private을 붙일 수 있습니다

2023-12-13 23:55 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
> +}
좋습니다!

다만 모든 `UIViewController`가 `moveToManageStockView`를 알고있을 필요가 있을까요?
UIViewController의 extension으로는 부적절해 보입니다

2023-12-15 06:53 UTC, mireu930 commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
> +    }
`viewDidLoad`를 `viewWillApear`로 수정해줬습니다. 
`override`의 경우 `UIViewController`를 상속하고 있어 슈퍼클래스인 `UIViewController`를 `JuiceOrderViewController`에 맞게 재정의하고 싶을때 사용해줍니다. override를 안쓰게 된다면 컴파일에러가 납니다.

2023-12-15 06:53 UTC, mireu930 commented on JuiceMaker/JuiceMaker/Controller/ManageStockViewController.swift
> +        self.presentingViewController?.dismiss(animated: true)
해당 부분 `self.dismiss(animated: true)`로 수정해줬습니다.

2023-12-15 06:56 UTC, mireu930 commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
> +}
말씀주신대로 모든 `UIViewController`가 알필요없다고 생각하여 `JuiceOrderViewController`로 수정해줬습니다.

2023-12-15 07:22 UTC, crisine commented on JuiceMaker/JuiceMaker/Model/NameSpace.swift
> +}
[해당 커밋](https://github.com/tasty-code/ios-juice-maker/commit/fb19c4d30b52d46f3d1d0d441503ee901c528948) 에서 다음과 같이 수정하였습니다.

# `UIViewController` 의 `Extension` 그룹 생성 
> /Extensions/UIViewControllerExtension.swift

```swift
import UIKit

extension UIViewController {
  static var identifier: String {
    return String(describing: self)
  }
}
```

## VC의 `identifier` 계산 속성을 사용한 예
```swift
guard let vc = storyboard?.instantiateViewController(identifier: ManageStockViewController.identifier) as? ManageStockViewController else {
    let alert = Alert.createAlert(message: JuiceMakerError.cannotLoadManageStockView.description, okTitle: "확인") { }
    present(alert, animated: true)
    return
}
```
- VC의 `identifier` 를 가져와 `as` 캐스팅으로 캐스팅되지 않는 경우 유효하지 않은 View로 판단하여 Alert를 띄워주도록 했습니다.
- `guard let` 바인딩을 통해 옵셔널 언래핑도 하고, 언래핑이 불가능한 (유효하지 않은 View) 경우의 처리까지 겸했습니다.
- StoryBoard 상의 id는 ViewController의 이름과 동일하게 설정해 주었습니다.

2023-12-15 07:28 UTC, mireu930 commented on JuiceMaker/JuiceMaker/Model/Alert.swift
> +class Alert {
two button alert으로 만든다는 것이 어떤의도인지 파악이 어려운데, 간단하게 설명부탁드려도 될까요?
[해당커밋](https://github.com/tasty-code/ios-juice-maker/pull/92/commits/145faf977d906cad933b142e2abeb2be87d8c77a)에서 구조체로 수정해줬습니다.

2023-12-15 07:30 UTC, mireu930 commented on JuiceMaker/JuiceMaker/Controller/ManageStockViewController.swift
> +    private func checkFruitsStock() {
[해당커밋](https://github.com/tasty-code/ios-juice-maker/pull/92/commits/5d9941f9b246b86bce090c40b7006f712dcb4be2)에서 configureUI로 수정해줬습니다.

2023-12-15 07:30 UTC, mireu930 commented on JuiceMaker/JuiceMaker/Controller/ManageStockViewController.swift
> +    @IBOutlet weak var mangoStepper: UIStepper!
[해당커밋](https://github.com/tasty-code/ios-juice-maker/pull/92/commits/5d9941f9b246b86bce090c40b7006f712dcb4be2)에서 접근제어해줬습니다.

2023-12-15 07:30 UTC, crisine commented on JuiceMaker/JuiceMaker/Controller/ManageStockViewController.swift
> +    @IBAction func stepperTapped(_ sender: UIStepper) {
[해당 이슈](https://github.com/tasty-code/ios-juice-maker/pull/92#discussion_r1425994856) 와 묶어서 해결할 수 있는 부분이어서 [해당 커밋](https://github.com/tasty-code/ios-juice-maker/commit/fb19c4d30b52d46f3d1d0d441503ee901c528948) 에서 다음과 같이 해결하였습니다 😄 

# `FruitStore` 내에 `updateFruitStock()` 메서드를 생성
```swift
func updateFruitStock(fruit: Fruit, num: UInt) {
    fruitStock[fruit] = num
}
```
- 기존의 `add()`, `subtract()` 메서드들을 사용하려면 스텝퍼에서 `+`, `-` 각각 어느 것이 눌렸는지에 대한 판단이 추가로 이행된 후 호출되어야 하므로 현재 수량을 기준으로 `update()` 를 해주는 메서드를 생성하였습니다.

## `ManageStockVC` 에서의 활용
```swift
@IBAction private func stepperTapped(_ sender: UIStepper) {
    switch sender {
    case strawberryStepper:
        fruitStore.updateFruitStock(fruit: .strawberry, num: UInt(sender.value))
        // ...
    }
    configureUI()
}
```
- 스텝퍼가 눌릴 때마다, 스텝퍼가 가진 값을 `updateFruitStock()` 메서드로 보내어 값을 수정할 수 있도록 했습니다.
- 가능하다면 `stepper` 의 `identifier` 에 `Fruit` 타입을 넣을 수 있다면 switch 문도 줄일 수 있을 것 같다는 생각이 들었습니다 😄

2023-12-15 07:31 UTC, crisine commented on JuiceMaker/JuiceMaker/Controller/ManageStockViewController.swift
> +    }
[해당 이슈](https://github.com/tasty-code/ios-juice-maker/pull/92#discussion_r1427643080) 에서 같이 해결하였습니다! 🥳

2023-12-15 07:35 UTC, crisine commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
> +}
[해당 커밋](https://github.com/tasty-code/ios-juice-maker/commit/fb19c4d30b52d46f3d1d0d441503ee901c528948) 에서 다음과 같은 방향으로 수정하였습니다!

## 메서드를 `JuiceOrderViewController` 안으로 이동
```swift
final class JuiceOrderViewController: UIViewController {

    // Some other functions ...

    private func moveToManageStockView() {
        // ...
    }
}
```
- 모든 `UIViewController` 들이 `moveToManageStockView()` 를 알 필요는 없으므로, `JuiceOrderVC` 안으로 이동하였습니다

2023-12-16 13:31 UTC, mireu930 commented
UML 작성한 부분도 확인 부탁드립니다!
![클래스다이어그램](https://github.com/tasty-code/ios-juice-maker/assets/148876644/3b62f4a3-d31f-4c84-9d04-ca38a2e1aad3)

2023-12-17 10:23 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Model/NameSpace.swift
> +}
좋습니다!
근데 사실 이것도 길죠?

검색해보면 더 여러가지 방법들이 있으니 다음프로젝트에 적용해 보시는것도 좋을것 같아요 :)

2023-12-17 10:33 UTC, FirstDo approved these changes
고생하셨습니다! 추가코맨트는 딱히 없습니다.
UML 확인했습니다 :)

2023-12-19 00:19 UTC, FirstDo requested changes
두분 고생하셨습니다.
델리게이트 패턴으로 바꿔보니 어떤가요?
수정해야 할 부분들 남겨두었으니
코맨트 확인부탁드려요!

그리고 전체적으로 폴더링을 다시해야될것 같습니다
View, Controller, Model, Extensions으로 나누셨는데

Apple의 Cocoa MVC에서는 View와 VC가 사실 하나입니다.
그래서 View, Controller를 구분할 필요가 없어보여요.

#### AppDelegate, SceneDelegate는 VC가 아닙니다
App 같은 폴더를 만들어서 따로 놔두는게 좋을것 같아요

#### Assets은 View가 아닙니다
Assets, LaunchScreen등은 Resources 등의 폴더에 따로 보관하는게 좋아보여요

#### JuiceMaker, FruitStore, Alert등은 모델보다는 Service에 가깝습니다
따로 서비스 폴더를 만드는게 좋아보입니다

그리고 폴더링에는 정답이 없지만, 자기만의 기준이 있으면 좋습니다.
지금처럼 나누면 나중에 VC가 100개가되면 ViewController 폴더에 100개가 박히겠죠?
저는 보통 도메인 별로 나누는 편입니다.

ex) 다른 기능들이 추가됬다고 가정 (게임, 건강등)
[]는 폴더,, -는 계층구조를 의미

[Scene]
- [Juice]
- - [View]
- - - JuiceOrderVC
- - - ManageStockvC
- - [Model]
- - - Juice
- - - Fruit
- - - JuiceMakerError

- [Game]

- [Health]

약간 이런느낌으로요??
지금 바꾸라는 말은 아니에요
지금은 프로젝트가 작아서 의미는 없으나 나중에 프로젝트가 커진다면 유용할거에요

2023-12-19 00:19 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
> +        vc.modalPresentationStyle = .fullScreen
한줄씩 띄운 특별한 이유가 있을까요?
vc의 프로퍼티에 값 할당하는 과정인데 그냥 다 붙여써도 좋을것 같습니다

2023-12-19 00:19 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
>          updateFruitStockLabel()
이제 viewwillappear에서 `updateFruitStockLabel`를 해줄 필요가 없습니다

JuiceMakerVC가 처음생성될때 viewdidload에서 해주시고,
UI업데이트 역시 델리게이트 매서드에서 해주세요

2023-12-19 00:19 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
> +extension JuiceOrderViewController: Delegate {
extension으로 분리한것 좋습니다
재고업데이트만 하는것이 아닌, UI업데이트도 여기서 진행해주세요.
그리고 5번쓸 필요없이, 반복문을 사용하면 한번에도 가능할것 같습니다.

2023-12-19 05:38 UTC, mireu930 commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
> +        super.viewWillAppear(animated)
`super`는 슈퍼클래스를 나타태는 키워드이며, 슈퍼클래스의 구현을 호출해야 할 필요가 있는 경우에만 붙여야 합니다.
다만, 현재와 같은 상황에선 쓰지 않아도 구현이 되어 굳이 쓸필요가 없다고 생각합니다!

2023-12-19 05:44 UTC, mireu930 commented on JuiceMaker/JuiceMaker/Model/Alert.swift
>  struct Alert {
현재프로젝트에선 `Alert`인스턴스를 할수 있는 기능이 없습니다. 
말씀주신 대로 코드를 모르는 분들이 보면 인스턴스를 생성하는 실수를 범할수 있다고 생각하여 `enum`으로 바꿔 인스턴스를 생성하지 못하게 막아줬습니다!

2023-12-19 05:53 UTC, mireu930 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
>      init() {}
`JuiceOrderViewController`에 `JuiceMaker` 인스턴스를 생성하여 `JuiceMaker`에서 `FruitStore`의 프로퍼티와 메서드에 접근하기 위해 인스턴스를 생성하였고, 이니셜라이저는 객체를 초기화하게 되면 원하는 초기상태로 설정할수 있기때문에 이니셜라이저를 만들어줬습니다.

2023-12-19 05:56 UTC, mireu930 commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
> +        vc.modalPresentationStyle = .fullScreen
vc의 프로퍼티에 값 할당하는 과정을 직관적으로 보이기 편하게 띄어주긴했는데, 붙어주는게 좋을거 같아보여 붙여줬습니다!

2023-12-19 08:38 UTC, mireu930 commented on JuiceMaker/JuiceMaker/Model/Alert.swift
> +    static func createAlert(title: String? = nil, message: String? = nil, okTitle: String, okAction: @escaping () -> Void) -> UIAlertController {
`@escaping`의 경우 함수가 종료되도 클로저는 종료되지 않고 진행될수 있도록 사용하는 키워드입니다. 프로젝트의 경우 쥬스주문을 하면 쥬스가 나오고, 재고가 부족하면 `order`메서드는 종료되고 재고수정화면으로 넘어갈 수 있도록 키워드가 사용됩니다.

2023-12-19 09:15 UTC, mireu930 commented on JuiceMaker/JuiceMaker/Controller/ManageStockViewController.swift
> +    var delegate: Delegate?
weak을 쓰는 것은  강한 참조 순환을 방지하기 위함인데,  객체가 서로를 강한 참조하고 있는 상태이라면 이로 인해 메모리 누수가 발생할 수 있습니다. Delegate 패턴에서는 주로 객체 간의 상호 작용을 위해 delegate를 사용하므로 이런 순환을 피하기 위해 weak키워드를 사용해 메모리누수를 방지할수 있습니다.

2023-12-19 13:24 UTC, mireu930 commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
>          updateFruitStockLabel()
해당부분 JuiceMakerVC에선 viewdidload해주고, 델리게이트 메서드에 viewWillAppear를 해줬는데, 이렇게 이해한게 맞을까요?
```swift
protocol Delegate: AnyObject {
    func fruitStock(fruitStock: [Fruit: UInt])
    func viewWillAppear(_ animated: Bool)
}
```

2023-12-20 23:42 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
>      init() {}
아무 의미가 없어보여서  `init() { }`를 여쭤본거였어요.

쓰나안쓰나 현재는 동일하게 동작할껄요?
구조체는 맴버와이즈 이니셜라이저를 자동으로 만들어줍니다

2023-12-21 00:13 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
> +            guard let fruit = Fruit(rawValue: index) else { return }
이 줄이 왜 필요한가요??
저는 필요없어보이는데, 작성하신 이유가 궁금합니다 ㅎㅎ

2023-12-21 00:13 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
> +    func viewAppearing() {
삭제해주세요
디코에 코맨트 자세히 남겼습니다..!

2023-12-21 00:13 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
> +protocol JuiceOrderViewControllerDelegate: AnyObject {
델리게이트에 관련해서는 디코에 코맨트를 자세히 남겼으니 반영 부탁드립니다 :)

2023-12-21 00:13 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
>      override func viewDidLoad() {
super 매서드를 빼란뜻이 아니엿습니다..!!
물론 빼고 정상적으로 동작하는것 처럼 보입니다.
그런데, super.viewDidLoad에서는 뭔가 뷰의 로드에 필요한 작업들을 수행해 줄텐데, 우리 마음대로 빼버려도 되는걸까요..?
무조건 써야합니다

2023-12-21 00:13 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Controller/ManageStockViewController.swift
> +    @IBAction private func stepperTapped(_ sender: UIStepper) {
이 시점에서, delegate 매서드가 호출되는게 자연스럽습니다

2023-12-21 03:11 UTC, mireu930 commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
> +            guard let fruit = Fruit(rawValue: index) else { return }
Fruit의 rawValue를 fruitStock 배열의 순서를 알아야 메인VC에서 재고VC로 넘어갈수 있다고 생각해서 작성했었는데, 수정해보니 쓸 필요없이 배열의 key값만 넣어줘도 수정된 재고가 잘넘어 재고VC에 잘 넘어가는 것을 알 수 있었습니다!

2023-12-21 03:14 UTC, mireu930 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
>      init() {}
아.. 잘못이해했네요.. 말씀주신대로 구조체는 멤버와이즈 이니셜라이저를 자동을 생성해 따로 쓸 필요없었습니다! 하여 이니셜라이저는 삭제하였습니다!

2023-12-21 03:19 UTC, mireu930 commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
>      override func viewDidLoad() {
[해당커밋](https://github.com/tasty-code/ios-juice-maker/pull/92/commits/399f7f7c2e7bfa147f2c3dd96a0f6d15a1a56f21) 에서 수정해줬습니다!

2023-12-21 03:37 UTC, mireu930 commented on JuiceMaker/JuiceMaker/Controller/ManageStockViewController.swift
> +    @IBAction private func stepperTapped(_ sender: UIStepper) {
[해당커밋](https://github.com/tasty-code/ios-juice-maker/pull/92/commits/40391aab5ce8e6bb49f776a97aad2bb95d24c5e3)에서 stepper가 눌릴때마다 호출될수 있도록 구현해줬습니다.

2023-12-21 03:38 UTC, mireu930 commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
> +protocol JuiceOrderViewControllerDelegate: AnyObject {
[해당커밋](https://github.com/tasty-code/ios-juice-maker/pull/92/commits/40391aab5ce8e6bb49f776a97aad2bb95d24c5e3)에서 `UIViewControllerDelegate`로 네이밍 수정해줬습니다!

2023-12-21 03:40 UTC, mireu930 commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
> +    func viewAppearing() {
[해당커밋](https://github.com/tasty-code/ios-juice-maker/pull/92/commits/40391aab5ce8e6bb49f776a97aad2bb95d24c5e3)에서 메서드는 삭제하고, `fruitStock`메서드의 경우`fruitStockDidChange`로 네이밍 수정해줬습니다.

2023-12-21 03:50 UTC, mireu930 commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
>          updateFruitStockLabel()
[해당커밋](https://github.com/tasty-code/ios-juice-maker/pull/92/commits/40391aab5ce8e6bb49f776a97aad2bb95d24c5e3)에서 수정했습니다!

2023-12-21 13:30 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
> +protocol JuiceOrderViewControllerDelegate: AnyObject {
ManageStockViewControllerDelegate 여야 할 것 같네요...!
위임을 부탁하는 객체의 이름으로 써주는게 맞습니다

2023-12-21 13:41 UTC, FirstDo approved these changes
두분 진짜 너무 고생많으셨습니다..!!!

2023-12-22 00:46 UTC, mireu930 commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
> +protocol JuiceOrderViewControllerDelegate: AnyObject {
[해당커밋](https://github.com/tasty-code/ios-juice-maker/pull/92/commits/931a435517dd54d8a5938c6635094352adb7caf4)에서 네이밍 수정해줬습니다!

2023-12-22 01:38 UTC, merged