쥬스메이커 [STEP 2] Nnn, Sam
tasty-code/ios-juice-maker pull request #96
Opened 2023-12-14 06:12 UTC by Nnn-Park

@songda515
안녕하세요, Nnn, Sam입니다!!
STEP 2 작업완료 후 PR올립니다!

## 📝 PR Point

### 1. 오류처리 
딸기주스 버튼 조작방법으로 오류처리를 합니다. 과알쥬스를 만들 과일이 부족할 경우 재고 업데이트 여부를 묻는 알림이 표시되도록 하였습니다.

### 2 네비게이션
세컨드 뷰 컨트롤러로의 네비게이션 구현. 이 세컨드 뷰 컨트롤러를 사용하여 과일 재고에 대한 업데이트를 수행하도록 하였습니다.

### 3. 사용자 지정
 UIAlert Controller의 actionYes 버튼에서  텍스트 색상이 빨간색으로 변경되게 하였습니다.

## 1) 메인화면
![Simulator Screenshot - iPhone 14 Pro Max - 2023-12-14 at 15 02 51](https://github.com/Nnn-Park/Swift_Study/assets/75471842/22f9eded-5dd5-4aa1-b915-a546bed14399)

## 2) 주문완료 화면
![Simulator Screenshot - iPhone 14 Pro Max - 2023-12-14 at 15 02 55](https://github.com/Nnn-Park/Swift_Study/assets/75471842/9d162565-3fc5-4118-84ed-b061ce8b94c7)

## 3) 재고부족 시 Alert 화면
![Simulator Screenshot - iPhone 14 Pro Max - 2023-12-14 at 15 03 01](https://github.com/Nnn-Park/Swift_Study/assets/75471842/9b102c93-98f2-4636-a63c-cbe16693efea)

## 4) Alert에 예 버튼 누른 후 화면 전환
![Simulator Screenshot - iPhone 14 Pro Max - 2023-12-14 at 15 03 06](https://github.com/Nnn-Park/Swift_Study/assets/75471842/40c2c378-6f61-4b33-8b4f-652ed50eb615)

## 추가
이번 프로젝트를 진행하며 깃 사용 미숙으로 커밋단위와 커밋기록이 꼬여버렸습니다. 이를 통해 깃 사용법을 더 명확하게 숙지하고 프로젝트를 계속 진행할 수 있도록 하겠습니다.

2023-12-15 14:44 UTC, songda515 requested changes
Nnn, Sam 쥬스메이커 STEP2 고생하셨습니다! 🥳
화면 이동과 Alert Controller 의 활용을 잘 해주신것 같아요 👍 

Git 을 사용하면서 오류가 발생했다고 하셨는데, 이것도 협업 프로그래밍에서 꼭 필요한 경험이라고 생각합니다 😁 잘 해결해나가는 방법을 배우신거같네요.
다만 지금 `JuiceMaker/JuiceMaker/Model/FruitStore.swift` 파일에서 컨플릭이 발생하고 있어 이부분을 확인해주셔야 할것 같습니다!

2023-12-15 14:44 UTC, songda515 commented on JuiceMaker/JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        uiUpdate()
함수의 경우 네이밍을 동사 형태로 지어주는것이 더 적절할 것 같아요 🙂!

2023-12-15 14:44 UTC, songda515 commented on JuiceMaker/JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +//    func useQuantity(fruit: Fruit, quantity: Int, name: String) -> [Fruit] {
불필요한 주석은 제거해주시는게 좋을것 같습니다!

2023-12-15 14:44 UTC, songda515 commented on JuiceMaker/JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +class FruitStore {
<img width="456" alt="스크린샷 2023-12-15 오후 11 27 13" src="https://github.com/tasty-code/ios-juice-maker/assets/25761841/eb098197-e1c0-4a97-98a1-23835bc356fe">

FruitStore 에서 컨플릭이 발생하고 있는데 확인해보셔야 할 것 같아요 🙏

2023-12-15 14:44 UTC, songda515 commented on JuiceMaker/JuiceMaker/JuiceMaker/Model/Fruit.swift
> +    var name: String {
지난번 코멘트 반영해주신것 확인했습니다 😊

2023-12-15 14:44 UTC, songda515 commented on JuiceMaker/JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        case 0:
버튼을 연결할때 sender 의 tag를 활용해주셨네요! 
버튼에 대해서 한번에 처리할 수 있는 장점이 있겠네요 🙌

2023-12-15 14:44 UTC, songda515 commented on JuiceMaker/JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    @IBAction func strawberryJuice(_ sender: UIButton) {
요 함수의 네이밍에 대해 조금 더 고민해주시면 좋을것 같아요.
- 딸기쥬스만 만드는 버튼으로 보이진 않네요 🤔 
- 버튼이 어떤 상태가 될 때 해당 메소드가 호출하게 되는걸까요?

2023-12-15 14:44 UTC, songda515 commented on JuiceMaker/JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +            present(successAlert, animated: true)
Alert Controller 를 잘 활용해주셨네요 👍

2023-12-15 14:44 UTC, songda515 commented on JuiceMaker/JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        self.navigationController?.pushViewController(vc2, animated: false)
해당 메소드에서는 `pushViewController` 를 사용해서 화면을 열어주고고, 위의 AlertController 는 `present` 를 사용한것으로 보이는데 각각 선택한 설명해주실 수 있을까요? 👀

2023-12-15 14:44 UTC, songda515 commented on JuiceMaker/JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    static let first = UIStoryboard(name: "Main", bundle: .main)
스토리보드의 이름에 대해 상수로 빼서 관리하는 점 좋은것 같아요 👍 
`withIdentifier: "secondVC"` 같은 형태도 자주 쓰이는것 같은데, 요것도 상수로 관리하면 더 생산성이 향상될것 같네요!

2023-12-18 05:59 UTC, ParkChanH commented on JuiceMaker/JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        uiUpdate()
uiUpdate -> updateStockLabel 로 변경하여 UI 내에서 과일 재고 수량을 업데이트한다는 것을 더욱 명확히 표현해주었습니다.!!

2023-12-18 06:00 UTC, ParkChanH commented on JuiceMaker/JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    @IBAction func strawberryJuice(_ sender: UIButton) {
strawberryJuice -> orderJuice 로 변경하여 사용자의 주스 주문을 처리하는 함수의 역할을 반영 하였습니다!

2023-12-18 06:00 UTC, ParkChanH commented on JuiceMaker/JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        self.navigationController?.pushViewController(vc2, animated: false)
이 부분은 재고관리 버튼을 눌렀을때 stockUpdateAction로 화면을 코드로 나타내주게 하기위해 구현 했던 점 입니다.

이는 학습차원에서 스토리보드, 코드 여러방법으로 사용해보며 학습하기 위함이었습니다.

2023-12-18 06:01 UTC, ParkChanH commented on JuiceMaker/JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    static let first = UIStoryboard(name: "Main", bundle: .main)
Step3 에서는 해당 내용을 반영하겠습니다!!

2023-12-18 06:29 UTC, Nnn-Park commented on JuiceMaker/JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +class FruitStore {
해결했습니다!
해결 과정은 원본 저장소에 동기화를 해서 pull 받아 컨플릭을 확인하여 해결 후 다시 push하고 원본 저장소 동기화를 다시 해제 해줬습니다!

2023-12-18 12:38 UTC, songda515 commented on JuiceMaker/JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        self.navigationController?.pushViewController(vc2, animated: false)
오호 넵 ㅎㅎ 다양하게 사용해보신것 좋네요! present, push 화면 전환의 차이에 대해 학습해보면 좋을것 같습니다~

2023-12-18 12:39 UTC, songda515 approved these changes
코멘트 반영해주시고, 컨플릭 해결해주신것 확인해서 머지하겠습니다!
Step 3 도 화이팅하세요 😄!!

2023-12-18 12:40 UTC, merged