쥬스메이커 [STEP2] 루피, 홍
tasty-code/ios-juice-maker pull request #99
Opened 2023-12-14 08:07 UTC by ujhong7

## 

담당 리뷰어 : @GREENOVER (green)
팀원: @kimdj1102 (loffy), @ujhong7 (hong)
  

## 코드에 관하여 

### 순서도 
![image](https://github.com/tasty-code/ios-juice-maker/assets/108393988/d9eeb4b5-9866-4a46-a472-da19e85f8826)

---
## 기능구현
### ViewController의 화면 전환 방법
 1. ViewController의 View 바꿔치기
- 하나의 뷰 컨트롤러 안에 두개의 루트 뷰를 준비한 후, 상태에 따라 뷰를 적절히 교체하는 방식
- 메모리 overflow 위험이 있기 때문에 좋은 방법이 아님
 2. ViewController가 다른 ViewController 호출
- 현재의 뷰 컨트롤러에서 이동할 대상 뷰 컨트롤러를 직접 호출해서 화면을 표시하는 방식 (Present)
- present를 이용한 화면전환은 기존의 뷰 컨트롤러를 그대로 둔 채, 그 위세 새로운 뷰 컨트롤러의 화면을 덮는 방식.
3. NavigationViewController를 사용하여 화면 전환
- ViewController가 새로 생길때마다 Stack에 쌓이는 방식
4. 화면 전환용 객체 Segue 사용
- storyboard상에서 경로가 시각적으로 나타남
- ViewController에 대한 정보를 몰라도 화면 전환 가능

 위 4가지의 방법 중 2번과 3번 방법 중 한가지를 사용하는 것으로 고민해 본 후, 비교를 해보았습니다.

### 이동 방식은 어떤 방식이 적절할까요? 
 navigation vs modal
 navigation 방식은 화면 간의 계층 구조를 가질 때 유용하며, 주로 탐색 기능이 필요한 경우에 사용됩니다. modal 방식은 주로 사용자에게 추가 정보를 입력하거나, 알림을 보여주는 등의 목적으로 활용됩니다. 때문에 modal 방식을 채택했습니다.

```swift
func dataToStockManagementViewController() {
        if let stockManagementVC = self.storyboard?.instantiateViewController(withIdentifier: "StockManagementViewController") as? StockManagementViewController {
            stockManagementVC.receivedData = juiceMaker.fruitStore.inventory
            let stockManagementNavigationController = UINavigationController(rootViewController: stockManagementVC)
            self.present(stockManagementNavigationController, animated: true, completion: nil)
        }
    }
```

1. `storyboard`를 사용하여 "StockManagementViewController"라는 식별자identifier를 가진 뷰 컨트롤러를 인스턴스화합니다.
2. `StockManagementViewController`의 `receivedData` 프로퍼티에 현재 `JuiceMakingViewController`의 `juiceMaker.fruitStore.inventory` 데이터를 할당합니다.
3. `StockManagementViewController`를 `UINavigationController`에 넣어서 생성하고, `present` 메서드를 사용하여 화면을 전환합니다.
코드를 통해 화면을 직접 생성하고 전환하는 방법입니다.

### 쥬스 주문 버튼 터치 시
 쥬스 재료의 재고가 있는 경우 : 버튼입력 → 주스 제조 → (성공) 얼럿 띄우기 → 예 → 얼럿 닫힘 → 레이블 수량 변화
 쥬스 재료의 재고가 없는 경우 : 버튼 → 주스 제조 → (실패) 얼럿 띄우기 → 예/아니오 → “예” 선택시 재고수정 화면이동 
 재고수정 화면이동 방법: UIAlertAction의 handler에 화면이동 함수 transitionToStockManagement() 추가
 재고수정 화면이동 함수: transitionToStockManagement() 내부에서 dataToStockManagementViewController() 함수 호출

### 재고수정 버튼 터치 시 
 재고수정 버튼 stockChangeButton에 액션을 달아서 셀렉터를 통해 stockChangeButtonTapped 함수 호출 stockChangeButtonTapped 함수 내부에서 dataToStockManagementViewController 함수 호출 

### 과일쥬스를 제조하여 과일의 재고가 변경되면 화면의 적절한 요소에 변경사항을 반영
- **JuiceMakingViewController**

수량 변화 감지 옵저버 생성
```swift
NotificationCenter.default.addObserver(self, selector: #selector(didChangeFruitsAmount(_:)), name: Notification.Name("fruitsAmountDidChange"), object: nil)
```
수량 변화 레이블에 나타냄
```swift
@objc func didChangeFruitsAmount(_ notification: Notification) {
        //  notification.userInfo -> Notification 객체에 연결된 사용자 정의 정보를 나타냄 (사용자 정의 데이터를 저장하는 Dictionary)
        guard let userInfo = notification.userInfo, let fruitInfo = userInfo as? [Fruit : Int] else {
            return
        }
        // 수량 변환에 따른 레이블 변화
        self.showNumberOnLabel(fruits: fruitInfo)
    }
```
**NotificationCenter**를 통한 옵저버 패턴에서는 **비동기적으로 데이터의 변화를 감지**하고 처리합니다. 이는 **화면의 변화를 다시 그릴 필요 없이** **데이터의 변경을 즉시 반영**할 수 있도록 해줍니다.

- **FruitStore**

수량 변화 NotificationCenter를 통해 알리는 함수 

```swift
private func sendNotification(about fruit: Fruit, number: Int) {
        NotificationCenter.default.post(name: Notification.Name("fruitsAmountDidChange"), object: nil, userInfo: [fruit: number])
    }
```

재고 감소 함수: 새로운 수량을 계산하고, 해당 과일의 재고를 업데이트한 후에 sendNotification 함수를 호출하여 수량 변화를 NotificationCenter로 알립니다.

```swift
private func decreaseStock(of fruit: Fruit, by number: Int, from numberOfFruitExist: Int) {
        let valueAfterChange = numberOfFruitExist - number
        inventory[fruit] = valueAfterChange
        sendNotification(about: fruit, number: valueAfterChange)
    }
```

재고가 감소되면 해당 알림을 받은 옵저버들은 즉시 화면 등을 업데이트할 수 있습니다.

2023-12-14 08:49 UTC, GREENOVER requested changes
@ujhong7 @kimdj1102 
안녕하세요 ㅎㅎ 두분 스텝 2 너무 고생 많으셨습니다!!
이번 스텝 VC 다루는 일이 많으셨을텐데 아주 잘 구현해주셨네요 👍
코드 상에서 로직적인 부분이나 뷰와 바인딩되는 부분들은 모두 괜찮아서 주로 한번 더 생각해볼 포인트들 혹은 조금 더 가독성이 좋아질 수 있을 부분들을 위주로 리뷰 드려봤습니다 🙇🏻
***
### 칭찬 드리고 싶은 부분
- 전체적으로 로직이 모난데 없이 잘 짜여져 있네요 💯
- 노티피케이션 활용 굿!! 💯
- 이전 스텝 1의 부분도 같이 반영되면서 보다 훨씬 더 코드가 단단해졌어요! 💯
***
### 보완되면 좋을 포인트
- 어느정도 리뷰에 남겨봤지만 한번 더 강조하고 싶은 포인트는 바로 extension으로 관심사 별 분리를 아주 잘 해주셨지만, 어떤 역할의 메서드들이 모인건지에 대해 주석을 남겨두면 처음 보는 동료들도 빠르게 이해할 수 있을것 같아요..!
점점 기능이 많아질수록 ViewController가 커질것이고 현재 코드 컨벤션 상 extension 분리도 많아질때 주석을 통해 조금 더 가독성을 높여가고 또한 원하는 부분으로 주석을 통해 빠르게 Xcode에서 탐색/이동도 가능하여 한번 적용해보면 어떨까 싶습니다 🙋🏻
`// MARK: - 초기 과일수량 설정` 요런식으로 말이죠..!ㅎㅎ
- 코멘트엔 없지만 하나 궁금했던 부분은 App/SceneDelegate 파일이 Controller에 있는 이유가 궁금했습니다ㅎㅎ
두분은 어떠한 이유로 넣어주셨을까요~?!
***
스텝 2 너무 잘 수행해주시고 또한 PR 본문에서 고민하시면서 사용하신 이유들도 너무 잘 작성해주셔서 리뷰하는데 도움이 많이 되었습니다!
생각 정리를 두분은 아주 잘하시는것 같아요 👍
한번 더 체크할 부분들 확인 후 넘어갈 수 있도록 우선 Request Changes로 드리겠습니다!
너무 수고많으셨고 언제든 머지 요청 혹은 재리뷰 요청 해주시면 감사하겠습니다~

2023-12-14 08:49 UTC, GREENOVER commented on JuiceMaker/JuiceMaker.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 15.0;
배포 타겟을 변경하신 이유가 궁금합니다 🙋🏻

2023-12-14 08:49 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/JuiceMakingViewController.swift
> +    @IBOutlet var orderStrawberryButton: UIButton!
Button의 프로퍼티는 XXButton으로 네이밍을 가져가고 Label은 Label없이 xx로 네이밍을 가져가시는 이유가 궁금합니다 🙋🏻
잘못되었다는 소리 전혀 아니고 어떤 포인트를 기준으로 네이밍을 지으시는지 정말 궁금해서 여쭤봅니다ㅎㅎ

2023-12-14 08:49 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/JuiceMakingViewController.swift
> +class JuiceMakingViewController: UIViewController {
해당 쥬스메이커VC는 이후 상속 받을 경우가 존재할까요~?
만약 없다고 판단된다면, final 키워드에 대해서도 알아보면 좋을것 같습니다 🙋🏻

2023-12-14 08:49 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/JuiceMakingViewController.swift
> +    let juiceMaker = JuiceMaker(fruitStore: FruitStore())
private해도 되지 않을까요~?

2023-12-14 08:49 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/JuiceMakingViewController.swift
> +        super.viewDidLoad()
왜 override를 해야하며 super.viewDidLoad()가 없으면 실제 어떤일이 일어나나요~?

2023-12-14 08:49 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/JuiceMakingViewController.swift
> +    }
LGTM 👍👍👍

2023-12-14 08:49 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/JuiceMakingViewController.swift
> +    func setUp(number: Int, on label:UILabel) {
주로 setup은 한단어로 표현되기에 setup이 조금 더 적절하지 않을까 싶습니다..!

2023-12-14 08:49 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/JuiceMakingViewController.swift
> +extension JuiceMakingViewController {
포함된 메서드들이 private해도 된다면 `private extension`으로 사용해도 좋을것 같아요..!

현재 의도에 따라 extension을 나눠서 표현하고 있는데 어떤 메서드끼리 묶어서 extension을 했는지 MARK 주석을 활용해 남겨두면 더 가독성이 좋을것 같습니다..!

2023-12-14 08:49 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/JuiceMakingViewController.swift
> +extension JuiceMakingViewController {
여기 속한 메서드들도 모두 private해도 되지 않을까요~?

2023-12-14 08:49 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/JuiceMakingViewController.swift
> +            result = .failure(description: message)
조금 더 명확한 워딩으로 예외처리를 해보면 어떨까요 🤔

2023-12-14 08:49 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/JuiceMakingViewController.swift
> +    func dataToStockManagementViewController() {
메서드명만으론 어떤 역할을 하는지 조금 유추하기가 힘든것 같은데 조금만 더 명확하게 변경해볼 수 있을까요..!?

2023-12-14 08:49 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/StockManagementViewController.swift
> +    var receivedData: [Fruit:Int] = [:]
받은데이터도 맞긴하지만 변수명만으론 어떤 데이터인지 구분하기 힘들지 않을까요..?
추후 이렇게 받아오는 데이터가 2~3개 된다면 네이밍 리팩토링이 필수가 될것 같아서 지금 명확히 변경해놓아도 좋을것 같습니다 🙋🏻

2023-12-14 08:49 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/StockManagementViewController.swift
> +
한줄 개행이 더 된것 같습니다 🙋🏻

2023-12-14 08:49 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Info.plist
>  		<string>UIInterfaceOrientationLandscapeLeft</string>
Portrait이 원래 없었던걸로 기억하는데 맞을까요..!?
만약 맞다면 Landscape말고 Portrait도 지원하게 설정하신 이유가 궁금합니다 🙋🏻

2023-12-18 02:13 UTC, kimdj1102 commented on JuiceMaker/JuiceMaker.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 15.0;
저희가 뷰 컨트롤러 간에 화면전환 방식을 modal 방식으로 설정을 했는데, 가로모드에서는 modal로 나타나는 화면이 전체화면으로 밖에 안되서 그것보다 좀 작게 설정하기 위해  pageSheet을 사용하고, pageSheet의 모양과 동작을 관리하는 `UISheetPresentationController `을 사용했습니다.  하지만 ios15버전 이후부터 지원가능하다고 해서 배포 타켓을 변경하게 되었습니다..😂

![image](https://github.com/tasty-code/ios-juice-maker/assets/12614929/f01ceedc-8a78-4198-b8c9-cf1a5bf6d3a6)

2023-12-18 02:14 UTC, kimdj1102 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakingViewController.swift
> +    @IBOutlet var orderStrawberryButton: UIButton!
버튼이나 라벨 등 명확한 기능을 가지고 있는 프로퍼티는 뒤에 기능을 명시하려고 했는데, Label은 깜빡하고 넣지 못했던 것 같습니다. 수정하겠습니다!

2023-12-18 02:15 UTC, kimdj1102 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakingViewController.swift
> +    func setUp(number: Int, on label:UILabel) {
네 수정하겠습니다!

2023-12-18 02:20 UTC, kimdj1102 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakingViewController.swift
> +extension JuiceMakingViewController {
넵 private extension으로 사용할 수도 있다는 걸 알게됬습니다 감사합니다!

저희도 헷갈려서 주석을 달고싶었지만... 주석금지라는 제약사항이 있어서 달지 못했습니다 🥲

2023-12-18 02:21 UTC, kimdj1102 commented on JuiceMaker/JuiceMaker/Info.plist
>  		<string>UIInterfaceOrientationLandscapeLeft</string>
이것저것 테스트해보다가 설정을 다시 못 바꿨던것 같습니다 다시 변경하겠습니다 😀

2023-12-18 03:26 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/JuiceMakingViewController.swift
> +extension JuiceMakingViewController {
아하 주석금지라는 제약이 있었군요 ㅠㅠ 
아쉽지만, 제약사항을 따르시죠ㅎㅎ..

2023-12-18 08:36 UTC, kimdj1102 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakingViewController.swift
> +extension JuiceMakingViewController {
혹시 몰라서 버디한테 여쭤봤는데 말씀하신 MARK 주석은 사용가능하다고 하시네요...^^:  한번 추가해보도록 하겠습니다!! ㅎㅎ

2023-12-19 01:55 UTC, ujhong7 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakingViewController.swift
> +        super.viewDidLoad()
super.viewDidLoad()를 호출하지 않으면, 부모 클래스인 UIViewController의 viewDidLoad() 메서드가 실행되지 않습니다. 부모 클래스의 메서드를 호출하지 않으면, 부모 클래스의 초기화 코드가 실행되지 않아 예상치 못한 문제가 발생할 수 있습니다.

2023-12-19 01:57 UTC, ujhong7 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakingViewController.swift
> +            result = .failure(description: message)
"잘못된입력입니다."로 변경했습니다!

2023-12-19 02:00 UTC, kimdj1102 commented
Q: 코멘트엔 없지만 하나 궁금했던 부분은 App/SceneDelegate 파일이 Controller에 있는 이유가 궁금했습니다ㅎㅎ
두분은 어떠한 이유로 넣어주셨을까요~?!

A: SceneDelegate과 AppDelegate이 Controller에 잘못 들어갔습니다... 폴더 밖으로 꺼내두었습니다 !

2023-12-19 06:33 UTC, GREENOVER approved these changes

2023-12-19 06:33 UTC, merged